### ISSUE TITLE
Official Debugging Instructions (Informational) 

### ISSUE THREAD

**Issue by sferich888** [openshift/installer#1003]
# Version

Not Important

# Platform (aws|libvirt|openstack):

Not Important

# What happened?

Red Hat Support has moved the content (that you have currently) in: https://github.com/openshift/installer/blob/v0.8.0/docs/user/troubleshooting.md to https://access.redhat.com/articles/3780981#debugging-an-install-1 and will begin using the KB system to capture and record troubleshooting steps as we find them and work with customers on their issues. 

# What you expected to happen?

This is an informational issue as any updates to the pages you make here; will now start to drift from what we tell customers, as we directly support them. 

# How to reproduce it (as minimally and precisely as possible)?

Not Important

# Anything else we need to know?

Please consider referencing this KB article in your guide (where people can get official support, with a subscription) or as changes are made to this page raise them with some in support to make sure the corresponding official guides/docs get updated as well. 

# References

Feel free to close this issue as this is purly an informational issue.

**Comment by wking** [comment]
> ... https://access.redhat.com/articles/3780981#debugging-an-install-1 ...

Are there particular subscriptions we should reference when pointing people at that page?  I don't seem to have access to it myself.

> ... as changes are made to this page raise them with some in support...

What channel should we use for this?

**Comment by wking** [comment]
> I don't seem to have access to it myself.

This is what I see now:

![screenshot from 2019-01-11 11-21-57](https://user-images.githubusercontent.com/209920/51069258-36566500-15e0-11e9-945e-c0317bd3ffc3.png)

I need meta-support about accessing support ;).

> > ... as changes are made to this page raise them with some in support...
>
> What channel should we use for this?

From out-of-band discussion, the recommended channel is mentioning @sferich888 when we change the content (maybe like [this][1]).  Did you want to be notified as these landed?  It might be easier if I just ping you when we cut releases, and you can check something like [this][2] for the diff?  Unfortunately, the fragment doesn't seem to take me to quite the place I'd like, but if you click the "Files changed" tab and scroll down to `docs/user/troubleshooting.md`, you can see the changes to that file between v0.8.0 and v0.9.0.

[1]: https://github.com/openshift/installer/pull/967#issuecomment-453719047
[2]: https://github.com/openshift/installer/compare/v0.8.0...v0.9.0#diff-8309613435473cd584c37f4498f82cf3L37

**Comment by sferich888** [comment]
I updated our guides to align with these changes.
