### ISSUE TITLE
Is it possible to customize master api port upon install

### ISSUE THREAD

**Issue by jianlinliu** [openshift/installer#1015]
# Version

```console
$ openshift-install version
v0.8.0-master-8-g713289e20bd6afccb06f2e4ff7ed89d2483fac9a
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

Upon install, I did not see any place to customize default master api port (6443).

# What you expected to happen?

There is a way to allow user customized master api port.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by wking** [comment]
We are unlikely to make this customizeable without a strong argument to motivate it, but see [here][1] about potentially changing the default.  Let's continue the discussion over there.

/close

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1663453
