### ISSUE TITLE
How to change KUBE_MAX_PD_VOLS for master controllers?

### ISSUE THREAD

**Issue by hongkailiu** [openshift/installer#1021]
This is a question, NOT a bug report.

This is the solution for 3.10 and 3.11:
Edit the static pod yaml file for controller with:
```
   env:
   - name: KUBE_MAX_PD_VOLS
     value: "60" 
```

I wonder how to achieve it on 4.0?

**Comment by DanyC97** [comment]
my 0.02$ this is not an installer question as far as i can see, my suggestion will be to try and ask https://groups.google.com/forum/#!forum/openshift-4-dev-preview as that is the forum for 4.0 dev phase

**Comment by hongkailiu** [comment]
Thanks for the pointer. @DanyC97

**Comment by hongkailiu** [comment]
For tracking
https://groups.google.com/forum/#!topic/openshift-4-dev-preview/96pQXW3v1zo
