### ISSUE TITLE
"Pull Secret" prompt doesn't actually allow "? for help"

### ISSUE THREAD

**Issue by danwinship** [openshift/installer#1029]
# Version

```console
$ openshift-install version
openshift-install v0.9.0-master-12-g6880b3e44647d4882db23d371d02620e06617884
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

I was prompted:

```console
? Pull Secret [? for help]
```
and typed "`?`", but instead of getting help, it just accepted the "`?`" as part of the input

(I had just skimmed quickly over the cloud.openshift.com install instructions and didn't see "pull secret" in any of the bold section headers and was confused because I had remembered it being really obvious, so I thought maybe the pull secret had been moved somewhere else. After failing to get help from the installer, I looked at the instructions a little more carefully and noticed the [really obvious] "Copy Pull Secret" link.)

**Comment by wking** [comment]
And also for `Cluster Name`.  File [an upstream issue][1] with a minimal reproducer?

[1]: https://github.com/AlecAivazis/survey/issues

**Comment by danwinship** [comment]
Oh, so I guess the issue is that for menu-type options the `?` acts immediately, but for string-type options you have to type Enter after the `?` before it will show the help. So it's behaving as intended, just not how I expected.
