### ISSUE TITLE
Timestamp installer output

### ISSUE THREAD

**Issue by sttts** [openshift/installer#1067]
Debugging/Unterstanding issues in CI is often unnecesserarily complicated because one cannot relate installer output to other logs because the former lack timestamps.

**Comment by wking** [comment]
Dup of#1026.  Comment with reasoning there if you think we should reopen.

/close

**Comment by sttts** [comment]
@wking if one knows that the log file with timestamps exists, there is no issue. Maybe a hidden file is not discoverable enough?

**Comment by wking** [comment]
We document the log file [here][1].  Do you think we should shuffle those docs?

[1]: https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources

**Comment by sttts** [comment]
Why is the file hidden? Why not just `<install-dir>/install.log`?

**Comment by sttts** [comment]
Or even reference it in the terminal output. "Full logs can be found at ...."

**Comment by wking** [comment]
Previous hidden-file discussion in #876.  Continue there?
