### ISSUE TITLE
[libvirt] Failed to get console route for v0.10.0 tag and ImagePullBackoff for clusterapi-manager-controllers

### ISSUE THREAD

**Issue by praveenkumar** [openshift/installer#1078]
# Version

```console
$ openshift-install version
bin/openshift-install v0.10.0
```

# Platform (aws|libvirt|openstack): 

**libvirt**

# What happened?

Installer is failed to get the `console route` and exit after 10 mins due to `context deadline exceeded`.

# What you expected to happen?

Installer should able to create the cluster without any issue.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ env TF_VAR_libvirt_master_memory=8192 TF_VAR_libvirt_master_vcpu=4 ./bin/openshift-install create cluster --dir=test --log-level debug
[...]
INFO Waiting up to 10m0s for the openshift-console route to be created... 
DEBUG Still waiting for the console route...       
DEBUG Still waiting for the console route...
[...]
DEBUG Still waiting for the console route...       
FATAL waiting for openshift-console URL: context deadline exceeded 

$ export KUBECONFIG=/home/prkumar/work/github/practice/go/src/github.com/openshift/installer/test/auth/kubeconfig

$ kubectl get pods --all-namespaces
NAMESPACE                                    NAME                                                         READY     STATUS             RESTARTS   AGE
kube-system                                  etcd-member-crcont-master-0                                  1/1       Running            0          17m
openshift-apiserver-operator                 openshift-apiserver-operator-7fc9bc59d9-wpbw6                1/1       Running            0          16m
openshift-apiserver                          apiserver-j6g59                                              1/1       Running            2          10m
openshift-cluster-api                        cluster-autoscaler-operator-7f74bdf7f9-26tsp                 1/1       Running            0          12m
openshift-cluster-api                        clusterapi-manager-controllers-db4fbd5fc-f7x6x               2/4       ImagePullBackOff   0          11m

$ kubectl logs clusterapi-manager-controllers-db4fbd5fc-f7x6x -n openshift-cluster-api -c nodelink-controller | less
[...]
W0116 08:26:01.170879       1 main.go:379] no matching machine found for node
I0116 08:26:01.170935       1 main.go:312] finished syncing node, duration: 207.751µs
I0116 08:26:01.170988       1 main.go:296] Error syncing node crcont-master-0: no matching machine found for node: crcont-master-0
I0116 08:26:04.914170       1 main.go:147] updating node: crcont-master-0
I0116 08:26:04.914282       1 main.go:310] syncing node
I0116 08:26:04.914334       1 main.go:368] searching machine cache for IP match for node
W0116 08:26:04.914373       1 main.go:379] no matching machine found for node
I0116 08:26:04.914410       1 main.go:312] finished syncing node, duration: 129.151µs
I0116 08:26:04.914447       1 main.go:296] Error syncing node crcont-master-0: no matching machine found for node: crcont-master-0

$ kubectl logs clusterapi-manager-controllers-db4fbd5fc-f7x6x -n openshift-cluster-api -c machine-healthcheck
[...]
I0116 08:25:58.615279       1 machinehealthcheck_controller.go:73] Reconciling MachineHealthCheck triggered by /crcont-master-0
W0116 08:25:58.615409       1 machinehealthcheck_controller.go:92] No machine annotation for node crcont-master-0
I0116 08:26:08.629294       1 machinehealthcheck_controller.go:73] Reconciling MachineHealthCheck triggered by /crcont-master-0
W0116 08:26:08.629354       1 machinehealthcheck_controller.go:92] No machine annotation for node crcont-master-0
I0116 08:26:18.649707       1 machinehealthcheck_controller.go:73] Reconciling MachineHealthCheck triggered by /crcont-master-0
W0116 08:26:18.649756       1 machinehealthcheck_controller.go:92] No machine annotation for node crcont-master-0
```

# Anything else we need to know?

Looks like the issue with `clusterapi-manager-controllers-db4fbd5fc-f7x6x` pod since it is in `ImagePullBackoff` state and logs shows that it is not able to identify the master node.

# References

- enter text here.

**Comment by johwes** [comment]
I have the same issue, it fails to pull the image doing an "oc describe pod <name>" shows the following.

  Normal   Scheduled  46m                 default-scheduler      Successfully assigned openshift-cluster-api/clusterapi-manager-controllers-db4fbd5fc-bmlhw to ocp-master-0
  Normal   Pulled     46m                 kubelet, ocp-master-0  Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3d1b7554af827639b86372f1d9c0fbdbe609c878381f40c433a1f788ec0fe5a7" already present on machine
  Normal   Started    46m                 kubelet, ocp-master-0  Started container
  Normal   Created    46m                 kubelet, ocp-master-0  Created container
  Normal   Pulled     46m                 kubelet, ocp-master-0  Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3d1b7554af827639b86372f1d9c0fbdbe609c878381f40c433a1f788ec0fe5a7" already present on machine
  Normal   Started    46m                 kubelet, ocp-master-0  Started container
  Normal   Created    46m                 kubelet, ocp-master-0  Created container
  Normal   Pulling    46m (x2 over 46m)   kubelet, ocp-master-0  pulling image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225"
  Warning  Failed     46m (x4 over 46m)   kubelet, ocp-master-0  Error: ImagePullBackOff
  Normal   BackOff    46m (x4 over 46m)   kubelet, ocp-master-0  Back-off pulling image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225"
  Warning  Failed     46m (x2 over 46m)   kubelet, ocp-master-0  Error: ErrImagePull
  Warning  Failed     46m (x2 over 46m)   kubelet, ocp-master-0  Failed to pull image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225": rpc error: code = Unknown desc = Error reading manifest sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225 in registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905: unauthorized: authentication required
  Normal   BackOff    36m (x39 over 46m)  kubelet, ocp-master-0  Back-off pulling image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225"
  Warning  Failed     1m (x188 over 46m)  kubelet, ocp-master-0  Error: ImagePullBackOff

**Comment by praveenkumar** [comment]
I tried today with master branch and didn't see this issue but then again with 0.10.0 tag it is occurring so might be something to do with the way we tag the payload for this tag?

**Comment by johwes** [comment]
I also rebuilt from 0.9.1 tag and got it working with that.

**Comment by crawford** [comment]
0.10.0 is a special release. It is the beta1 build, which means that it targets a different set of content than 0.9.1. I also noticed that the libvirt container isn't pushed to quay (unlike its AWS counterpart), so I think it was just missed in the release process.

**Comment by praveenkumar** [comment]
> I also noticed that the libvirt container isn't pushed to quay (unlike its AWS counterpart), so I think it was just missed in the release process.

@crawford thanks, that explain why it is happening with only `libvirt`. Do we have any plan to push those missing libvirt containers to quay registry?

**Comment by bbrowning** [comment]
I just wanted to add that my team is hitting this issue as well and are stuck on 0.9.1 for now until we find a way to run 0.10.x locally with libvirt.

**Comment by e-minguez** [comment]
Same issue with 0.10.1, console is not deployed because there are no workers available... because the clusterapi-manager-controllers is not up... because it is trying to pull the image from an internal registry which I cannot access:
```
5m          5m           2         clusterapi-manager-controllers-db4fbd5fc-nhqnb.157c848781ca4d28   Pod          spec.containers{controller-manager}            Warning   Failed              kubelet, minwi-master-0                                                             Failed to pull image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225": rpc error: code = Unknown desc = Error reading manifest sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225 in registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905: unauthorized: authentication required
```

**Comment by wking** [comment]
This is a release issue, the installer just pins the update payloads the release folks push to quay.io.  It's being tracked [here][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1666561

**Comment by eivantsov** [comment]
@wking any update on this one? I am using the latest master and have exactly the same issue

**Comment by smarterclayton** [comment]
You must have a pull secret to api.ci in order to access libvirt, because the installer team has chosen not to build libvirt for OCP.

**Comment by eivantsov** [comment]
@smarterclayton thanks. How do I get one?

**Comment by smarterclayton** [comment]
If you're not in the openshift GitHub organization, you can't get one. 

libvirt isn't supported in the official installer.  You need to use the origin variant or not use libvirt.

**Comment by eivantsov** [comment]
@smarterclayton what's Origin variant? Flavor isn't that important to me. I need a local 4.0 cluster :)

**Comment by smarterclayton** [comment]
git clone openshift/installer, run hack/build-go.sh, and that's origin

**Comment by wking** [comment]
> git clone openshift/installer, run hack/build-go.sh, and that's origin

For libvirt, you need to [set `TAGS=libvirt` when building][1].

[1]: https://github.com/openshift/installer/blob/v0.11.0/docs/dev/libvirt-howto.md#build-and-run-the-installer

**Comment by wking** [comment]
> Flavor isn't that important to me.

Unless you take steps to preserve the public (I think?) OKD builds at [registry.svc.ci.openshift.org/openshift/origin-release][1], they're going to get garbage-collected after a few days.  Master installer builds (currently the only way to get libvirt compiled in) point there by default, so your cluster should run fine for a few days and then probably start to die as the backing images get garbage-collected.  Should be fine for dev-work (the libvirt target), but it's not going to work for long-running tasks out of the box.

[1]: https://origin-release.svc.ci.openshift.org/

**Comment by eivantsov** [comment]
@smarterclayton @wking but this is exactly what I am doing:

```
eugene@ivantsoft ~/go/src/github.com/openshift/installer ((HEAD detached at v0.10.0)) $ TAGS=libvirt hack/build.sh
+ RELEASE_IMAGE=quay.io/openshift-release-dev/ocp-release:4.0.0-0.1
+ RHCOS_BUILD_NAME=47.249
+ minimum_go_version=1.10
++ go version
++ cut -d ' ' -f 3
+ current_go_version=go1.10.3
++ version 1.10.3
++ IFS=.
++ printf '%03d%03d%03d\n' 1 10 3
++ unset IFS
++ version 1.10
++ IFS=.
++ printf '%03d%03d%03d\n' 1 10
++ unset IFS
+ '[' 001010003 -lt 001010000 ']'
+ LAUNCH_PATH=/home/eugene/go/src/github.com/openshift/installer
++ dirname hack/build.sh
+ cd hack/..
++ go list -e -f '{{.Dir}}' github.com/openshift/installer
+ PACKAGE_PATH=/home/eugene/go/src/github.com/openshift/installer
+ test -z /home/eugene/go/src/github.com/openshift/installer
+ LOCAL_PATH=/home/eugene/go/src/github.com/openshift/installer
+ test /home/eugene/go/src/github.com/openshift/installer '!=' /home/eugene/go/src/github.com/openshift/installer
+ MODE=release
++ git describe --always --abbrev=40 --dirty
+ LDFLAGS=' -X main.version=v0.10.0'
+ TAGS=libvirt
+ OUTPUT=bin/openshift-install
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ case "${MODE}" in
+ TAGS='libvirt release'
+ test -n quay.io/openshift-release-dev/ocp-release:4.0.0-0.1
+ LDFLAGS=' -X main.version=v0.10.0 -X github.com/openshift/installer/pkg/asset/ignition/bootstrap.defaultReleaseImage=quay.io/openshift-release-dev/ocp-release:4.0.0-0.1'
+ test -n 47.249
+ LDFLAGS=' -X main.version=v0.10.0 -X github.com/openshift/installer/pkg/asset/ignition/bootstrap.defaultReleaseImage=quay.io/openshift-release-dev/ocp-release:4.0.0-0.1 -X github.com/openshift/installer/pkg/rhcos.buildName=47.249'
+ test '' '!=' y
+ go generate ./data
writing assets_vfsdata.go
+ echo 'libvirt release'
+ grep -q libvirt
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ go build -ldflags ' -X main.version=v0.10.0 -X github.com/openshift/installer/pkg/asset/ignition/bootstrap.defaultReleaseImage=quay.io/openshift-release-dev/ocp-release:4.0.0-0.1 -X github.com/openshift/installer/pkg/rhcos.buildName=47.249' -tags 'libvirt release' -o bin/openshift-install ./cmd/openshift-install
eugene@ivantsoft ~/go/src/github.com/openshift/installer ((HEAD detached at v0.10.0)) $ bin/openshift-install create cluster
? SSH Public Key /home/eugene/.ssh/id_rsa.pub
? Platform libvirt
? Libvirt Connection URI qemu+tcp://192.168.122.1/system
? Base Domain tt.testing
? Cluster Name codenvy
? Pull Secret [? for help] ****************************************************************************************************************************************************************************************INFO Fetching OS image: redhat-coreos-maipo-47.249-qemu.qcow2.gz 
INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
INFO API v1.11.0+c69f926354 up                    
INFO Waiting up to 30m0s for the bootstrap-complete event... 
ERROR: logging before flag.Parse: E0130 08:28:24.401392    6213 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARNING RetryWatcher - getting event failed! Re-creating the watcher. Last RV: 148 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 10m0s for the openshift-console route to be created... 
FATAL waiting for openshift-console URL: context deadline exceeded 
```
Events:
[events.log](https://github.com/openshift/installer/files/2811223/events.log)

Is this expected with 0.10.0? Since it works with 0.9.1 for me on Fedora 28 with libvirt. However, unfortunately, 0.9.1 has a bug (already fixed https://github.com/openshift/console/issues/1112) and this version does not work for me since I need to work with OperatorHub and integration of Eclipse Che operator.

What would be the best way to proceed? Give up on a local install with libvirt and look for AWS resources?

**Comment by praveenkumar** [comment]
@eivantsov https://bugzilla.redhat.com/show_bug.cgi?id=1666561this is where it is tracked, do put your comments.

**Comment by wking** [comment]
>     ...(HEAD detached at v0.10.0)...

Building from tagged releases get update payloads from quay.io, see the Bugzilla bug linked above (twice now ;).  Building from master should work better, but comes wiith [its own caveats][1].

> What would be the best way to proceed? Give up on a local install with libvirt and look for AWS resources?

We will sell AWS support, so yeah, I expect that is the best route if you want fewer quirks at this stage.

[1]: https://github.com/openshift/installer/issues/1078#issuecomment-458744723

**Comment by eivantsov** [comment]
@praveenkumar i don't have access to this issue

@wking would it be fair to say that 0.10.0+ libvirt installation is broken now?

**Comment by praveenkumar** [comment]
>  i don't have access to this issue

@eivantsov if you login using your redhat account then you will able to access this atm.

> would it be fair to say that 0.10.0+ libvirt installation is broken now?

@eivantsov this only broken for tagged release which have released payloads but it does work with from master as @wking said.

**Comment by eivantsov** [comment]
@praveenkumar I have the same problem with master too

**Comment by eivantsov** [comment]
@wking @praveenkumar 
From master, libvirt, Fedora 28

```
eugene@ivantsoft ~/go/src/github.com/openshift/fourdotoh $ ../installer/bin/openshift-install create cluster
? SSH Public Key /home/eugene/.ssh/id_rsa.pub
? Platform libvirt
? Libvirt Connection URI qemu+tcp://192.168.122.1/system
? Base Domain tt.testing
? Cluster Name eugenious
? Pull Secret [? for help] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
INFO Fetching OS image: redhat-coreos-maipo-47.287-qemu.qcow2.gz 
INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
INFO API v1.12.4+3434dda up                       
INFO Waiting up to 30m0s for the bootstrap-complete event... 
ERROR: logging before flag.Parse: E0130 11:06:07.008600   14435 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARNING RetryWatcher - getting event failed! Re-creating the watcher. Last RV: 2318 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 10m0s for the openshift-console route to be created... 
FATAL waiting for openshift-console URL: context deadline exceeded 
```
Last lines from install log:

```
time="2019-01-30T11:12:45+02:00" level=debug msg="Still waiting for the console route: the server could not find the requested resource (get routes.route.openshift.io)"
time="2019-01-30T11:13:15+02:00" level=debug msg="Still waiting for the console route..."
time="2019-01-30T11:14:04+02:00" level=debug msg="Still waiting for the console route: the server could not find the requested resource (get routes.route.openshift.io)"
time="2019-01-30T11:14:34+02:00" level=debug msg="Still waiting for the console route: the server is currently unable to handle the request (get routes.route.openshift.io)"
time="2019-01-30T11:15:04+02:00" level=debug msg="Still waiting for the console route: the server is currently unable to handle the request (get routes.route.openshift.io)"
time="2019-01-30T11:15:44+02:00" level=debug msg="Still waiting for the console route: the server could not find the requested resource (get routes.route.openshift.io)"
time="2019-01-30T11:16:15+02:00" level=debug msg="Still waiting for the console route..."
time="2019-01-30T11:16:45+02:00" level=debug msg="Still waiting for the console route..."
time="2019-01-30T11:17:22+02:00" level=debug msg="Still waiting for the console route: the server could not find the requested resource (get routes.route.openshift.io)"
time="2019-01-30T11:17:52+02:00" level=debug msg="Still waiting for the console route..."
time="2019-01-30T11:18:07+02:00" level=fatal msg="waiting for openshift-console URL: context deadline exceeded"
```

Events:

[install_events.log](https://github.com/openshift/installer/files/2811781/install_events.log)

**Comment by e-minguez** [comment]
Current master (commit id d3ff3afe):

- Bootstrap node and master are created
- Deployment happens
- Bootstrap node is deleted
- Worker is created
- Installation finished unsuccessfully while waiting for the console to be created (FATAL waiting for openshift-console URL: context deadline exceeded)

Findings:

- Some pods in the master are oomkilled/crashloopback
- Some 'the server is currently unable to handle the request' messages happen. I think this is because the master is out of resources
- openshift-install still uses a huge amount of ram...

I think the issues can be workarounded by adding more cpu/ram to the master node (so, create the manifests, modify the cpu/ram specs for the masters, and create the cluster), but I will need to find somewhere else to test it, my laptop is not capable of do that.

Just in case, in order to make this 'work' in my laptop (t480s, 16 gb ram) I need to:

- Close all apps (except the terminal)
- Add 4 gb of swap (fallocate -l 4G /swapfile to create a swapfile... then swapon -a /swapfile... 
- Also after closing all apps, clean the disk cache to free up some memory (echo 3 > /proc/sys/vm/drop_caches)

**Comment by eivantsov** [comment]
@e-minguez i have 24GB and while installing I do not see all of my RAM being used.

**Comment by e-minguez** [comment]
> @e-minguez i have 24GB and while installing I do not see all of my RAM being used.

I do have 16 and unless I add 4 gb more of swap (goodbye nvme!) the installer is oom-killed :)

**Comment by rhopp** [comment]
It seems, that I stumbled upon the same issue using 0.11.0 version and AWS as the target infrastructure.
Here's the script output
<details>
INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
INFO API v1.11.0+8868a98a7b up                    
INFO Waiting up to 30m0s for the bootstrap-complete event... 
ERROR: logging before flag.Parse: E0130 12:44:05.888016   25969 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARNING RetryWatcher - getting event failed! Re-creating the watcher. Last RV: 297 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 10m0s for the openshift-console route to be created... 
FATAL waiting for openshift-console URL: context deadline exceeded 
</details>


Here's the `.openshift_install.log`: https://paste.fedoraproject.org/paste/zhe4v4FPxfel9vm01Nvvjw

**Comment by Jiri-Kremser** [comment]
I am in the completely same situation as @eivantsov . I need to test the operator in the marketplace and I am also hitting this issue in `clusterapi-manager-controllers` pod. No console for me :(

```
Failed to pull image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225": rpc error: code = Unknown desc = Error reading manifest sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225 in registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-15-010905: unauthorized: authentication required
```

and I can confirm that it's almost impossible to run the installer on t480s with 16gigs of RAM. `0.9.1` worked, but marketplace was broken there. Isn't it possible to run `0.9.1` version of installer and upgrade only the console in it? The whole cluster comes with the console operator, can't I just modify the crd for the console to use the version w/ the fix?

**Comment by praveenkumar** [comment]
@wking Since now this payload is available on `quay.io`, and according to https://bugzilla.redhat.com/show_bug.cgi?id=166656 it should be available with new tag of installer, so when we can do a new tag release for installer and have all payload from `quay.io` side?

**Comment by cynepco3hahue** [comment]
I still can see that issue on the master
```
  Warning  Failed     3m (x2 over 4m)  kubelet, test-1-master-0  Error: ErrImagePull
  Warning  Failed     3m (x2 over 4m)  kubelet, test-1-master-0  Failed to pull image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-25-205123@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225": rpc error: code = Unknown desc = Error reading manifest sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225 in registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-25-205123: unauthorized: authentication required
  Warning  Failed     3m (x4 over 4m)  kubelet, test-1-master-0  Error: ImagePullBackOff
  Normal   BackOff    3m (x3 over 4m)  kubelet, test-1-master-0  Back-off pulling image "registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-01-25-205123@sha256:8b848ebe6ba72a678300a0fa9b7749bcef3b4230e355e1c789527e6d1c615225"
```

**Comment by steven-ellis** [comment]
I've been having similar issues which I put down to memory sizing #1041 
I've increased the memory for master-0 but I'm still not getting any workers starting.

**Comment by ssbano** [comment]
Hi guys,

The minimum required is :

1 x master 
2x workers

*router - need two worker


Best,
Fábio Sbano

**Comment by wking** [comment]
> *router - need two worker

Is there a router pull or docs I can link for that?  I guess we need to bump our libvirt default to catch up.

**Comment by ssbano** [comment]
wking,

I'll create a howto..

see running at https://youtu.be/ZOZPmwUwWj8

Best Regards,
Fábio Sbano

**Comment by ssbano** [comment]
Wking,

Are you using the latest version of the installer?

Regards,
Fábio Sbano

**Comment by wking** [comment]
> Are you using the latest version of the installer?

I haven't run it on libvirt in a while, but if the router for some reason needs 2+ compute nodes now, we'd want to update [the default][1] and [some validation][2].  Or is the issue total compute memory constraints or similar, and not actually compute replica count?

[1]: https://github.com/openshift/installer/blob/master/pkg/types/defaults/installconfig.go#L46-L47
[2]: https://github.com/openshift/installer/blob/master/pkg/types/validation/installconfig.go#L186-L187

**Comment by ssbano** [comment]
WKing,

replica count=2 then you can not hear two 443, 80 on the same physical or virtual host.

Best Regards,
Fábio Sbano

**Comment by ssbano** [comment]
I needed to change some things in my setup configuration file and adjust the memory and solve the problem with dnsmasq.

Regards,
Fábio Sbano

**Comment by ssbano** [comment]
.tf
bootstrap - 32gb
master - 32gb
2x worker - 4gb

and wildcard "*.apps.test1.tt.testing" on bind listen ip 192.168.126.1

Regards,
Fábio Sbano

**Comment by ssbano** [comment]
Hi,

[fsbano@voyager-1 ~]$ oc get deployment
NAME             READY     UP-TO-DATE   AVAILABLE   AGE
router-default   0/2       2            0           8m23s
[fsbano@voyager-1 ~]$ 


[fsbano@voyager-1 ~]$ oc describe deployment/router-default
Name:                   router-default
Namespace:              openshift-ingress
CreationTimestamp:      Fri, 08 Mar 2019 21:16:46 -0300
Labels:                 app=router
                        ingress.openshift.io/clusteringress=default
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=router,router=router-default
Replicas:               2 desired | 2 updated | 2 total | 0 available | 2 unavailable

  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  8m    deployment-controller  Scaled up replica set router-default-779745f684 to 2
[fsbano@voyager-1 ~]$ 


[fsbano@voyager-1 ~]$ oc edit deployments/router-default

     nodeSelector:
        node-role.kubernetes.io/worker: ""


Best Regards,
Fábio Sbano

**Comment by ssbano** [comment]
Hi,

My install-config.yaml file

[root@voyager-1 ~]# more install-config.yaml 
apiVersion: v1beta3
baseDomain: tt.testing
compute:
- name: worker
  platform: {}
  replicas: 2
controlPlane:
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: test1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0

# ./openshift-install create cluster --dir . --log-level debug

Best Regards,
Fábio Sbano

**Comment by ssbano** [comment]
Hey,

Step-by-Step 

[fsbano@voyager-1 ~]$ oc get pod --all-namespaces | egrep -v '(Running|Completed)'
NAMESPACE                                     NAME                                                           READY     STATUS             RESTARTS   AGE
openshift-console                             console-6d6ffd4444-9299h                                       0/1       CrashLoopBackOff   13         59m
openshift-console                             console-6d6ffd4444-p2hpf                                       0/1       CrashLoopBackOff   13         59m
openshift-kube-controller-manager             revision-pruner-3-jaguar-kt74v-master-0                        0/1       OOMKilled          0          75m
[fsbano@voyager-1 ~]$ 

```
[fsbano@voyager-1 ~]$ sudo cat /var/named/named.apps.jaguar.fsbano.io
$TTL 1D
@	IN SOA	@ rname.invalid. (
					0	; serial
					1D	; refresh
					1H	; retry
					1W	; expire
					3H )	; minimum
	  NS	@
	A     192.168.126.1
*       A     192.168.126.51
*       A     192.168.126.52
[fsbano@voyager-1 ~]$ 
```

[fsbano@voyager-1 ~]$ host prometheus-k8s-openshift-monitoring.apps.jaguar.fsbano.io
Host prometheus-k8s-openshift-monitoring.apps.jaguar.fsbano.io not found: 3(NXDOMAIN)
[fsbano@voyager-1 ~]$ 

[fsbano@voyager-1 ~]$ sudo service named restart
Redirecting to /bin/systemctl restart named.service
[fsbano@voyager-1 ~]$ 

[fsbano@voyager-1 ~]$ host prometheus-k8s-openshift-monitoring.apps.jaguar.fsbano.io
prometheus-k8s-openshift-monitoring.apps.jaguar.fsbano.io has address 192.168.126.51
prometheus-k8s-openshift-monitoring.apps.jaguar.fsbano.io has address 192.168.126.52
[fsbano@voyager-1 ~]$   👍 

[fsbano@voyager-1 ~]$ oc scale deployment.apps/console --replicas=0
deployment.apps/console scaled
[fsbano@voyager-1 ~]$ oc get pod
NAME                       READY     STATUS        RESTARTS   AGE
console-6d6ffd4444-9299h   0/1       Terminating   14         64m
[fsbano@voyager-1 ~]$ 

[fsbano@voyager-1 ~]$ oc get pod
No resources found.
[fsbano@voyager-1 ~]$ 

[fsbano@voyager-1 ~]$ oc get pod
NAME                       READY     STATUS              RESTARTS   AGE
console-6d6ffd4444-6c4p2   0/1       ContainerCreating   0          3s
console-6d6ffd4444-9tfhv   0/1       ContainerCreating   0          3s
[fsbano@voyager-1 ~]$ 

[fsbano@voyager-1 ~]$ oc get pod
NAME                       READY     STATUS    RESTARTS   AGE
console-6d6ffd4444-skhg6   1/1       Running   0          2m52s
console-6d6ffd4444-wcd6g   1/1       Running   0          2m52s
[fsbano@voyager-1 ~]$  💯 

Best Regards,
Good Night Everybody
Fábio Sbano

**Comment by ssbano** [comment]
Imagens!

![okd-preview-4-libvirt](https://user-images.githubusercontent.com/48354484/54064738-3cd71680-41f6-11e9-9ce4-8306194150e7.png)
![okd-preview-4-cluster-status-libvirt](https://user-images.githubusercontent.com/48354484/54064739-41033400-41f6-11e9-99b4-fd39cbb516f1.png)
![okd-preview-4-machines-libvirt](https://user-images.githubusercontent.com/48354484/54064741-45c7e800-41f6-11e9-9a9e-8448f61d8607.png)

Best Regards,
Fábio Sbano

**Comment by ssbano** [comment]
> > *router - need two worker
> 
> Is there a router pull or docs I can link for that? I guess we need to bump our libvirt default to catch up.

Can I send a pull request?

Best Regards,
Fabio Sbano

**Comment by praveenkumar** [comment]
@ssbano From which commit (component) it is required to have 2 worker to make it work in case of libvirt platform? If this is hard requirement then it would be problematic for us (Code Ready Container team).

I tested 0.14.0 tag with single worker and everything worked as expected. but today when I am trying out the master then getting following error (is this because of that limitation?)

```
$ oc get events -n openshift-ingress
LAST SEEN   TYPE      REASON              OBJECT                                 MESSAGE
8m23s       Warning   FailedCreate        replicaset/router-default-76d66d6844   Error creating: pods "router-default-76d66d6844-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 80: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 443: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 1936: Host ports are not allowed to be used]
```

**Comment by ssbano** [comment]
@praveenkumar,

I was using the master until yesterday. this morning I did downgrade to 0.14 and it is also running perfectly

Could you describe your setup?

PS: I saw that they updated the image to 20190310

Regards,
Fábio Sbano

**Comment by ssbano** [comment]
@praveenkumar,

on the two worker it works only with a work but will always be "pending".

Please,

oc project openshift-ingress
oc describe router-default

see #1395

Regards,
Fábio Sbano

**Comment by zeenix** [comment]
I think this is likely a duplicate of #1007

**Comment by praveenkumar** [comment]
Already fixed.
