### ISSUE TITLE
Errors during init provide insufficient guidance when missing required fields

### ISSUE THREAD

**Issue by jupierce** [openshift/installer#108]
### Tectonic version ([release](https://github.com/openshift/installer/releases) or commit hash):
```
78e6f76292331a7fadc57ce3f362e558890fde84
```

### Terraform version (`terraform version`):
```
Terraform v0.11.7
```

### Platform (aws|azure|openstack|metal|vmware):

```
aws
```

### What happened?
```
As a new user to tectonic init, tried populating aws config example. Clearly missing some fields in the file, but error output from is not always indicative of missing field:

15:47 $ tectonic init --config=examples/tectonic.aws.yaml
ERRO[0000] Found 1 error in the cluster definition:     
ERRO[0000] error 1: open : no such file or directory    
FATA[0000] found 1 cluster definition error   

```

### What you expected to happen?
```
Error should identify which field is missing.
```

### How to reproduce it (as minimally and precisely as possible)?
```
aws config file without required file fields.
```

**Comment by crawford** [comment]
This refers to the old installer which has since been deleted. If you are still having trouble with the new installer, feel free to open a new issue.
