### ISSUE TITLE
Add support for CNAME in Route53

### ISSUE THREAD

**Issue by pierreozoux** [openshift/installer#1082]
In our enterprise env, we don't have support for ALIAS (we have an internal DNS system that syncs Route53 to internal DNS and it just supports CNAME, not ALIAS).

**Comment by abhinavdahiya** [comment]
What platform is this AWS?

**Comment by pierreozoux** [comment]
Yes, sorry, I thought it was implied by the term Route53

**Comment by abhinavdahiya** [comment]
> Yes, sorry, I thought it was implied by the term Route53

And Route53 in **your** enterprise AWS  account doesn't have ALIAS support?

**Comment by pierreozoux** [comment]
I know it might sound strange :) in my Enterprise, we have our own DNS server. And the DNS team was kind enough to create a lambda to sync Route53 to this internal DNS.
This already is a great news, you can't imagine :) interacting with this xml API was a pain :)
But, they don't support ALIAS. I'm asking them to support it, of course (if I had access to this piece of code, I would have added this line of code already) but you might know as I do, that it will take months.

If you want to close this issue as 'won't solve', I'd understand also.

Thanks for your precious time :)

Have a nice day!

**Comment by sdodson** [comment]
@pierreozoux ALIAS has certain advantages when working in AWS. Does it seem feasible to translate ALIAS into CNAME when mirroring the information into your environment? For now we'd prefer sticking with only ALIAS.

**Comment by abhinavdahiya** [comment]
> @pierreozoux ALIAS has certain advantages when working in AWS. Does it seem feasible to translate ALIAS into CNAME when mirroring the information into your environment? For now we'd prefer sticking with only ALIAS.

/close
