### ISSUE TITLE
RFE: Support for BYO certs

### ISSUE THREAD

**Issue by pierreozoux** [openshift/installer#1084]
In my enterprise env, as a cluster operator, we have a CA, and our own certs.
This is currently used to secure the following routes:
 - registry
 - console
 - grafana
 - prometheus
 - elastic
 - kibana
 - and what I forgot

The installer looks like a good place to define it. Is my assumption correct? If not, where is the place to configure that?

Thanks :)

**Comment by abhinavdahiya** [comment]
> In my enterprise env, as a cluster operator, we have a CA, and our own certs.
> This is currently used to secure the following routes:
> 
>     * registry

https://github.com/openshift/cluster-image-registry-operator

>     * console

https://github.com/openshift/console-operator

>     * grafana
> 
>     * prometheus

https://github.com/openshift/prometheus-operator

>     * elastic
> 
>     * kibana

https://github.com/openshift/cluster-logging-operator

>     * and what I forgot

You will have to configure the operators as day2 

> 
> The installer looks like a good place to define it. Is my assumption correct? If not, where is the place to configure that?

The installer controls only the CA and certs for control plane components... These are not configurable.
