### ISSUE TITLE
RFE: Support for proxy/CA for applications

### ISSUE THREAD

**Issue by pierreozoux** [openshift/installer#1085]
As an enterprise cluster operator, I need to define proxy and Certificate authority for every piece of software I use (OS, yum, pip, docker, artifactory, npm...).
As a cluster operator, it is convenient to configure it once for all.
I managed to achieve that in OCP 3.11.

It looks like this installer would be a good place for that. Is my assumption correct? Or will there be another place to configure that?

**Comment by ericavonb** [comment]
Can you give more details about exactly which CAs you configured in 3.11, like which config fields and files?
cc @ironcladlou @knobunc

**Comment by pierreozoux** [comment]
- Compagny registry (artifactory)
 - yum (but here I guess it doesn't apply)
 - ldap for auth (we'll have openidconnect soon, but same, we'll need CA)

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/issues/1690 duplicate

/close
