### ISSUE TITLE
RFE: warn user if no SSH pubkeys found

### ISSUE THREAD

**Issue by thoraxe** [openshift/installer#1093]
Currently 0.10 will simply not interactively prompt for a keypair if it doesn't find any .pub files. This doesn't create an unusable cluster, but it seems users are surprised when their hosts have no keypairs associated or installed.

We may wish to add a warning to the pubkey/keypair selection step if no keys are found.

eg: WARNING: No .pub keyfiles found. You will need to manually add keys to your nodes via the operator post-install. Do you wish to continue? [Y/N]

**Comment by abhinavdahiya** [comment]
Providing SSH keys is not required during installation, and can be added as Day 2 https://github.com/openshift/machine-config-operator/blob/ce2eba470b0fe85a06139d0a905b6241c5ceb409/docs/Update-SSHKeys.md

The Prompts are best-effort. you can use https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations to create an `install-config` and add your SSH keys there.

/close
