### ISSUE TITLE
Documentation for DNS setup for Libvirt on Debian hosts

### ISSUE THREAD

**Issue by cdrage** [openshift/installer#1097]
See here: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#set-up-networkmanager-dns-overlay

There's instructions for using NetworkManager.

Is there any documentation with regards to Debian / Ubuntu based Libvirt hosts? I see there is reference to other Debian / Ubuntu documentation here: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#configure-the-service-runner-to-pass---listen-to-libvirtd

**Comment by zeenix** [comment]
@cdcabrera Since almost all Openshift devs use Fedora/RHEL/centOS, I think this will need a contribution from a Debian user, like yourself. I'm closing this for now but if you could contribute the Debian instruction, that would be great and please re-open the issue then. Thanks.

/close
