### ISSUE TITLE
Installation fails with error unable to connect to server at '192.168.122.1:16509': Connection refused

### ISSUE THREAD

**Issue by eivantsov** [openshift/installer#1102]
# Version

```console
eugene@ivantsoft ~/go/src/github.com/openshift/installer (master) $ bin/openshift-install version
bin/openshift-install unreleased-master-99-g4016f5f9c166f255aca875e9d0ba0dffb8c88122
```

# Platform (aws|libvirt|openstack):

libvirt
# What happened?

When prompted for the url, I used the default one:

![image](https://user-images.githubusercontent.com/5337267/51412315-2cc98180-1b39-11e9-91b4-6a5efd287459.png)

However, the installation fails with 

```
unable to connect to server at '192.168.122.1:16509': Connection refused
```

What am I doing wrong? None of pre-installation steps showed any errors.

# How to reproduce it (as minimally and precisely as possible)?

I went through libvirt guide

**Comment by eivantsov** [comment]
@wking sorry about that. Issue description updated

**Comment by wking** [comment]
Can you attach `.openshift_install.log`?

**Comment by eivantsov** [comment]
[log.txt](https://github.com/openshift/installer/files/2774961/log.txt)

**Comment by wking** [comment]
Ah, for some reason I hadn't realized that the connection error was from Terraform:

```
time="2019-01-18T12:39:09-05:00" level=error msg="Error: Error refreshing state: 1 error occurred:"
time="2019-01-18T12:39:09-05:00" level=error msg="\t* provider.libvirt: virError(Code=38, Domain=7, Message='unable to connect to server at '192.168.122.1:16509': Connection refused')"
```

You've [set up libvirtd to listen][1]?

[1]: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#configure-the-service-runner-to-pass---listen-to-libvirtd

**Comment by wking** [comment]
So this is almost certainly not an installer issue.  You can test with:

```console
 $ virsh -c qemu+tcp://192.168.122.1/system version
Compiled against library: libvirt 3.9.0
Using library: libvirt 3.9.0
Using API: QEMU 3.9.0
Running hypervisor: QEMU 2.9.0
```

I expect that to give you:

```
error: failed to connect to the hypervisor
error: unable to connect to server at '192.168.122.1:16509': Connection refused
```

instead.  Then work through [our libvirt docs][1] and/or your system's libvirt docs until you get `virsh` connecting over TCP.  Once you have that straightened out, I expect the installer will work.

[1]: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md

**Comment by eivantsov** [comment]
@wking yes, it was misconfiguration on my side. Closing the issue. However, I was not able to install again since the installer never got console route. I think I hit https://github.com/openshift/installer/issues/1078

**Comment by ScrapCodes** [comment]
Hi, the links to the docs above are now 404. I am hitting the same problem, it would be helpful, if you could share those docs.
