### ISSUE TITLE
Libvirt image download process should respect `--dir`

### ISSUE THREAD

**Issue by e-minguez** [openshift/installer#1104]
# Version

```console
$ openshift-install version
openshift-install v0.10.0
```

Also tested with latest master (unreleased-master-105-gd1272424396f1d42faf239dc1b976db905d0b338)

# Platform (aws|libvirt|openstack):

Libvirt

# What happened?

`--dir` flag should be respected for every asset the installer creates/downloads. For libvirt, the image file is stored in `~/.cache/openshift-installer/` instead.

# What you expected to happen?

If using `--dir` flag, the image download should happen in the folder specified.

# How to reproduce it (as minimally and precisely as possible)?

Build the openshift-installer with libvirt support, then run the installer with `--dir` and `--log-level=debug`

```console
$ openshift-install create cluster --dir . --log-level debug
...
DEBUG   Generating "Bootstrap Ignition Config"...  
DEBUG   Fetching "Master Ignition Config"...       
DEBUG   Reusing previously-fetched "Master Ignition Config" 
DEBUG Generating "Terraform Variables"...          
INFO Fetching OS image: redhat-coreos-maipo-47.249-qemu.qcow2.gz 
DEBUG Unpacking OS image into "/home/edu/.cache/openshift-install/libvirt/image/3131181dbd7544f53eb280b2ffa0ca55"... 
```

# Anything else we need to know?

# References

**Comment by abhinavdahiya** [comment]
I think the reasoning for that is that you might want to keep the image while we recommend deleting the asset directory before new install. https://github.com/openshift/installer#cleanup

**Comment by crawford** [comment]
Additionally, the downloaded RHCOS image is not a generated asset.

@e-minguez why do you think the RHCOS image should end up in the asset directory?

**Comment by wking** [comment]
More ideas for where the RHCOS QCOW2 should live in #687.

**Comment by e-minguez** [comment]
Even if it is not an asset 'per se' it is something the installer generates/requires, so as a user, I think it would be better to keep all the stuff in the specified folder (`--dir`) instead spreading some stuff here and there.
My 2 cents.

**Comment by zeenix** [comment]
Closing based on https://github.com/openshift/installer/issues/1104#issuecomment-456219950

/close
