### ISSUE TITLE
Install Fails - Undefined variable

### ISSUE THREAD

**Issue by glennswest** [openshift/installer#1115]
# Version openshift-install unreleased-master-110-gb166e2e663455389ac29f4685c1e985c2168ee72

# Platform (aws|libvirt|openstack):
libvirt

# What happened?
changed: [bts.green.k.e2e.bos.redhat.com] => (item={'value': True, 'key': u'openshift.service'})

TASK [Wait for MCS endpoint to show up] ******************************************************************************************************************************************************************************************
fatal: [bts.green.k.e2e.bos.redhat.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'mcd_endpoint' is undefined\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/deploy_cluster_40.yml': line 41, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      - progress.service\n  - name: Wait for MCS endpoint to show up\n    ^ here\n"}
...ignoring

TASK [Get node logs] *************************************************************************************************************************************************************************************************************
changed: [bts.green.k.e2e.bos.redhat.com]

TASK [Collect a list of containers] **********************************************************************************************************************************************************************************************
changed: [bts.green.k.e2e.bos.redhat.com]

TASK [Collect container logs] ****************************************************************************************************************************************************************************************************

TASK [debug] *********************************************************************************************************************************************************************************************************************
ok: [bts.green.k.e2e.bos.redhat.com] => {
    "crictl_logs_output": {
        "changed": false, 
        "results": [], 
        "skipped": true, 
        "skipped_reason": "No items in the list"
    }
}

TASK [debug] *********************************************************************************************************************************************************************************************************************
ok: [bts.green.k.e2e.bos.redhat.com] => {
    "msg": [
        "-- Logs begin at Tue 2019-01-22 10:42:15 CST, end at Tue 2019-01-22 10:56:44 CST. --", 
        "Jan 22 10:56:42 bts.green.k.e2e.bos.redhat.com systemd[1]: Started Bootstrap a Kubernetes cluster.", 
        "Jan 22 10:56:43 bts.green.k.e2e.bos.redhat.com bootkube.sh[15500]: Pulling release image..."
    ]
}

TASK [fail] **********************************************************************************************************************************************************************************************************************
fatal: [bts.green.k.e2e.bos.redhat.com]: FAILED! => {"changed": false, "msg": "MCS start failed."}
	to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster_40.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************
bts.green.k.e2e.bos.redhat.com : ok=72   changed=32   unreachable=0    failed=1   
localhost                  : ok=8    changed=0    unreachable=0    failed=0   
openshift.green.k.e2e.bos.redhat.com : ok=59   changed=24   unreachable=0    failed=0   

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

1. openshift-install create ignition-configs --log-level debug
2. ansible-playbook -i /root/openshift_winoperator/inventory.ini /root/openshift-ansible/playbooks/deploy_cluster_40.yml

# Anything else we need to know?
1. Rebuilt installer this morning
2. Using RHEL75 

[root@ctl openshift_winoperator]# cat inventory.ini 
[nodes:children]
bootstrap
masters
workers

[nodes:vars]
ansible_ssh_user=root
ansible_become=True

openshift_install_config_path=/root/openshift_winoperator/install-config-ansible.yaml
openshift_deployment_type=origin
openshift_release=v4.0

[bootstrap]
bts.green.k.e2e.bos.redhat.com

[bootstrap:vars]
openshift_ignition_file_path=/root/openshift_winoperator/bootstrap.ign

[masters]
openshift.green.k.e2e.bos.redhat.com

[workers]
worker.green.k.e2e.bos.redhat.com

[root@ctl openshift_winoperator]# cat install-config-ansible.yaml
apiVersion: v1beta1
baseDomain: green.k.e2e.bos.redhat.com
machines:
- name: master
  platform: {}
  replicas: 1
- name: worker
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: green
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  serviceCIDR: 172.30.0.0/16
  type: OpenshiftSDN
platform:
  libvirt:
    # This URI is not actually used
    URI: null
    defaultMachinePlatform:
      image: file:///unused
    masterIPs: null
    network:
      if: null
      ipRange: null
pullSecret: '...something'
sshKey: '...something'

**Comment by crawford** [comment]
I'm not sure what you are trying to do here. The installer doesn't use Ansible.

**Comment by eparis** [comment]
I afraid that since we don't know what you are doing we won't likely be able to help. Please feel free to reopen if you can help supply more actionable reproduction steps.
