### ISSUE TITLE
eu-west-3 doesn't have m4.xlarge

### ISSUE THREAD

**Issue by brenton** [openshift/installer#1127]
# Version

```console
$ openshift-install version
unreleased-master-122-g3a604a3f060fea1a3a8c87968ee8af2db89a35eb
```

# Platform (aws|libvirt|openstack):
aws

# What happened?

Right now a stock aws cluster doesn't work in eu-west-3.  This is because m4.xlarge is not available.

# What you expected to happen?
We should query the list of supported instance types and choose the best option for a given region.  See https://stackoverflow.com/questions/45283036/list-all-ec2-instance-types-in-a-region-or-az for tips on using the pricing API to gather this info.

# How to reproduce it (as minimally and precisely as possible)?

A stock aws cluster in eu-west-3 will reproduce this problem as of commit 3a604a3f060fea1a3a8c87968ee8af2db89a35eb

**Comment by eparis** [comment]
https://github.com/openshift/installer/pull/1163
