### ISSUE TITLE
image-registry pod stuck in "CreateContainerConfigError"

### ISSUE THREAD

**Issue by rutvik23** [openshift/installer#1138]
# Version
# oc version 
oc v4.0.0-0.147.0
kubernetes v1.11.0+dde478551e

Installer: 
```console
$ openshift-install version
./openshift-install v0.11.0
```

# Platform (aws|libvirt|openstack):
`aws`

# What happened?

When I installed cluster and went to see `image-registry` pods, I found those in `CreateContainerConfigError` state.
```
# oc get pods
NAME                                               READY     STATUS                       RESTARTS   AGE
cluster-image-registry-operator-684499b66b-4x5nd   1/1       Running                      0          3h
image-registry-5d74797757-b2llp                    0/1       CreateContainerConfigError   0          33m
image-registry-897d8cbdd-6khfl                     0/1       CreateContainerConfigError   0          33m
```

# What you expected to happen?

`image-registry` pods should be up and running as soon as cluster is installed.

# Anything else we need to know?
After looking below message, I found that the `image-registry` secret is empty. Also, I compared this with installer `0.10.0` & `oc v4.0.0-0.79.0`  environment and found that this secret `image-registry-private-configuration` is missing in installer `0.11.0`  & `oc v4.0.0-0.147.0`
```
# oc get configs.imageregistry.operator.openshift.io/instance -o yaml -n openshift-image-registry
...
message: 'Unable to apply resources: unable to sync secrets: timed out 
...

# oc get secret
image-registry                                    Opaque                                0         3h
```

**Comment by bparees** [comment]
since this is being tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1670357 we don't need it in two places.
