### ISSUE TITLE
Unable to pass libvirt to openshift-install create cluster

### ISSUE THREAD

**Issue by AsherShoshan** [openshift/installer#1140]
# Version
bin/openshift-install unreleased-master-147-g322f8ed0101769b4164de50f6e5c158528fffac4
```console
$ openshift-install version
<your output here>
```

# Platform (aws|libvirt|openstack):
libvirt
Unable to pass 'libvirt' to openshift-installer create cluster

# What happened?
1. run bin/openshift-installer create cluster --> pressed enter
2. prompted for ssh key --> pressed enter
2. prompted for 'Platform' --> typed 'libvirt'
got --> X Sorry, your reply was invalid: Value is required

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Proceed to libvirt

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by wking** [comment]
> bin/openshift-install unreleased-master-147-g322f8ed0101769b4164de50f6e5c158528fffac4

Looks like you built your own installer (which you need to do for libvirt), but I'm guessing you didn't [set `TAGS=libvirt`][1] (which you need to do).  Can you provide more details about your compilation step?

[1]: https://github.com/openshift/installer/blob/v0.11.0/docs/dev/libvirt-howto.md#build-and-run-the-installer

**Comment by AsherShoshan** [comment]
Hi,
Even with the set tag - the same issue.
Compilation:  cloned the repo and run hack/build sh
Asher

**Comment by crawford** [comment]
Can you show us the exact invocation you used and the current commit hash you are using?

**Comment by AsherShoshan** [comment]
Hi,
mkdir $HOME/go/src/github.com/openshift
cd $HOME/go/src/github.com/openshift
git clone https://github.com/openshift/installer.git
cd installer
hack/build.sh
set TAGS=libvirt
<https://github.com/openshift/installer/blob/v0.11.0/docs/dev/libvirt-howto.md#build-and-run-the-installer>

bin/installer create cluster
(press enter)
(type libvirt)



pls advice on how to give you the commit hash?

**Comment by AsherShoshan** [comment]
* bin/openshift-install create cluster

**Comment by johwes** [comment]
You need to set the TAGS environtment _before_ building.
example,
export TAGS=libvirt
hack/build.sh

**Comment by AsherShoshan** [comment]
Thanks,
working now (missed it..)

**Comment by AsherShoshan** [comment]
Hi,
Now I get:
FATAL failed to fetch Terraform Variables: failed to generate asset
"Terraform Variables": failed to get Tfvars:

Is there any document detailing requirements?
Asher

**Comment by crawford** [comment]
This bug tracker isn't meant to be used as a discussion forum. Please open a new issue with the full logs.
