### ISSUE TITLE
How to set certificates for web console

### ISSUE THREAD

**Issue by perfey-he** [openshift/installer#1152]
HI, I am a newcomer using openshift , I created a cluster on aws follow the guide successfully，and I can connect to the cluster by useing oc command. But when I try to open the web console, chrome will prevent the connection because of invaild certificate(ERR_CERT_INVALID), and I can't proceed. 
I try to delete the route: console (namespace: openshit-console) and recreate it by [set tls key and certificate,](https://docs.openshift.com/container-platform/3.7/dev_guide/routes.html) but when I delete the route: console, it will recover immediately. 
I'm suffering the issue for a few days, if someone can offer some help, it will be very grateful.

**Comment by abhinavdahiya** [comment]
The route for console is owned and managed by [console-operator](https://github.com/openshift/console-operator) 

I think an issue there will have more chances for a concrete solution.

**Comment by eparis** [comment]
I am going to close this issue in hopes that the console team was able to help.
