### ISSUE TITLE
Libvirt in RHEL7.6 supported?

### ISSUE THREAD

**Issue by AsherShoshan** [openshift/installer#1183]
# Version
$ openshift-install version
unreleased-master-197-g8604f1fa3669176bc557b97f19d5dc11ee85fad7

# Platform (aws|libvirt|openstack):libvirt

# What happened?
openshift-install create cluster generates the below message

ERROR 	* libvirt_domain.bootstrap: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option') 

# What you expected to happen?
Creating a cluster

# How to reproduce it (as minimally and precisely as possible)?
run 'openshift-installer create cluster' in rhel7.6 machine

**Comment by e-minguez** [comment]
qemu-kvm version included in RHEL7.6 doesn't support the `-fw_cfg` flag required to use igntion. There is a PR pending for this https://github.com/openshift/installer/pull/675

If you have access to qemu-kvm-rhev (in RHV or OSP software channels), you can use it as it is an updated version that includes the `-fw_cfg` flag support.

**Comment by dantrainor** [comment]
I've been using the following to pull packages that support this from upstream Virt SIG.  This could provide a temporary workaround until the aforementioned PR is accepted:

https://github.com/ironcladlou/openshift4-libvirt-gcp/blob/master/provision.sh#L13-L34

**Comment by zeenix** [comment]
AFAIK, this has been resolved. Please re-open if not.

/close
