### ISSUE TITLE
libvirt: creating cluster not completed (fatal msg)

### ISSUE THREAD

**Issue by AsherShoshan** [openshift/installer#1184]
$ openshift-install version
unreleased-master-147-g322f8ed0101769b4164de50f6e5c158528fffac4

# Platform (aws|libvirt|openstack):
libvirt

# What happened?
~/go/src/github.com/openshift/installer/bin/openshift-install create cluster
INFO Fetching OS image: redhat-coreos-maipo-47.299-qemu.qcow2.gz 
INFO Consuming "Install Config" from target directory 
INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
FATAL waiting for Kubernetes API: context deadline exceeded 

# What you expected to happen?

Normal completion

# How to reproduce it (as minimally and precisely as possible)?

Try creating a cluster in Fedora-29 + libvirt

$ your-commands-here
~/go/src/github.com/openshift/installer/bin/openshift-install create cluster

**Comment by DarkBlaez** [comment]
Can confirm I see the same issue on the same OS install, I have posted another issue with further details

**Comment by zeenix** [comment]
@AsherShoshan is this still reproducible?

**Comment by AsherShoshan** [comment]
No.

**Comment by zeenix** [comment]
@AsherShoshan oh ok, thanks for the quick response.

/close
