### ISSUE TITLE
failed to initialize the cluster: a lot off restarting pods -  CrashLoopBackOff

### ISSUE THREAD

**Issue by ahrechanychenko** [openshift/installer#1198]
# Version
unreleased-master-227-ge4df3e220b9bb757f4494fd0073c497fb647f98f-dirty
Red Hat Enterprise Linux Server release 7.6 (Maipo)

# Platform (aws|libvirt|openstack):
libvirt

# What happened?
from .openshift_install.log
https://paste.fedoraproject.org/paste/~CUWq4CuxoWUjvfRU2GSWA

[ahrechan@~]$ oc get pods --all-namespaces |grep -v "Running" |grep -v Completed
https://paste.fedoraproject.org/paste/MSaz1j-c1wUz4v3Das44zA

[ahrechan@~]$ oc describe pods openshift-apiserver-operator-688879bb4f-g976h  -n openshift-apiserver-operator
https://paste.fedoraproject.org/paste/2175rDfFT-b7AKlOVNCCXQ

ahrechan@~]$ oc describe pods kube-apiserver-operator-6d56f6578f-pg9wc  -n openshift-kube-apiserver-operator
https://paste.fedoraproject.org/paste/j405M7OWEUZR7BHHQOnPoQ

from time to time:

[ahrechan@ ~]$ oc get pods --all-namespaces |grep -v "Running" |grep -v Completed
No resources found.
The connection to the server rhhi-api.redhat.local:6443 was refused - did you specify the right host or port?

# What you expected to happen?
https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md

Please list the full steps required to reproduce the issue.
execute all necessary steps from how-to 
failed on : bin/openshift-install --dir=cluster-0 create cluster

**Comment by levor23** [comment]
sudo crictl logs $(sudo crictl ps --pod=$(sudo crictl pods --name=etcd-member --quiet) --quiet) 
https://paste.fedoraproject.org/paste/6q8452ZZZoKyMifdopShbw

[core@rhhi-master-0 ~]$ sudo crictl pods --name=etcd-member
POD ID              CREATED             STATE               NAME                        NAMESPACE           ATTEMPT
331576e9f45a3       About an hour ago   Ready               etcd-member-rhhi-master-0   kube-system         0

[ahrechan@ ~]$ oc get nodes
NAME                  STATUS    ROLES     AGE       VERSION
rhhi-master-0         Ready     master    60m       v1.12.4+610027abd7
rhhi-worker-0-gs8qj   Ready     worker    51m       v1.12.4+610027abd7
rhhi-worker-0-nbfgx   Ready     worker    51m       v1.12.4+610027abd7
rhhi-worker-0-r6rfp   Ready     worker    51m       v1.12.4+610027abd7

oc get pods --all-namespaces

https://paste.fedoraproject.org/paste/Rl~b5J~L-AuiNRmgup3xLg

**Comment by levor23** [comment]
sometimes installation can finished without errors but the same issue are present with many pods
w/a - redeploy with disabled firewalld.service

**Comment by ahrechanychenko** [comment]
even with disabled firewalld after some time after installation I still can see

[root@titan57 ~]# oc get pods --all-namespaces |grep -v Running | grep -v Completed
NAMESPACE                                    NAME                                                       READY   STATUS              RESTARTS   AGE
openshift-apiserver-operator                 openshift-apiserver-operator-6f947ff54b-5zhhm              0/1     CrashLoopBackOff    109        13h
openshift-authentication-operator            origin-cluster-authentication-operator1-7c45746896-n9nms   0/1     CrashLoopBackOff    107        13h
openshift-controller-manager-operator        openshift-controller-manager-operator-68645b69b7-qplql     0/1     CrashLoopBackOff    111        13h
openshift-controller-manager                 controller-manager-92l9g                                   0/1     CrashLoopBackOff    8          55m
openshift-kube-apiserver-operator            kube-apiserver-operator-5b5756db99-fdvzq                   0/1     CrashLoopBackOff    110        13h
openshift-kube-controller-manager-operator   kube-controller-manager-operator-588b74d4fb-fkjj2          0/1     CrashLoopBackOff    111        13h
openshift-kube-scheduler                     openshift-kube-scheduler-rhhi-master-0                     0/1     CrashLoopBackOff    11         73m
openshift-monitoring                         prometheus-k8s-0                                           0/6     ContainerCreating   1          5h8m
openshift-monitoring                         prometheus-k8s-1                                           0/6     ContainerCreating   1          7h10m
openshift-sdn                                sdn-controller-drdn7                                       0/1     CrashLoopBackOff    110        13h
[root@titan57 ~]# sudo systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)


oc describe pod sdn-controller-drdn7 -n openshift-sdn
Name:               sdn-controller-drdn7
Namespace:          openshift-sdn
Priority:           0
PriorityClassName:  <none>
Node:               rhhi-master-0/192.168.126.11
Start Time:         Wed, 06 Feb 2019 23:43:39 +0200
Labels:             app=sdn-controller
                    controller-revision-hash=5c968cf5ff
                    pod-template-generation=1
Annotations:        <none>
Status:             Running
IP:                 192.168.126.11
Controlled By:      DaemonSet/sdn-controller
Containers:
  sdn-controller:
    Container ID:  cri-o://723c72223588984228afe933db821f32ffc6dc8539417d8fa7fd6b6e0e616897
    Image:         registry.svc.ci.openshift.org/openshift/origin-v4.0-2019-02-06-200409@sha256:a3e3f16ed997d16de00d99e9181fcab676a7cdd0f1b8bd99b432bf0092754b6a
    Image ID:      registry.svc.ci.openshift.org/openshift/origin-v4.0-2019-02-06-200409@sha256:a3e3f16ed997d16de00d99e9181fcab676a7cdd0f1b8bd99b432bf0092754b6a
    Port:          <none>
    Host Port:     <none>
    Command:
      hypershift
      openshift-network-controller
    Args:
      --config=/config/controller-config.yaml
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   cal:6443/apis/network.openshift.io/v1/netnamespaces?limit=500&resourceVersion=0: dial tcp 192.168.126.11:6443: connect: connection refused
E0207 11:11:38.697678       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Namespace: Get https://rhhi-api.redhat.local:6443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 192.168.126.11:6443: connect: connection refused
E0207 11:11:38.700121       1 reflector.go:134] github.com/openshift/client-go/network/informers/externalversions/factory.go:101: Failed to list *v1.HostSubnet: Get https://rhhi-api.redhat.local:6443/apis/network.openshift.io/v1/hostsubnets?limit=500&resourceVersion=0: dial tcp 192.168.126.11:6443: connect: connection refused
E0207 11:11:38.702085       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Node: Get https://rhhi-api.redhat.local:6443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 192.168.126.11:6443: connect: connection refused
E0207 11:11:46.435150       1 event.go:259] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil), BinaryData:map[string][]uint8(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'rhhi-master-0 stopped leading'
I0207 11:11:46.435452       1 leaderelection.go:249] failed to renew lease openshift-sdn/openshift-network-controller: failed to tryAcquireOrRenew context deadline exceeded
F0207 11:11:46.435554       1 network_controller.go:82] leaderelection lost

      Exit Code:    255
      Started:      Thu, 07 Feb 2019 13:10:44 +0200
      Finished:     Thu, 07 Feb 2019 13:11:46 +0200
    Ready:          False
    Restart Count:  110
    Requests:
      cpu:     10m
      memory:  50Mi
    Environment:
      KUBERNETES_SERVICE_PORT:  6443
      KUBERNETES_SERVICE_HOST:  rhhi-api.redhat.local
    Mounts:
      /config from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from sdn-controller-token-fsfjh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sdn-controller-config
    Optional:  false
  sdn-controller-token-fsfjh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sdn-controller-token-fsfjh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/not-ready:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason   Age                     From                    Message
  ----     ------   ----                    ----                    -------
  Warning  BackOff  4m48s (x2200 over 13h)  kubelet, rhhi-master-0  Back-off restarting failed container

**Comment by e-minguez** [comment]
I've been having those issues as well and I think it is related to lack of resources on the master host. I've been able to successfully create the cluster with >16gb ram and >4 cores in the master host.
I'm not sure if it is related, just my 2 cents.

**Comment by steven-ellis** [comment]
Might this relate to #1041

**Comment by eparis** [comment]
closing as this does feel a bit like a dup of #1041
