### ISSUE TITLE
Untagged NAT gateways leading to deprovision infinite loops

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#1216]
We've seen this several times in Hive clusters where sometimes, a deprovision gets stuck with errors like:

```
DEBU[2019-02-08T09:38:12-04:00] deleting arn:aws:ec2:us-east-1:125931421481:subnet/subnet-0a7a9a886dbcef6b6: DependencyViolation: The subnet 'subnet-0a7a9a886dbcef6b6' has dependencies and cannot be deleted.
        status code: 400, request id: 7a940c04-6896-4023-8967-c3e675571797 
DEBU[2019-02-08T09:38:13-04:00] deleting arn:aws:ec2:us-east-1:125931421481:dhcp-options/dopt-00847e523a5d7c3bb: DependencyViolation: The dhcpOptions 'dopt-00847e523a5d7c3bb' has dependencies and cannot be deleted.
        status code: 400, request id: ad9cb74f-1c06-4f8b-8771-eddb8328df34 
DEBU[2019-02-08T09:38:13-04:00] deleting arn:aws:ec2:us-east-1:125931421481:elastic-ip/eipalloc-00d992909bd9f71d8: AuthFailure: You do not have permission to access the specified resource.
        status code: 400, request id: d07f5ee5-d454-4fae-89cd-a9caebe1d6ea 
```

The problem appears to be NAT gateways that sometimes do not get any tags. It appears that when it happens, possibly *all* NAT gateways for that cluster are affected, I have 6 untagged all attached to the same VPC in my AWS account for this failure.

**Comment by abhinavdahiya** [comment]
Do you have the `.openshift-install.log` from the run

**Comment by dgoodwin** [comment]
Unfortunately I don't think so, we run installer in a pod and this is not one of the artifacts we upload to configmap. Can't reliably reproduce either.

**Comment by abhinavdahiya** [comment]
> Unfortunately I don't think so, we run installer in a pod and this is not one of the artifacts we upload to configmap. Can't reliably reproduce either.

Hmm :( 

Will keep it open to see if someone else ends up in this situation.

**Comment by jaywryan** [comment]
I have this issue on trying to cleanup a failed cluster install.  The EC2 instances are tagged correctly but they are not being deleted.  If I manually delete the EC2s the destroy completes as expected.  The EC2's do have a TAG that was put on the resource by a reaperbot, I can't think that would have anything to do with it, but its the only thing out of the "stock" install that is present.

**Comment by wking** [comment]
> The EC2 instances....

This issue is about NAT gateways, not instances.  File a separate issue with your full `.openshift_install.log`?

**Comment by abhinavdahiya** [comment]
haven't seen these anymore. feel free to reopen if needed.

/close
