### ISSUE TITLE
Unable to Run Smoke Tests

### ISSUE THREAD

**Issue by danehans** [openshift/installer#1228]
# Version

```console
$ ./bin/openshift-install version
./bin/openshift-install unreleased-master-248-g08afe7edc9729494966b4a43804e44a96a464803
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

I followed the [instructions](https://github.com/openshift/installer/tree/master/tests) for running smoke tests and I get the following error:
```
$ pwd
/Users/daneyonhansen/code/go/src/github.com/openshift/installer
$ ./tests/run.sh aws
generate a universally unique identifier
usage: uuidgen [-hdr]
	-hdr	emit result in form suitable for copying into a header
\e[36m Starting build process...\e[0m
ERROR: The 'build' command is only supported from within a workspace.
```

I create an empty WORKSPACE at the project root and I get the following error:
```
$ touch WORKSPACE
$ ./tests/run.sh aws
generate a universally unique identifier
usage: uuidgen [-hdr]
	-hdr	emit result in form suitable for copying into a header
\e[36m Starting build process...\e[0m
Loading: 
Loading: 0 packages loaded
ERROR: couldn't determine target from filename 'smoke_tests'
INFO: Elapsed time: 0.091s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I do not see any bazel files in the project repo.

# What you expected to happen?

A successful smoke test run.

# How to reproduce it (as minimally and precisely as possible)?

- Clone the project repo and cd into the repo.
- Follow the instructions for running smoke tests.

# Anything else we need to know?

Bazel version:
```
$ bazel version
Build label: 0.9.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jul 12 03:29:57 +49936 (1513677382197)
Build timestamp: 1513677382197
Build timestamp as int: 1513677382197
```

# References

- [Bazel Workspaces](https://docs.bazel.build/versions/master/build-ref.html#workspace)
- I see [this commit](https://github.com/openshift/installer/commit/0c6d53b7d6108b00f2cfb5116ee810fef0e10a47) removed bazel artifacts from the project repo. If bazel is not being used, what are the steps to run e2e tests against an openshift cluster installed in aws using `openshift-install`?

**Comment by wking** [comment]
Smoke tests are currently dead code while we decide if they add anything beyond the current e2e suite.  Personally, I'm fine dropping that directory.  @abhinavdahiya, @crawford?

**Comment by abhinavdahiya** [comment]
We have removed the old smoke tests.
