### ISSUE TITLE
Unable to Create a Sample App

### ISSUE THREAD

**Issue by danehans** [openshift/installer#1236]
# Version

```console
$ openshift-install version
openshift-install v0.12.0
```

# Platform (aws|libvirt|openstack):

aws

# What happened?
After running the `new-app` command to create an example app, I receive a WARNING message that a Docker registry has not been configured:
```
$ oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
<SNIP>
    WARNING: No Docker registry has been configured with the server. Automatic builds and deployments may not function.
    Build scheduled, use 'oc logs -f bc/nodejs-ex' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/nodejs-ex' 
    Run 'oc status' to view your app.
```

It appears the `image-registry-private-configuration-user` secret required by the cluster-image-registry-operator is not being created:
```
$ oc logs cluster-image-registry-operator-6d6b45bfdf-mt856 -n openshift-image-registry
E0212 03:37:49.763547       1 controller.go:208] unable to sync: unable to apply objects: failed to create object *v1.Secret, Namespace=openshift-image-registry, Name=image-registry-private-configuration: unable to get cluster minted credentials "kube-system/installer-cloud-credentials": secrets "image-registry-private-configuration-user" not found, requeuing
```

The above event continues to be requeued because the secret never gets created by the installer:
```
$ oc get secret/installer-cloud-credentials -n openshift-image-registry
No resources found.
Error from server (NotFound): secrets "installer-cloud-credentials" not found
```

# What you expected to happen?

Successfully create the sample app.

# How to reproduce it (as minimally and precisely as possible)?

- Follow the steps in https://cloud.openshift.com/clusters/install to create an OpenShift 4 cluster on AWS.
- Verify access to the API and web console.
- Create a sample app: `oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp`.

# Anything else we need to know?

- No

# References

- [code link](https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/clusterconfig/clusterconfig.go#L107-L123)

**Comment by eparis** [comment]
I'm going to close this report as the install team is unable to help in this area. Please open a bugzilla against the 'registry' component to get help in this area.
