### ISSUE TITLE
libvirt: Fails to complete installation

### ISSUE THREAD

**Issue by DarkBlaez** [openshift/installer#1248]
Followed instructions: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md
Fedora 29 Server
libvirt
32GB RAM and 8vCPUs
unreleased-master-281-g4bd58eb3d5a82058175d86f23ac6401aa70393a6

? Platform libvirt
? Libvirt Connection URI qemu+tcp://192.168.122.1/system
? Base Domain devcluster.com
? Cluster Name dev
? Pull Secret [? for help]

INFO Creating cluster...NFO Fetching OS image: redhat-coreos-maipo-47.315-qemu.qcow2.gz
INFO Waiting up to 30m0s for the Kubernetes API...
FATAL waiting for Kubernetes API: context deadline exceeded

Seems to be reproducible under libvirt

DEBUG Still waiting for the Kubernetes API: Get https://dev-api.devcluster:6443/version?timeout=32s: dial tcp: lookup dev-api.devcluster on 127.0.0.1:53: no such host

Thanks
DB-

**Comment by bbalakriz** [comment]
I encountered the same issue and was able to overcome that with [this](https://github.com/openshift/installer/issues/653#issuecomment-444514082)?

**Comment by zeenix** [comment]
I guess this is resolved by now so I'm closing already. If not, it's probably a dup of #1428.

/close
