### ISSUE TITLE
libvirt: FATAL waiting for bootstrap-complete: timed out waiting for the condition

### ISSUE THREAD

**Issue by bbalakriz** [openshift/installer#1257]
# Version

```console
$ bin/openshift-install version
bin/openshift-install unreleased-master-311-g0b656ae253743be4643626602ee2d6f6c45c1137-dirty
```

# Platform (aws|libvirt|openstack):
libvirt

# What happened?

Installation failed with the error

```
WARNING Failed to connect events watcher: Get https://cluster-0-api.bala:6443/api/v1/namespaces/kube-system/events?resourceVersion=3096&watch=true: dial tcp 192.168.126.10:6443: connect: connection refused 
WARNING Failed to connect events watcher: Get https://cluster-0-api.bala:6443/api/v1/namespaces/kube-system/events?resourceVersion=3096&watch=true: dial tcp 192.168.126.10:6443: connect: connection refused 
FATAL waiting for bootstrap-complete: timed out waiting for the condition 
```

# What you expected to happen?

Installation should have succeeded.

# How to reproduce it (as minimally and precisely as possible)?

This is consistently reproducible by following the steps given in the instructions given in [libvirt-howto.md](https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md) 

```console
$ bin/openshift-install create cluster --dir cluster-0
? Platform libvirt
? Libvirt Connection URI qemu+tcp://10.142.0.2/system
? Base Domain bala
? Cluster Name cluster-0
? Pull Secret [? for help] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
```

# Anything else we need to know?

Debian GNU/Linux 9.7 (stretch)
openshift_install.log - https://gist.github.com/bbalakriz/3e91375f50fba35f4b23d7dfd3b9f997
Have set up networkmanager dns overlay as given in the instructions.

**Comment by bbalakriz** [comment]
Issue resolved. NetworkManager didn't work as expected. So, removed it and used dnsmasq directly instead and the installation moved on.

**Comment by pcuzner** [comment]
@bbalakriz I'm hitting the same problem. Can you be more specific about the changes you made? I'm assuming you removed the config items added to Network Manager, and set up dnsmasq - so could you provide the config you used as an example?

**Comment by bbalakriz** [comment]
> @bbalakriz I'm hitting the same problem. Can you be more specific about the changes you made? I'm assuming you removed the config items added to Network Manager, and set up dnsmasq - so could you provide the config you used as an example?

Here's what I did. 

```
> sudo apt-get remove --purge network-manager
> sudo apt-get install dnsmasq

> sudo vi /etc/dnsmasq.conf 	
# Performed the following configs
# 1. uncommented the param 'strict-order'
# 2. added an entry for the parameter 'server' like this:
server=/tt.testing/192.168.126.1

> sudo vi /etc/dhcp/dhclient.conf 
# Added the following config
prepend domain-name-servers 192.168.126.1;
```
Then, 
a.) Restarted the host and checked /etc/resolv.conf to confirm that the name server 192.168.126.1 has got listed in this file.
b.) [Cleaned-up](https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#cleanup) the failed cluster (_both openshift-install destroy cluster + virsh-cleanup.sh_) and re-run the 'create cluster'. 

Hope this helps.

**Comment by zeenix** [comment]
@bbalakriz is this still reproducible?

**Comment by zeenix** [comment]
@bbalakriz if this is still reproducible, please reopen.

/close
