### ISSUE TITLE
AWS_Region env var is different from AWS CLI Region Variable (its confusing)

### ISSUE THREAD

**Issue by sferich888** [openshift/installer#1258]
https://github.com/openshift/installer/blob/a71a531178b9e5ac8272cf3deadad03eab523f47/data/data/aws/main.tf#L10 uses AWS_REGION while the AWS CLI uses AWS_DEFAULT_REGION which is confusing and or a nuisance as you have to set the information twice to keep the CLI and the installer in sync. 

See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html for more information on the cli variables.

**Comment by staebler** [comment]
I am confused about this. The installer should not be using AWS_REGION at all. The variable that your link references is filled out from the region specified in your install-config.yaml.

**Comment by crawford** [comment]
You can use `AWS_DEFAULT_REGION` as well. The Terraform code you linked, @sferich888, has little to do with the [AWS SDK](https://github.com/aws/aws-sdk-go/blob/60293cacbc1ed27eb78374e1b24a3ea55a74d1b6/aws/session/env_config.go#L36) we use. The variable you linked would be set with `TF_VAR_aws_region`, but you never actually want to do that.
