### ISSUE TITLE
Replace fetching router-ca secret with router-ca configmap to get default router crt

### ISSUE THREAD

**Issue by sallyom** [openshift/installer#1261]
# Platform: all

There have been reports of router-ca configmap not being created, due to ingress-operator reconciliation errors. This will be resolved when [this](https://github.com/openshift/cluster-ingress-operator/pull/118) lands, so ingress-operator will publish `router-ca` even if reconciliation has errors.

Until then, since CI depends on router CA being added to kubeconfig, to ensure 
`oc login -u kubeadmin -p blah` succeeds, we will fetch router-ca secret (that should always exist, and if it doesn't that's an error).
see: https://github.com/openshift/installer/pull/1260

In the future, it's possible that router-ca configmap will be absent (but only if launching with a custom default router crt). However, in our internal CI, this should never be the case (and it won't once that ingress-operator fix is in).

Before adding the ability to launch with a custom default router crt, this switch to fetching configmap must be made (because we don't want to add our router crt to kubeconfig in that case).

**Comment by sallyom** [comment]
here's the substitutions in cmd/openshift-install/create.go  for future ref:
```	// TODO: replace secret with configmap when this merges https://github.com/openshift/cluster-ingress-operator/pull/118
	// Configmap may not exist. log and accept not-found errors with configmap.
	//caConfigMap, err := client.CoreV1().ConfigMaps("openshift-config-managed").Get("router-ca", metav1.GetOptions{})
	routerCASecret, err := client.CoreV1().Secrets("openshift-ingress-operator").Get("router-ca", metav1.GetOptions{})
	if err != nil {
		if apierrors.IsNotFound(err) {
			// TODO: uncomment/replace once switch to configmap. If configmap not found, not necessarily an error
			//logrus.Infof("router CA not found in cluster, perhaps you configured your router to use a custom default certificate")
			//return nil
			return errors.New("router CA secret not found in openshift-ingress-operator namespace")
		}
		// TODO: replace secret with configmap
		//return errors.Wrap(err, "fetching router-ca configmap from openshift-config-managed namespace")
		return errors.Wrap(err, "fetching router-ca secret from openshift-ingress-operator namespace")
	}

	// TODO: replace secret with configmap
	//routerCrtBytes := []byte(caConfigMap.Data["ca-bundle.crt"])
	routerCrtBytes := routerCASecret.Data["tls.crt"]
```

**Comment by abhinavdahiya** [comment]
It doesn't seem like this is required anymore.
/close
