### ISSUE TITLE
AWS install fails: IAM instance profile already exists

### ISSUE THREAD

**Issue by michaelgugino** [openshift/installer#1265]
# Version

```console
$ ./bin/openshift-install version
./bin/openshift-install unreleased-master-340-g54506be98cff773ed6ef60b18db0e26d9f7f618f-dirty
[mgugino@mguginop50 installer]$ git status
HEAD detached at upstream/master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   data/data/libvirt/variables-libvirt.tf

```

Note, above changes are for RAM and CPU of libvirt install, this bug is for AWS install.

# Platform (aws|libvirt|openstack):

AWS

# What happened?

Can't create a new cluster because openshift-install destroy cluster apparently leaves artifacts unaccounted for.

# How to reproduce it (as minimally and precisely as possible)?

Had a cluster.  Ran 'openshift-install destroy cluster' (cluster may have been offline due to autokiller, unsure).

Updated code to latest master.  Built, ran openshift-install create cluster.  Complained about existing iam stuff.  Ran destroy cluster, not much happend.  Ran create cluster, complained about existing tfvars.  Renamed tfvars file.  Rinse repeat.

**Comment by eparis** [comment]
you have to delete this manually. For example:
`aws --region=eu-west-2 iam delete-instance-profile --instance-profile-name eparis1-worker-profile`

DPP deleted the instance and role after 48h, but not the instance profile (please stop leaving clusters up 48hours). This is a bug in the dpp cleanup.

**Comment by michaelgugino** [comment]
I think the installer should clean up the instance profiles if the installer creates them.  Regardless of whether or not something or someone else messes with the cluster at some point.

Spinning up a cluster and getting it to the point where I can do actual work takes about an hour.  We need a development workflow that takes 5 minutes.

**Comment by crawford** [comment]
If I understand the problem correctly, there is no way for us to safely find and remove instance profiles after the instances have been deleted. This is a limitation with AWS as they don't support tagging. Unfortunately, my recommendation is going to be to bug DPP. OCP IPI impies IDI (installer deprovisioned infrastructure) and the installer needs to own the process.

**Comment by eparis** [comment]
it would be nice, but you can't add AWS labels or anything to instance profiles. so we have no way to know when you run destroy if that instance profile really belongs to the cluster you are trying to destroy or not :-(

**Comment by eparis** [comment]
the install destroy could have --dangerous flag that does this....

**Comment by danehans** [comment]
I am hitting the same issue using latest master (`3e8831844`). Error from insatller:
```
INFO Creating cluster...                          ***************************************************************************************************************ERROR                                              **************************************************************************************************************ERROR Error: Error applying plan:                  
ERROR                                              
ERROR 2 errors occurred:                           
ERROR 	* module.iam.aws_iam_instance_profile.worker: 1 error occurred: 
ERROR 	* aws_iam_instance_profile.worker: Error creating IAM instance profile dhansen-worker-profile: EntityAlreadyExists: Instance Profile dhansen-worker-profile already exists. 
ERROR 	status code: 409, request id: d14220a0-339b-11e9-a101-4bee234095ad 
ERROR                                              
ERROR                                              
ERROR 	* module.masters.aws_iam_instance_profile.master: 1 error occurred: 
ERROR 	* aws_iam_instance_profile.master: Error creating IAM instance profile dhansen-master-profile: EntityAlreadyExists: Instance Profile dhansen-master-profile already exists. 
ERROR 	status code: 409, request id: d144b8c9-339b-11e9-bad7-7bc2a6c6c0e6 
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR Terraform does not automatically rollback in the face of errors. 
ERROR Instead, your Terraform state file has been partially updated with 
ERROR any resources that successfully completed. Please address the error 
ERROR above and apply again to incrementally change your infrastructure. 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
```

I destroy the cluster and verify the profiles were successfully removed, but I hit the same error when I reinstall. I can see the installer requesting the worker/master profiles to be created:
```
time="2019-02-18T08:39:53-08:00" level=debug msg="module.iam.aws_iam_instance_profile.worker: Creating..."
time="2019-02-18T08:39:53-08:00" level=debug msg="  arn:         \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  create_date: \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  name:        \"\" => \"dhansen-worker-profile\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  path:        \"\" => \"/\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  role:        \"\" => \"dhansen-worker-role\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  roles.#:     \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  unique_id:   \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="module.iam.aws_iam_role_policy.worker_policy: Creating..."
time="2019-02-18T08:39:53-08:00" level=debug msg="  name:   \"\" => \"dhansen_worker_policy\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  policy: \"\" => \"{\\n  \\\"Version\\\": \\\"2012-10-17\\\",\\n  \\\"Statement\\\": [\\n    {\\n      \\\"Effect\\\": \\\"Allow\\\",\\n      \\\"Action\\\": \\\"ec2:Describe*\\\",\\n      \\\"Resource\\\": \\\"*\\\"\\n    }\\n  ]\\n}\\n\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  role:   \"\" => \"dhansen-worker-role\""
<SNIP>
time="2019-02-18T08:39:53-08:00" level=debug msg="  role:   \"\" => \"dhansen-bootstrap-role\""
time="2019-02-18T08:39:53-08:00" level=debug msg="module.masters.aws_iam_instance_profile.master: Creating..."
time="2019-02-18T08:39:53-08:00" level=debug msg="  arn:         \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  create_date: \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  name:        \"\" => \"dhansen-master-profile\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  path:        \"\" => \"/\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  role:        \"\" => \"dhansen-master-role\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  roles.#:     \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="  unique_id:   \"\" => \"<computed>\""
time="2019-02-18T08:39:53-08:00" level=debug msg="module.masters.aws_iam_role_policy.master_policy: Creating..."
time="2019-02-18T08:39:53-08:00" level=debug msg="  name:   \"\" => \"dhansen_master_policy\""
<SNIP>
```

However, `bootstrap` is the only profile `Creation complete` event I see:
```
time="2019-02-18T08:39:54-08:00" level=debug msg="module.bootstrap.aws_iam_instance_profile.bootstrap: Creation complete after 1s (ID: dhansen-bootstrap-profile)"
```

**Comment by danehans** [comment]
I worked around this issue by creating a cluster with a different name.

**Comment by michaelgugino** [comment]
> it would be nice, but you can't add AWS labels or anything to instance profiles. so we have no way to know when you run destroy if that instance profile really belongs to the cluster you are trying to destroy or not :-(

@eparis We should give them a name such as '<cluster-id>-<cluster-name>-instance-whatever'  And it should be simple to cleanup on name-based case.  UUIDs should be unique for each cluster, so should be doable.  If we're keeping around a 'tfstate' file then we might as well keep around other information about what we actually created as well.  No need to arbitrarily tie our hands because terraform doesn't want to keep track of assets.

**Comment by eparis** [comment]
@danehans you have to delete this manually if you left your cluster up unused for so long that DPP deleted it for you. For example:
`aws --region=eu-west-2 iam delete-instance-profile --instance-profile-name eparis1-worker-profile`

**Comment by wking** [comment]
Dup of #1174.

/close
