### ISSUE TITLE
RFE: Support for spot and reserved instances on AWS

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/installer#1287]
# Version

```console
$ ./openshift-install version
./openshift-install v0.12.0
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

Installer uses on-demand instances for all nodes in the cluster, m4.large for workers and m4.xlarge for masters, by default. 

# What you expected to happen?

Would be interesting to have an option on installer to use reserved instances for the master nodes, and spot instances for the workers, improving overall cost of the environment. The MachineSet should be able to respond for the spot termination events, executing the drain of the node and creating a new node.

# References

 This configuration is technically possible with community installers like `kops`, or other distributions like `rancher` or `AWS EKS`.

- https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md
- https://rancher.com/reducing-aws-spend
- https://aws.amazon.com/blogs/compute/run-your-kubernetes-workloads-on-amazon-ec2-spot-instances-with-amazon-eks/

**Comment by debianmaster** [comment]
+1

**Comment by ashishxooa** [comment]
+1

**Comment by mikee** [comment]
+1

**Comment by abhinavdahiya** [comment]
The installer cannot support these types if instance type as we have to follow and contraint ourselves to the machine-api. https://github.com/kubernetes-sigs/cluster-api-provider-aws

So probably see if the upstream machine-api would support these features and then we can try to provide those as an option for atleast day-2 compute nodes and not necessarily during install.

**Comment by paulhanatupstart** [comment]
+1

**Comment by smarterclayton** [comment]
Why would the machine API not support these?  These seem pretty fundamental to use of cloud providers.

One note, we are moving to a world where masters are not static and can be replaced at will.  But even in that case, you'd still want to pull from a reserved instances pool.

In the short term, UPI master config should work exactly the same as this, and compute pools should be able to set it.

**Comment by sapkra** [comment]
Maybe it would be a good idea to upvote the issue instead of writing comments with `+1`. The guys at RedHat could then sort for the most wanted feature and find this one.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/enhancements/pull/199 is working in adding spot instance support to machine-api

When that's complete, it should allow installer to support a knob for compute.

**Comment by sapkra** [comment]
Seems to be implemented into the MachineProviderConfig now:
https://github.com/openshift/cluster-api-provider-aws/pull/306

Will it now be possible to just use them in the `install-config.yaml`? If so, how would it be possible? If it's not the case yet what needs to be implemented to make it work?

**Comment by rasheedamir** [comment]
@abhinavdahiya now which version of OpenShift will add support for it?

**Comment by rasheedamir** [comment]
@smarterclayton when will this be supported in OpenShift?

> One note, we are moving to a world where masters are not static and can be replaced at will. 

It has been in `kops` and other flavors for ages now

**Comment by JoelSpeed** [comment]
> @JoelSpeed Will it now be possible to just use them in the install-config.yaml? If so, how would it be possible? If it's not the case yet what needs to be implemented to make it work?

This isn't planned to be supported straight through the installer, initial Machines and MachineSets will still be created as on-demand. When running spot, you should mix your workloads across multiple instance types and multiple availability zones, and also have the ability to fall back to on-demand should you need to. So I personally don't think exposing this through the installer, thus promoting spot only clusters, is a good idea.

You can however, from OpenShift 4.5, create additional MachineSets that will run on spot on AWS. Within the `providerSpec.value` you can add `spotMarketOptions: {}` to make instances from that MachineSet be created as spot.

We are also adding this support for Azure and GCP in the 4.6 release.

> One note, we are moving to a world where masters are not static and can be replaced at will.

It is generally not recommended to run control plane machines on spot instances due to the potential volatility of the instances and the potential to break your cluster when instances are removed. Currently in OpenShift, there is no automation to replace a control plane instance should it be removed. We are working on this and I believe this automation may land in 4.7. Even then, I would still recommend against control plane on spot. Spot is much more aligned with running batch jobs or stateless workloads.

**Comment by davivcgarcia** [comment]
/remove-lifecycle stale

@JoelSpeed Could you please share a full example of a MachineSet using spot-instances on AWS? I've tried to follow your instructions without much success. Also, I think it would be great to have this feature explained in the docs.

**Comment by JoelSpeed** [comment]
This is now documented in the openshift docs, have you seen this already? If so, did it not help? 
https://docs.openshift.com/container-platform/4.6/machine_management/creating_machinesets/creating-machineset-aws.html#machineset-creating-non-guaranteed-instance_creating-machineset-aws

**Comment by davivcgarcia** [comment]
> This is now documented in the openshift docs, have you seen this already? If so, did it not help?

Yes, I saw that doc but was not very helpful due to the lack of a full example. I found the following blog post with more details and I was able to successfully configure it.

https://www.openshift.com/blog/cost-saving-with-amazon-ec2-spot-instances-for-red-hat-openshift-4.5

**Comment by JoelSpeed** [comment]
Do you have any suggestion how we could improve the docs here? It shows an example of putting the value into the `providerSpec` already, would having more fields around that make it more clear? I can raise this with the docs team if you have a suggestion for improvement 🙂

**Comment by davivcgarcia** [comment]
> Do you have any suggestion how we could improve the docs here? It shows an example of putting the value into the `providerSpec` already, would having more fields around that make it more clear? I can raise this with the docs team if you have a suggestion for improvement

I think we should clarify what are the available fields inside spotMarketOptions, and an example using them. I also think we should mention how to gracefully handle termination events for OCP nodes, maybe using the https://github.com/aws/aws-node-termination-handler.

**Comment by JoelSpeed** [comment]
Thanks for the feedback, I think your concerns are actually covered in the existing documentation, but perhaps not in a clear way. I helped write the docs so I'm obviously a little blinded when it comes to how readable they are.

To answer those questions directly before I follow up with the docs team,

> I think we should clarify what are the available fields inside spotMarketOptions, and an example using them.

There is only one field within the `spotMarketOptions`, which is mentioned below the yaml example on the link I sent in my previous comment, I've copied it below. We chose to make it a separate comment as it is recommended by default to not use a `maxPrice`, the recommendation is to just use the naked `spotMarketOptions: {}` for best performance.

> You can optionally set the spotMarketOptions.maxPrice field to limit the cost of the Spot Instance. For example you can set maxPrice: '2.50'.

To your second point:

>  I also think we should mention how to gracefully handle termination events for OCP nodes

In the [section above](https://docs.openshift.com/container-platform/4.6/machine_management/creating_machinesets/creating-machineset-aws.html#machineset-non-guaranteed-instance_creating-machineset-aws) the one I previously linked, we describe termination events and mention that we already deploy a termination handler to VMs, so there is nothing for users to do here, we automated that for them.

I will try to think about how we can make this clearer to the reader

**Comment by alexanderniebuhr** [comment]
This might be a bit biased but I think an example of how to make a machine set with dynamic instance types e.g. for an flexible workload, as AWS allows you to set in their console (sorry for German ui) would be helpful, or am I missing some doc here?

<img width="1088" alt="Bildschirmfoto 2020-12-10 um 14 17 40" src="https://user-images.githubusercontent.com/45965090/101777488-d7af0400-3af2-11eb-8e2f-7cdc92c4e144.png">
<img width="1076" alt="Bildschirmfoto 2020-12-10 um 14 18 11" src="https://user-images.githubusercontent.com/45965090/101777484-d67dd700-3af2-11eb-84f7-c986d90778ac.png">

**Comment by JoelSpeed** [comment]
We don't yet support dynamic instance types as this would break many assumptions that various components within openshift make at present. We are aware that this is a desirable feature but have not had time to prioritise it yet.
