### ISSUE TITLE
Changelog merged but no new pre-release present?

### ISSUE THREAD

**Issue by DanyC97** [openshift/installer#1312]
@wking i see the [changelog](https://github.com/openshift/installer/pull/1270) PR was merged however i don't see a new pre-release?

Is that in progress and on its way ?

**Comment by wking** [comment]
There was some confusion about which installer commit to use and about the reliability of the proposed release image; see discussion in #1271.  I've just filed #1316 with an updated change log in preparation for a new release today (hopefully :).  But #1271 will track the next release, whenever it ends up happening.

**Comment by DanyC97** [comment]
thanks a bunch for speedy response!
