### ISSUE TITLE
Operator install error when pulling from registry.connect.redhat.com

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/installer#1320]
# Version

```console
$ ./openshift-install version
./openshift-install v0.13.0
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

The cluster does not have proper authentication credentials (service account) to access Red Hat Connect Registry (partners). When trying to deploy the MondoDB Operator, from Operator Hub, but the install stays in `InstallWaiting` and then `Error`. Checking the operator pod, it is reporting `ImagePullBackOff`:

```
Failed to pull image "registry.connect.redhat.com/mongodb/enterprise-operator": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password
```

# What you expected to happen?

Operator being installed successfully.

# How to reproduce it (as minimally and precisely as possible)?

1. On Operator Hub page, install MongoDB.
2. On `openshift-operator` project, check for the `mongodb-enterprise-operator` pod events.

# Anything else we need to know?

The problem does not affect, for example, the Etcd or AMQ Streams operators because the container images are being pulled from different registries (`quay.io` and `registry.access.redhat.com`):

```
Successfully pulled image "quay.io/coreos/etcd-operator@sha256:c0301e4686c3ed4206e370b42de5a3bd2229b9fb4906cf85f3f30650424abec2"

Successfully pulled image "registry.access.redhat.com/amqstreams-1/amqstreams10-clusteroperator-openshift:1.0.0"
```

**Comment by e-minguez** [comment]
Try to regenerate your token from try.openshift.com. I did regenerate and now includes the registry.connect.redhat.com token as well.

**Comment by davivcgarcia** [comment]
Thanks @e-minguez, I downloaded again the `pull-secret.txt` from `try.openshift.com` and the file is way bigger than the previous one, including authentication credentials for multiple registries. Do you know if we have an operator to reapply the new content to the hosts without the need to redeploy the cluster?

**Comment by e-minguez** [comment]
Unfortunately I have no idea... but I think your best chance is to redeploy it.

**Comment by wking** [comment]
We pass the pull secret in [here][1], so try updating the `kube-system/coreos-pull-secret` secret.  I dunno if that's actively monitored though; you may need to cycle compute nodes to get them to notice (and kick masters by hand, until we support cycling them too).

[1]:nhttps://github.com/openshift/installer/blob/958724a513627404b18532ec2d6a7245e428e824/data/data/manifests/bootkube/pull.yaml.template

**Comment by abhinavdahiya** [comment]
> We pass the pull secret in here, so try updating the `kube-system/coreos-pull-secret` secret. I dunno if that's actively monitored though; you may need to cycle compute nodes to get them to notice (and update masters by hand, until we support cycling them too).

It should, and if it doesn't try opening issue on https://github.com/openshift/machine-config-operator/issues/new
