### ISSUE TITLE
Cluster operator ingress has not yet reported success 

### ISSUE THREAD

**Issue by Jooho** [openshift/installer#1324]
# Version

```console
$ openshift-install version
./openshift-install v0.13.0
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

Installation failed.
```
DEBUG Still waiting for the cluster to initialize: Cluster operator ingress has not yet reported success 
DEBUG Still waiting for the cluster to initialize: Cluster operator monitoring is reporting a failure: Failed to rollout the stack. Error: running task Updating configuration sharing failed: failed to retrieve Prometheus host: getting Route object failed: the server is currently unable to handle the request (get routes.route.openshift.io prometheus-k8s) 
```

# What you expected to happen?

Install OCP4 successfully.

# How to reproduce it (as minimally and precisely as possible)?

build v0.13.0 openshift installer and create a cluster

```console
$ ./openshift-install-lib  create cluster --log-level=debug --dir=./lib
```

# Anything else we need to know?

nope

# References

- enter text here.

**Comment by Jooho** [comment]
Master log keep throwing this kind of messages
```
Feb 27 20:15:15 ocp4-r7vf7-master-0 hyperkube[3522]: ; err: exit status 1, extraDiskErr: du command failed on /var/log/pods/71f6e324-3ac9-11e9-aba3-664f163f5f0f/console/5.log with output stdout: , stderr: du: cannot access ‘/var/log/pods/71f6e324-3ac9-11e9-aba3-664f163f5f0f/console/5.log’: No such file or directory
```

**Comment by wking** [comment]
Is this an issue with the router?  With monitoring?  Can you dig into the logs (see [here][1] for notes on getting the machine-API logs, although you'll want to look at router, monitoring, and ingress containers)?  Can you get the `ClusterOperator` objects (more on that in flight in #1329)?

[1]: https://github.com/openshift/installer/blob/13d11584e5e8f2d0c61e2ab50494f08ad68f2e52/docs/user/troubleshooting.md#no-worker-nodes-created

**Comment by ssbano** [comment]
Hi,

There is a workaround

#1397

**Comment by abhinavdahiya** [comment]
ingress operator should be reaching available level now. 

/close

Feel free to reopen if you are still seeing this issue
