### ISSUE TITLE
Segmentation Fault in 0.13.0 and Fedora 29

### ISSUE THREAD

**Issue by jsm84** [openshift/installer#1336]
# Version

```console
$ openshift-install version
openshift-install v0.13.0

$ go version
go version go1.11.5 linux/amd64
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

$ openshift-install create cluster

WARNING Discarding the "Terraform Variables" that was provided in the target directory because its dependencies are dirty and it needs to be regenerated 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x3bd388e]

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/ignition/bootstrap.(*Bootstrap).getTemplateData(0xc0006c76b0, 0xc000492f00, 0x1, 0x1, 0x3)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/pkg/asset/ignition/bootstrap/bootstrap.go:172 +0x3e
github.com/openshift/installer/pkg/asset/ignition/bootstrap.(*Bootstrap).Generate(0xc0006c76b0, 0xc0009781e0, 0xc00111b7c0, 0x2)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/pkg/asset/ignition/bootstrap/bootstrap.go:119 +0xbc
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc000932f90, 0x5602b60, 0xc0006c76b0, 0x5050571, 0x2, 0x5050571, 0x2)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/pkg/asset/store/store.go:226 +0x7e7
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc000932f90, 0x5602b20, 0x9b1a2c0, 0x0, 0x0, 0x47d6ca0, 0x491ca60)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/pkg/asset/store/store.go:220 +0x638
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0xc000932f90, 0x5602b20, 0x9b1a2c0, 0x5602b20, 0x9b1a2c0)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/pkg/asset/store/store.go:76 +0x4b
main.runTargetCmd.func1(0x5050525, 0x1, 0xc00098fec0, 0xc0008c5c08)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:163 +0x126
main.runTargetCmd.func2(0x9af1ba0, 0x9b51530, 0x0, 0x0)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:188 +0x81
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0x9af1ba0, 0x9b51530, 0x0, 0x0, 0x9af1ba0, 0x9b51530)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00093a780, 0x8, 0x0, 0xc00093b900)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00093a780, 0xc0008c5ec8, 0x1)
	/home/wking/.local/lib/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.installerMain()
	/home/wking/.local/lib/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:56 +0x132
main.main()
	/home/wking/.local/lib/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:40 +0x99

$ tail -10 .openshift_install.log

time="2019-02-28T10:24:13-05:00" level=debug msg="      Fetching \"Certificate (kubelet-signer)\"..."
time="2019-02-28T10:24:13-05:00" level=debug msg="      Reusing previously-fetched \"Certificate (kubelet-signer)\""
time="2019-02-28T10:24:13-05:00" level=debug msg="    Generating \"Certificate (kubelet-serving-ca-bundle)\"..."
time="2019-02-28T10:24:13-05:00" level=debug msg="    Fetching \"Certificate (mcs)\"..."
time="2019-02-28T10:24:13-05:00" level=debug msg="    Reusing previously-fetched \"Certificate (mcs)\""
time="2019-02-28T10:24:13-05:00" level=debug msg="    Fetching \"Root CA\"..."
time="2019-02-28T10:24:13-05:00" level=debug msg="    Reusing previously-fetched \"Root CA\""
time="2019-02-28T10:24:13-05:00" level=debug msg="    Fetching \"Key Pair (service-account.pub)\"..."
time="2019-02-28T10:24:13-05:00" level=debug msg="    Reusing previously-fetched \"Key Pair (service-account.pub)\""
time="2019-02-28T10:24:13-05:00" level=debug msg="  Generating \"Bootstrap Ignition Config\"..."

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Expected to reach the installation prompt in order to update the pull secret (per email instructions)

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create cluster
```

# Anything else we need to know?

Have the latest updates installed for Fedora 29 on amd64

# References

**Comment by staebler** [comment]
You ran the new version of the installer using a directory that had assets created from a previous version of the installer. That is not supported.

**Comment by jsm84** [comment]
ahhh... so to update the pull secret, i will need to run `openshift-install destroy cluster` using 0.12.0 and then redeploy using 0.13.0 in order to update the image pull secret (for the newly included registry.redhat.io credentials)?

**Comment by jsm84** [comment]
Closing as user error.

**Comment by jsm84** [comment]
Closing as user error.
