### ISSUE TITLE
InvalidClientTokenId - The security token included in the request is invalid

### ISSUE THREAD

**Issue by rasheedamir** [openshift/installer#1349]
# Version

```console
$ openshift-install version
./openshift-install v0.13.0
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

```
FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "Master Machines": failed to generate asset "Platform Credentials Check": validate AWS credentials: checking install permissions: error querying current username: InvalidClientTokenId: The security token included in the request is invalid.**********************************************************************************************************************status code: 403, request id: 63423bf5-3c3c-11e9-....
```

# What you expected to happen?

Creation of cluster!

# How to reproduce it (as minimally and precisely as possible)?

```console
./openshift-install create cluster
```

# Credentials

The credentials file looks like this (already obfuscated):

```console
[stakater-devtest]
output = json
region = eu-west-1
aws_access_key_id = OPOPO22QVH77JWZUM4W5Z
aws_secret_access_key = LLLL/+0bzxIQS64xU///+wqfYglmh29XBWVfGLU5
aws_session_token = ZZZZZIvYXdzEAEaDJzY9IJbvTCs8zRKHyKoAok2+zuzvZsxgDbfbspjci/oRaIvwPgePZT/xMu9vj2P93O1QzqF2KMVf3gaIKBJZMlNa7s5VjEqjM/DLcQZvWzWnPeXGYRRlikaHbAj5H2NTeYZCmu9W/+FJxjLS2hR6utb1V6hMz1o2XtT+DMRHYyHsE3rdm9y0rCtFwyGl2vKN3kY/FixDQ/HaFdQHBXm8AW153Apwm/IQe3UKu89HL51ulaOfeUPgaSDaH/zDCiihvqxeZse9JbkqvcX1RaHny26SZo0iRgmvcsPNt1wYkM7A6w8Y+oBQ6M9u3b4Jn+T4keIErRt3EW4qkFmmue6UjPKIXzqSbenC7DswXOGqzLrIuKmYiNqd6n9pQcxbsHS5V88WG2j1gPdzhrUyONYbQuxRof3tZG/KKKK
role = arn:aws:iam::744147648999:role/Administrator-Role,arn:aws:iam::744147648467:saml-provider/AbcAWS
```console

**Comment by wking** [comment]
Looks like the installer is picking up your `aws_session_token` and then getting rejected by the AWS API for `iam.GetUser`.  Does:

```console
$ AWS_PROFILE=stakater-devtest aws iam get-user --user-name $YOUR_USERNAME
```

work for you?  I think the current checker has trouble with assumed roles.

**Comment by rasheedamir** [comment]
@wking 

This is denied; does installer expect any of it to be allowed?

```
        {
            "Action": [
                "iam:AddUserToGroup",
                "iam:AddClientIDToOpenIDConnectProvider",
                "iam:AttachGroupPolicy",
                "iam:AttachUserPolicy",
                "iam:ChangePassword",
                "iam:CreateAccessKey",
                "iam:CreateAccountAlias",
                "iam:CreateGroup",
                "iam:CreateLoginProfile",
                "iam:CreateOpenIDConnectProvider",
                "iam:CreateSAMLProvider",
                "iam:CreateUser",
                "iam:CreateVirtualMFADevice",
                "iam:DeactivateMFADevice",
                "iam:DeleteAccessKey",
                "iam:DeleteAccountAlias",
                "iam:DeleteAccountPasswordPolicy",
                "iam:DeleteGroup",
                "iam:DeleteGroupPolicy",
                "iam:DeleteLoginProfile",
                "iam:DeleteOpenIDConnectProvider",
                "iam:DeleteSAMLProvider",
                "iam:DeleteSSHPublicKey",
                "iam:DeleteServerCertificate",
                "iam:DeleteSigningCertificate",
                "iam:DeleteUser",
                "iam:DeleteUserPolicy",
                "iam:DeleteVirtualMFADevice",
                "iam:DetachGroupPolicy",
                "iam:EnableMFADevice",
                "iam:PutGroupPolicy",
                "iam:PutUserPolicy",
                "iam:RemoveClientIDFromOpenIDConnectProvider",
                "iam:RemoveUserFromGroup",
                "iam:ResyncMFADevice",
                "iam:UpdateGroup",
                "iam:UpdateLoginProfile",
                "iam:UpdateOpenIDConnectProviderThumbprint",
                "iam:UpdateSAMLProvider",
                "iam:UpdateUser"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Deny"
        }
```

**Comment by rasheedamir** [comment]
I think my credentials do have these permissions: https://github.com/openshift/installer/blob/master/pkg/asset/installconfig/aws/permissions.go#L14

I wonder if installer fails before reaching this point?

**Comment by rasheedamir** [comment]
So, it fails right here: https://github.com/openshift/installer/blob/3a5193cdd28d32e13d712c902a0b005574719716/pkg/asset/installconfig/aws/permissions.go#L204

**Comment by sferich888** [comment]
yes, but there are more errors and you have to dig into where those come from to see what install permission issue your hitting: https://github.com/openshift/cloud-credential-operator/blob/master/pkg/aws/utils.go#L114-L135 has the code for some of these checks.

**Comment by Vlatombe** [comment]
Would like be fixed by #1984 / openshift/cloud-credential-operator#91

**Comment by yashbhutwala** [comment]
I'm seeing a similar error, also trying to deploy on AWS.  My account has MFA enabled, but I'm able to get username from the command given by @wking above.  This is the error I'm getting:

`
FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "Master Machines": failed to generate asset "Platform Credentials Check": validate AWS credentials: checking install permissions: error gathering AWS credentials details: error querying username: InvalidClientTokenId: The security token included in the request is invalid.
`

**Comment by abhinavdahiya** [comment]
we explicitly document that we need api access key+secret for an AWS user, and don't support assume role style authentication.
https://github.com/openshift/installer/blob/master/docs/user/aws/iam.md

/close

**Comment by abhinavdahiya** [comment]
for assume role on AWS there is a more concise bug https://github.com/openshift/installer/issues/1535
