### ISSUE TITLE
[AWS] Bootstrap etcd rule not needed after bootstrap

### ISSUE THREAD

**Issue by cuppett** [openshift/installer#1353]
This port is used during the bootstrap:

https://github.com/openshift/installer/blob/a98d4d75cdacfbb7c779c17bc05ec94a76843587/data/data/aws/vpc/sg-master.tf#L169-L177

Should it move to the boostrap terraform template? 

Is it needed on all the master nodes or only internally for the bootstrap node (temporary on master security group versus included in the bootstrap security group)?

**Comment by cuppett** [comment]
These ports may not even be used anymore at all... On the bootstrap on UPI, I see these:

[core@ip-10-0-0-232 ~]$ journalctl -b -u bootkube.service
-- Logs begin at Sun 2019-03-03 14:50:36 UTC, end at Sun 2019-03-03 15:29:47 UTC. --
Mar 03 14:51:21 ip-10-0-0-232 systemd[1]: Started Bootstrap a Kubernetes cluster.
Mar 03 14:51:23 ip-10-0-0-232 bootkube.sh[4757]: Pulling release image...
Mar 03 14:51:35 ip-10-0-0-232 bootkube.sh[4757]: 3cda42285dd19e0e5525524de7b872bbb9e065aff51cea79e75c4cc757c420a1
Mar 03 14:51:47 ip-10-0-0-232 bootkube.sh[4757]: Rendering Cluster Version Operator Manifests...
Mar 03 14:51:47 ip-10-0-0-232 bootkube.sh[4757]: Rendering cluster config manifests...
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_apiserver.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_infrastructure.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_oauth.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_scheduling.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_authentication.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_console.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_dns.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_ingress.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_registry.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_build.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_openshift-config-ns.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_project.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_features.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_image.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_network.crd.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/config-bootstrap/manifests/0000_05_config-operator_01_openshift-config-managed-ns.yaml
Mar 03 14:51:51 ip-10-0-0-232 bootkube.sh[4757]: Rendering Kubernetes API server core manifests...
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/bootstrap-manifests/kube-apiserver-pod.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/00_openshift-kube-apiserver-operator-ns.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-csr-controller-ca.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-initial-sa-token-signing-certs.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-service-network-serving-signer.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/00_openshift-kube-apiserver-ns.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/cluster-role-binding-kube-apiserver.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/cluster-role-kube-apiserver.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-aggregator-client-signer.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-control-plane-client-signer.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-initial-kubelet-client.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-initial-kube-apiserver-serving-ca.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-initial-temporary-kube-apiserver-client-ca.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-node-bootstrap-client-ca.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-initial-serving-cert.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-loadbalancer-serving-signer.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/secret-localhost-serving-signer.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-admin-kubeconfig-client-ca.yaml
Mar 03 14:51:54 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-apiserver-bootstrap/manifests/configmap-initial-kube-apiserver-client-ca.yaml
Mar 03 14:51:55 ip-10-0-0-232 bootkube.sh[4757]: Rendering Kubernetes Controller Manager core manifests...
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-controller-manager-bootstrap/bootstrap-manifests/kube-controller-manager-pod.yaml
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/00_openshift-kube-controller-manager-ns.yaml
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/00_openshift-kube-controller-manager-operator-ns.yaml
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/configmap-initial-kube-controller-manager-csr-ca.yaml
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/secret-csr-signer-signer.yaml
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/secret-initial-kube-controller-manager-service-account-private-key.yaml
Mar 03 14:51:58 ip-10-0-0-232 bootkube.sh[4757]: Rendering Kubernetes Scheduler core manifests...
Mar 03 14:52:06 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-scheduler-bootstrap/bootstrap-manifests/kube-scheduler-pod.yaml
Mar 03 14:52:06 ip-10-0-0-232 bootkube.sh[4757]: Writing asset: /assets/kube-scheduler-bootstrap/manifests/00_openshift-kube-scheduler-ns.yaml
Mar 03 14:52:06 ip-10-0-0-232 bootkube.sh[4757]: Rendering MCO manifests...
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.959394       1 bootstrap.go:79] Version: 4.0.0-alpha.0-5-gf87d8b8d-dirty
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.966058       1 bootstrap.go:121] manifests/machineconfigcontroller/controllerconfig.yaml
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.967860       1 bootstrap.go:121] manifests/master.machineconfigpool.yaml
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.968432       1 bootstrap.go:121] manifests/worker.machineconfigpool.yaml
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.969002       1 bootstrap.go:121] manifests/bootstrap-pod-v2.yaml
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.969603       1 bootstrap.go:121]
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.970042       1 bootstrap.go:121] manifests/machineconfigserver/csr-approver-role-binding.yaml
Mar 03 14:52:09 ip-10-0-0-232 bootkube.sh[4757]: I0303 14:52:09.970661       1 bootstrap.go:121] manifests/machineconfigserver/csr-bootstrap-role-binding.yaml
Mar 03 14:52:10 ip-10-0-0-232 bootkube.sh[4757]: Starting etcd certificate signer...
Mar 03 14:52:12 ip-10-0-0-232 bootkube.sh[4757]: 193f7f1b61b6ff8e419b95818577b7aee468c9db64972813bff9b17d0827ebe2
Mar 03 14:52:12 ip-10-0-0-232 bootkube.sh[4757]: Waiting for etcd cluster...
Mar 03 15:02:17 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-2.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-2.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:02:17 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-0.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-0.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:02:17 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-1.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-1.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:02:17 ip-10-0-0-232 bootkube.sh[4757]: Error: unhealthy cluster
Mar 03 15:02:17 ip-10-0-0-232 bootkube.sh[4757]: etcdctl failed. Retrying in 5 seconds...
Mar 03 15:12:22 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-1.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-1.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:12:22 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-0.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-0.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:12:22 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-2.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-2.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:12:22 ip-10-0-0-232 bootkube.sh[4757]: Error: unhealthy cluster
Mar 03 15:12:22 ip-10-0-0-232 bootkube.sh[4757]: etcdctl failed. Retrying in 5 seconds...
Mar 03 15:22:28 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-1.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-1.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:22:28 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-0.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-0.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:22:28 ip-10-0-0-232 bootkube.sh[4757]: https://etcd-2.cuppett2.openshiftcorp.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-2.cuppett2.openshiftcorp.com on 10.0.0.2:53: no such host
Mar 03 15:22:28 ip-10-0-0-232 bootkube.sh[4757]: Error: unhealthy cluster
Mar 03 15:22:28 ip-10-0-0-232 bootkube.sh[4757]: etcdctl failed. Retrying in 5 seconds...


[core@ip-10-0-0-232 ~]$ netstat -an | more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:54900           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:46751         0.0.0.0:*               LISTEN     
tcp        0     36 10.0.0.232:22           172.2.202.35:37262      ESTABLISHED
tcp6       0      0 :::10250                :::*                    LISTEN     
tcp6       0      0 :::6443                 :::*                    LISTEN     
tcp6       0      0 :::19531                :::*                    LISTEN     
tcp6       0      0 :::46510                :::*                    LISTEN     
tcp6       0      0 :::10255                :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::22623                :::*                    LISTEN     
tcp6       0      0 :::22624                :::*                    LISTEN     
tcp6       0      0 :::9537                 :::*                    LISTEN     
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp        0      0 0.0.0.0:111             0.0.0.0:*                          
udp        0      0 127.0.0.1:323           0.0.0.0:*                          
udp        0      0 0.0.0.0:819             0.0.0.0:*                          
udp        0      0 127.0.0.1:1001          0.0.0.0:*                          
udp        0      0 0.0.0.0:46434           0.0.0.0:*                          
udp6       0      0 :::111                  :::*                               
udp6       0      0 ::1:323                 :::*                               
udp6       0      0 :::819                  :::*                               
udp6       0      0 :::34566                :::*

Unclear yet if those ports are used later.

**Comment by abhinavdahiya** [comment]
I think we ended up removing that etcd rule as it was not being is used.

/close
