### ISSUE TITLE
will support aws cn-north-1 and cn-northwest-1 regions?

### ISSUE THREAD

**Issue by tj13** [openshift/installer#1354]
will openshift 4.0 support install in aws cn-north-1 and cn-northwest-1 regions?

**Comment by wking** [comment]
At the moment, we only support regions where the RHCOS team publishes AMIs.  The encrypted-copy approach begun in #1296 will allow for clusters in any region (once we get machine-API support for encrypted compute nodes, so probably a bit out yet).  In the meantime, you can copy your own AMIs into your target region and use those, although that might make automatic RHCOS upgrades tricky (or maybe the OSTree pivots would be fine, I dunno).

**Comment by tj13** [comment]
how about custom installation on centos 7 which hosted by EC2?

**Comment by wking** [comment]
Cross-linking [rhbz#1734136][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1734136
