### ISSUE TITLE
Instructions for <firstIP> confusing for Libvirt.

### ISSUE THREAD

**Issue by cdrage** [openshift/installer#1357]
# Documentation issue:

Here: https://github.com/openshift/installer/blob/e1082a3ba20036be273300984ac01b891993764b/docs/dev/libvirt-howto.md#set-up-networkmanager-dns-overlay

Provides an example on how to use dnsmasq.

Unfortunately it says: `Tell dnsmasq to use your cluster. The syntax is server=/<baseDomain>/<firstIP>.` without any indication what <firstIP> means. 

Does this mean the first IP of the master OpenShift server? IP of the Libvirt host / server? First IP for the DHCP server?

**Comment by ssbano** [comment]
cdrage,

Virtual machines that will be provisioned by the installer will use this ip for name resolution.

Best Regards,
Fábio Sbano

**Comment by cdrage** [comment]
@ssbano So to clarify, this means that <firstIP> is the DNS server address?

So we should have <firstIP> instead be <dnsMasqIP> or something more explicit.

**Comment by ssbano** [comment]
Yeah, you need to have some knowledge of the libvirt / dnsmasq architecture

```
[core@jaguar-jfcpr-master-0 ~]$ nslookup -type=txt -class=chaos version.bind 192.168.126.1
Server:		192.168.126.1
Address:	192.168.126.1#53

version.bind	text = "dnsmasq-2.79"

[core@jaguar-jfcpr-master-0 ~]$ 
```

Best Regards,
Fabio Sbano

**Comment by zeenix** [comment]
Closing based on https://github.com/openshift/installer/issues/1357#issuecomment-471914565

/close
