### ISSUE TITLE
Openshift Installer is not listing all ssh keys on ssh folder on MacOS Mojave

### ISSUE THREAD

**Issue by gbaufake** [openshift/installer#1362]
# Version

```console
$ openshift-install version
openshift-install v0.13.1
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

. Openshift install is not listing all the keys on .ssh folder.

DEBUG       Generating "SSH Key"...
? SSH Public Key  [Use arrows to move, type to filter, ? for more help]
  /Users/gbaufake/.ssh/id_rsa.pub

```
 ls -l ~/.ssh/         

~ id_rsa
~ example.pem                                                                                                                                              1 
```

# What you expected to happen?

- Example Pem is not listed onte SSH Public Keys even though is on the list of keys.

# How to reproduce it (as minimally and precisely as possible)?

- Download Openshift Install on MacOS Mojave

- Try to install on AWS Platform

- Generate more than one key on ssh folder

- Execute `openshift-install create cluster --dir=cluster-name --log-level=debug`

**Comment by wking** [comment]
> ```
>  ls -l ~/.ssh/         
>
> ~ id_rsa
> ~ example.pem   
> ```
> ...
> Example Pem is not listed onte SSH Public Keys even though is on the list of keys.

That looks like garbled `ls` output, but the installer [looks for `~/.ssh/*.pub`][1] and [doesn't bother asking if you only have a single match][2] (it just auto-selects that `~/.ssh/*.pub`).  We could still offer a choice between "use my only `~/.ssh/*.pub`" and "don't set a SSH key at all", but auto-choosing "use my only `~/.ssh/*.pub`" seems fine to me (folks can always remove it as a day-2 operation).  Some previous discussion [here][3], although that's a bit stale now that we've dropped the environment variables.

[1]: https://github.com/openshift/installer/blob/v0.13.1/pkg/asset/installconfig/ssh.go#L55
[2]: https://github.com/openshift/installer/blob/v0.13.1/pkg/asset/installconfig/ssh.go#L68-L73
[3]: https://github.com/openshift/installer/pull/351#discussion_r221023241

**Comment by gbaufake** [comment]
Changing .pem extension to .pub doesn't seem to solve the case. In Linux, it list everything on the folder (included the same .pem that I have there).

Why this difference of implementation?

**Comment by alanmoran** [comment]
@gbaufake renaming will not work. Try `ssh-keygen -f private.pem -y > public.pub`

Is there a reason we are only listing `*.pub`? AWS by default provides `.pem`. I'm sure we can cover this in the documentation but I was interested as to why we are only allowing `.pub` presently?

**Comment by gbaufake** [comment]
@alanfx Thanks for the update. That worked libra.pub was listed now for me.

**Comment by abhinavdahiya** [comment]
So the goal of the terminal prompts is to help guide users, it's not the only way and it possibly can't keep all users happy.

therefore we have users allow provide install-config.yaml https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations
you can customize using https://github.com/openshift/installer/blob/master/docs/user/customization.md#platform-customization

/close
