### ISSUE TITLE
[libvirt] Can't connect oc rsh <pod> | console->terminal and Pods Overview - Memory, CPU, File System Usage Do Not Appear on Chart

### ISSUE THREAD

**Issue by ssbano** [openshift/installer#1394]
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-504-g18fca42a0a4d7b1489214472d66682a1e2c54894-dirty
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

Can't connect to POD terminal via UI or 'oc rsh'
Pods Overview - Memory, CPU, File System Usage Do Not Appear on Chart

# What you expected to happen?

[fsbano@voyager-1 ~]$ oc get pod
NAME             READY     STATUS      RESTARTS   AGE
nginx-1-build    0/1       Completed   0          10m
nginx-1-deploy   0/1       Completed   0          6m26s
nginx-1-sgb9l    1/1       Running     0          6m10s
[fsbano@voyager-1 ~]$ oc rsh nginx-1-sgb9l
sh-4.2$

# How to reproduce it (as minimally and precisely as possible)?
oc get pod
oc rsh <pod>

# Anything else we need to know?

to solve the problem I executed the command below
```
oc adm certificate approve $(oc get csr | egrep ^csr | awk '{ print $1 }')
```
# References

N/A

**Comment by ssbano** [comment]
Attached Image

![Uploading ui-terminal.png…]()
![ui-pod-overview](https://user-images.githubusercontent.com/48354484/54069107-e3410d00-4232-11e9-92ed-cb482ae31794.png)

**Comment by praveenkumar** [comment]
Here is the issue at respective repo : https://github.com/openshift/cluster-machine-approver/issues/15 , @ssbano can we close it from here?

**Comment by ssbano** [comment]
@praveenkumar,

Yeah, thanks for the attention.

Regards,
Fabio Sbano
