### ISSUE TITLE
[libvirt] router-default 0/1 - forever "pending status"

### ISSUE THREAD

**Issue by ssbano** [openshift/installer#1395]
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-540-g12af0c9b8e6a090c041b19c2fb0c040188607bcb-dirty
```

# Platform (aws|libvirt|openstack):
libvirt

# What happened?
[fsbano@voyager-1 ~]$ oc get pod
NAME                              READY     STATUS    RESTARTS   AGE
router-default-779745f684-nxqrs   0/1       Pending   0          17m
router-default-779745f684-zmf8k   1/1       Running   0          37m
[fsbano@voyager-1 ~]$ 

[fsbano@voyager-1 ~]$ oc describe pod/router-default-779745f684-nxqrs | tail -4
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  8m (x17 over 17m)  default-scheduler  0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  2m (x11 over 17m)  default-scheduler  0/2 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match node selector.
[fsbano@voyager-1 ~]$ 

"didn't have free ports for the requested pod ports, 1 node(s) didn't match node selector."

# What you expected to happen?

Provision two worker per default

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./openshift-install create cluster (Without customization in config)
```

# Anything else we need to know?

N/A

# References
N/A

**Comment by praveenkumar** [comment]
> default-scheduler 0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate.

@ssbano This is expected because by default `master` is tainted and it can't have any workload on it. Also there is no issue if you have one router pod is running since it can serve the requests. If you create 2 worker then whatever started on the master will still be on the pending and you can delete that pod manually without any issue iirc.

**Comment by ssbano** [comment]
@praveenkumar,

My setup

1x master - 16gb 
2x worker - 8gb

less than these values is very unstable environment

Best Regards,
Fábio Sbano

**Comment by ssbano** [comment]
is not a problem is expected to happen
