### ISSUE TITLE
[OPENSTACK] platform.openstack.cloud parameter doesn't have an effect

### ISSUE THREAD

**Issue by lukas-bednar** [openshift/installer#1404]
# Version 

```console
$ openshift-install version
./bin/openshift-install unreleased-master-542-g0e12f4527c25e9d1e2ddb31bea0ace0cb6d463ca-dirty
```

# Platform openstack:
Having install-config.yaml containing following snippet
```yaml
platform:
  openstack:
    cloud: psi-prod
```
When running installer, it fails on following error:
```
ERROR Error: Error refreshing state: 1 error occurred: 
ERROR 	* provider.openstack: cloud openstack does not exist in clouds.yaml 
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR Failed to read tfstate: open /tmp/openshift-install-721794227/terraform.tfstate: no such file or directory 
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform 
```
it is looking for cloud named `openstack` instead of `psi-prod` which I have selected in wizard.

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Installer should respect values in configuration file.

# How to reproduce it (as minimally and precisely as possible)?

run installer with custom cloud name.

# Anything else we need to know?

I believe it is because of hard-coded `CloudName` as a constant in https://github.com/openshift/installer/blob/5455c4ac317900208a92983e35e6b87fc74fd354/pkg/asset/machines/openstack/machines.go#L27

**Comment by ssbano** [comment]
@lukas-bednar,

I want to try running the ocp4-preview on openstack over the weekend.

How is your experience?

Regards,
Fábio Sbano

**Comment by lukas-bednar** [comment]
@ssbano I am at state where installer is able to create following resources for me:
* tenant network + router + subnet + trunks ...
* swift containers
* 3 masters, API and bootstrap nodes

I am providing floating IP for LB, and currently installer timeouts on 
```
INFO Waiting up to 30m0s for the Kubernetes API... 
DEBUG Still waiting for the Kubernetes API: Get https://api.lbednar-ocp-4.0.example.com:6443/version?timeout=32s: dial tcp 10.0.145.151:6443: i/o timeout 
```
When I inspects console of nodes:
* bootstrap node fails to boot on "No DHCP offers" and 
* api node is looping in attempts to authenticate against my openstack instance
* master nodes are looping in "connection refused" when trying to reach API node.

This is as far I could get ATM.

**Comment by ssbano** [comment]
@lukas-bednar,

What version of openstack are you running? (Rocky)

I had difficulty putting the ocp4-preview in libvirt but now it's running perfectly

Regards,
Fábio Sbano

**Comment by lukas-bednar** [comment]
> What version of openstack are you running? (Rocky)

@ssbano I am using RHOS 13.

**Comment by ssbano** [comment]
@lukas-bednar,

I got 60 days on the developer account.
I'll put the same version

Regards,
Fábio Sbano

**Comment by ssbano** [comment]
@lukas-bednar

did you try to boot the core image and see if it has a routing problem?

**Comment by ssbano** [comment]
@lukas-bednar

Create an installation and attach the image on openstack with floatip

https://coreos.com/os/docs/2079.0.0/installing-to-disk.html

Regards,
Fábio Sbano

**Comment by lukas-bednar** [comment]
@ssbano I am not sure if I follow . I have rhcos image in my openstack and yes I am able to lunch an instance from that and instance boots up.

**Comment by ssbano** [comment]
@lukas-bednar,

I understood, very good.

**Comment by ssbano** [comment]
@lukas-bednar,

Not able to run in any version 0.14, 0.13 ...?

Regards,
Fabio Sbano

**Comment by lukas-bednar** [comment]
@ssbano  I was trying at master first and now I am running on 0.14.

**Comment by ssbano** [comment]
@lukas-bednar,

Allright, let's try together.

**Comment by tomassedovic** [comment]
Should be fixed when https://github.com/openshift/installer/pull/2122 merges.

**Comment by tomassedovic** [comment]
#2122 is merged, closing this. Please re-open this issue if it still persists with the latest code.

/close
