### ISSUE TITLE
Libvirt: Port conflict error raising up the scheduler container

### ISSUE THREAD

**Issue by jparrill** [openshift/installer#1409]
# Version

```console
$ openshift-install version
./bin/openshift-install v0.14.0
```

# Platform (aws|libvirt|openstack):

Libvirt

# What happened?

Raising up OCP4 on RHEL 7.6 I've receive a port conflict error here the installer log: [https://pastebin.com/jS3XL3jY](https://pastebin.com/jS3XL3jY)

# What you expected to happen?

Installation Finishes correctly

# How to reproduce it (as minimally and precisely as possible)?

- Follow the libvirt documentation deployer using RHEL 7.6 as OS on v0.14.0 installer version.
- Use this repo for qemu-kvm and qemu-kvm-ev for full compatibility:
```
[kvm-common]
name=CentOS-7-Common
baseurl=http://mirror.centos.org/centos/7/virt/x86_64/kvm-common/
enabled=1
gpgcheck=0
```
All parameters by default, but the baseDomain that was changed.

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by praveenkumar** [comment]
@jparrill I also saw this issue from time to time but not able to reproduce using the consecutive run of the installer, Can you destroy the cluster again and then try if you can face it again?

**Comment by jparrill** [comment]
I've followed the steps that are on libvirt_cleaner script has and it seems like undefining elements that are not there works. Makes not sense but works...
