### ISSUE TITLE
Fix code comment

### ISSUE THREAD

**Issue by ingvagabund** [openshift/installer#1436]
From [1]:

```go
// Generate generates the Worker asset.
func (c *ClusterK8sIO) Generate(dependencies asset.Parents) error {
```

The comment should be `// Generate generates the Cluster asset.` given `Generate` constructs `clusterv1a1.Cluster` object.

[1] https://github.com/openshift/installer/blob/e5b5047f93f64c75fca7e35caae732f4a49b305c/pkg/asset/manifests/cluster_k8s_io.go#L37

**Comment by wking** [comment]
Fixed (by removing the asset type ;) in #1449.
