### ISSUE TITLE
`tls: internal error` when getting logs on OpenStack

### ISSUE THREAD

**Issue by tomassedovic** [openshift/installer#1467]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-591-g0d891e1119806555871330723497f4ac770ad13a
built from commit 0d891e1119806555871330723497f4ac770ad13a
```

# Platform (aws|libvirt|openstack):

openstack

# What happened?

Running `oc logs` always seems to fail with a tls internal error. For example:

```console
$ oc logs console-779f468448-t784l -n openshift-console
Error from server: Get https://ostest-w5vdz-master-2.ostest.shiftstack.com:10250/containerLogs/openshift-console/console-779f468448-t784l/console: remote error: tls: internal error
```

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

Install OpenShift on OpenStack (you have to create the install-config.yaml manually) and once the cluster is mostly up (e.g. the worker nodes are created), pick a pod and run `oc logs pod`.

This should produce the logs, but instead outputs the tls error above.

**Comment by tomassedovic** [comment]
/cc @trown @flaper87 

We need to figure that out asap because it's blocking us from figuring out any of the other issues.

**Comment by zeenix** [comment]
This is fixed by https://github.com/openshift/cluster-api-provider-libvirt/pull/128

**Comment by tomassedovic** [comment]
Ah, thanks for the pointer @zeenix! I'll see if we need to do something similar for OpenStack.

**Comment by zeenix** [comment]
> This is fixed by [openshift/cluster-api-provider-libvirt#128](https://github.com/openshift/cluster-api-provider-libvirt/pull/128)

Oops. This is openstack backend. The PR above is libvirt specific. Having said that, I'd bet it's a very similar issue.

**Comment by FlorinPeter** [comment]
@tomassedovic I had the same issue because the csr was not approved. This happened because the nodelink-controller can not link the machine because of the missing status field.
I created an PR here https://github.com/openshift/cluster-api-provider-openstack/pull/29 but still no response ;(

**Comment by tomassedovic** [comment]
Thanks @FlorinPeter, I'll have a look.

**Comment by gbraad** [comment]
Can you check the following on your node? #1494 See if the certs in `/var/lib/kubelet/pki` are still valid.

**Comment by abhinavdahiya** [comment]
This seems like an machine API and machine approver issue. Please open issues on corresponding PRs to track this.

/close

But if you still think this installer configuring resources incorrectly please feel free to reopen with your reasoning.
