### ISSUE TITLE
dep check fails in pkg/terraform/exec

### ISSUE THREAD

**Issue by serbrech** [openshift/installer#1471]
# Version 
dev environment

# Platform (all):
I want to add the azure terraform provider, and I'm looking at how I should manage the dependencies under `pkg/terraform/exec`.
from latest master, running `dep check` under the `exec` folder fails with : 
```
~/go/src/github.com/openshift/installer/pkg/terraform/exec master
% dep check            
# Gopkg.lock is out of sync:
github.com/hashicorp/terraform/version: in Gopkg.lock's input-imports, but neither imported nor required
```

dep version : 
```
% dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```
I'll just send a PR to fix the above if in case it's not expected.

I am unsure how you manage the dependencies under this folder as there seems to be a hierarchy between exec and the plugins?
Do you have docs around how to manage the dependencies for terraform?

Thanks

**Comment by wking** [comment]
> I am unsure how you manage the dependencies under this folder as there seems to be a hierarchy between exec and the plugins?

I'm also not all that clear on the Terraform/plugin split.  @abhinavdahiya?

> Do you have docs around how to manage the dependencies for terraform?

[Here][1], but it doesn't go into detail about the Terraform nesting.

[1]: https://github.com/openshift/installer/blob/b3b8a8928b1953c00944fae307c933dbcad6cf75/docs/dev/dependencies.md#go

**Comment by serbrech** [comment]
More concretely, how would I go about adding `github.com/terraform-providers/terraform-provider-azurerm` to support my other PRs?
so far, I am using `MODE=dev` to hit this : https://github.com/openshift/installer/blob/b3b8a8928b1953c00944fae307c933dbcad6cf75/pkg/terraform/exec/plugin.go#L1 when building.

I then point the installer at the `data/data` folder for the assets when creating the cluster.

```
MODE=dev hack/build.sh
OPENSHIFT_INSTALL_DATA=data/data bin/openshift-install create cluster
```

And I'm not sure if that was a clever hack, or the intended way to do it, but it works for my dev environment. 😆

**Comment by abhinavdahiya** [comment]
> More concretely, how would I go about adding `github.com/terraform-providers/terraform-provider-azurerm` to support my other PRs?
maybe this will help
https://github.com/abhinavdahiya/installer/commit/7b71c902cdcebfda0e06fc57f379732a6505069e

**Comment by wking** [comment]
> And I'm not sure if that was a clever hack, or the intended way to do it...

`MODE=dev` is intended for iterating on Terraform modules without having to recompile the installer, so yeah, that was the plan ;).  In practice, compilation is cheap, so I rarely bother :p.

**Comment by serbrech** [comment]
@abhinavdahiya I figured out the `plugins.go` but the constraint part wasn't clear. thanks

**Comment by DanyC97** [comment]
do you think https://github.com/openshift/installer/issues/1471#issuecomment-476888668 should be added in the hack dir / dev readme ?
