### ISSUE TITLE
Ignition config for bootstrap machine ignored

### ISSUE THREAD

**Issue by kshlm** [openshift/installer#1484]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-595-gbcdeb2f209f9f58ac070e27185c376ae087b21fe
built from commit bcdeb2f209f9f58ac070e27185c376ae087b21fe
```

_Note: This is a custom build to increase timeouts to allow container images to download when in slow networks_

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

I want to setup a Squid caching proxy to cache the container images downloaded by the machines as I downloads take a long time for me. To do this I want to add the self-signed CA cert of the squid server to the bootstrap, master and worker machines, using custom ignition configs. The ignition configs I used are below.

[ignition-configs.tar.gz](https://github.com/openshift/installer/files/3017958/ignition-configs.tar.gz)

The ignition configs were generated using `openshift-install create ignition-configs` and then edited to add the CA certs.

But the ignition config for the bootstrap machine is discarded, and the bootstrap ignition config is regenerated with the default values. The following line appears in the log,

```
time="2019-03-28T18:19:12+05:30" level=warning msg="  Discarding the \"Bootstrap Ignition Config\" that was provided in the target directory because its dependencies are dirty and it needs to be regenerated"
```

The full log is available below.
[openshift_install.log](https://github.com/openshift/installer/files/3017976/openshift_install.log)

The libvirt VM network has been configured to forward all http/https connections to the proxy. As the bootstrap VM comes up without the proxy CA, it cannot establish any connections through the proxy and fails to download anything.

# What you expected to happen?

I expect the bootstrap machine to use the custom provided ignition config, add the custom CA cert, and successfully download the images via the proxy.

# How to reproduce it (as minimally and precisely as possible)?

Using the provided ignition-configs this can be reproduced.

```console
$ tar -xf ignition-configs.tar.gz
$ openshift-install create cluster
```

Once the command is in progress, check the log for the above mentioned log line. The ignition config is also attached to the VM as a volume. This volume can be checked to see if it is the custom one or the regenerated default one.
```console
$ cat $(virsh vol-list --pool=default | awk '/bootstrap.ign/{print $2}')
```

# Anything else we need to know?

None.

**Comment by abhinavdahiya** [comment]
The bootstrap ignition includes the master and worker ign file as they need to be pushed to cluster. So changing all together means bootstrap ignition needs to be regenerated. Do it is working as expected.

Feel free to open an RFE if you think that is a feature you would like to see.

/close

If you want to modify control plane and compute machine configuration you should try to use multi stage install to provide custom machine config objects https://github.com/openshift/installer/blob/master/docs/user/customization.md#install-time-customization-for-machine-configuration
