### ISSUE TITLE
libvirt OOM panic, document system requirements?

### ISSUE THREAD

**Issue by wongma7** [openshift/installer#1485]
# Version

```console
$ openshift-install version
bin/openshift-install v0.15.0
built from commit 462d548ed561aab9b5866c9a612fc85d1a47419f
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

Installer panics with out of memory error at RHCOS image pulling step

# What you expected to happen?

Installer doesn't panic

# How to reproduce it (as minimally and precisely as possible)?

1. have a system with 8GB RAM or less
```console
$ openshift-install create cluster
```

# Anything else we need to know?

Even if the installer succeeds, how much memory would the 3VMs need? About how much free disk space would be needed?

**Comment by zeenix** [comment]
I'm hoping #1676 (or rather the new PR @skitt will be creating) will make this redundant (or at least not so important).

**Comment by skitt** [comment]
See #1697 (I didn’t mark that as fixing this since it doesn’t address the documentation part).

**Comment by zeenix** [comment]
IMO it's a bit early to set specific requirements. Hopefully when things are more stable (4.2 or 4.3 maybe), we could specify the exact requirements. I'd very much prefer a separate issue for that (I think there already is?) so closing this one.

/close
