### ISSUE TITLE
manifests dir contains a mix of ".yaml" and ".yml" files

### ISSUE THREAD

**Issue by danwinship** [openshift/installer#1501]
# Version
git master

# Platform
aws

# What happened?
While reviewing network configuration docs, I noticed that the network config manifest is called `cluster-network-02-config.yml`, while most (but not all) of the other manifest files have the suffix `.yaml`, as does `install-config.yaml`. It seems icky and inconsistent and possibly likely to lead to mistakes. And also maybe too late to change? :man_shrugging:

**Comment by abhinavdahiya** [comment]
It's not great, but it's not too bad.

all our files in manifests target don't have any compatibility guarantees, but we would like to not break users if we don't have to.

/close
