### ISSUE TITLE
Should be able to setup cluster on baremetal with bootstrap vm

### ISSUE THREAD

**Issue by bmeng** [openshift/installer#1517]
# Platform (aws|libvirt|openstack):
baremetal

# What happened?
https://github.com/openshift/installer/blob/master/docs/user/metal/install_upi.md#compute

As the document says above, we need to use a bootstrap host to setup control plane hosts for baremetal cluster. And the bootstrap host can be removed after that.

# What you expected to happen?
We should also support that using the virtual machine as the bootstrap node, so that we won't waste the hardware resources.

**Comment by abhinavdahiya** [comment]
If your VM can be configured with the bootstrap ignition and it is in the API load balancer pool etc.. that might work...

We haven't tried it. It would be great if you could try it and tell us if that worked ;)
