### ISSUE TITLE
BaseDomain AWS : aws.IsForbidden(cause) returns true when cause is nil so the code is not doing what it looks like

### ISSUE THREAD

**Issue by serbrech** [openshift/installer#1524]
https://github.com/openshift/installer/blob/3d904d3364e68251cc067782344b72b626e65573/pkg/asset/installconfig/basedomain.go#L36-L38

`return err` in fact returns `nil`, it's very confusing when reading the code to understand why it doesn't get to the last return statement and ask a second time for the BaseDomain when everything goes fine.

**Comment by serbrech** [comment]
@wking @abhinavdahiya

**Comment by abhinavdahiya** [comment]
I'm a little confused here. Would you mind expanding on the failure you are seeing?

The if statement is setup so that throttling and forbidden errors do not prevent users from creating install config. On these ^^ errors installer falls back to text based input.
