### ISSUE TITLE
what's the best way to automate openshift-install interactions right now?

### ISSUE THREAD

**Issue by ktdreyer** [openshift/installer#1533]
I am using `openshift-install` in a CI environment (Jenkins), and I wonder about how to best handle this.

There are two ways to set up a cluster with `openshift-install`:

1. Specify an pre-written YAML file ("install-config")
2. Run it interactively

The [documentation](https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations) currently says "Supplying a previously-generated install-config like this is explicitly part of the stable API." so I think that means that my team and I can generate one configuration file today and keep using the same exact one for months without ever thinking about updating it.

There are a few other facts that make me wonder about this.

1. OpenShift 4 is not GA.
2. There are many commits to `openshift/installer` every day, and there are weekly (or more) releases, so the rate of change is extremely high right now.
3. If openshift-install is following [SemVer](https://semver.org/), the "0" in "0.16.1" would indicate that this is not stable and we should not rely on it being stable.

Would you please tell us whether we should expect to use a single static install-config YAML file right now for the next several months, or what other approach we should take?

**Comment by wking** [comment]
For CI, interactive wizard use is not really possible, right?  You need to use the `install-config.yaml` route.

For stability, yes, we reserve the right to make breaking changes up until GA, although:

* We'll probably stop cutting independently-versioned installer releases, see #1422 and openshift/origin#22439.  So if the installer ends up having/keeping SemVer APIs, the way you find the version is probably going to change.
* We will make a best-effort attempt to maintain backwards compat with ideally-stable APIs, despite not hitting an installer 1.x or OpenShift GA.  For example, we currently support both v1beta3 and v1beta4 install-configs, and while the former [is deprecated][1], we probably won't drop it before GA.

So if you need months+ stability, probably wait for GA.  If you are willing to work with our best-effort stability, feel free to start now.

[1]: https://github.com/openshift/installer/blob/v0.15.0/CHANGELOG.md#changed

**Comment by ktdreyer** [comment]
Thank you for the detailed response. That helps my team know what to expect now.

After you stop cutting independently-versioned releases of openshift-install, how will we download openshift-install binaries? Today we do it in Jenkins by querying https://github.com/openshift/installer/releases .

**Comment by wking** [comment]
> After you stop cutting independently-versioned releases of openshift-install, how will we download openshift-install binaries?

Release tooling will extract them from release images with the pin-injection from openshift/origin#22439 and drop them somewhere under [here][1] (e.g. see the "Download Command-line Tools" button [here][2]).  The details of the directory structure are still being worked out.

[1]: https://mirror.openshift.com/pub/
[2]: https://cloud.openshift.com/clusters/install

**Comment by ktdreyer** [comment]
Ok, thanks. I think that answers my questions and we can close this.

**Comment by DanyC97** [comment]
stellar information provided @wking !! 💯
