### ISSUE TITLE
Installer breaks when using assume role in profile.

### ISSUE THREAD

**Issue by stobias123** [openshift/installer#1535]
# Version

```console
$ openshift-install version
openshift-install v0.16.1
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform (aws):

# What happened?

Credentials file specified an assume role.
ex.
```console
  29   │ #account id : 1234567890
  30   │ [contoso-hub]
  31   │ aws_region = us-west-1
  32   │ role_arn = arn:aws:iam::1234567890:role/OrganizationAccountAccessRole
  33   │ source_profile = contoso-root
```

I ended up seeing the below from the credential operator. Worker machines were never created. 

```
4 of 4 credentials requests are failing to sync.
```

# What you expected to happen?

Cluster is created.

# How to reproduce it (as minimally and precisely as possible)?

See above. Set assume-role in profile you're using. 

# Anything else we need to know?

Once I went with straight up AWS credentials, everything was :thumbsup:

**Comment by wking** [comment]
Similar to #1010, CC @joelddiaz about somehow guarding against this if we can't make it work.

**Comment by joelddiaz** [comment]
@wking i went ahead and created a jira bug so we can work on this
