### ISSUE TITLE
Customize worker vcpu/memory parameters

### ISSUE THREAD

**Issue by pavolbrilla** [openshift/installer#1540]
# Version

```console
$ openshift-install version
bin/openshift-install v0.16.1
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

Worker are static, not customizable at all by installer and is created default libvirt VM

# What you expected to happen?

to be able to customize worker size, so I can really deploy somthing over it

# How to reproduce it (as minimally and precisely as possible)?

just build installer, and run it, cluster will be created with worker with defualt libvirt values

# Anything else we need to know?

On cluster-api-provider-libvirt was created issue to make vcpu/memory customizable, this issue is about exposing those variables through installer to end user before installation.

# References

https://github.com/openshift/cluster-api-provider-libvirt/issues/143

**Comment by zeenix** [comment]
Will hopefully look into this soon.

**Comment by fromanirh** [comment]
Hey, I've been hacking around the installer code because I have the same need, and I've published https://github.com/openshift/installer/pull/2258. Maybe that can help?

**Comment by abhinavdahiya** [comment]
should be customizable by https://github.com/openshift/installer/pull/2399

/close
