### ISSUE TITLE
Existing A record error

### ISSUE THREAD

**Issue by bertinatto** [openshift/installer#1562]
# Version

```console
$ bin/openshift-install version
bin/openshift-install unreleased-master-729-g83ca64d34e7e16935cbaa39fb42a6c8ba9d58c33
built from commit 83ca64d34e7e16935cbaa39fb42a6c8ba9d58c33
release image registry.svc.ci.openshift.org/openshift/origin-release:v4.0
```

# What happened?

I've seen this error occasionally:

```
ERROR                                              
ERROR Error: Error applying plan:                  
ERROR                                              
ERROR 1 error occurred:                            
ERROR 	* module.dns.aws_route53_record.api_external: 1 error occurred: 
ERROR 	* aws_route53_record.api_external: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.myname.mydevcluster.com.', type='A'] but it already exists] 
ERROR 	status code: 400, request id: 2315fe75-5ac2-11e9-9982-7b4f4ee60637 
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR Terraform does not automatically rollback in the face of errors. 
ERROR Instead, your Terraform state file has been partially updated with 
ERROR any resources that successfully completed. Please address the error 
ERROR above and apply again to incrementally change your infrastructure. 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform 
```

Then I head to the AWS Console and delete the records manually.

I'm not sure how often this happen out there, but it might be worthwhile to parse this AWS error and print a more helpful message to the user.

Ideally, the message would instruct the user to delete the records manually and then proceed with the installation.

**Comment by wking** [comment]
> Ideally, the message would instruct the user to delete the records manually and then proceed with the installation.

That's not always the appropriate response.  See [rhbz#1659970][1] (fixed by #1442) for why we error out in this case.  Your issue is almost certainly a failed/forgotten uninstall of an earlier cluster; have you been running `destroy cluster` when you're done with old clusters?  But I'm ok with elaborating on this and other Terraform errors (see my stub in #1452) if we wanted to pursue that direction.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1659970

**Comment by bertinatto** [comment]
>  Your issue is almost certainly a failed/forgotten uninstall of an earlier cluster

Yep, that's my case. No doubt that it was my fault, but since we want to make the installer very accessible to our users, it might be worthwhile to point them some directions on how to solve common errors (if that's possible). https://github.com/openshift/installer/pull/1452 looks very useful, perhaps we could have a pointer to it in the error message?

**Comment by chmouel** [comment]
I have the issue happening to me every time (openshift-dev us-east-2 account), running a "destroy cluster"

**Comment by wking** [comment]
> I have the issue happening to me every time...

Have you removed the leaked A record?  You need to recover this manually after the buggy openshift-dev reaper partially removes the cluster.  Running `destroy cluster` *before* the reaper gets to your cluster will keep this from happening, but it won't help after the reaper removes your private zone.

**Comment by abhinavdahiya** [comment]
openshift-dev account should be cleaning them correctly, if the installer doesn't find the private zone, the public records cannot be delete for safety.

/close

**Comment by lukas-vlcek** [comment]
I am running into similar issue but I am unable to find my domain in **Hosted zones** list so I can not delete it in AWS console. Am I looking into wrong dashboard?
