### ISSUE TITLE
Lost metadata.json and kubeconfig

### ISSUE THREAD

**Issue by DJAyth** [openshift/installer#1583]
I have been testing out Openshift 4 via the preview, and have a cluster installed in AWS. I installed it from an AWS instance, and was using that to manage it. I have the kubeadmin login, and can login to the console.

My issue arises due to the fact that the AWS instance I used to install and manage it, was terminated. As such I've lost the kubeconfig, and the metadata details to destroy the cluster.

There seems to be some ways of getting around the ability to delete the cluster, but the details require a subscription. https://access.redhat.com/solutions/3826921

Anyone able to give me some advice? Particularly for re-generating the kubeconfig somehow.

**Comment by DJAyth** [comment]
Nevermind managed to generate a metadata.json file by running ./openshift-install create install-configs then running ./openshift-install create ignition-configs. From there modified the file with the cluster id, and infra id from the console and it worked for me.

**Comment by wking** [comment]
Closing as a dup of #746.  But yeah, "figure out the missing IDs somehow and plug them in to a `metadata.json` template is how I do this ;).

/close
