### ISSUE TITLE
Cluster name needs validation

### ISSUE THREAD

**Issue by dantrainor** [openshift/installer#1584]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-731-g27b24b8250293db120464095960f3b42cfaa94f5
built from commit 27b24b8250293db120464095960f3b42cfaa94f5
release image registry.svc.ci.openshift.org/openshift/origin-release:v4.0

```

# Platform (aws|libvirt|openstack):

libvirt, with upstream Virt SIG repos

# What happened?

When using a cluster name that is of a number, it appears that enumeration breaks.  For example, looking at an install-config.yaml:

...
metadata:
  creationTimestamp: null
  name: 01
...

The resulting error is:

ERROR                                              
ERROR Error: Error applying plan:                  
ERROR                                              
ERROR 2 errors occurred:                           
ERROR 	* module.bootstrap.libvirt_domain.bootstrap: 1 error occurred: 
ERROR 	* libvirt_domain.bootstrap: virError(Code=27, Domain=19, Message='XML error: Cannot use host name '1-x24zk-bootstrap' in network '1-x24zk'') 
ERROR                                              
ERROR                                              
ERROR 	* libvirt_domain.master: 1 error occurred:  
ERROR 	* libvirt_domain.master: virError(Code=27, Domain=19, Message='XML error: Cannot use host name '1-x24zk-master-0' in network '1-x24zk'') 

I'm not sure if this is a limitation of libvirt's network implementation with regards to named network creation, but nonetheless it affects the deployment.  

# What you expected to happen?

The deployment should properly succeed with a name of e.g. '01' after this name is enumerated over properly.

# How to reproduce it (as minimally and precisely as possible)?

Create an install-config.yaml as you normally would, and give it a 'name' of a zero-index or integer number.

```console
$ bin/openshift-install --dir=staging create --log-level debug cluster
```

# Anything else we need to know?

The cluster name either needs some additional validation so that elements are created properly, or enforce using a non-numerical cluster name.  The former suggestion would probably be preferable.

# References

**Comment by praveenkumar** [comment]
We need to find out if this is case for other providers also.

**Comment by asalkeld** [comment]
also see: https://github.com/openshift/installer/issues/1012

**Comment by abhinavdahiya** [comment]
@zeenix is this something we are looking to fix soon?
