### ISSUE TITLE
AWS UPI instructions for DNS

### ISSUE THREAD

**Issue by maci0** [openshift/installer#1611]
https://github.com/maci0/openshift4-ansible

basically the dnses object has to be replaced check the template I used in the files/ directory
also in the machinesets I'm referencing actual IDs for policy and subnets etc instead of looking it up by name. Maybe theres something you can use from that repo

**Comment by abhinavdahiya** [comment]
we already have docs for AWS upi [here](https://github.com/openshift/installer/blob/master/docs/user/aws/install_upi.md)

This includes the cloud formation templates that show example of how the DNS can be setup. If the docs ad examples are not correct _bare in mind they are no supposed to cover all setups_ , feel free to create an issue that provides more details.

Thanks!

/close

**Comment by maci0** [comment]
this was about the "dnses" k8s object thats broken on fresh installs and also not covered by the UPI docs.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/pull/1590 is fixing the example to create correct DNS private zone so things work out of the box.
