### ISSUE TITLE
Is there anyway to use my own SSL certificate for web console and dashboards?

### ISSUE THREAD

**Issue by sloppycoder** [openshift/installer#1617]
I ran the installer and a complete cluster came up on AWS in about 20 min, kudos for a fantastic job!

The only problem I have now is that the SSL certificate generated by the installer is not valid and it's annoying to see "not secure" in my browser. Is there any way I can replace the SSL certificate with proper ones, like something I get from letsencrypt?

I'll be great if I can provide my own certficate before the installer starts.

Thanks.

**Comment by abhinavdahiya** [comment]
> I ran the installer and a complete cluster came up on AWS in about 20 min, kudos for a fantastic job!
> 
> The only problem I have now is that the SSL certificate generated by the installer is not valid and it's annoying to see "not secure" in my browser. Is there any way I can replace the SSL certificate with proper ones, like something I get from letsencrypt?

I would open issue on https://github.com/openshift/console-operator as that is the operator that controls the console.

> I'll be great if I can provide my own certficate before the installer starts.

That's a day 2 operation that you need to perform. OpenShift 4 is all about day-2 ;)

> Thanks.

**Comment by wking** [comment]
+1 to day-2, and we have a reference to the appropriate operator.  I don't see anything the installer can do here, so...

/close
