### ISSUE TITLE
Use AWS CA for certs?

### ISSUE THREAD

**Issue by mlbiam** [openshift/installer#1635]
# Version

```console
$ openshift-install version
./openshift-install v0.16.1
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

Generates self signed certs, with HSTS most browsers reject and won't let you trust.  
# What you expected to happen?

Use the AWS CA to generate commercially signed certs

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
The installer creates a cluster with self signed certs. You can configure certainly for components like the API,  ingress controller default cert or even individual route. Day 2 by configuring operators.

Please open bugs on respective operators to find how to achieve that. Like
https://github.com/openshift/cluster-kube-apiserver-operator/issues
https://github.com/openshift/cluster-ingress-operator

/close
