### ISSUE TITLE
hack/tf-fmt.sh doesn't work with selinux in enforcing

### ISSUE THREAD

**Issue by sjenning** [openshift/installer#164]
`hack/tf-fmt.sh` doesn't work with selinux in enforcing

Also, perhaps we should detect if the `terraform` command is on the path and only use the container if `terraform` is not present.

**Comment by wking** [comment]
> `hack/tf-fmt.sh` doesn't work with selinux in enforcing

Fixed by #174.

> Also, perhaps we should detect if the `terraform` command is on the path and only use the container if `terraform` is not present.

The script is basically a wrapper to invoke the container.  If you have a local `terraform` with a close-enough version, I'd just use `terraform fmt ...` instead of invoking `tf-fmt.sh` at all.
