### ISSUE TITLE
FATAL waiting for Kubernetes API: context deadline exceeded

### ISSUE THREAD

**Issue by rsriniva** [openshift/installer#1667]
It looks like the 30m wait time is not enough for the DNS to propagate. I am located in Bangalore and the cluster is being provisioned in ap-south-1 (Mumbai). Is there a way to increase the timeout to 1 hour? I have run the installer many many times now and the failure rate is > 90% for non-US regions....

Why ping the public DNS ip during cluster provision? Would it not be faster to use the internal DNS of the API server and then worry about slow DNS propagation when doing oc login?

# Version

```console
$ openshift-install version
openshift-install v0.16.1
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform (aws|libvirt|openstack):

aws. Installing from a Fedora 29 VM.

# What happened?
bash-4.4$ openshift-install create cluster
INFO Consuming "Install Config" from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 30m0s for the Kubernetes API at https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443... 
FATAL waiting for Kubernetes API: context deadline exceeded

install log:
time="2019-04-24T06:34:44Z" level=debug msg="Apply complete! Resources: 98 added, 0 changed, 0 destroyed."
time="2019-04-24T06:34:44Z" level=debug
time="2019-04-24T06:34:44Z" level=debug msg="The state of your infrastructure has been saved to the path"
time="2019-04-24T06:34:44Z" level=debug msg="below. This state is required to modify and destroy your"
time="2019-04-24T06:34:44Z" level=debug msg="infrastructure, so keep it safe. To inspect the complete state"
time="2019-04-24T06:34:44Z" level=debug msg="use the `terraform show` command."
time="2019-04-24T06:34:44Z" level=debug
time="2019-04-24T06:34:44Z" level=debug msg="State path: /tmp/openshift-install-232440634/terraform.tfstate"
time="2019-04-24T06:34:44Z" level=debug msg="OpenShift Installer v0.16.1"
time="2019-04-24T06:34:44Z" level=debug msg="Built from commit e3fceacc975953f56cb09931e6be015a36eb6075"
time="2019-04-24T06:34:44Z" level=info msg="Waiting up to 30m0s for the Kubernetes API at https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443..."
time="2019-04-24T06:35:14Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443/version?timeout=32s: dial tcp 13.234.206.93:6443: i/o timeout"
time="2019-04-24T06:35:31Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443/version?timeout=32s: dial tcp 13.234.206.93:6443: connect: connection refused"
time="2019-04-24T06:36:02Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443/version?timeout=32s: dial tcp 13.234.206.93:6443: connect: connection refused"
time="2019-04-24T06:36:32Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443/version?timeout=32s: dial tcp 13.234.206.93:6443: connect: connection refused"
time="2019-04-24T06:37:03Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.rsriniva-ocp4-cluster.dev.nextcle.com:6443/version?timeout=32s: dial tcp 13.234.206.93:6443: connect: connection refused"
time="2019-04-24T06:37:09Z" level=debug msg="Still waiting for the Kubernetes API: the server could not find the requested resource"
...
time="2019-04-24T07:04:31Z" level=debug msg="Still waiting for the Kubernetes API: the server could not find the requested resource"
time="2019-04-24T07:04:44Z" level=fatal msg="waiting for Kubernetes API: context deadline exceeded"

# What you expected to happen?

Installed OCP 4 cluster

# How to reproduce it (as minimally and precisely as possible)?

install-config.yaml snippet:

apiVersion: v1beta4
baseDomain: dev.nextcle.com
compute:
- name: worker
  platform:
    aws:
      zones:
      - ap-south-1a
      type: m4.xlarge
  replicas: 3
controlPlane:
  name: master
  platform:
    aws:
      zones:
      - ap-south-1a
      type: m4.xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: rsriniva-ocp4-dev
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ap-south-1
...

See attached install log.
[openshift_install.log](https://github.com/openshift/installer/files/3111010/openshift_install.log)

**Comment by wking** [comment]
See previous discussion in #1428 and #1553.

/close
