### ISSUE TITLE
Fails on second run if a temporary OS image exists

### ISSUE THREAD

**Issue by skitt** [openshift/installer#1668]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-879-g8eefb828e2aaf20dbbb953826a6ec1a95d6d8330
built from commit 8eefb828e2aaf20dbbb953826a6ec1a95d6d8330
release image registry.svc.ci.openshift.org/origin/release:v4.1
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

If the installer crashes (OOM...) while expanding an OS image, the next run fails because of the resulting temporary file:

```console
time="2019-04-24T14:37:25+02:00" level=fatal msg="failed to fetch Terraform Variables: failed to generate asset \"Terraform Variables\": failed to get libvirt Terraform variables: failed to use cached libvirt image: open /home/skitt/.cache/openshift-install/libvirt/image/77bc33c6249280fa9d3056095019ac18.tmp: file exists"
```

# What you expected to happen?

I expect the temporary file to be overwritten, or even better (if at all possible), re-used.

# How to reproduce it (as minimally and precisely as possible)?

Start creating a cluster, wait for the “Fetching OS image” message, check that the corresponding temporary file has been created, kill the installer, then start creating a cluster again.

I suspect this isn’t an installer bug but an issue somewhere else...

**Comment by skitt** [comment]
This needs to be re-tested, it might have been fixed in the meantime.

**Comment by zeenix** [comment]
@skitt did you manage to test?

**Comment by zeenix** [comment]
I just reproduced this successfully with latest git master:

```
FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get libvirt Terraform variables: failed to use cached libvirt image: open /home/zeenix/.cache/openshift-install/libvirt/image/6f383cd9e4ffc3c666b429d601ca642a.tmp: file exists 
```

**Comment by skitt** [comment]
I can reproduce this too.

**Comment by fgiloux** [comment]
I had the same issue. Due to my bad internet connection I had to download the qcow2 image before the installation and use OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE to get the cluster up and running.

**Comment by abhinavdahiya** [comment]
this should be fixed.

/close

**Comment by zeenix** [comment]
@abhinavdahiya Which commit should have fixed this? I'm still able to reproduce it:

```
INFO Fetching OS image: rhcos-420.8.20190708.2-qemu.qcow2 
DEBUG Unpacking OS image into "/home/zeenix/.cache/openshift-install/libvirt/image/9f9856c442135c03f1076aefdc33d349"... 
FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get libvirt Terraform variables: failed to use cached libvirt image: open /home/zeenix/.cache/openshift-install/libvirt/image/9f9856c442135c03f1076aefdc33d349.tmp: file exists
```

/reopen
