### ISSUE TITLE
is it possible to add "app Item" to Catalog???

### ISSUE THREAD

**Issue by angry-tony** [openshift/installer#1672]
Hello! all..

is there way to add "customized Item"  and see it on "Developer Catalog" in Openshift 4??
( openshift 3 can do it using "ASB + APB + local registry" )

**like below...**
![image](https://user-images.githubusercontent.com/18000837/56705270-3f141680-674b-11e9-9ebf-9dc2e503461d.png)

**Comment by abhinavdahiya** [comment]
please move this to https://github.com/openshift/console-operator/

/close
