### ISSUE TITLE
Choose subnets CIDR range for a better use of VPC IPs

### ISSUE THREAD

**Issue by fgero** [openshift/installer#1685]
# Version

```console
$ openshift-install version
./openshift-install v0.16.1
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

With our enterprise AWS accounts, we cannot easily reserve a /16 VPC to install one cluster.
We could use /18-20 VPCs (machineCIDR) but the IPI installer automatically uses /n+4 CIDR for all the public and private subnets it creates in the VPC.
With a /20 VPC (4096 IPs) and 3 AZ we end up having only 256 IPs per private AZ /24 subnet (max ~ 245 nodes per AZ suppose).  The public subnets have the same amount of IPs, but will be almost unused.

# What you expected to happen?

Let's keep the /20 VPC (4096 IPs) use case
I wonder if it was possible to generate something like  : 
- 3 x  /22 Private subnets (thus, 1024 IPs each)
- 3 x /24 Public subnets (we have even room for 4 within the remaining /22 area)

That would work for up to 3 AZs, of course.

That would make a better use of the VPC 4096 IPs (total 3072 IPs available for the 3 private subnets, instead of 1532)

# Ideas (or not..)

1/ Ideally : 
Add a new optional section to the IPI install-config.yaml,  in which the user must provide a complete list of subnets with their range, or a privateCIDR and publicCIDR

Or 2/ less ideal : 
change the terraform n+4 bits calculation 

in 
https://github.com/openshift/installer/blob/master/data/data/aws/vpc/vpc.tf
...we have half of the VPC range that's reserved for public : 

```
locals { 
  new_private_cidr_range =   "${cidrsubnet(data.aws_vpc.cluster_vpc.cidr_block,1,1)}"
  new_public_cidr_range =   "${cidrsubnet(data.aws_vpc.cluster_vpc.cidr_block,1,0)}"
}
```
And within 
https://github.com/openshift/installer/blob/master/data/data/aws/vpc/vpc-public.tf
and
https://github.com/openshift/installer/blob/master/data/data/aws/vpc/vpc-private.tf

...we have a fixed 3 bits to extend (that could be 2 bits if count.index is <=4, for example) : 

```
resource "aws_subnet"   "public_subnet" {
 count = "${local.new_az_count}"
 vpc_id = "${data.aws_vpc.cluster_vpc.id}"
 cidr_block = "${cidrsubnet(local.new_public_cidr_range, 3, count.index)}"
...
```

**Comment by abhinavdahiya** [comment]
we allow users to bring their own subnets, https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md#cluster-scoped-properties

so you should be able to get whatever split is more suitable.

/close
