### ISSUE TITLE
Unable to create cluster at AWS

### ISSUE THREAD

**Issue by ananth777** [openshift/installer#1695]
# Version

```console
$ openshift-install version
<your output here>
```
INFO Creating infrastructure resources...         
ERROR                                              
ERROR Error: Error applying plan:                  
ERROR                                              
ERROR 1 error occurred:                            
ERROR 	* module.vpc.aws_eip.nat_eip[0]: 1 error occurred: 
ERROR 	* aws_eip.nat_eip.0: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached. 
ERROR 	status code: 400, request id: 8e4e6bf7-f2c9-45ea-82f3-d6609702de85 
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR Terraform does not automatically rollback in the face of errors. 
ERROR Instead, your Terraform state file has been partially updated with 
ERROR any resources that successfully completed. Please address the error 
ERROR above and apply again to incrementally change your infrastructure. 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform 

# Platform (aws|libvirt|openstack):

Enter text here.

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?
I believe Cluster to be created on AWS 

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mazzystr** [comment]
The debug output is pretty clear.  You hit a limit on the number of EIPs in that region.  Delete some and/or create a support case with AWS to raise the limit.

**Comment by ananth777** [comment]
thanks a lot, let me create a case and reopen if needed
