### ISSUE TITLE
[RFE] Missing progress indicator during installation

### ISSUE THREAD

**Issue by tzvatot** [openshift/installer#1710]
The install process is very long, and there's no indication of work or steps that the installer is preforming.
I suggest having:
1. Steps that the installer is doing, presented in a list, and add a checked mark next to each step as soon as it's finished.
2. Add some rolling mark/progress bar like (limited by what you can achieve in terminal) that can indicate the installer is progressing.

**Comment by abhinavdahiya** [comment]
Although that is nice to have, we don't think it provides a lot additional of value to users,
we already provide important checkpoint updates and we are not looking at making it conform to progress-bar like.

/close
