### ISSUE TITLE
libvirt installation doc: possible centos fixes, way to reuse downloaded qcow2 image

### ISSUE THREAD

**Issue by brainfunked** [openshift/installer#1716]
1. kvm-common repo exists, but is now centos-qemu-ev. Installing the [repository configuration RPM ](http://mirror.centos.org/centos/7/virt/x86_64/kvm-common/centos-release-qemu-ev-1.0-1.el7.noarch.rpm) is probably the best way to enable it. Once the repo is configured, installing the qemu-kvm RPM automatically pulls the qemu-kvm-ev RPM, which has the necessary `-fw_cfg` support. On that note, it might be a good idea to mention the `-fw_cfg` related qemu failure in the troubleshooting section.

2. Would be a good idea to move the libvirtd configuration section just after the package installation and before libvirtd.service is enabled and started.

3. On CentOS 7, firewalld comes with a service file for libvirtd on TCP port 16509. This can be enabled by using `--add-service=libvirt` (note the lack of the "d").

4. To avoid re-downloading a fully downloaded rhcos base image, do the following:
  - Move the downloaded image file to the default pool storage (/var/lib/libvirt/images). I had the installation fail a due to [OOM errors](https://github.com/openshift/installer/issues/610). In this case, the image was available at `~/.cache/openshift-install/libvirt/image/<hash>.tmp`. The image itself needs to be named the same as the value of `images.qemu.path` from `<installer-checkout>/data/data/rhcos.json`.
  - Modify the same file `rhcos.json` mentioned in the previous step. Change the value of `baseURI` to be `file:///var/lib/libvirt/images/`.
  - `chcon system_u:object_r:virt_image_t:s0 /var/lib/libvirt/images/<image_name>`
  - Might be a good idea to also `chown qemu:qemu` the image file, but the file seems only to be read by the installer, so this shouldn't matter as long as the SELinux context is fine. In any case, SELinux needs to be disabled for the installer to work.
  - **Recompile the installer with `TAGS=libvirt` after modifying the `rhcos.json` file.**

**Comment by zeenix** [comment]
@brainfunked Thanks for reporting. I feel that this is a bunch of unrelated issues and hence it'd be nice to put them in separate issues. Could you kindly do that? Also, PRs addressing these issues would be awesome.

/priority awaiting-more-evidence

**Comment by brainfunked** [comment]
Yes, will split the issues up and send PRs.

**Comment by zeenix** [comment]
@brainfunked Great!, thanks so much.

**Comment by th3penguinwhisperer** [comment]
Number 1 would be good to be updated in the docs. It's not obvious what the fix here is.
