### ISSUE TITLE
libvirt: should support multiple clusters on a single host

### ISSUE THREAD

**Issue by skitt** [openshift/installer#1741]
This is a tracker for a feature request, and the feature might already be supported — at least, I know CIDRs can be configured in the manifests, and clusters with different names can be defined in parallel and will result in different libvirt resources.

Feel free to close this if it’s known to work; otherwise I’ll continue my investigations and add notes here.

**Comment by wking** [comment]
Ok, I dunno what the incantation is for getting Prow to add the platform/libvirt label ;).

**Comment by zeenix** [comment]
@skitt Did you get to test this?

/priority backlog

**Comment by skitt** [comment]
> @skitt Did you get to test this?
> 
> /priority backlog

No, I’ll add it to my queue for next week!

**Comment by ssbano** [comment]
is there any progress?

Best Regards,
Fabio Sbano

**Comment by zeenix** [comment]
Keeping in mind that we give everything unique names for each cluster, I'd assume this works already. @ssbano you could test it and re-open if it doesn't work.

/close
