### ISSUE TITLE
Waiting 30m0s for the kubernetes api 

### ISSUE THREAD

**Issue by matty1979** [openshift/installer#1745]
# Version

```console
$ openshift-install version ./openshift-install v4.1.0-201905091432-dirty
built from commit 969b7ef6a763d1a4af658f3f19eb1c2a85d573f0
release image quay.io/openshift-release-dev/ocp-release@sha256:713aae8687cf8a3cb5c2c504f65532dfe11e1b3534448ea9eeef5b0931d3e208
<your output here>
```

# Platform (aws|libvirt|openstack): AWS

Enter text here.

# What happened? 
Time out at waiting for the kubernetes api to enable

# What you expected to happen?
Sucessfull installation of the OCP4 console. 

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./openshift-install create cluster --dir=/downloads/openshift4 
```

# Anything else we need to know?

Unable to log in to get logs as it doesn't give me the password needed and I don't have a SSH key for the server.

# References

**Comment by abhinavdahiya** [comment]
We do not setup passwords. All debugging efforts require that you provide installer an ssh key when prompted.

`openshift-install gather bootstap` should provide details on how to gather logs.

**Comment by matty1979** [comment]
interesting, I tried running it on a local laptop and it asked for an ssh key this time. It didn't do that when I ran the installer on a cloud server ssh window. 
That said, the 
INFO Creating infrastructure resources...         
INFO Waiting up to 30m0s for the Kubernetes API
Is still occurring and I'm unsure what to do to progress further.

**Comment by matty1979** [comment]
time="2019-05-13T17:34:56-04:00" level=debug msg="Still waiting for the Kubernetes API: Get https://api.os4.xxx.xxx.chat:6443/version?timeout=32s: dial tcp x.x.x.x:6443: connect: connection refused"

**Comment by SonOfTheChief** [comment]
I have the same problem. The installer waited 30mins for the Kubernetes API and then failed with:
`FATAL waiting for Kubernetes API: context deadline exceeded`

**Comment by SonOfTheChief** [comment]
After deleting the whole cluster and installing it again two times it worked, no idea what the problem was.

**Comment by matty1979** [comment]
I've destroyed and reinstalled numerous times, I still receive the same errors. I can SSH to the machines so there's that, but nothing else is working within the Kubernetes API.

**Comment by abhinavdahiya** [comment]
Can you provide us the log tar file that installer recommends, so we can help debug.

Also see https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#kubernetes-api-is-unavailable

**Comment by matty1979** [comment]
oc --config=${INSTALL_DIR}/auth/kubeconfig --namespace=openshift-machine-api get deployments
error: stat /auth/kubeconfig: no such file or directory

**Comment by matty1979** [comment]
`Matthew-King-MacBook-Pro:openshift4 matthewking$ oc status
The connection to the server api.os.dev.openshift.octo.chat:6443 was refused - did you specify the right host or port?`

**Comment by wking** [comment]
> ```console
> $ oc --config=${INSTALL_DIR}/auth/kubeconfig --namespace=openshift-machine-api get deployments
> error: stat /auth/kubeconfig: no such file or directory
> ```

Looks like your `INSTALL_DIR` was empty.  You need to fill in whatever directory you used for assets when you called `openshift-install create ...` (`/downloads/openshift4` in your original post here).  But `oc` commands in general are not going to work without a Kubernetes API.  You need to gather bootstrap logs over `ssh` as folks [keep][1] [suggesting][2] [above][3].

[1]: https://github.com/openshift/installer/issues/1745#issuecomment-491965985
[2]: https://github.com/openshift/installer/issues/1745#issuecomment-492150449
[3]: https://github.com/openshift/installer/issues/1745#issuecomment-492318277

**Comment by matty1979** [comment]
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3182823/log-bundle.tar.gz)

**Comment by abhinavdahiya** [comment]
> [log-bundle.tar.gz](https://github.com/openshift/installer/files/3182823/log-bundle.tar.gz)

based on the file attached, it looks like the bootstrapping did finish...
Can you try again and provide, both `INSTALL_DIR/.openshift_install.log` and `log-bundle.tar.gz` from the run if it fails again.

**Comment by matty1979** [comment]
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3202624/log-bundle.tar.gz)
[openshift_install.log](https://github.com/openshift/installer/files/3202625/openshift_install.log)

**Comment by yangjinsay** [comment]
I also encountered the same problem as you, have you solved it?

**Comment by matty1979** [comment]
No it’s still an issue for me. I’m going to try again today to see if I can get it to install.

**Comment by matty1979** [comment]
Using the newest version, I noticed something with the elb creation phase as well as an error while tail -f the .openshift_install.log 

`time="2019-06-04T17:12:14-04:00" level=debug msg="Still waiting for the Kubernetes API: Get https://api.os4.openshiftdev.octo.chat:6443/version?timeout=32s: dial tcp: lookup api.os4.openshiftdev.octo.chat on 75.75.75.75:53: no such host"`

Even with changing off of Comcast DNS to google, I receive the same error. 



During the ELB creation phase, without fail one instance will not become healthy in one AZ. So I'm not quite sure what the issue is but, us-east-2b and us-east-2c are fine, us-east-2a is unhealthy. 

I did this earlier today and 2b was unhealthy.

**Comment by matty1979** [comment]
I tired this again today in us-west-2 and it worked correctly. No idea why this won’t work in us-east-2 though.

**Comment by abhinavdahiya** [comment]
Please re-open if issue re-appears.

/close

**Comment by Satyam1210** [comment]
I am facing the same issue in AWS. I tried these regions: us-east-1, us-east-2, us-west-2 with no success. Also tried using using openshift-install-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz, openshift-install-linux-4.5.0-0.okd-2020-10-03-012432.tar.gz, openshift-install-linux-4.2.16.tar.gz but all failed at the same point. 

`Still waiting for the Kubernetes API: Get https://api.test.okd.testing.fake.com:6443/version?timeout=32s: dial tcp: lookup api.test.okd.testing.fake.com on 10.0.0.2:53: no such host` 

for me also target group health check is failing. 
Does someone has a workaround for this?
