### ISSUE TITLE
Support deployment not directly attached to internet

### ISSUE THREAD

**Issue by patlachance** [openshift/installer#1766]
# Version

```console
$ openshift-install version
./openshift-install v4.1.0-201905061832-dirty
built from commit 9b486eedf57c20ce446b25734afc1187259a599e
release image quay.io/openshift-release-dev/ocp-release@sha256:be61a9ec132118e41a417b347242361d9cc96b1a73753e121dc7a74a1905baea
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

Nothing yet, can't install according to doc...

# What you expected to happen?

Installation should support configuring http_proxy as it was the case in OpenShift 3.x

# How to reproduce it (as minimally and precisely as possible)?

Didn't try to install using proxy as the documentation clearly mention that it is not supported.

# Anything else we need to know?

We need to trace all internet incoming and outgoing network flows and it must be done outside of OpenShift cluster as the cluster admins are not trusted.

We currently rely on http/https proxy and reverse proxy to log those network flows. Deploying directly attached to internet is not an option for us.

# References

From https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-default.html

> OpenShift Container Platform requires all machines, including the computer that you run the installation process on, to have direct internet access to pull images for platform containers and provide telemetry data to Red Hat.
> You cannot specify a proxy server for OpenShift Container Platform.

**Comment by katherinedube** [comment]
@patlachance This is already planned on our installer roadmap. We don't have a specific delivery date yet, but once we have it working we'll submit a PR. Thanks.

**Comment by DanyC97** [comment]
@wking can we close this one in favour of https://github.com/openshift/installer/issues/1831 ? ta

**Comment by ypakhomenko** [comment]
Hi All,

Is Internet access needed only for the installation || for the normal cluster operation as well?
Can I install 4.1 with a temporal Internet access enabled and then disable it?

Will it be possible to use the current satellite/capsule infrastructure for the RH content management also for the OCP 4.1?

Thanks & Regards

**Comment by ypakhomenko** [comment]
Thanks, so if the Internet access is needed for RH subscriptions only, then the cluster should remain operational if the Internet connectivity is blocked after the installation has been finishend, is this correct?

If not: what is the Internet connection needed for during the normal cluster operation?
(No updates, no scaling)

**Comment by DanyC97** [comment]
> Thanks, so if the Internet access is needed for RH subscriptions only, then the cluster should remain operational if the Internet connectivity is blocked after the installation has been finishend, is this correct?
> 
that is correct however see below

> If not: what is the Internet connection needed for during the normal cluster operation?
> (No updates, no scaling)

you still have telemetry enabled which needs access to push data back to RH. Also i think there is a connection needed for CVO which checks if a new release is been released ... this should be confirmed by a core dev person.

**Comment by wking** [comment]
Installer-provisioned nodes are private behind a NAT by default, so that definitely works.

**Comment by kfiresmith** [comment]
Big 'ol +1 from me as a customer who is subject to various government controls that require strict use of whitelist-only proxies.  IMO every Red Hat product needs a pre-release gate the blocks on proxy support.

**Comment by abhinavdahiya** [comment]
with combination of
a) imageContentSources

https://docs.openshift.com/container-platform/4.2/installing/installing_restricted_networks/installing-restricted-networks-aws.html#installing-restricted-networks-aws

b) 4.3 nightly) bring your own vpcs

c) 4.3 nightly) internal strategy https://github.com/openshift/installer/blob/master/docs/user/customization.md#platform-customization `publish`

you should be able to get private clusters.

/close
