### ISSUE TITLE
openshift-installer create cluster fails with qemu-kvm: -fw_cfg: invalid option'

### ISSUE THREAD

**Issue by flg77** [openshift/installer#1767]
# Version

openshift-install unreleased-master-1034-gf0aca3e8a0a196a748af03a29df40f66cb4910de
built from commit f0aca3e8a0a196a748af03a29df40f66cb4910de
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform (aws|libvirt|openstack):

libvirt

# What happened?
Install fails always at the following step:

INFO Creating infrastructure resources...
ERROR
ERROR Error: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-05-21 13:20:17.271+0000: Domain id=36 is tainted: custom-argv
ERROR 2019-05-21 13:20:17.271+0000: Domain id=36 is tainted: host-cpu
ERROR qemu-kvm: -fw_cfg: invalid option')
ERROR
ERROR   on ../tmp/openshift-install-452469032/main.tf line 76, in resource "libvirt_domain" "master":
ERROR   76: resource "libvirt_domain" "master" {
ERROR
ERROR
ERROR
ERROR Error: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-05-21 13:20:22.292+0000: Domain id=37 is tainted: custom-argv
ERROR 2019-05-21 13:20:22.292+0000: Domain id=37 is tainted: host-cpu
ERROR qemu-kvm: -fw_cfg: invalid option')
ERROR
ERROR   on ../tmp/openshift-install-452469032/bootstrap/main.tf line 11, in resource "libvirt_domain" "bootstrap":
ERROR   11: resource "libvirt_domain" "bootstrap" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
# What you expected to happen?

# How to reproduce it (as minimally and precisely as possible)?

build with libvirt enabled
enable terraforms-provider-libvirt
and initiate the install 
openshift-install create cluster 

# Anything else we need to know?

Tested on two different machines with the same result 

# References

**Comment by abhinavdahiya** [comment]
cc @zeenix @praveenkumar

**Comment by praveenkumar** [comment]
@fig77 Can you tell which version of libvirt/qemu you are using, most probably you are using an older one.

This seems to be duplicate of https://github.com/openshift/installer/issues/455 one.

**Comment by brainfunked** [comment]
If you're using the stock qemu-kvm from the base CentOS 7 repos, they cause this issue. This was solved for me by using the qemu-kvm-ev package from the [kvm-common repo.](http://mirror.centos.org/centos/7/virt/x86_64/kvm-common/). You can install the repo RPM and then do a `yum update` on an existing CentOS 7 installation.

**Comment by cfergeau** [comment]
This is already tracked in issue #1183 and PR #675

**Comment by zeenix** [comment]
> /duplicate #1183

Hm.. I could swear i saw this command. Anyway.

/close
/label triage/duplicate
