### ISSUE TITLE
tail: inotify resources exhausted

### ISSUE THREAD

**Issue by dantrainor** [openshift/installer#1773]
# Version

```console
$ openshift-install version
ocp/openshift-install f0b27c5583c4996cf70833d8d445035c35c1cad8-dirty
built from commit f0b27c5583c4996cf70833d8d445035c35c1cad8
release image registry.svc.ci.openshift.org/kni/release@sha256:1b8ca17442418b0295af5011d9d16829a3665fba9873ba6ec27968000d1e08f6

```

# Platform (aws|libvirt|openstack):
libvirt

# What happened?

Running openshift-installer via kni and ran in to:

[...]
level=debug msg="module.masters.ironic_node_v1.openshift-master.1: Still creating... (29m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (29m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.1: Still creating... (29m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (29m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (29m40s elapsed)"
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling

# What you expected to happen?

It looks like the 'tail' command is used internally somewhere and relies on inotify.  'tail' appears to be smart enough to fall back to polling, which appears to work fine, but leaves an unfamiliar message in the debug output.

# How to reproduce it (as minimally and precisely as possible)?
```console
$ ocp/openshift-install --dir ocp --log-level=debug create cluster
```

# Anything else we need to know?

Using the deployer as part of https://github.com/metalkube/dev-scripts but I think this affects upstream.

I did some digging, looks like this relies on a sysctl named fs.inotify.max_user_watches.  I think this is ok, but the default is a little low:

[rhhi@dev02 dev-scripts]$ sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 8192

Increasing this significantly - maybe even quadruple this amount - even as a pre-installation task should have no negative performance impact.  

Note that it's the first time I've ran in to this message having done probably 500+ deployments in testing.  Something may have changed in the backend that would have changed how many more inotifies watches are consumed.

# References

- http://peter-butkovic.blogspot.com/2013/08/tail-inotify-resources-exhausted.html
- https://nefaria.com/2014/08/tail-inotify-resources-exhausted/

**Comment by abhinavdahiya** [comment]
The installer doesn't have ironic backends. Maube open bug with https://github.com/openshift-metal3/kni-installer

/close
