### ISSUE TITLE
openshift-install create cluster libvirt failed: Error: Failed to instantiate provider "libvirt" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5

### ISSUE THREAD

**Issue by flg77** [openshift/installer#1784]
# Version
openshift-install unreleased-master-1042-gaa6cd95533840d08332aa3adda330d19626737f1
built from commit aa6cd95533840d08332aa3adda330d19626737f1
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform (aws|libvirt|openstack):
libvirt

# What happened?

After chained issues I finally got stuck at this: 

time="2019-05-23T12:02:00+02:00" level=debug msg="If you ever set or change modules or backend configuration for Terraform,"
time="2019-05-23T12:02:00+02:00" level=debug msg="rerun this command to reinitialize your working directory. If you forget, other"
time="2019-05-23T12:02:00+02:00" level=debug msg="commands will detect it and remind you to do so if necessary."
time="2019-05-23T12:02:00+02:00" level=error
time="2019-05-23T12:02:00+02:00" level=error msg="Error: Failed to instantiate provider \"libvirt\" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]"
time="2019-05-23T12:02:00+02:00" level=error
time="2019-05-23T12:02:00+02:00" level=error
time="2019-05-23T12:02:00+02:00" level=error msg="Failed to read tfstate: open /tmp/openshift-install-033211353/terraform.tfstate: no such file or directory"
time="2019-05-23T12:02:00+02:00" level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"

# What you expected to happen?

Installer to finish setup 

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

./hack/build.sh
openshift-install create cluster

# Anything else we need to know?

**Comment by abhinavdahiya** [comment]
Are you building with `dev` mode?

Please run the following command to gather detailed logs from internal terraform
```
TF_LOG=debug openshift-install create cluster
```
and attach the `.openshift_install.log`

**Comment by damobrisbane** [comment]
Without being able to replicate, it sounds like not picking up **terraform-provider-libvirt** plugin from the tmp build directory path. I would make sure do not have terraform-provider-libvirt anywhere else in PATH; may need to destroy and re-run setup (recreating tfvars, etc).

**Comment by czhujer** [comment]
for me, it was too newer version of terraform.

**Comment by flg77** [comment]
Hi, I was not able to respond *earlier*.
[openshift_install.log](https://github.com/openshift/installer/files/3261966/openshift_install.log)
On a second host I get the same results. 

But no environment variable should disturb the process

**Comment by abhinavdahiya** [comment]
from the logs:
```
time="2019-06-06T12:19:43+02:00" level=debug msg="2019/06/06 12:19:43 [DEBUG] checking for provider in \"/usr/local/sbin\""
time="2019-06-06T12:19:43+02:00" level=debug msg="2019/06/06 12:19:43 [WARN] found legacy provider \"terraform-provider-libvirt\""
```
it looks like you do have local libvirt provider in terraform's search path. Please remove that and retry.

Feel free to re-open, if you see the error again.

/close
