### ISSUE TITLE
Cert issues on bootstrap cluster.

### ISSUE THREAD

**Issue by stobias123** [openshift/installer#1792]
# Version

```console
$ openshift-install version
openshift-install v4.1.0-201905171742-dirty
built from commit d28dfe4dc0d89b507100c92e509a4bb618ec489f
release image quay.io/openshift-release-dev/ocp-release@sha256:dc67ad5edd91ca48402309fe0629593e5ae3333435ef8d0bc52c2b62ca725021
```

# Platform (aws|libvirt|openstack):

UPI

# What happened?

Running the openshift-install with terraform examples for vmware. Everything seems to go ok, API comes up, I can even interact with the kube cluster. 

However...
* No nodes are registered. 
* All pods related to cluster operations are stuck pending. (cluster version operator, etc.)

Bootkube logs on the bootstrap node show the below

```
 Get https://api.okd.myDOMAIN.dev:6443/api/v1/pods: x509: certificate has expired or is not yet valid
May 26 14:58:50 okd-boot-0 bootkube.sh[6353]: [#1489] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid
May 26 14:58:50 okd-boot-0 bootkube.sh[6353]: [#1490] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid
```
# What you expected to happen?

Cluster to be bootstrapped successfully.

# How to reproduce it (as minimally and precisely as possible)?

Run the terraform examples for vmware.

**Comment by mvknowles** [comment]
This is usually caused because of the installation certificate expiring as it only lasts 24hrs. You can check it with the following:
`echo | openssl s_client -connect api.okd.myDOMAIN.dev:6443:6443  | openssl x509 -noout -text`

Check these lines:

```
             Not Before: May 28 16:04:57 2019 GMT
             Not After : May 29 16:05:01 2019 GMT
```

**Comment by stobias123** [comment]
yeah. certs expired. thanks!
