### ISSUE TITLE
rootca.key missing

### ISSUE THREAD

**Issue by e-minguez** [openshift/installer#1797]
# Version

```console
$ openshift-install version
openshift-install v4.1.0-201905171742-dirty
built from commit 6ba66dbb6c2c53e1901a6d167d1c813bbbf27f4d
release image quay.io/openshift-release-dev/ocp-release@sha256:dc67ad5edd91ca48402309fe0629593e5ae3333435ef8d0bc52c2b62ca725021
```

# Platform (aws|libvirt|openstack):

Baremetal (but any)

# What happened?

If you want to create certificates to be signed by the rootca, the rootca.key is required and currently the rootca.key is not available anywhere 

# What you expected to happen?

When creating the openshift manifests, it would be nice to have the rootca.key as output as well.

# How to reproduce it (as minimally and precisely as possible)?

Try to get the root ca self generated key using openshift-install.

# Anything else we need to know?

# References

**Comment by abhinavdahiya** [comment]
rootca is not used to sign trust chains in the cluster. All the important trust chains with control-plane are distinct.

So rootca is not required and shouldn't be used to sign any new cert.

/close
