### ISSUE TITLE
Azure vhd image.

### ISSUE THREAD

**Issue by vguar** [openshift/installer#1804]
Hello everyone,

I would like to test ocp4 install on Azure.
For that I need a vhd image of rhcos.

I have tried to create a vhd image for azure from the following rhcos images: rhcos-410.8.20190520.0-vmware.ova and rhcos-410.8.20190520.0-openstack.qcow, but none of the 2 images work.

Either it does not boot (for the qcow version) or it does not find the ignition file (for the ova version).

Can you tell me which image rhcos I have to use to create my vhd image?

Thanks for your help,
Vincent.

**Comment by abhinavdahiya** [comment]
This is duplicate of https://github.com/openshift/installer/issues/1783

/close
