### ISSUE TITLE
Usability: docker auth token invalid is hidden deep in bootstrap node logs

### ISSUE THREAD

**Issue by sttts** [openshift/installer#1812]
When the Docker auth tokens are outdated in the cluster config, the installer starts installing, but the bootstrap node never comes alive. One has to log into the bootstrap node to see in the bootkube unit logs that the token is invalid.

Expected behaviour: openshift-install noticing this, either by smoke testing token beforehand, or by somehow forwarding the error to the admin console.

**Comment by abhinavdahiya** [comment]
closing in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1662106

/close
