### ISSUE TITLE
install-config.yaml deleted when running openshift-install

### ISSUE THREAD

**Issue by mathianasj** [openshift/installer#1819]
# Version

```console
$ openshift-install version
./bin/openshift-install v4.1.0-201905212232-dirty
built from commit 226288f70e78c0e2fbc077872cbcbb7e81a5d727
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6
```

# Platform (aws|libvirt|openstack):

bare metal

# What happened?

I build the ignition config files and the install-config.yaml file is deleted

# What you expected to happen?

The install-config.yaml file remains in place so I don't lose what I created in case I have to alter something.

# How to reproduce it (as minimally and precisely as possible)?

1. Create an install-config.yaml file by hand
1. Run ./openshift-install create ignition-configs --dir=<installation_directory>
1. The install-config.yaml file is deleted

**Comment by abhinavdahiya** [comment]
Please look at https://github.com/openshift/installer/issues/898 for previous discussion.

`create install-config --dir <installation_directory>` returns the consumed install-config.yaml to dir.

/close
