### ISSUE TITLE
Tilde expansion does not work in "--dir=<path>"

### ISSUE THREAD

**Issue by bysnupy** [openshift/installer#1821]
# Version

```console
$ openshift-install version
openshift-install v4.1.0-201905212232-dirty
built from commit 71d8978039726046929729ad15302973e3da18ce
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6
```

# Platform (aws|libvirt|openstack):

`aws`

# What happened?

Tilde `~` does not convert with directory of `$HOME`, `~` is just evaluated as a literal letter. 
`~` is expanded as home directory like a value of `$HOME` env, so there is some risk which can remove home directory when you remove the `~` directory which `openshift-installer` created.

See the following output.

```console
# openshift-install create install-config --dir=~/clusters
...
# ls -l .
total 52340
drwxr-xr-x. 3 root root       22 Jun  5 23:08 ~
...
# tree ./~
./~
└── clusters

```

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Like expected result in `Linux`, `~` would be converted as `$HOME` home directory.

```console
# openshift-install create install-config --dir=~/clusters
...
# ls -l ~/
total 52340
drwxr-xr-x. 3 root root       22 Jun  5 23:08 clusters
...
# tree ~/
$HOME
└── clusters

```

# How to reproduce it (as minimally and precisely as possible)?

Always, reproducing steps is provided a previous section.

# Anything else we need to know?

N/A

# References

**Comment by sallyom** [comment]
The `~` works as expected, but have to omit the `=`  so it's `--dir ~/installdir` instead of `--dir=~/installdir`

**Comment by bysnupy** [comment]
Thank you for your swift update ! @sallyom ,
I've verified the `~` expansion is working well as you mentioned ! I close this issue.
