### ISSUE TITLE
installer for OKD 4.1 on bare metal

### ISSUE THREAD

**Issue by uocxp** [openshift/installer#1825]
> OKD is upstream code base upon which Red Hat OpenShift Online and Red Hat OpenShift Container Platform are built

[red hat openshift 4 is now available](https://blog.openshift.com/red-hat-openshift-4-is-now-available/) when OKD 4.x will be available?
Is there any plans for making an installer for OKD 4.x on bare metal?

**Comment by DanyC97** [comment]
> > OKD is upstream code base upon which Red Hat OpenShift Online and Red Hat OpenShift Container Platform are built
> 
> [red hat openshift 4 is now available](https://blog.openshift.com/red-hat-openshift-4-is-now-available/) when OKD 4.x will be available?
> Is there any plans for making an installer for OKD 4.x on bare metal?

@uocxp thanks for your interest in OKD, yesterday more info was shared [1] (i'd strongly recommend to subscribe to that mailer and ask questions). As was mentioned, standby for more updates soon (everyone, including myself is eager to understand the details etc).


[1] http://lists.openshift.redhat.com/openshift-archives/users/2019-June/msg00017.html

**Comment by DanyC97** [comment]
with that said i think this issue can be closed, you agree ?

**Comment by uocxp** [comment]
yes for sure
