### ISSUE TITLE
v4.1.0 reports a dirty version 

### ISSUE THREAD

**Issue by caseydavenport** [openshift/installer#1828]
# What happened?

Installer reported a dirty version.

# What you expected to happen?

Release binary should report a non-dirty version.

# How to reproduce it (as minimally and precisely as possible)?

First:

```
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.1.0.tar.gz  
```

```
tar -xvf openshift-install-linux-4.1.0.tar.gz                                                                      
README.md
openshift-install
```

Then:
```
./openshift-install version  
./openshift-install v4.1.0-201905212232-dirty
built from commit 71d8978039726046929729ad15302973e3da18ce
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6
```

**Comment by wking** [comment]
71d8978039 is also a non-existent commit.  You can get the real commit with:

```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.1.0 | grep installer
  installer                                     https://github.com/openshift/installer                                     c6517384e71e5f09931c4da5e772fdec225d02ec
  installer-artifacts                           https://github.com/openshift/installer                                     c6517384e71e5f09931c4da5e772fdec225d02ec
```

but we don't have #1744 set for backporting to 4.1.z yet (would be easy to do if folks want it in 4.1.z).

**Comment by DanyC97** [comment]
> 71d8978039 is also a non-existent commit. You can get the real commit with:
> 
> ```
> $ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.1.0 | grep installer
>   installer                                     https://github.com/openshift/installer                                     c6517384e71e5f09931c4da5e772fdec225d02ec
>   installer-artifacts                           https://github.com/openshift/installer                                     c6517384e71e5f09931c4da5e772fdec225d02ec
> ```
> 
> but we don't have #1744 set for backporting to 4.1.z yet (would be easy to do if folks want it in 4.1.z).

@wking if you don't mind asking why 2 entries: `installer` and `installer-artifacts` pointing to same repo/ commit id ? i thought (could be very well wrong though) the entries showing in the release payload is a 1:1 mapping to each git repo/ commit id

**Comment by wking** [comment]
@DanyC97, see #1506.

**Comment by DanyC97** [comment]
> @DanyC97, see #1506.

kindly thank you

**Comment by oglok** [comment]
Any update on this? In the Akraino project, we have a job for building the installer recurrently with libvirt support, and adding the version. This wrong commit id makes the job fail.
