### ISSUE TITLE
[RFE] any way to create cluster without internet access (disconnected install)?

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1831]
# Version

```console
$ openshift-install version
<your output here>
```

# Platform (aws|libvirt|openstack):

Enter text here.

# What happened?

I am using openstack and because internal restriction I can't make the booted machines access internet and only have intranet access. I think most private clouds will also restrict those so any doc to refer to in order to create cluster under :
the cloud and compute node has internet access while booted vm (worker and master node) doesn't have ?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by wking** [comment]
We're working on it.  Some earlier discussion [here][1] and in #472.  I can't find a better tracker, so we can use this issue.

[1]: https://github.com/openshift/installer/issues/1083#issuecomment-457366928

**Comment by wking** [comment]
@DanyC97 turned up the existing #1766 tracker.

/close
