### ISSUE TITLE
Openstack install-config.yaml failed

### ISSUE THREAD

**Issue by ayaseen** [openshift/installer#1834]
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-1105-g0e4119dd152586a6cfed0f8bed512ceccbdfdac3-dirty
built from commit 0e4119dd152586a6cfed0f8bed512ceccbdfdac3
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform (aws|libvirt|openstack):
OpenStack

# What happened?

./openshift-install --dir=initial create install-config

? SSH Public Key /root/.ssh/id_rsa.pub
? Platform openstack
? Cloud ose4
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": You must provide exactly one of DomainID or DomainName to authenticate by Username

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

time="2019-06-08T17:29:03+03:00" level=debug msg="OpenShift Installer unreleased-master-1105-g0e4119dd152586a6cfed0f8bed512ceccbdfdac3-dirty"
time="2019-06-08T17:29:03+03:00" level=debug msg="Built from commit 0e4119dd152586a6cfed0f8bed512ceccbdfdac3"
time="2019-06-08T17:29:03+03:00" level=debug msg="Fetching \"Terraform Variables\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="Loading \"Terraform Variables\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"SSH Key\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Base Domain\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Platform\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Cluster Name\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Base Domain\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Pull Secret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Platform\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Image\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Bootstrap Ignition Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Kubeconfig Admin Client\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (admin-kubeconfig-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (admin-kubeconfig-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-complete-server-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-localhost-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="          Loading \"Certificate (kube-apiserver-localhost-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-service-network-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="          Loading \"Certificate (kube-apiserver-service-network-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-lb-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="          Loading \"Certificate (kube-apiserver-lb-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Kubeconfig Kubelet\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-complete-server-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kubelet-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kubelet-bootstrap-kubeconfig-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Master Machines\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Platform Credentials Check\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Image\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Master Ignition Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Root CA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Worker Machines\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Platform Credentials Check\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Image\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Worker Ignition Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Root CA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Common Manifests\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Ingress Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"DNS Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Platform Credentials Check\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Infrastructure Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Cloud Provider Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="          Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="          Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="          Loading \"Platform Credentials Check\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Network Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Network CRDs\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Root CA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (etcd-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (etcd-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (etcd-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (etcd-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (etcd-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (etcd-metric-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (etcd-metric-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (etcd-metric-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (etcd-metric-signer-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (etcd-metric-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (mcs)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Root CA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"CVOOverrides\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdCAConfigMap\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdClientSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdHostServiceEndpoints\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdHostService\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdMetricClientSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdMetricServingCAConfigMap\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdMetricSignerSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdNamespace\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdService\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdSignerSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"KubeCloudConfig\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"EtcdServingCAConfigMap\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"KubeSystemConfigmapRootCA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"MachineConfigServerTLSSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"OpenshiftConfigSecretPullSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"OpenshiftMachineConfigOperator\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Openshift Manifests\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Kubeadmin Password\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"BindingDiscovery\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"CloudCredsSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"KubeadminPasswordSecret\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"RoleCloudCredsSecretReader\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (admin-kubeconfig-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (admin-kubeconfig-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (aggregator)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (aggregator-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (aggregator-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (system:kube-apiserver-proxy)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (aggregator-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (aggregator-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (system:kube-apiserver-proxy)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (aggregator)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (etcd-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (etcd-metric-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (etcd-metric-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (etcd-metric-signer-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (etcd-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (etcd-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (journal-gatewayd)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Root CA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-lb-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-external-lb-server)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-lb-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-internal-lb-server)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-lb-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-lb-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-localhost-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-localhost-server)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-localhost-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-localhost-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-service-network-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-service-network-server)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-service-network-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-service-network-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-complete-server-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-complete-client-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (admin-kubeconfig-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kubelet-client-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kubelet-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-control-plane-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-control-plane-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-lb-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-localhost-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-service-network-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-to-kubelet-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kube-apiserver-to-kubelet-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kubelet-bootstrap-kubeconfig-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="        Loading \"Certificate (kubelet-bootstrap-kubeconfig-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-to-kubelet-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-to-kubelet-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-apiserver-to-kubelet-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-apiserver-to-kubelet-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-control-plane-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-control-plane-kube-controller-manager-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-control-plane-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-control-plane-kube-scheduler-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kube-control-plane-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kube-control-plane-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kubelet-bootstrap-kubeconfig-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kubelet-client-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kubelet-client)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kubelet-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (kubelet-serving-ca-bundle)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Loading \"Certificate (kubelet-signer)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Certificate (mcs)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Root CA\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Loading \"Key Pair (service-account.pub)\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Master Ignition Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Master Machines\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Loading \"Worker Machines\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="  Fetching \"Cluster ID\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="    Fetching \"Install Config\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Fetching \"SSH Key\"..."
time="2019-06-08T17:29:03+03:00" level=debug msg="      Generating \"SSH Key\"..."
time="2019-06-08T17:29:05+03:00" level=debug msg="      Fetching \"Base Domain\"..."
time="2019-06-08T17:29:05+03:00" level=debug msg="        Fetching \"Platform\"..."
time="2019-06-08T17:29:05+03:00" level=debug msg="        Generating \"Platform\"..."
time="2019-06-08T17:29:07+03:00" level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Cluster ID\": failed to fetch dependency of \"Install Config\": failed to fetch dependency of \"Base Domain\": failed to generate asset \"Platform\": You must provide exactly one of DomainID or DomainName to authenticate by Username"

# What you expected to happen?

Generate config-install.yaml

**Comment by mandre** [comment]
It looks like gophercloud wasn't able to authenticate against your `ose4` cloud. 

The logs say "You must provide exactly one of DomainID or DomainName to authenticate by Username".
Check that you only have either DomainID or DomainName in your clouds.yaml file for `ose4`, not both at the same time.

On our side, we should  handle the error better instead of spitting out misleading Terraform failures.

**Comment by ayaseen** [comment]
This what I have in clouds.yaml

  ose4:
    auth:
      auth_url: http://192.168.1.3:5000/v3
      username: "demo1"
      project_name: "demo"
      password: "demo1"
      user_domain_name: "Default"
      project_domain_name: "Default"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3

Also I dsiable user_domain_name , still quickly got the errors.

**Comment by mandre** [comment]
Try removing `project_domain_name`.
If you have access to horizon you could  connect to your cloud and download valid clouds.yaml file from "Project > API Access".

**Comment by admiyo** [comment]
On the Keystone Side, DomainName or DomainId should never be specified.  For a project scoped token, it should be ( ProjectDomainName and ProjectName ) or ProjectId to get a scoped token.  There  user will not likely have  Domain Scoped token, and thus using DomainName or DomainId will fail.

The same is true for UserDomainName.  This should always be present with UserName, or the user should provide UserId.

NMote that I am using the Camel Case from the Go code, but the appropriate values are in snake case in the clouds.yaml

**Comment by mandre** [comment]
Thanks @admiyo, this is useful info.
I'm going to close this bug since it's likely caused by a bogus `clouds.yaml` and I assume it's now fixed on the reporter' side. @ayaseen please re-open if that's not the case.

/close

**Comment by admiyo** [comment]
On the Keystone Side, DomainName or DomainId should never be specified.  For a project scoped token, it should be ( ProjectDomainName and ProjectName ) or ProjectId to get a scoped token.  There  user will not likely have  Domain Scoped token, and thus using DomainName or DomainId will fail.

The same is true for UserDomainName.  This should always be present with UserName, or the user should provide UserId.

NMote that I am using the Camel Case from the Go code, but the appropriate values are in snake case in the clouds.yaml

**Comment by mrostamii** [comment]
Mine has occurred the error when I used filename `.config/openstack/clouds.yml` instead of the correct one which is `.config/openstack/clouds.yaml`.
In addition, I have had that problem with OKD(OpenShift Origin) [v4.7.0](https://github.com/openshift/okd/releases/tag/4.7.0-0.okd-2021-06-04-191031). It was ok with OpenShift Enterprise.
