### ISSUE TITLE
Support oc cluster up

### ISSUE THREAD

**Issue by magick93** [openshift/installer#1837]
Please dont decommission `oc cluster up`. 

Users have built internal systems, tools and development processes that use `oc cluster up`. This is an extremely simple way for developers to get started. 

How many steps do you expect a user to follow according to https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md ? 

How much more complicated is this compared to running `oc cluster up`?

**Comment by wking** [comment]
https://github.com/code-ready/crc is working on packaging for local-VM use-cases, you probably want to check there.

/close
