### ISSUE TITLE
Improve minimum requirements 

### ISSUE THREAD

**Issue by magick93** [openshift/installer#1838]
The docs for baremetal state:
> The smallest OpenShift 4.x clusters require the following host:
> 1 bootstrap machine.
> 3 control plane machines.
> at least 1 worker machine.

This should be considered a regression, as currently 3.11 can run on a single node. 

The new minimum requirement massively increases the barrier to entry.

**Comment by DanyC97** [comment]
@magick93 the docs does a recommendation for a production ready environment and not for a dev type environment. 

Saying that the minimum number of hosts for a dev env are:
* 1 bootstrap machine => could be destroyed once the cluster is up and running, is temporary and the same applies to prod env
* 1 master => you can go that way if you really want for your dev env
* 1 or n compute nodes

Is not that too much increase in the entry barrier

**Comment by glennswest** [comment]
brew install minishift
minishift start

So yes, its a huge increase.

Second the number of dns entries. Before only needed 1 and 1 wildcard, and a noip would work for 1 of those.

The kvm support not being backed in is another pain, and on top of that, it does not work with default kvm rpm, even on rhel8. Fedora maybe it will work. 

Also the manual flow for bare metal, which really requires the setup via pxe boot seems big barrier.

And a better debug guide would be really helpful.

**Comment by abhinavdahiya** [comment]
The docs provide accurate description of the requirements for the productions environment.
/close

> Also the manual flow for bare metal, which really requires the setup via pxe boot seems big barrier

bare metal doesn't require pxe boot, booting from iso is also supported. https://docs.openshift.com/container-platform/4.1/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-iso_installing-bare-metal

> And a better debug guide would be really helpful.

please open a specific bug on what information was missing.. installer logs trace level logs in `INSTALL_DIR/.openshift_install.log`

> brew install minishift
> minishift start
> So yes, its a huge increase.

I am not sure if minishift was equivalent to openshift 3.x, while the installer for OpenShift 4 is using VMs/servers to create a production-ready OpenShift cluster.

**Comment by DanyC97** [comment]
> brew install minishift
> minishift start
> 
> So yes, its a huge increase.
> 

in fairness @glennswest i think you are making a fair comparison.
Yes in 3.x you had minishift and `oc cluster up` however none of them were exercising 3.x openshift-ansible installer and as such you were getting different behaviour/ output.

Now the installer primary goal is for real (production) deployments however is flexible enough to reduce the footprint should you wish.

if you would look into the comments https://github.com/openshift/installer/issues/1837 you will find an alternative which again is not s'thing supported by RH however it might work for you.

> Second the number of dns entries. Before only needed 1 and 1 wildcard, and a noip would work for 1 of those.
> 

The story is very simple here:
* in 3.x folks (including myself) ignored any recommendation mentioned in the openshift docs to register the nodes in DNS, as well as the subdomain wildcard for the Routes. Everyone was bending / cutting corners where`/etc/hosts` was their DNS server.
* in 4.x the game changed where the DNS is no longer a loose/ nice to have req but is a must. And the must comes very much from the fact that the `app`/ `app-int`/ `*.apps`<cluster name>.<base domain> are fully embedded in the installer. In addition one of the key DNS req is the `SRV` etcd records.
