### ISSUE TITLE
[RFE]: patch terraform dns provider to allow SRV records

### ISSUE THREAD

**Issue by DanyC97** [openshift/installer#1840]
For folks who are trying to deploy on prem by leveraging the terraform upi code, should they wish to register the DNS records (pre-req) in a local (not R53) DNS server then be aware that terraform dns provider doesn't support `SRV` records

Terraform community provided a [PR](https://github.com/terraform-providers/terraform-provider-dns/pull/70) but not much interest (yet) from hashicorp and so my ask/ question is: are you happy to include a dns provider fork ( with the above PR included) in the installer ? 

Otherwise i think would be nice to document this gap which **_is not_** caused by openshift/ RH but 3rd party

/cc @abhinavdahiya @wking @staebler  your thoughts ?

**Comment by abhinavdahiya** [comment]
The installer provide **examples** for how to create clusters for user-provisioned. The users can use any provider they like, as long the DNS, LB requirements are being fulfilled.

/close

**Comment by DanyC97** [comment]
> The installer provide **examples** for how to create clusters for user-provisioned. The users can use any provider they like, as long the DNS, LB requirements are being fulfilled.
> 
> /close

with all respect @abhinavdahiya you were missing the point here, so let expand a bit (in case you ever read this again) ....

i understand that installer does provides examples for UPIs however this examples are most of the time used by folks coming and exploring how things are being done. It was the case with [openshift-ansible-contrib](https://github.com/openshift/openshift-ansible-contrib) examples and same it was with various cloud provider inventories in 3.x - see [here](https://github.com/openshift/openshift-ansible/tree/release-3.11/inventory/dynamic)

At the same time, the same examples are your UPI's sale story ( _hey, check this templates and get a working UPI env up_)  and as such all i was trying to say was:

1) rather than surprise folks later on with the examples where R53 is a dependency for DNS pre-req maybe you can improve it and remove R53 (even if the 3rd party tool - in this case `terraform` has a gap)
    * now i understand if this is not ideal as then you will need to support a fork ... so yes i can agree that you can ditch this idea
2) however i think is sensible to add a note [here](https://github.com/openshift/installer/blob/master/docs/user/vsphere/install_upi.md) and then [here](https://github.com/openshift/installer/tree/master/upi/vsphere) to say that _R53 is a pre-req and for other terraform dns providers users should check if `SRV` record type is supported_


P.S - should you consider my 2nd point, i'm happy to send out a PR, let me know
