### ISSUE TITLE
Provide "API URL" additionally when installation complete

### ISSUE THREAD

**Issue by bysnupy** [openshift/installer#1844]
# Version

```console
$ openshift-install version
openshift-install v4.1.0-201905212232-dirty
built from commit 71d8978039726046929729ad15302973e3da18ce
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6
```

# Platform (aws|libvirt|openstack):

`aws`

# What happened?

For more clarification, it had better to add `API URL` to installation result summary.

Look [login to ocp4 shows error - error: invalid character '<' looking for beginning of value](https://bugzilla.redhat.com/show_bug.cgi?id=1673911) it's confusing for users. 
Because  `API URL` was same with web console URL at `v3.x`. But `v4.x` is different with it.

# What you expected to happen?

Add `API URL` to installation summary text.

* Current
~~~console
...
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/myuser/cluster/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console.cluster.example.com 
INFO Login to the console with user: kubeadmin, password: xxxxxxxxxx
~~~

* After adding `API URL`
~~~console
...
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/myuser/cluster/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console.cluster.example.com 
INFO Access the OpenShift api here: https://api.cluster.example.com:6443
INFO Login to the console with user: kubeadmin, password: xxxxxxxxxx
~~~

# How to reproduce it (as minimally and precisely as possible)?

N/A

# Anything else we need to know?

N/A

**Comment by abhinavdahiya** [comment]
The kubeconfig provided to the user has the API_URL set. So I don't think there's a need to provide that information again.

**Comment by bysnupy** [comment]
Thank you for update @abhinavdahiya,
I also agree your thought.
But I think it's reasonable to provide API URL from installation summary even though it's duplicated. It's kind way to user and It may save some time looking for API URL or suppress some issues like using console URL as API URL.

**Comment by abhinavdahiya** [comment]
> But I think it's reasonable to provide API URL from installation summary even though it's duplicated. It's kind way to user and It may save some time looking for API URL or suppress some issues like using console URL as API URL.

The installer is explicit that the url is for the console, and I don't think duplicating the API URL, as the API url is only useful for clients of the API, which all of them require kubeconfig...

/close

**Comment by bysnupy** [comment]
@abhinavdahiya Thank you for your response.
