### ISSUE TITLE
vmware missing documentation 

### ISSUE THREAD

**Issue by Fodoj** [openshift/installer#1845]
In terraform example for VMware there is a reference to a template: https://github.com/openshift/installer/blob/master/upi/vsphere/machine/main.tf#L41

How is this template created out of .ova file?

**Comment by staebler** [comment]
See https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-machines_installing-vsphere.

**Comment by Fodoj** [comment]
This documentation doesn't show how to create a template though, only one VM after another

**Comment by staebler** [comment]
Step 6. "In the vSphere Client, create a template for the OVA image."

**Comment by Fodoj** [comment]
Does it mean creating a VM out of it first and then cloning this VM to template? Will this allow to override ignition configurations and if yes - how?

**Comment by staebler** [comment]
Yes. You create a VM using the OVA image. Then, you clone that VM to create the bootstrap, control plane, and compute VMs. You can set the ignition configurations on each of those by setting the vApp properties. The ignition configurations can be modified until the first boot. So, as long as you do not set the ignition configuration on the template VM and boot that template VM, then you can set the ignition configurations on the clone VMs.

**Comment by Fodoj** [comment]
Does it mean I won't be able to use regular ignition as a provisioning user data? Only passing it as vApp is supported right now ? Thanks for your answers!
