### ISSUE TITLE
Azure destroyer fails on DNS delete

### ISSUE THREAD

**Issue by mjudeikis** [openshift/installer#1851]
# Version
Master

# Platform (aws|libvirt|openstack):
Azure

# What happened?

Azure is using private DNS groups. 
Azure destroyer is using `RG` api to delete all resources.
`RG/ARM` api is using old dns client so deletion of private DNS zones does not work.

How to recreate:
1. Create RG with private DNS record inside of it
2. Try delete DNS record directly - works.
3. Try delete RG with all the resources inside of it - fails with
```
Private zone feature is not supported in version '2016-04-01'
```

Because Azure destroyer is using `RG/ARM` api - this fails.

/kind bug

**Comment by abhinavdahiya** [comment]
I'm not sure this is an installer bug. Azure should be capable of deleting the resource group and items inside it unless there is dependencies outside the resource group.

**Comment by mjudeikis** [comment]
Its not Installer bug, its Azure. This is just workaround until its get sorted in azure. Azure ARM API uses old API for tested resources when using resource API. Im in private conversation with MSFT on this.

**Comment by mjudeikis** [comment]
/close 
fixed in upstream
