### ISSUE TITLE
Installer failed but cluster was created

### ISSUE THREAD

**Issue by asorokhtey** [openshift/installer#1853]
# Version

```console
[asorok@MiWiFi-R3-srv olm]$ openshift-install version
openshift-install v4.1.0-201905171742-dirty
built from commit 6ba66dbb6c2c53e1901a6d167d1c813bbbf27f4d
release image quay.io/openshift-release-dev/ocp-release@sha256:dc67ad5edd91ca48402309fe0629593e5ae3333435ef8d0bc52c2b62ca725021
```

# Platform:
aws

# What happened?

I've tried to create cluster two times but installer failed with error:
```RROR Error: Error applying plan: ERROR ERROR 1 error occurred: ERROR * module.dns.aws_route53_record.api_external: 1 error occurred: ERROR * aws_route53_record.api_external: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.amq-streams.openshift-aws.rhocf-dev.com.', type='A'] but it already exists] ERROR status code: 400, request id: 5f547eca-83ab-11e9-811e-2fb90b12a499```

Than I chose another region and cluster successfully started and works fine but I received alert that I'm running some other two clusters.
Looks like other two clusters were created by first two tries when installer failed

# What you expected to happen?

Only one cluster created

# How to reproduce it (as minimally and precisely as possible)?

Try to deploy coulple of cluster in one subdomain in one region.

```console
[asorok@MiWiFi-R3-srv ocp4]$ openshift-install create install-config 
? SSH Public Key /home/asorok/.ssh/key.pub 
? Platform aws 
? Region us-west-1 
? Base Domain openshift-aws.rhocf-dev.com 
? Cluster Name amq-streams
```

**Comment by abhinavdahiya** [comment]
If you used installer to create 2 clusters, I think it is expected that you get resources created for 2 clusters..? So i'm not sure why expectation was `Only one cluster created`.

Destroy your cluster (or even partially created cluster) using `openshift-install destroy cluster`, before you retry to create another cluster.

> RROR Error: Error applying plan: ERROR ERROR 1 error occurred: ERROR * module.dns.aws_route53_record.api_external: 1 error occurred: ERROR * aws_route53_record.api_external: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.amq-streams.openshift-aws.rhocf-dev.com.', type='A'] but it already exists] ERROR status code: 400, request id: 5f547eca-83ab-11e9-811e-2fb90b12a499

That error specifies that DNS records already exist for that name, and creating the records for this attempt would overwrite the previous records which is very dangerous, so the installer failed correctly.

DNS records are not region based, they are global, no please do not reuse clustername and basedomain.

/close
