### ISSUE TITLE
Some components stay in 'pending' state because nodes have taints 'noschedule' on them?

### ISSUE THREAD

**Issue by jomeier** [openshift/installer#1855]
Hi,

during one hour of installation of OpenShift 4 on OpenStack stein I found all pods running instead a few (registry, prometheus, ...) which stayed in 'pending' state.

After a little bit of research I found out that all master nodes had this taint on them:
```
Taints:             node-role.kubernetes.io/master:NoSchedule
```

The installer stopped after a while because of time out.

I removed the taints from the master nodes and the pending pods started deploying immediately.

Is this expected behaviour or are this pods supposed to be spawned on the worker nodes?

Thanks for your assistance,

Josef

Installer version:
./openshift-install unreleased-master-1112-g7a54a6b120a0044cf9c07b14331760af8e3c216b-dirty
built from commit 7a54a6b120a0044cf9c07b14331760af8e3c216b
release image registry.svc.ci.openshift.org/origin/release:4.2

**Comment by tomassedovic** [comment]
Yes, some of the pods are expected to run on the worker nodes. The OpenShift console (the web UI) is another example.

The installer will eventually fail if at least one worker doesn't came up because these pods won't get scheduled.

**Comment by abhinavdahiya** [comment]
OpenShift currently requires worker nodes for complete installation, so I'm not sure what's the issue here.

And as for allowing workloads on control plane nodes, that's an RFE that we are already tracking.

/close
