### ISSUE TITLE
openstack: Error: cloud openstack does not exist in clouds.yaml

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1857]
# Version

```console
$ openshift-install version
<your output here>
```
[root@jichen-openstack-1 installer]# bin/openshift-install version
bin/openshift-install unreleased-master-1125-g40c771692dfab964294b8022d810921e1bb5b4c1-dirty
built from commit 40c771692dfab964294b8022d810921e1bb5b4c1
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform (aws|libvirt|openstack):

Enter text here.

# What happened?
follow the README and use `shiftstack` in input but got following error, the 
terraform.openstack.auto.tfvars.json has following setting:
"openstack_credentials_cloud": "openstack",

[root@jichen-openstack-1 installer]# ./bin/openshift-install create install-config
? SSH Public Key /root/.ssh/id_rsa.pub
? Platform openstack
? Cloud shiftstack

INFO Creating infrastructure resources...
ERROR
ERROR Error: cloud openstack does not exist in clouds.yaml
ERROR
ERROR   on ../../../../../../tmp/openshift-install-995688511/main.tf line 1, in provider "openstack":
ERROR    1: provider "openstack" {
ERROR
ERROR
ERROR Failed to read tfstate: open /tmp/openshift-install-995688511/terraform.tfstate: no such file or directory
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
[root@jichen-openstack-1 installer]# ls

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
I'm not able to reproduce this issue with the latest master even when changing my clouds.yaml to look like the one in the README. Do you mind posting your clouds.yaml file?

**Comment by jichenjc** [comment]
The code I am using  is 40c771692dfab964294b8022d810921e1bb5b4c1, which is Jun 14

clouds.yaml

[root@jichen-openstack-1 installer]# cat clouds.yaml
clouds:
  shiftstack:
    auth:
      auth_url: http://10.43.0.185:5000/v3
      project_name: admin
      username: admin
      password: xxxxxxxxxx
      user_domain_name: Default
      project_domain_name: Default

the difference is I am using following steps because I need do some changes (change master from 3 to 1 due to resource limit) but I don't think that's related the my question @mandre 

./bin/openshift-install create install-config
./bin/openshift-install create manifests
./bin/openshift-install create ignition-configs
./bin/openshift-install create cluster

**Comment by jichenjc** [comment]
sorry, I tried again by using create cluster directly just now, same result...


```
[root@jichen-openstack-1 installer]# ./bin/openshift-install create cluster
? SSH Public Key /root/.ssh/id_rsa.pub
? Platform openstack
? Cloud shiftstack
? Region RegionOne
? ExternalNetwork public
? FlavorName m1.small
? Base Domain test
? Cluster Name test
[root@jichen-openstack-1 installer]# ./bin/openshift-install create cluster
INFO Creating infrastructure resources...
ERROR
ERROR Error: cloud openstack does not exist in clouds.yaml
ERROR
ERROR   on ../../../../../../tmp/openshift-install-116225943/main.tf line 1, in provider "openstack":
ERROR    1: provider "openstack" {
ERROR
ERROR
ERROR Failed to read tfstate: open /tmp/openshift-install-116225943/terraform.tfstate: no such file or directory
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform

````

**Comment by jichenjc** [comment]
terraform.openstack.auto.tfvars.json

```
{
  "openstack_region": "RegionOne",
  "openstack_base_image": "rhcos",
  "openstack_external_network": "public",
  "openstack_credentials_cloud": "openstack",
  "openstack_master_flavor_name": "m1.small",
  "openstack_trunk_support": "1"
}

```

**Comment by mandre** [comment]
Thanks! You can workaround the issue by exporting the `OS_CLOUD` environment variable prior to deploying, it will take precedence over the `openstack_credentials_cloud` tf var.
I always have the OS_CLOUD variable set and that's the reason I couldn't reproduce at first.

https://github.com/openshift/installer/pull/1858 is likely a step in the right direction however there seems to be some assumptions about the cloud name causing the workers not to come up. Looking into a proper fix.

**Comment by jichenjc** [comment]
I don't fully understand the 'the cloud name causing the workers no to come up'
as if I manually change openstack_credentials_cloud,  and try again, everything is fine...
anyway, if you can provide some guide / hint on what's the proper fix, it will be very helpful~

**Comment by pierreprinetti** [comment]
Hi @jichenjc,

I have tried to reproduce with [the current `master`](https://github.com/openshift/installer/tree/f293e7a15b2ce81468b14b323916c318eda1514a).
In my tests, the installer correctly generated `terraform.openstack.auto.tfvars.json`.`openstack_credentials_cloud` using the input provided through `create install-config`; the value was correctly picked up during installation without `OC_CLOUD` being set in the environment.

Are you still experiencing this problem?

**Comment by jichenjc** [comment]
I haven't have this for a while, let's close this and reopen if needed.. thanks ~
