### ISSUE TITLE
openstack: delete cluster will never end

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1859]
# Version

```console
$ openshift-install version
<your output here>
```
bin/openshift-install unreleased-master-1125-g40c771692dfab964294b8022d810921e1bb5b4c1-dirty
built from commit 40c771692dfab964294b8022d810921e1bb5b4c1
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform (aws|libvirt|openstack):
openstack 

Enter text here.

# What happened?

delete cluster never end, use debug option shows it keep deleting network and subnets but not complete, we should give an error message at least if debug not enabled. and we need check why delete failed (I didn't have any manual changes to network )

```
[root@jichen-openstack-1 installer]# ./bin/openshift-install destroy cluster --log-level debug
DEBUG OpenShift Installer unreleased-master-1125-g40c771692dfab964294b8022d810921e1bb5b4c1-dirty
DEBUG Built from commit 40c771692dfab964294b8022d810921e1bb5b4c1
DEBUG Deleting openstack networks
DEBUG Deleting openstack servers
DEBUG Deleting openstack routers
DEBUG Deleting openstack ports
DEBUG Deleting openstack trunks
DEBUG Deleting openstack subnets
DEBUG Deleting openstack security-groups
DEBUG Deleting openstack containers
DEBUG Exiting deleting openstack ports
DEBUG goroutine deletePorts complete
DEBUG Deleting Subnet: 61083c96-486a-4f5b-8ed6-075a8b7eb4e0
DEBUG Deleting network: f5c0d547-a7c8-4c89-80e6-45e1ba758ee0
DEBUG Exiting deleting openstack security-groups
DEBUG goroutine deleteSecurityGroups complete
DEBUG Exiting deleting openstack networks
DEBUG Exiting deleting openstack trunks
DEBUG goroutine deleteTrunks complete
DEBUG Exiting deleting openstack subnets
DEBUG Exiting deleting openstack containers
DEBUG goroutine deleteContainers complete
DEBUG Removing Subnet e651de31-6fb9-4a2d-aee8-6d4b09eb86f2 from Router a11b26a2-b880-410e-898a-045aa39d805d
DEBUG Exiting deleting openstack servers
DEBUG goroutine deleteServers complete
DEBUG Exiting deleting openstack routers
DEBUG Deleting openstack networks
DEBUG Deleting openstack subnets
DEBUG Deleting network: f5c0d547-a7c8-4c89-80e6-45e1ba758ee0
DEBUG Exiting deleting openstack networks
DEBUG Deleting Subnet: 61083c96-486a-4f5b-8ed6-075a8b7eb4e0
DEBUG Exiting deleting openstack subnets
DEBUG Deleting openstack routers
DEBUG Removing Subnet e651de31-6fb9-4a2d-aee8-6d4b09eb86f2 from Router a11b26a2-b880-410e-898a-045aa39d805d
DEBUG Exiting deleting openstack routers
DEBUG Deleting openstack networks
DEBUG Deleting openstack subnets
DEBUG Deleting network: f5c0d547-a7c8-4c89-80e6-45e1ba758ee0
DEBUG Deleting Subnet: 61083c96-486a-4f5b-8ed6-075a8b7eb4e0
DEBUG Exiting deleting openstack subnets
DEBUG Exiting deleting openstack networks
DEBUG Deleting openstack routers
DEBUG Removing Subnet e651de31-6fb9-4a2d-aee8-6d4b09eb86f2 from Router a11b26a2-b880-410e-898a-045aa39d805d
DEBUG Exiting deleting openstack routers
DEBUG Deleting openstack subnets
DEBUG Deleting openstack networks
DEBUG Deleting Subnet: 61083c96-486a-4f5b-8ed6-075a8b7eb4e0
DEBUG Deleting network: f5c0d547-a7c8-4c89-80e6-45e1ba758ee0

```

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by zeenix** [comment]
@jichenjc Thanks for the report. Could you please edit the description to specify the platform?

**Comment by jichenjc** [comment]
@zeenix thank you for reminder, I updated just now , as title indicated, it's an openstack issue :)

**Comment by mandre** [comment]
Could it be that you provisioned another VM on the same subnet and that causes OpenStack to refuse to remove the networking resources because they're still in use?

**Comment by jichenjc** [comment]
no, I am following the instructions and no other vm created... and, several times has same result
I think something like 'router interface remove' didn't execute but not 100% sure, still debuging
