### ISSUE TITLE
prevent sensitive data in log output

### ISSUE THREAD

**Issue by mjudeikis** [openshift/installer#1862]
When running test clusters in CI sometimes cluster are long lived for debug purposes.
When consuming installer as a library we need a way to tell "installer" to either obfuscate or not log at all sensitive data as the same process is provisioning multiple clusters and we can't log any sensitive data.

```
time="2019-06-18T13:13:40Z" level=info msg="To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/prow/go/src/github.com/openshift/openshift-azure/_data/clusters/ci-1728-create-djevnn/auth/kubeconfig'" func=github.com/openshift/openshift-azure/pkg/util/installer.logComplete file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/installer/installer.go:166"
time="2019-06-18T13:13:40Z" level=info msg="Access the OpenShift web-console here: https://console-openshift-console.apps.ci-1728-create-djevnn.osadev.cloud" func=github.com/openshift/openshift-azure/pkg/util/installer.logComplete file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/installer/installer.go:167"
time="2019-06-18T13:13:40Z" level=info msg="Login to the console with user: kubeadmin, password: QKopq-SbU8e-xxx-xxx" func=github.com/openshift/openshift-azure/pkg/util/installer.logComplete file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/installer/installer.go:168"
```

The proposal would be to add some kind of flag/field into `InstallConfig` or just into `context` payload to specify execution mode. When calling from binary we can set it to log out.
When called as a library or in CI we can override it. 

At the moment its only one `msg="Login to the console with user: kubeadmin, password: QKopq-SbU8e-xxx-xxx" `

**Comment by abhinavdahiya** [comment]
The print commands are not part of the Cluster asset, but rather part of the list of wait-for steps.. so you can implement for your own wait-for.

/close
