### ISSUE TITLE
Is this repository used to install Openshift version 4 on RedHat 7?

### ISSUE THREAD

**Issue by Sofia-Gonzalez-Unlam** [openshift/installer#1887]
Good afternoon.
Please, your help. 
Is this repository used to install Openshift version 4 on RedHat 7?  

Many thanks.
Regards.

**Comment by abhinavdahiya** [comment]
OpenShift 4 is installed on Red Hat Linux Enterprise CoreOS. For more details checkout https://docs.openshift.com/container-platform/4.1/welcome/index.html

/close
