### ISSUE TITLE
Customize installation to have a cluster with minimum components

### ISSUE THREAD

**Issue by liqlin2015** [openshift/installer#1900]
# Version

```
4.1
```

# Platform (aws|libvirt|openstack): aws

# What happened?

I want to customize openshift installation to only have a cluster with minimum components. For example, disable monitoring, service-broker, router, imagestream, etc in the default installation. 

# What you expected to happen?

See above.

**Comment by abhinavdahiya** [comment]
The installer doesn't pick what's installed, the release image drives that decision. You could create your own release image... But that's not going to be OpenShift anymore.

All these components make up OpenShift and there are no plans to support non-OpenShift installations

/close
