### ISSUE TITLE
RedHat 7 - OpenShift 4: Help with "hack/build.sh"

### ISSUE THREAD

**Issue by Sofia-Gonzalez-Unlam** [openshift/installer#1902]
Please, your help to solve this issue. 
When following this step of the repository: 

"Clone this repository to src/github.com/openshift/installer in your GOPATH. Then build the openshift-install binary with: hack/build.sh "

This output appears by console: 

```console
root@sa1master_openshift hack]# ./build.sh+ minimum_go_version=1.10++ go version++ cut -d ' ' -f 3+ current_go_version=go1.12.6++ version 1.12.6++ IFS=.++ printf '%03d%03d%03d\n' 1 12 6++ unset IFS++ version 1.10++ IFS=.++ printf '%03d%03d%03d\n' 1 10++ unset IFS+ '[' 001012006 -lt 001010000 ']'+ LAUNCH_PATH=/root/src/github.com/openshift/installer/hack++ dirname ./build.sh+ cd ./..++ go list -e -f '{{.Dir}}' github.com/openshift/installer+ PACKAGE_PATH=+ test -z ''++ go env GOPATH+ echo 'build from your ${GOPATH} (/root/src/github.com/openshift/installer/hack is not in /root/src/github.com/openshift)'build from your ${GOPATH} (/root/src/github.com/openshift/installer/hack is not in /root/src/github.com/openshift)+ exit 1[root@sa1master_openshift hack]#
```

Thank you very much for your contributions. 
Regards.

**Comment by staebler** [comment]
You should run `./hack/build.sh` from `/root/src/github.com/openshift/installer` instead of running `./build.sh` from `/root/src/github.com/openshift/installer/hack`

**Comment by Sofia-Gonzalez-Unlam** [comment]
Unfortunately, the problem persists.
After running the command ./hack/build.sh  from  /root/src/github.com/openshift/installer ; the following output is displayed: 

[root@sa1master_openshift installer]# ./hack/build.sh
+ minimum_go_version=1.10
++ go version
++ cut -d ' ' -f 3
+ current_go_version=go1.12.6
++ version 1.12.6
++ IFS=.
++ printf '%03d%03d%03d\n' 1 12 6
++ unset IFS
++ version 1.10
++ IFS=.
++ printf '%03d%03d%03d\n' 1 10
++ unset IFS
+ '[' 001012006 -lt 001010000 ']'
+ LAUNCH_PATH=/root/src/github.com/openshift/installer
++ dirname ./hack/build.sh
+ cd ./hack/..
++ go list -e -f '{{.Dir}}' github.com/openshift/installer
+ PACKAGE_PATH=
+ test -z ''
++ go env GOPATH
+ echo 'build from your ${GOPATH} (/root/src/github.com/openshift/installer is not in /root/src/github.com/openshift)'
build from your ${GOPATH} (/root/src/github.com/openshift/installer is not in /root/src/github.com/openshift)
+ exit 1

------------------------------
Thank you all for your help.
Regards.

**Comment by staebler** [comment]
Is ${GOPATH} set to `/root/src/github.com/openshift/installer`?
It should be set to `/root/src`.

**Comment by Sofia-Gonzalez-Unlam** [comment]
Perfect! Now, its works correctly. 
Thank you very much indeed.
