### ISSUE TITLE
in build.sh, the directory check is not quite working

### ISSUE THREAD

**Issue by rob-baron** [openshift/installer#1908]
Attempt 1:

    $ ./hack/build.sh 
    + minimum_go_version=1.10
    ++ go version
    ++ cut -d ' ' -f 3
    + current_go_version=go1.11.2
    ++ version 1.11.2
    ++ IFS=.
    ++ printf '%03d%03d%03d\n' 1 11 2
    ++ unset IFS
    ++ version 1.10
    ++ IFS=.
    ++ printf '%03d%03d%03d\n' 1 10
    ++ unset IFS
    + '[' 001011002 -lt 001010000 ']'
    + LAUNCH_PATH='/Users/Rob 1/Programming/go/installer'
    ++ dirname ./hack/build.sh
    + cd ./hack/..
    ++ go list -e -f '{{.Dir}}' github.com/openshift/installer
    + PACKAGE_PATH=
    + test -z '' 
    ++ go env GOPATH
    + echo 'build from your ${GOPATH} (/Users/Rob 1/Programming/go/installer is not in /Users/Rob 1/Programming/go)'
    build from your ${GOPATH} (/Users/Rob 1/Programming/go/installer is not in /Users/Rob 1/Programming/go)
    + exit 1

Attempt 2:

    $ installer/hack/build.sh 
    + minimum_go_version=1.10 
    ++ go version
    ++ cut -d ' ' -f 3
    + current_go_version=go1.11.2
    ++ version 1.11.2
    ++ IFS=.
    ++ printf '%03d%03d%03d\n' 1 11 2
    ++ unset IFS
    ++ version 1.10
    ++ IFS=.
    ++ printf '%03d%03d%03d\n' 1 10
    ++ unset IFS
    + '[' 001011002 -lt 001010000 ']'
    + LAUNCH_PATH='/Users/Rob 1/Programming/go'
    ++ dirname installer/hack/build.sh
    + cd installer/hack/..
    ++ go list -e -f '{{.Dir}}' github.com/openshift/installer
    + PACKAGE_PATH=
    + test -z ''
    ++ go env GOPATH
    + echo 'build from your ${GOPATH} (/Users/Rob 1/Programming/go is not in /Users/Rob   1/Programming/go)'
    build from your ${GOPATH} (/Users/Rob 1/Programming/go is not in /Users/Rob 1/Programming/go)
    + exit 1

The error message is bad.  In my case it should have mentioned that it needs to be in ${GOPATH}/github.com/openshift/installer and not in ${GOPATH}/installer

**Comment by sacharya** [comment]
I am getting the same error too:

`$ echo $GOPATH
/home/sa/gowork
$ pwd
/home/sa/gowork/src/github.com/openshift/installer
$ ./hack/build.sh
+ minimum_go_version=1.10
++ go version
++ cut -d ' ' -f 3
+ current_go_version=go1.11.5
++ version 1.11.5
++ IFS=.
++ printf '%03d%03d%03d\n' 1 11 5
++ unset IFS
++ version 1.10
++ IFS=.
++ printf '%03d%03d%03d\n' 1 10
++ unset IFS
+ '[' 001011005 -lt 001010000 ']'
+ LAUNCH_PATH=/home/sa/gowork/src/github.com/openshift/installer
++ dirname ./hack/build.sh
+ cd ./hack/..
++ go list -e -f '{{.Dir}}' github.com/openshift/installer
+ PACKAGE_PATH=
+ test -z ''
++ go env GOPATH
+ echo 'build from your ${GOPATH} (/home/sa/gowork/src/github.com/openshift/installer is not in /home/sa/gowork)'
build from your ${GOPATH} (/home/sa/gowork/src/github.com/openshift/installer is not in /home/sa/gowork)
+ exit 1
`

**Comment by jichenjc** [comment]
+1, I suffered this as well~

**Comment by rgov** [comment]
I cloned the repository to `$HOME/go/github.com/openshift/installer/` (where `go env GOPATH` is `$HOME/go`) and still get this error message. What exactly does it want?

In my opinion, a pull request related to this (such as #1911) also needs to update the README to clarify what the user is expected to do.

**Comment by jichenjc** [comment]
I didn't get this message if the repo is `$HOME/go/src/github.com/openshift/installer/`

it's because go library check so if you don't put code in this exact folder later on compile will complain 
IMO it's just the error message is that clear.. and put into README is overkill .. since this is go standard for code repo?

**Comment by rgov** [comment]
Right, that is the correct directory, with `src/`... your pull request does not include that. (The output of `go env GOPATH` on my machine does not include `src/`.)

> and put into README is overkill .. since this is go standard for code repo?

There is already [this README](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md) which explicitly tells you to clone the repo and run the `build.sh` script. These instructions are linked from elsewhere. A user following these instructions would not know that this is a Go project, or the correct way to set up a Go project's directory structure.

**Comment by eperry** [comment]
Yah I ran in to this too. Did not realize this is a GO Project and don't understand why the shell script just does not set the GOPATH to its own directory structure and build there.

**Comment by th3penguinwhisperer** [comment]
Apparently still not fixed. Ran into the same issue.

**Comment by Alekson87** [comment]
> Attempt 1:
> 
> ```
> $ ./hack/build.sh 
> + minimum_go_version=1.10
> ++ go version
> ++ cut -d ' ' -f 3
> + current_go_version=go1.11.2
> ++ version 1.11.2
> ++ IFS=.
> ++ printf '%03d%03d%03d\n' 1 11 2
> ++ unset IFS
> ++ version 1.10
> ++ IFS=.
> ++ printf '%03d%03d%03d\n' 1 10
> ++ unset IFS
> + '[' 001011002 -lt 001010000 ']'
> + LAUNCH_PATH='/Users/Rob 1/Programming/go/installer'
> ++ dirname ./hack/build.sh
> + cd ./hack/..
> ++ go list -e -f '{{.Dir}}' github.com/openshift/installer
> + PACKAGE_PATH=
> + test -z '' 
> ++ go env GOPATH
> + echo 'build from your ${GOPATH} (/Users/Rob 1/Programming/go/installer is not in /Users/Rob 1/Programming/go)'
> build from your ${GOPATH} (/Users/Rob 1/Programming/go/installer is not in /Users/Rob 1/Programming/go)
> + exit 1
> ```
> 
> Attempt 2:
> 
> ```
> $ installer/hack/build.sh 
> + minimum_go_version=1.10 
> ++ go version
> ++ cut -d ' ' -f 3
> + current_go_version=go1.11.2
> ++ version 1.11.2
> ++ IFS=.
> ++ printf '%03d%03d%03d\n' 1 11 2
> ++ unset IFS
> ++ version 1.10
> ++ IFS=.
> ++ printf '%03d%03d%03d\n' 1 10
> ++ unset IFS
> + '[' 001011002 -lt 001010000 ']'
> + LAUNCH_PATH='/Users/Rob 1/Programming/go'
> ++ dirname installer/hack/build.sh
> + cd installer/hack/..
> ++ go list -e -f '{{.Dir}}' github.com/openshift/installer
> + PACKAGE_PATH=
> + test -z ''
> ++ go env GOPATH
> + echo 'build from your ${GOPATH} (/Users/Rob 1/Programming/go is not in /Users/Rob   1/Programming/go)'
> build from your ${GOPATH} (/Users/Rob 1/Programming/go is not in /Users/Rob 1/Programming/go)
> + exit 1
> ```
> 
> The error message is bad. In my case it should have mentioned that it needs to be in ${GOPATH}/github.com/openshift/installer and not in ${GOPATH}/installer
