### ISSUE TITLE
libvirt: DEBUG Still waiting for the Kubernetes API....

### ISSUE THREAD

**Issue by tux1980** [openshift/installer#1909]
# Version
openshift-install unreleased-master-1194-g2241d21bc6509e6372c28ba29495f024001124cf-dirty
built from commit 2241d21bc6509e6372c28ba29495f024001124cf
release image registry.svc.ci.openshift.org/origin/release:v4.1

# Platform:
RHEL 7.6 with libvirt 5.0 / QEMU 2.12 / Go Verson 1.12 / dep version 0.5.3

# What happened?
After executing ./openshift-install --log-level=debug create cluster anything is apparently running smooth. The master gets deployed, DNS resolution is going to work. And all of a sudden I get the folllowing Error Message:

libvirt: DEBUG Still waiting for the Kubernetes API: Get https://api.okd.testing.tt:6443/version?timeout=32s: dial tcp IP_ADDRESS:6443: connect: connection refused 

This is going to happen on an on in the debug file for over 30 minutes until it stops. I've been trying to reach the master with curl -vvv ....  -- also without success. the Kubernetes API does not come up. 

# What you expected to happen?
I expect the openshift cluster setup to succeed the Installation.

# How to reproduce it (as minimally and precisely as possible)?
execute the installer: 
openshift-install --log-level=debug create cluster
Choose: libvirt
Domain: testing.tt
Clustername: okd
Paste the secret.
Go for it!

**Comment by zeenix** [comment]
> This is going to happen on an on in the debug file for over 30 minutes until it stops.

Just to clarify: what does "it stops" mean here. The installer gives up on the cluster creation you mean?

Did you follow the steps and troubleshooting instructions [here](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md)?

/priority important-soon

**Comment by tux1980** [comment]
Hi, yes, this is exact the document I've been working with - and I followed its instruction really step by stepp. It still throws out the error during the deployment.... I can ping both IP's from my libvirt host (master & bootstrap node).  But when I tried out "curl -vv 192.168.126.10:6443" it is been routed correctly but says constantly "Connection" refused... 

Hmmm.... Attached, maybe you could take a look at it, my .openshift_install.log 

[openshift_install_log.txt](https://github.com/openshift/installer/files/3340613/openshift_install_log.txt)

Wolfgang

**Comment by zeenix** [comment]
@tux1980 Thanks for the info and logs. This is strange. A bunch of these messages are normal:

```
DEBUG Still waiting for the Kubernetes API: Get https://api.pupu.openshift.testing:6443/version?timeout=32s: dial tcp 192.168.126.11:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.pupu.openshift.testing:6443/version?timeout=32s: dial tcp 192.168.126.10:6443: connect: connection refused 
```

but eventually API server is up and Cluster creation progresses forwards. Maybe for some reason it takes longer than usual for you. Can you check if waiting longer helps? `openshift-install wait-for install-complete`?

**Comment by tux1980** [comment]
I did it as you said - unfortunately it didn't succeed. After 30 Minutes the deployment had been failed with the following "last lines" in the log... 

Furthermore, I can't retrieve the logs (ssh -A .... or with scp) because even though I know the user is apparently "core" on the bootstrape node, I do not know the SSH password.  
-------------------------

LOG Excerpt:
time="2019-07-01T17:02:08+02:00" level=debug msg="Still waiting for the Kubernetes API: Get https://api.okd.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.10:6443: connect: connection refused"
time="2019-07-01T17:02:38+02:00" level=debug msg="Still waiting for the Kubernetes API: Get https://api.okd.tt.testing:6443/version?timeout=32s: dial tcp 192.168.126.10:6443: connect: connection refused"
time="2019-07-01T17:02:54+02:00" level=debug msg="Fetching \"Install Config\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="Loading \"Install Config\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="  Loading \"SSH Key\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="  Using \"SSH Key\" loaded from state file"
time="2019-07-01T17:02:54+02:00" level=debug msg="  Loading \"Base Domain\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="    Loading \"Platform\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="    Using \"Platform\" loaded from state file"
time="2019-07-01T17:02:54+02:00" level=debug msg="  Using \"Base Domain\" loaded from state file"
time="2019-07-01T17:02:54+02:00" level=debug msg="  Loading \"Cluster Name\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="    Loading \"Base Domain\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="  Using \"Cluster Name\" loaded from state file"
time="2019-07-01T17:02:54+02:00" level=debug msg="  Loading \"Pull Secret\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="  Using \"Pull Secret\" loaded from state file"
time="2019-07-01T17:02:54+02:00" level=debug msg="  Loading \"Platform\"..."
time="2019-07-01T17:02:54+02:00" level=debug msg="Using \"Install Config\" loaded from state file"
time="2019-07-01T17:02:54+02:00" level=debug msg="Reusing previously-fetched \"Install Config\""
time="2019-07-01T17:02:54+02:00" level=info msg="Make sure ssh-agent is running, env SSH_AUTH_SOCK is set to the ssh-agent's UNIX socket and your private key is added to the agent."
time="2019-07-01T17:02:54+02:00" level=info msg="Use the following commands to gather logs from the cluster"
time="2019-07-01T17:02:54+02:00" level=info msg="ssh -A core@okd-k5mn2-bootstrap '/usr/local/bin/installer-gather.sh okd-k5mn2-master-0'"
time="2019-07-01T17:02:54+02:00" level=info msg="scp core@okd-k5mn2-bootstrap:~/log-bundle.tar.gz ."
time="2019-07-01T17:02:54+02:00" level=fatal msg="waiting for Kubernetes API: context deadline exceeded"

**Comment by tux1980** [comment]
@zeenix Now I was able to login into the bootstrap node. With journalctl I investigated the bootkube.service. It is always the same error message: 

Jul 01 16:53:37 okd-gt8xd-bootstrap bootkube.sh[28408]: unable to pull registry.svc.ci.openshift.org/origin/4.1-2019-05-13-204940@sha256:2052e13f8a6e1ce52f9f719b05e0cf4f694079295bd0e6e4aa95c37eab4c0192: unable to pull image: Error determining manifest MIME type for docker://registry.svc.ci.openshift.org/origin/4.1-2019-05-13-204940@sha256:2052e13f8a6e1ce52f9f719b05e0cf4f694079295bd0e6e4aa95c37eab4c0192: Error reading manifest sha256:2052e13f8a6e1ce52f9f719b05e0cf4f694079295bd0e6e4aa95c37eab4c0192 in registry.svc.ci.openshift.org/origin/4.1-2019-05-13-204940: manifest unknown: manifest unknown

**Comment by tux1980** [comment]
Hi, it is solved.... I switched the installer version against the actual "standard" version.
release image registry.svc.ci.openshift.org/origin/release:4.2 

Now the API service is running just fine. 
Jul 01 17:16:29 okd-dz7vc-bootstrap bootkube.sh[1361]: bootkube.service complete

Thanks!

**Comment by zeenix** [comment]
@tux1980 You mean you were using a custom image? That'd have been a useful piece of info. :)

**Comment by zeenix** [comment]
@tux1980 I see that you did mention which image you're using but it wasn't clear to me that it's a custom image you explicitly tell installer to use.

**Comment by oswee** [comment]
@tux1980 Would be great to see how that was done. :) Have a similar issue, but no luck in solving that.

**Comment by qzhang90** [comment]
@tux1980 What is the IP address of `api.okd.tt.testing` in your setup? Is it the IP of the master or bootstrap node?
