### ISSUE TITLE
[RFE] Flat vendor directory

### ISSUE THREAD

**Issue by mjudeikis** [openshift/installer#1914]
When revendoring `installer` project we are running into the issue with a double vendor directory for `terraform` and main project dependencies. 

`https://github.com/openshift/installer/tree/master/pkg/terraform/exec/vendor` 
`https://github.com/openshift/installer/tree/master/vendor`
 
When vendoring in `installer` its gets either truncated or squashed by `dep`. 

It would be good somehow align `vendor` directories so we would not have this hack and have a flat vendor for the project.

**Comment by abhinavdahiya** [comment]
Should be fixed with https://github.com/openshift/installer/pull/2745
