### ISSUE TITLE
[openstack] 2+ images named 'rhcos' no error reported

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1921]
# Version

```console
$ openshift-install version
<your output here>
```
[root@jichen-openstack-1 installer]# bin/openshift-install version
bin/openshift-install unreleased-master-1200-gf4ddfdf9d9b8ae7c99298bcbfa49ba3e3ad317e1-dirty
built from commit f4ddfdf9d9b8ae7c99298bcbfa49ba3e3ad317e1
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform:

openstack
# What happened?
have following images to do test (2 rhcos) but no error reported when creating cluster
```
+--------------------------------------+--------+--------+
| ID                                   | Name   | Status |
+--------------------------------------+--------+--------+
| d890d41e-6f26-460d-a348-fc4725ddffa4 | cirros | active |
| 1ee4f2fd-aa2f-4e7b-a259-a28b74ab9c73 | rhcos  | active |
| 3cb37b02-6ff8-4366-ad01-34993b15639d | rhcos  | active |
+--------------------------------------+--------+--------+
```
Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
Apparently glance is perfectly fine with allowing two images with the same name, it will use the id to differentiate them. Now should we really fail the install if there are two images named `rhcos` in glance? I'm not sure about this as it would fail in perfectly valid environments. We could perhaps print a warning?

**Comment by jichenjc** [comment]
I don't know which is good, I would think we need ask which id to use if more rhcos exist and ask user to select a preferred one...

**Comment by mandre** [comment]
Yeah I suppose it's possible to ask in the installer wizard for which image ID to use in case there are several images with the `rhcos` name.

**Comment by Fedosin** [comment]
Fixed: https://github.com/openshift/installer/pull/2492
