### ISSUE TITLE
[openstack] support boot from volume 

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1922]
# Version

```console
$ openshift-install version
<your output here>
```
[root@jichen-openstack-1 installer]# bin/openshift-install version
bin/openshift-install unreleased-master-1200-gf4ddfdf9d9b8ae7c99298bcbfa49ba3e3ad317e1-dirty
built from commit f4ddfdf9d9b8ae7c99298bcbfa49ba3e3ad317e1
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform:

openstack

# What happened?

see following code at 
https://github.com/openshift/installer/blob/master/pkg/asset/machines/openstack
/machines.go#L89
RootVolume is commented .....

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
Boot from Volume was implemented in #2394.
