### ISSUE TITLE
[openstack][question] where to find latest coreos image 

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1924]
# Version

```console
$ openshift-install version
<your output here>
```

# Platform:

# What happened?

This actually comes from Josphat Mutai but we seems suffered similar issue, 
```
$ export build="420.8.20190611.0"
$ wget  https://releases-rhcos.svc.ci.openshift.org/storage/releases/ootpa/$build/rhcos-$build-openstack.qcow2

use above image to be base coreOS then during boot will have something like:

Booting from Hard disk...
Boot failed: not a bootable disk

No bootable device
```

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by jichenjc** [comment]
from our test , seems running this on baremetal hardware is fine while on virtual server (which becomes 2nd level nested virtualization) seems has problem, can someone help to confirm?

**Comment by mandre** [comment]
Could you give it a try with https://raw.githubusercontent.com/shiftstack-dev-tools/shiftstack-ci/master/refresh_rhcos.sh ? This will pull the latest image as defined in https://github.com/openshift/installer/blob/master/data/data/rhcos.json

**Comment by abhinavdahiya** [comment]
The location to get openstack bootimages must be https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/latest/

**Comment by jmutai** [comment]
> The location to get openstack bootimages must be https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/latest/

There is no OpenStack template in the link. These are files for installing on Bare metal and vsphere.

**Comment by jmutai** [comment]
> Could you give it a try with https://raw.githubusercontent.com/shiftstack-dev-tools/shiftstack-ci/master/refresh_rhcos.sh ? This will pull the latest image as defined in https://github.com/openshift/installer/blob/master/data/data/rhcos.json

Let me try this.

**Comment by cgwalters** [comment]
See also https://github.com/openshift/installer/issues/1399

**Comment by jichenjc** [comment]
@cgwalters @mandre thanks for the info, I confirmed I tried the link provided by @mandre ,exactly same way

however, the question becomes whether the image allow nested virtualization work
as my colleagues use baremetal to do test everything is fine but I am using 2nd level (the bootstrap,master,api servers are hosted on a VM by another openstack), this will fail,

only want to confirm this so that won't try on 2nd env anymore...

**Comment by hamzy** [comment]
+ LOCAL_IMAGE_FILE=rhcos-latest.qcow2
+ RHCOS_VERSIONS_FILE=rhcos.json
+ curl --silent -o rhcos.json https://raw.githubusercontent.com/openshift/installer/master/data/data/rhcos.json
++ jq --raw-output '.baseURI + .images.openstack.path' rhcos.json
+ IMAGE_URL=https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.2/420.8.20190708.2/rhcos-420.8.20190708.2-openstack.qcow2
++ jq --raw-output '.images.openstack."uncompressed-sha256"' rhcos.json
error: syntax error, unexpected QQSTRING_START, expecting IDENT
.images.openstack."uncompressed-sha256"
                  ^
1 compile error
+ IMAGE_SHA=

Also, how do we get access to it?

(overcloud) [stack@osp017 ~]$ curl --remote-name https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.2/420.8.20190708.2/rhcos-420.8.20190708.2-openstack.qcow2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   161  100   161    0     0    215      0 --:--:-- --:--:-- --:--:--   216
(overcloud) [stack@osp017 ~]$ file rhcos-420.8.20190708.2-openstack.qcow2
rhcos-420.8.20190708.2-openstack.qcow2: HTML document, ASCII text, with CRLF line terminators
(overcloud) [stack@osp017 ~]$ cat rhcos-420.8.20190708.2-openstack.qcow2
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>

**Comment by jichenjc** [comment]
I haven't try recently, at least after got info here, I am able to download images :)

**Comment by hamzy** [comment]
@jichenjc Could you please try it again?  Or someone else?

**Comment by waynedovey** [comment]
+1 I am also having issues with these latest images. Have they been tested on OpenStack? 

I see the same error

Booting from Hard disk...
Boot failed: not a bootable disk

No bootable device

using both raw and qcow2 format

**Comment by mandre** [comment]
/close

RHCOS images to use on OpenStack platform are located in https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/.

Closing the issue as we have it documented at https://github.com/openshift/installer/tree/master/docs/user/openstack#red-hat-enterprise-linux-coreos-rhcos.

In the next version, we'll have the installer download the required image automatically and upload them to glance, this will all be transparent for the user.

**Comment by ktibi** [comment]
Hi,
I try to deploy this image : rhcos-42.80.20190828.2-openstack.qcow2

But fail on Openstack Rocky : Same issue, not a bootable device.

**Comment by mandre** [comment]
> Hi,
> I try to deploy this image : rhcos-42.80.20190828.2-openstack.qcow2
> 
> But fail on Openstack Rocky : Same issue, not a bootable device.
> 
> ping @mandre

It may be that the image was pushed to glance while being compressed.
Try downloading the image with `curl --compressed -J -L -O <url of OpenStack QCOW2>`

We've just updated the docs to make it clearer, see https://github.com/openshift/installer/pull/2416.

**Comment by X-dark** [comment]
This indeed works better. Thanks!
