### ISSUE TITLE
[Azure] Worker nodes won't join the cluster

### ISSUE THREAD

**Issue by ams0** [openshift/installer#1942]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1088-g273cece0ea05bd55ac7d03c5c3022255ea4fd5f7-dirty
built from commit 273cece0ea05bd55ac7d03c5c3022255ea4fd5f7
release image quay.io/openshift-release-dev/ocp-release@sha256:8d51bc2da4b9873053b2b3f0737c912ba1e0623ff4b303f1a8ec3618ba3354ff```
```

# Platform:
Client: Mac OS X Catalina beta
Cloud: Azure (West Europe)

# What happened?

Workes nodes are created, I can SSH into them, kubelet is running, but they don't join the cluster. This obviously makes the whole provisioning fail (I thought it was a problem with a CRD until I look at the nodes.

# What you expected to happen?

Nodes are up and joined with the masters.

# How to reproduce it (as minimally and precisely as possible)?

Deploy a cluster in azure

```console
$> oc get nodes
NAME                    STATUS   ROLES    AGE   VERSION
shift4-p8t5n-master-0   Ready    master   23h   v1.13.4+cb455d664
shift4-p8t5n-master-1   Ready    master   23h   v1.13.4+cb455d664
shift4-p8t5n-master-2   Ready    master   23h   v1.13.4+cb455d664
```

# Anything else we need to know?

DNS resolution from the worker nodes to the API works, I can curl the API. I found this error in the kubelet logs:

```
Jul 05 07:57:35 shift4-p8t5n-worker-5gscv hyperkube[17117]: E0705 07:57:35.457877   17117 bootstrap.go:238] Unable to read existing bootstrap client config: invalid configuration: [unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory, unable to read client-key /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory]
```

Indeed `/var/lib/kubelet/pki/` does not exist.

# References

It is not related to other issues.

**Comment by abhinavdahiya** [comment]
Are the CSRs approved for the worker nodes.
```
oc get csrs
```

If the CSRs are not approved please open an issue or BZ with https://github.com/openshift/cluster-machine-approver/issues

/close
