### ISSUE TITLE
Adding network interface to node leads to "NotReady" - vsphere

### ISSUE THREAD

**Issue by neuroserve** [openshift/installer#1943]
# Version

```console
$ openshift-install version
./openshift-install v4.1.4-201906271212-dirty
built from commit bf47826c077d16798c556b1bd143a5bbfac14271
release image quay.io/openshift-release-dev/ocp-release@sha256:a6c177eb007d20bb00bfd8f829e99bd40137167480112bd5ae1c25e40a4a163a
```

# Platform:
```Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        13007421
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.2
Product ID:   vpx
UUID:         1d884c6e-a1ac-4daf-9e25-b197e7f6bd91
```

# What happened?
After setting up the cluster, I added another network interface to one of my worker nodes in order to satisfy "4.1.14.1.1. Configuring registry storage for VMware vSphere". The additional network interface would allow the node to access an NFS-share/volume on one of our NFS-servers.

The additional interface is initialized and gets an ip address via dhcp. But the node remains in "NotReady" status after that:
```[root@console (vm8529214):~]$ oc get nodes
NAME      STATUS     ROLES    AGE     VERSION
master1   Ready      master   7d22h   v1.13.4+c9e4f28ff
master2   Ready      master   7d22h   v1.13.4+c9e4f28ff
master3   Ready      master   7d22h   v1.13.4+c9e4f28ff
worker1   Ready      worker   7d22h   v1.13.4+c9e4f28ff
worker2   NotReady   worker   7d22h   v1.13.4+c9e4f28ff
worker3   Ready      worker   7d19h   v1.13.4+c9e4f28ff
worker4   Ready      worker   7d19h   v1.13.4+c9e4f28ff
```

# What you expected to happen?

I'd thought, it would be possible to add another network interface to a node and enable NFS-access by doing that. If the node remains "NotReady", there has to be another solution.

# How to reproduce it (as minimally and precisely as possible)?
I've just added another network adapter via the vsphere gui and rebooted the VM. Console output shows, that both interfaces are detected and brought up and get the designated IP addresses.

# Anything else we need to know?

I'd be interested if this is the right way to add additional network interfaces to RHCOS nodes or if I have to manipulate the ignition files (e. g. like here https://coreos.com/os/docs/latest/network-config-with-networkd.html - if that is valid vor RHCOS, too).

I'd appreciate a hint for the "correct" solution for RHCOS in order to prevent to much manual work or gui clicking.

**Comment by DanyC97** [comment]
@neuroserve the right way to add a new interface is via NM and not networkd - in RHCOS/ FCOS NM is managing the network (yes i know the Ignition 2.2 spec doesn't mention it nor the v4 docs)

See an example [here](https://github.com/openshift/installer/blob/master/upi/vsphere/machine/ignition.tf#L28-L39)

**Comment by abhinavdahiya** [comment]
day 2 configuration of the hosts is better placed in machine-config-operator github issues (https://github.com/openshift/machine-config-operator/issues) or Bugzilla for `Machine Config Operator` component 

/close
