### ISSUE TITLE
[gcp] handle destroying additional artifacts

### ISSUE THREAD

**Issue by csrwng** [openshift/installer#1954]
With https://github.com/openshift/installer/pull/1950, we are introducing an uninstaller for GCP. This issue is to keep track of remaining items that need to be handled by the uninstaller:

* Disks created by the GCP CSI driver (ideally need a way to have them labeled)
* Internal/External Load Balancers in shared mode created by the Kube cloud controller. 
  For these, we need to generate an 8-char ingress-UID that we store in metadata and in place in the cluster in a ConfigMap named kube-system/ingress-uid. If we know the clusterid, then we can search for the shared resources specifically by name and delete them.

Shared mode for load balancers is a per-service feature that allows sharing a single GCP backend service for multiple k8s Service resources. Introduced with this PR: https://github.com/kubernetes/kubernetes/pull/47459
it is enabled by an annotation on the Service resource. 
In shared mode, the following resources need to be cleaned up:
- Backend service (https://github.com/kubernetes/kubernetes/blob/7936da50c68f42236d952378a37ce4407ab192ed/pkg/cloudprovider/providers/gce/gce_loadbalancer_naming.go#L60)
- Health check (https://github.com/kubernetes/kubernetes/blob/7936da50c68f42236d952378a37ce4407ab192ed/pkg/cloudprovider/providers/gce/gce_loadbalancer_naming.go#L67)
- Health check firewall (https://github.com/kubernetes/kubernetes/blob/7936da50c68f42236d952378a37ce4407ab192ed/pkg/cloudprovider/providers/gce/gce_loadbalancer_naming.go#L79)
- Nodes health check (https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/gce/gce_loadbalancer_naming.go#L101)

**Comment by abhinavdahiya** [comment]
> Internal/External Load Balancers in shared mode created by the Kube cloud controller.

Can you expand on what's shared and non-shared mode for k8s cloud-provide on GCP. Is this a service level feature, or a cluster level feature...

> For these, we need to generate an 8-char ingress-UID that we store in metadata and in place in the cluster in a ConfigMap named kube-system/ingress-uid. If we know the clusterid, then we can search for the shared resources specifically by name and delete them.

will the use of the configmap mentioned depend on if shared or non-shared feature is turn-on

on bootstrap host as we have no way to create objects after api is up but bootstrap-kube-controller-manger is running, will this create a race between the installer trying to create the configmap and bootstrap-kube-controller-manager trying to create the configmap.

**Comment by csrwng** [comment]
@abhinavdahiya added more information about shared mode above.

The configmap will help us identify resources created by the cloud controller regardless of shared/non-shared mode of the services. 

I think it should be ok to update the configmap after the apiserver is up, as the GCE cloud controller continually watches for changes to it and updates its variables based on its value:
https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/gce/gce_clusterid.go#L69-L117

**Comment by abhinavdahiya** [comment]
I think I was not clear, the installer can only `CREATE` objects not `apply` objects to the cluster due to the limitation of the cluster-bootstrap, and hence the race of who creates the configmap first.

**Comment by abhinavdahiya** [comment]
/close

I think this is complete.
