### ISSUE TITLE
[openstack] image-registry panic: Swift authentication failed: Authorization Failed

### ISSUE THREAD

**Issue by bjhuangr** [openshift/installer#1962]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1261-g81be1e5192468568a17c3c6a061a8d9cc9ce6624
built from commit 81be1e5192468568a17c3c6a061a8d9cc9ce6624
release image registry.svc.ci.openshift.org/origin/release:4.2

```

# Platform:

openstack

# What happened?
All cluster operators working, except image-registry:
oc get clusteroperators
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.2.0-0.okd-2019-07-10-055119   True        False         False      161m
cloud-credential                           4.2.0-0.okd-2019-07-10-055119   True        False         False      3h3m
cluster-autoscaler                         4.2.0-0.okd-2019-07-10-055119   True        False         False      166m
console                                    4.2.0-0.okd-2019-07-10-055119   True        False         False      164m
dns                                        4.2.0-0.okd-2019-07-10-055119   True        False         False      179m
image-registry                                                             False       True          False      175m
ingress                                    4.2.0-0.okd-2019-07-10-055119   True        False         False      167m
kube-apiserver                             4.2.0-0.okd-2019-07-10-055119   True        False         False      179m
...

oc -n openshift-image-registry get pods
NAME                                               READY   STATUS             RESTARTS   AGE
cluster-image-registry-operator-599d645d5c-dxb5d   1/1     Running            0          176m
image-registry-5d68f876bb-bsxjc                    0/1     CrashLoopBackOff   37         176m
image-registry-699b778879-gfvhh                    0/1     CrashLoopBackOff   37         176m
node-ca-9gh4r                                      1/1     Running            0          176m
node-ca-bw7gb                                      1/1     Running            0          176m
node-ca-d2kzm                                      1/1     Running            0          169m
node-ca-ts289                                      1/1     Running            0          176m

oc -n openshift-image-registry logs image-registry-5d68f876bb-bsxjc
time="2019-07-10T09:55:51.251456841Z" level=info msg="start registry" distribution_version=v2.6.0+unknown go.version=go1.11.10 openshift_version=v3.11.0+dbb629d-114-dirty
time="2019-07-10T09:55:51.252221453Z" level=info msg="caching project quota objects with TTL 1m0s" go.version=go1.11.10
panic: Swift authentication failed: Authorization Failed

goroutine 1 [running]:
github.com/openshift/image-registry/vendor/github.com/docker/distribution/registry/handlers.NewApp(0x19786e0, 0xc000042038, 0xc000553180, 0xc0002b4f00)
	/go/src/github.com/openshift/image-registry/vendor/github.com/docker/distribution/registry/handlers/app.go:127 +0x335a
github.com/openshift/image-registry/pkg/dockerregistry/server/supermiddleware.NewApp(0x19786e0, 0xc000042038, 0xc000553180, 0x197ea20, 0xc00037d0e0, 0x19809e0)
	/go/src/github.com/openshift/image-registry/pkg/dockerregistry/server/supermiddleware/app.go:96 +0x85
github.com/openshift/image-registry/pkg/dockerregistry/server.NewApp(0x19786e0, 0xc000042038, 0x195eec0, 0xc00014c240, 0xc000553180, 0xc0004125a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/image-registry/pkg/dockerregistry/server/app.go:138 +0x287
github.com/openshift/image-registry/pkg/cmd/dockerregistry.NewServer(0x19786e0, 0xc000042038, 0xc000553180, 0xc0004125a0, 0x0, 0x0, 0x19982a0)
	/go/src/github.com/openshift/image-registry/pkg/cmd/dockerregistry/dockerregistry.go:187 +0x190
github.com/openshift/image-registry/pkg/cmd/dockerregistry.Execute(0x195b760, 0xc00014c010)
	/go/src/github.com/openshift/image-registry/pkg/cmd/dockerregistry/dockerregistry.go:162 +0x96a
main.main()
	/go/src/github.com/openshift/image-registry/cmd/dockerregistry/main.go:93 +0x3f6

# What you expected to happen?

image-registry available

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshfit-install create cluster
```

# Anything else we need to know?

# References

**Comment by jmutai** [comment]
Hi,

Which RHCOS OpenStack image version are you using?. I couldn't get one working.

**Comment by bjhuangr** [comment]
> Hi,
> 
> Which RHCOS OpenStack image version are you using?. I couldn't get one working.

It's rhcos-420.8.20190708.2-openstack.qcow2 .
You can find the url in: https://github.com/openshift/installer/blob/master/data/data/rhcos.json

**Comment by akrzos** [comment]
I am also hitting this issue.

**Comment by Fedosin** [comment]
https://github.com/openshift/cluster-image-registry-operator/pull/326 should fix that
