### ISSUE TITLE
[rfe] ignition config for .pem for a TrustedUserCAKeys configuration

### ISSUE THREAD

**Issue by ckyriakidou** [openshift/installer#1963]
# Version

```console
$ openshift-install version 

./openshift-install unreleased-master-1237-g22064445fd8a49824d77230b397cd49c2509c715
built from commit 22064445fd8a49824d77230b397cd49c2509c715
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

ALL

# What happened?

The current install config documentation talks about ssh key as a parameter to configure nodes with. This makes the ability to rotate and revoke keys cumbersome and a potential security risk.

# What you expected to happen?

However, it would be much more secure to be able to rotate keys and certificates for a cluster. This would be possible by providing a "TrustedUserCAKeys" key value pair for the installer (optional - similar to the sshKey one) that would create a file under /etc/ssh/<publickeys.pem> and a parameter in the `/etc/sshdsshd_config` that points to that location.

# Anything else we need to know?

This is on behalf of a customer investigating OCP on AWS and Azure.

**Comment by abhinavdahiya** [comment]
1. ssh key is optional. only useful if you want to debug bootstrapping failures or control-plane down scenarios.
2. the ssh key can be revoked, updated from the cluster using machine-configuration https://github.com/openshift/machine-config-operator/blob/master/docs/Update-SSHKeys.md
3. You can use machine-configuration to created your own setup, and machine-config-operator will be the best place to open requests for documenting such setups.

/close
