### ISSUE TITLE
Failed to open "/home/user/libvirt/images/openshift-pnjsw-bootstrap.ing" Permission denied

### ISSUE THREAD

**Issue by oswee** [openshift/installer#1973]
Leaving this issue just for record while trying to solve it. Will close it if will find it to be irrelevant there.
My intention is to try set up OpenShift 4 on my Fedora 30 Workstation (12 cores, 64 ram) to learn it. I want it to be fully functional and exposed to public network so i can learn CI/CD workflows.

Started by following [instructions from there](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md#install-and-enable-libvirt)

# Version
Not installed yet, but it is latest version at date of this issue.

# Platform:
libvirtd (libvirt) 5.1.0

# What happened?
```console
Error: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2019-07-11T10:29:47.947197Z qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/home/user/libvirt/images/openshift-pnjsw-master.ign: can't load /home/user/libvirt/images/openshift-pnjsw-master.ign: Failed to open file “/home/user/libvirt/images/openshift-pnjsw-master.ign”: Permission denied')
```
My default libvirt image directory is customized to appear on different partition. (SSD RAID 10).
When i change it to default `/var/lib/libvirt/images` installation somehow proceeds, but stuck at 
```console
Waiting up to 30m0s for the Kubernetes API at https://api.openshift.domain.com:6443...
```
which is another thing and not relevant to this issue.
I think this access issue is somehow related to SELinux.

# What you expected to happen?

Not sure. Probably libvirt based cluster should be deployed.

# How to reproduce it (as minimally and precisely as possible)?

Not sure.
I defaulted libvirt network to default one.
Tried to `sudo usermod -a -G libvirt $(whoami)`, `newgrp libvirt`, `unix_sock_group = "libvirt"` etc... but result was the same.
That `openshift-pnjsw-master.ign` file appears to be created as `root:root` even if i do execute `bin/openshift-install create cluster` - with my default user.

Probably setup prerequisites instructions should be populated with networking related instructions: bridged/NAT? networks, domain registry requirements like required wildcards, A/CNAME records etc.
As well information about required user groups and libvirt storage settings.
And how to configure router. Which ports should be forwarder or does DMZ must be used.

**Comment by oswee** [comment]
Installation ended with error:
```console
failed to create SSH client: dial tcp: lookup openshift-pnjsw-bootstrap on 127.0.0.1:53: no such host
```
2 libvirt domains created and running
- openshift-pnjsw-bootstrap
- openshift-pnjsw-master-0

Looking now how to clean up system and start from scratch.

**Comment by chrisdoherty4** [comment]
This was closed without a solution? Was the root cause and solution ever found?

**Comment by tom-stockwell** [comment]
@chrisdoherty4 I had a similar issue. In my case it was an selinux issue. The following fixed it for me:
```sh
dir="/path/to/dir"
semanage fcontext -a -t virt_image_t "$dir(/.*)?"
restorecon -R -v "$dir"
```

Disabling or setting selinux mode to `permissive` would also fix the issue.

**Comment by manintheit** [comment]
virt-install \
    --sysinfo type=fwcfg,entry0.name=opt/com.coreos/config,entry0.file=${IGNITION_CONFIG} \
    ...
