### ISSUE TITLE
What ports should be forwarded in router?

### ISSUE THREAD

**Issue by oswee** [openshift/installer#1974]
Can't find a list of required ports to open/forward in my physical router (currently only 80; 443 are allowed for me).  For publicly accessible `libvirt` setup.
Or DMZ should be used?

**Comment by zeenix** [comment]
The `libvirt` platform is mainly intended for local-only setups for testing and development so documenting how to expose the cluster over the internet is not in the highest of priorities and hence this is not an issue we want to keep open. That said, it should be possible to expose the network through iptables/firewalld but i don't know the magic. If you find out how, you're more than welcome to contribute a PR that documents this information.

/close

**Comment by oswee** [comment]
Ok. Tnx. Trying to set up neat home lab. When will come up with something reasonable will try to contribute.
