### ISSUE TITLE
[openstack] FATAL Resource not found in destroy cluster

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#1985]
# Version

```console
$ openshift-install version
<your output here>
```
[root@jichen-openstack-1 installer]# bin/openshift-install version
bin/openshift-install unreleased-master-1297-g4f5f6a639e30bbe40422653200b9fb15666cc5dc-dirty
built from commit 4f5f6a639e30bbe40422653200b9fb15666cc5dc
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform:

openstack 
# What happened?
first destroy has some error , 2nd try succeed

[root@jichen-openstack-1 installer]# ./bin/openshift-install destroy cluster
FATAL Resource not found
[root@jichen-openstack-1 installer]# ./bin/openshift-install destroy cluster
[root@jichen-openstack-1 installer]#

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by jichenjc** [comment]
please note I tried this several times and each time got same result(create a cluster then destroy it )....

**Comment by mandre** [comment]
Also reported at https://bugzilla.redhat.com/show_bug.cgi?id=1746748.

**Comment by mandre** [comment]
/close

This should has been fixed with https://github.com/openshift/installer/pull/2322. Please re-open if you see it happening again.
