### ISSUE TITLE
Add cloud name to Infrastructure status

### ISSUE THREAD

**Issue by dmage** [openshift/installer#1986]
The installer provides the secret `openstack-credentials` with `clouds.yaml`, but this secret may contain configuration for multiple clouds. The name of the cloud is stored in the installer config, but the operators shouldn't use this config and should use the Infrastructure resource instead.

Can the cloud name be added to PlatformStatus?

**Comment by abhinavdahiya** [comment]
cc @trown 

Should be definitely possible...

**Comment by adambkaplan** [comment]
@abhinavdahiya @dmage looks like we already have a PR to add `PlatformStatus` for OpenStack to the API. Made a note there.

https://github.com/openshift/api/pull/374

**Comment by tomassedovic** [comment]
The `CloudName` field has been added to https://github.com/openshift/api/pull/374
