### ISSUE TITLE
baremetal: Consider an alternate way to specify which hosts should be masters

### ISSUE THREAD

**Issue by russellb** [openshift/installer#2003]
This is a follow-up from a review on PR #1873.  https://github.com/openshift/installer/pull/1873#discussion_r304057442

The current install-config for the experimental `baremetal` platform includes a `role` field on the bare metal hosts.  This is to be used to specify which of the defined bare metal hosts should be chosen for provisioning as control plane nodes.

We discussed some alternatives:

1. Instead of listing all hosts in the platform config, move them into the platform config under the `compute` and `controlPlane` sections.  That makes it explicit how each host should be provisioned.

2. Leave all of the bare metal host details in a single list, but remove the `role` field.  Instead, put a list of names in the `baremetal` config section under `compute` or `controlPlane`

This should be re-considered before taking the `baremetal` platform out of experimental and committing to an install-config format.

**Comment by stbenjam** [comment]
I should also note: in many cases, we probably don't care which hosts are used as master and workers. Ironic is able to decide for itself using the allocation mechanism, or just let the terraform config implicitly picks the hosts as workers or masters based on the order they were defined. We just only need to make sure we have enough hosts available.

**Comment by russellb** [comment]
It's possible that a deployment has different hardware for control plane hosts vs compute hosts, so we'll need a way to be explicit somehow

**Comment by hardys** [comment]
According to https://github.com/openshift-kni/baremetal-deploy/issues/75 we actually depend on order of the hosts list vs using the role to filter, so we should probably revive this to fix up the hosts interface, and ensure groups of machines can be correctly specified as masters/workers without hacks like depending on the list order (I don't actually see where in the code we're doing that atm..)
