### ISSUE TITLE
baremetal: Need additional validation on apiVIP and ingressVIP

### ISSUE THREAD

**Issue by russellb** [openshift/installer#2006]
Original issue from @stbenjam - https://github.com/openshift-metal3/kni-installer/issues/142

Currently we just validate that it's a valid IP, but we should check that it is also not part of the MachineCIDR / ClusterNetwork / Sevice Network

See: openshift/installer#1873 (comment)

**Comment by tomassedovic** [comment]
@bcrochet I've just implemented this for OpenStack:

https://github.com/openshift/installer/pull/1959/commits/ade37f550cc2b4f26f23d1705b6a34e020a0bd5f

**Comment by tomassedovic** [comment]
oh nevermind I didn't see you've added a commit already

**Comment by bcrochet** [comment]
> oh nevermind I didn't see you've added a commit already

I'm taking some of what you have too... :)

**Comment by bcrochet** [comment]
@russellb @stbenjam For clarification... The VIPs should be in MachineCIDR, but should not be in ClusterNetwork and Service Network. Correct?

**Comment by russellb** [comment]
> @russellb @stbenjam For clarification... The VIPs should be in MachineCIDR, but should not be in ClusterNetwork and Service Network. Correct?

sounds right

**Comment by bcrochet** [comment]
As noted in the patch that fixes this, the MachineCIDR is already checked for overlap of Cluster network and Service network. So, as long as VIP is in MachineCIDR, it cannot be in the other two.
