### ISSUE TITLE
Include openshift-install binary with baremetal support in release image

### ISSUE THREAD

**Issue by markmc** [openshift/installer#2021]
**Background**

Release images currently contain two installer images:

1. `installer` - built from [images/installer](https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.ci), the standard openshift-install binary for Linux systems
2. `installer-artifacts` - built from [images/installer-artifacts](https://github.com/openshift/installer/blob/master/images/installer-artifacts/Dockerfile.rhel), an openshift-install binary for MacOS layered over the `installer` image

There are other images which are built per commit but not included in the release image - `libvirt-installer`, `upi-installer`, and `openstack-installer` - however apparently all of these are used for CI only

(The `installer` image is listed as an "always include" image in ['oc adm release new' code](https://github.com/openshift/origin/blob/3e9167b8052283c6b15e215616090773532a0979/staging/src/github.com/openshift/oc/pkg/cli/admin/release/new.go#L50-L53) - unclear how `installer-artifacts` gets included)

The [`baremetal` platform](https://github.com/openshift/installer/pull/1873) is only available in openshift-install if it is built with `TAGS="baremetal libvirt"`

Builds with `libvirt` support are dynamically linked as [there are no static builds of libvirt](https://www.redhat.com/archives/libvir-list/2013-April/msg00156.html)

The `baremetal` platform will be considered experimental in 4.2 and it will be listed in HiddenPlatformNames (currently openstack and vsphere are listed there)

**Request**

Since baremetal IPI support will not be available in the standard openshift-install binary, would it be acceptable to include a baremetal-installer image included in the 4.2 release image?

**Comment by russellb** [comment]
@eparis @crawford @smarterclayton would be interested in your feedback on this issue, thanks!

**Comment by smarterclayton** [comment]
I would prefer baremetal support in the binary but gated by tech preview than ship a second image.  I recall a discussion with Alex about having a tech preview env var guard, did that happen yet (and/or would that be a better solution here)?

**Comment by smarterclayton** [comment]
I’m also not sure I care too much if we just listed baremetal in the choices but said “tech preview” next to it - but a tech preview flag that controls more than just platforms would be useful in general (and if we did that, I could still see us wanting to list it as tech preview).

To an end user, we already have the concept of a feature flag or feature set, I don’t see a huge reason not to extend / carry that concept into other tools that we have rather than make up a novel way to have users do it.

**Comment by russellb** [comment]
Hiding it in the choices really isn't a big deal.  The bigger problem is that we can't build a single binary that also works for baremetal without imposing a new requirement to have libvirt installed.  To avoid creating new compatibility challenges for the main installer binary, an alternative is to just bundle a second installer build in the release image only used for baremetal.

**Comment by stbenjam** [comment]
FWIW, baremetal doesn't have a survey wizard, so it'll never be shown in the list of platforms to configure interactively.  IIRC hidden platforms only controls the ones with a survey, unless there's a different list other than the one in installconfig.go.

**Comment by russellb** [comment]
@abhinavdahiya FYI as well

**Comment by eparis** [comment]
I started looking at what it would take to write a wrapper library around all of the libvirt calls so we can use it via dlopen.  It ain't simple. I suggest we take this and add support for a dlopen version in the future...

(I'm going to keep poking it today though)

**Comment by abhinavdahiya** [comment]
imo

I think it's going to be easier if rhhi moved away from current libvirt.. I'm not sure why you guys choose it in first place when you guys already knew it couldn't be shipped to the customers... 

Anyways another option is rhhi use https://github.com/digitalocean/go-libvirt to build a libvirt terraform that doesn't need c bindings

**Comment by russellb** [comment]
> imo
> 
> I think it's going to be easier if rhhi moved away from current libvirt.. I'm not sure why you guys choose it in first place when you guys already knew it couldn't be shipped to the customers...
> 
> Anyways another option is rhhi use https://github.com/digitalocean/go-libvirt to build a libvirt terraform that doesn't need c bindings

happy to discuss alternatives for 4.3, but a major change like that isn't practical for 4.2

**Comment by eparis** [comment]
go-libvirt uses non-stable ABI which the libvirt team has EXPLICITLY said they can, and will, break in the future.

**Comment by russellb** [comment]
OK - so should we put up PRs to include a baremetal build of openshift-install for 4.2?  I don't really see any other practical way to resolve this in 4.2.

Support for dlopen sounds like a nice improvement to pursue for a future release.

**Comment by dhellmann** [comment]
Do we have a decision on what approach to take here?

**Comment by stbenjam** [comment]
@eparis @abhinavdahiya Anything I can do to help move this forward? I opened https://github.com/openshift/release/pull/4640 to build a baremetal-installer container like we do for other platforms, is that an acceptable approach for 4.2? How do we get it included with the release?

**Comment by eparis** [comment]
closing because we merged 4640.

**Comment by russellb** [comment]
> closing because we merged [openshift/release#4640](https://github.com/openshift/release/pull/4640)

does that actually include the installer build in the release image?  or just have it get built in CI?

**Comment by stbenjam** [comment]
> > closing because we merged [openshift/release#4640](https://github.com/openshift/release/pull/4640)
> 
> does that actually include the installer build in the release image? or just have it get built in CI?

My understanding is no, but I couldn’t find any more info other than the `oc` code @markmc linked to above. We could ask on ART slack.

**Comment by russellb** [comment]
OK, I'd like to reopen this until we confirm that there's a baremetal build of the installer in a release image.

**Comment by stbenjam** [comment]
I think this is what we need: https://github.com/openshift/oc/pull/52

**Comment by stbenjam** [comment]
From Slack regarding the oc solution:

```
That's probably the best approach for non-operators, until we get a label like we have for operators: https://github.com/openshift/machine-config-operator/blob/master/Dockerfile#L22
```

**Comment by stbenjam** [comment]
This is now complete, as the OC changes were merged in https://github.com/openshift/oc/issues/57

/close
