### ISSUE TITLE
DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource

### ISSUE THREAD

**Issue by Jabulisile** [openshift/installer#2026]
# Version

```console
./openshift-install v4.1.0-201905212232-dirty
built from commit 226288f70e78c0e2fbc077872cbcbb7e81a5d727
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6
```

# Platform:
AWS

# What happened?

Installing a cluster on AWS using CloudFormation templates failing at Initializing the bootstrap node stage. 

# What you expected to happen?

Initializing the bootstrap node on AWS with user-provisioned infrastructure to complete successfully.

# How to reproduce it (as minimally and precisely as possible)?

```console
openshift-install wait-for bootstrap-complete --dir=custom-install --log-level debug
```

# Anything else we need to know?

Have attached logs. Error is: FATAL waiting for Kubernetes API: context deadline exceeded

[log-bundle.tar.gz](https://github.com/openshift/installer/files/3403195/log-bundle.tar.gz)

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
```
Jul 17 15:09:40 ip-10-0-2-148 bootkube.sh[4738]: etcdctl failed. Retrying in 5 seconds...
Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: https://etcd-0.ocp4aws.rainforrest.standardbank.co.za:2379 is unhealthy: failed to connect: dial tcp 10.0.119.81:2379: connect: connection refused
Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: https://etcd-1.ocp4aws.rainforrest.standardbank.co.za:2379 is unhealthy: failed to connect: dial tcp 10.0.156.210:2379: connect: connection refused
Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: https://etcd-2.ocp4aws.rainforrest.standardbank.co.za:2379 is unhealthy: failed to connect: dial tcp 10.0.173.115:2379: connect: connection refused
Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: Error: unhealthy cluster
```

the etcd cluster is not running and the log couldn't capture the logs from master's.

Are the control-plane machines running.. if they are can you capture logs from 

```
journalctl -u kubelet -u crio
pods from crictl ps -a using crictl logs <id>
```

**Comment by Jabulisile** [comment]
> ```
> Jul 17 15:09:40 ip-10-0-2-148 bootkube.sh[4738]: etcdctl failed. Retrying in 5 seconds...
> Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: https://etcd-0.ocp4aws.rainforrest.standardbank.co.za:2379 is unhealthy: failed to connect: dial tcp 10.0.119.81:2379: connect: connection refused
> Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: https://etcd-1.ocp4aws.rainforrest.standardbank.co.za:2379 is unhealthy: failed to connect: dial tcp 10.0.156.210:2379: connect: connection refused
> Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: https://etcd-2.ocp4aws.rainforrest.standardbank.co.za:2379 is unhealthy: failed to connect: dial tcp 10.0.173.115:2379: connect: connection refused
> Jul 17 15:19:45 ip-10-0-2-148 bootkube.sh[4738]: Error: unhealthy cluster
> ```
> 
> the etcd cluster is not running and the log couldn't capture the logs from master's.
> 
> Are the control-plane machines running.. if they are can you capture logs from
> 
> ```
> journalctl -u kubelet -u crio
> pods from crictl ps -a using crictl logs <id>
> ```

Thanks Abhinav. The control-plane machines are up. Are you recommending this command be ran on control-plane  machines? I'm unable to log into them via the bootstrap host using my ssh key.

**Comment by Jabulisile** [comment]
> journalctl -u kubelet -u crio

Thanks Abhinav. Have gathered logs from one of the masters and attached below. No pods currently running on the masters:

> ssh -J core@xx.xx.xx.xx core@10.0.115.110 "sudo crictl ps -a"
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID

$

**Comment by abhinavdahiya** [comment]
```
Jul 17 21:35:33 ip-10-0-115-110 hyperkube[4803]: E0717 21:35:33.362324    4803 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "etcd-member-ip-10-0-115-110.eu-west-1.compute.internal_openshift-etcd(590f121e80ac23d31419a19aa6ab2b85)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-member-ip-10-0-115-110.eu-west-1.compute.internal_openshift-etcd_590f121e80ac23d31419a19aa6ab2b85_0": Error determining manifest MIME type for docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:44acdad8a15f5c5676e272421ff8a977b384b75d45ea39cd8dcccb2339f9f43c: Error reading manifest sha256:44acdad8a15f5c5676e272421ff8a977b384b75d45ea39cd8dcccb2339f9f43c in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized
Jul 17 21:35:33 ip-10-0-115-110 hyperkube[4803]: E0717 21:35:33.362352    4803 kuberuntime_manager.go:660] createPodSandbox for pod "etcd-member-ip-10-0-115-110.eu-west-1.compute.internal_openshift-etcd(590f121e80ac23d31419a19aa6ab2b85)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-member-ip-10-0-115-110.eu-west-1.compute.internal_openshift-etcd_590f121e80ac23d31419a19aa6ab2b85_0": Error determining manifest MIME type for docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:44acdad8a15f5c5676e272421ff8a977b384b75d45ea39cd8dcccb2339f9f43c: Error reading manifest sha256:44acdad8a15f5c5676e272421ff8a977b384b75d45ea39cd8dcccb2339f9f43c in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized
```

it looks like your pull-secret doesn't have access to pull images..?

**Comment by Jabulisile** [comment]
Thanks Abhinav. Rebuilt with a new pull-secret and the error has cleared. Closing the issue.

**Comment by dmc5179** [comment]
@Jabulisile Could you elaborate on rebuilding a pull secret? I'm still not able to get access.
