### ISSUE TITLE
baremetal: keepalived/coredns systemd restarts can permanently fail

### ISSUE THREAD

**Issue by hardys** [openshift/installer#2032]
Platform: baremetal

# What happened?

The keepalived and coredns services are currently started via systemd units (although there is work in progress to convert to static pods ref https://github.com/openshift-metal3/kni-installer/pull/155)

When testing locally I hit an issue which caused the keepalived container to exit, but then the systemd restart got stuck permanently with a "storage for container N removed" error.

It seems that on exit podman cleans some resources for the container, so we can't just re-start it, we need to first remove the old container, then redefine a new one (doing a podman rm -f on the failed container meant the next systemd restart worked..)

# What you expected to happen?

Systemd restart should attempt to re-launch the container after failure.

# How to reproduce it (as minimally and precisely as possible)?

This seems to be a transient failure unfortunately, not yet figured out the root-cause and unfortunately lost my local logs redeploying to test a PR to work around the issue..

# Proposed fixes

There seem to be two options,  we either always clean up existing containers in the ExecStartPre script, or we make the switch to staticpods, which I assume will resolve this case (what's the restart policy in that case?)

**Comment by abhinavdahiya** [comment]
I think all of this is moved to static pods and therefore seems like should not be an issue anymore.

/close
