### ISSUE TITLE
manifest-templates option is missing from installer

### ISSUE THREAD

**Issue by JuozasA** [openshift/installer#2053]
# Version

```console
$ $ ./openshift-install version
./openshift-install unreleased-master-1359-g665a8608e5383e5b929b6fa8eb6b99da0b6b77d8
built from commit 665a8608e5383e5b929b6fa8eb6b99da0b6b77d8
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform: Any

# What happened?

I remember on version 4.0 there was an option to generate manifest-templates before installation. Now i see it is gone. Are there plans to bring it back? 

```
$ ./openshift-install create --help
Create part of an OpenShift cluster

Usage:
  openshift-install create [flags]
  openshift-install create [command]

Available Commands:
  cluster          Create an OpenShift cluster
  ignition-configs Generates the Ignition Config asset
  install-config   Generates the Install Config asset
  manifests        Generates the Kubernetes manifests
```

# What you expected to happen?

manifest-templates option available when running openshift-install create

**Comment by abhinavdahiya** [comment]
We released GA 4.1 without that option. And we don't have current plans to bring them back.

What's your use case?

**Comment by JuozasA** [comment]
Currently, if I am installing OCP on public cloud, I have no option to select the ingress type (it defaults to LoadBalancerService and creates the LB with all the DNS records, public IP and security rules).
 
Most of potential (including my current client) OCP4 clients will want to restrict the Ingress access from the Internet to their OCP. 
Right now, e.g. on Azure, if i try to change the Network Security Group rules, kubernetes changes them back.

If there is a way to specify the endpointPublishingStrategy parameter anywhere in manifests then that is fine, but how I understant, this needs to be specified in ingresscontroller, not the cluster operator...

**Comment by abhinavdahiya** [comment]
manifest-templates would not help with that. And you can open bug/rfe with cluster-ingress-operator to make the LB private.

/close
