### ISSUE TITLE
RFE: Add install-config.yaml document to explain all the parameters

### ISSUE THREAD

**Issue by e-minguez** [openshift/installer#2058]
# Version
any

# Platform:
any

# What happened?
The `install-config.yaml` file contains a lot of parameters that should be explained for users.

# What you expected to happen?
A `install-config.yaml` document explaining the parameters and values that can be used.

# How to reproduce it (as minimally and precisely as possible)?
Try to figure out the `install-config.yaml` parameters

# Anything else we need to know?

# References
https://github.com/openshift/installer/pull/1161

**Comment by abhinavdahiya** [comment]
we already have customization docs for our supported platforms:

aws: https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md
azure: https://github.com/openshift/installer/blob/master/docs/user/azure/customization.md

so i'm not sure what else would be required?
