### ISSUE TITLE
baremetal:  installer should register hosts for masters and workers

### ISSUE THREAD

**Issue by russellb** [openshift/installer#2063]
Original issue from @dhellmann here: https://github.com/openshift-metal3/kni-installer/issues/46

---

# Platform:

baremetal

# What happened?

After the cluster was running, there were no BareMetalHost objects associated with the Machines for master Nodes.

# What you expected to happen?

At least the information for the BareMetalHost CRs for the masters should be registered. If those are set up with the machineRef linked to existing Machines, the hosts will be marked as "externally provisioned" and managed more safely (they won't be rebooted to inspect their hardware).

# How to reproduce it (as minimally and precisely as possible)?

```console
$ cd dev-scripts
$ make
```

# Anything else we need to know?

To populate the hardware details for masters we will have to update the Status block of the host objects.

# References

- https://github.com/openshift-metalkube/dev-scripts/pull/330

**Comment by zeenix** [comment]
We modified the issue template to make it harder for issue creators to add names of non-relevant platforms in the description recently but seems we didn't do a good job of that. Could you please remove them from description, thanks.

**Comment by russellb** [comment]
> We modified the issue template to make it harder for issue creators to add names of non-relevant platforms in the description recently but seems we didn't do a good job of that. Could you please remove them from description, thanks.
> 
> **EDIT:** Ah, you copied from an older issue, that's why. :)

I've removed the platform list, as well.
