### ISSUE TITLE
baremetal: Add dns VIP to install config

### ISSUE THREAD

**Issue by russellb** [openshift/installer#2065]
There is an existing VIP for DNS that must be user supplied.  It's currently discovered using a `ns1.<cluster-name>.<base-domain>` DNS record, but this is not something we want to require be present in external DNS.

Note there was a PR for this against the KNI installer fork, but that fork is now retired:

https://github.com/openshift-metal3/kni-installer/pull/157

**Comment by cybertron** [comment]
DNS VIP is now included in the platform: https://github.com/openshift/installer/blob/b50a68e4b891800ed4823dbf81b21b501ab3c213/pkg/types/baremetal/platform.go#L68

This can be closed.
