### ISSUE TITLE
baremetal: Migrate bootstrap assets to machine-config-operator

### ISSUE THREAD

**Issue by russellb** [openshift/installer#2067]
bootkube already uses MCO to render other bootstrap assets.  The idea here is to move the bootstrap assets for the baremetal platform from the installer to MCO.

A driving motivation behind this is that at install time, we're not able to get the right image pull spec for each of the services.  By moving this to MCO, we can inspect the release image and pass the right pull specs to MCO, similar to what bootkuke does to get other images.

This will also keep maintenance of all of these assets in one place, since they're similar to assets placed on masters and workers.

Here's a related WIP PR that was posted to the old kni installer fork: https://github.com/openshift-metal3/kni-installer/pull/126

**Comment by russellb** [comment]
related: https://github.com/openshift/installer/issues/2038

This issue is kind of a duplicate, but we can leave them both open ...

**Comment by stbenjam** [comment]
@russellb Can you confirm if https://github.com/openshift/installer/pull/2119 fixed this issue?

**Comment by russellb** [comment]
yes, looks like this is done
