### ISSUE TITLE
Images not getting removed on cluster destruction

### ISSUE THREAD

**Issue by zeenix** [openshift/installer#2074]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-1404-ge090d19dda2ba9d80dba652e168fcc8ed54f1b55
built from commit e090d19dda2ba9d80dba652e168fcc8ed54f1b55
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

libvirt

# What happened?

Seems I introduced a regression in https://github.com/openshift/installer/pull/1956 so our custom pool gets deleted on cluster destruction but the images and the dir are not deleted. The issue is probably in terraform-libvirt-provider side but I need to investigate first.

/assign
/label platform-libvirt

**Comment by praveenkumar** [comment]
@zeenix Can you also verify the selinux context on the created images does it have the correct context there?

**Comment by zeenix** [comment]
> @zeenix Can you also verify the selinux context on the created images does it have the correct context there?

I don't know but I think @skitt did test it with selinux: https://github.com/openshift/installer/pull/1956#pullrequestreview-260091802 . I'll recheck.

**Comment by zeenix** [comment]
> @zeenix Can you also verify the selinux context on the created images does it have the correct context there?

I'm not selinux expert but selinux is enforced on my machine and there hasn't been any issues wrt volume access/usage. About the leak itself, I found out the issue and it was in the existing code. #1956 only exposed it. I'll send a PR for this soon after i test my fix.
