### ISSUE TITLE
Azure IPI doc incomplete

### ISSUE THREAD

**Issue by christianh814** [openshift/installer#2124]
# Version

```console
$ openshift-install version
openshift-install v4.1.4-201906271212-dirty
built from commit bf47826c077d16798c556b1bd143a5bbfac14271
release image quay.io/openshift-release-dev/ocp-release@sha256:a6c177eb007d20bb00bfd8f829e99bd40137167480112bd5ae1c25e40a4a163a
```

# Platform:
azure IPI

# What happened?

Doc for azure ipi (https://github.com/openshift/installer/tree/master/docs/user/azure) is incomplete. There are things missing that you need to do that's not outlined.

# What you expected to happen?

Doc gives you information

# How to reproduce it (as minimally and precisely as possible)?

Run through the Azure IPI installer

# Anything else we need to know?

Gist overall steps https://gist.github.com/christianh814/c562e4c96868a48ea07341df99581d65

**Comment by abhinavdahiya** [comment]
Looking at the gist, the only thing it adds is as cli commands to setup SP..

The doc links to Azure to show how to do it.

If you have specific improvements please open a bug with those details. Generic docs are not complete are difficult to objectively fix.


/close
