### ISSUE TITLE
OpenStack:Object Service and Persistent Storage in Dashboard are not available

### ISSUE THREAD

**Issue by Zouuup** [openshift/installer#2136]
# Version

```console
$ openshift-install version
../bin/openshift-install unreleased-master-1483-g547d64a995928f7c9e8473c0721a95c8f53b7711-dirty
built from commit 547d64a995928f7c9e8473c0721a95c8f53b7711
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

# What happened?

After the installation, i have noticed that both "Persistent Storage" and "Object Service" are unavailable in the Dashboard.
in case Persistent Storage, it can be related to #2102 .

in case if Object Service, the name section is unavailable, provider section shows openstack and version section never loads.

# What you expected to happen?
Seeing both services available.

# How to reproduce it (as minimally and precisely as possible)?
Install latest on OpenStack should be enough test, i haven't done anything outside the scope of create cluster.

**Comment by Zouuup** [comment]
I can update that ability to create persistent storage is fixed with 4.2.0-0.okd-2019-08-05-111213, but these issues (dashboard statistics) are not solved yet.
(it's quite possible that i'm not looking at right place)

**Comment by mandre** [comment]
/close

I believe this is fixed now, all stats show up in the dashboard.

Could you give it another try with latest 4.2 or master build? We've fixed some issue with security groups recently that may have prevented the dashboard from showing the stats.
Please reopen if you're still experiencing the issue.

**Comment by Zouuup** [comment]
Fix confirmed.
