### ISSUE TITLE
HTTP_proxy not passed to pods

### ISSUE THREAD

**Issue by Zouuup** [openshift/installer#2142]
# Version

```console
$ openshift-install version
../bin/openshift-install unreleased-master-1483-g547d64a995928f7c9e8473c0721a95c8f53b7711-dirty
built from commit 547d64a995928f7c9e8473c0721a95c8f53b7711
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

# What happened?

While proxy setting passed in manifest file applied to master/worker nodes perfectly fine, it doesn't get passed to containers.
even modifying the proxy in global configuration of the console doesn't seem to have any effect. this cause problems with containers that require internet access such as openshift-cluster-version. 

# What you expected to happen?

pods have the expected proxy configuration

# How to reproduce it (as minimally and precisely as possible)?

1. Add proxy settings to installer
2. deploy cluster
3. add proxy setting to console global configuration
4. oc exec -n openshift-cluster-version cluster-version-operator-77c6f6cd86-dc9zl cat /proc/1/environ | grep http_proxy

**Comment by abhinavdahiya** [comment]
openshift-cluster-version operator uses the proxy values when calling the internet. https://github.com/openshift/cluster-version-operator/pull/219

If the proxy isn't working open an issue on CVO's repo https://github.com/openshift/cluster-version-operator/issues/new

/close
