### ISSUE TITLE
openshift-install should not necessary move to GOPATH and can be clearer 

### ISSUE THREAD

**Issue by bryantson** [openshift/installer#2150]
The instruction to install this installer states:

"Clone this repository to src/github.com/openshift/installer in your GOPATH..."

However, the instruction can made clearer by updating two things:

1. Briefly explain at the top what this installer is for
2. Clearly that the prerequisite to install go programming language. This is mentioned as dependencies but could be made clearer
3. Modify hack/build.sh to not necessarily move the installer to GOPATH but should be executable from any directory
4. Provide the sample install-config.yml (e.g. https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md) directly when redirected to https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations and provide more resources to understand

**Comment by abhinavdahiya** [comment]
> The instruction to install this installer states:
> 
> "Clone this repository to src/github.com/openshift/installer in your GOPATH..."
> 
> However, the instruction can made clearer by updating two things:
> 
>     1. Briefly explain at the top what this installer is for

We have that include in the Description of the repository and `openshift/installer` name felt informative enough.. :)

>     2. Clearly that the prerequisite to install go programming language. This is mentioned as dependencies but could be made clearer

the first line for quickstart https://github.com/openshift/installer/blob/master/README.md#quick-start links to build requirements.. what are additional are you looking here??
 
>     3. Modify hack/build.sh to not necessarily move the installer to GOPATH but should be executable from any directory

Go still requires the packages to build in GOPATH, so we are just following the convention.

>     4. Provide the sample install-config.yml (e.g. https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md) directly when redirected to https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations and provide more resources to understand

install-config.yaml is not required, the installer prompts the first-time user for basic things to get started.. the install-config.yaml examples are for more advanced users.

I think it would be better if you open issues for each thing you would like fixed, blanket issues are difficult to fix.

/close
