### ISSUE TITLE
OpenStack: openshift-kube-controller-manager: no OpenStack cloud provider config file given

### ISSUE THREAD

**Issue by Zouuup** [openshift/installer#2151]
# Version

```console
$ openshift-install version
unreleased-master-1509-gb61c58f4298d251e8e0e77abb1e024f98a4d1e9e-dirty
```

# Platform:
OpenStack

# What happened?
Cluster never deploys
`
[root@pth-mc85j-bootstrap ~]# oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version             False       True          3h4m    Working towards 4.2.0-0.okd-2019-08-04-161913: 82% complete
`

Kube controller manager complains about:
`
W0804 21:45:02.873991       1 plugins.go:118] WARNING: openstack built-in cloud provider is now deprecated. Please use 'external' cloud provider for openstack: https://github.com/kubernetes/cloud-provider-openstack
F0804 21:45:02.874016       1 controllermanager.go:235] error building controller context: cloud provider could not be initialized: could not init cloud provider "openstack": no OpenStack cloud provider config file given
`
* Full log attached
[openshift-kube-controller-manager.txt](https://github.com/openshift/installer/files/3465367/openshift-kube-controller-manager.txt)

**Comment by tomassedovic** [comment]
/assign @Fedosin 

Sorry about that! This should be solved by https://github.com/openshift/cluster-kube-controller-manager-operator/pull/275 once the release image merges.

**Comment by Zouuup** [comment]
Thanks,
after installing 4.2.0-0.okd-2019-08-05-111213, that issue seems to be half-fixed as i'm only receiving:
`
cannot initialize cloud provider, only limited functionality is available : cloud provider is not initialized
`
ideas?

**Comment by Fedosin** [comment]
Should be fixed with: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/275
In the logs I see:
I0805 10:34:01.818833       1 openstack.go:300] OpenStack cloud provider was initialized using data from the secret.

**Comment by Zouuup** [comment]
thanks for the reply @Fedosin ,
no, it appears the error is:
`Aug 05 13:37:34 pth-m548v-master-1.novalocal hyperkube[2631]: E0805 13:37:34.583863    2631 openstack_instances.go:69] cannot initialize cloud provider, only limited functionality is available : cloud provider is not initialized`

running 4.2.0-0.okd-2019-08-05-111213

**Comment by Fedosin** [comment]
@Zouuup if we are talking about kubelet logs, then it's fine... kubelet can't initialize the provider and operates with limited functionality - it's enough for the service to do its job :)
but you're right - we shouldn't print errors in this case. on the other hand we need these messages if kube-controller-manager can't init the provider.
The only solution I see is to decrease the log level from error to warning here: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go#L69
