### ISSUE TITLE
libvirt: monitoring operator not startup 24h after install 

### ISSUE THREAD

**Issue by jichenjc** [openshift/installer#2166]
# Version

```console
$ openshift-install version
<your output here>
```
[root@jichen-test2 installer]# bin/openshift-install version
bin/openshift-install unreleased-master-1506-g885a44213514c81507c62af9d7271e176baa5c05
built from commit 885a44213514c81507c62af9d7271e176baa5c05
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform:

# What happened?

```
monitoring                                                                 False       True          True       23h
```

install complete and most operators startup correctly, but 
```
[core@test1-nncq4-master-0 ~]$ oc describe clusteroperators monitoring
Name:         monitoring
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  config.openshift.io/v1
Kind:         ClusterOperator
Metadata:
  Creation Timestamp:  2019-08-05T08:58:00Z
  Generation:          1
  Resource Version:    288449
  Self Link:           /apis/config.openshift.io/v1/clusteroperators/monitoring
  UID:                 2036b1f5-b75f-11e9-bb60-5254006aa4ca
Spec:
Status:
  Conditions:
    Last Transition Time:  2019-08-06T08:14:44Z
    Message:               Rolling out the stack.
    Status:                True
    Type:                  Progressing
    Last Transition Time:  2019-08-06T03:50:59Z
    Message:               Failed to rollout the stack. Error: running task Updating configuration sharing failed: failed to retrieve Prometheus host: getting Route object failed: the server is currently unable to handle the request (get routes.route.openshift.io prometheus-k8s)
    Status:                True
    Type:                  Degraded
    Last Transition Time:  2019-08-06T08:14:44Z
    Message:               Rollout of the monitoring stack is in progress. Please wait until it finishes.
    Status:                False
    Type:                  Upgradeable
    Last Transition Time:  2019-08-05T09:02:35Z
    Status:                False
    Type:                  Available
  Extension:               <nil>
  Related Objects:
    Group:     operator.openshift.io
    Name:      cluster
    Resource:  monitoring
    Group:
    Name:      openshift-monitoring
    Resource:  namespaces
Events:        <none>
```

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by zeenix** [comment]
@jichenjc Thanks for reporting this issue. In future, kindly remove the irrelevant bits from the issue template that you won't be filling/replacing.

**Comment by zeenix** [comment]
Since this happens *after* a successful install, I don't think it's likely to be an Installer issue. Please talk to [Monitoring folks](https://github.com/openshift/cluster-monitoring-operator) to get to the bottom of this. Feel free to reopen this if it turns out an Installer issue somehow after all.

**Comment by jichenjc** [comment]
thanks, I will pay attention to the format later
and I will open an issue for monitor after further analysis on my system
