### ISSUE TITLE
Document tags/naming conventions used by Terraform for teardown

### ISSUE THREAD

**Issue by adambkaplan** [openshift/installer#2172]
# Version
v4.2.0

```console
$ openshift-install version
<your output here>
```

# Platform:

All

# What happened?

There's been a bit of churn on what is expected of resources created/provisioned by cluster operators for teardown via Terraform to work properly (for UPI clusters).

See:
1. https://github.com/openshift/cluster-image-registry-operator/pull/352
2. https://github.com/openshift/cluster-image-registry-operator/pull/347

# What you expected to happen?

DevEx would like to have clear guidance on which tags, naming conventions, or other requirements are needed to have cluster teardown via Terraform work on each cloud provider.

# Anything else we need to know?

Do we need similar guidance for `destroy cluster`?

**Comment by abhinavdahiya** [comment]
Terraform is NOT used for destroying cluster.

Each platform has a different way _because of platform limitation_ of keeping track for destroy cluster.

**Comment by adambkaplan** [comment]
@Fedosin can you comment on what Terraform is being used for with OpenStack?

**Comment by tomassedovic** [comment]
@adambkaplan I don't have the context here, but it should be the same as any other IPI platform: initial cluster creation and removal of the bootstrap server.

Cluster destroy uses go code.

**Comment by abhinavdahiya** [comment]
I don't think this is an issue we need an action item for, as we don't use terraform for deleting any code.
destroy cluster is all go based.

/close
