### ISSUE TITLE
Openshift 4.1 baremetal, after adding RHEL 7.6 nodes to cluster, not able to login to master. Error : EOF.

### ISSUE THREAD

**Issue by sunilhsk** [openshift/installer#2179]
# Version

```console
$ openshift-install version
<your output here>
```

# Platform:

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Can you provide details for this bug??

What process did you follow?

**Comment by abhinavdahiya** [comment]
/close

> Can you provide details for this bug??
> 
> What process did you follow?
