### ISSUE TITLE
Vsphere terraform deployment fail

### ISSUE THREAD

**Issue by fctoibm** [openshift/installer#2183]
# Version

```console
$openshift-install v4.1.6-201907101224-dirty
built from commit e8e6d8998bed2087244a14be16185235b43d6407
release image quay.io/openshift-release-dev/ocp-release@sha256:aa955a9ec40e55e5d9c0203a995b398e8c1031473dae24ed405efe9a95b43186


# Platform:
<!--
Vmware
-->

# What happened?

The directions are not clear on prereqs steps for deploying Openshift using terraform with VMware



Error: Invalid argument name

 on machine/main.tf line 47, in resource “vsphere_virtual_machine” “vm”:
 47:       “guestinfo.ignition.config.data”          = “${base64encode(data.ignition_config.ign.*.rendered[count.index])}”

Argument names must not be quoted.
Step
https://github.com/openshift/installer/blob/master/upi/vsphere/README.md#pre-requisites

Do we need to download OVA file and place it where?

**Comment by abhinavdahiya** [comment]
try using terraform 0.11, we don't yet support 0.12.

**Comment by DanyC97** [comment]
@fctoibm it will be supported once https://github.com/openshift/installer/pull/2057 will be merged, for now is on hold until 4.2 is released

**Comment by mca7267** [comment]
Terraform v0.11.12 doesn't seem to work either. When I run ./terraform apply, validate, or plan I get the same error (see below) The error is benign and the logging stinks. 

./terraform plan
Usage: terraform plan [options] [DIR-OR-PLAN]

  Generates an execution plan for Terraform.

  This execution plan can be reviewed prior to running apply to get a
  sense for what Terraform will do. Optionally, the plan can be saved to
  a Terraform plan file, and apply can take this plan file to execute
  this plan exactly.

  If a saved plan is passed as an argument, this command will output
  the saved plan contents. It will not modify the given plan.

Options:

  -destroy            If set, a plan will be generated to destroy all resources
                      managed by the given configuration and state.

**Comment by DanyC97** [comment]
@mca7267 please don't hijack this issue which is related to 0.12 . Please open a new issue describing your problem, thanks
