### ISSUE TITLE
Web Console is broken

### ISSUE THREAD

**Issue by ahrtr** [openshift/installer#2190]
# Version 
$ bin/openshift-install version
bin/openshift-install unreleased-master-1527-gdd407b0351339ec5fec540c82ecd556ec0dcb98c-dirty
built from commit dd407b0351339ec5fec540c82ecd556ec0dcb98c
release image registry.svc.ci.openshift.org/origin/release:4.2

# Platform 
libvirt

# What happened
The web console was working well in the begining, but it doesn't work now and I did nothing in between.  

Please see the following screen shot,
<img width="978" alt="Screen Shot 2019-08-09 at 11 05 19 AM" src="https://user-images.githubusercontent.com/30739825/62751394-216a8300-ba96-11e9-929d-8cd8faf3eef6.png">

There were error logs in oauth-openshift POD,
```
$ kc logs -f oauth-openshift-76665d876d-smpvw -n openshift-authentication
I0808 07:58:30.529650       1 secure_serving.go:65] Forcing use of http/1.1 only
I0808 07:58:30.530611       1 secure_serving.go:127] Serving securely on 0.0.0.0:6443
E0809 02:57:57.634774       1 osinserver.go:91] internal error: the server is currently unable to handle the request (get oauthclients.oauth.openshift.io console)
E0809 03:06:45.276816       1 osinserver.go:91] internal error: the server is currently unable to handle the request (get oauthclients.oauth.openshift.io console)

E0809 03:07:04.399407       1 osinserver.go:91] internal error: the server is currently unable to handle the request (get oauthclients.oauth.openshift.io console)
E0809 03:07:09.455808       1 osinserver.go:91] internal error: the server is currently unable to handle the request (get oauthclients.oauth.openshift.io console)
```

**Comment by ahrtr** [comment]
Feel free to let me know if any further info is needed.

**Comment by zeenix** [comment]
@ahrtr how much time had passed between cluster initialization and this issue?

**Comment by ahrtr** [comment]
@zeenix It should be more than at least 16 hours. 

The timeline was roughly as below,
1. The cluster was initialized successfully at 4 PM on Aug. 8th;
2. I deployed & un-deployed a simple "hello world" POD in the cluster using "kubectl create -f xxx.yaml" successfully in the same afternoon (at about 4:30 PM?).
3. Two members in the team tried to login into the Web Console in the next morning (Aug. 9th),and both were successful. (at about 9:00 AM). We changed nothing, and we just looked around in the Web Console. 
4. About one hour later, when I tried to login into the Web Console again, then I found this issue.

**Comment by zeenix** [comment]
@ahrtr Thanks for the detailed information. One more question: You're certain nothing changed wrt networking during this time? Firewall etc?

**Comment by ahrtr** [comment]
@zeenix Yes, I am pretty sure that I changed nothing before I saw the issue. 

I destroyed the cluster yesterday, and then created a new cluster, but I did not reproduce this issue so far.

**Comment by zeenix** [comment]
@ahrtr Oh ok, since it's been 5 days of that. I'll close this for now.

/close
