### ISSUE TITLE
Openshift azure -> authorization problem (role?)

### ISSUE THREAD

**Issue by sander53134512** [openshift/installer#2193]
# Version

**4.2.0-0.nightly-2019-06-03-135056**
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.0-0.nightly-2019-06-03-135056/
# Platform:

AZURE

# What happened?

**RROR Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '857803c-1176-46e0-88a4-9e84434936ad' with object id '857803c-1176-46e0-88a4-9e84434936ad' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/760579d-6e21-4a51-988b-54af405584f4/resourceGroups/openshift-automatic-i-zzn7x-rg/providers/Microsoft.Authorization/roleAssignments/89f8d0d8-9fc0-53fa-2dc2-0ac18f9a4b92' or the scope is invalid. If access was recently granted, please refresh your credentials."**

Full error with highest log level:
https://docs.google.com/document/d/1xy5YTX7Nm14rdbOILUA2d87DB2pJfKwIxpmgVOE4n1w/edit?usp=sharing

Azure installs all the network parts
But seems to have troubles reaching the images on Azure.

# What you expected to happen?

**Create a fully functioning openshift cluster**

# How to reproduce it (as minimally and precisely as possible)?

**openshift-install  create cluster --log-level debug**

install-config.yaml
**apiVersion: v1
baseDomain: opensource.devoteam.be
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: openshift-automatic-install
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: opensource-dns-server
    region: westeurope
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3Bl**

# Anything else we need to know?

Seem to be two errors
- **Azure permissions error**
The client 'x' with object id 'y' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/x/resourceGroups/openshift-automatic-i-zzn7x-rg/providers/Microsoft.Authorization/roleAssignments/89f8d0d8-9fc0-53fa-2dc2-0ac18f9a4b92' or the scope is invalid.
- **error that he can't find the image**
"The Image '/subscriptions/760579d-6e21-4a51-988b-54af405584f4/resourceGroups/rhcos_images/providers/Microsoft.Compute/images/rhcostestimage' cannot be found in 'westeurope' region."

**Comment by abhinavdahiya** [comment]
> Azure permissions error
The client 'x' with object id 'y' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/x/resourceGroups/openshift-automatic-i-zzn7x-rg/providers/Microsoft.Authorization/roleAssignments/89f8d0d8-9fc0-53fa-2dc2-0ac18f9a4b92' or the scope is invalid.

https://github.com/openshift/installer/blob/master/docs/user/azure/credentials.md#step-2-attach-administrative-role

Did you make sure the service principal you are using has both the roles assigned for your subscription.

> error that he can't find the image
"The Image '/subscriptions/760579d-6e21-4a51-988b-54af405584f4/resourceGroups/rhcos_images/providers/Microsoft.Compute/images/rhcostestimage' cannot be found in 'westeurope' region."

If you downloaded the installer binary from cloud.redhat.com, Please use the instructions on setting up image for your cluster here https://github.com/openshift/installer/blob/2535155c04539ffe6bb898bcb2e65c2d9c57ec1b/docs/user/azure/install.md

we are in process of another version of OpenShift and the docs have moved to that.

**Comment by sander53134512** [comment]
https://github.com/openshift/installer/blob/2535155c04539ffe6bb898bcb2e65c2d9c57ec1b/docs/user/azure/install.md


Is it important that I use exactly the same names?
Because I get this error:

**sander@Azure:~$ az storage account create --location centralus --name os4storage --kind StorageV2 --resource-group rhel-images-RG**
The storage account named os4storage is already taken.

**sander@Azure:~$ az storage account delete --name os4storage**
Are you sure you want to perform this operation? (y/n): y
usage: az storage account delete [-h] [--verbose] [--debug]
                                 [--output {json,jsonc,table,tsv,yaml,none}]
                                 [--query JMESPATH]
                                 [--subscription _SUBSCRIPTION]
                                 [--resource-group RESOURCE_GROUP_NAME]
                                 [--name ACCOUNT_NAME] [--yes]
                                 [--ids ID [ID ...]]
az storage account delete: error: Storage account 'os4storage' not found.

Or is this because the script itself already created that account

**Comment by sander53134512** [comment]
Also. I added the permissions, this didn't change the error

**Comment by dearmasm** [comment]
I've encountered the same exact issue as OP on my Azure account attempt:
- added all permissions as documented in: 
https://github.com/openshift/installer/blob/master/docs/user/azure/credentials.md
- My `ServicePrincipal` has `User Access Administrator` and `Reader` roles assigned.

```
$ bin/openshift-install create cluster
INFO Creating infrastructure resources...         
ERROR                                              
ERROR Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '741101a0-7171-4814-825f-25a0f6de8cf1' with object id '741101a0-7171-4814-825f-25a0f6de8cf1' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/825332db-1be0-4558-af40-f979eb37fa8d/resourceGroups/os4azure1-w8fhp-rg/providers/Microsoft.Authorization/roleAssignments/4d173ef0-651f-1851-ff3d-2f53904b7fe1' or the scope is invalid. If access was recently granted, please refresh your credentials." 
ERROR                                              
ERROR   on ../../../../../../../var/folders/29/yq50ph6s5gd3w_c3xbc7fxmr0000gn/T/openshift-install-164458995/main.tf line 118, in resource "azurerm_role_assignment" "main": 
ERROR  118: resource "azurerm_role_assignment" "main" { 
ERROR                                              
ERROR                                              
```

**Comment by dearmasm** [comment]
Was able to work-around by adding `Owner` role to `ServicePrincipal`. Not ideal, but got me unblocked for now. It would be nice to know why this is failing.

**Comment by abhinavdahiya** [comment]
> Was able to work-around by adding `Owner` role to `ServicePrincipal`. Not ideal, but got me unblocked for now. It would be nice to know why this is failing.

we document the exact process and requirements for the service principal for azure here https://github.com/openshift/installer/blob/master/docs/user/azure/credentials.md

if you follow that, you should be successful in creating the cluster.
