### ISSUE TITLE
Enhancement: downloading all files before installation

### ISSUE THREAD

**Issue by donghwicha** [openshift/installer#2199]
# Version
N/A 

# Platform:
To all 

# What you expected to happen?
Stable installation 

# Enhancement
Hi. This is just small suggestion. I am testing OCP4 using installer, but I noticed that all steps includes downloading file. before bootstrap, during bootstrap, and after bootstrap. 

I hope downloading files can be done before bootstrap and files can be uploaded via SSH. 

If download is slow temporarily, then bootstrap fails randomly, and I believe this is not what an user will expect.

**Comment by abhinavdahiya** [comment]
>Hi. This is just small suggestion. I am testing OCP4 using installer, but I noticed that all steps includes downloading file. before bootstrap, during bootstrap, and after bootstrap.

Can you please elaborate which files are you pointing to?

**Comment by donghwicha** [comment]
> > Hi. This is just small suggestion. I am testing OCP4 using installer, but I noticed that all steps includes downloading file. before bootstrap, during bootstrap, and after bootstrap.
> 
> Can you please elaborate which files are you pointing to?

All files downloaded.

**Comment by wking** [comment]
Can you provide filenames?  We're not sure which ones you're talking about.
