### ISSUE TITLE
Container network not ready

### ISSUE THREAD

**Issue by davis-jacob** [openshift/installer#2204]
# Version

openshift-install v4.1.8-201907241243-dirty
built from commit e8d7e37ea7655522ac8f6ede471fd1d3ebd1bcba
release image quay.io/openshift-release-dev/ocp-release@sha256:3ea2648231035c1a65e8d91fa818bb225a2815bc0d6abfc35063a11eaba8659f

# Platform:
 (UPI) , vSphere 

# What happened?
The following command created the VMs (3 compute ,3 control and 1 bootstrap) from the ignition and all are booted fine.
openshift-install --dir ~/vsphere wait-for bootstrap-complete

However the command fails waiting for the Kubernetes API server to be available.

Following are the messages from the  journalctl on the compute and control nodes.
```console
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.358717    1268 plugins.go:547] Loaded volume plugin "kubernetes.io/csi"
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: E0812 10:33:20.357822    1268 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: the server could not>
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: E0812 10:33:20.357790    1268 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: the server co>
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: E0812 10:33:20.357779    1268 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: the server could >
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.359347    1268 server.go:1070] Started kubelet
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: E0812 10:33:20.359792    1268 kubelet.go:1308] Image garbage collection failed once. Stats initialization may not have completed yet: faile>
Aug 12 10:33:20 control-plane-1 systemd[1]: Started Kubernetes Kubelet.
Aug 12 10:33:20 control-plane-1 systemd[1]: Reached target Multi-User System.
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.361266    1268 server.go:137] Starting to listen on 0.0.0.0:10250
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.359342    1268 event.go:221] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"control-plane-1", UID:"control-plane->
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: E0812 10:33:20.361816    1268 event.go:203] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.Ob>
Aug 12 10:33:20 control-plane-1 systemd[1]: Starting Update UTMP about System Runlevel Changes...
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.362881    1268 server.go:337] Adding debug handlers to kubelet server.
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.364538    1268 certificate_manager.go:248] Certificate rotation is enabled.
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.364624    1268 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.364765    1268 volume_manager.go:246] The desired_state_of_world populator starts
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.364816    1268 volume_manager.go:248] Starting Kubelet Volume Manager
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.364879    1268 desired_state_of_world_populator.go:130] Desired state populator starts to run
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.365117    1268 status_manager.go:152] Starting to sync pod status with apiserver
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.365190    1268 kubelet.go:1836] Starting kubelet main sync loop.
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.365244    1268 kubelet.go:1853] skipping pod synchronization - [container runtime status check may not have completed yet PL>
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: E0812 10:33:20.365814    1268 kubelet.go:2200] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message>
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.366912    1268 factory.go:157] Registering CRI-O factory
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.368896    1268 factory.go:54] Registering systemd factory
Aug 12 10:33:20 control-plane-1 hyperkube[1268]: I0812 10:33:20.369889    1268 factory.go:97] Registering Raw factory
```
-> Also I see not extra container network adapters created on the compute , control nodes.

# What you expected to happen?
up and running OCP 4.1 cluster 

# How to reproduce it (as minimally and precisely as possible)?
-> VMs set to run on a vSphere cluster
-> machine_cidr = "20.0.0.0/8"
1. Set static IPs from the Control, Compute and Bootstrap in the terraform.tfvars
2. Set the gateway and DNS in the machine/ignition.tf
3. Remove route53 section from the main.tf
4. run terraform init
5. terraform apply -auto-approve
6. openshift-install --dir ~/vsphere wait-for bootstrap-complete

**Comment by abhinavdahiya** [comment]
can provide us the 

1) `openshift-install --dir ~/vshpere gather bootstrap` ?
2) `oc adm must-gather`

**Comment by davis-jacob** [comment]
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3493481/log-bundle.tar.gz)

Couldn't get the openshift install logs due to this error.
ERROR Cannot fetch the bootstrap and control plane host addresses from state file for vsphere platform

However attached is the cluster logs. 
OC commands do not work

**Comment by abhinavdahiya** [comment]
> [log-bundle.tar.gz](https://github.com/openshift/installer/files/3493481/log-bundle.tar.gz)
> 
> Couldn't get the openshift install logs due to this error.
> ERROR Cannot fetch the bootstrap and control plane host addresses from state file for vsphere platform

that's expected as the installer did not create your cluster. provide it the gather bootstrap command the ip adresses to you bootstrap-host and control-plane-hosts.

`openshift-install gather bootstrap --help`

the one you attached doesn't have logs from the control-plane...

> However attached is the cluster logs.
> OC commands do not work

**Comment by davis-jacob** [comment]
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3493533/log-bundle.tar.gz)

This is all I get even after giving three of my control-plane 

openshift-install gather bootstrap --dir ~/ocp41-v8/ --bootstrap 20.0.9.34 --master [20.0.9.35,20.0.9.36,20.0.9.37] --log-level debug

**Comment by abhinavdahiya** [comment]
`openshift-install gather bootstrap --dir ~/ocp41-v8/ --bootstrap 20.0.9.34 --master 20.0.9.35 --master 20.0.9.36 --master 20.0.9.37 --log-level debug`

**Comment by davis-jacob** [comment]
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3493555/log-bundle.tar.gz)

INFO ssh -A core@20.0.9.34 '/usr/local/bin/installer-gather.sh 20.0.9.35 20.0.9.36 20.0.9.37'
INFO scp core@20.0.9.34:~/log-bundle.tar.gz .

Thank you

**Comment by davis-jacob** [comment]
@abhinavdahiya is that log bundle good enough ?

**Comment by abhinavdahiya** [comment]
> [log-bundle.tar.gz](https://github.com/openshift/installer/files/3493555/log-bundle.tar.gz)
> 
> INFO ssh -A core@20.0.9.34 '/usr/local/bin/installer-gather.sh 20.0.9.35 20.0.9.36 20.0.9.37'
> INFO scp core@20.0.9.34:~/log-bundle.tar.gz .
> 
> Thank you

the control-plane dir is empty. So it looks like the control plane machines aren't reachable over ssh with the same key as the bootstrap or your ssh-agent doesn't have the right set of keys..

`ssh -A core@20.0.9.34 '/usr/local/bin/installer-gather.sh 20.0.9.35 20.0.9.36 20.0.9.37'`
^^ what's the output when you run the command?

the bootstrap-host is waiting for etcd cluster to start on the control-plane host.

here's what will help in debugging from the control-plane node:
1) journalctl -fu kubelet
2) logs from all the containers running on the control-plane host. `sudo crictl ps -a` and `sudo crictl logs <id of the container>`

**Comment by davis-jacob** [comment]
> ssh -A core@20.0.9.34 '/usr/local/bin/installer-gather.sh 20.0.9.35 20.0.9.36 20.0.9.37'
^^ what's the output when you run the command?

> It asked for the confirm the SSH key for adding to known host file and then gathering started
Warning: Permanently added '20.0.9.34' (ECDSA) to the list of known hosts.
Gathering bootstrap journals ...
Gathering bootstrap containers ...
Gathering rendered assets...
Gathering cluster resources ...
error: the server doesn't have a resource type "pods"
error: the server doesn't have a resource type "nodes"
error: the server doesn't have a resource type "nodes"

1. journalctl -fu kubelet
Attached is the journalctl log for one control-plane

2.	logs from all the containers running on the control-plane host
Not many running, attached are couple of the container logs.

3. I dont see any service networks and pod networks created on the nodes


[CONTAINER-600d4e0a17028.txt](https://github.com/openshift/installer/files/3496722/CONTAINER-600d4e0a17028.txt)

[journalctl-kubelet-control-plane-0.txt]

(https://github.com/openshift/installer/files/3496723/journalctl-kubelet-control-plane-0.txt)
[CONTAINER-83c5dd7842c3c.log](https://github.com/openshift/installer/files/3496724/CONTAINER-83c5dd7842c3c.log)

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/files/3496724/CONTAINER-83c5dd7842c3c.log

>> I0813 09:14:45.083157       1 run.go:134] checking against etcd-0.
E0813 09:14:45.084309       1 run.go:63] error looking up self: could not resolve member "etcd-0."
I0813 09:15:15.085784       1 run.go:134] checking against etcd-0.
E0813 09:15:15.086664       1 run.go:63] error looking up self: could not resolve member "etcd-0."
I0813 09:15:45.085437       1 run.go:134] checking against etcd-1.
E0813 09:15:45.086282       1 run.go:63] error looking up self: could not resolve member "etcd-1."
I0813 09:16:15.085574       1 run.go:134] checking against etcd-0.
E0813 09:16:15.086537       1 run.go:63] error looking up self: could not resolve member "etcd-0."
I0813 09:16:45.085689       1 run.go:134] checking against etcd-1.
E0813 09:16:45.086880       1 run.go:63] error looking up self: could not resolve member "etcd-1."
I0813 09:17:15.085645       1 run.go:134] checking against etcd-1.
E0813 09:17:15.086737       1 run.go:63] error looking up self: could not resolve member "etcd-1."
I0813 09:17:45.085415       1 run.go:134] checking against etcd-2.
E0813 09:17:45.086298       1 run.go:63] error looking up self: could not resolve member "etcd-2."
I0813 09:18:15.085648       1 run.go:134] checking against etcd-0.
E0813 09:18:15.086482       1 run.go:63] error looking up self: could not resolve member "etcd-0."
I0813 09:18:45.085432       1 run.go:134] checking against etcd-2.
E0813 09:18:45.086383       1 run.go:63] error looking up self: could not resolve member "etcd-2."
I0813 09:19:15.085359       1 run.go:134] checking against etcd-0.
E0813 09:19:15.086429       1 run.go:63] error looking up self: could not resolve member "etcd-0."
I0813 09:19:45.085824       1 run.go:134] checking against etcd-1.
E0813 09:19:45.086983       1 run.go:63] error looking up self: could not resolve member "etcd-1."
I0813 09:19:45.087732       1 run.go:134] checking against etcd-2.
E0813 09:19:45.088605       1 run.go:63] error looking up self: could not resolve member "etcd-2."
F0813 09:19:45.088760       1 main.go:30] Error executing etcd-setup-environment: could not find self: timed out waiting for the condition


It looks like you have not correctly setup your etcd URLs. https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html#installation-dns-user-infra_installing-vsphere

**Comment by davis-jacob** [comment]
Thank you so much @abhinavdahiya  , you were right my DNS entries were messed for the etcd
