### ISSUE TITLE
OpenStack: API service VM is not launched/created

### ISSUE THREAD

**Issue by oybed** [openshift/installer#2208]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1575-g8db0de0082ceefba04327fc9d767095da3db8d69
built from commit 8db0de0082ceefba04327fc9d767095da3db8d69
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

openstack

# What happened?
Following the experimental support for OpenStack, there should be a 'service VM' being launched to provide API LB access. This does not happen when using the above mentioned commit id (latest?). When downloading the `openshift-install` from the [latest mirror](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/) it works fine and the *-api instance is created. 

# What you expected to happen?

The *-api instance should be created per the (experimental) documentation.

# How to reproduce it (as minimally and precisely as possible)?

Follow the instructions in the experimental section for OpenStack.

**Comment by oybed** [comment]
Well, so it seems that this is intentional per PR https://github.com/openshift/installer/pull/1959 ... so the [(experimental) docs for OpenStack](https://github.com/openshift/installer/blob/master/docs/user/openstack/README.md) should be updated to reflect this.

**Comment by dprince** [comment]
> Well, so it seems that this is intentional per PR #1959 ... so the [(experimental) docs for OpenStack](https://github.com/openshift/installer/blob/master/docs/user/openstack/README.md) should be updated to reflect this.

I think this may be a case where we just need to update the docs and expectations. During the last sprint the service VM requirement was removed (as you mentioned in the PR #1959).

**Comment by mandre** [comment]
Thanks, I'm going to close this as the docs were refreshed in https://github.com/openshift/installer/pull/2218 and should not mention the service VM anymore.
