### ISSUE TITLE
tf ignition provider does not support the use of a custom CA

### ISSUE THREAD

**Issue by oybed** [openshift/installer#2225]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-1597-gc7a87b5a60201a22f7b061bb18ed8133460de4b6-dirty
built from commit c7a87b5a60201a22f7b061bb18ed8133460de4b6
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:
openstack (although not necessarily OSP related)

# What happened?
The [ignition provider](https://www.terraform.io/docs/providers/ignition/index.html) for Terraform only supports ignition 2.1.0 (see output below). This version does not support using custom CAs to validate the ignition append URL (v2.2.x of ignition does). This means that ignition fails to download the bootstrap.ign, etc. from the source URL when a custom CA is used for the target hosting environment -  for example, when a custom CA is used for OpenStack, and hence the tempurl https link won't work when the instance(s) attempt to fetch the (secondary) ignition data. The bootstrap instance will continue to fail/retry during boot due to "x509: certificate signed by unknown authority". 

Here's an example of the terraform provided ignition user-data found on the OpenStack instance:

```console
> curl http://169.254.169.254/latest/user-data
{"ignition":{"config":{},"timeouts":{},"version":"2.1.0"}, ...
 :
```

# What you expected to happen?

I would have expected that a custom CA can be provided at install time to allow for correct URL validation. However, this was introduced in ignition v2.2.x with the security/tls object:
https://coreos.com/ignition/docs/latest/configuration-v2_2.html

# How to reproduce it (as minimally and precisely as possible)?

Target a hosting environment, for example openstack, with certificates generated with the custom CA. Observe that the bootstrap instance will not fetch its (seconary) ignition configuration due to the custom CA.

# Anything else we need to know?
Note that ignition v2.2.0 is used for the ignition data generated secondary, but the initial data generated by terraform (what's found in the [data](https://github.com/openshift/installer/tree/master/data) directory) is v2.1.0 - as also described [here](https://www.terraform.io/docs/providers/ignition/index.html#ignition-versions) - and hence the v2.2.0 data cannot be fetched due to the custom CA.

**Comment by mandre** [comment]
Related feature request in the terraform ignition provider issue tracker: https://github.com/terraform-providers/terraform-provider-ignition/issues/42

**Comment by iamemilio** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1735192

**Comment by wking** [comment]
Hmm.  Ignition configs for the bootstrap and control-plane machines should [come out of Go][1] and not be generated with Terraform's Ignition provider.  And we [add a CA there][2].

[1]: https://github.com/openshift/installer/blob/8c9abe40f7616303c03cafdc9ad612cd8fa7bd6b/data/data/config.tf#L54-L72
[2]: https://github.com/openshift/installer/blob/8c9abe40f7616303c03cafdc9ad612cd8fa7bd6b/pkg/asset/ignition/machine/node.go#L50-L53

**Comment by wking** [comment]
Ah, perhaps you mean that we should inject a CA [into the bootstrap Ignition config][1] (where we don't, at the moment, add any custom CAs).

[1]: https://github.com/openshift/installer/blob/8c9abe40f7616303c03cafdc9ad612cd8fa7bd6b/pkg/asset/ignition/bootstrap/bootstrap.go#L132-L174

**Comment by oybed** [comment]
There is a bit of a chicken/egg situation as in order to be able to fetch the generated config we need the initial boot to have access (and use) the CA as well - otherwise it will fail to fetch the config from a https:// url.

**Comment by wking** [comment]
So why don't you know the CA you'll need when you [generate the bootstrap config][1]?  Couldn't you construct the pointer config then too?

[1]: https://github.com/openshift/installer/blob/8c9abe40f7616303c03cafdc9ad612cd8fa7bd6b/pkg/asset/ignition/bootstrap/bootstrap.go#L132-L174
[2]: https://github.com/openshift/installer/blob/58205006353c4be4a1f1a8fce95136020d6ede95/data/data/openstack/bootstrap/main.tf#L62-L72

**Comment by oybed** [comment]
Hopefully my original write-up above explains this in detail. Basically, the Terraform Ignition provider **is** currently used by the OpenShift installer and hence only version 2.1.x is supported (see output/capture in the original write-up) and hence there is no way to make it provide and consume a custom CA (this was added in ignition v2.2.x).

**Comment by wking** [comment]
> Basically, the Terraform Ignition provider is currently used by the OpenShift installer and hence only version 2.1.x is supported...

I'm still not clear on why "stop touching Install configs with the Terraform Ignition provider and just build Install configs in Go and pass them opaquely through Terraform" isn't an option.

**Comment by iamemilio** [comment]
I think we should be able to resolve this by generating _all_ templates in Go, rather than in terraform. The current cert issue we are having is two fold, we need the customers Cert bundle to be trusted on the bootstrap node, which is not a feature yet, and we are currently generating the bootstrap shim in Terraform instead of Go, which would prevent us from writing this feature. I am going to do more discovery on this today, but it seems like it should be doable.

**Comment by oybed** [comment]
Agreed - when digging in on this a few weeks back, I came to the same conclusion that it's more of a shift in approach than something as simple as "passing the correct values/parameters". Moving away from the TF Ignition provider I believe is a given (as I see others have done that as well), but it may mean quite a bit of refactoring. @iamemilio Please let me know if there is anything I can assist with.

**Comment by iamemilio** [comment]
We are proposing a solution here: https://github.com/openshift/installer/pull/2270
Feel free to contribute to the conversation

**Comment by abhinavdahiya** [comment]
I think this was fixed by https://github.com/openshift/installer/pull/2587

/close
