### ISSUE TITLE
OpenStack: using wrong IP when gathering debug logs

### ISSUE THREAD

**Issue by ppitonak** [openshift/installer#2229]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1601-g4e204c5e509de1bd31113b0c0e73af1a35e52c0a-dirty
built from commit 4e204c5e509de1bd31113b0c0e73af1a35e52c0a
release image registry.svc.ci.openshift.org/ocp/release@sha256:5b3258e168b8b8d05970c7a75018fa79d38639dbd560df3f1f156a892b176421
```

# Platform:

OpenStack 13

# What happened?

Installation failed because I forgot to update DNS records (expected) and then the installer tried to ssh to bootstrap node to get debug logs which failed:

```
INFO Pulling debug logs from the bootstrap machine 
ERROR failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: dial tcp 172.16.0.16:22: connect: connection timed out 
FATAL waiting for Kubernetes API: context deadline exceeded
```

The issue is that `172.16.0.16` is and IP address from internal network created by installer, the node had a floating IP `10.0.79.177` which was assigned by installer for this kind of situations.

# What you expected to happen?

Installer tries to ssh to bootstrap VM using the floating IP, not using internal IP.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
This should be fixed by https://github.com/openshift/installer/pull/2212

**Comment by mandre** [comment]
Going to close this bug since the patch addressing the issue was merged. Please reopen if it reproduces with a recent build.

/close
