### ISSUE TITLE
OpenStack: Nameserver limits were exceeded, some nameservers have been omitted

### ISSUE THREAD

**Issue by ppitonak** [openshift/installer#2230]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1601-g4e204c5e509de1bd31113b0c0e73af1a35e52c0a-dirty
built from commit 4e204c5e509de1bd31113b0c0e73af1a35e52c0a
release image registry.svc.ci.openshift.org/ocp/release@sha256:d1c69ad529dab9fc1c8498fd889950be4816007b0fb447f66587472707eae855
```

# Platform:

OpenStack 13

# What happened?

During a new cluster installation when the installer is still waiting for the cluster to initialize (`DEBUG Still waiting for the cluster to initialize: Working towards 4.2.0-0.ci-2019-08-19-054234: 80% complete`), watch for event (`oc get events -w -A`)

There are a lot of warnings similar to these:

```
openshift-kube-scheduler                                0s          Warning   DNSConfigForming                         pod/openshift-kube-scheduler-alpha-4kvb5-master-0                             Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.16.0.6 172.16.0.12 172.16.0.10
openshift-machine-config-operator                       0s          Warning   DNSConfigForming                         pod/etcd-quorum-guard-545557d44-wll4z                                         Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.16.0.6 172.16.0.12 172.16.0.10
openshift-cluster-node-tuning-operator                  1s          Warning   DNSConfigForming                         pod/tuned-5x85q                                                               Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.16.0.6 172.16.0.12 172.16.0.10
```

When I ssh to a master node, I see the following
```
$ cat /etc/resolv.conf 
# Generated by NetworkManager
search alpha.devel.pitonak.com
nameserver 172.16.0.6
nameserver 172.16.0.12
nameserver 172.16.0.10
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 172.16.0.11
```

# What you expected to happen?

No warnings

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by paulliss** [comment]
Have the same trouble with Kubernetes 1.15 through RKE
coredns crashes with 
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is....

as a solution:
https://coredns.io/plugins/loop/#troubleshooting

**Comment by ishaannarang** [comment]
Linux has limits of just 3 DNS nameserver records and 6 DNS search records. Kubernetes needs to consume 1 nameserver record and 3 search records. This means that if a local installation already uses 3 nameservers or uses more than 3 searches, some of those settings will be lost.

https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues

**Comment by pierreprinetti** [comment]
Thank you for reporting. This issue [is being tracked](https://bugzilla.redhat.com/show_bug.cgi?id=1791008) in Red Hat's Bugzilla.

**Comment by waheedi** [comment]
I think this is not really a bug, https://bugzilla.redhat.com/show_bug.cgi?id=1791008#c15

i managed to get rid of the warnings (which are legit warnings btw)

edit your net plan config located here `/etc/netplan/SOME_FILE.yaml` and make sure to keep up to three `nameservers`

then `systemctl daemon-reload && systemctl systemd-networkd && systemctl restart systemd-resolved && systemctl restart kubelet`

**Comment by pierreprinetti** [comment]
The [fix](https://github.com/openshift/machine-config-operator/pull/1573) has been applied in OpenShift 4.5.
/close
