### ISSUE TITLE
openshift-install for Azure, "authorizer" file already present and incorrect

### ISSUE THREAD

**Issue by heatmiser** [openshift/installer#2237]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1088-g273cece0ea05bd55ac7d03c5c3022255ea4fd5f7-dirty
built from commit 273cece0ea05bd55ac7d03c5c3022255ea4fd5f7
release image quay.io/openshift-release-dev/ocp-release@sha256:8d51bc2da4b9873053b2b3f0737c912ba1e0623ff4b303f1a8ec3618ba3354ff
```

# Platform:
azure

# What happened?

Using the installer for an Azure deployment:

./openshift-install create install-config --log-level debug
...proceed through SSH Public Key step, then select Azure...
? Platform azure
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": failed to get list of regions...(extra output removed)

Not sure why the file was already in place, might have been from a different install I was attempting with a different installer, however, ~/.azure/osServicePrincipal.json was already present with the following values:

{"subscriptionId":"azid","clientId":"svcprincipalid","clientSecret":"svcprincipalscrt","tenantId":"mytenantid"}

# What you expected to happen?

Currently, when executing with DEBUG enabled, a message is provided when credentials file is not found...

? Platform azure
DEBUG Could not get an azure authorizer from file. Asking user to provide authentication info 
? azure subscription id [? for help]

However, as it stands now, if ~/.azure/osServicePrincipal.json is already present, openshift-install assumes that the contents are correct and are what the end user wants to use for the deployment.  Additionally, if the end user is not aware that this file is already present and populated, a debug message should be provided to point to the location of the azure authorizer file and allow for troubleshooting/corrections.  Example proposed DEBUG message:

DEBUG azure authorization credentials found in file ~/.azure/osServicePrincipal.json

Thus if the above error is experienced, the end user can be notified of the location of the authorizer file, make edits/adjustments and re-run the install.  Or possibly, the openshift-install code could be modified such that if the authorizer file already exists, notify the end user of it's location and current contents, asking if they would like to continue with values that are present before proceeding.

# How to reproduce it (as minimally and precisely as possible)?

Use an authorization file, ~/.azure/osServicePrincipal.json that is already in place with incorrect authorization/authentication credentials.

**Comment by asalkeld** [comment]
@heatmiser thanks for reporting this, I just ran into the same issue. I'll post a PR to at least provide a log and better error message.

**Comment by xjtustt** [comment]
@asalkeld 
I also encountered this problem, errors are exactly same with @heatmiser 's .
Do we know the root cause now?
@gyliu513 FYI.

**Comment by abhinavdahiya** [comment]
The installer now prints the location of the credentials being used. So the user would now know what to fix.

/close
