### ISSUE TITLE
Openshift 4.2 with proxy enabled : cant deploy images from internal registry

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/installer#2241]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1601-g4e204c5e509de1bd31113b0c0e73af1a35e52c0a
built from commit 4e204c5e509de1bd31113b0c0e73af1a35e52c0a
release image registry.svc.ci.openshift.org/origin/release:4.2

```

# Platform:

None

# What happened?

cant deploy using the internal registry because there is no no_proxy for .svc default.   
# What you expected to happen?

# How to reproduce it (as minimally and precisely as possible)?

Install openshift 4.2 with proxy enabled and deploy default jenkins empheral template

# Anything else we need to know?

No not at this time

**Comment by abhinavdahiya** [comment]
Try opening an issue on https://github.com/openshift/cluster-network-operator/issues as the NoProxy default list is maintained for cluster by the operator. Thanks!

/close
