### ISSUE TITLE
quick start questions

### ISSUE THREAD

**Issue by magick93** [openshift/installer#2250]
Hello

I have a few, hopefully simple, questions.

In the readme, there is a section titled **Quick Start**. Is this for quickly starting development on this project? Or is this for using the openshift installer? I'm asking as I just want to use the installer, and would prefer to not have to install go and terraform, if possible.

Do I need to build from source, and thus install go and terraform? Or is there a binary I can download from the `releases` page? 

I've tried to download and run the linux asset from the `releases` page for this project and, regardless of what command I run, I get the same result - nothing.

First I ran `chmod +x openshift-install-linux-amd64` then tried the following:
```
 ./openshift-install-linux-amd64 
./openshift-install-linux-amd64 --version
 ./openshift-install-linux-amd64  create cluster
```

There was no output from any of the above commands. 

For using VMWare, I'm reading https://github.com/openshift/installer/blob/master/upi/vsphere/README.md and wonder why is AWS required? And why do I need `jq`? 
From the above link it says:

> Fill out a terraform.tfvars file with the ignition configs generated

Maybe I'm misunderstanding this, but it sounds like the installer generates a file, then I need to copy values from this file to another file. Wouldnt it be easier to just generate `terraform.tfvars` with the required values and let the user fill in the remaining values?

After the above step there is a further 5 or 6 steps. Yet on the Readme there is an example of running just one command - `openshift-install create cluster`. Does this command not work with vmware? Is it not possible to condense the list of commands into a single command?

**Comment by abhinavdahiya** [comment]
> Hello
> 
> I have a few, hopefully simple, questions.
> 
> In the readme, there is a section titled **Quick Start**. Is this for quickly starting development on this project? Or is this for using the openshift installer? I'm asking as I just want to use the installer, and would prefer to not have to install go and terraform, if possible.
> 
> Do I need to build from source, and thus install go and terraform? Or is there a binary I can download from the `releases` page?
> 

if you want just the installer, feel free to head over to https://docs.openshift.com/container-platform/4.2/welcome/index.html and follow instructions for whatever platform you like.

> I've tried to download and run the linux asset from the `releases` page for this project and, regardless of what command I run, I get the same result - nothing.
> 
> First I ran `chmod +x openshift-install-linux-amd64` then tried the following:
> 
> ```
>  ./openshift-install-linux-amd64 
> ./openshift-install-linux-amd64 --version
>  ./openshift-install-linux-amd64  create cluster
> ```

we don't release binaries as part of the repo anymore, all binaries are generated by Red Hat infra and made available to users from the link i mentioned above.

> There was no output from any of the above commands.
> 
> For using VMWare, I'm reading https://github.com/openshift/installer/blob/master/upi/vsphere/README.md and wonder why is AWS required? 

Because we use AWS to host the DNS records for the example-vpshere we have in the repo.

> And why do I need `jq`?
> From the above link it says:
> 
> > Fill out a terraform.tfvars file with the ignition configs generated
> 
> Maybe I'm misunderstanding this, but it sounds like the installer generates a file, then I need to copy values from this file to another file. Wouldnt it be easier to just generate `terraform.tfvars` with the required values and let the user fill in the remaining values?

The goal of the installer is to produce assets, that can be used by anybody and not just terraform, that's why the binary doesn't provide you any specific asset.
 
> After the above step there is a further 5 or 6 steps. Yet on the Readme there is an example of running just one command - `openshift-install create cluster`. Does this command not work with vmware? Is it not possible to condense the list of commands into a single command?

The vmware is what we call, a user-provisioned infra installation, and therefore, the users need to use external tools to create the infra necessary for the cluster.

/close
