### ISSUE TITLE
initializing terraform for vSphere UPI  fails with latest terraform version

### ISSUE THREAD

**Issue by vavuthu** [openshift/installer#2260]
Initialize terraform for vSphere UPI  fails with latest terraform version

# Version

```
$ ./terraform version
Terraform v0.12.7
$
```

# Platform:
vSphere UPI
-->

# What happened?

```
$ ./terraform init .
Initializing modules...
- bootstrap in machine
- compute in machine
- control_plane in machine
- dns in route53
- folder in folder
- resource_pool in resource_pool
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid argument name

  on machine/main.tf line 47, in resource "vsphere_virtual_machine" "vm":
  47:       "guestinfo.ignition.config.data"          = "${base64encode(data.ignition_config.ign.*.rendered[count.index])}"

Argument names must not be quoted.
$ 
```

# What you expected to happen?

Initialization should happen without any errors

# How to reproduce it (as minimally and precisely as possible)?

Always

**Comment by DanyC97** [comment]
@vavuthu any chance you searched/ checked to see if an existing issue was already open?

Fyi others already opened [here](https://github.com/openshift/installer/pull/2185) and [here](https://github.com/openshift/installer/issues/2183) and the answer relies on the open PR https://github.com/openshift/installer/pull/2057 which will be accepted by RH team after the code freeze.

@abhinavdahiya can you please close this issue as a duplicate, thanks

**Comment by vavuthu** [comment]
closing this bug as duplicate ( #2183  )

**Comment by vavuthu** [comment]
closing this bug as duplicate ( #2183  )
