### ISSUE TITLE
Install OCP4.1 with sourcecode from release-4.1 not possible: manifest unknown

### ISSUE THREAD

**Issue by mcpdev80** [openshift/installer#2268]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-1006-gadb76eb637501b41c530ca4a7e5326b54776b44f
built from commit adb76eb637501b41c530ca4a7e5326b54776b44f
release image registry.svc.ci.openshift.org/origin/release:v4.1
```

# Platform:
AWS

# What happened?

I tried to install Openshift 4.1 on two different AWS accounts with the git branch release-4.1. Unfortunately, an installation with the source code is not possible.

openshift-install.log:
time="2019-08-26T11:57:07Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.ocp41.sandbox506.opentlc.com:6443/version?timeout=32s: dial tcp 3.123.103.131:6443: connect: connection refused"                          time="2019-08-26T11:57:26Z" level=debug msg="Fetching \"Install Config\"..."                                                                                                                                                                 time="2019-08-26T11:57:26Z" level=debug msg="Loading \"Install Config\"..."                                                                                                                                                                  time="2019-08-26T11:57:26Z" level=debug msg="  Loading \"SSH Key\"..."                                                                                                                                                                       time="2019-08-26T11:57:26Z" level=debug msg="  Using \"SSH Key\" loaded from state file"                                                                                                                                                     time="2019-08-26T11:57:26Z" level=debug msg="  Loading \"Base Domain\"..."                                                                                                                                                                   time="2019-08-26T11:57:26Z" level=debug msg="    Loading \"Platform\"..."                                                                                                                                                                    time="2019-08-26T11:57:26Z" level=debug msg="    Using \"Platform\" loaded from state file"                                                                                                                                                  time="2019-08-26T11:57:26Z" level=debug msg="  Using \"Base Domain\" loaded from state file"                                                                                                                                                 time="2019-08-26T11:57:26Z" level=debug msg="  Loading \"Cluster Name\"..."                                                                                                                                                                  time="2019-08-26T11:57:26Z" level=debug msg="    Loading \"Base Domain\"..."                                                                                                                                                                 time="2019-08-26T11:57:26Z" level=debug msg="  Using \"Cluster Name\" loaded from state file"                                                                                                                                                time="2019-08-26T11:57:26Z" level=debug msg="  Loading \"Pull Secret\"..."                                                                                                                                                                   time="2019-08-26T11:57:26Z" level=debug msg="  Using \"Pull Secret\" loaded from state file"                                                                                                                                                 time="2019-08-26T11:57:26Z" level=debug msg="  Loading \"Platform\"..."                                                                                                                                                                      time="2019-08-26T11:57:26Z" level=debug msg="Using \"Install Config\" loaded from state file"                                                                                                                                                time="2019-08-26T11:57:26Z" level=debug msg="Reusing previously-fetched \"Install Config\""                                                                                                                                                  time="2019-08-26T11:57:26Z" level=info msg="Make sure ssh-agent is running, env SSH_AUTH_SOCK is set to the ssh-agent's UNIX socket and your private key is added to the agent."                                                             time="2019-08-26T11:57:26Z" level=info msg="Use the following commands to gather logs from the cluster"                                                                                                                                      time="2019-08-26T11:57:26Z" level=info msg="ssh -A core@54.93.240.77 '/usr/local/bin/installer-gather.sh 10.0.140.131 10.0.149.86 10.0.175.138'"                                                                                             time="2019-08-26T11:57:26Z" level=info msg="scp core@54.93.240.77:~/log-bundle.tar.gz ."                                                                                                                                                     time="2019-08-26T11:57:26Z" level=fatal msg="waiting for Kubernetes API: context deadline exceeded"

Journalctl from Bootstap:
  -- Logs begin at Mon 2019-08-26 11:26:36 UTC. --
Aug 26 12:04:37 ip-10-0-0-131 systemd[1]: bootkube.service: Main process exited, code=exited, status=125/n/a
Aug 26 12:04:37 ip-10-0-0-131 systemd[1]: bootkube.service: Failed with result 'exit-code'.
Aug 26 12:04:42 ip-10-0-0-131 systemd[1]: bootkube.service: Service RestartSec=5s expired, scheduling restart.
Aug 26 12:04:42 ip-10-0-0-131 systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 107.
Aug 26 12:04:42 ip-10-0-0-131 systemd[1]: Stopped Bootstrap a Kubernetes cluster.
Aug 26 12:04:42 ip-10-0-0-131 systemd[1]: Started Bootstrap a Kubernetes cluster.
Aug 26 12:04:57 ip-10-0-0-131 bootkube.sh[31510]: Rendering cluster config manifests...
Aug 26 12:04:59 ip-10-0-0-131 bootkube.sh[31510]: unable to pull registry.svc.ci.openshift.org/origin/4.1-2019-05-13-204940@sha256:2052e13f8a6e1ce52f9f719b05e0cf4f694079295bd0e6e4aa95c37eab4c0192: unable to pull image: Error determining manifest MIME type for docker://registry.svc.ci.openshift.org/origin/4.1-2019-05-13-204940@sha256:2052e13f8a6e1ce52f9f719b05e0cf4f694079295bd0e6e4aa95c37eab4c0192: Error reading manifest sha256:2052e13f8a6e1ce52f9f719b05e0cf4f694079295bd0e6e4aa95c37eab4c0192 in registry.svc.ci.openshift.org/origin/4.1-2019-05-13-204940: manifest unknown: manifest unknown

# What you expected to happen?

Install OCP4.1

# How to reproduce it (as minimally and precisely as possible)?

I checked it with two different accounts from aws.

openshift-install create cluster --dir $HOME/ocp41 --log-level debug

# Anything else we need to know?

I tried also to use the branch master and edit the release Version to stable-4.1 in:
pkg/asset/releaseimage/default.go = http://registry.svc.ci.openshift.org/origin/release:4.1
data/data/manifests/bootkube/cvo-overrides.yaml.template = stable-4.1

Result: Error: unknown flag: --machine-config-operator-image

**Comment by mcpdev80** [comment]
Hi yes, see:
https://github.com/openshift/installer/pull/2267

**Comment by mcpdev80** [comment]
Is it possible to install OCP4.1 with the master? 
If please tell me how because I have tried different solutions:
Like:
pkg/asset/releaseimage/default.go = http://registry.svc.ci.openshift.org/origin/release:4.1
data/data/manifests/bootkube/cvo-overrides.yaml.template = stable-4.1
and:
OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/openshift-release-dev/ocp-release:4.1.11

But both doesn't work!

**Comment by wking** [comment]
Consensus is to use pinned 4.1.z releases and develop in master.

/close
