### ISSUE TITLE
SSH connection refused by bootstrap aws node

### ISSUE THREAD

**Issue by Jabulisile** [openshift/installer#2273]
# Version

```console
$ openshift-install version
./openshift-install v4.1.4-201906271212-dirty
built from commit ca5d270bc8d554496f0aa1073bdaa67adf01a25a
release image quay.io/openshift-release-dev/ocp-release@sha256:a6c177eb007d20bb00bfd8f829e99bd40137167480112bd5ae1c25e40a4a163a
```

# Platform:

# What happened?

Creating the bootstrap node via cloudformation succeeds but the instance is immediately unnreachable via ssh.

ssh core@xx.xx.xx.xx -vvv
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/wilfredm/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: /etc/ssh/ssh_config line 52: Applying options for *
debug2: resolve_canonicalize: hostname 18.203.137.152 is address
debug2: ssh_connect_direct
debug1: Connecting to xx.xx.xx.xx port 22.
debug1: connect to address xx.xx.xx.xx port 22: Connection refused
ssh: connect to host xx.xx.xx.xx port 22: Connection refused 

curl --insecure --cert tls/journal-gatewayd.crt  --key tls/journal-gatewayd.key 'https://xx.xx.xx.xx:19531/entries?follow&_SYSTEMD_UNIT=bootkube.service'
curl: (7) Failed to connect to xx.xx.xx.xx port 19531: Connection refused

Install log attached. 

# What you expected to happen?

For bootstrap node to be created and reachable.

# How to reproduce it (as minimally and precisely as possible)?

```console
./openshift-install create install-config --dir=custom_install
aws cloudformation create-stack --stack-name ocp-bootstrap-template-`date +%H%M%S` --template-body file:///ocp_bootstrap_template.yaml --parameters file:///ocp_bootstrap_params.json --capabilities CAPABILITY_NAMED_IAM
```

[ocp_bootstrap_params.json.log](https://github.com/openshift/installer/files/3547265/ocp_bootstrap_params.json.log)
[ocp_bootstrap_template.yaml.log](https://github.com/openshift/installer/files/3547267/ocp_bootstrap_template.yaml.log)
[.openshift_install.log](https://github.com/openshift/installer/files/3547270/default.openshift_install.log)

**Comment by abhinavdahiya** [comment]
Please feel free to reopen if there error still happens and you have the debugging bundles

/close
