### ISSUE TITLE
TAGS=libvirt hack/build.sh

### ISSUE THREAD

**Issue by deanpeterson** [openshift/installer#2278]
I receive the following error: 

++ go env GOPATH
+ echo 'build from your ${GOPATH} (/root/go/src/installer is not in /root/go)'
build from your ${GOPATH} (/root/go/src/installer is not in /root/go)
+ exit 1

I have set the GOPATH every way I can imagine. Building Go files works on the terminal but the build.sh script is unable to recognize it is, in fact on the go path.

**Comment by miiraheart** [comment]
Hello, I'm facing the same issue although I have the directory at $GOPATH/src/github.com/openshift/installer
