### ISSUE TITLE
Package libvirt was not found in the pkg-config search path

### ISSUE THREAD

**Issue by deanpeterson** [openshift/installer#2280]
I get the following error trying to run:
TAGS=libvirt hack/build.sh

Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libvirt', required by 'virtual:world', not found
Package 'libvirt', required by 'virtual:world', not found
.
.
.
Package 'libvirt', required by 'virtual:world', not found
Package 'libvirt', required by 'virtual:world', not found
pkg-config: exit status 1

I am on the latest version of RHEL 8

**Comment by DirectedSoul1** [comment]
Thanks this solved my issue
