### ISSUE TITLE
baremetal: bootstrap VM using old version of ironic

### ISSUE THREAD

**Issue by hardys** [openshift/installer#2282]
Since #2234 landed we're seeing issues starting ironic-inspector on the bootstrap VM, we can see the image referenced is:
```
Aug 28 08:51:17 localhost startironic.sh[1972]: + IRONIC_INSPECTOR_IMAGE=registry.svc.ci.openshift.org/origin/4.2-2019-08-28-054558@sha256:2cf170cc3e
6dad9c9bae32dea3a82267530a8d02742d16e865bb9d8b2fc7653f
```

However attempts to start the ironic-inspector container fail like this, indicating that it's an old version of ironic:

```
[core@localhost ~]$ sudo podman logs ironic-inspector | grep ConfigFileValueError
2019-08-28 09:34:13.447 1 CRITICAL ironic_inspector [-] Unhandled error: ConfigFileValueError: Value for option store_data is not valid: Valid values are [none, swift], but found 'database'
2019-08-28 09:34:13.447 1 ERROR ironic_inspector ConfigFileValueError: Value for option store_data is not valid: Valid values are [none, swift], but found 'database'
```

This has already been discussed in https://github.com/openshift/ironic-inspector-image/pull/17, and with the nightly release payload we've previously been getting an ART build (which contains the right version of ironic), vs a CI build (which currently does not ref openshift/release#4835 openshift/release#4836 openshift/release#4837)

On the cluster we were getting an image from quay.io/openshift-release-dev/ocp-v4.0-art-dev - this was tested and proven to work OK, hence the revert in https://github.com/openshift/ironic-inspector-image/pull/17 - it seems like we may have to re-revert that, but it breaks introspection and prevents any testing of workers, so not ideal

**Comment by hardys** [comment]
cc @stbenjam @elfosardo

**Comment by yprokule** [comment]
Looks like that's due to `{{.ReleaseImage}}` from **data/data/bootstrap/files/usr/local/bin/release-image.sh.template** being resolved to `registry.svc.ci.openshift.org/origin/release:4.2` and I thought it should be `registry.svc.ci.openshift.org/ocp/release:4.2`

**Comment by hardys** [comment]
Ok I think this is actually due to  https://github.com/openshift-metal3/dev-scripts/commit/65a987c74fb6363892c6fb1114009fdbccdba5dd#diff-2407feeeedf4de6f5b077ee1746f344b - we still need to set OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE or the installer uses the default (origin) pullspec

**Comment by hardys** [comment]
Closing, we'll track this via https://github.com/openshift-metal3/dev-scripts/issues/775
