### ISSUE TITLE
Documentation is not friendly

### ISSUE THREAD

**Issue by gswallow** [openshift/installer#2285]
# Version
None.  Still working on an install.

# Platform:
UPI on vsphere

# What happened?
The documentation, particularly the section on platform customization, is poor.

https://github.com/openshift/installer/blob/master/docs/user/customization.md#platform-customization

I'm instructed to read Go docs.  I can figure it out but c'mon.  Do better.

# What you expected to happen?
I expect to read a table in markdown format explaining how to create an install-config.yaml file.

# How to reproduce it (as minimally and precisely as possible)?
Read the docs.

**Comment by wking** [comment]
A few points:

* #2162 is a WIP in flight to give you Markdown docs.
* Installer-repo docs are unofficial.
    * [Here][1] are the official vSphere docs.  Better, but still not perfect.
    * [Here][2] are the official AWS docs, with the non-godoc detail we all aspire too.
* PRs welcome, if you can't wait for us to fix things ourselves :)
* Dunno what's going on with the vSphere wizard; I'll look later.

[1]: https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-config-yaml_installing-vsphere
[2]: https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-customizations.html#installation-configuration-parameters_install-customizations-cloud

**Comment by gswallow** [comment]
Thanks! 

My Golang skill are non-existent or I'd submit a PR.

**Comment by wking** [comment]
No Go required to fill in the Markdown docs you're asking for?

**Comment by gswallow** [comment]
Well I can do that!  I'll take a closer look.

I thought it'd be Go tooling to automatically fill out markdown docs.
