### ISSUE TITLE
100% complete, waiting on authentication, console

### ISSUE THREAD

**Issue by deanpeterson** [openshift/installer#2287]
I get the following error installing with libvirt settings:

FATAL failed to initialize the cluster: Working towards 4.2.0-0.okd-2019-08-29-022631: 100% complete, waiting on authentication, console

I am using a RHEL 8 host machine.

**Comment by wking** [comment]
Attach `oc adm must-gather` logs?

**Comment by rphillips** [comment]
There are some special DNS settings you need for the console. Are these settings setup?

[troubleshooting](https://github.com/openshift/installer/tree/master/docs/dev/libvirt#console-doesnt-come-up)

**Comment by deanpeterson** [comment]
> There are some special DNS settings you need for the console. Are these settings setup?
> 
> [troubleshooting](https://github.com/openshift/installer/tree/master/docs/dev/libvirt#console-doesnt-come-up)

I followed the instructions at the time and did this: 

echo server=/abecorn.enterprisewebservice/192.168.126.1 | sudo tee /etc/NetworkManager/dnsmasq.d/openshift.conf

how will adding address=/.apps.abecorn.enterprisewebservice/192.168.126.51 help?

How will I know the worker node will get 192.168.126.51 as its ip?

**Comment by deanpeterson** [comment]
> Attach `oc adm must-gather` logs?

I have no idea how to do this if I don't have an actual functioning cluster

**Comment by deanpeterson** [comment]
> Attach `oc adm must-gather` logs?

`2019/08/30 05:08:45 Finished successfully with no errors.
2019/08/30 05:08:46 Gathering data for ns/openshift-cluster-version...
2019/08/30 05:08:46     Collecting resources for namespace "openshift-cluster-version"...
2019/08/30 05:08:46     Gathering pod data for namespace "openshift-cluster-version"...
2019/08/30 05:08:46         Gathering data for pod "cluster-version-operator-6c47bf78cd-xplhp"
2019/08/30 05:08:48         Unable to gather previous container logs: previous terminated container "cluster-version-operator" in pod "cluster-version-operator-6c47bf78cd-xplhp" not found
2019/08/30 05:08:48         Skipping container endpoint collection for pod "cluster-version-operator-6c47bf78cd-xplhp" container "cluster-version-operator": No ports
2019/08/30 05:08:55 Finished successfully with no errors.
2019/08/30 05:08:55 Gathering config.openshift.io resource data...
2019/08/30 05:08:57 Gathering kubeapiserver.operator.openshift.io resource data...
2019/08/30 05:08:57 Gathering cluster operator resource data...
2019/08/30 05:08:57     Gathering related object reference information for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "authentications.operator.openshift.io/cluster" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "authentications.config.openshift.io/cluster" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "infrastructures.config.openshift.io/cluster" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "oauths.config.openshift.io/cluster" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "namespaces/openshift-config" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "namespaces/openshift-config-managed" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "namespaces/openshift-authentication" for ClusterOperator "authentication"...
2019/08/30 05:08:57     Found related object "namespaces/openshift-authentication-operator" for ClusterOperator "authentication"...
2019/08/30 05:09:21 Gathering data for ns/openshift-config...
2019/08/30 05:09:21     Collecting resources for namespace "openshift-config"...
2019/08/30 05:09:21     Gathering pod data for namespace "openshift-config"...
2019/08/30 05:09:27 Gathering data for ns/openshift-config-managed...
2019/08/30 05:09:27     Collecting resources for namespace "openshift-config-managed"...
2019/08/30 05:09:27     Gathering pod data for namespace "openshift-config-managed"...
2019/08/30 05:09:35 Gathering data for ns/openshift-authentication...
2019/08/30 05:09:36     Collecting resources for namespace "openshift-authentication"...
2019/08/30 05:09:36     Gathering pod data for namespace "openshift-authentication"...
2019/08/30 05:09:36         Gathering data for pod "oauth-openshift-75d8969cb-5k5rf"
2019/08/30 05:09:36         Skipping container data collection for pod "oauth-openshift-75d8969cb-5k5rf": Pod not running
2019/08/30 05:09:36         Gathering data for pod "oauth-openshift-75d8969cb-kqd26"
2019/08/30 05:09:36         Skipping container data collection for pod "oauth-openshift-75d8969cb-kqd26": Pod not running
2019/08/30 05:09:36         Gathering data for pod "oauth-openshift-75d8969cb-sk2g6"
2019/08/30 05:09:36         Unable to gather previous container logs: previous terminated container "oauth-openshift" in pod "oauth-openshift-75d8969cb-sk2g6" not found
2019/08/30 05:09:37         Gathering data for pod "oauth-openshift-7cf95f4dbf-4qwzk"
2019/08/30 05:09:37         Skipping container data collection for pod "oauth-openshift-7cf95f4dbf-4qwzk": Pod not running
2019/08/30 05:09:42 Gathering data for ns/openshift-authentication-operator...
2019/08/30 05:09:42     Collecting resources for namespace "openshift-authentication-operator"...
2019/08/30 05:09:42     Gathering pod data for namespace "openshift-authentication-operator"...
2019/08/30 05:09:42         Gathering data for pod "authentication-operator-679d566b79-fkgkg"
2019/08/30 05:09:43         Unable to gather previous container logs: previous terminated container "operator" in pod "authentication-operator-679d566b79-fkgkg" not found
2019/08/30 05:09:43         Skipping container endpoint collection for pod "authentication-operator-679d566b79-fkgkg" container "operator": No ports
2019/08/30 05:09:52 Skipping previously-collected config.openshift.io resource data
2019/08/30 05:09:52 Skipping previously-collected operator.openshift.io resource data
2019/08/30 05:09:52 Gathering cluster operator resource data...
2019/08/30 05:09:52     Gathering related object reference information for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "namespaces/openshift-cloud-credential-operator" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/cloud-credential-operator-iam-ro" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-image-registry" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-image-registry-azure" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-image-registry-gcs" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-image-registry-openstack" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-ingress" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-ingress-azure" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-ingress-gcp" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-machine-api-aws" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-machine-api-azure" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-machine-api-gcp" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52     Found related object "CredentialsRequest.cloudcredential.openshift.io/openshift-machine-api-openstack" for ClusterOperator "cloud-credential"...
2019/08/30 05:09:52 Gathering data for ns/openshift-cloud-credential-operator...
2019/08/30 05:09:52     Collecting resources for namespace "openshift-cloud-credential-operator"...
2019/08/30 05:09:52     Gathering pod data for namespace "openshift-cloud-credential-operator"...
2019/08/30 05:09:52         Gathering data for pod "cloud-credential-operator-5d5b8c86d8-w7pdq"
E0830 05:09:53.545516      32 portforward.go:331] an error occurred forwarding 37587 -> 9876: error forwarding port 9876 to pod 6a530e88bfc54c37d8e9733ae10e500114fa00e3bae5aa0ce33fd0aff3c3dadc, uid : exit status 1: 2019/08/30 05:09:53 socat[18923] E connect(5, AF=2 127.0.0.1:9876, 16): Connection refused
E0830 05:09:53.693908      32 portforward.go:331] an error occurred forwarding 37587 -> 9876: error forwarding port 9876 to pod 6a530e88bfc54c37d8e9733ae10e500114fa00e3bae5aa0ce33fd0aff3c3dadc, uid : exit status 1: 2019/08/30 05:09:53 socat[18939] E connect(5, AF=2 127.0.0.1:9876, 16): Connection refused
E0830 05:09:53.772836      32 portforward.go:331] an error occurred forwarding 37587 -> 9876: error forwarding port 9876 to pod 6a530e88bfc54c37d8e9733ae10e500114fa00e3bae5aa0ce33fd0aff3c3dadc, uid : exit status 1: 2019/08/30 05:09:53 socat[18946] E connect(5, AF=2 127.0.0.1:9876, 16): Connection refused
2019/08/30 05:11:30 Skipping previously-collected config.openshift.io resource data
2019/08/30 05:11:30 Skipping previously-collected operator.openshift.io resource data
2019/08/30 05:11:30 Gathering cluster operator resource data...
2019/08/30 05:11:30     Gathering related object reference information for ClusterOperator "cluster-autoscaler"...
2019/08/30 05:11:30     Found related object "namespaces/openshift-machine-api" for ClusterOperator "cluster-autoscaler"...
2019/08/30 05:11:30 Gathering data for ns/openshift-machine-api...
2019/08/30 05:11:30     Collecting resources for namespace "openshift-machine-api"...
2019/08/30 05:11:30     Gathering pod data for namespace "openshift-machine-api"...
2019/08/30 05:11:30         Gathering data for pod "cluster-autoscaler-operator-56fd4f8b66-zrhwt"
2019/08/30 05:11:30         Unable to gather previous container logs: previous terminated container "cluster-autoscaler-operator" in pod "cluster-autoscaler-operator-56fd4f8b66-zrhwt" not found
2019/08/30 05:11:31         Gathering data for pod "machine-api-controllers-64976d866f-txhbs"
2019/08/30 05:11:31         Unable to gather previous container logs: previous terminated container "controller-manager" in pod "machine-api-controllers-64976d866f-txhbs" not found
2019/08/30 05:11:31         Skipping container endpoint collection for pod "machine-api-controllers-64976d866f-txhbs" container "controller-manager": No ports
2019/08/30 05:11:31         Unable to gather previous container logs: previous terminated container "machine-controller" in pod "machine-api-controllers-64976d866f-txhbs" not found
2019/08/30 05:11:31         Skipping container endpoint collection for pod "machine-api-controllers-64976d866f-txhbs" container "machine-controller": No ports
2019/08/30 05:11:31         Unable to gather previous container logs: previous terminated container "nodelink-controller" in pod "machine-api-controllers-64976d866f-txhbs" not found
2019/08/30 05:11:31         Skipping container endpoint collection for pod "machine-api-controllers-64976d866f-txhbs" container "nodelink-controller": No ports
2019/08/30 05:11:31         Gathering data for pod "machine-api-operator-594fcb5d95-jzg8d"
E0830 05:11:31.767315      32 portforward.go:316] error copying from local connection to remote stream: EOF
2019/08/30 05:11:38 Skipping previously-collected config.openshift.io resource data
2019/08/30 05:11:38 Skipping previously-collected operator.openshift.io resource data
2019/08/30 05:11:38 Gathering cluster operator resource data...
2019/08/30 05:11:38     Gathering related object reference information for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "consoles.operator.openshift.io/cluster" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "consoles.config.openshift.io/cluster" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "infrastructures.config.openshift.io/cluster" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "proxies.config.openshift.io/cluster" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "oauthclients.oauth.openshift.io/console" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "namespaces/openshift-console-operator" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "namespaces/openshift-console" for ClusterOperator "console"...
2019/08/30 05:11:38     Found related object "configmaps/console-public" for ClusterOperator "console"...
2019/08/30 05:12:11 Gathering data for ns/openshift-console-operator...
2019/08/30 05:12:11     Collecting resources for namespace "openshift-console-operator"...
2019/08/30 05:12:11     Gathering pod data for namespace "openshift-console-operator"...
2019/08/30 05:12:11         Gathering data for pod "console-operator-7cbbf95d76-jw97k"
2019/08/30 05:12:11         Skipping container data collection for pod "console-operator-7cbbf95d76-jw97k": Pod not running
2019/08/30 05:12:11         Gathering data for pod "console-operator-7cbbf95d76-l97nx"
2019/08/30 05:12:11         Unable to gather previous container logs: previous terminated container "console-operator" in pod "console-operator-7cbbf95d76-l97nx" not found
E0830 05:12:11.740802      32 portforward.go:331] an error occurred forwarding 37587 -> 60000: error forwarding port 60000 to pod 1688a29a8ee99a95337095c9b1bda4e8b7f0e7df8b2e8d256e19a74f822c1497, uid : exit status 1: 2019/08/30 05:12:11 socat[23922] E connect(5, AF=2 127.0.0.1:60000, 16): Connection refused
E0830 05:12:11.804787      32 portforward.go:331] an error occurred forwarding 37587 -> 60000: error forwarding port 60000 to pod 1688a29a8ee99a95337095c9b1bda4e8b7f0e7df8b2e8d256e19a74f822c1497, uid : exit status 1: 2019/08/30 05:12:11 socat[23929] E connect(5, AF=2 127.0.0.1:60000, 16): Connection refused
E0830 05:12:11.866803      32 portforward.go:331] an error occurred forwarding 37587 -> 60000: error forwarding port 60000 to pod 1688a29a8ee99a95337095c9b1bda4e8b7f0e7df8b2e8d256e19a74f822c1497, uid : exit status 1: 2019/08/30 05:12:11 socat[23936] E connect(5, AF=2 127.0.0.1:60000, 16): Connection refused
2019/08/30 05:12:17 Gathering data for ns/openshift-console...
2019/08/30 05:12:17     Collecting resources for namespace "openshift-console"...
2019/08/30 05:12:17     Gathering pod data for namespace "openshift-console"...
2019/08/30 05:12:17         Gathering data for pod "console-6d96fdb575-42cr5"
2019/08/30 05:12:17         Skipping container data collection for pod "console-6d96fdb575-42cr5": Pod not running
2019/08/30 05:12:17         Gathering data for pod "console-6d96fdb575-jfqfp"
2019/08/30 05:12:17         Skipping container data collection for pod "console-6d96fdb575-jfqfp": Pod not running
2019/08/30 05:12:17         Gathering data for pod "console-8444846b74-cfrhh"
2019/08/30 05:12:17         Skipping container data collection for pod "console-8444846b74-cfrhh": Pod not running
2019/08/30 05:12:17         Gathering data for pod "downloads-f9ff65658-b5pw7"
2019/08/30 05:12:17         Unable to gather previous container logs: previous terminated container "download-server" in pod "downloads-f9ff65658-b5pw7" not found
2019/08/30 05:12:17         Gathering data for pod "downloads-f9ff65658-lhfvx"
2019/08/30 05:12:17         Unable to gather previous container logs: previous terminated container "download-server" in pod "downloads-f9ff65658-lhfvx" not found
E0830 05:12:17.598841      32 portforward.go:316] error copying from local connection to remote stream: tls: use of closed connection
2019/08/30 05:12:22 Skipping previously-collected config.openshift.io resource data
2019/08/30 05:12:22 Skipping previously-collected operator.openshift.io resource data
2019/08/30 05:12:22 Gathering cluster operator resource data...
2019/08/30 05:12:22     Gathering related object reference information for ClusterOperator "dns"...
2019/08/30 05:12:22     Found related object "namespaces/openshift-dns-operator" for ClusterOperator "dns"...
2019/08/30 05:12:22     Found related object "namespaces/openshift-dns" for ClusterOperator "dns"...
2019/08/30 05:12:22     Found related object "DNS.operator.openshift.io/default" for ClusterOperator "dns"...
2019/08/30 05:12:22 Gathering data for ns/openshift-dns-operator...
2019/08/30 05:12:22     Collecting resources for namespace "openshift-dns-operator"...
2019/08/30 05:12:22     Gathering pod data for namespace "openshift-dns-operator"...
2019/08/30 05:12:22         Gathering data for pod "dns-operator-7d7964d5c-92ttg"
2019/08/30 05:12:22         Unable to gather previous container logs: previous terminated container "dns-operator" in pod "dns-operator-7d7964d5c-92ttg" not found
2019/08/30 05:12:22         Skipping container endpoint collection for pod "dns-operator-7d7964d5c-92ttg" container "dns-operator": No ports
2019/08/30 05:12:33 Gathering data for ns/openshift-dns...
2019/08/30 05:12:33     Collecting resources for namespace "openshift-dns"...
2019/08/30 05:12:33     Gathering pod data for namespace "openshift-dns"...
2019/08/30 05:12:33         Gathering data for pod "dns-default-fc9v6"
2019/08/30 05:12:33         Unable to gather previous container logs: previous terminated container "dns" in pod "dns-default-fc9v6" not found
2019/08/30 05:12:40         Unable to gather previous container logs: previous terminated container "dns-node-resolver" in pod "dns-default-fc9v6" not found
2019/08/30 05:12:40         Skipping container endpoint collection for pod "dns-default-fc9v6" container "dns-node-resolver": No ports
2019/08/30 05:12:40         Gathering data for pod "dns-default-xm2qs"
2019/08/30 05:12:40         Unable to gather previous container logs: previous terminated container "dns" in pod "dns-default-xm2qs" not found`

**Comment by wking** [comment]
Hmm.  Looks like some of that succeeded and a bunch failed.  Did it create a tarball/

**Comment by wking** [comment]
Also, what's the cluster ID from `install-dir/metadata.json`?    Maybe some Telemetry is making it out.

**Comment by deanpeterson** [comment]
> Also, what's the cluster ID from `install-dir/metadata.json`? Maybe some Telemetry is making it out.

{"clusterName":"ocp","clusterID":"a9c25afa-568b-4a7a-88d4-22de58a1987a","infraID":"ocp-n76nx","libvirt":{"uri":"qemu+tcp://192.168.122.1/system"}}

**Comment by deanpeterson** [comment]
> Hmm. Looks like some of that succeeded and a bunch failed. Did it create a tarball/

Where would the tarball be? It's definitely not on the host machine where I ran the oc adm must-gather command.

**Comment by wking** [comment]
Tarball would have been on the installer machine.  Seems like your cluster is too broken to get the tarball off the cluster and back to your installer machine (`rsync: connection unexpectedly closed`).

Looking at metrics from your cluster, there are all sorts of alerts firing, including `KubeCPUOvercommit`, `KubeMemOvercommit`, `KubePodCrashLooping`, and `etcdHighCommitDurations`.  I suspect you have underprovisioned your control plane machines, and the cluster components there are all gasping for resources.  #2258 has some discussion about possibly bumping our defaults (as we've done before in #1279 and similar).

**Comment by deanpeterson** [comment]
Interesting. I will modify the defaults. Just an fyi, following the [Libvirt Instructions](https://github.com/openshift/installer/blob/4a97eccab5e432a1318d15ff064ede78dca05d4a/docs/dev/libvirt/README.md) did not indicate needing to set cpu/memory. So, I am using the defaults but the machine I am using is a dual socket xeon with 24 cores and 64 GB of ram. If the defaults don't work on that machine wouldn't that tutorial fail for most everyone?

**Comment by deanpeterson** [comment]
What isn't entirely clear, if I'm following [Libvirt Instructions](https://github.com/openshift/installer/blob/4a97eccab5e432a1318d15ff064ede78dca05d4a/docs/dev/libvirt/README.md), do I still have to do prerequisites like set up an http server to host ignition files and rchos images? Or is all of that unnecessary when doing the libvirt install?

**Comment by simon3z** [comment]
@wking I am hitting this as well with machines of 12Gb each (master and worker). This issue doesn't seem related to underprovisioned VMs (unless for some reason the system believes to be underprovisioned) as there are 4-6Gb still free when the error occurs.

I cannot provide the must-gather feedback but on the other hand this is 100% reproducible ATM.

**Comment by wking** [comment]
I dunno.  Getting logs from the pod in the `openshift-cluster-version` namespace might help.  `oc get -o yaml clusteroperators` and `oc get -o yaml --all-namespaces pods` might help.  Logs from pods in the `  openshift-authentication-operator` and `openshift-console-operator ` namespaces might help.  Hopefully those complete fast enough

**Comment by deanpeterson** [comment]
I'm thinking without better understanding of what the requirements are it could be any number of things. I am most likely going to have to do the bare metal install with kvm and libvirt from scratch rather than use the dev / libvirt tutorial and scripts. That way I'll have a much better understanding where I might be going wrong. In fact, I only did the dev / libvirt process after trying to follow a number of tutorials online about how to get the bare metal install process to work with kvm and libvirt. Then, I found the github libvirt readme thinking the process had been streamlined. I didn't realize it was an entirely different process designed just for low powered dev machines. I will say the new 4.X install UPI has quite a learning curve for less operational type app/dev - middleware folks like myself, I have installed Openshift 3.X a number of times and that was easier for me. I think the biggest hurdle is some of the assumption the 4.X documentation makes about setting up DNS requirements. I have read a number of tutorials, and they all make different recommendations and jump between running a separate VM dedicated to DNS  with dnsmasq or Bind (will have to read up what the actual right way is or if any of that is in fact necessary) to the libvirt tutorial saying I just have to run some one line command to set things manually to get around dns wildcard limitations. That is all highly confusing at the moment. I am actually a new Middleware SA for Red Hat. My plan is to get this working and do a painstakingly detailed video tutorial on how to install Openshift 4.X. Eventually things will click but right now, I am quite confused as I have not learned the CoreOS way yet.

**Comment by wking** [comment]
Have you tried the [official 4.1 baremetal docs][1]?  Using the official flow with a stable 4.1 release is going to be more reliable than any workflow with a 4.2 nightly.


[1]: https://docs.openshift.com/container-platform/4.1/installing/installing_bare_metal/installing-bare-metal.html#installing-bare-metal

**Comment by deanpeterson** [comment]
> Have you tried the [official 4.1 baremetal docs](https://docs.openshift.com/container-platform/4.1/installing/installing_bare_metal/installing-bare-metal.html#installing-bare-metal)? Using the official flow with a stable 4.1 release is going to be more reliable than any workflow with a 4.2 nightly.

I have kind of tried to do that but then I went to on-line blogs to help me understand the pre reqs a bit better and ended up confusing myself more it seems. I will see if I can figure it out just using the documentation. Being a middleware - app/dev guy some of pre reqs (especially around DNS) are still a bit fuzzy  to me and I was looking for a short cut. Lesson learned.

**Comment by wking** [comment]
Installer-provisioning for AWS is probably the simplest approach.  But there's always room for improvement; let us know if/where you get stuck in any flow.

**Comment by wking** [comment]
And, for what it's worth, the libvirt CI jobs are generally making it through setup (and then failing to pass the e2e suite): https://ci-search-ci-search-next.svc.ci.openshift.org/chart?name=libvirt&search=failed%20to%20initialize%20the%20cluster

**Comment by deanpeterson** [comment]
I was finally successful. I created a video tutorial to help anyone else trying to get through the gotchas I ran into:
https://youtu.be/qj4tLuPPClg

**Comment by zeenix** [comment]
> I was finally successful. I created a video tutorial to help anyone else trying to get through the gotchas I ran into:

Thanks for keeping us updated and also making a video. Could you please summarize what was it in the end? Did you just miss something in the docs?

**Comment by deanpeterson** [comment]
> > I was finally successful. I created a video tutorial to help anyone else trying to get through the gotchas I ran into:
> 
> Thanks for keeping us updated and also making a video. Could you please summarize what was it in the end? Did you just miss something in the docs?

It was a few things:
1. The part in the troubleshooting section about modifying openshift.conf to get around the dns wildcard issue should probably just go right in the main instructions section of the libvirt howto. It should be more clear generating the manifests first and then running that sed command is an important step.
2. It helped quite a bit to update the default vm sizing to 16 gigs and 8 vcpu.
3. There should be a reminder to generate an ssh key prior to generating the manifests. I was on a fresh machine and the cli would just skip past setting or asking about the ssh key when one didn't exist. Once I generated that, the cli then asked me about using it.
4. The error messages in the openshift_install.log while things are coming up are scary. Unless you spend some time looking at issues in github, it's easy to just think things are really messed up rather than realize the errors are continued checks to probe running components.

**Comment by ssbano** [comment]
@deanpeterson 

Great job !! but you can set dns (bind - bare metal) to resolve the * .apps.${domain} and i made some changes below

1) 
```
[root@argon ~]# cat /etc/NetworkManager/dnsmasq.d/openshift.conf 
server=/jaguar.fsbano.com/192.168.126.1
server=/apps.jaguar.fsbano.com/172.27.15.30
[root@argon ~]# 
```

2)
git diff 

```
diff --git a/cmd/openshift-install/create.go b/cmd/openshift-install/create.go
index 9021025b6..679649d1d 100644
--- a/cmd/openshift-install/create.go
+++ b/cmd/openshift-install/create.go
@@ -238,7 +238,7 @@ func waitForBootstrapComplete(ctx context.Context, config *rest.Config, director
 
        discovery := client.Discovery()
 
-       apiTimeout := 30 * time.Minute
+       apiTimeout := 60 * time.Minute
        logrus.Infof("Waiting up to %v for the Kubernetes API at %s...", apiTimeout, config.Host)
        apiContext, cancel := context.WithTimeout(ctx, apiTimeout)
        defer cancel()
@@ -279,7 +279,7 @@ func waitForBootstrapComplete(ctx context.Context, config *rest.Config, director
 // and waits for the bootstrap configmap to report that bootstrapping has
 // completed.
 func waitForBootstrapConfigMap(ctx context.Context, client *kubernetes.Clientset) error {
-       timeout := 30 * time.Minute
+       timeout := 60 * time.Minute
        logrus.Infof("Waiting up to %v for bootstrapping to complete...", timeout)
 
        waitCtx, cancel := context.WithTimeout(ctx, timeout)
@@ -317,7 +317,7 @@ func waitForBootstrapConfigMap(ctx context.Context, client *kubernetes.Clientset
 // waitForInitializedCluster watches the ClusterVersion waiting for confirmation
[root@argon installer]# 
[root@argon installer]# git diff
diff --git a/cmd/openshift-install/create.go b/cmd/openshift-install/create.go
index 9021025b6..679649d1d 100644
--- a/cmd/openshift-install/create.go
+++ b/cmd/openshift-install/create.go
@@ -238,7 +238,7 @@ func waitForBootstrapComplete(ctx context.Context, config *rest.Config, director
 
        discovery := client.Discovery()
 
-       apiTimeout := 30 * time.Minute
+       apiTimeout := 60 * time.Minute
        logrus.Infof("Waiting up to %v for the Kubernetes API at %s...", apiTimeout, config.Host)
        apiContext, cancel := context.WithTimeout(ctx, apiTimeout)
        defer cancel()
@@ -279,7 +279,7 @@ func waitForBootstrapComplete(ctx context.Context, config *rest.Config, director
 // and waits for the bootstrap configmap to report that bootstrapping has
 // completed.
 func waitForBootstrapConfigMap(ctx context.Context, client *kubernetes.Clientset) error {
-       timeout := 30 * time.Minute
+       timeout := 60 * time.Minute
        logrus.Infof("Waiting up to %v for bootstrapping to complete...", timeout)
 
        waitCtx, cancel := context.WithTimeout(ctx, timeout)
@@ -317,7 +317,7 @@ func waitForBootstrapConfigMap(ctx context.Context, client *kubernetes.Clientset
 // waitForInitializedCluster watches the ClusterVersion waiting for confirmation
 // that the cluster has been initialized.
 func waitForInitializedCluster(ctx context.Context, config *rest.Config) error {
-       timeout := 30 * time.Minute
+       timeout := 60 * time.Minute
        logrus.Infof("Waiting up to %v for the cluster at %s to initialize...", timeout, config.Host)
        cc, err := configclient.NewForConfig(config)
        if err != nil {
diff --git a/data/data/libvirt/main.tf b/data/data/libvirt/main.tf
index 9ba88c9cf..152c78dd5 100644
--- a/data/data/libvirt/main.tf
+++ b/data/data/libvirt/main.tf
@@ -54,6 +54,11 @@ resource "libvirt_network" "net" {
   dns {
     local_only = true
 
+    forwarders { 
+        address = "172.27.15.30"
+        domain = "apps.${var.cluster_domain}"
+    }
+
     dynamic "srvs" {
       for_each = data.libvirt_network_dns_srv_template.etcd_cluster.*.rendered
       content {
diff --git a/data/data/libvirt/variables-libvirt.tf b/data/data/libvirt/variables-libvirt.tf
index 53cf68bae..79d1018e2 100644
--- a/data/data/libvirt/variables-libvirt.tf
+++ b/data/data/libvirt/variables-libvirt.tf
@@ -32,7 +32,7 @@ variable "libvirt_master_ips" {
 variable "libvirt_master_memory" {
   type        = string
   description = "RAM in MiB allocated to masters"
-  default     = "6144"
+  default     = "16384"
 }
 
 # At some point this one is likely to default to the number
diff --git a/pkg/asset/machines/libvirt/machines.go b/pkg/asset/machines/libvirt/machines.go
index 2ab6d9aa2..08847ab95 100644
--- a/pkg/asset/machines/libvirt/machines.go
+++ b/pkg/asset/machines/libvirt/machines.go
@@ -63,7 +63,7 @@ func provider(clusterID string, networkInterfaceAddress string, platform *libvir
                        APIVersion: "libvirtproviderconfig.openshift.io/v1beta1",
                        Kind:       "LibvirtMachineProviderConfig",
                },
-               DomainMemory: 7168,
+               DomainMemory: 16384,
                DomainVcpu:   4,
                Ignition: &libvirtprovider.Ignition{
                        UserDataSecret: userDataSecret,
[root@argon installer]# 
```

**Comment by ssbano** [comment]
@deanpeterson 

see - https://pbs.twimg.com/media/EFiKJ0OW4AAc4xn?format=png&name=large

Best Regards,
Fabio Sbano

**Comment by rthallisey** [comment]
@deanpeterson If you're still having this problem, here's a workaround: https://github.com/openshift/installer/issues/1648#issuecomment-585235423
