### ISSUE TITLE
ERROR failed to create SSH client, ensure the proper ssh key is in your keyring

### ISSUE THREAD

**Issue by burrsutter** [openshift/installer#2293]
# Version

```console
$ openshift-install version
built from commit c2e6b0afd7f33ae0125d1ac96f3948919748ffc5
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:22182e8e20f1127855e2ae9170f4f121d9c66d2574eb1d98d0c0398ac46b70b0
```

# Platform:
gcp

# What happened?
The docs do not tell the reader that they need to upload their ssh key into the GCP Metadata. 

# What you expected to happen?

# How to reproduce it (as minimally and precisely as possible)?
ssh-keygen -t rsa
./openshift-install using that generated key
but not yet having uploaded it via "gcloud" or the GCP UI

**Comment by abhinavdahiya** [comment]
You don't need to upload your keep anywhere. 

As long as you have provided the ssh key using the terminal prompts or using the install-config.yaml you'll be able to ssh as long as you have connectivity.

**Comment by sdodson** [comment]
This key only gets included in ignition assets and applied to the node once it applies those assets, it's not added to any cloud specific resources.
/close

**Comment by burrsutter** [comment]
I think the solution is "ssh-add -K whateverkey"

**Comment by sdodson** [comment]
This is covered in product docs already for AWS and will similarly be in the GCP docs when available.

https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default
