### ISSUE TITLE
GCP ServiceAccount Key Doc Bug

### ISSUE THREAD

**Issue by burrsutter** [openshift/installer#2294]
# Version

```console
$ openshift-install version
built from commit c2e6b0afd7f33ae0125d1ac96f3948919748ffc5
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:22182e8e20f1127855e2ae9170f4f121d9c66d2574eb1d98d0c0398ac46b70b0
```

# Platform:
gcp
# What happened?
The installer documentation should tell the reader that once they have downloaded the Service Account Key as a JSON file, that they will be prompted for that file during the installation process (e.g. ./openshift-install --dir=whatever create install-config)

note: this prompt is only done 1 time, it stops prompting on the 2nd and beyond execution of ./openshift-install (which I think is odd)

https://github.com/openshift/installer/blob/master/docs/user/gcp/install.md

**Comment by abhinavdahiya** [comment]
> The installer documentation should tell the reader that once they have downloaded the Service Account Key as a JSON file, that they will be prompted for that file during the installation process

Why? I don't think that very necessary as the prompt itself is clear enough.

If you have preferences we are open to PRs :)

/close
