### ISSUE TITLE
Dont remove install-config.yaml

### ISSUE THREAD

**Issue by kameshsampath** [openshift/installer#2299]
It will be nice not to remove the `install-config.yaml` post install, if the removal is required it will be better to rename it

# Version

```console
$ openshift-install version
/Users/kameshs/MyLabs/openshift/ocp42/openshift-install v4.2.0-201908251340-dirty
built from commit c2e6b0afd7f33ae0125d1ac96f3948919748ffc5
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:22182e8e20f1127855e2ae9170f4f121d9c66d2574eb1d98d0c0398ac46b70b0
```

# Platform:
aws,gcp and azure

# What happened?
install-config.yaml is removed

# What you expected to happen?

install-config.yaml is not deleted if needed renamed.

cc:@burrsutter

**Comment by wking** [comment]
Dup of #898.  Comment there if the earlier discussion missed anything ;).

/close
