### ISSUE TITLE
Azr destroy cluster Failed to destroy cluster: failed to delete public DNS records

### ISSUE THREAD

**Issue by burrsutter** [openshift/installer#2300]
# Version

```console
$ openshift-install version
built from commit 4f3e73a0143ba36229f42e8b65b6e65342bb826b
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:d48a15ea564293934eb188e6eb8737e56903453d50bc70830cdac2641fb63acc
```

# Platform:
AZR IPI

# What happened?
cluster creation failed due to quota issues

./openshift-install --dir=azr_aug30v1 destroy cluster

FATAL Failed to destroy cluster: failed to delete public DNS records: failed to delete public records for fred.burrsutter.net: failed to delete record api.fred in zone burrsutter.net: dns.RecordSetsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ScopeLocked" Message="The scope '/subscriptions/75cfbc26-90b5-4163-ad22-722e060c5ec5/resourceGroups/myresourcegroup/providers/Microsoft.Network/dnsZones/burrsutter.net/CNAME/api.fred' cannot perform delete operation because following scope(s) are locked: '/subscriptions/75cfbc26-90b5-4163-ad22-722e060c5ec5/resourcegroups/myresourcegroup/providers/Microsoft.Network/dnszones/burrsutter.net'. Please remove the lock and try again."

I will need to figure out how to "remove the lock"

**Comment by burrsutter** [comment]
az lock list
[
  {
    "id": "/subscriptions/75cfbc26-90b5-4163-ad22-722e060c5ec5/resourcegroups/myresourcegroup/providers/Microsoft.DomainRegistration/domains/burrsutter.net/providers/Microsoft.Authorization/locks/burrsutter.net",
    "level": "CanNotDelete",
    "name": "burrsutter.net",
    "notes": "Deleting a domain will make it unavailable to purchase for 60 days. Please remove the lock before deleting this domain.",
    "owners": null,
    "resourceGroup": "myresourcegroup",
    "type": "Microsoft.Authorization/locks"
  },
  {
    "id": "/subscriptions/75cfbc26-90b5-4163-ad22-722e060c5ec5/resourcegroups/myresourcegroup/providers/Microsoft.Network/dnszones/burrsutter.net/providers/Microsoft.Authorization/locks/burrsutter.net",
    "level": "CanNotDelete",
    "name": "burrsutter.net",
    "notes": "This DNS zone was created when purchasing a domain and is likely still required by the domain. If you still want to delete this DNS zone please remove the lock and delete the zone.",
    "owners": null,
    "resourceGroup": "myresourcegroup",
    "type": "Microsoft.Authorization/locks"
  }
]

**Comment by abhinavdahiya** [comment]
I think the error is pretty much tells you what the error is.. So what is your expectation from the installer??

**Comment by burrsutter** [comment]
If the error message is accurate then I do not wish to lose my domain name for 60 days because the installer wants it unlocked and deleted!

**Comment by burrsutter** [comment]
the trick: removal of the 'DNS zone' lock without deleting the domain name lock allows "destroy cluster" to work.  The lock was applied automatically when creating the DNS Zone and it is odd that "destroy cluster" run afoul of it.

**Comment by abhinavdahiya** [comment]
>The scope '/subscriptions/75cfbc26-90b5-4163-ad22-722e060c5ec5/resourceGroups/myresourcegroup/providers/Microsoft.Network/dnsZones/burrsutter.net/CNAME/api.fred' cannot perform delete operation because following scope(s) are locked

The error message is pretty clear that the installer was trying to delete the DNS `record` and not the `entire` DNS `zone.`

Also the error message is pretty clear on the next steps that the user should unlock the DNS zone to allow the destroy to proceed.

> If the error message is accurate then I do not wish to lose my domain name for 60 days because the installer wants it unlocked and deleted!

If you look carefully the 60 days warning is on the `domain name` and not the `DNS zone`

>  The lock was applied automatically when creating the DNS Zone and it is odd that "destroy cluster" run afoul of it.

It's a safety mechanism in Azure, and the destroy failed correctly to inform the user.

I don't think there is any action item for the installer from this.

/close
