### ISSUE TITLE
Add CLI commands in the Installer Docs

### ISSUE THREAD

**Issue by burrsutter** [openshift/installer#2301]
# Version

```console
$ ./openshift-install version
./openshift-install v4.2.0-201908282219-dirty
built from commit 4f3e73a0143ba36229f42e8b65b6e65342bb826b
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:d48a15ea564293934eb188e6eb8737e56903453d50bc70830cdac2641fb63acc```
```

# Platform:
gcp
# What happened?

The current GCP and AZR IPI docs assume a fair bit of knowledge about those platforms.  In addition, it links the reader out to the various GCP/AZR docs for the actual details of "how to create a Service Account" and "how to add the correct permissions/roles", etc.   Our own docs should inline the actual CLI commands to make these steps much more explicit vs hunting and clicking around in some obscure GUI console. 

What follows is the documentation text for Step 4 on https://github.com/openshift/installer/blob/master/docs/user/gcp/iam.md

Compute Engine API (compute.googleapis.com)
Google Cloud APIs (cloudapis.googleapis.com)
Cloud Resource Manager API (cloudresourcemanager.googleapis.com)
Google DNS API (dns.googleapis.com)
Identity and Access Management (IAM) API (iam.googleapis.com)
IAM Service Account Credentials API (iamcredentials.googleapis.com)
Service Management API (servicemanagement.googleapis.com)
Service Usage API (serviceusage.googleapis.com)
Google Cloud Storage JSON API (storage-api.googleapis.com)
Cloud Storage (storage-component.googleapis.com)
 
# What you expected to happen?

I propose this change to the following (if my steps are accurate):
gcloud services enable compute.googleapis.com
gcloud services enable cloudapis.googleapis.com
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable dns.googleapis.com
gcloud services enable iam.googleapis.com
gcloud services enable iamcredentials.googleapis.com
gcloud services enable servicemanagement.googleapis.com
gcloud services enable serviceusage.googleapis.com
gcloud services enable storage-api.googleapis.com
gcloud services enable storage-component.googleapis.com

gcloud services list

# How to reproduce it (as minimally and precisely as possible)?

Read and try to actually follow the instructions at https://github.com/openshift/installer/blob/master/docs/user/gcp/iam.md

This means we also need to provide the installation tips for the cloud provider CLIs.

**Comment by abhinavdahiya** [comment]
> The current GCP and AZR IPI docs assume a fair bit of knowledge about those platforms. In addition, it links the reader out to the various GCP/AZR docs for the actual details of "how to create a Service Account" and "how to add the correct permissions/roles", etc. Our own docs should inline the actual CLI commands to make these steps much more explicit vs hunting and clicking around in some obscure GUI console.

The docs hosted by the Cloud providers is always going to be more descriptive and provides users links to more concepts that are useful. I would not like the installer repo docs to become authoritative source on those resources and reduce our burden to keep them in sync... therefore we link to the Cloud Provide where ever possible.

Also, I'm fine if users get some basic understanding of the cloud they are trying to use.

/close
