### ISSUE TITLE
Installer dependencies

### ISSUE THREAD

**Issue by sander53134512** [openshift/installer#2302]
# Version
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.13/

# Platform:
azure

# What happened?

install fails
partial error debug log: (end of it)

level=debug msg="  Fetching \"Master Ignition Config\"..."
level=debug msg="  Reusing previously-fetched \"Master Ignition Config\""
level=debug msg="  Fetching \"Master Machines\"..."
level=debug msg="  Reusing previously-fetched \"Master Machines\""
level=debug msg="  Fetching \"Worker Machines\"..."
level=debug msg="  Reusing previously-fetched \"Worker Machines\""
level=debug msg="Generating \"Terraform Variables\"..."
level=info msg="Consuming \"Install Config\" from target directory"
level=debug msg="Purging asset \"Install Config\" from disk"
level=debug msg="Fetching \"Kubeconfig Admin Client\"..."
level=debug msg="Reusing previously-fetched \"Kubeconfig Admin Client\""
level=debug msg="Fetching \"Kubeadmin Password\"..."
level=debug msg="Reusing previously-fetched \"Kubeadmin Password\""
level=debug msg="Fetching \"Certificate (journal-gatewayd)\"..."
level=debug msg="Reusing previously-fetched \"Certificate (journal-gatewayd)\""
level=debug msg="Fetching \"Metadata\"..."
level=debug msg="Loading \"Metadata\"..."
level=debug msg="  Loading \"Cluster ID\"..."
level=debug msg="  Loading \"Install Config\"..."
level=debug msg="  Fetching \"Cluster ID\"..."
level=debug msg="  Reusing previously-fetched \"Cluster ID\""
level=debug msg="  Fetching \"Install Config\"..."
level=debug msg="  Reusing previously-fetched \"Install Config\""
level=debug msg="Generating \"Metadata\"..."
level=debug msg="Fetching \"Cluster\"..."
level=debug msg="Loading \"Cluster\"..."
level=debug msg="  Loading \"Cluster ID\"..."
level=debug msg="  Loading \"Install Config\"..."
level=debug msg="  Loading \"Platform Credentials Check\"..."
level=debug msg="  Loading \"Terraform Variables\"..."
level=debug msg="  Loading \"Kubeadmin Password\"..."
level=debug msg="  Fetching \"Cluster ID\"..."
level=debug msg="  Reusing previously-fetched \"Cluster ID\""
level=debug msg="  Fetching \"Install Config\"..."
level=debug msg="  Reusing previously-fetched \"Install Config\""
level=debug msg="  Fetching \"Platform Credentials Check\"..."
level=debug msg="  Reusing previously-fetched \"Platform Credentials Check\""
level=debug msg="  Fetching \"Terraform Variables\"..."
level=debug msg="  Reusing previously-fetched \"Terraform Variables\""
level=debug msg="  Fetching \"Kubeadmin Password\"..."
level=debug msg="  Reusing previously-fetched \"Kubeadmin Password\""
level=debug msg="Generating \"Cluster\"..."
level=info msg="Creating infrastructure resources..."
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to unpack Terraform modules: open /azure: file does not exist"
ERROR: Job failed: exit code 1

# What you expected to happen?

Build a cluster

# How to reproduce it (as minimally and precisely as possible)?

just use the installer on Azure
part of pipeline:
           ...
        - mv osServicePrincipal.json   /root/.azure/
        - ls -al /root/.azure/
        - cat /root/.azure/osServicePrincipal.json
        - openshift-install create cluster --log-level debug

I'm trying for some time to get it working. Some input would be much appreciated.

Can this be because the OC tool is not installed on the Linux VM that runs the installer.

**Comment by abhinavdahiya** [comment]
Azure is only supported starting 4.2.
