### ISSUE TITLE
OpenStack: Add current limitations section to the README.md file

### ISSUE THREAD

**Issue by racedo** [openshift/installer#2303]
The OpenStack README.md doesn't mention what limitations the current implementation has. Using self-signed certificates and support for temp URLs from Ceph RGW as deployed by director come to mind as things users should be aware of.

**Comment by mandre** [comment]
/label platform/openstack

Should be taken care of (for the most part) in  https://github.com/openshift/installer/pull/2270.
We'll document the remaining limitations in a subsequent PR.

**Comment by racedo** [comment]
Great job. Thanks.
