### ISSUE TITLE
Cluster initialisation not completing on AWS

### ISSUE THREAD

**Issue by Jabulisile** [openshift/installer#2306]
# Version

```console
$ openshift-install version
./openshift-install v4.1.4-201906271212-dirty
built from commit ca5d270bc8d554496f0aa1073bdaa67adf01a25a
release image quay.io/openshift-release-dev/ocp-release@sha256:a6c177eb007d20bb00bfd8f829e99bd40137167480112bd5ae1c25e40a4a163a
```

# Platform:

# What happened?

Installation in AWS fails to complete with error "failed to initialize the cluster: Some cluster operators are still updating: authentication, console: timed out waiting for the condition". Install log attached. Authentication, monitoring, and console operators in a degraded state.

# What you expected to happen?

The cluster to initialise successfully.

# How to reproduce it (as minimally and precisely as possible)?

- Infrastructure provisioned using cloud formation
- ./openshift-install wait-for bootstrap-complete --dir=custom-install --log-level debug (completes succesfully)
- ./openshift-install --dir=custom-install wait-for install-complete --log-level debug (fails at 99%)

[.openshift_install.log](https://github.com/openshift/installer/files/3570283/default.openshift_install.log)

**Comment by abhinavdahiya** [comment]
Please try the troubleshooting docs at https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-initialize-the-cluster

also `oc adm must-gather` will help debugging.

`openshift-install v4.1.4-201906271212-dirty` is quite a old version, see if new version of OpenShift fixes the issue.

**Comment by Jabulisile** [comment]
Hi Abhinav

Have updated to the latest openshift-install but control plane instances don't seem top be listening on port 6443. I suspect if the AMI i'm using (using the latest recommended here https://github.com/openshift/installer/blob/d7621ca95c509e193454ed9e00d4f64644cd33e0/data/data/rhcos.json). Is this the right AMI to pair with this installer?

```
./openshift-install v4.1.13-201908210601-dirty
built from commit 8eae6c2b1e69e63186902ddf2a49ede7150b229c
release image quay.io/openshift-release-dev/ocp-release@sha256:212296a41e04176c308bfe169e7c6e05d77b76f403361664c3ce55cd30682a94
```

AMI ID: ami-081ea939fd630c300 (eu-west-1)

**Comment by Jabulisile** [comment]
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3575595/log-bundle.tar.gz)

Gathered logs

**Comment by Jabulisile** [comment]
Looks like an internet connectivity issue at the moment. Will revert once checked.

```
[core@ip-xx-xx-xx-xx ~]$ curl -kv quay.io
* Rebuilt URL to: quay.io/
*   Trying 23.23.157.35...
* TCP_NODELAY set
^C
```

**Comment by Jabulisile** [comment]
Internet connectivity resolved but issue persists. Have rebuilt and recollected logs. Please assist if possible.
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3579223/log-bundle.tar.gz)

**Comment by abhinavdahiya** [comment]
> Internet connectivity resolved but issue persists. Have rebuilt and recollected logs. Please assist if possible.
> [log-bundle.tar.gz](https://github.com/openshift/installer/files/3579223/log-bundle.tar.gz)

Looking at the bootstrap/journals/bootkube.log the etcd cluster is failing to start because the control plane machines are not running.

Please make sure the control-plane machines have booted.

**Comment by Jabulisile** [comment]
Thanks Abhinav. Closing this as cluster has since been destroyed.

**Comment by lakshmanpasala** [comment]
> Thanks Abhinav. Closing this as cluster has since been destroyed.

@Jabulisile , I am facing the same issue on aws. Were you able to deploy the cluster?
