### ISSUE TITLE
AWS permissions boundaries restricting role creation causing failure

### ISSUE THREAD

**Issue by joelddiaz** [openshift/installer#2319]
# Version

```console
master
```

# Platform:

aws`

# What happened?

In the event the installer is using an IAM permissions configuration where there are permissions boundaries set restricting the creation of Roles, the installer does not create the roles with the permissions boundaries defined (ultimately failing the install).

```
ERROR                                              
ERROR Error: Error creating IAM Role jdiaz-roles-g75ml-bootstrap-role: AccessDenied: User: arn:aws:iam::125931421481:user/permboundary is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::125931421481:role/jdiaz-roles-g75ml-bootstrap-role 
ERROR   status code: 403, request id: f3cbd4eb-cfdb-11e9-b58c-6dee0d78c915 
ERROR                                              
ERROR   on ../../../../../../../../../tmp/openshift-install-842368062/bootstrap/main.tf line 48, in resource "aws_iam_role" "bootstrap": 
ERROR   48: resource "aws_iam_role" "bootstrap" {  
ERROR                                              
ERROR                                              
ERROR     
```

Similar to how cloud-credential-operator added some code to detect and pass along any defined permissions boundary to the IAM users CCO creates (https://github.com/openshift/cloud-credential-operator/pull/89/files), the installer should do the same for the IAM Roles that it creates.
# What you expected to happen?

Naively attempt to pass along any permissions boundary for the Roles that are created. ('naively' b/c in theory the permissions boundary could be enforcing a more complex condition that doesn't self-reference itself in the permissions boundary condition)

# How to reproduce it (as minimally and precisely as possible)?

Need to run the install with a permissions boundary defined with rules that look like:

```
"Statement": [
        {
            "Sid": "CreateOrChangeOnlyWithBoundary",
            "Effect": "Allow",
            "Action": [
                "iam:CreateUser",
                "iam:DeleteUserPolicy",
                "iam:CreateRole",
                "iam:PutRolePolicy",
                "iam:PutUserPolicy"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:PermissionsBoundary": "arn:aws:iam::125931421481:policy/permboundaryminterlimits"
                }
            }
        },
```

(NOTE: the StringEquals condition should be modified so that the policy self-references itself)

# Anything else we need to know?
You can check that the IAM permissions are configured correctly if creating a role fails unless you provide a permissions boundary.

```console
[jdiaz@minigoomba bin (vendor-cco)]$ aws iam create-role --role-name mytestrole --assume-role-policy-document "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"ec2.amazonaws.com\"]},\"Action\":[\"sts:AssumeRole\"]}]}" > /dev/null ; echo $?

An error occurred (AccessDenied) when calling the CreateRole operation: User: arn:aws:iam::125931421481:user/permboundary is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::125931421481:role/mytestrole
255
[jdiaz@minigoomba bin (vendor-cco)]$ aws iam create-role --role-name mytestrole --assume-role-policy-document "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"ec2.amazonaws.com\"]},\"Action\":[\"sts:AssumeRole\"]}]}" --permissions-boundary arn:aws:iam::125931421481:policy/permboundaryminterlimits  > /dev/null ; echo $?
0
```

# References

- PR adding support for permissions boundaries in cloud-credential-operator https://github.com/openshift/cloud-credential-operator/pull/89
- original BZ report https://bugzilla.redhat.com/show_bug.cgi?id=1729021

**Comment by Jabulisile** [comment]
You might want to try a UPI deployment using CloudFormation. That way you customise your role creation, including referencing your permissions boundary.

```
MasterIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [Bounded, !Ref InfrastructureName, "MasterIamRole"]]
      PermissionsBoundary: "arn:aws:iam::XXXXX:policy/BoundedPermissionsPolicy"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action:
          - "sts:AssumeRole"
```
