### ISSUE TITLE
Allow user to set disk size for workers easily in libvirt provider

### ISSUE THREAD

**Issue by tareqalayan** [openshift/installer#2338]
Currently workers comes with 16GB of disk and there is no way to set the size of worker.
However for master it can be set by adding size = 42949672960 in the file:
https://github.com/openshift/installer/blob/b5dbb46b7e97d2c63333048f055dd518aa01eb10/data/data/libvirt/main.tf#L31

# Version

```console
$ openshift-install version
<your output here>
```

# Platform:

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by zeenix** [comment]
You can do it through manifests. See https://github.com/openshift/installer/issues/2111 for the discrepancy between how it's handled for master and worker.

/close

**Comment by cynepco3hahue** [comment]
@zeenix You can not set the volume size, only the memory, and VCPU, it the reason for https://github.com/openshift/cluster-api-provider-libvirt/pull/175, but anyway this issues should be open for the https://github.com/openshift/cluster-api-provider-libvirt/ repo

**Comment by AsherShoshan** [comment]
@zeenix  -  Please reopen the issue

**Comment by zeenix** [comment]
Oh right, i missed that fact. :) A related issue: https://github.com/openshift/installer/issues/2112

/reopen

**Comment by jichenjc** [comment]
let me try whether I can fix it...
