### ISSUE TITLE
Installation fails with SSH handshake problem

### ISSUE THREAD

**Issue by tvieira** [openshift/installer#2349]
# Version

```console
$ openshift-install version
openshift-install-4.2 unreleased-master-1745-g66e47aaae34c84618d3506ff133ea8c9df2ae8c9-dirty
built from commit 66e47aaae34c84618d3506ff133ea8c9df2ae8c9
release image registry.svc.ci.openshift.org/ocp/release@sha256:5ec723200f498e702b9494679d198fa0a0506724e943d517d7920be72921c914
```

# Platform:
aws

# What happened?
By running the `create cluster` command, and selecting the options manually, the installation fails as the SSH handshake fails.

```console
$ openshift-install create cluster
? SSH Public Key /Users/tmoreira/.ssh/id_rsa.pub
? Platform aws
? Region us-east-1
? Base Domain devcluster.openshift.com
? Cluster Name tmoreira-08
? Pull Secret [? for help] ****************************
INFO Creating infrastructure resources...
INFO Waiting up to 30m0s for the Kubernetes API at https://api.tmoreira-08.devcluster.openshift.com:6443... 
INFO Pulling debug logs from the bootstrap machine 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
```

# What you expected to happen?

Installation succeeds.

# How to reproduce it (as minimally and precisely as possible)?

1. Run

```console
$ openshift-install create cluster
```

2. Make your selections manually (do not use config file)

# Anything else we need to know?
I have 3 different public keys in my .ssh/ directory and I tried with all of them.

**Comment by wking** [comment]
> ```
> ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
```

The primary error here is the Kubernetes API not coming up in time (the FATAL).  We try to automatically gather logs to help explain why, and that is failing too (the ERROR).

I talked this over with @mattmahoneyrh out of band, and at least in his case the issue was `SSH_AUTH_SOCK` present in his installer environment.  When that's set, we just [use it][1] instead of constructing our own `agent.Agent` with discovered SSH keys.  That means you'll need to either unset `SSH_AUTH_SOCK` when calling `openshift-install ... create cluster` or `openshift-install ... gather bootstrap ...`, or add the relevant key to your existing agent with `ssh-add ...`.

I'll try to land some logging and error wrapping to help make this process clearer when it goes wrong.

[1]: https://github.com/openshift/installer/blob/f96afb99f1ce4f8976ce62f7df44acb24d2062d6/pkg/gather/ssh/agent.go#L16-L18

**Comment by astefanutti** [comment]
I face the same issue, even with `unset SSH_AUTH_SOCK`:

```console
$ ./openshift-install version
./openshift-install v4.2.0
built from commit 8c6c64d5a1465595f39da968f923141c48a30bfc
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:02efb41240a70e0eb32224c6bdf33b819c0767294906d03211785b4d7a2b34c7

$ ./openshift-install create cluster --dir=os42       
INFO Consuming "Install Config" from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 30m0s for the Kubernetes API at https://api.astefanu2.rhmw-integrations.net:6443... 
INFO Pulling debug logs from the bootstrap machine 
INFO Bootstrap gather logs captured here "os42/log-bundle-20191002174012.tar.gz" 
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded 
```

Note that in my case, it works when using installer for OpenShift 4.1.13.

**Comment by jralmaraz** [comment]
Tried unset SSH_AUTH_SOCK, tried adding key to ssh agent, nothing worked :(

openshift-install version
./bin/openshift-install unreleased-master-1130-g311a8a1266268aa454e45049e85f2b3c186715c7
built from commit 311a8a1266268aa454e45049e85f2b3c186715c7
release image registry.svc.ci.openshift.org/origin/release:4.2

Will try getting a newer version.

**Comment by jralmaraz** [comment]
Tried again with the unset and it worked, thanks!

**Comment by abhinavdahiya** [comment]
> Tried again with the unset and it worked, thanks!

/close

**Comment by Nurlan199206** [comment]
@tommyreilly i have same error, where i can find it?

> Unsetting SSH_AUTH_SOCK worked for me.

**Comment by Valen503** [comment]
> > ```
> > ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> > FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
> > ```
> 
> The primary error here is the Kubernetes API not coming up in time (the FATAL). We try to automatically gather logs to help explain why, and that is failing too (the ERROR).
> 
> I talked this over with @mattmahoneyrh out of band, and at least in his case the issue was `SSH_AUTH_SOCK` present in his installer environment. When that's set, we just [use it](https://github.com/openshift/installer/blob/f96afb99f1ce4f8976ce62f7df44acb24d2062d6/pkg/gather/ssh/agent.go#L16-L18) instead of constructing our own `agent.Agent` with discovered SSH keys. That means you'll need to either unset `SSH_AUTH_SOCK` when calling `openshift-install ... create cluster` or `openshift-install ... gather bootstrap ...`, or add the relevant key to your existing agent with `ssh-add ...`.
> 
> I'll try to land some logging and error wrapping to help make this process clearer when it goes wrong.


Can you help me solve my problem, I have the same error. Try unset SSH_AUTH_SOCK and then openhift-install wait-for bootstrap-complete --log-level debug. And the result is the same. FATAL failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by xenolinux** [comment]
how do we unset SSH_AUTH_SOCK in mac OS? would this work?  `export SSH_AUTH_SOCK=""` and `launchctl stop com.openssh.ssh-agent`

**Comment by ablaabiyad** [comment]
> > > ```
> > > ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> > > FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
> > > ```
> > 
> > 
> > The primary error here is the Kubernetes API not coming up in time (the FATAL). We try to automatically gather logs to help explain why, and that is failing too (the ERROR).
> > I talked this over with @mattmahoneyrh out of band, and at least in his case the issue was `SSH_AUTH_SOCK` present in his installer environment. When that's set, we just [use it](https://github.com/openshift/installer/blob/f96afb99f1ce4f8976ce62f7df44acb24d2062d6/pkg/gather/ssh/agent.go#L16-L18) instead of constructing our own `agent.Agent` with discovered SSH keys. That means you'll need to either unset `SSH_AUTH_SOCK` when calling `openshift-install ... create cluster` or `openshift-install ... gather bootstrap ...`, or add the relevant key to your existing agent with `ssh-add ...`.
> > I'll try to land some logging and error wrapping to help make this process clearer when it goes wrong.
> 
> Can you help me solve my problem, I have the same error. Try unset SSH_AUTH_SOCK and then openhift-install wait-for bootstrap-complete --log-level debug. And the result is the same. FATAL failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Hi, 
I tried unset SSH_AUTH_SOCK as well, still the same issue, did you manage to get rid of this error? any help is appreciated.

**Comment by kaovilai** [comment]
> how do we unset SSH_AUTH_SOCK in mac OS? would this work? `export SSH_AUTH_SOCK=""` and `launchctl stop com.openssh.ssh-agent`
```
❯ unset SSH_AUTH_SOCK
```
