### ISSUE TITLE
openshift install does not allow me to input AccessKey and SecretKey if run multiple times

### ISSUE THREAD

**Issue by gyliu513** [openshift/installer#2380]
# Version
```
root@gyliu-dev1:~/ocp41/install# ./openshift-install version
./openshift-install v4.1.16-201909100604-dirty
built from commit 7c3908a694fa7401ae5a8c34ac5942d7dbfd7092
release image quay.io/openshift-release-dev/ocp-release@sha256:61ed953962d43cae388cb3c544b4cac358d4675076c2fc0befb236209d5116f7
```

# Platform:
AWS

# What happened?

I run `./openshift-install create install-config --dir=/root/ocp41/ocp-config/ --log-level debug` multiple times due to I input some wrong parameters. 

The first time run `./openshift-install`, it allowed me to input AccessKey and SecretKey, and due to some wrong input parameters, I deleted the folder `/root/ocp41/ocp-config/ ` and re-create it, and run `./openshift-install create install-config --dir=/root/ocp41/ocp-config/ --log-level debug` again, but it does not pop out message to let me input AccessKey and SecretKey, and this caused I cannot install OCP on AWS.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

This is the output of the second command, you can see I have no chance to input AccessKey and SecretKey for aws.

```console
root@gyliu-dev1:~/ocp41/install# ./openshift-install create install-config --dir=/root/ocp41/ocp-config/ --log-level debug
DEBUG OpenShift Installer v4.1.16-201909100604-dirty
DEBUG Built from commit 7c3908a694fa7401ae5a8c34ac5942d7dbfd7092
DEBUG Fetching "Install Config"...
DEBUG Loading "Install Config"...
DEBUG   Loading "SSH Key"...
DEBUG   Loading "Base Domain"...
DEBUG     Loading "Platform"...
DEBUG   Loading "Cluster Name"...
DEBUG     Loading "Base Domain"...
DEBUG   Loading "Pull Secret"...
DEBUG   Loading "Platform"...
DEBUG   Fetching "SSH Key"...
DEBUG   Generating "SSH Key"...
? SSH Public Key /root/.ssh/id_rsa.pub
DEBUG   Fetching "Base Domain"...
DEBUG     Fetching "Platform"...
DEBUG     Generating "Platform"...
? Platform aws
? Region us-east-1
DEBUG   Generating "Base Domain"...
DEBUG listing AWS hosted zones
? Base Domain apps.opencloudops.io
DEBUG   Fetching "Cluster Name"...
DEBUG     Fetching "Base Domain"...
DEBUG     Reusing previously-fetched "Base Domain"
DEBUG   Generating "Cluster Name"...
? Cluster Name liugya-ocp41
DEBUG   Fetching "Pull Secret"...
DEBUG   Generating "Pull Secret"...
? Pull Secret [? for help] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************DEBUG   Fetching "Platform"...                     **************************************************************************************************************************************************DEBUG   Reusing previously-fetched "Platform"      **************************************************************************************************************************************************DEBUG Generating "Install Config"...               **************************************************************************************************************************************************root@gyliu-dev1:~/ocp41/install#
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by gyliu513** [comment]
Seems the credential was stored in `$HOME/.aws`, and installer always get the credential from there.

```
root@gyliu-dev1:~/.aws# pwd
/root/.aws
```

But due to I input wrong credential, so the creation failed, I think the installer should provide some option to force re-write the credentials but not always using the persisted credential even if the credential is not right or expired.

**Comment by abhinavdahiya** [comment]
The installer can use the known methods [env](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) or [credential file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) to provide credentials for AWS API similar to AWS cli.


The prompts are only for user's ease so that they can setup the credentials once and reuse those for the installer.

If you want the installer to use specific or different ones, please use any of the options defined above.

/close
