### ISSUE TITLE
Propose migrate from dep to go modules

### ISSUE THREAD

**Issue by gyliu513** [openshift/installer#2384]
I can see most of the go projects are now migrating from dep to go modules, like https://github.com/kubernetes-sigs/cluster-api/pull/1054 etc, does installer has some plan to migrate as well?

Reference: https://blog.golang.org/migrating-to-go-modules

**Comment by gyliu513** [comment]
Seems installer repo is using go module mode, why not introduce `go.mod` and delete `Gopkg.xx`?

**Comment by sgreene570** [comment]
This is definitely an important switch, since Ignition v2.0.1 (which includes the new Ignition Spec 3)  cannot be vendored with Dep. OKD 4 will be dependent on the installer having Ignition Spec 3 available in order to use FCOS.
However, the migration is not as trivial as it would seem. Current attempts at the migration are hanging on Azure problems during build (see https://github.com/vrutkovs/installer/tree/spec3-all-in-one-mod).

**Comment by abhinavdahiya** [comment]
We want to do it, but the go.mod implementation doesn't make it easy to have multiple vendors for some internal services.

We are definitely looking into it.

**Comment by sgreene570** [comment]
Relevant Go github issue:
https://github.com/golang/go/issues/33789

**Comment by DanyC97** [comment]
@sgreene570 if i'm not wrong i think at the end some implementation was done based on the https://github.com/golang/go/issues/33848 proposal

**Comment by LorbusChris** [comment]
is there a good reason to not keep all deps in one vendor dir? Having multiple seems to call for version mismatches and the likes..

**Comment by gyliu513** [comment]
@LorbusChris do you mean you want use multiple vendor folders but not one? I did not see such case yet.

**Comment by LorbusChris** [comment]
What I want is the opposite: one vendor dir for everything

**Comment by sgreene570** [comment]
> What I want is the opposite: one vendor dir for everything

There are parts of the installer using different versions of the same dependencies, so having one vendor dir would require refactoring some code (namely the azure terraform stuff). For example, `azure-sdk-for-go` @ `v21.3.0` is used in `pkg/terraform/exec` ([link](https://github.com/openshift/installer/blob/master/pkg/terraform/exec/Gopkg.lock#L32)) while `v29.0.0` is used in the project root ([link](https://github.com/openshift/installer/blob/master/Gopkg.lock#L38)). While one overall version could definitely be reconciled, it will require changing some of the Azure specific code.

**Comment by LorbusChris** [comment]
@sgreene570 exactly. I'm on that over in https://github.com/openshift/installer/pull/2745 :smiley:

**Comment by gyliu513** [comment]
@LorbusChris I was a bit confused, after you migrate to go mod, if you run `go mod vendor`, you will see all dependency packages are in the folder of `vendor`, it is one vendor dir actually, am I missing anything?
