### ISSUE TITLE
Openstack image-registry pods crashloop.

### ISSUE THREAD

**Issue by dimaunx** [openshift/installer#2392]
# Version
4.2.0-0.nightly-2019-09-21-151322 or any other 4.2 version of the installer

# Platform:
Openstack on Upshift

# What happened?
The installation on upshift infrastructure always fails with image-registry operator pods never becoming healthy.

# What you expected to happen?
Installation to finish correctly.

# How to reproduce it (as minimally and precisely as possible)?

Run openshift-installer on upshift project infrastructure.

# Anything else we need to know?
I have tried quoting and double quoting all values in clouds.yaml.

The pods for image-registry contain the following errors:
time="2019-09-23T11:46:33Z" level=fatal msg="error parsing configuration file: yaml: found character that cannot start any token"

oc get clusterversion version output:
Available False 
Failing True Cluster operator image-registry is still updating
Progressing True Unable to apply 4.2.0-0.nightly-2019-09-21-174942: the cluster operator image-registry has not yet successfully rolled out
RetrievedUpdates False Unable to retrieve available updates: currently installed version 4.2.0-0.nightly-2019-09-21-174942 not found in the "stable-4.2" channel
[openshift_install.log](https://github.com/openshift/installer/files/3641970/openshift_install.log)

**Comment by tomassedovic** [comment]
/assign @Fedosin 

@Fedosin you were looking and quoting some values, right? Does this ring a bell?

**Comment by mandre** [comment]
According to @Fedosin , this was fixed in gophercloud with https://github.com/gophercloud/utils/pull/100. We'll need to pull in the fix into the installer up to branch `release-4.2`.
