### ISSUE TITLE
[vSphere]: memory, vCPU, Disk size should be configurable through terrafor.tfvars

### ISSUE THREAD

**Issue by vavuthu** [openshift/installer#2421]
# Platform:
vSphere
# What happened?

if we want to change the memory of the VM , we need to change the https://github.com/openshift/installer/blob/master/upi/vsphere/machine/main.tf#L23 to particular value.

# What you expected to happen?

need to take memory ( both for master and worker ) , vCPU ( both for master and worker ) and disk size as parameter  from terraform.tfvars

```
master_num_cpus = "4"
node_num_cpus = "4"
master_memory =  "8192"
node_memory =  "8192"
disk_size = "50"
```

**Comment by abhinavdahiya** [comment]
The vSphere terraform setup is an example and users are free to take it and modify to their requirement.

So any requests for enhancements for it are most likely going to be added/accepted. If the current setup doesn't work, we are open to fix the bugs for these.

Having said that, we would welcome any contributions https://github.com/openshift/installer/blob/master/CONTRIBUTING.md
