### ISSUE TITLE
[OpenStack] Installer looks for Kubernetes API to be up on IP different from LB FIP

### ISSUE THREAD

**Issue by smalleni** [openshift/installer#2423]
# Version

```console
$ openshift-install version
./openshift-install v4.2.0
built from commit 79267e5c1fb5835c694d36cad8d7b4417c1e2d65
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:49da18dcaf0dd58c2356c6a2009056c45facaca8171db6c5705ea67723523b78

```

# Platform: OpenStack

# What happened?
Since I do not have a DNS server under my control, I added the loadbalancer Ip to /etc/hosts as follows
172.21.0.126 api.ostest2.shiftstack.com
base domain is shiftstakc.com and clustername is ostest2

However, my install fails and looking at logs it looks like the installer is checking at a different IP for api.ostest2.shiftstack.com.
 time="2019-09-27T15:49:09Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.ostest2.shitstack.com:6443/version?timeout=32s: dial tcp: lookup api.ostest2.shitstack.com on 10.1.32.3:53: no such host

10.1.32.3 is the nameserver I have configured in /etc/resolve. conf. So not sure why the installer is waiting for the API at 10.1.32.3:53

# How to reproduce it (as minimally and precisely as possible)?

Add the LB IP in /etc/hosts
Try an install

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
Ouch, looking at the log you had a bad typo. Try again without the typo :)

**Comment by mandre** [comment]
/close

Please re-open if you still see the issue after fixing the typo.

**Comment by smalleni** [comment]
@mandre Sorry, not sure I understand what the typo is, could you mention that? The APIFloatingIPAddress in my install-config.yaml is 172.21.0.126 but the installer tries to connect to 10.1.32.3:53

Thanks in advance for help!

**Comment by mandre** [comment]
Hey @smalleni, you're missing the `f` in `shiftstack` :see_no_evil: 

10.1.32.3 is your first nameserver and the installer makes a request to it in order to resolve the bogus hostname. If you fix the base domain (assuming you have the right record in /etc/hosts it won't do a DNS query.

**Comment by smalleni** [comment]
LOL. Thanks!
