### ISSUE TITLE
OpenShift Azure -> failed `destroy cluster` after failed `create cluster`

### ISSUE THREAD

**Issue by dearmasm** [openshift/installer#2427]
# Version

```console
IBMMacBookMario:installer dearmasm$ bin/openshift-install version
bin/openshift-install unreleased-master-1786-g14b51fe581f2e841ecd7d1176aac5b78bc49d63f
built from commit 14b51fe581f2e841ecd7d1176aac5b78bc49d63f
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:
Azure (IPI)

# What happened?
- ran `create cluster` and failed due to issue #2426 
- noticed that `terraform.*` files were created and are in local directory
- wanted to clean-up given bad create invocation, so i ran `destroy cluster` so it would "reset" installer state back to original (clean) state
- the `destroy cluster` failed with error about cluster not existing (!) - which is not helpful

# What you expected to happen?

- i expected `destroy cluster` to be more resilient and smart about possible bad states it has to recover from.
- i expected `destroy cluster` to clean up orphan `terraform.*` files in directory after validating that OpenShift clusters do not exist and are thus "destroyed".
- i expect `destroy cluster` to at a minimum display better error messaging to delete/clean up files manually if it does not want to do it - make error messages more actionable and clearly appropriate for terraform infra state.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ls -l
.
.
drwxr-xr-x   3 dearmasm  staff      96 Sep 25 18:58 scripts
-rw-r--r--   1 dearmasm  staff     660 Sep 27 13:35 terraform.azure.auto.tfvars.json
-rw-r--r--   1 dearmasm  staff  387194 Sep 27 12:08 terraform.tfstate
-rw-r--r--   1 dearmasm  staff  310093 Sep 27 13:35 terraform.tfvars.json
drwxr-xr-x   6 dearmasm  staff     192 Sep 25 18:58 tests
drwxr-xr-x   4 dearmasm  staff     128 Sep 27 13:35 tls
drwxr-xr-x   6 dearmasm  staff     192 Sep 25 18:58 upi
drwxr-xr-x  12 dearmasm  staff     384 Sep 25 18:58 vendor
IBMMacBookMario:installer dearmasm$ bin/openshift-install destroy cluster --log-level=debug
DEBUG OpenShift Installer unreleased-master-1786-g14b51fe581f2e841ecd7d1176aac5b78bc49d63f 
DEBUG Built from commit 14b51fe581f2e841ecd7d1176aac5b78bc49d63f 
DEBUG deleting public records                      
DEBUG deleting resource group                      
DEBUG resources.GroupsGroupClient#Delete: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'os4azure1-xfq8j-rg' could not be found." 
FATAL Failed to destroy cluster: failed to delete resource group: resources.GroupsGroupClient#Delete: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'os4azure1-xfq8j-rg' could not be found." 
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
> i expect destroy cluster to at a minimum display better error messaging to delete/clean up files manually if it does not want to do it - make error messages more actionable and clearly appropriate for terraform infra state.

`if it does not want to do it ` -> the error is `destroy` failed to clean-up because it didn't exist, (and we will fix that), but can you provide more details on this expectation.

**Comment by dearmasm** [comment]
hi Abhinav, thank you for your follow up question. I would say that ideally the installer is smart enough to tell state of cluster is either (a) incomplete install (see #2426 for an example), or (b) it can't find it and describe appropriate next steps to manually remediate back to "clean state". perhaps installer can offer to quarantine `terraform.*` files and/or other remediation steps (and user can opt-in if they want installer to take action). thanks!

**Comment by dearmasm** [comment]
@abhinavdahiya any improvements made to tooling error reporting or logic? thanks

**Comment by dearmasm** [comment]
@abhinavdahiya any improvements made to tooling error reporting or logic? thanks
