### ISSUE TITLE
BareMetal deployment needs more configuration items.

### ISSUE THREAD

**Issue by imain** [openshift/installer#2456]
Currently the baremetal platform is being configured via a configMap from scripts.  It was agreed we could create a CRD or extend platformStatus containing information for the deployment of baremetal nodes.  Configuration items include the network interface, network, IPs etc needed on the deployment node (running the metal3 pod) in order to provision new nodes.

This configuration would then be consumed by the machine api operator and fed into the metal3 deployment pod.

**Comment by imain** [comment]
https://github.com/openshift/machine-api-operator/pull/402

**Comment by imain** [comment]
https://github.com/openshift/installer/pull/2449

**Comment by davidvossel** [comment]
I hit this today. It's not obvious that we need to manually create the metal3 ConfigMap when doing a baremetal ipi install.

**Comment by stbenjam** [comment]
This is fixed: the config map is no longer required! :tada: 

/close
