### ISSUE TITLE
Duplicate domain in etcd-member

### ISSUE THREAD

**Issue by daniel-wtd** [openshift/installer#2458]
# Version

# Platform:
Please specify the platform type: aws, libvirt, openstack, baremetal

# What happened?

I am currently setting up openshift 4.1 on baremetal.
During the setup it seemed like etcd never came up and running, therefore I inspected the logs from etcd-member containers on all masters.

There I was able to find, that the domain (basedomain) was "duplicated" in some way.

```
I1004 14:59:41.718497       1 run.go:134] checking against etcd-1.os-prod.lab.example.com.lab.example.com.
E1004 14:59:41.719410       1 run.go:63] error looking up self: could not resolve member "etcd-1.os-prod.lab.example.com.lab.example.com."
```

The real entry was resolvable

```
etcd-1.os-prod.lab.example.com
```

# What you expected to happen?

<base domain> is not duplicated

# How to reproduce it (as minimally and precisely as possible)?

Start a bare metal setup with the default example ignition configuration for bare metal.

It would be awesome to get some insight where this is coming from and how to fix it.

Regards,
Daniel

**Comment by abhinavdahiya** [comment]
Can you run the `openshift-install gather bootstrap --key <path to private key for ssh access> --bootstrap <bootstrap-host ip> --master <control-plane-0 ip> [--master <>]` to gather the logs from the failure?

**Comment by daniel-wtd** [comment]
I will do so and update the thread.

**Comment by daniel-wtd** [comment]
Hey,

I have restarted a setup today and collected the logs accoriding to the openshift-install command.
I just replaced the original domain name and repacked everything.

In addition, I logged into the first and second master and was able to find the following logs:

```
[core@os01 ~]$ sudo crictl logs a53cd54b053d7
I1007 10:35:44.174427       1 run.go:46] Version: 4.1.18-201909201915-dirty (a2175e587b007272f26305fe7d8b603c49e8f1fc)
I1007 10:35:44.175666       1 run.go:134] checking against etcd-0.os-prod.lab.example.com.lab.example.com.
E1007 10:35:44.176180       1 run.go:63] error looking up self: could not resolve member "etcd-0.os-prod.lab.example.com.lab.example.com."
I1007 10:36:14.177222       1 run.go:134] checking against etcd-1.os-prod.lab.example.com.lab.example.com.
E1007 10:36:14.177854       1 run.go:63] error looking up self: could not resolve member "etcd-1.os-prod.lab.example.com.lab.example.com."
I1007 10:36:44.177173       1 run.go:134] checking against etcd-0.os-prod.lab.example.com.lab.example.com.
E1007 10:36:44.177626       1 run.go:63] error looking up self: could not resolve member "etcd-0.os-prod.lab.example.com.lab.example.com."
I1007 10:37:14.177805       1 run.go:134] checking against etcd-0.os-prod.lab.example.com.lab.example.com.
E1007 10:37:14.179135       1 run.go:63] error looking up self: could not resolve member "etcd-0.os-prod.lab.example.com.lab.example.com."
```

[log-bundle-obfus.tar.gz](https://github.com/openshift/installer/files/3696739/log-bundle-obfus.tar.gz)

**Comment by daniel-wtd** [comment]
Gnarf, nevermind.

the problem was not caused by the installer, but by my DNS SRV Records. The SRV Records were pointing to "etcd-X.os-prod.lab.example.com.lab.example.com."

Anyway, thanks a lot and keep up the good work. :)

**Comment by abhinavdahiya** [comment]
> Gnarf, nevermind.
> 
> the problem was not caused by the installer, but by my DNS SRV Records. The SRV Records were pointing to "etcd-X.os-prod.lab.example.com.lab.example.com."
> 

+1
Let us know if you see another error.

/close
