### ISSUE TITLE
Provide UPI vmware ignition files for master and workers as path

### ISSUE THREAD

**Issue by mulbc** [openshift/installer#2504]
# Issue statement

Currently the ignition files for master and worker are set up as strings in the tfvars file. During the installation, these files will always be present as files after the `openshift-install create ignition-configs` step. This currently leads to an additional step for the user to copy the content of these files into tfvars, which is especially cumbersome when ssh-ed into a deploy host.

https://github.com/openshift/installer/blob/f0ad4e618b5d46bfb2ea08e871165a5d30bf69c4/upi/vsphere/main.tf#L53

https://github.com/openshift/installer/blob/f0ad4e618b5d46bfb2ea08e871165a5d30bf69c4/upi/vsphere/main.tf#L74

# Possible solution

Use interpolation syntax to read the content of the files:
https://www.terraform.io/docs/configuration-0-11/interpolation.html#file-path-
That way the user can provide a path to these files.

**Comment by mulbc** [comment]
@dav1x Can you have a look?

**Comment by dav1x** [comment]
Hey @mulbc take a look here:
https://github.com/openshift/installer/pull/2479

@jcpowermac has been working on adding the ignition files without the use of a url.

**Comment by mulbc** [comment]
Great! closing this then
