### ISSUE TITLE
[Question] Does openshift-installer support day 2 operations

### ISSUE THREAD

**Issue by gyliu513** [openshift/installer#2509]
I found that `openshift-install` only support day 1 install but it seems it does not support day 2 update, like adding more components on top of the existing openshift cluster. Does `openshift-install` has plan to support day 2 operations?

**Comment by abhinavdahiya** [comment]
The installer is best constraints to performing the installation of the OpenShift clusters, as we want it to cover that goal best.

Day-2 modifications can easily be handled with `oc apply -f <dir>` and can be easily scripted with installer as the installer `exits 0` when cluster is ready. There are also a vast variety of git-ops products that help configure the cluster and best suited to solve those problems.

So day-2 operations are not on the Roadmap for Installer.

**Comment by gyliu513** [comment]
Thanks @abhinavdahiya !
