### ISSUE TITLE
openshift-install not detecting symlinked path

### ISSUE THREAD

**Issue by nccurry** [openshift/installer#2524]
# Version

```console
ncc@rht460s:~$ openshift-install version                                                                                             openshift-install v4.2.0
built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
release image quay.io/openshift-release-dev/ocp-release@sha256:c5337afd85b94c93ec513f21c8545e3f9e36a227f55d41bc1dfb8fcc3f2be129
```

# Platform:
azure

# What happened?

Installer failed to create files in /tmp when using relative pathing from symlinked directory.

> INFO Creating infrastructure resources...
> DEBUG Symlinking plugin terraform-provider-google src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-google"
> DEBUG Symlinking plugin terraform-provider-ignition src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-ignition"
> DEBUG Symlinking plugin terraform-provider-local src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-local"
> DEBUG Symlinking plugin terraform-provider-openstack src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-openstack"
> DEBUG Symlinking plugin terraform-provider-random src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-random"
> DEBUG Symlinking plugin terraform-provider-aws src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-aws"
> DEBUG Symlinking plugin terraform-provider-azurerm src: "/home/ncc/bin/openshift-install" dst: "/tmp/openshift-install-352079361/plugins/terraform-provider-azurerm"
> ERROR There are some problems with the configuration, described below.                                                               ERROR                                                                                                                                ERROR The Terraform configuration must be valid before initialization so that                                                        ERROR Terraform can determine which modules and providers need to be installed.                                                      ERROR                                                                                                                                ERROR Error: Failed to read module directory                                                                                         ERROR                                                                                                                                ERROR Module directory ../../../../tmp/openshift-install-352079361 does not exist or                                                 ERROR cannot be read.                                                                                                                ERROR                                                                                                                                FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to initialize Terraform

 Directory via pwd:
/home/ncc/programming/ocp4-azure

Actual directory 
/home/ncc/documents/programming/ocp4-azure

I think the installer isn't picking up on the following symlink.
/home/ncc/programming -> /home/ncc/documents/programming

# What you expected to happen?

Working installation

# How to reproduce it (as minimally and precisely as possible)?

```
mkdir ~/one/two
ln -s ~/one/two ~/two
cd ~/two
openshift-install create install-config
openshift-install create cluster
```

# Anything else we need to know?

# References

**Comment by wking** [comment]
Dup of #1839 

/close
