### ISSUE TITLE
AWS documentation: request for EIP count needed for successful installation

### ISSUE THREAD

**Issue by myechuri** [openshift/installer#2534]
# Version

```console
$ openshift-install version
./openshift-install v4.1.18-201909201915-dirty
built from commit 33daf58e035dfd94f9ad23cf8d81e6665ff26c57
release image quay.io/openshift-release-dev/ocp-release@sha256:420633acf3fc7572372fe2df758152f6ab1f53a21c79a6c4b741fa0394c7df3a
```

# Platform:
AWS

# What happened?

Followed [quick install documentation](https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-default.html) to get a default Openshift Platform stack up and running on AWS.

```
openshift-install create cluster --dir=$HOME/openshift --log-level debug
...
ERROR                                              
ERROR 	* module.vpc.aws_eip.nat_eip[1]: 1 error occurred: 
ERROR 	* aws_eip.nat_eip.1: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached. 
ERROR 	status code: 400, request id: 9618bfad-09e2-40be-a758-7554d4fb906b 
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR Terraform does not automatically rollback in the face of errors. 
ERROR Instead, your Terraform state file has been partially updated with 
ERROR any resources that successfully completed. Please address the error 
ERROR above and apply again to incrementally change your infrastructure. 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
```

My AWS account limit for EIP (both Classic and VPC) is 5, which is the default limit for any AWS account, and all 5 were consumed by openshift-install during installation:

<img width="1208" alt="Screen Shot 2019-10-18 at 6 22 02 PM" src="https://user-images.githubusercontent.com/12038016/67135920-3ec57700-f1d4-11e9-8452-9e9438cba13a.png">

 It would be helpful to first time user to have the exact EIP count expected to be available in AWS account for a successful first install. i submitted service limit increase request to AWS to up my EIP count (both Classic and VPC) to 10 hoping that 10 would be sufficient to get through successful install.

# What you expected to happen?

Would appreciate documentation guidance on the exact EIP count that we expect to create. Thanks!

# How to reproduce it (as minimally and precisely as possible)?

Run 4.1 `openshift-install create cluster --dir=$HOME/openshift --log-level debug` from an AWS account with default EIP limit of 5.

# Anything else we need to know?

None

# References

None

**Comment by abhinavdahiya** [comment]
We have documentation that provides those and more already https://github.com/openshift/installer/blob/master/docs/user/aws/limits.md#elastic-ip-eip

**Comment by myechuri** [comment]
Thanks a lot for pointing me to the documentation, @abhinavdahiya ! Closing.
