### ISSUE TITLE
OpenShift 4.2 Disconnect installation on VMware Workstation

### ISSUE THREAD

**Issue by vinothkumar437** [openshift/installer#2536]
Hi Team,

Please help me to configure OpenShift 4.2 Disconnected Installation on VMware Workstation UPI environment.

Regards
Vinothkumar P

**Comment by stefanskotte** [comment]
Follow this: https://blog.openshift.com/deploying-a-upi-environment-for-openshift-4-1-on-vms-and-bare-metal/

Make sure you follow the updated instructions for 4.2, from this point: 

https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#installation-user-infra-generate-k8s-manifest-ignition_installing-vsphere

**Comment by abhinavdahiya** [comment]
we have official docs for restricted networks for vspshere https://docs.openshift.com/container-platform/4.2/installing/installing_restricted_networks/installing-restricted-networks-vsphere.html#installing-restricted-networks-vsphere

/close
