### ISSUE TITLE
Add UEFI_COMPATIBLE and SECURE_BOOT to RHCOS on GCP

### ISSUE THREAD

**Issue by cgwalters** [openshift/installer#2546]
We will need to do https://github.com/coreos/mantle/pull/1060 but with Terraform, since for GCP we only upload image files.  It looks like this was only very recently added to the Terraform GCP provider: https://github.com/GoogleCloudPlatform/magic-modules/pull/2339

I still need to do some testing with this with RHCOS, but it works with FCOS, so filing this now to track it and help me remember to do it.

**Comment by abhinavdahiya** [comment]
@cgwalters do you mind providing a little more context on why this is important?

Also I think a prerequisite would be making sure machine-api has this feature if this is a VM tunable.

**Comment by cgwalters** [comment]
> @cgwalters do you mind providing a little more context on why this is important?

Turning on these flags gives us secure boot and a virtual TPM.  The virtual TPM is quite useful for a variety of reasons, but one of the biggest is that we really want to push using TPMs on bare metal, and having a top-tier cloud target also have a TPM means we effectively get testing of some of the metal/TPM paths for free at scale.

> Also I think a prerequisite would be making sure machine-api has this feature if this is a VM tunable.

I don't think that's necessary; it's a property of the image which machine-api just consumes.
