### ISSUE TITLE
missing discovery-srv parameter in etcd-member.yaml when reinstalled master

### ISSUE THREAD

**Issue by bmillemathias-1a** [openshift/installer#2551]
# Version

```console
/usr/local/bin/openshift-install v4.2.0
built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
release image quay.io/openshift-release-dev/ocp-release@sha256:c5337afd85b94c93ec513f21c8545e3f9e36a227f55d41bc1dfb8fcc3f2be129
```

# Platform:
baremetal

# What happened?

So we installed a cluster 4.2 with 3 masters and 2 workers successfully, however after a day we discovered one master was installed on a wrong disk (virtual USB 8GB) and went full after few hours. So we reinstalled it.
But this node has a pod etcd-quorum-guard which was failing constantly, after investigating (issue explained in https://github.com/openshift/openshift-docs/issues/17475 to fix the docs) we found that the file did not had the parameter `--discovery-srv=dev01.subdom.dom.tld` for container discovery as the other nodes.
I've looked into the file `.openshift_install.log` but did not find the log related to the reinstallation of the node.

# What you expected to happen?

to have this parameter set.

# How to reproduce it (as minimally and precisely as possible)?

We did not tried to reproduce.

# Anything else we need to know?

The cluster was installed in disconnected mode which is brand new in version 4.2 with static manually set IP address at boot (no DHCP, PXE for now)

# References

To fix the problem with etcd we applied the documentation https://docs.openshift.com/container-platform/4.2/backup_and_restore/disaster_recovery/scenario-1-infra-recovery.html which was a bit buggy, I've reported encountered issues on https://github.com/openshift/openshift-docs/issues/17475

**Comment by abhinavdahiya** [comment]
The installer does not control the etcd, please open a bugzilla https://bugzilla.redhat.com/ for product OpenShift container platform and Etcd component.

**Comment by abhinavdahiya** [comment]
> The installer does not control the etcd, please open a bugzilla https://bugzilla.redhat.com/ for product OpenShift container platform and Etcd component.

/close
