### ISSUE TITLE
Vsphere UPI doesn't inject network static files

### ISSUE THREAD

**Issue by chechuironman** [openshift/installer#2552]
hey guys,

I'm running the vsphere scripts, and works fine, but network files for static IPs are not injected into the CoreOS 4.2

 

# Version

```console
[root@terraform ocp4.2]# ./openshift-install version
./openshift-install v4.2.0
built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
release image quay.io/openshift-release-dev/ocp-release@sha256:c5337afd85b94c93ec513f21c8545e3f9e36a227f55d41bc1dfb8fcc3f2be129
```

# Platform:

# What happened?

Network static files are not injected into de OS CoreOS4.2

# What you expected to happen?

static IPs

# How to reproduce it (as minimally and precisely as possible)?

Run the tf scripts with the nodes IPs defined on the variables file

**Comment by vishnoisuresh** [comment]
yea, I have got the same issue.

**Comment by ooOOJavaOOoo** [comment]
we are seeing this issue as well.. only available workaround is to create an iso per static ip..

**Comment by fherbert** [comment]
We had this problem with RHCOS RHCOS_42.80.20190801, updating to RHCOS_42.80.20190828.2 or RHCOS_42.80.20191002.0 fixed static ip config using ignition for us.

**Comment by crissonpl** [comment]
I have the same issue both with RHCOS latest 4.1 and 4.2 images.

Some weeks ago with the same images it was working fine and now after I cloned the repo again it doesn't assign static IPs.

In the VM Options of the VMs I don't see the fields - guestinfo.ignition.config.data neither guestinfo.ignition.config.data.encoding. Should the terraform scrip create them?

**Comment by bortek** [comment]
Same here. Static IPs renot being ssigned and guestinfo.ignition.config.dataand enconding are not set on the VM guests. Are these the right parameters, jhave they changed their name inthe VM ?

It is this block in the machine/main.tf that should do the magic

  vapp {
    properties {
      "guestinfo.ignition.config.data"          = "${base64encode(data.ignition_config.ign.*.rendered[count.index])}"
      "guestinfo.ignition.config.data.encoding" = "base65"
    }
  }

**Comment by David-Igou** [comment]
Can we get some clarity on if true static IPs as possible via ignition files? I suspect the vSphere UPI terraform requires a DHCP server to be available, but doesn't clearly document it. The download of the remote ignition file is done at the initram level, which requires networking, but ifgcfg-ens192 is written to after this. takes place.

**Comment by crissonpl** [comment]
My experience is that you still need DHCP as you wrote. The static IPs config is done after ignition download so the VMs without DHCP and with static IPs configured via ignition were still making a DHCP request
