### ISSUE TITLE
AWS installer fails with "waiting for Kubernetes API: context deadline exceeded"

### ISSUE THREAD

**Issue by myechuri** [openshift/installer#2566]
# Version

```console
$ openshift-install version
./openshift-install v4.1.18-201909201915-dirty
built from commit 33daf58e035dfd94f9ad23cf8d81e6665ff26c57
release image quay.io/openshift-release-dev/ocp-release@sha256:420633acf3fc7572372fe2df758152f6ab1f53a21c79a6c4b741fa0394c7df3a

```

# Platform:
AWS

# What happened?

Installer fails waiting for Kubernetes API to be available.

```
$ openshift-install create cluster --dir=$HOME/openshift --log-level debug
...
DEBUG Still waiting for the Kubernetes API: Get https://api.myechuri-openshift.3.218.74.31.nip.io:6443/version?timeout=32s: dial tcp 3.218.74.31:6443: i/o timeout 
DEBUG Still waiting for the Kubernetes API: Get https://api.myechuri-openshift.3.218.74.31.nip.io:6443/version?timeout=32s: dial tcp 3.218.74.31:6443: i/o timeout 
DEBUG Still waiting for the Kubernetes API: Get https://api.myechuri-openshift.3.218.74.31.nip.io:6443/version?timeout=32s: dial tcp 3.218.74.31:6443: i/o timeout 
DEBUG Still waiting for the Kubernetes API: Get https://api.myechuri-openshift.3.218.74.31.nip.io:6443/version?timeout=32s: dial tcp 3.218.74.31:6443: i/o timeout 
DEBUG Fetching "Install Config"...                 
DEBUG Loading "Install Config"...                  
DEBUG   Loading "SSH Key"...                       
DEBUG   Using "SSH Key" loaded from state file     
DEBUG   Loading "Base Domain"...                   
DEBUG     Loading "Platform"...                    
DEBUG     Using "Platform" loaded from state file  
DEBUG   Using "Base Domain" loaded from state file 
DEBUG   Loading "Cluster Name"...                  
DEBUG     Loading "Base Domain"...                 
DEBUG   Using "Cluster Name" loaded from state file 
DEBUG   Loading "Pull Secret"...                   
DEBUG   Using "Pull Secret" loaded from state file 
DEBUG   Loading "Platform"...                      
DEBUG Using "Install Config" loaded from state file 
DEBUG Reusing previously-fetched "Install Config"  
INFO Use the following commands to gather logs from the cluster 
INFO ssh -A core@52.87.183.117 '/usr/local/bin/installer-gather.sh 10.0.133.110 10.0.153.109 10.0.162.251' 
INFO scp core@52.87.183.117:~/log-bundle.tar.gz . 
FATAL waiting for Kubernetes API: context deadline exceeded 
```

Unable to access API endpoint after a couple of hours:
```
$ kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp 3.218.74.31:6443: i/o timeout
```
# What you expected to happen?

API server was expected to be available post-install.

# How to reproduce it (as minimally and precisely as possible)?

On Mac:

```console
$ openshift-install create cluster --dir=$HOME/openshift --log-level debug
```

# Anything else we need to know?

Following [troubleshooting doc](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#kubernetes-api-is-unavailable), etcd seems to be up on all 3 master nodes:

Master1:
```
$ ssh -J core@ec2-52-87-183-117.compute-1.amazonaws.com core@10.0.133.110 "sudo crictl logs 7bb4a2c365b3e615b54c2160f73cbd2ac8b698f1dff4c66e2f52469cea8627c5"
2019-10-23 23:58:18.170181 I | etcdmain: ServerTLS: cert = /etc/ssl/etcd/system:etcd-metric:etcd-0.myechuri-openshift.3.218.74.31.nip.io.crt, key = /etc/ssl/etcd/system:etcd-metric:etcd-0.myechuri-openshift.3.218.74.31.nip.io.key, ca = /etc/ssl/etcd/metric-ca.crt, trusted-ca = , client-cert-auth = false, crl-file = 
2019-10-23 23:58:18.171470 I | etcdmain: listening for grpc-proxy client requests on 127.0.0.1:9977
2019-10-23 23:58:18.172023 I | etcdmain: ClientTLS: cert = /etc/ssl/etcd/system:etcd-peer:etcd-0.myechuri-openshift.3.218.74.31.nip.io.crt, key = /etc/ssl/etcd/system:etcd-peer:etcd-0.myechuri-openshift.3.218.74.31.nip.io.key, ca = /etc/ssl/etcd/ca.crt, trusted-ca = , client-cert-auth = false, crl-file = 
2019-10-23 23:58:18.188619 I | etcdmain: grpc-proxy: listening for metrics on https://0.0.0.0:9979
```

Master2:
```
$ ssh -J core@ec2-52-87-183-117.compute-1.amazonaws.com core@10.0.153.109 "sudo crictl logs 9ef71d5ed6c7ea762ac91fc2c5b46f17d1c15562f58aaf899a30d764b117e7f3"
2019-10-23 23:58:19.097070 I | etcdmain: ServerTLS: cert = /etc/ssl/etcd/system:etcd-metric:etcd-1.myechuri-openshift.3.218.74.31.nip.io.crt, key = /etc/ssl/etcd/system:etcd-metric:etcd-1.myechuri-openshift.3.218.74.31.nip.io.key, ca = /etc/ssl/etcd/metric-ca.crt, trusted-ca = , client-cert-auth = false, crl-file = 
2019-10-23 23:58:19.098309 I | etcdmain: listening for grpc-proxy client requests on 127.0.0.1:9977
2019-10-23 23:58:19.098761 I | etcdmain: ClientTLS: cert = /etc/ssl/etcd/system:etcd-peer:etcd-1.myechuri-openshift.3.218.74.31.nip.io.crt, key = /etc/ssl/etcd/system:etcd-peer:etcd-1.myechuri-openshift.3.218.74.31.nip.io.key, ca = /etc/ssl/etcd/ca.crt, trusted-ca = , client-cert-auth = false, crl-file = 
2019-10-23 23:58:19.112176 I | etcdmain: grpc-proxy: listening for metrics on https://0.0.0.0:9979
```

Master3:
```
$ ssh -J core@ec2-52-87-183-117.compute-1.amazonaws.com core@10.0.162.251 "sudo crictl logs c381ed54551776c78a841162323a26abe697834335aa8cbf1443b35f2cc4de89"
2019-10-23 23:58:20.038092 I | etcdmain: ServerTLS: cert = /etc/ssl/etcd/system:etcd-metric:etcd-2.myechuri-openshift.3.218.74.31.nip.io.crt, key = /etc/ssl/etcd/system:etcd-metric:etcd-2.myechuri-openshift.3.218.74.31.nip.io.key, ca = /etc/ssl/etcd/metric-ca.crt, trusted-ca = , client-cert-auth = false, crl-file = 
2019-10-23 23:58:20.039349 I | etcdmain: listening for grpc-proxy client requests on 127.0.0.1:9977
2019-10-23 23:58:20.039944 I | etcdmain: ClientTLS: cert = /etc/ssl/etcd/system:etcd-peer:etcd-2.myechuri-openshift.3.218.74.31.nip.io.crt, key = /etc/ssl/etcd/system:etcd-peer:etcd-2.myechuri-openshift.3.218.74.31.nip.io.key, ca = /etc/ssl/etcd/ca.crt, trusted-ca = , client-cert-auth = false, crl-file = 
2019-10-23 23:58:20.052714 I | etcdmain: grpc-proxy: listening for metrics on https://0.0.0.0:9979
```

Am able to access API endpoint from bootstrap node inside the VPC:
```
$ ssh core@ec2-52-87-183-117.compute-1.amazonaws.com
Red Hat Enterprise Linux CoreOS 410.8.20190520.0
WARNING: Direct SSH access to machines is not recommended.
This node has been annotated with machineconfiguration.openshift.io/ssh=accessed

---
This is the bootstrap node; it will be destroyed when the master is fully up.

The primary service is "bootkube.service". To watch its status, run e.g.

  journalctl -b -f -u bootkube.service
Last login: Thu Oct 24 00:08:24 2019 from 157.131.195.34

[core@ip-10-0-4-53 ~]$ kubectl cluster-info
Kubernetes master is running at https://api.myechuri-openshift.3.218.74.31.nip.io:6443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

[core@ip-10-0-4-53 ~]$ kubectl get nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-10-0-133-110.ec2.internal   Ready    master   18h   v1.13.4+12ee15d4a
ip-10-0-140-92.ec2.internal    Ready    worker   18h   v1.13.4+12ee15d4a
ip-10-0-153-109.ec2.internal   Ready    master   18h   v1.13.4+12ee15d4a
ip-10-0-159-114.ec2.internal   Ready    worker   18h   v1.13.4+12ee15d4a
ip-10-0-162-251.ec2.internal   Ready    master   18h   v1.13.4+12ee15d4a
ip-10-0-167-131.ec2.internal   Ready    worker   18h   v1.13.4+12ee15d4a
[core@ip-10-0-4-53 ~]$
```

DNS A record and external/internal LBs seem healthy:
<img width="419" alt="Screen Shot 2019-10-24 at 11 21 21 AM" src="https://user-images.githubusercontent.com/12038016/67513829-82930300-f650-11e9-98c9-c013447591c3.png">
<img width="1218" alt="Screen Shot 2019-10-24 at 11 20 34 AM" src="https://user-images.githubusercontent.com/12038016/67513835-86268a00-f650-11e9-875e-ccadcbe39cd7.png">

Log bundle:
[log-bundle.tar.gz](https://github.com/openshift/installer/files/3768839/log-bundle.tar.gz)

# References

- enter text here.

**Comment by wking** [comment]
Everything looks happy in the attached log bundle.  I agree that installer->cluster networking seems like the culprit.  I/O timeouts and `3.218.74.31` matching your DNS record means that the problem is probably not DNS ;).  Did you check your load balancer targets and health checks to make sure the load balancers are happy with the backing Kubernetes API servers?

**Comment by myechuri** [comment]
Thanks for taking a look at the log bundle, @wking . 

> Did you check your load balancer targets and health checks to make sure the load balancers are happy with the backing Kubernetes API servers?

Thanks for suggesting. All of the listeners for the host group are healthy except for the one corresponding to bootstrap node:

<img width="1205" alt="Screen Shot 2019-10-25 at 5 25 14 PM" src="https://user-images.githubusercontent.com/12038016/67611206-daaf2f80-f74c-11e9-9bee-c83585ed15d9.png">
<img width="1218" alt="Screen Shot 2019-10-25 at 5 27 37 PM" src="https://user-images.githubusercontent.com/12038016/67611211-de42b680-f74c-11e9-8296-88ec61d1cf33.png">

i am assuming bootstrap node being a listener for api endpoint is a temporary bootstrap configuration. Can you please correct if that is not the case? Am looking into why bootstrap is unhealthy, will update the issue once i find more info. Thanks!

**Comment by myechuri** [comment]
Thanks to @justnoise and @ldx for helping triage the issue. The problem was with a faulty hosted zone. Created a fresh new hosted zone and reran installer - things worked fine.

**Comment by Aidan-Pasquale99** [comment]
@myechuri Could you please shed a bit more insight as to what the issue with your hosted zone was?

**Comment by parsh96** [comment]
@myechuri i am also facing the same issue but tried your solution but not able to resolve the same.
.

**Comment by grelaxus** [comment]
For me it also has to do with a faulty hosted domain and I managed to fix it. I posted a Question and an Answer on Stackoverflow. Please feel free to vote it up so it doesn't get deleted by moderators: https://stackoverflow.com/questions/59384073/why-openshift-installer-for-aws-provider-fails-unable-to-connect-to-kubernetes-a

**Comment by clbx** [comment]
I am running into this issue on 4.9.13 to AWS. The NS servers are already in the configuration mentioned in @grelaxus SO link. 

Any advice is appreciated.

**Comment by staebler** [comment]
> I am running into this issue on 4.9.13 to AWS. The NS servers are already in the configuration mentioned in @grelaxus SO link.
> 
> Any advice is appreciated.

Please open a separate issue with the details of the problem that you are facing, as this issue as closed as resolved. In your issue, please include the .openshift_install.log from the install directory and the logs from the bootkube and release-image service that you can find in the bootkube gather bundle generated by the installer when the installation fails.
