### ISSUE TITLE
Instance type field not working on AWS with install config.

### ISSUE THREAD

**Issue by anmolsachan** [openshift/installer#2584]
# Version
4.2
```console
$ openshift-install version
unreleased-master-2043-ga9d73356bfc5046b1d66f674bb46df10199b83a4-dirty
built from commit a9d73356bfc5046b1d66f674bb46df10199b83a4
release image registry.svc.ci.openshift.org/ocp/release@sha256:43014d6d4a2a10d92a3c66838d415c9dfc29b3e48724a78822671a89f293d01c
```

# Platform:
AWS

# What happened?
I added the type field (type: m5.4xlarge) in the compute.platform.aws.type in the install-config to create a cluster. But the cluster created was of nodes m4.xlarge instance.
```
platform:
  aws:
    region: us-east-1
    type: m5.4xlarge
```
-- | --

# What you expected to happen?
The created nodes should have been of instance type m5.4xlarge.

# How to reproduce it (as minimally and precisely as possible)?
1) Create install config.
2) Add compute.platform.aws.type field
3) Create a cluster using this install config.

# Anything else we need to know?

Enter text here.

# References
Documentation:
https://docs.openshift.com/container-platform/4.2/installing/installing_aws/installing-aws-customizations.html#installation-initializing_installing-aws-customizations

**Comment by abhinavdahiya** [comment]
The field is setup incorrectly. 

Look at https://github.com/openshift/installer/blob/master/docs/user/aws/customization.md#custom-machine-pools for reference.

**Comment by anmolsachan** [comment]
@abhinavdahiya Thanks. I found the mistake. Thanks :) Closing the issue.
