### ISSUE TITLE
Unable to access the web Console : Openshift 3 kubernetes v1.11.0+d4cacc0

### ISSUE THREAD

**Issue by virtualsaif** [openshift/installer#2612]
# Version

```console
$ openshift-install version
openshift v3.11.153
```

# Platform:

VMware VM RHEL 7.5
# What happened?

New setup, Single node
 Install completed successfully

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Get the web console

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
``Name:               openshift.swat.local
Roles:              compute,infra,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=openshift.swat.local
                    logging-infra-fluentd=true
                    node-role.kubernetes.io/compute=true
                    node-role.kubernetes.io/infra=true
                    node-role.kubernetes.io/master=true
Annotations:        node.openshift.io/md5sum=4c4e257bf0bc5eb5a206a789632bba08
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Fri, 01 Nov 2019 17:17:05 -0500
Taints:             <none>
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Fri, 01 Nov 2019 18:16:20 -0500   Fri, 01 Nov 2019 17:17:05 -0500   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Fri, 01 Nov 2019 18:16:20 -0500   Fri, 01 Nov 2019 17:17:05 -0500   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 01 Nov 2019 18:16:20 -0500   Fri, 01 Nov 2019 17:17:05 -0500   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 01 Nov 2019 18:16:20 -0500   Fri, 01 Nov 2019 17:17:05 -0500   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 01 Nov 2019 18:16:20 -0500   Fri, 01 Nov 2019 18:00:49 -0500   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  172.16.60.59
  Hostname:    openshift.swat.local
`

# Anything else we need to know?

This is lab

# References

<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #6017
-->

- enter text here.

**Comment by virtualsaif** [comment]
I am new to GitHub and OS as well, Please let me know if you need any other info
I had followed a youtube video to install it, and it looks to be working
"[root@openshift ~]#  oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-8z7fm    1/1       Running   1          1h
registry-console-1-29cpl   1/1       Running   1          1h
router-1-mm92n             1/1       Running   1          1h
[root@openshift ~]# oc version
oc v3.11.153
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO"

**Comment by abhinavdahiya** [comment]
> $ openshift-install version
openshift v3.11.153

Where did you get the installer binary for version `3.11.153` ??

This repository is only for installing Openshift 4 clusters. https://docs.openshift.com/container-platform/4.2/welcome/index.html

**Comment by abhinavdahiya** [comment]
Looks like this is stale.

/close
