### ISSUE TITLE
gcp images are not labeled

### ISSUE THREAD

**Issue by joelddiaz** [openshift/installer#2621]
# Version
4.2.2

```console
./openshift-install v4.2.0
built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
release image quay.io/openshift-release-dev/ocp-release@sha256:c5337afd85b94c93ec513f21c8545e3f9e36a227f55d41bc1dfb8fcc3f2be129
```

# Platform:
gcp

# What happened?
The image created for the cluster is not labeled.

# What you expected to happen?
In AWS the AMIs are labeled. GCP supports labeling images, I expect the GCP images to be labeled.

# How to reproduce it (as minimally and precisely as possible)?
install OpenShift on GCP and look at the non-existent labels on the image.

```console
$ [jdiaz@minigoomba ~]$ gcloud compute images list --filter 'name=( "jdiaz--pjcdm-rhcos-image" )' --format json | jq -r '.[].labels'
null
```

# Anything else we need to know?

# References

**Comment by abhinavdahiya** [comment]
None of the GCP resources are labelled and all of them are prefixed with identifier to mark owneship.

GCP only supports labeling _few_ resources https://cloud.google.com/compute/docs/labeling-resources and we will think about labeling the resources went a big chuck of resources we care about can be labelled.

**Comment by abhinavdahiya** [comment]
> None of the GCP resources are labelled and all of them are prefixed with identifier to mark owneship.
> 
> GCP only supports labeling _few_ resources https://cloud.google.com/compute/docs/labeling-resources and we will think about labeling the resources when a big chuck of resources we care about can be labelled.

/close
