### ISSUE TITLE
RFE: Support for NSX-T for VMware UPI

### ISSUE THREAD

**Issue by mkelnermishal** [openshift/installer#2627]
# Version

```console
$ openshift-install version
4.1
```

# Platform:

Users should have the option to deploy NSX-T parts when the network backend for the Openshift cluster is VMware's NSX-T and not the default vm_network.
This includes installation of a tier 1 router, a logical switch, DHCP server and IP pools.

This can be achieved by using terraform provider NSX-T.

Pull request
- #2622

**Comment by abhinavdahiya** [comment]
> Users should have the option to deploy NSX-T parts when the network backend for the Openshift cluster is VMware's NSX-T and not the default vm_network.

I totally agree that users should be allowed to use NSX-T parts, but

the the templates in `upi/vsphere` are ONLY ONE OF MANY ways of deploying the openshift clusters on vSphere. The goal of those templates are to provide a reference example and nothing more.

Also the example in `upi/vsphere` is something we use to test if UPI workflow for vsphere is correct and no changes in different compenents would break our customers. Adding this optional NSX-T makes that task difficult as we will have to verify that code-path.

So i do not think it's the current templates need be modified to support NSX-T, the users are free to take those templates if they like it and add/change them.. officially we only provide high level instructions https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#installing-vsphere

/cc @jcpowermac @dav1x

**Comment by njferrant** [comment]
@abhinavdahiya while I understand limiting the scope of provisioning UPI infrastructure, as a customer these types of RFE's are very useful. If Red Hat is going to take the approach of providing one reference example, can we get a separate repository like OCPv3's openshift-ansible-contrib?

That way customers can have access to this type of content out of tree and it won't break your UPI workflows. Regardless I don't see a desire for these types of UPI templates going away.
