### ISSUE TITLE
GCP instller does not produce public DNS zone

### ISSUE THREAD

**Issue by mjudeikis** [openshift/installer#2628]
# Version

master branch

# Platform:

gcp

# What happened?

When creating DNS GCP does not use Public DNS zone in the same way as AWS does.
![image](https://user-images.githubusercontent.com/3225744/68284756-f207ea00-0075-11ea-83b8-7f7fcbafba06.png)

A records are public by default in GCP private zones, this is why it works.

# What you expected to happen?

Expect to have 2 DNS zones:
![image](https://user-images.githubusercontent.com/3225744/68284825-0fd54f00-0076-11ea-9571-c8492d403065.png)

# Anything else we need to know?

This is needed if we want to use providers like "letsEncrypt" to provide certificates and use the TXT challenge to validate DNS. This works only with Public DNS zones. This is an OSD use-case. 

@aaronlevy @rafael-azevedo @cblecker

**Comment by patrickdillon** [comment]
If a cluster is public, the public DNS zone is a prerequisite. For GCP: https://github.com/openshift/installer/blob/master/docs/user/gcp/dns.md#step-2-create-public-zone

**Comment by mjudeikis** [comment]
@patrickdillon It is child DNS zone, not pre-requisites. Different zones :)

**Comment by mjudeikis** [comment]
/close
modifying root zone is so not nice. As if it is pre-requisite, I should not be granting access to it :/
