### ISSUE TITLE
Need to enable FIPS mode on the bootstrap node if FIPS mode requested

### ISSUE THREAD

**Issue by jlebon** [openshift/installer#2634]
Since the bootstrap node generates cryptographic material destined for the cluster, we need to ensure that if the user requested FIPS mode, the bootstrap node itself is in FIPS mode.

One idea to do this is to simply inject `install-config.yaml` into the Ignition config and have the RHCOS node key off of that (since the FIPS key is [there now](https://github.com/openshift/installer/pull/2594)). This mirrors what we do for the rest of the cluster with [`/etc/ignition-machine-config-encapsulated.json`](https://github.com/openshift/machine-config-operator/pull/868).

**Comment by cgwalters** [comment]
Or, any reason not to have the installer do the same thing as the MCS and generate the same encapsulated MC file/

**Comment by jlebon** [comment]
Sure that'd work too. Though... (and I'm speaking from a shallow understanding of things here), unlike the rest of the cluster, the bootstrap Ignition isn't actually generated from machine configs, is it? Feels cleaner to just use whatever is the source of truth in this case, which would be `install-config.yaml`.

**Comment by cgwalters** [comment]
Anyone on installer team have bandwidth for this?

**Comment by mrunalp** [comment]
@abhinavdahiya @wking @sdodson

**Comment by abhinavdahiya** [comment]
> Anyone on installer team have bandwidth for this?

if somebody can define what needs to configured using Ignition,  we can look at it.

The bootstrap-host is only configured using Ignition and not MachineConfigs, and we don't plan to do the back-n-fort because that doesn't buy us anything as users expect Ignition config to configure the bootstrap-host.

**Comment by jlebon** [comment]
> if somebody can define what needs to configured using Ignition, we can look at it.

OK, thoughts on serializing the `install-config.yaml` into JSON and plopping that down somewhere... let's say `/etc/openshift-install-config.json` ?

**Comment by abhinavdahiya** [comment]
> > if somebody can define what needs to configured using Ignition, we can look at it.
> 
> OK, thoughts on serializing the `install-config.yaml` into JSON and plopping that down somewhere... let's say `/etc/openshift-install-config.json` ?

no please, i do not want operators/component access to the install-config as as explicit API.

**Comment by jlebon** [comment]
> no please, i do not want operators/component access to the install-config as as explicit API.

We control the bootstrap node and all the code that runs on it, no? To clarify, this would only be part of the bootstrap Ignition config, not the rest of the cluster.

Anyway, thinking more on this, it's probably better to just generalize the RHCOS side of this and key off of a stamp file at e.g. `/etc/fips-requested`. Once day-2 FIPS is removed from the MC spec as discussed in https://github.com/openshift/machine-config-operator/pull/1233, we would switch the MCO to use that too.

**Comment by cgwalters** [comment]
> Anyway, thinking more on this, it's probably better to just generalize the RHCOS side of this and key off of a stamp file at e.g. /etc/fips-requested. 

Right, having the "API" be writing files into `/etc` is easy.  But the thing is...from the MCO's point of view, machines are booted into MachineConfig, **not** (just) Ignition.  The whole thing is oriented around MachineConfigs.  That's why the encapsulated file was invented - to allow us to bridge these two worlds.

We were starting to grow a separate "API" for kernel arguments that was doing the same "files in /etc" pattern - but that's not quite as ergonomic for users as having a nice direct `kernelArguments` field.

Bigger picture part of the goal here is to treat Ignition as a "low level" API, and the MachineConfig is higher level.  (And the internal controllers are higher level still)

So...while I'm not fundamentally opposed or anything to `/etc/fips-requested`, I think the encapsulated MC file is working and helps us with other aspects of the MCO, so let's keep finding the FIPS flag there?

**Comment by cgwalters** [comment]
A good way to think of this is that we're baking some "day 1 MachineConfig" processing into RHCOS, which already has `/usr/libexec/machine-config-daemon`.

(In fact...there's nothing really stopping us from putting the MCD into the initramfs, although I'm not sure we're at the point that's required)

**Comment by jlebon** [comment]
Hmm, though what about:

> Once day-2 FIPS is removed from the MC spec as discussed in openshift/machine-config-operator#1233, we would switch the MCO to use that too.

? I mean, we could just keep erroring out if sysadmins somehow set it to `false`, though it's cleaner to just remove it from the MC spec completely. And if we do that, it won't be in the encapsulated JSON anymore.

**Comment by abhinavdahiya** [comment]
> We control the bootstrap node and all the code that runs on it, no? To clarify, this would only be part of the bootstrap Ignition config, not the rest of the cluster.

doesn't mean providing install-config as json to a file somewhere as an API is a good idea.

If there needs to be some explicit location that needs certain values when FIPS, we can do that directly by creating that file with content while creating bootstrap.ign

**Comment by cgwalters** [comment]
> though it's cleaner to just remove it from the MC spec completely

One problem is we need to "ratchet" changes because we have multiple independent repositories...we sort of still rely on *before* the bootimage bump of being able to set `fips: true` in a MachineConfig.

Secondarily to that, I think it's useful for the MCO to validate that hosts are expected and desired to be in FIPS state.

**Comment by cgwalters** [comment]
> I think it's useful for the MCO to validate that hosts are expected and desired to be in FIPS state.

Not just useful, I think it's really quite important that the MCO do this type of validation.  So having FIPS in `MachineConfig` then makes sense, etc.

**Comment by cgwalters** [comment]
> if somebody can define what needs to configured using Ignition, we can look at it.

It's fairly straightforward; see:

https://github.com/openshift/installer/pull/2594
uses
https://github.com/openshift/machine-config-operator/pull/889
which renders down to
https://github.com/openshift/machine-config-operator/pull/868
which is now consumed by
https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/680

So the installer will need to do the same thing the MCO does - generate an Ignition config that has `/etc/ignition-machine-config-encapsulated.json` which sets `fips: true`.

**Comment by abhinavdahiya** [comment]
> > if somebody can define what needs to configured using Ignition, we can look at it.
> 
> It's fairly straightforward; see:
> 
> #2594
> uses
> [openshift/machine-config-operator#889](https://github.com/openshift/machine-config-operator/pull/889)
> which renders down to
> [openshift/machine-config-operator#868](https://github.com/openshift/machine-config-operator/pull/868)
> which is now consumed by
> https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/680
> 
> So the installer will need to do the same thing the MCO does - generate an Ignition config that has `/etc/ignition-machine-config-encapsulated.json` which sets `fips: true`.

@cgwalters can you provide an example of an Ignition config that just lays that file with correct contents?

**Comment by jlebon** [comment]
Some related discussions in https://github.com/openshift/machine-config-operator/issues/1250

I think overall I'm fine with re-using the encapsulated JSON file (it means we don't have to write more code, which is nice), but it does feel a bit forceful.

**Comment by cgwalters** [comment]
> @cgwalters can you provide an example of an Ignition config that just lays that file with correct contents?

https://github.com/cgwalters/playground/blob/master/ignition/rhcos-fips/etc/ignition-machine-config-encapsulated.json

**Comment by cgwalters** [comment]
And here's a pre-built Ignition JSON

```
{"ignition": {"version": "2.3.0"}, "storage": {"files": [{"path": "/etc/ignition-machine-config-encapsulated.json", "filesystem": "root", "mode": 420, "contents": {"source": "data:,%7B%0A%20%20%22metadata%22%3A%20%7B%0A%20%20%20%20%22name%22%3A%20%22rendered-master-61764a341438250970e46ed30b03faca%22%2C%0A%20%20%20%20%22selfLink%22%3A%20%22/apis/machineconfiguration.openshift.io/v1/machineconfigs/rendered-master-61764a341438250970e46ed30b03faca%22%2C%0A%20%20%20%20%22uid%22%3A%20%22e24ef66c-a612-4e6a-93e4-f53386459a76%22%2C%0A%20%20%20%20%22resourceVersion%22%3A%20%223754%22%2C%0A%20%20%20%20%22generation%22%3A%201%2C%0A%20%20%20%20%22creationTimestamp%22%3A%20%222019-11-01T19%3A54%3A59Z%22%2C%0A%20%20%20%20%22annotations%22%3A%20%7B%0A%20%20%20%20%20%20%22machineconfiguration.openshift.io/generated-by-controller-version%22%3A%20%22093b7ad7090894e844e0a51d8695d94eb24f7719%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22ownerReferences%22%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22apiVersion%22%3A%20%22machineconfiguration.openshift.io/v1%22%2C%0A%20%20%20%20%20%20%20%20%22kind%22%3A%20%22MachineConfigPool%22%2C%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22master%22%2C%0A%20%20%20%20%20%20%20%20%22uid%22%3A%20%225b8a996e-3f43-48f4-aebe-5d10964c1ef7%22%2C%0A%20%20%20%20%20%20%20%20%22controller%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%22blockOwnerDeletion%22%3A%20true%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%22spec%22%3A%20%7B%0A%20%20%20%20%22osImageURL%22%3A%20%22quay.io/openshift-release-dev/ocp-v4.0-art-dev%40sha256%3A210228123c8f7ff9f8aa528c270d7b491be230540e9b71a2fd8eaa894c27a7cf%22%2C%0A%20%20%20%20%22config%22%3A%20%7B%0A%20%20%20%20%20%20%22ignition%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22config%22%3A%20%7B%7D%2C%0A%20%20%20%20%20%20%20%20%22security%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22tls%22%3A%20%7B%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22timeouts%22%3A%20%7B%7D%2C%0A%20%20%20%20%20%20%20%20%22version%22%3A%20%222.2.0%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22networkd%22%3A%20%7B%7D%2C%0A%20%20%20%20%20%20%22passwd%22%3A%20%7B%7D%2C%0A%20%20%20%20%20%20%22storage%22%3A%20%7B%7D%2C%0A%20%20%20%20%20%20%22systemd%22%3A%20%7B%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22kernelArguments%22%3A%20%5B%5D%2C%0A%20%20%20%20%22fips%22%3A%20true%0A%20%20%7D%0A%7D%0A%0A"}}]}}
```
