### ISSUE TITLE
[Question] Any plan using openshift installer to install managed OCP services?

### ISSUE THREAD

**Issue by gyliu513** [openshift/installer#2637]
The `openshift-installer.sh` can support install OCP on many different Infra Clouds, like AWS, Azure, GCP etc, here I want to know what is the plan to enable the installer can support installing `managed OCP services`? 

Here the `managed OCP services` means OCP clusters hosted by some cloud providers, like [IBM Kubernetes Services](https://www.ibm.com/cloud/container-service) etc, with `managed OCP services`, the master nodes will be managed by the cloud provider but not by end user.

**Comment by gyliu513** [comment]
If we can enable this, then we can also use `hive` to manage the `managed ocp services` on different clouds. FYI @dgoodwin

**Comment by dgoodwin** [comment]
We are hoping to implement something for this in Hive, I do not know if it's planned to be integrated into the installer or not. CC @csrwng

**Comment by gyliu513** [comment]
Thanks @dgoodwin , does this already in hive roadmap or still under plan? I can see this also in cluster api scope based on discussion at https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/scope-and-objectives.md#glossary

**Comment by dgoodwin** [comment]
I think still in discussion as far as Hive is concerned, I'm not up to date on what's going on elsewhere for it. I will make sure to raise during our next planning round and see where we stand.

**Comment by abhinavdahiya** [comment]
Currently we don't plan to support hosted deployment using `openshift-install`.

/close
