### ISSUE TITLE
[RFE] Add nested virtualisation support in GCP

### ISSUE THREAD

**Issue by rgordill** [openshift/installer#2649]
# Version 4.2

```console
$ openshift-install version
openshift-install v4.2.4
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:cebce35c054f1fb066a4dc0a518064945087ac1f3637fe23d2ee2b0c433d6ba8
```

# Platform:
Google Cloud Platform

# What happened?
RHCOS created image does not support nested virtualisation in GCP.

# What you expected to happen?
RHCOS support nested virtualisation to be able to set up CNV in GCP by default.

For that, in https://github.com/openshift/installer/blob/master/data/data/gcp/main.tf#L96 image resouce creation should be added licenses as explained in: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

Reference on terraform provider: https://www.terraform.io/docs/providers/google/r/compute_image.html#licenses

# How to reproduce it (as minimally and precisely as possible)?
Always

**Comment by cgwalters** [comment]
xref https://github.com/coreos/coreos-assembler/blob/master/doc/openshift-gcp-nested-virt.md

Hmm.  It's not clear to me that we should do this by default; not all GCP OpenShift users want nested virt.  I think adding this license may perhaps limit the hardware/regions where one can run instances?  Or maybe it's just to track who is using it?  Not clear.

**Comment by cgwalters** [comment]
Basically, it's not difficult to do this manually, although it does poke somewhat into cluster "internals".  Perhaps a middle ground could be an install config option.

Why are you asking for this?  CI testing of CNV?  Or is this about e.g. kata containers?

If it's about CI for CNV, I think we should probably wait until actual customers ask for this.

**Comment by rgordill** [comment]
According with https://cloud.google.com/compute/docs/regions-zones/, it seems all regions default CPU selection are good for the minimum requirement of nested virtualisation, and the vms do not incur extra costs.

The scenario is to build an hybrid infra based on CNV rather than using one solution on GCP and another on bare metal in the DC.

It also helps a lot to set up easily a cluster on public cloud to start working with CNS before investing in hardware. And troubleshooting with a second infra.

**Comment by rgordill** [comment]
I agree if you know a little bit the internals, you can hack a little bit. Indeed, we recreate the image  with the license, and roll the machinesets to get the nested one in fresh new nodes.

I think it would be good if we give that hack to the users without digging in the process.
