### ISSUE TITLE
install/bootstrap abuses Endpoints for host-etcd

### ISSUE THREAD

**Issue by danwinship** [openshift/installer#2653]
Working on bringing up a single-stack IPv6 cluster, and I now have all nodes, pods, services, and endpoints coming up IPv6... except `openshift-etcd/host-etcd`.

As near as I can tell, the way that the `host-etcd` service works is that the installer writes out the hostnames of the etcd host to the `Endpoints` resource, along with fake IP addresses, because `Endpoints` need to have IP addresses, and then cluster-kube-apiserver-operator looks at the `Endpoints` object, completely ignores the fake IP addresses, and uses just the hostnames along with a special magic annotation.

I imagine this probably evolved out of something that made much more sense than this, but it really seems like it would be a lot simpler to have the installer just write out a configmap or something, rather than write out an Endpoints object where half of the data is fake, and one of the most important bits of information exists only in an annotation...

(This is not actually an IPv6 blocker because again, as far as I can tell, the addresses are write-only so it doesn't matter what they are. But it's really confusing...)

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/enhancements/pull/56/files#diff-bf3920b2d59626504dd416e30881dde3R213-R235

that is the goal for the endpoint.
cc @hexfusion
