### ISSUE TITLE
improve baremetal IPI installer log visibility

### ISSUE THREAD

**Issue by davidvossel** [openshift/installer#2679]
# Version

```console
openshift-baremetal-install v4.3.0
built from commit 0b98b56e96f2e56a12dcaf1860d3162294b07a82
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:adfedf4441ebb540ba65ef986575c61d9af5dc2ba771790873fc3609ff884f03
```
# Platform:
baremetal IPI

# What happened?

I apologize for not having the exact log messages I encountered available here. I'm filing this issue retroactively after having worked through debugging several baremetal IPI install failures.

During the process of performing the baremetal IPI install, I encountered multiple failures. All of these failures were either issues already solved by the installer team that required me to update the installer version, related to my environment that I needed to account for, or transient issues that were eventually resolved through "retrying" the install process. What I found through this process is that the installer gives very little visibility into what the source of a install failure is, primarily during the very early stages of bootstrapping the cluster.

Here are some examples of what I mean.

## Example 1, Libvirt errors not bubbling up to installer log.

At one point, baremetal IPI failed with an error along the lines of "timed out waiting for bootstrap VM to come online".

The installer spent something like 20-30 minutes waiting for this VM to come online before timing out. The reality is that the VM was never started because it lacked a required "default" storage volume which (rhel8) doesn't provide by default. The only way I figured this out was to find the VM definition the installer was waiting on, and executing ```virsh start <domain>``` manually to see why it wasn't online. Simple enough, but it took some detailed knowledge of how to debug libvirt to arrive at the real source of the timeout.

## Example 2. startironic.sh errors not bubbling up to installer log.

At another point, my baremetal IPI install failed with a generic "timed out waiting on ironic api" sort of error. What had happened is that a pod executed in the startironic.sh script had failed, but that took quite a bit of time to uncover. 

To discover the source of the error, I had to log into the bootstrap VM and search through the ```journal -u ironic``` log file. There were no obvious errors related to the download failure. I just happened to catch that a `podman wait` resulted in a `4` exit code instead of a `0` exit code. I then did a `podman logs` on that specific container and discovered that the container that downloads an image failed.

All the information the installer gave was a timeout error though.

## Example 3. errors during host provisioning

This one is tricky as the error was related to the process of provisioning the nodes with ironic. I had configured the wrong MAC address in my install-config.yaml for the bootstrap nic. The result is the nodes never fully completed the provisioning stage. Ironic would reboot the machines, they'd come online, and then nothing.

From the installer logs, I didn't get a clear understanding about where exactly the cluster was in the install process when it failed. Ironic was waiting on the hosts to heartbeat back (or something like that. my understanding is fuzzy), but apparently that failed because the hosts were contacting with a device using an unexpected MAC address (again i'm fuzzy on the specifics here). The only indication I had into the real source of the issue was watching the idrac console for one of the master nodes which had an ironic api call return a 400 error. 

From the installer logs, it wasn't obvious at what stage I was in the install process, and what exactly the installer process was waiting on when the failure occurred. All I had to go on was something like  "waiting for ironic on master-1, creating...." and a timeout error. It would be nice to know more detailed information about what condition the install process was waiting on before it could continue.

## Additional Info

In the end I was successful with performing the baremetal IPI install using the openshift installer. Greater visibility into installer failures, especially during the initial bootstrap process, would have made this a smoother process though.

**Comment by stbenjam** [comment]
Thanks for filing this! 

Some but not all of this should probably be addressed by https://github.com/openshift/installer/issues/2009

**Comment by stbenjam** [comment]
/lifecycle frozen

Let's keep this open, it's important that we address these concerns. Extracting more information from Ironic to bubble up to the user is especially important to avoid having to dig into the internals of the Metal3 implementation.

For example, if BMC credentials are invalid, the installer should inform the user as much. That's probably reported in last_error.

**Comment by stbenjam** [comment]
We've improved this quite a bit lately, with more details being bubbled up to users. Additional work should get bugzilla or jira RFE's and we'll take care of them as they come in.

/close
