### ISSUE TITLE
Openshift 4.2 support s3 storage

### ISSUE THREAD

**Issue by Bahu2016** [openshift/installer#2715]
Openshift 4.2 support s3 storage? i didn't find document says it will support

**Comment by faust64** [comment]
As of OpenShift 4, CSI should be used setting up storage providers. Didn't check s3 just yet, though it should be doable.

Here's a CSI implementation for s3: https://github.com/ctrox/csi-s3

Or using rook, which would probably be recommended with OpenShift 4, looks like they have something as well: https://rook.io/docs/rook/v0.9/edgefs-s3x-crd.html

**Comment by go2sekhar** [comment]
Thanks Samuel.

I will take a look on this.

**Comment by go2sekhar** [comment]
Samuel,

on 3.11 below variable are using for object storage configuration, do we have anything on 4.2.

# Any S3 service (Minio, ExoScale, ...): 
# but with regionendpoint configured
# S3 bucket must already exist.
#openshift_hosted_registry_storage_kind=object
#openshift_hosted_registry_storage_provider=s3
#openshift_hosted_registry_storage_s3_accesskey=access_key_id
#openshift_hosted_registry_storage_s3_secretkey=secret_access_key
#openshift_hosted_registry_storage_s3_regionendpoint=https://myendpoint.example.com/
#openshift_hosted_registry_storage_s3_bucket=bucket_name
#openshift_hosted_registry_storage_s3_region=bucket_region
#openshift_hosted_registry_storage_s3_chunksize=26214400
#openshift_hosted_registry_storage_s3_rootdirectory=/registry
#openshift_hosted_registry_pullthrough=true
#openshift_hosted_registry_acceptschema2=true
#openshift_hosted_registry_enforcequota=true

**Comment by Bahu2016** [comment]
Am not using Amazon s3, looking for other than Amazon s3.

**Comment by abhinavdahiya** [comment]
> Openshift 4.2 support s3 storage? i didn't find document says it will support

can you provide details on which component you are referring to in regards to the S3 support. OpenShift Internal Registry ??

@Bahu2016

**Comment by Bahu2016** [comment]
I want to use object storage for Block, NAS and for registry purpose.

**Comment by Bahu2016** [comment]
We have Cloudian and want to use for Block, NAS and registry purpose.

**Comment by abhinavdahiya** [comment]
Here are the docs for configuring registry in OpenShift 4 https://docs.openshift.com/container-platform/4.2/registry/architecture-component-imageregistry.html

if you have more questions.. best place to get answers is https://github.com/openshift/cluster-image-registry-operator/issues

> Block, NAS

It would be great if you can provide more details on how you configure that in 3.11 or K8S in general so that we can point you in the right direction.

**Comment by Bahu2016** [comment]
on 3.11 we have trident for dynamic provision with storage class Block and NAS.

And i did the trident setup on 4.2 and worked great. But looking into Object Storage, for similar to trident configuration.

**Comment by abhinavdahiya** [comment]
>  3.11 we have trident for dynamic provision with storage class Block and NAS.
so I'm hoping you are talking about https://github.com/NetApp/trident ...

> And i did the trident setup on 4.2 and worked great. But looking into Object Storage, for similar to trident configuration.
So you want to configure Object Storage using trident ?? Or are you trying to configure object storage based Storage class ??

**Comment by Bahu2016** [comment]
Trident mainly for Netapp storage, not sure if that supports for object storage.

trying to configure object storage based Storage class ?? this is what am looking.

**Comment by abhinavdahiya** [comment]
> trying to configure object storage based Storage class ?? this is what am looking.

https://docs.openshift.com/container-platform/4.2/storage/dynamic-provisioning.html#available-plug-ins_dynamic-provisioning

It doesn't look like we support S3 based dynamic storage class..

and doesn't look like upstream k8s supports such a thing too.. https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by Bahu2016** [comment]
Is there any future plan to include S3 based dynamic Storage Class?

**Comment by abhinavdahiya** [comment]
> Is there any future plan to include S3 based dynamic Storage Class?

I think that is best tracked https://github.com/openshift/community in that repo.

**Comment by gnufied** [comment]
We aren't planning to add object storage to core Openshift product. However - it should be possible to use something like rook - https://rook.io/docs/rook/v0.8/object.html or any other storage product that supports object storage on Kubernetes/Openshift.

**Comment by abhinavdahiya** [comment]
> > Is there any future plan to include S3 based dynamic Storage Class?
> 
> I think that is best tracked https://github.com/openshift/community in that repo.

> We aren't planning to add object storage to core Openshift product. However - it should be possible to use something like rook - https://rook.io/docs/rook/v0.8/object.html or any other storage product that supports object storage on Kubernetes/Openshift.

If there isn't anything else, please feel free to close the issue @Bahu2016

**Comment by abhinavdahiya** [comment]
> > > Is there any future plan to include S3 based dynamic Storage Class?
> > 
> > 
> > I think that is best tracked https://github.com/openshift/community in that repo.
> 
> > We aren't planning to add object storage to core Openshift product. However - it should be possible to use something like rook - https://rook.io/docs/rook/v0.8/object.html or any other storage product that supports object storage on Kubernetes/Openshift.
> 
> If there isn't anything else, please feel free to close the issue @Bahu2016
