### ISSUE TITLE
Openstack: Cannot create coredns container: executable file not found in $PATH

### ISSUE THREAD

**Issue by ppeereb1** [openshift/installer#2716]
Hi community,

A few weeks ago I have successfully created a openshift 4 cluster. Today I tried to redeploy the environment, but it seems it fails to setup coredns which is why it tries to resolve to the external dns only:

`[core@os-test-29g6b-bootstrap ~]$   journalctl -b -f -u bootkube.service
-- Logs begin at Mon 2019-11-25 12:50:40 UTC. --
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: {"level":"warn","ts":"2019-11-25T13:14:43.906Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-b340ecb9-82d5-49b2-8a19-935a8d9afe20/etcd-2.os-test.novalocal:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup etcd-2.os-test.novalocal on 8.8.4.4:53: no such host\""}
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: {"level":"warn","ts":"2019-11-25T13:14:43.906Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-4a93c208-fe3c-47b6-a987-9858cb34bda0/etcd-1.os-test.novalocal:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup etcd-1.os-test.novalocal on 8.8.4.4:53: no such host\""}
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: {"level":"warn","ts":"2019-11-25T13:14:43.906Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-62f4e137-d8d3-403e-8ea5-29f79f149727/etcd-0.os-test.novalocal:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup etcd-0.os-test.novalocal on 8.8.4.4:53: no such host\""}
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: https://etcd-2.os-test.novalocal:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: https://etcd-1.os-test.novalocal:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: https://etcd-0.os-test.novalocal:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 25 13:14:43 os-test-29g6b-bootstrap bootkube.sh[2847]: Error: unhealthy cluster
`

Cannot talk to api:
`
[root@os-test-29g6b-bootstrap ~]# oc --config=/var/opt/openshift/auth/kubeconfig --namespace=openshift-machine-api get deployments
Unable to connect to the server: dial tcp: lookup api-int.os-test.novalocal on 8.8.4.4:53: no such host
`

crictl logs:
`
[root@os-test-29g6b-bootstrap ~]# sudo crictl logs $(sudo crictl ps --pod=$(sudo crictl pods --name=etcd-member --quiet) --quiet)
I1125 12:53:29.309784       1 bootstrap.go:37] Version: machine-config-daemon-4.3.0-201910221717-34-g56c91185-dirty (56c91185b2344912558730bca6273dd85681dd31)
I1125 12:53:29.309926       1 api.go:51] Launching server on :22624
I1125 12:53:29.309992       1 api.go:51] Launching server on :22623
2019/11/25 13:04:16 http: TLS handshake error from 10.0.0.13:56046: remote error: tls: unknown certificate authority
I1125 13:04:19.134117       1 api.go:97] Pool master requested by 10.0.0.13:56048
I1125 13:04:19.134146       1 bootstrap_server.go:62] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I1125 13:04:19.135711       1 bootstrap_server.go:82] reading file "/etc/mcs/bootstrap/machine-configs/rendered-master-8bcdb475514f589a01245edd3d4fbf32.yaml"
`

No etcd is running:
`
[root@os-test-29g6b-bootstrap ~]# sudo crictl pods --name=etcd-member
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT
`

coredns failed to start(kubelet.log):
`
from runtime service failed: rpc error: code = Unknown desc = container create failed: container_linux.go:345: starting container process caused "exec: \"runtimecfg\": executable file not found in $PATH"
Nov 25 13:21:23 os-test-29g6b-bootstrap hyperkube[2828]: E1125 13:21:23.769829    2828 kuberuntime_manager.go:783] init container start failed: CreateContainerError: container create failed: container_linux.go:345: starting container process caused "exec: \"runtimecfg\": executable file not found in $PATH"
Nov 25 13:21:23 os-test-29g6b-bootstrap hyperkube[2828]: E1125 13:21:23.769873    2828 pod_workers.go:191] Error syncing pod 169fedefe78a1962650a77e30319b858 ("coredns-os-test-29g6b-bootstrap_openshift-openstack-infra(169fedefe78a1962650a77e30319b858)"), skipping: failed to "StartContainer" for "render-config" with CreateContainerError: "container create failed: container_linux.go:345: starting container process caused \"exec: \\\"runtimecfg\\\": executable file not found in $PATH\"\n"
`

Using CoreDNS image: registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:9a7e8297f7b70ee3a11fcbe4a78c59a5861e1afda5657a7437de6934bdc2458e

install-config.yaml:
`
apiVersion: v1
baseDomain: novalocal
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
  replicas: 3
metadata:
  creationTimestamp: null
  name: os-test
networking:
  clusterNetwork:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.132.0.0/16
platform:
  openstack:
    cloud: openshift-pauldev
    computeFlavor: m1.4large
    externalDNS:
    - 8.8.4.4
    - 8.8.8.8
    externalNetwork: OS-PRD-Internet
    lbFloatingIP: <ip>
    octaviaSupport: "0"
    region: Region
    trunkSupport: "0"
pullSecret: <pullsecret>
`

edit:
I think there are some references to this branch: https://github.com/openshift/baremetal-runtimecfg . Maybe I have a mismatch in versions somehow. This utility is for baremetal deployments only so should this utitily be called in the first place?

Is this a known issue? What can I do to fix this?

Thanks for your help!
Paul

**Comment by ppeereb1** [comment]
I think there are some references to this new branch: https://github.com/openshift/baremetal-runtimecfg . Maybe I have a mismatch in versions somehow?

**Comment by mandre** [comment]
Hey @ppeereb1, this seems to be caused by a bogus release image.

I assume you built the installer from source. Could you give it a try with a release image coming from `registry.svc.ci.openshift.org/ocp` instead of `registry.svc.ci.openshift.org/origin`?
If you want to keep the installer yourself, you could `export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="registry.svc.ci.openshift.org/ocp/release:4.3"` before running the installer.

Or you could also download a pre-built installer binary from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/.

Hope this helps.

**Comment by ppeereb1** [comment]
Hi @mandre , you're right it seems to be a bogus image. After I deploy it with https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.3/ it seems to be running okay. Thanks a lot for pointing to the link. I will close this issue because it seems to be unrelated to the installer.
Regards,
Paul
