### ISSUE TITLE
"openshift-install" cannot be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by wgordon17** [openshift/installer#2722]
# Version

```console
$ openshift-install version
./openshift-install v4.2.5
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:bac62983757570b9b8f8bc84c740782984a255c16372b3e30cfc8b52c0a187b9
```

# Device:
macOS Catalina
Version 10.15.1

# What happened?

When trying to open `./openshift-install`, the action is blocked with a pop error message

![image](https://user-images.githubusercontent.com/22222756/69666232-ec406b80-1059-11ea-906e-0dcc85553f96.png)

# What you expected to happen?

No error message

# How to reproduce it (as minimally and precisely as possible)?

Download from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/

```console
$ ./openshift-install
```

# Anything else we need to know?

This can be worked around via: https://support.apple.com/en-us/HT202491
However "unidentified developer" is an unfortunate thing to see for any new customers

# References

None that I found

**Comment by wking** [comment]
Try downloading installers from the product page (e.g. [here][1]) instead of using the mirrors.  I *think* the macOS and Windows binaries there have OS signatures injected after they're extracted from the release image, but I don't have access to either OS available to test right now.

[1]: https://access.redhat.com/downloads/content/290/ver=4.2/rhel---8/4.2.8/x86_64/product-software

**Comment by wking** [comment]
Binaries are different, in any case, with 86e5896f5c423157deaa572b9e756912df0ea1b8 as the SHA-1 of the mirrored Mac `oc` and d506c486d9d4c9c2a6c4e8e2cf5148f50d92c2db as the SHA-1 of the release-page Mac `oc`.

**Comment by wking** [comment]
Above SHA-1s are for 4.2.8.  Comparing:

```console
$ diff -U1 <(hexdump -vC mirror-oc) <(hexdump -vC release-page-oc)
...
+051d7fa0  2e 06 03 55 04 03 0c 27  41 70 70 6c 65 20 54 69  |...U...'Apple Ti|
+051d7fb0  6d 65 73 74 61 6d 70 20  43 65 72 74 69 66 69 63  |mestamp Certific|
+051d7fc0  61 74 69 6f 6e 20 41 75  74 68 6f 72 69 74 79 31  |ation Authority1|
+051d7fd0  26 30 24 06 03 55 04 0b  0c 1d 41 70 70 6c 65 20  |&0$..U....Apple |
+051d7fe0  43 65 72 74 69 66 69 63  61 74 69 6f 6e 20 41 75  |Certification Au|
+051d7ff0  74 68 6f 72 69 74 79 31  13 30 11 06 03 55 04 0a  |thority1.0...U..|
+051d8000  0c 0a 41 70 70 6c 65 20  49 6e 63 2e 31 0b 30 09  |..Apple Inc.1.0.|
...
```

Looks promising, anyway.  Still don't have a way to test and ensure the sig is actually valid.

**Comment by wgordon17** [comment]
Same issue for 4.2.7

![image](https://user-images.githubusercontent.com/22222756/69749390-6800ed80-1118-11ea-878d-33d7b501733b.png)

I'm unable to test with 4.2.8 `openshift-install` currently

**Comment by smarterclayton** [comment]
This is “expected” behavior because we don’t sign the binaries before they are in the payload.  The binaries in the red hat portal *should* be signed.

**Comment by wking** [comment]
Closing this because signing binaries for the portal is an RCM thing, not an installer thing.  If there are issues with portal binaries, follow up with RCM.

/close

**Comment by jdbaptist** [comment]
This helped me execute whatever I want on my Mac.. 

https://macpaw.com/how-to/allow-apps-anywhere

**Comment by c3d** [comment]
Same problem with a developper release from https://console.redhat.com/openshift/install/multi/pre-release
