### ISSUE TITLE
OpenShift 4.2 baremetal install fails

### ISSUE THREAD

**Issue by vinothkumar437** [openshift/installer#2732]
Attaching screenshot please help me to resolve it.

**From Master Node**

![master](https://user-images.githubusercontent.com/32629725/69809209-48002580-120f-11ea-90bf-ab21014c669a.JPG)

**From Worker Node**

![worker](https://user-images.githubusercontent.com/32629725/69809279-6a923e80-120f-11ea-94b9-ac3b1a94cfe3.JPG)

Please let me know, if any other details are required.

**Comment by abhinavdahiya** [comment]
we have an issue template https://github.com/openshift/installer/blob/master/.github/ISSUE_TEMPLATE.md that asks users some basic information like what version of the installer, which commands did you run, the `install-config.yaml` (if used), attaching `.openshift_install.log` file etc.

So if you can provide those details that would help.

**Comment by vinothkumar437** [comment]
time="2019-12-03T02:55:26+05:30" level=debug msg="Generating \"Metadata\"..."
time="2019-12-03T03:03:09+05:30" level=debug msg="OpenShift Installer v4.2.4"
time="2019-12-03T03:03:09+05:30" level=debug msg="Built from commit 425e4ff0037487e32571258640b39f56d5ee5572"
time="2019-12-03T03:03:09+05:30" level=info msg="Waiting up to 30m0s for the Kubernetes API at https://api.test.example.c             om:6443..."
time="2019-12-03T03:03:09+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:             6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:03:39+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:             6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:04:09+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:04:39+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:05:09+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:05:39+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:06:09+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"
time="2019-12-03T03:06:39+05:30" level=debug msg="Still waiting for the Kubernetes API: Get https://api.test.example.com:6443/version?timeout=32s: http: server gave HTTP response to HTTPS client"

**Comment by vinothkumar437** [comment]
openshift-install --dir=dir01/ wait-for bootstrap-complete --log-level=info

[root@bootstrap-0 install]# cat install-config.yaml
apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"bootstrap-0.example.com:5000": {"auth": "ZHVtbXk6ZHVtbXk="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDU3o5UQtW/2VTcoadDP1tKa97zaH8fNWmRlsT2WlnAtwwik91pTfZ1Iowmn40TmPenyVC66GS5qOQUE0qqb3Jdtf9/ayZJRXfMrMeYfyivJ9vujVML9O3KlFzQgOXXaPSeGlDFp9GNK06dQExb0SO8RvcAEWKjo+tz8A8imMhidP0jF9nS+DMAZpRgp3aLh1gkzQvou/jwjJkuEWn89aBDLZQAOlNI+Ex1BdL3ZgZNKpz/pvK2Hx6Oezu1rnIXrFBRHRwUMPqeeAdgbfh/xsZ9SKpoiwAUGFiYMFccXWp0eg8HchJ+fIjs2asyAzEzFeMukcWQ7Bng7kwMH8MyR329 root@bootstrap-0.example.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIF7zCCA9egAwIBAgIUIhVaf41IedpJggg41BcyZPckayAwDQYJKoZIhvcNAQEL
  BQAwgYYxCzAJBgNVBAYTAklOMQswCQYDVQQIDAJLQTEMMAoGA1UEBwwDQkxFMQww
  CgYDVQQKDANBQkMxDDAKBgNVBAsMA0NDRDEgMB4GA1UEAwwXYm9vdHN0cmFwLTAu
  ZXhhbXBsZS5jb20xHjAcBgkqhkiG9w0BCQEWD2FkbWluQGxvY2FsLmNvbTAeFw0x
  OTExMjYxOTQyMTVaFw0yMDExMjUxOTQyMTVaMIGGMQswCQYDVQQGEwJJTjELMAkG
  A1UECAwCS0ExDDAKBgNVBAcMA0JMRTEMMAoGA1UECgwDQUJDMQwwCgYDVQQLDAND
  Q0QxIDAeBgNVBAMMF2Jvb3RzdHJhcC0wLmV4YW1wbGUuY29tMR4wHAYJKoZIhvcN
  AQkBFg9hZG1pbkBsb2NhbC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
  AoICAQC86S/xhW/OuZyC9UjoD5+qFmD7JE07ywnxvb8jhpLw8oue+wTJu46I1t9m
  RrKnPEs74Nab8FzV23tsQWLmi07KmbkzI55X9YaeUToN0a2/KYnaY16+Kwl5dalp
  ikwcmZNZZIvETYy/Saw7/jUoALWL25F3AtbqHS8OD07L+CQyQgh4Q5K2EE7Pa3Cv
  ZsTpNhQIPxEJJtG83l10gxU9fzl8OBOi0dexohXjY7wIQhu8T+E5VhylHcQhmfU/
  7pBwtTTwBI2apTfWgEZn8vYy4E0jZ3ZRDCmN5QKKPLJQm8NaQYyo+gsgEBaA2P3C
  m0x6z/OPKpdvlsCf0GZYTMWvC5LNERrWuiXZLEGSrs2OtrpI7B3kwI2pwzErij1f
  tib9Ue07LpBz9jvwX1BcMtxrdcM8ww9OkY55bcJcLyqGCm90ukfKJM7N4M/IlvN0
  19Ohc88Xb2sYR06Ukw6Sc4ndkUPIbuvt8wpdfcSmU6on+mXsYLENC5Q2xKG3Z0St
  6F8ncrOBi4A+bZWkHEPf/v2wsZFZjyG2gvQFrVtIJDHZWHAMKEwfjLJIz2odjMnh
  DzgJflydYIzOaca57cz+yX0dHktP7zFpRCTk6gYt7WX5kOjTxfojNfZN8zO337Nx
  zxMCBVD3cWnXZUGTVqFYTPvTUdLtptgkUmknX+KHkZ4Qrk0/6QIDAQABo1MwUTAd
  BgNVHQ4EFgQUvl/3+CjcrBBqn4l8yq0nmM7BUuwwHwYDVR0jBBgwFoAUvl/3+Cjc
  rBBqn4l8yq0nmM7BUuwwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
  AgEALIOX17dhnjBFm5UTWcHGheuC5X4lul4DcjazX+p4nQt4XCuzsXFu6BMcbGoN
  T7Svs+Z1Ov2d8/6SYyiTTtTnr+ViS5m68SbWbaU08G1ZhzBd6g+BQaLRx+8zMttI
  cIIq9YvE4ZjPmv51Qssr54s8L/Ldr2lJyWEHLZfLaG2y+HLbIdEyPCgo2ZUbDyme
  AxbX3V6TRhb6WOEsiSRwAfSfIothswh1+iIpN6nEu/uLVu2GAxDuwWlD19+z+F4F
  essCT9wvxBDzrSnS+5fpz+/2JeOGDaY7RUS/h+SAN3t7aq8JZ3J+2+F9wFowWe1c
  4Us7EpxCIzXO5cjBq8flA2q5OfcfRV6deyUsylb5oO23AiTrHMa/lucNvVHowd94
  w0/6TUDTbO7F0pMRVgJID/IuGUJ01/1rCbJ/pO15wSTbOA3kVrNN0NjIUw4l8ysU
  XgUfIbiLtCbzKCgXkI6I8iHtAMe1+sA5KwptmHO7NigFEbRpQLt6ERxDYh/m9gbA
  bpNTWzBfTCHcGzQPfwW29F50UEbryJ9NERQwcgDkfxFQfUmG5tnGTTMdt+SqKZLY
  9O+bO8NuM41GK69oQQzljqrj+m/nsW31iZR0ss9ehcH/+Hg13/aBktWuwYR2DpIA
  TBz3dS8Pe6+iuZX+WvEMP+lHvLXh48uJw4oiCFXJnyJhniw=
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - bootstrap-0.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - bootstrap-0.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
[root@bootstrap-0 install]#

**Comment by vinothkumar437** [comment]
please find the requested information, please help me to resolve this issue.

Regards
Vinothkumar P

**Comment by abhinavdahiya** [comment]
>  https://github.com/openshift/installer/issues/2732#issuecomment-560462912

updated the comment for clearer install-config.yaml

```
openshift-install --dir=dir01/ wait-for bootstrap-complete --log-level=info
```
```
[root@bootstrap-0 install]# cat install-config.yaml
apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"bootstrap-0.example.com:5000": {"auth": "ZHVtbXk6ZHVtbXk="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDU3o5UQtW/2VTcoadDP1tKa97zaH8fNWmRlsT2WlnAtwwik91pTfZ1Iowmn40TmPenyVC66GS5qOQUE0qqb3Jdtf9/ayZJRXfMrMeYfyivJ9vujVML9O3KlFzQgOXXaPSeGlDFp9GNK06dQExb0SO8RvcAEWKjo+tz8A8imMhidP0jF9nS+DMAZpRgp3aLh1gkzQvou/jwjJkuEWn89aBDLZQAOlNI+Ex1BdL3ZgZNKpz/pvK2Hx6Oezu1rnIXrFBRHRwUMPqeeAdgbfh/xsZ9SKpoiwAUGFiYMFccXWp0eg8HchJ+fIjs2asyAzEzFeMukcWQ7Bng7kwMH8MyR329 root@bootstrap-0.example.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIF7zCCA9egAwIBAgIUIhVaf41IedpJggg41BcyZPckayAwDQYJKoZIhvcNAQEL
  BQAwgYYxCzAJBgNVBAYTAklOMQswCQYDVQQIDAJLQTEMMAoGA1UEBwwDQkxFMQww
  CgYDVQQKDANBQkMxDDAKBgNVBAsMA0NDRDEgMB4GA1UEAwwXYm9vdHN0cmFwLTAu
  ZXhhbXBsZS5jb20xHjAcBgkqhkiG9w0BCQEWD2FkbWluQGxvY2FsLmNvbTAeFw0x
  OTExMjYxOTQyMTVaFw0yMDExMjUxOTQyMTVaMIGGMQswCQYDVQQGEwJJTjELMAkG
  A1UECAwCS0ExDDAKBgNVBAcMA0JMRTEMMAoGA1UECgwDQUJDMQwwCgYDVQQLDAND
  Q0QxIDAeBgNVBAMMF2Jvb3RzdHJhcC0wLmV4YW1wbGUuY29tMR4wHAYJKoZIhvcN
  AQkBFg9hZG1pbkBsb2NhbC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
  AoICAQC86S/xhW/OuZyC9UjoD5+qFmD7JE07ywnxvb8jhpLw8oue+wTJu46I1t9m
  RrKnPEs74Nab8FzV23tsQWLmi07KmbkzI55X9YaeUToN0a2/KYnaY16+Kwl5dalp
  ikwcmZNZZIvETYy/Saw7/jUoALWL25F3AtbqHS8OD07L+CQyQgh4Q5K2EE7Pa3Cv
  ZsTpNhQIPxEJJtG83l10gxU9fzl8OBOi0dexohXjY7wIQhu8T+E5VhylHcQhmfU/
  7pBwtTTwBI2apTfWgEZn8vYy4E0jZ3ZRDCmN5QKKPLJQm8NaQYyo+gsgEBaA2P3C
  m0x6z/OPKpdvlsCf0GZYTMWvC5LNERrWuiXZLEGSrs2OtrpI7B3kwI2pwzErij1f
  tib9Ue07LpBz9jvwX1BcMtxrdcM8ww9OkY55bcJcLyqGCm90ukfKJM7N4M/IlvN0
  19Ohc88Xb2sYR06Ukw6Sc4ndkUPIbuvt8wpdfcSmU6on+mXsYLENC5Q2xKG3Z0St
  6F8ncrOBi4A+bZWkHEPf/v2wsZFZjyG2gvQFrVtIJDHZWHAMKEwfjLJIz2odjMnh
  DzgJflydYIzOaca57cz+yX0dHktP7zFpRCTk6gYt7WX5kOjTxfojNfZN8zO337Nx
  zxMCBVD3cWnXZUGTVqFYTPvTUdLtptgkUmknX+KHkZ4Qrk0/6QIDAQABo1MwUTAd
  BgNVHQ4EFgQUvl/3+CjcrBBqn4l8yq0nmM7BUuwwHwYDVR0jBBgwFoAUvl/3+Cjc
  rBBqn4l8yq0nmM7BUuwwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
  AgEALIOX17dhnjBFm5UTWcHGheuC5X4lul4DcjazX+p4nQt4XCuzsXFu6BMcbGoN
  T7Svs+Z1Ov2d8/6SYyiTTtTnr+ViS5m68SbWbaU08G1ZhzBd6g+BQaLRx+8zMttI
  cIIq9YvE4ZjPmv51Qssr54s8L/Ldr2lJyWEHLZfLaG2y+HLbIdEyPCgo2ZUbDyme
  AxbX3V6TRhb6WOEsiSRwAfSfIothswh1+iIpN6nEu/uLVu2GAxDuwWlD19+z+F4F
  essCT9wvxBDzrSnS+5fpz+/2JeOGDaY7RUS/h+SAN3t7aq8JZ3J+2+F9wFowWe1c
  4Us7EpxCIzXO5cjBq8flA2q5OfcfRV6deyUsylb5oO23AiTrHMa/lucNvVHowd94
  w0/6TUDTbO7F0pMRVgJID/IuGUJ01/1rCbJ/pO15wSTbOA3kVrNN0NjIUw4l8ysU
  XgUfIbiLtCbzKCgXkI6I8iHtAMe1+sA5KwptmHO7NigFEbRpQLt6ERxDYh/m9gbA
  bpNTWzBfTCHcGzQPfwW29F50UEbryJ9NERQwcgDkfxFQfUmG5tnGTTMdt+SqKZLY
  9O+bO8NuM41GK69oQQzljqrj+m/nsW31iZR0ss9ehcH/+Hg13/aBktWuwYR2DpIA
  TBz3dS8Pe6+iuZX+WvEMP+lHvLXh48uJw4oiCFXJnyJhniw=
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - bootstrap-0.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - bootstrap-0.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
[root@bootstrap-0 install]#
```


> please find the requested information, please help me to resolve this issue.
> time="2019-12-03T03:03:09+05:30" level=debug msg="OpenShift Installer v4.2.4"

@vinothkumar437 you should be able to grab the logs from failed bootstrap-host using the commands.. 

```sh
openshift-install gather bootstrap --bootstrap <bootstrap-host-ip> --master <control-plane-0-ip> [--master <control-plane-$idx-ip> ]
```

If you can provide the log bundle we should be able to help further.

**Comment by abhinavdahiya** [comment]
Closing since it's been few weeks and there isn't information for debugging. Please reopen or consider opening a new issue with requested details.
