### ISSUE TITLE
How is static IP being injected into the VM?

### ISSUE THREAD

**Issue by bortek** [openshift/installer#2733]
Can anyone shed some light how this part of injecting a "/etc/sysconfig/network-scripts/ifcfg-ens192" file into the VM is supposed to work? Code snippet is from machine/ignition.tf file.

data "ignition_file" "static_ip" {
  count = "${var.instance_count}"

  filesystem = "root"
  path       = "/etc/sysconfig/network-scripts/ifcfg-ens192"
  mode       = "420"

  content {
    content = <<EOF
TYPE=Ethernet
BOOTPROTO=none
NAME=ens192
DEVICE=ens192
ONBOOT=yes
IPADDR=${local.ip_addresses[count.index]}
PREFIX=${local.mask}
GATEWAY=${local.gw}
DOMAIN=${var.cluster_domain}
DNS1=129.178.2.1
DNS2=129.178.7.161
EOF
  }
}

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/blob/master/.github/ISSUE_TEMPLATE.md provides sections that help us get good information about an issue.. one of the important sections what happended and what did you expect to happen would have provided a good starting point for us to help you.

/cc @jcpowermac @dav1x
