### ISSUE TITLE
AWS: Add new default vCPU limit to docs

### ISSUE THREAD

**Issue by sapkra** [openshift/installer#2736]
# Version
```console
$ openshift-install version
openshift-install unreleased-master-2025-g23f40299a6ab4f4f9bfbfd1ec1d15dfab90a6ecf-dirty
built from commit 23f40299a6ab4f4f9bfbfd1ec1d15dfab90a6ecf
release image quay.io/openshift/okd@sha256:5d2e42d555d24bb1a60d20eb03ae7e288f4347cad6a68c5428d00598c5816678
```

# Platform:
aws

# What happened?
I've tried installing OKD on AWS using the new installer but I got some error related to vCPU limits.

```
Error: Error launching source instance: VcpuLimitExceeded: You have requested more vCPU capacity than your current vCPU limit of 1 allows for the instance bucket that the specified instance type belongs to. Please
 visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.
```

After some googling I've found this:
https://aws.amazon.com/about-aws/whats-new/2019/09/vcpu-based-on-demand-instance-limits-are-now-available-in-amazon-ec2/
https://aws.amazon.com/ec2/faqs/#EC2_On-Demand_Instance_limits

# What you expected to happen?
The docs for AWS should mention that the default installer config is not matching the default AWS limits anymore and that the vCPU limit has to be manually increased.

# How to reproduce it?
Just try to deploy a new cluster to AWS with an account without increased vCPU limits. So for example with a new account.

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/blob/master/docs/user/aws/limits.md#instance-limits

we have docs that provide a heads up. For detailed and newer AWS limits docs we will look at improving them.

Pull Requests welcome for updating the docs!
