### ISSUE TITLE
baremetal: etcd no longer uses SRV records

### ISSUE THREAD

**Issue by stbenjam** [openshift/installer#2740]
In 4.4, the default mechanism will be to bring up a single etcd master and then scale out to 3. SRV records are no longer used for bootstrapping etcd. 

This means some code in the installer for the baremetal platform may no longer be needed, we should clean up that code as needed and make any required changes in light of that change.

See: https://github.com/openshift/installer/pull/2730

**Comment by stbenjam** [comment]
FYI

/cc @celebdor 
/cc @cybertron

**Comment by hexfusion** [comment]
> In 4.4, the default mechanism will be to bring up a single etcd master and then scale out to 3. SRV records are no longer used.

To be clear they are no longer used to bootstrap etcd but we still will need SRV records for 4.4 at this time.

**Comment by stbenjam** [comment]
> > In 4.4, the default mechanism will be to bring up a single etcd master and then scale out to 3. SRV records are no longer used.
> 
> To be clear they are no longer used to bootstrap etcd but we still will need SRV records for 4.4 at this time.

Ah thanks, I see. I updated the description, based on my understanding of how we create those SRV records for baremetal IPI, it may still simplify some things for us.
