### ISSUE TITLE
Ignition failed! unsupported config version in Openshift 4.3

### ISSUE THREAD

**Issue by zhongjun2** [openshift/installer#2755]
I got an error "ignition[1149]: failed to fetch config: unsupported config version" after create a vm with user_data, when I install openshift 4.3 in openstack.

env:
Install openshift 4.3 in openstack platform

image:
848bb39d21be13325153e5b6dc1e2170c5acd67a8b0d3926d4e4a04c72810255  rhcos-43.81.201912030353.0-openstack.x86_64.qcow2.gz

When I use the follow command to boot master vm: "openshift-9rxg2-master-0", "openshift-9rxg2-master-1", "openshift-9rxg2-master-2". I got the following errors:

ignition[1149]: GET https://10.0.2.5:22623/config/master attempt #1
ignition[1149]: GET result: OK
ignition[1149]: failed to fetch config: unsupported config version
ignition[1149]: failed to acquire config: unsupported config version

I login to openshift-9rxg2-bootstrap vm, I get the https://10.0.2.5:22623/config/master config file:

{
	"ignition": {
		"config": {
			"replace": {
				"source": null,
				"verification": {}
			}
		},
		"security": {
			"tls": {}
		},
		"timeouts": {},
		"version": "3.0.0"
....

The ignition version is 3.0.0.

Is this a bug in rhcos-43.81.201912030353.0-openstack.x86_64.qcow2.gz image?

**Comment by abhinavdahiya** [comment]
Can you include the version of the installer?

Also if you used a installer binary built from branches in the repo and not the mirrors (https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/), this error might be because of https://github.com/openshift/installer/issues/2632

**Comment by LorbusChris** [comment]
Ignition Spec Version 3 is not supported by OpenShift 4.3, it needs 2.x

**Comment by zhongjun2** [comment]
@abhinavdahiya I build the installer by myself.   The master branch openshift-installer code

**Comment by zhongjun2** [comment]
# openshift-install version
openshift-install unreleased-master-2157-gf478dc13d5c41e83c86f4fd9b40bc10924270701-dirty
built from commit f478dc13d5c41e83c86f4fd9b40bc10924270701
release image registry.svc.ci.openshift.org/origin/release:4.3

**Comment by LorbusChris** [comment]
`registry.svc.ci.openshift.org/origin/release:4.3` points to OKD. Please build your installer from the `fcos` branch. That should fix your issue :)

**Comment by cfBrianMiller** [comment]
The FCOS branch doesn't support the azure platform. What branch supports azure and is targeted towards openshift?

**Comment by LorbusChris** [comment]
Azure support has not yet been re-added to the OKD community variant. It is supported in the OCP product, though.

**Comment by cfBrianMiller** [comment]
Which branches are targeted towards OCP?

**Comment by abhinavdahiya** [comment]
the only supported way for OCP is using the instructions like https://docs.openshift.com/container-platform/4.2/installing/installing_aws/installing-aws-default.html#installation-obtaining-installer_installing-aws-default

You can also find the binaries at 
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
or
https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/

**Comment by jichenjc** [comment]
The release doesn't support libvirt
 and I switched to fcos branch and it doesn't work either,
the coreos enter emergency mode... will try again and paste logs

**Comment by zhongjun2** [comment]
After I switched to fcos branch, the ignition version still be 3.0.0.
	"ignition": {
		"timeouts": {},
		"security": {
			"tls": {}
		},
		"version": "3.0.0",
		"config": {
			"replace": {
				"source": null,
				"verification": {}
			}
		}
	}

**Comment by LorbusChris** [comment]
yes, that is expected, OKD (the fcos branch) uses spec v3

**Comment by zhongjun2** [comment]
@LorbusChris But [rhcos](https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/) image doesn't support uses spec ignition v3.

https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/

**Comment by LorbusChris** [comment]
OKD uses FCOS as base OS, please refer to https://github.com/openshift/okd/blob/master/README.md#getting-started

**Comment by zhongjun2** [comment]
@LorbusChris The OKD is community version, The OCP is product version.
The OKD uses Fedora CoreOS image for openstack,  The OCP uses rhcos(rhcos-43.81.201912030353.0-openstack.x86_64.qcow2.gz) image for openstack.
The OKD uses fcos branch (openshift/installer),  The OCP uses master branch(openshift/installer).

The OKD openshift-installer version (builded by myself) is "release image registry.svc.ci.openshift.org/origin/release:4.3".

The OCP openshift-installer version (builded by myself) is "registry.svc.ci.openshift.org/origin/release:4.3". I could export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="registry.svc.ci.openshift.org/ocp/release:4.3" before running the installer.

Is it correct?

**Comment by cfBrianMiller** [comment]
@zhongjun2 when i build the installer with that export in the boot strap logs i get this:
``` 
Error: error pulling image "registry.svc.ci.openshift.org/ocp/release:4.3": unable to pull registry.svc.ci.openshift.org/ocp/release:4.3: unable to pull image: Error initializing source docker://registry.svc.ci.openshift.org/ocp/release:4.3: Error reading manifest 4.3 in registry.svc.ci.openshift.org/ocp/release: unauthorized: authentication required
```
it looks like registry.svc.ci.openshift.org requires authentication

**Comment by dcdh** [comment]
Here is a solution https://medium.com/@craig_robinson/openshift-4-4-okd-bare-metal-install-on-vmware-home-lab-6841ce2d37eb

In "Download the openshift-installer and oc client" paragraph.

**Comment by LorbusChris** [comment]
@zhongjun2 I hioe you got it to work eventually!

Just to sum this up again: OCP (RHCOS) you'd have to use spec v2.x, and for OKD (FCOS) spec v3.

The errors when using a mismatched Ignition version are expected.
If you still encounter this issue please refer to the docs and/or the other various channels where the OKD WG is present, e.g. https://groups.google.com/forum/#!forum/okd-wg

/close
