### ISSUE TITLE
TLS cert/key data duplicated in ignition configs

### ISSUE THREAD

**Issue by rajatchopra** [openshift/installer#277]
This is a dev/code optimization issue. Not a functionality bug.

The code for ignition config takes the cert/key pairs and dumps them into files. Here:
https://github.com/openshift/installer/blob/master/pkg/asset/ignition/bootstrap.go#L241-L246

Also, the operators manifest assets will take those key/certs and put them into a secret. Here:
https://github.com/openshift/installer/blob/master/modules/bootkube/resources/manifests/kube-apiserver-secret.yaml#L8-L23

The secret should likely exist. Not sure if we need all those files through the ignition target.

/cc @crawford

**Comment by abhinavdahiya** [comment]
Some of these are tls cert/key are required on bootstrap node for `bootstrap control plane`, but we should definitely revisit if some are not required.

**Comment by crawford** [comment]
Please re-open if you identify assets that can be removed. ...or open a PR ;)
