### ISSUE TITLE
installer doesn't support Non US Public Azure clouds

### ISSUE THREAD

**Issue by cfBrianMiller** [openshift/installer#2775]
# Version
4.2 / 4.3 / 4.4 / latest
```console
$ openshift-install version
/src/github.com/openshift/installer/bin/openshift-install version
/root/go/src/github.com/openshift/installer/bin/openshift-install unreleased-master-2237-g3d33fcbb66ce56bf1679a9c414db7f4d6d2c2721
built from commit 3d33fcbb66ce56bf1679a9c414db7f4d6d2c2721
release image registry.svc.ci.openshift.org/origin/release:4.3
```

# Platform:

Azure
# What happened?

When entering information into the create install-config command there is an error:

FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": failed to get list of regions: subscriptions.Client#ListLocations: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '{{AZURE US GOV SUBSCRIPTION ID}}' could not be found."

# What you expected to happen?

List the available regions

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-installer create install-config
```
Select azure as the platform
Enter in valid US Gov subscription / app details

# Anything else we need to know?

A PR is in the works to fix this issue. This is for tracking.

# References

None that I can find

**Comment by cfBrianMiller** [comment]
Hello,

I found a problem i'm trying to understand the master servers point to api-init.{clustername} to get their full master ignition file. That file header looks like this

```json
{
    "ignition": {
        "config": {
            "replace": {
                "source": null,
                "verification": {}
            }
        },
        "security": {
            "tls": {}
        },
        "timeouts": {},
        "version": "3.0.0"
    },
```
There is no ignition 3.0. The latest spec i can find is 2.3.0

**Comment by sferich888** [comment]
We support OpenShift in the following regions based on testing - https://docs.openshift.com/container-platform/4.3/installing/installing_azure/installing-azure-account.html#installation-azure-regions_installing-azure-account

**Comment by bit4man** [comment]
> We support OpenShift in the following regions based on testing - https://docs.openshift.com/container-platform/4.3/installing/installing_azure/installing-azure-account.html#installation-azure-regions_installing-azure-account
@sferich888 The issue isn't "just" regions - there are literately different end points to the 4 (or so) different Azure Cloud implementations: https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-cli
Attempting to sign in without specifying the right end point will fail.

**Comment by sferich888** [comment]
> > We support OpenShift in the following regions based on testing - https://docs.openshift.com/container-platform/4.3/installing/installing_azure/installing-azure-account.html#installation-azure-regions_installing-azure-account
> > @sferich888 The issue isn't "just" regions - there are literately different end points to the 4 (or so) different Azure Cloud implementations: https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-cli
> > Attempting to sign in without specifying the right end point will fail.

Thus why we have a limit list of supported regions.

**Comment by abhinavdahiya** [comment]
The installer now supports it in the master.

see `.platform.azure.cloudName`
```
./bin/openshift-install explain installconfig.platform.azure
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <object>
  Azure is the configuration used when installing on Azure.

FIELDS:
    baseDomainResourceGroupName <string>
      BaseDomainResourceGroupName specifies the resource group where the Azure DNS zone for the base domain is found.

    cloudName <string>
      Valid Values: "","AzurePublicCloud","AzureUSGovernmentCloud","AzureChinaCloud","AzureGermanCloud"
      cloudName is the name of the Azure cloud environment which can be used to configure the Azure SDK with the appropriate Azure API endpoints. If empty, the value is equal to "AzurePublicCloud".

    computeSubnet <string>
      ComputeSubnet specifies an existing subnet for use by compute nodes

    controlPlaneSubnet <string>
      ControlPlaneSubnet specifies an existing subnet for use by the control plane nodes

    defaultMachinePlatform <object>
      DefaultMachinePlatform is the default configuration used when installing on Azure for machine pools which do not define their own platform configuration.

    networkResourceGroupName <string>
      NetworkResourceGroupName specifies the network resource group that contains an existing VNet

    outboundType <string>
      Default: "Loadbalancer"
      Valid Values: "","Loadbalancer","UserDefinedRouting"
      OutboundType is a strategy for how egress from cluster is achieved. When not specified default is "Loadbalancer".

    region <string> -required-
      Region specifies the Azure region where the cluster will be created.

    virtualNetwork <string>
      VirtualNetwork specifies the name of an existing VNet for the installer to use
```


/close
