### ISSUE TITLE
openshift-install ignition bucket missing terraform bucket argument.

### ISSUE THREAD

**Issue by inderpaltiwana** [openshift/installer#2791]
# Version

```console
openshift-install version 4.3 (4.3.0-0.nightly-2019-12-10-034925)
```

# Platform:
```
AWS (IPI)
```

# What happened?

When deploying a cluster, during S3 bucket creation, the ignition bucket created omits the terraform s3 bucket property and as such it creates an s3 bucket with a random terraform generated name. Code in question included and linked [here](https://github.com/openshift/installer/blob/master/data/data/aws/bootstrap/main.tf).

```
resource "aws_s3_bucket" "ignition" {
  acl = "private"

  tags = merge(
    {
      "Name" = "${var.cluster_id}-bootstrap"
    },
    var.tags,
  )

  lifecycle {
    ignore_changes = all
  }
}
```

# What you expected to happen?

Expected to be something similar to code below. Which would ensure a named s3 bucket is generated win line with conventions as well as being tagged as intended.
```
resource "aws_s3_bucket" "ignition" {
  acl = "private"
  bucket = "${var.cluster_id}-blah"

  tags = merge(
    {
      "Name" = "${var.cluster_id}-bootstrap"
    },
    var.tags,
  )

  lifecycle {
    ignore_changes = all
  }
}
```

# How to reproduce it (as minimally and precisely as possible)?

```console
Will be reproduced on every AWS cluster installation
$ openshift-install create cluster
```

**Comment by abhinavdahiya** [comment]
Is this causing an error? Or if this just cosmetic?

**Comment by inderpaltiwana** [comment]
It causes errors in the cluster creation when trying to deploy due to inherited naming policies, and the random bucket name generated from terraform, doesn't lend itself well to identifying and using an accepted naming convention.

**Comment by abhinavdahiya** [comment]
> It causes errors in the cluster creation when trying to deploy due to inherited naming policies

can you expand on this, is this a constraint on your account?

**Comment by inderpaltiwana** [comment]
I do not have the error available to hand right now.

But terraform will get a 403 access denied error. Due to AWS endpoints policy that restricts access to/from s3 buckets of choice, effectively buckets that adhere to a convention. A similar implementation of this can be noted from the AWS docs.

Allowing access to specific resources with standard patterns.

```
{
  "Statement": [
    {
      "Sid": "Access-to-specific-bucket-only",
      "Principal": "*",
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::my_secure_bucket",
                   "arn:aws:s3:::my_secure_bucket/*"]
    }
  ]
}	
```
