### ISSUE TITLE
After OCP 4.2 cluster reboot, Console is not opening.

### ISSUE THREAD

**Issue by sunilhsk** [openshift/installer#2833]
Its Openshift 4.2 Baremetal.

After rebooting my nodes, i am unable to open console. if i check the pods for console operator its showing progressing.

here are my details.

[ auth]# oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.2.7     True        False         True       21d
cloud-credential                           4.2.7     True        False         False      21d
cluster-autoscaler                         4.2.7     True        False         False      21d
console                                    4.2.7     False       True          False      177m
dns                                        4.2.7     True        False         False      21d
image-registry                             4.2.7     True        False         False      66m
ingress                                    4.2.7     True        False         False      66m
insights                                   4.2.7     True        False         False      21d
kube-apiserver                             4.2.7     True        False         False      21d
kube-controller-manager                    4.2.7     True        False         False      21d
kube-scheduler                             4.2.7     True        False         False      21d
machine-api                                4.2.7     True        False         False      21d
machine-config                             4.2.7     True        False         False      21d
marketplace                                4.2.7     True        False         False      66m
monitoring                                 4.2.7     True        False         False      66m
network                                    4.2.7     True        False         False      21d
node-tuning                                4.2.7     True        False         False      66m
openshift-apiserver                        4.2.7     True        False         False      120m
openshift-controller-manager               4.2.7     True        False         False      21d
openshift-samples                          4.2.7     True        False         False      21d
operator-lifecycle-manager                 4.2.7     True        False         False      21d
operator-lifecycle-manager-catalog         4.2.7     True        False         False      21d
operator-lifecycle-manager-packageserver   4.2.7     True        False         False      66m
service-ca                                 4.2.7     True        False         False      21d
service-catalog-apiserver                  4.2.7     True        False         False      21d
service-catalog-controller-manager         4.2.7     True        False         False      21d
storage                                    4.2.7     True        False         False      21d

# oc get pods -n openshift-console
NAME                        READY   STATUS    RESTARTS   AGE
console-69447cb7b5-7f6xq    0/1     Running   41         21d
console-69447cb7b5-gl8sg    0/1     Running   41         21d
downloads-9fcbc4dc7-j69xd   1/1     Running   4          21d
downloads-9fcbc4dc7-vtdkf   1/1     Running   3          176m

oc describe pod console-69447cb7b5-7f6xq -n openshift-console
Name:               console-69447cb7b5-7f6xq
Namespace:          openshift-console
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               master-0.test.flex.com/192.168.105.51
Start Time:         Tue, 26 Nov 2019 10:57:00 +0530
Labels:             app=console
                    component=ui
                    pod-template-hash=69447cb7b5
Annotations:        console.openshift.io/console-config-version: 10933
                    console.openshift.io/image:
                      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:49df60954b0470caa5c13886e5e823f2cdf7e2507a61b2f2b4c2672fdcd2638e
                    console.openshift.io/oauth-secret-version: 10954
                    console.openshift.io/proxy-config-version: 428
                    console.openshift.io/service-ca-config-version: 10937
                    console.openshift.io/trusted-ca-config-version: 10952
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "openshift-sdn",
                          "interface": "eth0",
                          "ips": [
                              "10.128.0.93"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    openshift.io/scc: restricted
                    operator.openshift.io/pull-spec:
                      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:49df60954b0470caa5c13886e5e823f2cdf7e2507a61b2f2b4c2672fdcd2638e
Status:             Running
IP:                 10.128.0.93
Controlled By:      ReplicaSet/console-69447cb7b5
Containers:
  console:
    Container ID:  cri-o://6b1dcdaebb8a0d5ec8482f3fb54ef75b52b8c0145149dd7b1f48d9d806027731
    Image:         quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:49df60954b0470caa5c13886e5e823f2cdf7e2507a61b2f2b4c2672fdcd2638e
    Image ID:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:49df60954b0470caa5c13886e5e823f2cdf7e2507a61b2f2b4c2672fdcd2638e
    Port:          443/TCP
    Host Port:     0/TCP
    Command:
      /opt/bridge/bin/bridge
      --public-dir=/opt/bridge/static
      --config=/var/console-config/console-config.yaml
      --service-ca-file=/var/service-ca/service-ca.crt
    State:       Running
      Started:   Tue, 17 Dec 2019 16:02:17 +0530
    Last State:  Terminated
      Reason:    Error
      Message:   oint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:31:16 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:31:26 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:31:36 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:31:46 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:31:56 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:32:06 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client
2019/12/17 10:32:16 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.test.flex.com/oauth/token failed: Head https://oauth-openshift.apps.test.flex.com: http: server gave HTTP response to HTTPS client

      Exit Code:    2
      Started:      Tue, 17 Dec 2019 15:59:26 +0530
      Finished:     Tue, 17 Dec 2019 16:02:17 +0530
    Ready:          False
    Restart Count:  41
    Requests:
      cpu:        10m
      memory:     100Mi
    Liveness:     http-get https://:8443/health delay=150s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get https://:8443/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/pki/ca-trust/extracted/pem from trusted-ca-bundle (ro)
      /var/console-config from console-config (ro)
      /var/oauth-config from console-oauth-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jkc5f (ro)
      /var/service-ca from service-ca (ro)
      /var/serving-cert from console-serving-cert (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  console-serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  console-serving-cert
    Optional:    false
  console-oauth-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  console-oauth-config
    Optional:    false
  console-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      console-config
    Optional:  false
  service-ca:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      service-ca
    Optional:  false
  trusted-ca-bundle:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      trusted-ca-bundle
    Optional:  false
  default-token-jkc5f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jkc5f
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-reachable:NoExecute for 120s
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 120s
Events:
  Type     Reason           Age                    From                             Message
  ----     ------           ----                   ----                             -------
  Warning  FailedMount      3h (x3 over 3h)        kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-serving-cert" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      3h (x3 over 3h)        kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      3h (x3 over 3h)        kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-oauth-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      3h (x3 over 3h)        kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "trusted-ca-bundle" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      3h (x3 over 3h)        kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "default-token-jkc5f" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      3h (x3 over 3h)        kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "service-ca" : couldn't propagate object cache: timed out waiting for the condition
  Warning  NetworkNotReady  3h (x7 over 3h)        kubelet, master-0.test.flex.com  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network
  Warning  BackOff          140m (x55 over 163m)   kubelet, master-0.test.flex.com  Back-off restarting failed container
  Warning  Unhealthy        135m (x178 over 3h)    kubelet, master-0.test.flex.com  Readiness probe failed: Get https://10.128.0.67:8443/health: dial tcp 10.128.0.67:8443: connect: connection refused
  Warning  FailedMount      126m                   kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-oauth-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      126m (x2 over 126m)    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "service-ca" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      126m (x2 over 126m)    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "default-token-jkc5f" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      126m (x2 over 126m)    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-serving-cert" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      126m (x2 over 126m)    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      126m (x2 over 126m)    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "trusted-ca-bundle" : couldn't propagate object cache: timed out waiting for the condition
  Warning  NetworkNotReady  126m (x14 over 126m)   kubelet, master-0.test.flex.com  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network
  Warning  BackOff          95m (x34 over 108m)    kubelet, master-0.test.flex.com  Back-off restarting failed container
  Warning  Unhealthy        90m (x145 over 125m)   kubelet, master-0.test.flex.com  Readiness probe failed: Get https://10.128.0.71:8443/health: dial tcp 10.128.0.71:8443: connect: connection refused
  Warning  FailedMount      88m (x2 over 88m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "default-token-jkc5f" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      88m (x2 over 88m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "trusted-ca-bundle" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      88m (x2 over 88m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-serving-cert" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      88m (x2 over 88m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "service-ca" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      88m (x2 over 88m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-oauth-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      88m (x2 over 88m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  NetworkNotReady  88m (x13 over 88m)     kubelet, master-0.test.flex.com  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network
  Warning  Unhealthy        78m (x60 over 87m)     kubelet, master-0.test.flex.com  Readiness probe failed: Get https://10.128.0.78:8443/health: dial tcp 10.128.0.78:8443: connect: connection refused
  Warning  FailedMount      70m                    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      70m                    kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-oauth-config" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      70m (x2 over 70m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "default-token-jkc5f" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      70m (x2 over 70m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "console-serving-cert" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      70m (x2 over 70m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "service-ca" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount      70m (x2 over 70m)      kubelet, master-0.test.flex.com  MountVolume.SetUp failed for volume "trusted-ca-bundle" : couldn't propagate object cache: timed out waiting for the condition
  Warning  NetworkNotReady  69m (x14 over 70m)     kubelet, master-0.test.flex.com  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network
  Normal   Pulled           14m (x13 over 69m)     kubelet, master-0.test.flex.com  Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:49df60954b0470caa5c13886e5e823f2cdf7e2507a61b2f2b4c2672fdcd2638e" already present on machine
  Warning  Unhealthy        9m20s (x240 over 69m)  kubelet, master-0.test.flex.com  Readiness probe failed: Get https://10.128.0.93:8443/health: dial tcp 10.128.0.93:8443: connect: connection refused
  Warning  BackOff          4m22s (x118 over 52m)  kubelet, master-0.test.flex.com  Back-off restarting failed container

Can i know where it is affecting?

**Comment by sunilhsk** [comment]
@praveenkumar  Please help me out.

**Comment by kubedevops** [comment]
Need to make sure that your LB is routing traffic to the node running the oauth-openshift pod. 

Please try pinging the full FQDN in question (oauth-openshift.apps.test.flex.com)

what node is it resolving to ?

is that the node running oauth? 

If it's not, then that is your issue. I ran into the same exact issue as you and after updating dns, it booted up within 15 seconds and binded 443 to port 8443. please see my output below when checking the pod logs. 

```
2020/02/7 21:50:22 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:50:32 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:50:42 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:50:52 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:51:02 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:51:12 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:51:22 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:51:32 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:51:42 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:51:52 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:52:02 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.kube.d***tura**.net/oauth/token failed: Head https://oauth-openshift.apps.kube.d***tura**.net: dial tcp 172.16.145.101:443: connect: connection refused
2020/02/7 21:52:12 cmd/main: Binding to 0.0.0.0:8443...
2020/02/7 21:52:12 cmd/main: using TLS
```

please note that the bind part below, only showed up in logs after dns update 

```
2020/02/7 21:52:12 cmd/main: Binding to 0.0.0.0:8443...
2020/02/7 21:52:12 cmd/main: using TLS
```
