### ISSUE TITLE
Problem of installing RedHat OpenShift 4.2 on CentOS7 

### ISSUE THREAD

**Issue by doyoungim999** [openshift/installer#2839]
# Version

```console
$ openshift-install version
: OpenShift 4.2 
```

# Platform:

libvirt 

# What happened?
I am using CentOS7 and try to install OpenShift4.7 with LibVirt. 
The error is "invalid option". How can I fix  this problem ? 

[root@baremetal02 openshift]# ./installer/bin/openshift-install --dir install-dir create cluster
INFO Obtaining RHCOS image file from 'https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.81.201912110942.0/x86_64/rhcos-43.81.201912110942.0-qemu.x86_64.qcow2.gz?sha256=6a019c55a13c6ff4c6527d8b2c965bdc657bf444258ee7a420694d6f3ab3a8e8'
INFO The file was found in cache: /root/.cache/openshift-installer/image_cache/715650d055f55b62ef332078b9647f66. Reusing...
INFO Consuming Worker Machines from target directory
INFO Consuming Master Machines from target directory
INFO Consuming Common Manifests from target directory
INFO Consuming Openshift Manifests from target directory
INFO Creating infrastructure resources...
ERROR
ERROR Error: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option')
ERROR
ERROR   on ../../../../../tmp/openshift-install-148077477/main.tf line 87, in resource "libvirt_domain" "master":
ERROR   87: resource "libvirt_domain" "master" {
ERROR
ERROR
ERROR
ERROR Error: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option')
ERROR
ERROR   on ../../../../../tmp/openshift-install-148077477/bootstrap/main.tf line 13, in resource "libvirt_domain" "bootstrap":
ERROR   13: resource "libvirt_domain" "bootstrap" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform

# What you expected to happen?
Install sucssefully

# How to reproduce it (as minimally and precisely as possible)?
./installer/bin/openshift-install --dir install-dir create manifests

? Libvirt Connection URI [? for help] (qemu+tcp://192.168.122.1/system) qemu+tcp? Libvirt Connection URI qemu+tcp://localhost:16509/system
? Base Domain tt.doy
? Cluster Name mycluster
? Pull Secret

```console
$ your-commands-here
./installer/bin/openshift-install --dir install-dir create cluster

# Anything else we need to know?
OS is centOS7. Is it should be RHEL8 ? 


# References

https://docs.google.com/document/d/1gHautHUc4vSRkzhZrwSONeBMVh9oXgq16EoF7wn0i0c/edit#

**Comment by slintes** [comment]
> Message='internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option'

IIRC you need a newer qemu
I found this in my shell history:
```
yum install centos-release-qemu-ev
sudo yum install libvirt libvirt-devel libvirt-daemon-kvm qemu-kvm
```

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/tree/master/docs/dev/libvirt#install-and-enable-libvirt

we already document the packages required for CentOS.

/close
