### ISSUE TITLE
baremetal: incorrect checksum used for bootstrap vm with bootstrapOSImage override

### ISSUE THREAD

**Issue by hardys** [openshift/installer#2845]
Since https://github.com/openshift/installer/pull/2757 landed it is possible to override the bootstrap image for disconnected installs, and I tried that like this:

```
platform:
  baremetal:
    bootstrapOSImage: http://192.168.111.1/images/rhcos-43.81.201912110942.0-qemu.x86_64.qcow2.gz?sha256=fb31404bbd8b7cb4726799e0a839799060a496679e5c67b06a17929d757e5e9e
```

However we see that although the installer cache code downloads from the expected location, the checksum is not recalculated before passing to terraform, so the validation fails:

```
level=info msg="Obtaining RHCOS image file from 'http://192.168.111.1/images/rhcos-43.81.201912110942.0-qemu.x86_64.qcow2.gz?sha256=fb31404bbd8b7cb4726799e0a839799060a496679e5c67b06a17929d757e5e9e'"
level=debug msg="Unpacking file into \"/home/shardy/.cache/openshift-installer/image_cache/59c9306c6a41ee6d900e99b4a0b2697a\"..."
level=debug msg="content type of /home/shardy/.cache/openshift-installer/image_cache/59c9306c6a41ee6d900e99b4a0b2697a is application/x-gzip"
level=error msg="File sha256 checksum is invalid."
level=fatal msg="failed to fetch Terraform Variables: failed to generate asset \"Terraform Variables\": failed to get baremetal Terraform variables: failed to use cached bootstrap libvirt image: Checksum mismatch for /home/shardy/.cache/openshift-installer/image_cache/59c9306c6a41ee6d900e99b4a0b2697a; expected=fb31404bbd8b7cb4726799e0a839799060a496679e5c67b06a17929d757e5e9e found=6a019c55a13c6ff4c6527d8b2c965bdc657bf444258ee7a420694d6f3ab3a8e8"
```

Here we can see the compressed and uncompressed checksum - I think in the case where bootstrapOSImage is specified the sha256 should be used to validate the downloaded image, then a new checksum calculated for the gunzipped file?

```
$ sha256sum /home/dev-scripts/ironic/html/images/rhcos-43.81.201912110942.0-qemu.x86_64.qcow2.gz
fb31404bbd8b7cb4726799e0a839799060a496679e5c67b06a17929d757e5e9e  /home/dev-scripts/ironic/html/images/rhcos-43.81.201912110942.0-qemu.x86_64.qcow2.gz
$ gunzip -c /home/dev-scripts/ironic/html/images/rhcos-43.81.201912110942.0-qemu.x86_64.qcow2.gz | sha256sum
6a019c55a13c6ff4c6527d8b2c965bdc657bf444258ee7a420694d6f3ab3a8e8  -
```

**Comment by hardys** [comment]
@kirankt FYI I found this while testing with https://github.com/openshift-metal3/dev-scripts/pull/867

I'm not yet sure why this isn't playing nicely wrt https://github.com/openshift/installer/pull/2657

**Comment by kirankt** [comment]
@hardys I left a comment earlier in https://github.com/openshift-metal3/dev-scripts/pull/867 that we need to use the uncompressed sha256 hash.

**Comment by hardys** [comment]
Ok thanks for confirming @kirankt IMHO that is probably a bug, I see it appends the uncompressed hash here:

**Comment by RobertKrawitz** [comment]
We discussed doing that, but decided that it's best to not have to store (temporarily) two copies of the image on disk.

If a .gz file is explicitly requested, perhaps the code should decompress it on the fly (perhaps calculating the compressed checksum on passthrough), but only land the uncompressed file on disk.

**Comment by hardys** [comment]
@RobertKrawitz thanks for the additional context, it does seem like the interface would be more intuitive/consistent if we calculated the checksum for the compressed file.

As you say we could do it on the fly via streaming, e.g locally I've been doing `gunzip -c | sha256sum` for similar reasons 

I'm creating a local cache for disconnected installs that includes images used by the installer and other provisioning components deployed via IPI baremetal, and in that case I don't really want to store the uncompressed files, it's better to validate the compressed data.

**Comment by RobertKrawitz** [comment]
Last time I tried it, the machine would not boot the compressed image, so we stored it uncompressed and calculated the checksum on that basis.

**Comment by abhinavdahiya** [comment]
> @RobertKrawitz thanks for the additional context, it does seem like the interface would be more intuitive/consistent if we calculated the checksum for the compressed file.
> 
> As you say we could do it on the fly via streaming, e.g locally I've been doing `gunzip -c | sha256sum` for similar reasons;
> 
> I'm creating a local cache for disconnected installs that includes images used by the installer and other provisioning components deployed via IPI baremetal, and in that case I don't really want to store the uncompressed files, it's better (and faster) to validate the compressed data.

I don't want to store compressed data, because it's not useful to any of the consumers, libvirt, openstack can't use the compressed format... so it's most useful to store and cache the uncompressed files.

as for faster, caching means you don't have to do it always, so i don't see the benefit there.
