### ISSUE TITLE
Azure masters stuck in reboot loop not getting ignition config

### ISSUE THREAD

**Issue by hassenius** [openshift/installer#2856]
# Version

```console
../bin/openshift-install unreleased-master-2292-g3c25ea818d3299087689fefb390d35f3cc3c11c5
built from commit 3c25ea818d3299087689fefb390d35f3cc3c11c5
release image registry.svc.ci.openshift.org/origin/release:4.3
```

# Platform:
Azure

# What happened?
Boot node starts successfully, but master nodes never boots successfully, seemingly unable to download ignition file

# What you expected to happen?
Master nodes boot successfully

# How to reproduce it (as minimally and precisely as possible)?
Build latest master branch and deploy to Azure

# Anything else we need to know?
Seems to be an issue, maybe with loadbalancer?
In Master log I can see
```
[   15.548309] ignition[1592]: GET https://api-int.hkdevtest.dev.az.multicloudops.io:22623/config/master: attempt #5
[   15.559288] ignition[1592]: GET error: Get https://api-int.hkdevtest.dev.az.multicloudops.io:22623/config/master: dial tcp: lookup api-int.hkdevtest.dev.az.multicloudops.io on [::1]:53: read udp [::1]:57149->[::1]:53: read: connection refused
[   18.749086] ignition[1592]: GET https://api-int.hkdevtest.dev.az.multicloudops.io:22623/config/master: attempt #6
[[0m[0;31m*     [0m] A start job is running for Ignition (fetch) (15s / no limit)
[K[[0;1;31m*[0m[0;31m*    [0m] A start job is running for Ignition (fetch) (16s / no limit)
<snip>
[K[     [0;31m*[0m] A start job is running for Ignition (fetch) (44s / no limit)[   48.749317] ignition[1592]: GET error: Get https://api-int.hkdevtest.dev.az.multicloudops.io:22623/config/master: dial tcp 10.0.0.4:22623: i/o timeout
```
From the bootstrap machine I can
```
[core@hkdevtest-qjqnk-bootstrap ~]$ curl --insecure https://localhost:22623/config/master
{"ignition":{"config":{"replace":{"source":null,"verification":{}}},"security":{"tls":{..........
.......
```
But I have no luck through loadbalancer
```
[core@hkdevtest-qjqnk-bootstrap ~]$ curl --insecure https://api-int.hkdevtest.dev.az.multicloudops.io:22623/config/master
curl: (7) Failed to connect to api-int.hkdevtest.dev.az.multicloudops.io port 22623: Connection timed out
[core@hkdevtest-qjqnk-bootstrap ~]$ curl --insecure https://10.0.0.4:22623/config/master
curl: (7) Failed to connect to 10.0.0.4 port 22623: Connection timed out
[core@hkdevtest-qjqnk-bootstrap ~]$ 

```

Loadbalancer config seems ok (see attached az network lb output)
[loadbalancers.txt](https://github.com/openshift/installer/files/3989044/loadbalancers.txt)

Console logs from boot and one master attached (all masters same result)
[hkdevtest-qjqnk-bootstrap.066c0c65-1e1f-4342-a6cb-68a1bb05dd0b.serialconsole.txt](https://github.com/openshift/installer/files/3988967/hkdevtest-qjqnk-bootstrap.066c0c65-1e1f-4342-a6cb-68a1bb05dd0b.serialconsole.txt)
[hkdevtest-qjqnk-master-1.392caa6f-87d6-4502-8890-c938576ea390.serialconsole.txt](https://github.com/openshift/installer/files/3988969/hkdevtest-qjqnk-master-1.392caa6f-87d6-4502-8890-c938576ea390.serialconsole.txt)

**Comment by hassenius** [comment]
After looking closer, the actual error seems to be an issue with the ignition file, with the log entries of interest being 
```
[K[[0;31m*[0;1;31m*[0m[0;31m*   [0m] A start job is running for Ignition (fetch) (4min 55s / no limit)[  299.645665] ignition[1592]: error at line 1, column 794
[  299.645665] no filesystem specified

[K[  299.654168] ignition[1592]: error at line 1, column 1194
[  299.654168] no filesystem specified
```

Which is exactly the same symptoms as described in https://github.com/openshift/os/issues/394

**Comment by hassenius** [comment]
One thing I'm noticing is that if I ssh to the bootstrap machine of the openshift cluster and manually edit the `/etc/mcs/bootstrap/machine-configs/rendered-master-*.yaml` file to include `filesystem: root` this is not included in the resulting json from curl --insecure https://localhost:22623/config/master (however other modifications are).

So it appears to me this field is silently stripped by https://github.com/openshift/machine-config-operator

Does this point to some incorrect behaviour in mcahine-config-operator that has previously been accepted by coreos but no longer is?

**Comment by Obirah** [comment]
I'm experiencing the same issue on AWS (OpenShift 4.3), the `filesystem` is gone when curling `/config/master`.

**Comment by eitchugo** [comment]
Hi folks, I'm also experiencing this issue on AWS and OpenShift 4.3. This is only occurring when I have custom policies restricting regions in the user deploying the cluster. If the user has no restriction policies, the masters boot fine.

This seems kinda nonsense, but I'm going to check which permission is missing that is generating an invalid ignition config file without the `filesystem` field.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/issues/3030#issuecomment-580871556

Has the solution for the failure.

/close

**Comment by th3penguinwhisperer** [comment]
@hassenius , @eitchugo , @Obirah : was any of you able to resolve this with what's mentioned in #3030 ?
