### ISSUE TITLE
zVM openshift installer pulling amd64 `registry.svc.ci.openshift.org/origin/release` image

### ISSUE THREAD

**Issue by AnitaNayak** [openshift/installer#2859]
I am trying to install OCP 4.2 on zVM. On a different setup, OCP 4.2 installation was done successfully. But on a new cluster having same configuration, when I am trying to install OCP 4.2, the bootstrap node `bootkube` service is failing with STATUS 1 , which `exec format error`. Following is the error log:
```
Dec 19 14:00:24 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com podman[19274]: 2019-12-19 14:00:24.219674961 +0000 UTC m=+0.547192527 container attach c8f033a3b1c994be92aba76c2f07a897a13a8aad40a6d143d6cd3008e4c72b79 (image=registry.svc.ci.openshift.org/origin/release:4.2, name=dreamy_yonath)
Dec 19 14:00:24 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com bootkube.sh[19260]: standard_init_linux.go:211: exec user process caused "exec format error"
Dec 19 14:00:24 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com podman[19274]: 2019-12-19 14:00:24.219943146 +0000 UTC m=+0.547460698 container died c8f033a3b1c994be92aba76c2f07a897a13a8aad40a6d143d6cd3008e4c72b79 (image=registry.svc.ci.openshift.org/origin/release:4.2, name=dreamy_yonath)
Dec 19 14:00:24 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com podman[19274]: 2019-12-19 14:00:24.362449683 +0000 UTC m=+0.689967294 container remove c8f033a3b1c994be92aba76c2f07a897a13a8aad40a6d143d6cd3008e4c72b79 (image=registry.svc.ci.openshift.org/origin/release:4.2, name=dreamy_yonath)
Dec 19 14:00:24 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Dec 19 14:00:24 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com systemd[1]: bootkube.service: Failed with result 'exit-code'.
Dec 19 14:00:29 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com systemd[1]: bootkube.service: Service RestartSec=5s expired, scheduling restart.
Dec 19 14:00:29 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 92.
Dec 19 14:00:29 bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com systemd[1]: Stopped Bootstrap a Kubernetes cluster.
```
When checked the image, its of amd64 ( on a zVM s390x platform).
[root@bootstrap-0 ~]# sudo podman images
REPOSITORY                                     TAG   IMAGE ID       CREATED       SIZE
registry.svc.ci.openshift.org/origin/release   4.2   32e1b43aec13   7 weeks ago   292 MB
[root@bootstrap-0 ~]#
[root@bootstrap-0 ~]# sudo podman inspect registry.svc.ci.openshift.org/origin/release:4.2 | grep amd64
        "Architecture": "amd64",

I tried to debug...and compared with the working setup. But could not get any clue. On a good setup, its pulling all quao.io images.

Could any one please help me to debug this and find why its pulling amd64 image...

Thanks in advance.

**Comment by abhinavdahiya** [comment]
Please use the published binaries and try not to build from source as that's only for developement.

**Comment by AnitaNayak** [comment]
I am using Image and kernel from `http://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/pre-release/4.2.0-0.nightly-s390x-2019-11-26-152324/` 
and the installer : https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp-dev-preview/latest/openshift-install-linux-4.2.0-0.nightly-s390x-2019-12-05-223224.tar.gz

**Comment by AnitaNayak** [comment]
bootstrap node details: 
```
[core@bootstrap-0 ~]$ uname -a
Linux bootstrap-0.ocp-s390x-test-a7e9e1.ibm.com 4.18.0-147.0.3.el8_1.s390x #1 SMP Mon Nov 11 13:18:20 UTC 2019 s390x s390x s390x GNU/Linux
[core@bootstrap-0 ~]$
```
Surprisingly it is pulling amd64 Image.

**Comment by abhinavdahiya** [comment]
> I am using Image and kernel from `http://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/pre-release/4.2.0-0.nightly-s390x-2019-11-26-152324/`
> and the installer : https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp-dev-preview/latest/openshift-install-linux-4.2.0-0.nightly-s390x-2019-12-05-223224.tar.gz

can you attach the output of `openshift-install version` ?

**Comment by AnitaNayak** [comment]
[root@ocplnx01 multiarch-upi-playbooks]# openshift-install version
openshift-install v4.2.0
built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
release image registry.svc.ci.openshift.org/origin/release:4.2

**Comment by AnitaNayak** [comment]
With openshift-install version 4.2.10, I am able to proceed. Thank you so much.

**Comment by AnitaNayak** [comment]
Is there any compatibility matrix maintained anywhere for openshift-install and the openshift-install?
