### ISSUE TITLE
 Creating infrastructure resources...  in OpenShift 4.2.x

### ISSUE THREAD

**Issue by AjayDevOp** [openshift/installer#2869]
I am trying to install OpenShift 4.2.x in AWS with simple customized and i have modify install-
config
---------
 compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: userocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
---------

But while creating the cluster i got the error below. Do anyone have any idea how to overcome this issue.
----- 
INFO Consuming "Install Config" from target directory 
INFO Creating infrastructure resources...         
ERROR                                              
ERROR Error: Error launching source instance: timeout while waiting for state to become 'success' (timeout: 30s) 
ERROR                                              
ERROR   on ../../../tmp/openshift-install-570705544/master/main.tf line 89, in resource "aws_instance" "master": 
ERROR   89: resource "aws_instance" "master" {     
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform

**Comment by abhinavdahiya** [comment]
> INFO Consuming "Install Config" from target directory
INFO Creating infrastructure resources...
ERROR
ERROR Error: Error launching source instance: timeout while waiting for state to become 'success' (timeout: 30s)
ERROR
ERROR on ../../../tmp/openshift-install-570705544/master/main.tf line 89, in resource "aws_instance" "master":
ERROR 89: resource "aws_instance" "master" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform

This looks like an AWS error, can you retry with latest installer? @AjayDevOp

**Comment by AjayDevOp** [comment]
Ok i will try and let you know

**Comment by abhinavdahiya** [comment]
> Ok i will try and let you know

closing since this is waiting for information for a long time

/close
