### ISSUE TITLE
failed to depoly openshift 4.2 on vmware vsphere 

### ISSUE THREAD

**Issue by SOUIHEL-ayoub** [openshift/installer#2871]
hello , 

we are trying to set up an openshift cluster , but we still receive the below error :

gathered Logs are attached 

[machine-config-controller-c0895a7e95cab2c9c8624b2e0371e4a630e2f37267f2cfaa4433df75041a448e.log](https://github.com/openshift/installer/files/3998271/machine-config-controller-c0895a7e95cab2c9c8624b2e0371e4a630e2f37267f2cfaa4433df75041a448e.log)

[machine-config-server-d70ba1aaf9c20bf44cec15f4e9bde14b831e27bfd3ecaecf722c39263e76e688.log](https://github.com/openshift/installer/files/3998272/machine-config-server-d70ba1aaf9c20bf44cec15f4e9bde14b831e27bfd3ecaecf722c39263e76e688.log)

[root@sblocpbasc01 ocp41install]# openshift-install wait-for  bootstrap-complete --log-level debug
DEBUG OpenShift Installer v4.2.0
DEBUG Built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
INFO Waiting up to 30m0s for the Kubernetes API at https://api.openshift.XXXXXXXXXXXX.com:6443...
DEBUG Still waiting for the Kubernetes API: Get https://api.openshift.XXXXXXXXXXXX.com:6443/version?timeout=32s: proxyconnect tcp: dial tcp 10.21.203.10:8080: connect: connection refused
tcp 10.21.203.10:8080: connect: connection refusedDEBUG Still waiting for the Kubernetes API: Get https://api.openshift.XXXXXXXXXXXX.com:6443/version?timeout=32s: proxyconnect tcp: dial tcp 172.31.65.13:8080: connect: connection refused
DEBUG Still waiting for the Kubernetes API: Get https://api.openshift.XXXXXXXXXXXX.com:6443/version?timeout=32s: proxyconnect tcp: dial tcp 172.31.130.41:8080: connect: connection refused
DEBUG Still waiting for the Kubernetes API: Get https://api.openshift.XXXXXXXXXXXX.com:6443/version?timeout=32s: proxyconnect tcp: dial tcp 172.31.130.10:8080: connect: connection refused
DEBUG Still waiting for the Kubernetes API: Get https://api.openshift.XXXXXXXXXXXX.com:6443/version?timeout=32s: proxyconnect tcp: dial tcp 172.31.130.41:8080: connect: connection refused
[bootkube.log](https://github.com/openshift/installer/files/3998448/bootkube.log)
[kubelet.log](https://github.com/openshift/installer/files/3998449/kubelet.log)
[openshift.log](https://github.com/openshift/installer/files/3998450/openshift.log)
[release-image.log](https://github.com/openshift/installer/files/3998451/release-image.log)
[machine-config-controller-c0895a7e95cab2c9c8624b2e0371e4a630e2f37267f2cfaa4433df75041a448e.log](https://github.com/openshift/installer/files/3998452/machine-config-controller-c0895a7e95cab2c9c8624b2e0371e4a630e2f37267f2cfaa4433df75041a448e.log)
[machine-config-server-d70ba1aaf9c20bf44cec15f4e9bde14b831e27bfd3ecaecf722c39263e76e688.log](https://github.com/openshift/installer/files/3998453/machine-config-server-d70ba1aaf9c20bf44cec15f4e9bde14b831e27bfd3ecaecf722c39263e76e688.log)
[kubelet.log](https://github.com/openshift/installer/files/3998473/kubelet.log) master log

**Comment by dav1x** [comment]
I think this issue was probably your bootstrap certificate:

In openshift.log
```
Dec 24 09:20:41 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Dec 24 09:20:47 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: error: unable to recognize "./99_cloud-creds-secret.yaml": Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid
Dec 24 09:20:47 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Dec 24 09:20:52 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: error: unable to recognize "./99_cloud-creds-secret.yaml": Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid
Dec 24 09:20:52 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Dec 24 09:20:57 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: error: unable to recognize "./99_cloud-creds-secret.yaml": Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid
Dec 24 09:20:57 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Dec 24 09:21:02 bootstrap-0.XXXXXXXXXXXX.com openshift.sh[13956]: error: unable to recognize "./99_cloud-creds-secret.yaml": Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid
```
I would also double check that your etcd records resolve to the FQDN so the discovery pod can reach them properly.
