### ISSUE TITLE
failed to boot master vm for Openshift 4.3 on Openstack (UPI)

### ISSUE THREAD

**Issue by zhongjun2** [openshift/installer#2879]
failed to deploy Openshift 4.3 on Openstack (UPI)
The openshift-2tdwf-master-0 vm boot fail.  

# Version

```console
$ openshift-install version
./openshift-install v4.3.0
built from commit 93c78d09ed9e2badb4bf5dab708152fe6b3b6602
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:bd7a6d44a6b947d8127d248c721472cbc41f778b9c0fc6612b3d1c15f0c6f673
```

# Platform:
openstack (UPI)

# What happened?
The vm(openshift-bootstrap-ignition) booted.
But the vm(openshift-pd6v4-master-0) does not boot!!!

![image](https://user-images.githubusercontent.com/12421382/71808143-f5d0e080-30a7-11ea-8599-8b506ccabcd0.png)

# systemctl status machine-config-daemon-host.service
● machine-config-daemon-host.service - Machine Config Daemon Initial
   Loaded: loaded (/etc/systemd/system/machine-config-daemon-host.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-01-06 08:54:15 UTC; 1min 1s ago
  Process: 2246 ExecStart=/usr/libexec/machine-config-daemon pivot (code=exited, status=0/SUCCESS)
 Main PID: 2246 (code=exited, status=0/SUCCESS)

Jan 06 08:54:08 host-192-168-2-186 machine-config-daemon[2246]: 9c937d9de288c705f01db6a553bcab78fdf688294d26e9b385db016c34>
Jan 06 08:54:08 host-192-168-2-186 machine-config-daemon[2246]: I0106 08:54:08.438445    2246 rpm-ostree.go:365] Running c>
Jan 06 08:54:08 host-192-168-2-186 machine-config-daemon[2246]: I0106 08:54:08.668401    2246 rpm-ostree.go:365] Running c>
Jan 06 08:54:08 host-192-168-2-186 podman[2310]: 2020-01-06 08:54:08.759530289 +0000 UTC m=+0.074509858 container create a>
Jan 06 08:54:08 host-192-168-2-186 machine-config-daemon[2246]: I0106 08:54:08.774390    2246 rpm-ostree.go:365] Running c>
Jan 06 08:54:08 host-192-168-2-186 podman[2319]: 2020-01-06 08:54:08.840192189 +0000 UTC m=+0.048932800 container mount a6>
Jan 06 08:54:08 host-192-168-2-186 machine-config-daemon[2246]: I0106 08:54:08.847472    2246 rpm-ostree.go:242] Pivoting >
Jan 06 08:54:14 host-192-168-2-186 podman[2349]: 2020-01-06 08:54:14.484186992 +0000 UTC m=+0.063208479 container remove a>
Jan 06 08:54:15 host-192-168-2-186 podman[2358]: 2020-01-06 08:54:15.101946359 +0000 UTC m=+0.584979883 image remove 9c937>
Jan 06 08:54:15 host-192-168-2-186 systemd[1]: Started Machine Config Daemon Initial.

# What you expected to happen?

The vm(openshift-pd6v4-master-0) start up

# How to reproduce it (as minimally and precisely as possible)?

1. deploy openstack(Rocky) in CentoOS 7.6 
   https://ubuntu.com/openstack/install
2. create install-config
   https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md
3. create vm by openshift-bootstrap-ignition.json
    use image: rhcos-43.81.201912030353.0-openstack.x86_64.qcow2
4. create master vm by openshift-2tdwf-master-0-ignition.json, openshift-2tdwf-master-1-ignition.json, openshift-2tdwf-master-2-ignition.json
     use image: rhcos-43.81.201912030353.0-openstack.x86_64.qcow2

# Anything else we need to know?

Use rhcos image.
https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-43.81.201912030353.0-openstack.x86_64.qcow2.gz

# References

Which openshift installer version is match rhcos-43.81.201912030353.0-openstack.x86_64.qcow2 image?

**Comment by mandre** [comment]
/label platform/openstack

The instruction at https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md are only valid only starting from OCP 4.4.

Could you try again following the instruction for release 4.3 at https://github.com/openshift/installer/blob/release-4.3/docs/user/openstack/install_upi.md and let us know if it fixes your issue?

**Comment by zhongjun2** [comment]
@mandre  I use https://github.com/openshift/installer/blob/release-4.3/docs/user/openstack/install_upi.md,  but the issue still exist.

**Comment by zhongjun2** [comment]
@mandre   
 1. Created a vm (CentoOS 7.6) on public cloud
 2. Deploy openstack(Rocky) on CentoOS 7.6
    use:  https://ubuntu.com/openstack/install
 3. Download ocp:
     https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.3
4. use: https://github.com/openshift/installer/blob/release-4.3/docs/user/openstack/install_upi.md
5. Download image: rhcos-43.81.201912030353.0-openstack.x86_64.qcow2
    link: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/latest/

Are those links, versions correct?   Is this match?

**Comment by mandre** [comment]
Hi @zhongjun2, these are the correct instruction and in theory rhcos image, however there was a synchronization issue and the newer image wasn't pushed to the mirror. It should be fixed now.

Can you give it a try with the image in https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/ ?

**Comment by zhongjun2** [comment]
Hi @mandre  I used the newest image rhcos-43.81.202001142154.0-openstack.x86_64.qcow2.gz [https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/ ]. The error(failed to boot master vm) has been fixed. Thank you.

**Comment by zhongjun2** [comment]
But after I boot the master vm, I got another error in master vm:
The etcd server cannot started on master vm, and kubelet service node cannot be found.

**Comment by pierreprinetti** [comment]
> The error(failed to boot master vm [error: os-release file is missing]) has been fixed

/close

Please reopen in case it shows again
