### ISSUE TITLE
Getting error while installing ocp 4.2 on master node --- [systemd] Failed Units: 1   machine-config-daemon-firstboot.service [core@master-0 ~]$

### ISSUE THREAD

**Issue by AnitaNayak** [openshift/installer#2881]
Trying to install OCP 4.2 on s390x. Though nodes are coming up, but when tried to login to master-0, getting below error.

---
Last login: Mon Jan  6 18:21:25 2020 from xx.xx.xx.xx
[systemd]
Failed Units: 1
  machine-config-daemon-firstboot.service
[core@master-0 ~]$

Any idea how, what went wrong.

**Comment by abhinavdahiya** [comment]
you should probably open an issue with RHCOS https://github.com/openshift/os or machine config operator https://github.com/openshift/machine-config-operator/issues

**Comment by AnitaNayak** [comment]
Its my bad, that I have updated wrongly the cidr in all.yaml file. Thanks a lot.
