### ISSUE TITLE
OCP4.2 Install: can the coreos.inst.install_dev values updated with multiple disks to extend the /sysroot

### ISSUE THREAD

**Issue by AnitaNayak** [openshift/installer#2891]
The nodes have multiple disks. But OCP 4.2 takes only one disk as param in `coreos.inst.install_dev`.  Can the coreos.inst.install_dev value be updated with multiple disks to extend the /sysroot in all.yaml file.

**Comment by cgwalters** [comment]
This should be filed against https://github.com/coreos/coreos-installer/ most likely.
But the answer is no - what you're asking for sounds like either LVM or RAID?

**Comment by AnitaNayak** [comment]
Its LVM.... Ok will raise one issue in coreos-installer.
