### ISSUE TITLE
Baremetal image filenames require additional validation

### ISSUE THREAD

**Issue by hardys** [openshift/installer#2894]
Since https://github.com/openshift/installer/pull/2757 landed it's possible to specify arbitrary filenames in the install config, for locally mirrored rhcos images.

However we rely on the installer generated filename currently, to replace `-openstack` with `-compressed` - this aligns with how the downloader container works, and fails if the filename doesn't match the expected format:

https://github.com/openshift/installer/blob/master/pkg/asset/machines/baremetal/machines.go#L88

https://github.com/openshift/ironic-rhcos-downloader/issues/21

To reproduce you can specify e.g:

  clusterOSImage: http://1.2.3.4/rhcos.qcow2.gz?sha256=xyz

instead of the expected e.g:

  clusterOSImage: http://1.2.3.4/rhcos-44.81.202001030903.0-openstack.x86_64.qcow2.gz?sha256=xyz

The installer will accept this, but the downloader container will fail, and the providerSpec image reference will be wrong.

We need to either add validation to catch this, or rework the string substitution to work with arbitrary filenames.

**Comment by imain** [comment]
Hmm.. I'd like to undo the mess with all the substitutions but that's a lot of changes throughout the stack.  You have an opinion on this Steve?  I'm kinda leaning toward validation for now?  Be kind of a strange error message though: "ERROR: Your image name must have '-openstack' in it somewhere" :)

**Comment by imain** [comment]
I'm joking above but.. it would be a strange thing to verify.
