### ISSUE TITLE
baremetal: http_proxy prevents installer-ironic API calls

### ISSUE THREAD

**Issue by hardys** [openshift/installer#2904]
When http_proxy is set in the environment before running the installer, this breaks the terraform API calls to the ironic API which runs on the bootstrap VM.

This issue manifests as the installer waiting until the timeout for the API to respond, but debugging shows that the API is up and responding fine.

Probably we need to either validate http_proxy/no_proxy variables, or perhaps explicitly ignore them for the provisioning network (since we know there should never be any proxy on this network?)

cc @stbenjam @kirankt

**Comment by stbenjam** [comment]
Ultimately these requests go installer -> terraform-provider-ironic -> gophercloud, and then hits Golang's native HTTP library.  `NO_PROXY` would be the way to avoid using the proxy for API communcation, but it is inconsistent across software, although I think go supports most combinations of things (*.example.com, network CIDR, specific IP's). 

It's hard for the installer to influence the underlying http.Client calls in gophercloud without just setting the right proxy variables.

One option would be append the provisioning host IP to NO_PROXY (or set it if unset), but we're making an assumption it should never be proxied. The other would be rely on the customer who's using a proxy to properly craft a NO_PROXY configuration.  I believe in the env you were seeing this, a NO_PROXY line was being used - we should validate it's correct.

Maybe the installer should do some verification on NO_PROXY to make sure it's valid.

**Comment by hardys** [comment]
To clarify in this case there was no NO_PROXY variable, but HTTP_PROXY had been exported and left set (by mistake) before running the installer.

I guess the simplest solution would be some validation that fails if we detect a likely-broken combination of proxy vars, but it does seem reasonable to me to append the provisioning IP to the no_proxy - we control that network and basically it should never be proxied?

**Comment by stbenjam** [comment]
> I guess the simplest solution would be some validation that fails if we detect a likely-broken combination of proxy vars, but it does seem reasonable to me to append the provisioning IP to the no_proxy - we control that network and basically it should never be proxied?

That's probably a safe assumption for most environments (maybe not all, forever).
I think once https://github.com/openshift/installer/pull/2895 lands, we could follow-up with a fix that appends ProvisioningNetworkCIDR to NO_PROXY.

If NO_PROXY is defined, and malformed though, we probably have an issue. Go just takes the env var as is, and uses it. We probably need some way to validate it.

https://github.com/golang/net/blob/master/http/httpproxy/proxy.go#L39-L51

**Comment by hardys** [comment]
> If NO_PROXY is defined, and malformed though, we probably have an issue.

I wonder if we can do more functional validation, e.g before we run terraform at all wait for the httpd server to come up on the bootstrap VM, then wait for the ironic API.

Part of the problem is the terraform output is fairly opaque, in that it looks like we're waiting for the API to come up, or for masters to deploy, but we probably could have figured out that the bootstrap is unreachable somehow before running terraform?

**Comment by stbenjam** [comment]
> Part of the problem is the terraform output is fairly opaque, in that it looks like we're waiting for the API to come up, or for masters to deploy, but we probably could have figured out that the bootstrap is unreachable somehow before running terraform?

The bootstrap is created by terraform and it's all a single terraform run, so I don't think that's possible really.  We would need to do something like stages in the installer, which would be a big refactor. I previously investigated that when we wanted to wait on the Ironic API and it didn't look feasible to me at the time. The wait-for-api is really just implemented as a kludge in terraform-provider-ironic.

Terraform itself doesn't really have a good notion of one provider being responsible for making infrastructure available that other providers use. It very much targets the "cloud" where the existence of the infrastructure is just assumed to already be there.

**Comment by stbenjam** [comment]
Just to clarify, there's two places where we have to consider the provisioning network and proxies. First, the host from which the installer is run. We can probably do something in the installer to Setenv NO_PROXY to include the provisioning network, so the installer calls don't fail while inside terraform.

The second is from within the cluster itself.  The proxy settings defined in the install config create a Proxy object in the cluster.  That's great, we can modify the installer and have it add the provisioning network CIDR:

https://github.com/openshift/installer/blob/65a74ec0bea5c29c68304d10cd877b657a3ff798/pkg/asset/manifests/proxy.go#L116

However, cluster-network-operator also creates a Proxy object.  The installer code and the CNO code must match. This is a bug and needs addressing, and has already caused a ton of issues (for example, https://github.com/openshift/installer/pull/2939).

The CNO code is here:

https://github.com/openshift/cluster-network-operator/blob/adaf257b4d63661726443ab2b059a9b4209a02d1/pkg/util/proxyconfig/no_proxy.go#L22

This is problematic, as we'd have to store the provisioning network CIDR in there, which means it needs to become a part of the Infrastructure status (!) which we've been told not to do.

**Comment by pierreprinetti** [comment]
Sorry I’m late to the party.

> Probably we need to either validate http_proxy/no_proxy variables, or perhaps explicitly ignore them for the provisioning network (since we know there should never be any proxy on this network?)

Why should there never be a proxy between the installer machine and the provisioning network? Is the Installer always run locally to the target cluster, in baremetal installations?
