### ISSUE TITLE
Provide users instructions on how to Subscribe a cluster (as part of the install) 

### ISSUE THREAD

**Issue by sferich888** [openshift/installer#2910]
It would be good if the installer suggested that customers 'register' or 'subscribe' clusters. 

In short, if you know the clusterID then you can send users (of OpenShift Supported Versions (not OKD)) to a URL like: `https://access.redhat.com/management/systems/CLUSTER_ID/subscriptions` to subscribe the cluster. 

Having this presented; after https://github.com/openshift/installer/blob/05d4e97c233a6d835c116fbe6b80c2c8cf2b0385/cmd/openshift-install/create.go#L449 seems like the logical best place to present this URL to the user.

**Comment by abhinavdahiya** [comment]
The installer points to the OpenShift console and there is already links to view/subscribe the cluster.

I don't think it's useful to add this to the install output.

**Comment by sferich888** [comment]
I'm not aware of such an in cluster subscription view, where is this?

**Comment by abhinavdahiya** [comment]
![console OCM](https://user-images.githubusercontent.com/3481311/74197334-1e527a00-4c14-11ea-99d3-71fed9cfc5c4.png)

The console provides a link to the OCM dashboard and that should give options to include subscriptions.

And again I don't think the installer should prompt used to subscribe, i think that it left best to the console.

**Comment by abhinavdahiya** [comment]
> ![console OCM](https://user-images.githubusercontent.com/3481311/74197334-1e527a00-4c14-11ea-99d3-71fed9cfc5c4.png)
> 
> The console provides a link to the OCM dashboard and that should give options to include subscriptions.
> 
> And again I don't think the installer should prompt used to subscribe, i think that it left best to the console. @sferich888

/close
