### ISSUE TITLE
Proxy with machines on 192.168.0.0/16 network

### ISSUE THREAD

**Issue by danielkucera** [openshift/installer#2913]
# Version

```console
$ ./openshift-install version
./openshift-install v4.2.13
built from commit 46f909e4ccb4f7a4f82bf1ee28b32fa011a6bd1f
release image quay.io/openshift-release-dev/ocp-release@sha256:782b41750f3284f3c8ee2c1f8cb896896da074e362cf8a472846356d1617752d
```

# Platform:
vSphere

# What happened?

Cluster is using proxy for internal communication. See logs from squid:
```
1579009284.431 899889 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.100:6443 - HIER_DIRECT/192.168.99.100 -
1579009284.431 899881 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.101:6443 - HIER_DIRECT/192.168.99.101 -
1579009284.431 899873 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.102:6443 - HIER_DIRECT/192.168.99.102 -
1579009496.453 900104 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.100:6443 - HIER_DIRECT/192.168.99.100 -
1579009496.453 900094 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.101:6443 - HIER_DIRECT/192.168.99.101 -
1579009496.453 900088 192.168.99.101 TCP_TUNNEL/200 3693 CONNECT 192.168.99.102:6443 - HIER_DIRECT/192.168.99.102 -
1579009498.055  30072 192.168.99.101 TCP_TUNNEL/200 2811 CONNECT oauth-openshift.apps.os4.danman.eu:443 - HIER_DIRECT/172.23.198.36 -
1579009499.503 899955 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.100:6443 - HIER_DIRECT/192.168.99.100 -
1579009499.503 899947 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.101:6443 - HIER_DIRECT/192.168.99.101 -
1579009499.503 899940 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.102:6443 - HIER_DIRECT/192.168.99.102 -
1579009520.381 900378 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.100:6443 - HIER_DIRECT/192.168.99.100 -
1579009520.381 900371 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.101:6443 - HIER_DIRECT/192.168.99.101 -
1579009520.381 900365 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.102:6443 - HIER_DIRECT/192.168.99.102 -
1579009523.544 900340 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.100:6443 - HIER_DIRECT/192.168.99.100 -
1579009523.544 900333 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.101:6443 - HIER_DIRECT/192.168.99.101 -
1579009523.544 900325 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.102:6443 - HIER_DIRECT/192.168.99.102 -
1579009602.222  30058 192.168.99.101 TCP_TUNNEL/200 2811 CONNECT oauth-openshift.apps.os4.danman.eu:443 - HIER_DIRECT/172.23.198.36 -
1579009662.363 899841 192.168.99.101 TCP_TUNNEL/200 3693 CONNECT 192.168.99.100:6443 - HIER_DIRECT/192.168.99.100 -
1579009662.363 899832 192.168.99.101 TCP_TUNNEL/200 3691 CONNECT 192.168.99.101:6443 - HIER_DIRECT/192.168.99.101 -
1579009662.363 899826 192.168.99.101 TCP_TUNNEL/200 3692 CONNECT 192.168.99.102:6443 - HIER_DIRECT/192.168.99.102 -
1579009733.370  30028 192.168.99.101 TCP_TUNNEL/200 2811 CONNECT oauth-openshift.apps.os4.danman.eu:443 - HIER_DIRECT/172.23.198.36 -

```

# What you expected to happen?

To communicate directly.

# How to reproduce it (as minimally and precisely as possible)?

This is my proxy setting:
```
proxy:
  httpProxy: http://192.168.99.10:8080 
  httpsProxy: http://192.168.99.10:8080 
```

It results in following `env` inside of containers:
```
sh-4.2$ env | grep -i prox
NO_PROXY=.cluster.local,.svc,10.0.0.0/16,10.128.0.0/14,127.0.0.1,172.30.0.0/16,api-int.os4.danman.eu,etcd-0.os4.danman.eu,etcd-1.os4.danman.eu,etcd-2.os4.danman.eu,localhost
HTTPS_PROXY=http://192.168.99.10:8080
HTTP_PROXY=http://192.168.99.10:8080
```

# Anything else we need to know?

I see there is subnet 10.0.0.0/16 (not sure why) but 192.168.0.0/16 is not included. Where is this information taken from? Is there something I forgot to configure?

# References

**Comment by danielkucera** [comment]
My host IPs (/24) are following
- bootstrap: 192.168.99.103
- master-0: 192.168.99.100
- master-1: 192.168.99.101
- master-2: 192.168.99.102
- default gateway: 192.168.99.1
- proxy: 192.168.99.10

**Comment by danielkucera** [comment]
I found the explanation:

https://github.com/openshift/installer/blame/master/docs/user/customization.md#L44

and here:

https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-configure-proxy_installing-restricted-networks-vsphere

I would suggest adding this variable also to the sample install-config.yaml file:
https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere

**Comment by abhinavdahiya** [comment]
> I found the explanation:
> 
> https://github.com/openshift/installer/blame/master/docs/user/customization.md#L44
> 
> and here:
> 
> https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-configure-proxy_installing-restricted-networks-vsphere
> 
> I would suggest adding this variable also to the sample install-config.yaml file:
> https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere

you should open an issue at https://github.com/openshift/openshift-docs/issues/new for adding that to the docs.

closing as it's already fixed in installer.
/close
