### ISSUE TITLE
Feature: Proxy container images on the bootstrap node?

### ISSUE THREAD

**Issue by wking** [openshift/installer#294]
Especially with #281 on the table, it would be great if we had a way to mirror/cache images locally while bringing up the masters, and then a way to stuff those images into image streams once the cluster registry was up.  The bootstrap node is reachable by the masters as they're coming up, so it seems like a good place to put this.  Thoughts?

**Comment by eparis** [comment]
I don't think this is an installer feature really or something we want to tackle in the short/medium term. So I'm going to close. Please feel free to re-open in Jira if you want to keep it alive.
