### ISSUE TITLE
baremetal: redfish_verify_ca needs to be populated

### ISSUE THREAD

**Issue by yrobla** [openshift/installer#2941]
# Version

master

# Platform:
baremetal

# What happened?

When using redfish, an additional param redfish_verify_ca is missing (https://docs.openstack.org/ironic/pike/admin/drivers/redfish.html). This is needed in the case of non-trusted certs, to disable validation. This parameter should be passed to the ironic nodes in order to enable/disable validation, and should be exposed on the install-config.yaml from nodes, and be propagated until the ironic bits.

**Comment by stbenjam** [comment]
Please file an issue against the baremetal-operator repository and link it back here. The BMC credential handling is done by vendored baremetal-operator code.


/label platform/baremetal

**Comment by yrobla** [comment]
Related issue: https://github.com/metal3-io/baremetal-operator/issues/392

**Comment by stbenjam** [comment]
Fixed by https://github.com/openshift/installer/pull/3072
