### ISSUE TITLE
[RFE] Include the total installation time when finished

### ISSUE THREAD

**Issue by e-minguez** [openshift/installer#2942]
# Version
Any

```console
$ openshift-install version
4.4.0-0.nightly-2020-01-17-050113
```

# Platform:
Any

# What happened?
It would be nice to know directly from the installer the time the installation took.

# What you expected to happen?
When running the installation (maybe just with `--log-level=debug`) it would be nice to know how long the installation took at the end of it, such as `Install Complete in x minutes`

# How to reproduce it (as minimally and precisely as possible)?
Run the installation and forget about it.

```console
$ openshift-install ...
```

# Anything else we need to know?
Nope

# References
None

**Comment by abhinavdahiya** [comment]
How do you think users will benefit from showing them how long it took?

**Comment by e-minguez** [comment]
> How do you think users will benefit from showing them how long it took?

Users can predict how long it will take to install the environment for future reference in an easy way, like 'look, the preproduction cluster took 45 minutes with 3 workers, hence we need to plan ~1h for production'. Otherwise they need to do the calculations using the logs.

> What are trying to gain from this?

Visibility on the installation time.

**Comment by mvazquezc** [comment]
I would find this quite useful. 

On top of what Edu already mentioned, the installer could report the time taken for the different steps like:
- Taken time to create infra
- Taken time to bootstrap the cluster
- etc.

Back in Ansible OpenShift Installer, we had this report once the playbooks finished.

Thanks for bringing this up!

**Comment by ptrnull** [comment]
+1
It would be really helpful when you have to install more than one cluster as you already know how long would take. It will also help enabling you to schedule better your changes.

**Comment by patrickdillon** [comment]
Anyone who wants to know the overall installation time could just invoke `openshift-install` using `time`:

```
time openshift-install create cluster
```

Duration by stage is harder to determine so it seems like a more worthwhile RFE.

cc @rna-afk

**Comment by abhinavdahiya** [comment]
/close

https://github.com/openshift/installer/pull/3263
