### ISSUE TITLE
Query Returned no results

### ISSUE THREAD

**Issue by Praveenmail2him** [openshift/installer#2946]
Error: Your query returned no results. Please change your search criteria and try again.
  on 6_bootstrap\rhcos.tf line 1, in data "aws_ami" "rhcos":
   1: data "aws_ami" "rhcos" {
Error: Your query returned no results. Please change your search criteria and try again.
  on 7_control_plane\rhcos.tf line 1, in data "aws_ami" "rhcos":
   1: data "aws_ami" "rhcos" {

**Comment by Praveenmail2him** [comment]
Error: Your query returned no results. Please change your search criteria and try again.
on 6_bootstrap\rhcos.tf line 1, in data "aws_ami" "rhcos":
1: data "aws_ami" "rhcos" {
Error: Your query returned no results. Please change your search criteria and try again.
on 7_control_plane\rhcos.tf line 1, in data "aws_ami" "rhcos":
1: data "aws_ami" "rhcos" {

This issue whenever I do terraform destroy it occurs. Please let me know how to fix this?

**Comment by abhinavdahiya** [comment]
It would be great if you provide context on how and when do you see this bug

**Comment by Praveenmail2him** [comment]
Context - I'm openshift cluster 4.2 on AWS through UPI Scripts.

This error occurs at times when I do terraform destroy or terraform apply again. I'm giving admin access to the IAM role. But this has become a show stopper, Am I doing something wrong?

**Comment by abhinavdahiya** [comment]
> Context - I'm openshift cluster 4.2 on AWS through UPI Scripts.
> 
> This error occurs at times when I do terraform destroy or terraform apply again. I'm giving admin access to the IAM role. But this has become a show stopper, Am I doing something wrong?

Hmm.. the UPI templates are cloud formation based... so not sure where the terraform is involved in the process?

**Comment by abhinavdahiya** [comment]
> > Context - I'm openshift cluster 4.2 on AWS through UPI Scripts.
> > This error occurs at times when I do terraform destroy or terraform apply again. I'm giving admin access to the IAM role. But this has become a show stopper, Am I doing something wrong?
> 
> Hmm.. the UPI templates are cloud formation based... so not sure where the terraform is involved in the process?

closing because of no response.

/close
