### ISSUE TITLE
baremetal: VRRP traffic collision when multiple clusters using the same broadcast domain

### ISSUE THREAD

**Issue by rlopez133** [openshift/installer#2966]
When deploying Installer Provisioned Infrastructure (IPI) on baremetal, there is a potential issue that arises if there are multiple clusters using the same broadcast domain. In our particular case, we had an environment with IPI on baremetal successfully installed and when attempting to install a brand new cluster we started noticing that on the bootstrap VM the API VIP IP was not coming up on the bootstrap VM.

This was noticeable since when it was time for the master nodes to get their configuration the following error was showing:
```
GET error: Get https://10.19.140.44:22623/config/master: dial tcp 10.19.140.44:22623: connect: no route to host
```
In this example, the 10.19.140.44 was my API VIP address. When logging into the bootstrap VM, and looking at the keepalived logs it showed the following:

```
# crictl logs 2dca9eaaa10f38
VRRP_Instance(rna1_API) ignoring received advertisment...
(rna1_API): received an invalid passwd!
bogus VRRP packet received on ens3 !!!
VRRP_Instance(rna1_API) ignoring received advertisment...
(rna1_API): received an invalid passwd!
bogus VRRP packet received on ens3 !!!
VRRP_Instance(rna1_API) ignoring received advertisment...
```
Googling the above issue resulted in finding out that if you have multiple environments sharing the same virtual_router_id you will get the VRRP collision as shown above. 

Snippet of the keepalived.conf file on my bootstrap VM
```
# crictl exec 2dca9eaa10fe8 cat /etc/keepalived/keepalived.conf
# Configuration template for Keepalived, which is used to manage the DNS and
# API VIPs.
#
# For more information, see installer/data/data/bootstrap/baremetal/README.md
# in the installer repo.
vrrp_instance rna1_API {
    state BACKUP
    interface ens3
    virtual_router_id 154
    priority 50
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass rna1_api_vip
    }
    virtual_ipaddress {
        10.19.140.44/21
    }
}
```
The algorithm fletcher8 is used to generate a unique virtual_router_id, however, I was able to consistently reproduce this issue 100% of the time. Each time receiving the same virtual_router_id of 154. My understanding is that my node name of provision host matters when generating the ID.

https://github.com/openshift/installer/blob/a7d201ad16ab65c5162d3c6d3553cc1903cea528/data/data/bootstrap/baremetal/files/usr/local/bin/fletcher8#L1-L16

https://github.com/openshift/installer/blob/a7d201ad16ab65c5162d3c6d3553cc1903cea528/data/data/bootstrap/baremetal/files/usr/local/bin/keepalived.sh#L31-L32

## Manual Workaround 

The workaround is to provide the keepalived container a new virtual_router_id and restart the keepalived on the bootstrap VM. Once the bootstrap VM has been destroyed and the API VIP now resides on the masters, we must also change the virtual_router_id on the master nodes as the original value will reside. 

Steps to fix:

On the bootstrap VM:
```
# Get the container ID of keepalived
# crictl ps -a

Inspect the container to get the path of where keepalived.conf is stored
# crictl inspect <id> 
```
Looks something like this
```
   "mounts": [
      {
        "containerPath": "/etc/keepalived",
        "hostPath": "/var/lib/kubelet/pods/653f02a70ba686f9ba4c94b0c4d1f834/volumes/kubernetes.io~empty-dir/conf-dir",
        "propagation": "PROPAGATION_PRIVATE",
        "readonly": false,
        "selinuxRelabel": false

# Grab the path relating to keepalived dir config
# cd /var/lib/kubelet/pods/653f02a70ba686f9ba4c94b0c4d1f834/volumes/kubernetes.io~empty-dir/conf-dir

# Modify the virtual_router_id under the vrrp_instance_<clustername>_API
# vi keepalive.conf
# Save the file
# Stop the existing keepalived container
# crictl stop <id> 

The new keepalived pod should autostart with the newly virtual_router_id you inputted.
Confirm within the bootstrap VM that the 'ip -a' now shows your API VIP IP. Example of my ens3 showing my (10.19.140.44 - API VIP), (10.19.140.45 ns1 VIP)
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:ae:ac:61 brd ff:ff:ff:ff:ff:ff
    inet 10.19.142.225/21 brd 10.19.143.255 scope global dynamic noprefixroute ens3
       valid_lft 41045sec preferred_lft 41045sec
    inet 10.19.140.45/21 scope global secondary ens3
       valid_lft forever preferred_lft forever
    inet 10.19.140.44/21 scope global secondary ens3
       valid_lft forever preferred_lft forever
```

Once the bootstrap VM is destroyed, you will need to log into each master node and modify the /etc/keepalived/keepalived.conf file and replace the virtual_router_id on the API section with the one you specified previously in the bootstrap VM. Then restart the keepalived container on each master node and your API VIP IP will be pingable. 

Obviously, the workaround is not ideal but it does provide a way to have multiple IPI on baremetal clusters on the same broadcast domain.

**Comment by rlopez133** [comment]
@hardys @celebdor @cooktheryan @dav1x @sreichar

**Comment by stbenjam** [comment]
/retitle baremetal: VRRP traffic collision when multiple clusters using the same broadcast domain
