### ISSUE TITLE
fcos installer doubles 99_openshift-machineconfig_99-master-ssh.yaml in bootstrap

### ISSUE THREAD

**Issue by gtema** [openshift/installer#2975]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-2411-g1dce0a90471670f87843c7824764edade9cfcb12
built from commit 1dce0a90471670f87843c7824764edade9cfcb12
release image registry.svc.ci.openshift.org/origin/release:4.3
```

# Platform:

baremetal

# What happened?
`openshift create ignition-configs` duplicates 99_openshift-machineconfig_99-master-ssh.yaml and 99_openshift-machineconfig_99-worker-ssh.yaml in the bootstrap.ign, what results in machines refusing this ignition

```
gtema@localhost:test$  openshift-install create manifests
INFO Consuming Install Config from target directory
WARNING Making control-plane schedulable by setting MastersSchedulable to true for Scheduler cluster settings
gtema@localhost:test$ grep "99-" .openshift_install_state.json
                "Filename": "openshift/99_openshift-machineconfig_99-master-ssh.yaml",
                "Filename": "openshift/99_openshift-machineconfig_99-worker-ssh.yaml",
gtema@localhost:test$ openshift-install create ignition-configs
INFO Consuming Openshift Manifests from target directory
INFO Consuming Worker Machines from target directory
INFO Consuming Master Machines from target directory
INFO Consuming Common Manifests from target directory
gtema@localhost:test$ grep "99-" .openshift_install_state.json
                        "path": "/opt/openshift/openshift/99_openshift-machineconfig_99-master-ssh.yaml",
                        "path": "/opt/openshift/openshift/99_openshift-machineconfig_99-worker-ssh.yaml",
                        "path": "/opt/openshift/openshift/99_openshift-machineconfig_99-master-ssh.yaml",
                        "path": "/opt/openshift/openshift/99_openshift-machineconfig_99-worker-ssh.yaml",
                "Filename": "openshift/99_openshift-machineconfig_99-master-ssh.yaml",
                "Filename": "openshift/99_openshift-machineconfig_99-worker-ssh.yaml",
                "Filename": "openshift/99_openshift-machineconfig_99-master-ssh.yaml",
                "Filename": "openshift/99_openshift-machineconfig_99-worker-ssh.yaml",
```

So the files are duplicated already in the state file

# What you expected to happen?

those 2 files did not duplicate

# How to reproduce it (as minimally and precisely as possible)?

install_config.yaml:
```
apiVersion: v1
baseDomain: fake.com
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
metadata:
  name: test
networking:
  clusterNetworks:
  - cidr: 192.168.190.0/24
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9LIyvvV6ur6549MLmwxYid2XV4+GZo0aOsvzNLBZRMx/6GtznMTjxmIRWECKi/M5sqKTpK7TsrWt4kDLXbYUDmVZy+y+/7nEJlpsQmmcr3/1/vKAAt4bDVpbZJyUEMoVT1QOK/IQ2yW0LM3afG43IpeyRk0P13kUvNtrK3dmLBAa6+0OFk0pYx0yv7V6P28P/zct2Wt4dVXpJ13PtxVRUuzBirEv3vJplZtDcEJ9aJl6jVsPrw2VdVEC57hkuFoK+TwKyKCqJheL5mTUnRMKkI4IA29lnhAlR96Gsj1mXltzs/Hl681F0BCXKtnOgcIj0o5uVwnwpWN+U08OF2eYj root@local
```

```console
$ openshift-installer create manifests
$ openshift-installer create ignition-configs
```

# Anything else we need to know?

fcos branch

# References

**Comment by SriRamanujam** [comment]
I'm seeing this on the 4.4 CI builds too. It started happening with https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-24-140857 this build on there.

**Comment by vrutkovs** [comment]
Why is Ignition refusing duplicated files, what's the error message?

**Comment by gtema** [comment]
something like:

 10.776386] ignition[597]: error at $.storage.files.48, line 1 col 100405: duplicate entry defined
[ 10.783147] ignition[597]: error at $.storage.files.49, line 1 col 101854: duplicate entry defined
[[0;1;31mFAILED[0m] Failed to start [0;1;39mIgnition (fetch)[0m.

**Comment by SriRamanujam** [comment]
I did some more investigation. It seems like setting `mastersSchedulable` to `false` (the default is `true`) in `manifests/cluster-scheduler-02-config.yml` causes this duplication. This is currently recommended by the Openshift 4.3 docs for baremetal UPI deployment (see step 2 of the procedure [here](https://docs.openshift.com/container-platform/4.3/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-generate-k8s-manifest-ignition_installing-bare-metal), which is where I got it from, and I would guess where @gtema got it from as well). There's also a warning about this when you generate the manifests:

```
INFO Consuming Install Config from target directory
WARNING Making control-plane schedulable by setting MastersSchedulable to true for Scheduler cluster settings
```

**Comment by vrutkovs** [comment]
Lets move this to https://github.com/installer/okd, since it appears to be related to Ignition 3 patches

/close

**Comment by gtema** [comment]
@vrutkovs not sure I got where you meant to move

**Comment by vrutkovs** [comment]
Oh, I was hoping I could transfer this issue to a different repo via github's feature, but its not available here.

Please resubmit the issue to https://github.com/openshift/okd repo
