### ISSUE TITLE
Automated provisioning of a bastion box

### ISSUE THREAD

**Issue by garymoon** [openshift/installer#2981]
# Version
4.3.0

# Platform:
AWS

# What happened?
The v4 installer requires that you manually provision a bastion box should you want access to unresponsive cluster nodes.

# What you expected to happen?
It would be great to an automated means to provision such a box using the state the installer leaves behind when the needs arises instead of having to manually provision it ourselves.

Thank you.

**Comment by abhinavdahiya** [comment]
You don't need a dedicated box for that, there are other ways to get access to the ec2 instances like `oc debug node` or https://github.com/eparis/ssh-bastion

**Comment by garymoon** [comment]
Thanks @abhinavdahiya, but both of these options require the cluster to be functional. My impression from the documentation is that the only way to access nodes of a non-functional cluster is by bastion box.

**Comment by abhinavdahiya** [comment]
> Thanks @abhinavdahiya, but both of these options require the cluster to be functional. My impression from the documentation is that the only way to access nodes of a non-functional cluster is by bastion box.

But the original comment doesn't mention need for a bastian for _recovery_ cases ? 
and adding a machine to all installations for _recovery_ seems like an overkill. and creating a bastian host in those cases should be fairly simple.

**Comment by garymoon** [comment]
> But the original comment doesn't mention need for a bastian for recovery cases ?

Thanks for pointing that out @abhinavdahiya, I've amended my original post.

>  and adding a machine to all installations for recovery seems like an overkill. and creating a bastion host in those cases should be fairly simple.

I wouldn't want each cluster to come non-optionally with a bastion box, but rather that they can optionally be created at install time, or by automated means at a later time (during recovery). From my perspective, manually creating a bastion box during such a recovery process is not ideal.

**Comment by akostadinov** [comment]
I wonder if installer could create bastion (when requested) in a standard way. Such that if bastion already exist, only add network interface to it for new clusters. When destroying a cluster, that interface can be removed given there are still other clusters in the same account.

**Comment by abhinavdahiya** [comment]
We don't intend to add bastian using installer, I do not think installer is correct place to help users with this requirement, a simple cloud formation template should be easy enough to get that behavior on AWS.

/close
