### ISSUE TITLE
How to create manifests with multiple masters and workers

### ISSUE THREAD

**Issue by qzhang90** [openshift/installer#3004]
# Version

```
./installer/bin/openshift-install v0.16.1-dirty
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform:
libvirt

# What happened?

I created an OpenShift cluster by using the following command:
```
step 1: ./installer/bin/openshift-install --dir install-dir create manifests
step 2: ./installer/bin/openshift-install --dir install-dir create cluster      
```
However, the cluster has only 1 master and 1 worker. I assume the cluster created in step 2 is based on the manifests created in step 1. Thus my question is how to create a cluster with multiple masters and multiple workers?

**Comment by abhinavdahiya** [comment]
you can create an install-config, modify it to desired count of control plane and compute.

docs:
https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations
https://github.com/openshift/installer/blob/master/docs/user/customization.md#machine-pools

example:
https://github.com/openshift/installer/blob/master/docs/user/customization.md#custom-machine-pools

**Comment by abhinavdahiya** [comment]
> you can create an install-config, modify it to desired count of control plane and compute.
> 
> docs:
> https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations
> https://github.com/openshift/installer/blob/master/docs/user/customization.md#machine-pools
> 
> example:
> https://github.com/openshift/installer/blob/master/docs/user/customization.md#custom-machine-pools
