### ISSUE TITLE
[FCOS] Azure: No workers created if a custom image is used

### ISSUE THREAD

**Issue by jomeier** [openshift/installer#3017]
Hi,

I manually uploaded the decompressed FCOS image to a Azure storage blob in a resourcegroup and let Terraform create an fcos image from that. I had to patch openshift-install that I can do that in /data/data/azure/main.tf

The idea is that all my OKD cluster VMs use this image and I don't have to upload it every time I create a new cluster becaue in my case thats very slow (more than 25 minutes following a timeout).

The k8s control plane comes up this way but no workers are created.

I debugged that and saw that in the machineset for the workers still the "original" fcos image is referenced and not my own image which is in a different resource group.

The image for the machineset is defined in:

/pkg/asset/machines/azure/machines.go

I would like to create a parameter in the Azure installer where I can ask for the storage blob where the fcos vhd file is stored. 

What do you think about this idea?

Greetings,

Josef

**Comment by vrutkovs** [comment]
/close

Use openshift/okd
