### ISSUE TITLE
VM running on oVirt/RHV should use discard(fstrim) option

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/installer#3021]
In oVirt/RHV, virtual disks need to use the newer VirtIO-SCSI driver to pass on fstrim/discard instructions to the underlying storage.
It seems the right [interface](https://github.com/openshift/installer/blob/master/data/data/ovirt/template/main.tf#L58) was configured by @rgolangh but enabling discard support is an extra bool in the oVIrt API which the TF code isn't setting.
I believe this feature is important for setup where the underlying storage is thinly provisioned which is often the case in hyperconverged clusters.

**Comment by TFK1410** [comment]
This is something that I'm also interested about. I'd also like for discard be enabled by default for my hyperconverged setup. 
This should just be a matter of inserting `pass_discard = true` into the block_device item.
