### ISSUE TITLE
baremetal: ETCD_ENDPOINTS assigned with provision network IP address

### ISSUE THREAD

**Issue by zshi-redhat** [openshift/installer#3041]
# Version
Client Version: 4.4.0-0.nightly-2020-01-31-190444

```console
$ openshift-install version
built from commit 4922752840a113e61df22cb56a8c0848ea7ae0df
release image registry.svc.ci.openshift.org/ocp/release@sha256:4c84fe20de2cbf4f5dee7206144b9d027efa21e29cb87e6f7f7fbeb51535ea4e
```

# Platform:

Baremetal UPI

# What happened?

Certificate is invalid for IP address used as etcd endpoint. Bootstrap process timeout.
Etcd endpoint retrieved from [here](https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L117) is using IP address from provision network, for example '172.22.0.35'

```console
Feb 01 12:51:17 ci-bootstrap bootkube.sh[2707]: {"level":"warn","ts":"2020-02-01T12:51:17.659Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-99e7413e-b4e8-4495-aad1-396f0469973b/172.22.0.35:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 192.168.111.10, 127.0.0.1, not 172.22.0.35\""}
Feb 01 12:51:17 ci-bootstrap bootkube.sh[2707]: https://172.22.0.35:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Feb 01 12:51:17 ci-bootstrap bootkube.sh[2707]: Error: unhealthy cluster
```

# What you expected to happen?

Etcd endpoint uses IP address from baremetal network instead of provision network, for example '192.168.111.10'. 
Bootstrap succeeds.

# How to reproduce it (as minimally and precisely as possible)?

Run UPI installation of latest 4.4 (e.g. 4.4.0-0.nightly-2020-01-31-190444) and check bootkube.service log

```console
$ journal -b -f -u bootkube.service
```

# Anything else we need to know?

4.3 deployment (4.3.0-0.nightly-2020-01-30-173504) succeeded on the same UPI baremetal environment. The network re-requisites have been properly set up.

# References

Output of network interfaces on bootstrap VM:
```console
ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.0.35  netmask 255.255.255.0  broadcast 172.22.0.255
        inet6 fe80::5054:ff:fe82:683f  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:82:68:3f  txqueuelen 1000  (Ethernet)
        RX packets 354  bytes 23830 (23.2 KiB)
        RX errors 0  dropped 748  overruns 0  frame 0
        TX packets 29  bytes 3578 (3.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 6

ens4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.111.10  netmask 255.255.255.0  broadcast 192.168.111.255
        inet6 fe80::5054:ff:fe82:683e  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:82:68:3e  txqueuelen 1000  (Ethernet)
        RX packets 269482  bytes 360969929 (344.2 MiB)
        RX errors 0  dropped 19003  overruns 0  frame 0
        TX packets 25155  bytes 3480591 (3.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 126045

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 61669  bytes 6059226 (5.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 61669  bytes 6059226 (5.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by hexfusion** [comment]
/assign

Nice write up we will review. For the fastest turnaround, access to a cluster would be greatly appreciated.

/cc @alaypatel07

**Comment by alaypatel07** [comment]
Created a BZ to track this:  https://bugzilla.redhat.com/show_bug.cgi?id=1797796

**Comment by romfreiman** [comment]
According to the code of startironic, it expects the provisioning to be on ens4.
Maybe it's possible just to filter it out during the ip selection?

https://github.com/openshift/installer/blob/master/data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template#L26
