### ISSUE TITLE
RFE: Validate Pull Secret

### ISSUE THREAD

**Issue by iamemilio** [openshift/installer#3050]
# Version 4.5+

# Platform: All

# What happens?
When your pull secret is stale, the installer still runs and deploys masters and bootstrap nodes. Its fairly annoying to comb through the journalctl logs to figure this out.

# What you expected to happen?
The installer tries your pull secret out quickly during the validation phase. If your pull secret is stale, it terminates, and reports this as an error to the user.

# Additional Questions?
Is this the installer's responsibility? Should it be?

**Comment by abhinavdahiya** [comment]
> Is this the installer's responsibility? Should it be?

to validate the pull secret, the installer will have to contact the registry.

Currently there is no requirement that the host running the installer has access to reach the registry, esp in case of disconnected / proxy setups. And personally I am not very inclined to introduce this new requirement.

For our actual users, these should never be a failure case as they get release binaries and pull secret.

And only our developers end up in this situation when using expiring creds to talk to `registry.svc.ci.openshift.org`
