### ISSUE TITLE
[vsphere] 4.3 unable to pull from quay.io on bootstrap host

### ISSUE THREAD

**Issue by a-dawg** [openshift/installer#3064]
# Version

```console
$ openshift-install version
 openshift-install version
openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d

```

# Platform:
vsphere + coreos 4.3 + upi terraform

# What happened?
Cannot pull the base image on the bootstrap machine
`Feb 05 15:47:44 bootstrap-0 bootkube.sh[21852]: Error: unable to pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:133c08d3efdaabdb508c743f0ca95f26826d7c2fabfffcaafdacd1237c3bcd10: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:133c08d3efdaabdb508c743f0ca95f26826d7c2fabfffcaafdacd1237c3bcd10: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate signed by unknown authority
`

# What you expected to happen?
installation should continue further

# How to reproduce it (as minimally and precisely as possible)?

```console
$ terraform apply
```

**Comment by abhinavdahiya** [comment]
Can you run `curl -v https://quay.io/v2/` from the bootstrap host?

Also if you can provide some details around your setup, that would also help, like
are you using explicit proxy, or mitm proxy by any chance, or what version of RHCOS are you using.

Also if you can capture the log bundle by using `gather bootstrap` subcommand that can also help in debugging.

**Comment by a-dawg** [comment]
curl return an ssl issue I know that is the problem but I am surprised that the RHCOS does not embed the right CA.
```curl -Lv "https://quay.io/v2"
*   Trying 18.214.53.124...
* TCP_NODELAY set
* Connected to quay.io (18.214.53.124) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I ran this command from the bootstrap machine and I do not use any proxy. 
````NAME="Red Hat Enterprise Linux CoreOS"
VERSION="43.81.202001142154.0"
VERSION_ID="4.3"
OPENSHIFT_VERSION="4.3"
RHEL_VERSION=8.0
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 43.81.202001142154.0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.3"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.3"
OSTREE_VERSION='43.81.202001142154.0'
````

**Comment by a-dawg** [comment]
that was a problem on my network setup

**Comment by Dasaenz499** [comment]
@a-dawg Can you confirm the problem in the network setup for replicate in my installation because I have the same error.

Thanks.

**Comment by a-dawg** [comment]
I was using a proxy in front of my bootstrap node which filtered the urls for quay.io
