### ISSUE TITLE
Can not create the OCP cluster on GCP using openshift-install v4.2.1

### ISSUE THREAD

**Issue by hchenxa** [openshift/installer#3085]
# Version

```console
$ openshift-install version
[root@spiv-inf gcp]# openshift-install version
openshift-install v4.2.1
built from commit e349157f325dba2d06666987603da39965be5319
release image quay.io/openshift-release-dev/ocp-release@sha256:dc782b44cac3d59101904cc5da2b9d8bdb90e55a07814df50ea7a13071b0f5f0
```

# Platform:

GCP
# What happened?

Trying the install ocp on GCP via openshift-install v 4.2.1, find the cluster can not create success, check the log, the reason seems like the kubelet can not started on bootstrap node due to crio issue like below:
```
Feb 10 07:57:28 hchenx-nm4xm-b.c.oceanic-guard-191815.internal hyperkube[1660]: E0210 07:57:28.797489    1660 remote_runtime.go:85] Version from ru
ntime service failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc =
"transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory"
Feb 10 07:57:28 hchenx-nm4xm-b.c.oceanic-guard-191815.internal hyperkube[1660]: E0210 07:57:28.797629    1660 kuberuntime_manager.go:196] Get runti
me version failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "tr
ansport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory"
Feb 10 07:57:28 hchenx-nm4xm-b.c.oceanic-guard-191815.internal hyperkube[1660]: F0210 07:57:28.797667    1660 server.go:268] failed to run Kubelet:
 failed to create kubelet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: de
sc = "transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory"
```

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?
The cluster should be created successful
# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
For a failed installation, the installer should capture a log bundle, that should help us debug better. If you can attach it here that would be nice, or you can also open a BugZilla bug https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform component `Installer`..

Also can you provide more context on how you are creating this cluster.

**Comment by abhinavdahiya** [comment]
> For a failed installation, the installer should capture a log bundle, that should help us debug better. If you can attach it here that would be nice, or you can also open a BugZilla bug https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform component `Installer`..
> 
> Also can you provide more context on how you are creating this cluster.

/close
