### ISSUE TITLE
Install vsphere 4.3 kube-apiserver-lb-signer error

### ISSUE THREAD

**Issue by a-dawg** [openshift/installer#3093]
# Version

```console
$ openshift-install version
 openshift-install version
openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
```

# Platform:
vsphere + coreos 4.3 + upi terraform

# What happened?
````
openshift-install wait-for bootstrap-complete --log-level debug
DEBUG OpenShift Installer v4.3.0
DEBUG Built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
INFO Waiting up to 30m0s for the Kubernetes API at https://api.xxxxxx:6443...
DEBUG Still waiting for the Kubernetes API: Get https://api.xxxxxx:6443/version?timeout=32s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer
````

# What you expected to happen?
installation should continue further

# How to reproduce it (as minimally and precisely as possible)?

```console
openshift-install wait-for bootstrap-complete --log-level debug

```

**Comment by a-dawg** [comment]
[log-bundle-20200211155951.tar.gz](https://github.com/openshift/installer/files/4186969/log-bundle-20200211155951.tar.gz)

**Comment by sithebeme** [comment]
Hi,
Was this resolved? How?

**Comment by vap0rtranz** [comment]
@a-dawg seeing this in OCP4.4.7 installing to vSphere6.7, so what was the resolution?

**Comment by dmudired** [comment]
facing same issue

**Comment by vap0rtranz** [comment]
We downgraded from 4.4.x to 4.3.8 ... but other variables are suspect.

**Comment by m-usmanayub** [comment]
can anybody comment on how this issue was resolved. facing the same issue on 4.6.8.

**Comment by staebler** [comment]
This may be a problem with the configuration of your load balancer. Please review https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere.html#installation-network-user-infra_installing-vsphere.
