### ISSUE TITLE
Can't generate install-config yaml on GCP

### ISSUE THREAD

**Issue by ybnelson** [openshift/installer#3104]
# Version

```console
$ openshift-install version
./openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
```

# Platform: GCP
 

# What happened?

FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": could not retrieve base domains: Get https://www.googleapis.com/dns/v1/projects/yugabyte/managedZones?alt=json&prettyPrint=false: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}

# What you expected to happen?

Trying to create an install-config.yaml for a GCP openshift cluster

# How to reproduce it (as minimally and precisely as possible)?

Downloaded openshift installer and openshift cli for Mac. Using google-cloud-sdk locally as well with google auth set to project owner account. Tried refreshing login and adc tokens with same error repeated on openshift-install.

```console
./openshift-install create install-config --dir=working/template --log-level=debug
```

# References

https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35
None of the given solutions are resolving the oauth login failure.

**Comment by abhinavdahiya** [comment]
> Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}

the installer prints the location of the credential source, maybe attach the .openshift_install.log

Also try using the service account json key file? 
https://github.com/openshift/installer/blob/master/docs/user/gcp/iam.md
and then use any one of these https://github.com/openshift/installer/blob/4a4d46ba90fed8c6a854c07ac320e2a6676c7984/pkg/asset/installconfig/gcp/session.go#L32-L35 ??

**Comment by ybnelson** [comment]
gcloud is working fine, can execute against my current project or any other assigned projects or apis. Have downloaded and used my service account json key file as well and exact same result.
[install.log](https://github.com/openshift/installer/files/4202201/install.log)

**Comment by abhinavdahiya** [comment]
> gcloud is working fine, can execute against my current project or any other assigned projects or apis. Have downloaded and used my service account json key file as well and exact same result.
> [install.log](https://github.com/openshift/installer/files/4202201/install.log)

can you give the nightly for 4.4 a try, you can download the installer from https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.4/

and attach the .openshift_install.log

**Comment by ybnelson** [comment]
Same exact error on 4.4 latest
cat .openshift_install.log 
time="2020-02-18T13:56:18-08:00" level=debug msg="OpenShift Installer v4.4.0"
time="2020-02-18T13:56:18-08:00" level=debug msg="Built from commit 4a4d46ba90fed8c6a854c07ac320e2a6676c7984"
time="2020-02-18T13:56:18-08:00" level=debug msg="Fetching Install Config..."
time="2020-02-18T13:56:18-08:00" level=debug msg="Loading Install Config..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Loading SSH Key..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Loading Base Domain..."
time="2020-02-18T13:56:18-08:00" level=debug msg="    Loading Platform..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Loading Cluster Name..."
time="2020-02-18T13:56:18-08:00" level=debug msg="    Loading Base Domain..."
time="2020-02-18T13:56:18-08:00" level=debug msg="    Loading Platform..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Loading Pull Secret..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Loading Platform..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Fetching SSH Key..."
time="2020-02-18T13:56:18-08:00" level=debug msg="  Generating SSH Key..."
time="2020-02-18T13:56:29-08:00" level=debug msg="  Fetching Base Domain..."
time="2020-02-18T13:56:29-08:00" level=debug msg="    Fetching Platform..."
time="2020-02-18T13:56:29-08:00" level=debug msg="    Generating Platform..."
time="2020-02-18T13:56:30-08:00" level=info msg="Credentials loaded from file \"/Users/andrewnelson/.gcp/osServiceAccount.json\""
time="2020-02-18T13:56:33-08:00" level=debug msg="  Generating Base Domain..."
time="2020-02-18T13:56:33-08:00" level=fatal msg="failed to fetch Install Config: failed to fetch dependency of \"Install Config\": failed to generate asset \"Base Domain\": could not retrieve base domains: Get https://www.googleapis.com/dns/v1/projects/yugabyte/managedZones?alt=json&prettyPrint=false: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Invalid grant: account not found\"}"

**Comment by abhinavdahiya** [comment]
> time="2020-02-18T13:56:30-08:00" level=info msg="Credentials loaded from file "/Users/andrewnelson/.gcp/osServiceAccount.json""

`/Users/andrewnelson/.gcp/osServiceAccount.json` is the credential that installer is using.

what if you follow https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account to use that serviceaccount key file from `/Users/andrewnelson/.gcp/osServiceAccount.json` and then try to use gcloud? does that work.

**Comment by ybnelson** [comment]
Deleting the osServiceAccount.json allowed me to recreate that on the next run of openshift-install create install-config with my service account. For whatever reason, that json was invalid and each attempt of openshift-install would only re-use it. Thanks!
