### ISSUE TITLE
Could not update oauthclient "console" (287 of 494): the server is down or not responding 

### ISSUE THREAD

**Issue by fenggolang** [openshift/installer#3105]
# Version

```console
[root@cloud-com-1 rhcos]# openshift-install version
openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image registry.okd4.com:5000/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
[root@cloud-com-1 rhcos]# 
```

# Platform:
baremetal

# What happened?
[root@cloud-com-1 rhcos]# oc get node
NAME                            STATUS   ROLES    AGE     VERSION
master0.okd4-cluster.okd4.com   Ready    master   3h20m   v1.16.2
master1.okd4-cluster.okd4.com   Ready    master   3h20m   v1.16.2
master2.okd4-cluster.okd4.com   Ready    master   3h20m   v1.16.2
worker0.okd4-cluster.okd4.com   Ready    worker   164m    v1.16.2
worker1.okd4-cluster.okd4.com   Ready    worker   164m    v1.16.2
[root@cloud-com-1 rhcos]# oc get clusteroperator
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                                       Unknown     Unknown       True       163m
cloud-credential                           4.3.0     True        False         False      3h20m
cluster-autoscaler                         4.3.0     True        False         False      80m
console                                    4.3.0     False       True          True       83m
dns                                        4.3.0     True        False         False      3h2m
image-registry                             4.3.0     True        False         False      163m
ingress                                    4.3.0     True        False         False      98m
insights                                   4.3.0     True        False         False      3h16m
kube-apiserver                             4.3.0     True        False         False      3h2m
kube-controller-manager                    4.3.0     True        False         False      3h4m
kube-scheduler                             4.3.0     True        False         True       3h6m
machine-api                                4.3.0     True        False         False      3h3m
machine-config                             4.3.0     True        False         False      9m45s
marketplace                                4.3.0     True        False         False      163m
monitoring                                           False       True          True       157m
network                                    4.3.0     True        True          False      3h16m
node-tuning                                4.3.0     True        False         False      16m
openshift-apiserver                        4.3.0     False       False         False      150m
openshift-controller-manager               4.3.0     True        False         False      3h2m
openshift-samples                                    False       False         False      36m
operator-lifecycle-manager                 4.3.0     True        False         False      3h3m
operator-lifecycle-manager-catalog         4.3.0     True        False         False      3h3m
operator-lifecycle-manager-packageserver   4.3.0     False       True          False      151m
service-ca                                 4.3.0     True        False         False      3h16m
service-catalog-apiserver                  4.3.0     True        False         False      163m
service-catalog-controller-manager         4.3.0     True        False         False      164m
storage                                    4.3.0     True        False         False      162m
[root@cloud-com-1 rhcos]# 
[root@cloud-com-1 rhcos]# openshift-install wait-for install-complete --log-level debug
DEBUG OpenShift Installer v4.3.0                   
DEBUG Built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e 
INFO Waiting up to 30m0s for the cluster at https://api.okd4-cluster.okd4.com:6443 to initialize... 
DEBUG Still waiting for the cluster to initialize: Could not update oauthclient "console" (287 of 494): the server is down or not responding 
DEBUG Still waiting for the cluster to initialize: Could not update oauthclient "console" (287 of 494): the server is down or not responding 
![image](https://user-images.githubusercontent.com/16982786/74524042-42d28d00-4f59-11ea-905f-3f1f19c1588f.png)

[root@cloud-com-1 auth]# oc get oauth cluster -o yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2020-02-14T07:22:41Z"
  generation: 1
  name: cluster
  resourceVersion: "1972"
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: 41a410cc-de83-4206-b55b-4e7a51addeeb
spec: {}
[root@cloud-com-1 auth]# 

# What you expected to happen?
openshift-console-operator service is normal

**Comment by abhinavdahiya** [comment]
> NAME VERSION AVAILABLE PROGRESSING DEGRADED SINCE
authentication Unknown Unknown True 163m
operator-lifecycle-manager-packageserver 4.3.0 False True False 151m

Seem like the problem...
you can investigate those cluster operators for more details. 

on failure, the installer will print failing clusteroperators, you can attach the .openshift_install.log file.

For debugging `oc adm must-gather` should help... and you can open a BZ https://bugzilla.redhat.com/ for OKD in case you want to attach it privately.

Also okd issues should be opened in https://github.com/openshift/okd or on the corresponding failing operator.
