### ISSUE TITLE
KubeCA generates certificates that won't match the ca.crt mounted in Pod

### ISSUE THREAD

**Issue by rodrigovalin** [openshift/installer#3124]
# Version

```console
$ openshift-install version
openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
```

# Platform:

AWS

# What happened?

I'm generating certificates with certificates API and approving to provide automatic TLS for the MongoDB Enterprise Operator. These certificates are meant to be used by MongoDB servers for server/client authentication.

The problem is that the `ca.crt` file in the Pod (/var/run/secrets/kubernetes.io/serviceaccount/ca.crt) can't verify the authenticity of this generated certificate, meaning that this certificate, from client's perspective, is not secure.

The CommonName of the `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` certificate is `kube-apiserver-lb-signer`, while the CommonName of the Issuer of my server certificate is `kube-csr-signer_@1581508444`. I'm not sure this is expected.

# What you expected to happen?

I expect that the certificates issued when doing `kubectl certificate approve` to "match" or to be able to be verified with the certificates in `ca.crt` files.

# How to reproduce it (as minimally and precisely as possible)?

Based on https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

### 1
```
cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "my-svc.my-namespace.svc.cluster.local",
    "my-pod.my-namespace.pod.cluster.local",
    "192.0.2.24",
    "10.0.34.2"
  ],
  "CN": "my-pod.my-namespace.pod.cluster.local",
  "key": {
    "algo": "ecdsa",
    "size": 256
  }
}
EOF
```

### 2
```
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```

### 3 
```
# approve the cert
oc adm certificate approve my-svc.my-namespace
```
### 4
```
# get the signed certificate from kube-ca
kubectl get csr my-svc.my-namespace -o jsonpath='{.status.certificate}' \
    | base64 --decode > server.crt
```

### 5
```
# What's in here?
openssl x509 -in server.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            17:d2:ea:ea:a3:f0:82:e1:8c:6c:b8:ad:63:ef:22:fd:05:6a:6f:25
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = kube-csr-signer_@1581508444
        Validity
            Not Before: Feb 18 15:16:00 2020 GMT
            Not After : Mar 13 11:48:57 2020 GMT
        Subject: CN = my-pod.my-namespace.pod.cluster.local
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    ...
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                80:9D:43:52:B1:FE:9F:6A:88:26:AD:4E:CD:C3:D0:E1:34:35:43:66
            X509v3 Authority Key Identifier:
                keyid:C9:FD:E4:43:0D:1F:68:31:B1:24:66:E8:6C:16:67:53:BF:43:54:B8

            X509v3 Subject Alternative Name:
                DNS:my-svc.my-namespace.svc.cluster.local, DNS:my-pod.my-namespace.pod.cluster.local, IP Address:192.0.2.24, IP Address:10.0.34.2
    Signature Algorithm: sha256WithRSAEncryption
        ....
```

The certificate has been issued by "kube-csr-signer_@1581508444" which is not the same CA that is mounted into the Pods.

# Anything else we need to know?

This works out of the box in other Kubernetes distributions I have tried. In kind, for instance, the CA certificate in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt matches (`openssl verify -CAfile ca.crt my-certificate.crt`) the certs issued by Kube CA.

# References

- I have not been able to find any directions on this particular problem./

**Comment by abhinavdahiya** [comment]
> /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

That certificate allows the clients to trust the server, in this case this is kube-apiserver.

> certificate issued by CSR API

That certificate is a client certificate, used to issue client certificates, i.e the kube-apiserver allows the client to be an authenticated client.

Why do you expect those to be signed by same CA??

**Comment by abhinavdahiya** [comment]
And If you want to use the CSR API to provide serving certificates, i think you will have to open a BZ for kube-apiserver component https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform

The certificates are controlled by cluster-kube-apiserver-operator and installer is not involved in this. So we will not be able to help you with this to a great degree.

**Comment by rodrigovalin** [comment]
Thanks for the clarification @abhinavdahiya 

> That certificate allows the clients to trust the server, in this case this is kube-apiserver.

It was very clear from the docs [here](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/) that the certificates.k8s.io API will allow this particular use case. In the examples they create a "server" certificate. Reviewing the docs I can see:

* [1.14](https://v1-14.docs.kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#trusting-tls-in-a-cluster) -> Indicates that the `ca.crt` file can be used to verify the certs generated.
* [1.15](https://v1-15.docs.kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#trusting-tls-in-a-cluster) -> Removed the notion of the `ca.crt` file in the Pod.

I will close this now as I think it is outside the scope of `openshift/installer`.
