### ISSUE TITLE
How to specify the CPU and memory allocated to the workers

### ISSUE THREAD

**Issue by qzhang90** [openshift/installer#3125]
# Version
```
# ./bin/openshift-install version
./bin/openshift-install v0.16.1-dirty
built from commit e3fceacc975953f56cb09931e6be015a36eb6075
```

# Platform:
`libvirt`

# What happened?
I am wondering how to specify the number of CPUs and the amount of memory for each worker machine. Noticed we can specify such parameters for the master machine in this file (https://github.com/openshift/installer/blob/master/data/data/libvirt/variables-libvirt.tf) as `libvirt_master_memory ` and `libvirt_master_memory `. Is there any similar parameters for workers? In addition, what if I want to specify different number of CPUs/memory for different workers?

**Comment by abhinavdahiya** [comment]
the supported way is to

```
$ openshift-install create manifets
# edit the machine or machineset objects in openshift/ to use the required cpu/mem
$ openshift-install create cluster
```

/close
