### ISSUE TITLE
Private-Hosted DNS IPI for OCP 4.4

### ISSUE THREAD

**Issue by ckyriakidou** [openshift/installer#3136]
# Version

```console
$ openshift-install version 4.4 2020-02-19
aws route53 create-hosted-zone --name sheitsandgiggles.local --hosted-zone-config Comment="command-line version,PrivateZone=true" --vpc="VPCRegion=eu-central-1,VPCId=vpc-04190539ddd88f0d2" --caller-reference "$(date)"

aws route53 create-hosted-zone --name sheitsandgiggles.local --hosted-zone-config Comment="command-line version,PrivateZone=true" --vpc="VPCRegion=eu-west-1,VPCId=vpc-0159b68b260012880" --caller-reference "$(date)"
-bash: aws: command not found
[ec2-user@ip-172-31-45-212 ~]$ ./openshift-install create install-config --dir=try2
? SSH Public Key /home/ec2-user/.ssh/id_rsa.pub
? Platform aws
INFO Credentials loaded from the "default" profile in file "/home/ec2-user/.aws/credentials" 
? Region eu-central-1
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": no public Route 53 hosted zones found 
```

# Platform:
aws private - building cluster as mentioned https://aws.amazon.com/blogs/networking-and-content-delivery/creating-a-single-internet-exit-point-from-multiple-vpcs-using-aws-transit-gateway/ here on AWS for a pre-existing VPC and looking to create the cluster with a private hosted zone. 
I want to get the configuration so that I can edit the above. 

# What happened?
fails to create the yaml.

# What you expected to happen?
Creating the yaml skeleton but with a private hosted zone.

# How to reproduce it (as minimally and precisely as possible)?

follow the routing and isntance creation documentation in aws, add the dns changes required for OCP and add a private hosted zone.

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
To create a cluster with no acces from internet i.e internal only you can look at the docs

https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-private.html

which also requires https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-vpc.html

/close

**Comment by ckyriakidou** [comment]
Hello, Yes, I've seen the documents. I'm saying it's not acceptable to have a public hosted zone in AWS for a "private-access" cluster. Yes I understand the masters and the nodes are not going to be accessed unless you have access to the VPC but the installation should be done with a .local zone so that naming conventions and DNS names are not exposed to the public. This is not currently possible with IPI. Tested yesterday with a 4.4 nightly.
