### ISSUE TITLE
support vCloud Director platform

### ISSUE THREAD

**Issue by iyurev** [openshift/installer#3145]
Good day!

We're using vCloud Director as infrastructure platform, it will be nice to have opportunity creating openshift clusters without  bothering with UPI and other operation overhead.   

Have you planned  native support this platform in the future or roadmap ??

**Comment by katherinedube** [comment]
vCloud Director is only available to Telcos/CSPs. There are a number of differences in this product offering to vSphere, so It's not something we're planning to support or have on our roadmap at this time.

**Comment by abhinavdahiya** [comment]
Please open issues on against https://github.com/openshift/enhancements/blob/master/ROADMAP.md for these platforms.

Or open RFEs on https://issues.redhat.com/projects/RFE

/close
