### ISSUE TITLE
AWS: InvalidChangeBatch error for public zone records from previously failed installation

### ISSUE THREAD

**Issue by brianotte** [openshift/installer#3157]
# Version

```console
$ openshift-install version
openshift-install 4.4.0-0.okd-2020-02-18-212654
```

# Platform:

AWS

# What happened?

Attempted to destroy previous cluster (first cluster installation attempt failed) with the following:
openshift-install --dir ./ITS_GO_TIME destroy cluster

The above succeeded -- but then the next install finds that the A Alias records in the cluster domain:

Entries expected to be removed:

api.CLUSTER.DOMAIN.COM A ALIAS ....
*.apps.CLUSTER.DOMAIN.COM A ALIAS

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

THE Following command:

```console
openshift-install --dir ./ITS_GO_TIME destroy cluster

UN-DOES exactly what this command DID:

openshift-install --dir ./ITS_GO_TIME create cluster

{RAINBOWS_AND_UNICORNS} 
```

# How to reproduce it (as minimally and precisely as possible)?

```console
openshift-install --dir ./ITS_GO_TIME create cluster (failure experienced so timed out at 20 minutes waiting for API).
openshift-install --dir ./ITS_GO_TIME destroy cluster 
openshift-install --dir ./ITS_GO_TIME create cluster
```
and received the following:

INFO Credentials loaded from the "default" profile in file "/RANDOM_LOCATION/JUST_THIS_GUY/.aws/credentials"
INFO Consuming Install Config from target directory
INFO Creating infrastructure resources...
ERROR
ERROR Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.CLUSTER.DOMAIN.COM.', type='A'] but it already exists]
ERROR 	status code: 400, request id: UUID-REDACTED-CAUSE-SEEMS-LIKE_DATA
ERROR
ERROR   on ../../../../../../../../private/var/folders/_g/STRINGOFCHARACTERS/T/openshift-install-386130103/route53/base.tf line 33, in resource "aws_route53_record" "api_external":
ERROR   33: resource "aws_route53_record" "api_external" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform

# Anything else we need to know?

Time is the most valuable resource no-one has enough of. 

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Please clean up the records from the route53 Zone, that is the only workaround due to restrictions on how we need to hold record in public dns to prevent users re-using a clustername and then affecting pre-existing clusters

/close
