### ISSUE TITLE
Add OWNERS file

### ISSUE THREAD

**Issue by paulfantom** [openshift/installer#32]
There should be an OWNERS file (like [this one](https://github.com/openshift/origin/blob/master/OWNERS)) to allow prow to manage who is allowed to review and/or approve PRs.

**Comment by wking** [comment]
It would be nice if this came with docs to make it more discoverable and explain how the file fits into project governance.  For example, the k8s template has [a brief reference from `CONTRIBUTING.md`][1] and (stale) links from the `OWNERS` file to upstream docs explaining how it works (kubernetes/kubernetes-template-project#15).  CRI-O has [a similar `CONTRIBUTING.md` line][2], which contains links to both `OWNERS` and (different) upstream docs.

[1]: https://github.com/kubernetes/kubernetes-template-project/blame/16f1588e6d4746876beb08cc64769657530d4872/CONTRIBUTING.md#L10
[2]: https://github.com/kubernetes-incubator/cri-o/blame/v1.11.0/CONTRIBUTING.md#L71

**Comment by stevekuznetsov** [comment]
The most up-to-date documentation is [here](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#code-review-using-owners-files) but we understand the documentation is not perfect today and we are working on making it better.
