### ISSUE TITLE
Installing on Intel Software RAID (VROC) leaves array in degraded state.

### ISSUE THREAD

**Issue by Feelas** [openshift/installer#3218]
# Version

```Openshift 4.2 and 4.3```

# Platform: 
baremetal

# What happened?
After the installer is launched with ```rd.md=1 rd.auto coreos.inst.install_dev=md126``` (where md126 is a reference to /dev/md126, which is an assembled VROC RAID1 array), the OS ends up installed, but the whole process leaves the array in ```degraded``` state. This leaves the system boostrapped not the way that was intended (with redundancy).

# What you expected to happen?
Installation on /dev/md126 to succeed properly without degrading the array. Maybe there's a special way to install CoreOS that way or modify the standard wipefs+dd behaviour?

# How to reproduce it (as minimally and precisely as possible)?
Assemble an Intel VROC RAID1 array and install to the resultant MD device (e.g. /dev/md126) with parameters provided above.

# Anything else we need to know?
Most probably this is due to how the installation process is handled. Possibly due to wipefs being launched, which kills the metadata on partition, and afterwards being overwritten with dd. I would probably investigate modifying the Ignition files manually, but I'd rather not delve into monkey patching myself.

**Comment by abhinavdahiya** [comment]
Please open the issue against https://github.com/openshift/os installing RHCOS on a house is a little out of bounds of openshift installer...

**Comment by Feelas** [comment]
> Please open the issue against https://github.com/openshift/os installing RHCOS on a house is a little out of bounds of openshift installer...

Thanks, I'll take it there.
