### ISSUE TITLE
Azure: Installer does not associate security groups with existing subnets

### ISSUE THREAD

**Issue by akinfemi** [openshift/installer#3228]
# Version

```console
$ openshift-install version
./openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
```

# Platform:
Azure

# What happened?
No console access via a browser.

Installing a cluster to an existing network on Azure (using the install-config for an existing vnet) was successful (oc commands work and all pods are running). 

However, there was no access to the console via the browser. I created another cluster (without an existing vnet) and compared the network configurations and noticed that the security group allowing inbound connections from the internet to the public ip of the load balancer was not associated to the subnet when it was already existing.

# What you expected to happen?
Console access via a browser.

# How to reproduce it (as minimally and precisely as possible)?
* Create a network with 2 subnets (controlPlane and compute)
* Configure the install-config.yaml file to include:
```
    networkResourceGroupName: ${networkResourceGroupName}
    virtualNetwork: ${virtualNetwork}
    controlPlaneSubnet: ${controlPlaneSubnet}
    computeSubnet: ${computeSubnet}
```
in the `platform.azure` section.
```console
$ openshift-install create cluster --dir=<dir_containing_install_config_file> --log-level=debug
```

**Comment by abhinavdahiya** [comment]
It's documented https://docs.openshift.com/container-platform/4.3/installing/installing_azure/installing-azure-vnet.html#installation-about-custom-azure-vnet-nsg-requirements_installing-azure-vnet

that shared VPC requires use setup the network securty group for subnets.
