### ISSUE TITLE
[RFE] Add an option to configure clock synchronization at install time

### ISSUE THREAD

**Issue by e-minguez** [openshift/installer#3258]
# Version
4.X

# Platform:
Any platform that doesn't provide out of the box clock synchronization (RHV, OpenStack, bare metal, but maybe others)

# What happened?
Chronyd can be configured at post installation time via mco or if dhcpd is configured to send clock sources it can be done automatically, but current OpenShift installation doesn't support a proper way to have clocks synchronized at installation time. This can lead to etcd issues, certificates, etc.

# What you expected to happen?
Have a parameter in the install-config.yaml that allows people to configure chronyd at installation time via ignition.

# How to reproduce it (as minimally and precisely as possible)?
Have an environment where clocks are not synchronized and try to install OpenShift.

# Anything else we need to know?

# References
https://github.com/etcd-io/etcd/issues/9768
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp

**Comment by abhinavdahiya** [comment]
So for cloud, there are ways to use the platform itself to provide time sync. And by default the cluster should be using that, and the users should be free to configure or change it as day-2.

so can you expand and make it clear which environment you are referring to?

**Comment by e-minguez** [comment]
> So for cloud, there are ways to use the platform itself to provide time sync. And by default the cluster should be using that, and the users should be free to configure or change it as day-2.
> 
> so can you expand and make it clear which environment you are referring to?

Any non cloud such as RHV, OpenStack and bare metal.

**Comment by abhinavdahiya** [comment]
> > So for cloud, there are ways to use the platform itself to provide time sync. And by default the cluster should be using that, and the users should be free to configure or change it as day-2.
> > so can you expand and make it clear which environment you are referring to?
> 
> Any non cloud such as RHV, OpenStack and bare metal.

but the original RFE has `ANY` platform, so can you modify this to target specify environment?

**Comment by e-minguez** [comment]
> > > So for cloud, there are ways to use the platform itself to provide time sync. And by default the cluster should be using that, and the users should be free to configure or change it as day-2.
> > > so can you expand and make it clear which environment you are referring to?
> > 
> > 
> > Any non cloud such as RHV, OpenStack and bare metal.
> 
> but the original RFE has `ANY` platform, so can you modify this to target specify environment?

Done

**Comment by jan530** [comment]
Is there any plan to implement this soon?
