### ISSUE TITLE
[Question] Is there any plan to add IBM Cloud as a provider for Openshift ?

### ISSUE THREAD

**Issue by jamesregis** [openshift/installer#3275]
The openshift-installer can install OCP 4 on many different Clouds, like AWS, Azure, GCP , libvirt (in developer mode ... ) etc, here I want to know what is the plan to enable the installer to support IBM Cloud as a provider.

Terraform modules for IBM Cloud exist, ansible modules exist too.

I have seen this issue : https://github.com/openshift/installer/issues/2637 but my question is to have an install procedure to install OCP 4 on IBM Cloud as simple as the install on AWS.

**Comment by abhinavdahiya** [comment]
i think this is issues much better answered in the roadmap. https://github.com/openshift/enhancements/blob/master/ROADMAP.md

so please open this issue on https://github.com/openshift/enhancements

/close

**Comment by jamesregis** [comment]
@abhinavdahiya Are you ok to help me write this enhancement ?

**Comment by goldyfruit** [comment]
Indeed, this would be great to have!
