### ISSUE TITLE
The installer is only looking for clouds.yaml and not also for clouds.yml

### ISSUE THREAD

**Issue by b1zzu** [openshift/installer#3294]
Openstack supports both .yml and .yaml but the openshift-installer is only looking for .yaml, I've spend over one hour trying to understand why openstack could find the clouds file but the openshift-installer couldn't

**Comment by mandre** [comment]
OpenStack only documents `yaml` as a valid file name extention: https://docs.openstack.org/python-openstackclient/latest/configuration/index.html. Using anything different is not supported.

In the installer, we rely on gophercloud to find the configuration file. It tries to load a file named `clouds.yaml` but can be changed with the `OS_CLIENT_CONFIG_FILE` environment variable if yours is different:

https://github.com/gophercloud/utils/blob/e945bbea6306306988e3b97ab33a112c0f9c3f74/openstack/clientconfig/utils.go#L102-L112

/close
