### ISSUE TITLE
Libvirt master fails first boot due to Connection Refused for Ignition URL

### ISSUE THREAD

**Issue by davemulford** [openshift/installer#3300]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-2693-g0a2245077424770572e2cc90050bc3ae8d54c38b
built from commit 0a2245077424770572e2cc90050bc3ae8d54c38b
release image registry.svc.ci.openshift.org/origin/release:4.5
```

# Platform:
libvirt

# What happened?

The bootstrap and master virtual machines are created as expected, but the master repeatedly displays the following in a console.

```console
$ sudo virsh console lab-4jstl-master-0
Connected to domain lab-4jstl-master-0
Escape character is ^]
[***   ] A start job is running for Ignition (fetch) (33min 29s / no limit)[ 2012.613389] ignition[687]: GET https://api-int.lab.mw007.local:22623/config/master: attempt #274
[    **] A start job is running for Ignition (fetch) (33min 34s / no limit)[ 2017.637269] ignition[687]: GET error: Get https://api-int.lab.mw007.local:22623/config/master: dial tcp 192.168.126.11:22623: connect: connection refused
```

# What you expected to happen?

The master should boot successfully and the install process should continue.

# How to reproduce it (as minimally and precisely as possible)?

With an `install-config.yaml` in the current directory:

```console
$ openshift-install create cluster --dir $PWD
```

# Anything else we need to know?

The only change I made to `install-config.yaml` was to rename the bridge interface to `ocp4` as described in [Libvirt Platform Customization doc](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/customization.md).

I ran through the [Libvirt one time setup](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md#one-time-setup), including the [DNS overlay configuration](https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md#set-up-networkmanager-dns-overlay).   Is there anything I might have missed?

Running `dig api-int.lab.mw007.local` returns the address of both the bootstrap and master machines.  The bootstrap has nothing listening on port 22623, so I'm assuming this should be running on the master?

# References

My install-config.yaml: https://gist.github.com/davemulford/b3e7c24075747839d5df86f26398426d

**Comment by davemulford** [comment]
This appears to be a different issue than I originally reported.  The bootstrap machine's machine-config-operator isn't up because `registry.svc.ci.openshift.org/origin/release:4.5` doesn't seem to be a valid image.

I tried changing the installer to look for `origin/release:4.4` instead, but other problems occurred with the master ignition file, that I'll assume has to do with me changing the version.

I'll close this issue and wait for `release:4.5` to be available in CI.

**Comment by juliobarreto** [comment]
Boa tarde colegas, conseguiram resolver essa questão, estou passando pelo menos problema, so que estou na versão 4.6


[root@p50 installer]# bin/openshift-install --dir $INSTALL_DIR create cluster
INFO Obtaining RHCOS image file from 'https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.6/46.82.202008260918-0/x86_64/rhcos-46.82.202008260918-0-qemu.x86_64.qcow2.gz?sha256=c7c8ce8116e16a3cb4b9c197320470fc0e287bd69cc6a7186872ec203dc6096a' 
INFO The file was found in cache: /root/.cache/openshift-installer/image_cache/a4a1cdd5835e20adabf84755c58f94e4. Reusing... 
INFO Consuming Master Machines from target directory 
INFO Consuming OpenShift Install (Manifests) from target directory 
INFO Consuming Common Manifests from target directory 
INFO Consuming Worker Machines from target directory 
INFO Consuming Openshift Manifests from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s for the Kubernetes API at https://api.ocp.example.net:6443...
