### ISSUE TITLE
Cannot compile installer with libvirt tags on CentOS 8

### ISSUE THREAD

**Issue by yrobla** [openshift/installer#3305]
When trying to compile latest version of installer under CentOS 8 for libvirt, i am getting the following error:

[root@vip installer]# go build -mod=vendor -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-2702-g4703d61cb9d38996e2b790f5d32500d33f7dbdcb -X github.com/openshift/installer/pkg/version.Commit=4703d61cb9d38996e2b790f5d32500d33f7dbdcb -s -w' -tags 'libvirt baremetal release' -o bin/openshift-install ./cmd/openshift-install
# github.com/openshift/installer/cmd/openshift-install
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-837010001/000017.o: En la función `virDomainSetIOThreadParamsWrapper':
/root/go/src/github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go/domain_wrapper.go:1927: referencia a `virDomainSetIOThreadParams' sin definir
collect2: error: ld devolvió el estado de salida 1

This seems to be related with the libvirt-devel version needed. While RHEL8 has 5.6 version, CentOS 8 is still under 4.5 and don't seem to have those bindings. There are no external CentOS repos that can bring a newer version too. So we are currently unable to compile the installer.

**Comment by ralvares** [comment]
Hi,

There is a new repository available for rhel8/centos8 for advanced virtualization. 

Enabling Advanced Virtualization Repository

dnf module disable virt -y

In case of Centos 8

cat > /etc/yum.repos.d/CentOS-Virt.repo << EOF
[Advanced_Virt]
name=CentOS-$releasever - Advanced Virt 
baseurl=http://mirror.centos.org/centos/\$releasever/virt/x86_64/advanced-virtualization/
gpgcheck=0
enabled=1
EOF

In case of RHEL8

subscription-manager repos --enable advanced-virt-for-rhel-8-x86_64-rpms

yum groupinstall "Virtualization Host" -y
yum install virt-install libguestfs-tools swtpm swtpm-tools -y
systemctl enable libvirtd-tcp.socket

Note: swtpm is for virtualTPM, just in case of testing encryption at rest.


Please find all the steps for centos8 on the follow link

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/master/docs/ipi.md

**Comment by cfergeau** [comment]
`virDomainSetIOThreadParams` was added in libvirt 4.10.0, and the installer uses libvirt-go 5.10.0, so you need at least these libvirt versions for a successful build. Using this "advanced virtualization" repository should give you a new enough version
