### ISSUE TITLE
libvirt cluster installation fails - Error: unknown flag: --cluster-etcd-operator-image

### ISSUE THREAD

**Issue by cwawak** [openshift/installer#3341]
# Version
built from git, b895e7a303451671e30cea5aa57e32f1ccb003aa
bin/openshift-install unreleased-master-2739-gb895e7a303451671e30cea5aa57e32f1ccb003aa-dirty
built from commit b895e7a303451671e30cea5aa57e32f1ccb003aa
OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="quay.io/openshift-release-dev/ocp-release:4.3.8-x86_64"

# Platform:
libvirt
libvirt-5.6.0-5.fc31.x86_64 

# What happened?
I'm trying to install an OpenShift 4.3 cluster using the OpenShift Installer's dev libvirt cluster functionality. After following the directions, I can confirm that the master and bootstrap nodes are created, and networking/dns work, but the cluster never makes it up. Digging into the bootstrap node shows that some environment variables might not be declared in machine-config-operator

# What you expected to happen?
Cluster successfully installed

# How to reproduce it (as minimally and precisely as possible)?
After building the installer as per https://github.com/openshift/installer/tree/master/docs/dev/libvirt, I used "openshift-install create install-config" to create an install-config.yaml with the same DNS settings as I configured in the above tutorial, as well as my valid pull secret from cloud.redhat.com. Then, at the end of that file I add an sshKey section so I can SSH in easily.

Then, I created a clean, new directory for the cluster installation, and changed into it.

I had to set the right OpenShift image:
$ export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/openshift-release-dev/ocp-release:4.3.8-x86_64

Finally, I kick off the following command:

$ ../src/installer/bin/openshift-install --log-level debug create cluster

DEBUG The connection to the server api-int.openshift.cluster.invalid:6443 was refused - did you specify the right host or port?
DEBUG Gather remote logs
DEBUG Collecting info from openshift-tjlbz-master-0.openshift.cluster.invalid                                                                                    DEBUG lost connection
DEBUG ssh: connect to host openshift-tjlbz-master-0.openshift.cluster.invalid port 22: Connection refused                                      DEBUG Log bundle written to /var/home/core/log-bundle-20200324140431.tar.gz
INFO Bootstrap gather logs captured here "log-bundle-20200324140431.tar.gz"
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded

Basically what I see are a bunch of containers starting, dying, and getting removed really quickly. 
The only error message I could get out of it was from one of the ETCD containers (image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:af715ec65056480c8d7ff06acfef77839ef83d7b56b97bb1633389f7b5365585) running :
Error: unknown flag: --cluster-etcd-operator-image
Usage:
  machine-config bootstrap [flags]

When I dig into the container itself, at the end of the command I do see that cluster-etcd-operator-image env variable isn't being declared:
$ sudo podman inspect 54ae56eb33a5
[
    {
        "Id": "54ae56eb33a5f7ece7b86b077026336bfd700b649526d77aa8a65c29998b7e82",
        "Created": "2020-03-24T17:49:16.752889513Z",
        "Path": "/usr/bin/machine-config-operator",
        "Args": [
            "bootstrap",
            "--etcd-ca=/assets/tls/etcd-ca-bundle.crt",
            "--etcd-metric-ca=/assets/tls/etcd-metric-ca-bundle.crt",
            "--root-ca=/assets/tls/root-ca.crt",
            "--kube-ca=/assets/tls/kube-apiserver-complete-client-ca-bundle.crt",
            "--config-file=/assets/manifests/cluster-config.yaml",
            "--dest-dir=/assets/mco-bootstrap",
            "--pull-secret=/assets/manifests/openshift-config-secret-pull-secret.yaml",
            "--etcd-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e9a7267ad2a1146abdfd69eff5a9ccb5cb1c4b06ad92404b97fa34ecebd31a05",
            "--kube-client-agent-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:11427cf0bf365873a6614e68814f5c083cc5936453010350d754cff024c4d2f4",
            "--machine-config-operator-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:af715ec65056480c8d7ff06acfef77839ef83d7b56b97bb1633389f7b5365585",
            "--machine-config-oscontent-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d38088f408f216541faa2fe003c4d659c29828dedb1f6f5a7df540d967af859c",
            "--infra-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ee50534c2f97c6c9a6baeacf120cf7b4f13a8a59f6b673b152006ad7fb8702d6",
            "--keepalived-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d7109d8f53a9db0cdc56a18716a0c5363338af3f1146d93044825555558bbc9e",
            "--coredns-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1a743def9de2c5ef8b01355b3dca52f64990e691283a8b07f833369203f272ae",
            "--mdns-publisher-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2c5e36a7b628735301c8f8942239522ede628e61c26c7bd706aca1b1b18cee32",
            "--haproxy-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08ba9cb4f45c557b2ec8cea6528bb60b1efcd3a7588046a71f5babe19e5fc9c0",
            "--baremetal-runtimecfg-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c21b0b480483bb5f42aeec39a8c6a802d1c940bb15561ee84f9df3317fb24c37",
            "--cloud-config-file=/assets/manifests/cloud-provider-config.yaml",
            "--cluster-etcd-operator-image="
        ],

# Anything else we need to know?

Happy to share any logs needed, but let me know specifics so I can sanitize as needed.

**Comment by abhinavdahiya** [comment]
> OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="quay.io/openshift-release-dev/ocp-release:4.3.8-x86_64"
> built from git, b895e7a
bin/openshift-install unreleased-master-2739-gb895e7a303451671e30cea5aa57e32f1ccb003aa-dirty

there is a mismatch of the installer binary and the release you are using.

if you trying to use 4.3 release image, build installer from release-4.3

/close

**Comment by abhinavdahiya** [comment]
Ah, didn't mean to close this Oops

**Comment by cwawak** [comment]
Let me try this now! :) Thank you.

**Comment by cwawak** [comment]
This solved my problem! Others came up, hopefully I can solve them myself! Thank you again.
