### ISSUE TITLE
vpshere platform not in list

### ISSUE THREAD

**Issue by jvijay-work** [openshift/installer#3347]
# Version

```console
$ openshift-install version
built from commit f7a2f7cf9ec3201bb8c9ebb677c05d21c72e3cc5
release image quay.io/openshift-release-dev/ocp-release@sha256:a414f6308db72f88e9d2e95018f0cc4db71c6b12b2ec0f44587488f0a16efc42

```

# Platform:

# What happened?
./openshift-install create manifests
? SSH Public Key <none>
? Platform  [Use arrows to move, enter to select, type to filter, ? for more help]
> aws
  azure
  gcp
  openstack

# What you expected to happen?
No support for vpshere esxi?
./openshift-install create manifests
? SSH Public Key <none>
? Platform  [Use arrows to move, enter to select, type to filter, ? for more help]
> aws
  azure
  gcp
  openstack
 vpshere <-------

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
we only support vpshere as an user-provisioned workflow of installation, and platform in this workflow are only driven using install-config.yaml.
https://docs.openshift.com/container-platform/4.3/installing/installing_vsphere/installing-vsphere.html

/close
