### ISSUE TITLE
Customize Terraform To Create OCP4.3 Cluster On vSphere 6.7

### ISSUE THREAD

**Issue by efrieza** [openshift/installer#3354]
# Version
Terraform version: v0.11.14

```console
$ openshift-install version
openshift-install v4.3.1
```

# Platform:
vSPhere 6.7

# What happened?
Sorry I am new to Github and I have more of a question than I need help with than reporting a bug.
I followed the instructions from this Github page (https://github.com/openshift/installer/blob/master/docs/user/vsphere/install_upi.md) and managed to deploy a OCP4.3 cluster on my vSphere 6.7 environment just fine with 3 master nodes and 3 worker nodes using Terraform.  Everything came up and in working order after several attempts.  I would like to know how I can change the name of the nodes from "control-plane-0" and "compute-0" to something else like master0, and worker0.  I also want to build 3 infrastructure nodes like in OCP3.11 but I do not know how to add the extra node category to the Terraform configuration files.  The reason why I want to do this is so I can restrict my router and logging pods to the infrastructure nodes and leave the worker nodes to serve standard deployments.  I understand that I can designate 3 worker nodes as infrastructure nodes but I would also like to name them appropriately both in vSphere and in DNS.  Any help with this is much appreciated.

Thanks

**Comment by gojeaqui** [comment]
Hello, you can use my repo:
https://github.com/gojeaqui/installer/tree/master/upi/vsphere

I have made several modifications so the installer is more usable on a real world environment.

You can customize: hostname, CPU count, Memory and IP addresses.

There is also a helper script to configure a DHCP server for initial IP addresses for the VMs.

The documentation has not been updated with the latest changes, but now the script does not create a folder nor a Resource Group (they have to exist previously which is the most common case in clients)

I am also documenting the minimal permissions needed to create the cluster.

**Comment by efrieza** [comment]
Thank you gojeaqui for sharing your repo.  I got terraform to deploy the VMs with the names that I like but unfortunately now the cluster won't form.  the bootstrap seemed to have worked but I can't get the API to come up.  I remote onto the bootstrap server and I see some errors I haven't seen before.

Here are some of the errors I saw (I edited out my actual server names):
Mar 29 01:24:55 bootstrapserver.mydomain.com bootkube.sh[2236]: https://etcd-2.mydomain.com:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 29 01:24:55 bootstrapserver.mydomain.com bootkube.sh[2236]: https://etcd-0.mydomain.com:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 29 01:24:55 bootstrapserver.mydomain.com bootkube.sh[2236]: https://etcd-1.mydomain.com:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 29 01:24:55 bootstrapserver.mydomain.com bootkube.sh[2236]: Error: unhealthy cluster
Mar 29 01:24:55 bootstrapserver.mydomain.com podman[1088]: 2020-03-29 01:24:55.768395992 +0000 UTC m=+5.377888848 container died 5291d4878bb840f5d7e29982ef3657634dfab9270ad90356f27d0e3d984b0dd4 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fe763130ac96d53e108baaf9f7765477983e3ee42ad8c2274450acb84bc60353, name=etcdctl)
Mar 29 01:24:55 bootstrapserver.mydomain.com podman[1088]: 2020-03-29 01:24:55.809673515 +0000 UTC m=+5.419166399 container remove 5291d4878bb840f5d7e29982ef3657634dfab9270ad90356f27d0e3d984b0dd4 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fe763130ac96d53e108baaf9f7765477983e3ee42ad8c2274450acb84bc60353, name=etcdctl)
Mar 29 01:24:55 bootstrapserver.mydomain.com bootkube.sh[2236]: etcdctl failed. Retrying in 5 seconds...
Mar 29 01:25:00 bootstrapserver.mydomain.com podman[1175]: 2020-03-29 01:25:00.919933912 +0000 UTC m=+0.081945594 container create 11fb72aa2ec40578f2e35a0ce4601a3289b89eaca48e0be8218253f691cfa3f0 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fe763130ac96d53e108baaf9f7765477983e3ee42ad8c2274450acb84bc60353, name=etcdctl)
Mar 29 01:25:01 bootstrapserver.mydomain.com podman[1175]: 2020-03-29 01:25:01.211728714 +0000 UTC m=+0.373740276 container init 11fb72aa2ec40578f2e35a0ce4601a3289b89eaca48e0be8218253f691cfa3f0 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fe763130ac96d53e108baaf9f7765477983e3ee42ad8c2274450acb84bc60353, name=etcdctl)
Mar 29 01:25:01 bootstrapserver.mydomain.com podman[1175]: 2020-03-29 01:25:01.224125174 +0000 UTC m=+0.386136741 container start 11fb72aa2ec40578f2e35a0ce4601a3289b89eaca48e0be8218253f691cfa3f0 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fe763130ac96d53e108baaf9f7765477983e3ee42ad8c2274450acb84bc60353, name=etcdctl)
Mar 29 01:25:01 bootstrapserver.mydomain.com podman[1175]: 2020-03-29 01:25:01.224324031 +0000 UTC m=+0.386335608 container attach 11fb72aa2ec40578f2e35a0ce4601a3289b89eaca48e0be8218253f691cfa3f0 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fe763130ac96d53e108baaf9f7765477983e3ee42ad8c2274450acb84bc60353, name=etcdctl)
Mar 29 01:25:06 bootstrapserver.mydomain.com bootkube.sh[2236]: {"level":"warn","ts":"2020-03-29T01:25:06.233Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-2bd7e6aa-1173-4c01-b51f-2fbcef91e6c9/etcd-1.mydomain.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.21:2379: connect: connection refused\""}
Mar 29 01:25:06 bootstrapserver.mydomain.com bootkube.sh[2236]: {"level":"warn","ts":"2020-03-29T01:25:06.233Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-1e7977c6-2691-41fb-bacd-6ab3c4660a41/etcd-0.mydomain.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.20:2379: connect: connection refused\""}
Mar 29 01:25:06 bootstrapserver.mydomain.com bootkube.sh[2236]: {"level":"warn","ts":"2020-03-29T01:25:06.233Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-2ad129e7-02eb-4a26-a6cf-711f06cb1867/etcd-2.mydomain.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.22:2379: connect: connection refused\""}
 

------------------------------------------------------------------------------

Back on the Bastian node (the server I deploy the scripts from) I run the command: openshift-install --dir=. wait-for bootstrap-complete --log-level debug
I just get the infinite loop of DEBUG still waiting for the Kubernetes API messages.

Have you experience something like this before?  I'm searching for a solution but if you know how to fix these errors please share.  :-)

Also I believe your DHCP helper script is full of comments in Portuguese or Spanish which I do not understand.  I deployed my own DHCP server but I thought the Terraform script was going to statically assign the IPs but that didn't seem to be the case.  Anyway I don't think DHCP is my problem at the moment.

**Comment by gojeaqui** [comment]
Hello, sorry for the Spanish comments I need to translate them yet.

You need DHCP for the initial IP assignment.

What the terraform script does is base64 encode an ignition config with an ifcfg-ens192 file.

So the nodes get a static IP config only after getting and IP from a DHCP server, that's why I made the config-gen.py script.

About your errors: you need to check DNS, and load balancer.
(by the way, the config-gen.py script checks the DNS entries for you...)

**Comment by efrieza** [comment]
Hi gojeaqui

Thank you for the suggestion.  It was a DNS issue as you suggested and I was able to bring the cluster up and running.  Sorry I didn't response sooner. 

Thanks again for your help
