### ISSUE TITLE
failed to create machineconfigs.v1.machineconfiguration.openshift.io/99-master-ssh

### ISSUE THREAD

**Issue by Capr1sna** [openshift/installer#3375]
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-2459-gfc790034704d5e279eabacd833d3e90c76815978-dirty
built from commit fc790034704d5e279eabacd833d3e90c76815978
release image registry.svc.ci.openshift.org/origin/release:4.4
```
self built installer based on "fcos" branch (patched: removing the AWS credential checks).

# Platform:

# What happened?

**Installation did not finish:**
-bash-4.2$ ./openshift-install wait-for bootstrap-complete --dir=openshift-config --log-level=info
INFO Waiting up to 20m0s for the Kubernetes API at https://api.openshift.xxx:6443...
INFO API v1.17.1 up
INFO Waiting up to 40m0s for bootstrapping to complete...
E0330 08:42:55.422903    3215 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get https://api.openshift.xxx:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=6438&timeoutSeconds=330&watch=true: dial tcp 10.223.231.21:6443: connect: connection refused
ERROR Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::RouteStatus_FailedHost::RouterCerts_NoRouterCertSecret: RouterCertsDegraded: secret/v4-0-config-system-router-certs -n openshift-authentication: could not be retrieved: secret "v4-0-config-system-router-certs" not found
IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server
RouteStatusDegraded: route is not available at canonical host oauth-openshift.apps.openshift.xxx: []
INFO Cluster operator authentication Progressing is Unknown with NoData:
INFO Cluster operator authentication Available is Unknown with NoData:
INFO Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available
INFO Cluster operator machine-config Available is False with : Cluster not available for 4.4.0-0.okd-2020-03-28-092308
INFO Cluster operator machine-config Progressing is True with : Cluster is bootstrapping 4.4.0-0.okd-2020-03-28-092308
ERROR Cluster operator machine-config Degraded is True with RequiredPoolsFailed: Failed to resync 4.4.0-0.okd-2020-03-28-092308 because: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: configuration status for pool master is empty: pool is degraded because nodes fail with "3 nodes are reporting degraded status on sync": "Node ip-10-223-231-25.eu-central-1.compute.internal is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-7bac6a16c868a2907711515c8bdef1b3\\\" not found\", Node ip-10-223-231-58.eu-central-1.compute.internal is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-7bac6a16c868a2907711515c8bdef1b3\\\" not found\", Node ip-10-223-231-52.eu-central-1.compute.internal is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-7bac6a16c868a2907711515c8bdef1b3\\\" not found\"", retrying
INFO Cluster operator openshift-controller-manager Progressing is True with :
INFO Cluster operator openshift-controller-manager Available is False with :
INFO Use the following commands to gather logs from the cluster
INFO openshift-install gather bootstrap --help
FATAL failed to wait for bootstrapping to complete: timed out waiting for the condition

**Bootstrap node logs following**
journalctl -b -f -u bootkube.service
Mar 30 09:02:22 ip-10-223-231-86 bootkube.sh[712]: [#2847] failed to create some manifests:
Mar 30 09:02:22 ip-10-223-231-86 bootkube.sh[712]: "99_openshift-machineconfig_99-master-ssh.yaml": failed to create machineconfigs.v1.machineconfiguration.openshift.io/99-master-ssh -n : MachineConfig.machineconfiguration.openshift.io "99-master-ssh" is invalid: spec.config.ignition.config.replace.source: Invalid value: "null": spec.config.ignition.config.replace.source in body must be of type string: "null"
Mar 30 09:02:22 ip-10-223-231-86 bootkube.sh[712]: "99_openshift-machineconfig_99-worker-ssh.yaml": failed to create machineconfigs.v1.machineconfiguration.openshift.io/99-worker-ssh -n : MachineConfig.machineconfiguration.openshift.io "99-worker-ssh" is invalid: spec.config.ignition.config.replace.source: Invalid value: "null": spec.config.ignition.config.replace.source in body must be of type string: "null"
Mar 30 09:02:22 ip-10-223-231-86 bootkube.sh[712]: Failed to create "99_openshift-machineconfig_99-master-ssh.yaml" machineconfigs.v1.machineconfiguration.openshift.io/99-master-ssh -n : MachineConfig.machineconfiguration.openshift.io "99-master-ssh" is invalid: spec.config.ignition.config.replace.source: Invalid value: "null": spec.config.ignition.config.replace.source in body must be of type string: "null"

**kubernetes status:**
-bash-4.2$ ./oc get pods --all-namespaces
NAMESPACE                                               NAME                                                                      READY   STATUS      RESTARTS   AGE
openshift-apiserver-operator                            openshift-apiserver-operator-658fdcfbcb-fbsvq                             1/1     Running     1          39m
openshift-apiserver                                     apiserver-7bbb8f899c-8rp4g                                                1/1     Running     0          26m
openshift-apiserver                                     apiserver-7bbb8f899c-nlzkp                                                1/1     Running     0          27m
openshift-apiserver                                     apiserver-7bbb8f899c-pq4zm                                                1/1     Running     0          26m
openshift-authentication-operator                       authentication-operator-7c684bd887-jl27z                                  1/1     Running     1          39m
openshift-cloud-credential-operator                     cloud-credential-operator-7cf77fc5cd-dtcss                                1/1     Running     0          39m
openshift-cluster-machine-approver                      machine-approver-5577db88b6-bcx4m                                         2/2     Running     0          39m
openshift-cluster-node-tuning-operator                  cluster-node-tuning-operator-5f46858dcd-rtl8h                             1/1     Running     0          39m
openshift-cluster-node-tuning-operator                  tuned-47hbz                                                               1/1     Running     0          31m
openshift-cluster-node-tuning-operator                  tuned-k8gbt                                                               1/1     Running     0          31m
openshift-cluster-node-tuning-operator                  tuned-kdh82                                                               1/1     Running     0          31m
openshift-cluster-storage-operator                      csi-snapshot-controller-operator-68766cc444-8nbtz                         0/1     Pending     0          39m
openshift-cluster-version                               cluster-version-operator-5cb6989445-45l5j                                 1/1     Running     0          40m
openshift-controller-manager-operator                   openshift-controller-manager-operator-7b8f5bbdf6-nrbw4                    1/1     Running     1          39m
openshift-dns-operator                                  dns-operator-7ccc7949b5-d49sl                                             2/2     Running     0          39m
openshift-dns                                           dns-default-5kvcj                                                         2/2     Running     0          29m
openshift-dns                                           dns-default-752qj                                                         2/2     Running     0          29m
openshift-dns                                           dns-default-zb6q5                                                         2/2     Running     0          30m
openshift-etcd-operator                                 etcd-operator-5778674f87-rgbc7                                            1/1     Running     1          39m
openshift-etcd                                          etcd-ip-10-223-231-25.eu-central-1.compute.internal                       3/3     Running     0          29m
openshift-etcd                                          etcd-ip-10-223-231-52.eu-central-1.compute.internal                       3/3     Running     0          27m
openshift-etcd                                          etcd-ip-10-223-231-58.eu-central-1.compute.internal                       3/3     Running     0          28m
openshift-etcd                                          installer-2-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          30m
openshift-etcd                                          installer-2-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          27m
openshift-etcd                                          installer-2-ip-10-223-231-58.eu-central-1.compute.internal                0/1     Completed   0          28m
openshift-etcd                                          revision-pruner-2-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-etcd                                          revision-pruner-2-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-etcd                                          revision-pruner-2-ip-10-223-231-58.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-kube-apiserver-operator                       kube-apiserver-operator-65cff77fb8-z7wkp                                  1/1     Running     1          39m
openshift-kube-apiserver                                installer-2-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          30m
openshift-kube-apiserver                                installer-3-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          28m
openshift-kube-apiserver                                installer-4-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          24m
openshift-kube-apiserver                                installer-4-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          26m
openshift-kube-apiserver                                installer-4-ip-10-223-231-58.eu-central-1.compute.internal                0/1     Completed   0          27m
openshift-kube-apiserver                                kube-apiserver-ip-10-223-231-25.eu-central-1.compute.internal             4/4     Running     0          24m
openshift-kube-apiserver                                kube-apiserver-ip-10-223-231-52.eu-central-1.compute.internal             4/4     Running     0          26m
openshift-kube-apiserver                                kube-apiserver-ip-10-223-231-58.eu-central-1.compute.internal             4/4     Running     0          27m
openshift-kube-apiserver                                revision-pruner-2-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          28m
openshift-kube-apiserver                                revision-pruner-3-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-kube-apiserver                                revision-pruner-4-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          22m
openshift-kube-apiserver                                revision-pruner-4-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          24m
openshift-kube-apiserver                                revision-pruner-4-ip-10-223-231-58.eu-central-1.compute.internal          0/1     Completed   0          26m
openshift-kube-controller-manager-operator              kube-controller-manager-operator-77dfc876c6-7nrsn                         1/1     Running     1          39m
openshift-kube-controller-manager                       installer-2-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          30m
openshift-kube-controller-manager                       installer-4-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          27m
openshift-kube-controller-manager                       installer-4-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          27m
openshift-kube-controller-manager                       installer-4-ip-10-223-231-58.eu-central-1.compute.internal                0/1     Completed   0          28m
openshift-kube-controller-manager                       installer-5-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          23m
openshift-kube-controller-manager                       installer-5-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          20m
openshift-kube-controller-manager                       installer-5-ip-10-223-231-58.eu-central-1.compute.internal                0/1     Completed   0          22m
openshift-kube-controller-manager                       kube-controller-manager-ip-10-223-231-25.eu-central-1.compute.internal    4/4     Running     0          22m
openshift-kube-controller-manager                       kube-controller-manager-ip-10-223-231-52.eu-central-1.compute.internal    4/4     Running     0          20m
openshift-kube-controller-manager                       kube-controller-manager-ip-10-223-231-58.eu-central-1.compute.internal    4/4     Running     0          21m
openshift-kube-controller-manager                       revision-pruner-2-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          28m
openshift-kube-controller-manager                       revision-pruner-4-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          26m
openshift-kube-controller-manager                       revision-pruner-4-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-kube-controller-manager                       revision-pruner-4-ip-10-223-231-58.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-kube-controller-manager                       revision-pruner-5-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          22m
openshift-kube-controller-manager                       revision-pruner-5-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          19m
openshift-kube-controller-manager                       revision-pruner-5-ip-10-223-231-58.eu-central-1.compute.internal          0/1     Completed   0          21m
openshift-kube-scheduler-operator                       openshift-kube-scheduler-operator-5b7c7f9998-rhk88                        1/1     Running     1          39m
openshift-kube-scheduler                                installer-2-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          30m
openshift-kube-scheduler                                installer-4-ip-10-223-231-25.eu-central-1.compute.internal                0/1     Completed   0          28m
openshift-kube-scheduler                                installer-4-ip-10-223-231-52.eu-central-1.compute.internal                0/1     Completed   0          25m
openshift-kube-scheduler                                installer-4-ip-10-223-231-58.eu-central-1.compute.internal                0/1     Completed   0          27m
openshift-kube-scheduler                                openshift-kube-scheduler-ip-10-223-231-25.eu-central-1.compute.internal   2/2     Running     0          28m
openshift-kube-scheduler                                openshift-kube-scheduler-ip-10-223-231-52.eu-central-1.compute.internal   2/2     Running     0          25m
openshift-kube-scheduler                                openshift-kube-scheduler-ip-10-223-231-58.eu-central-1.compute.internal   2/2     Running     0          26m
openshift-kube-scheduler                                revision-pruner-2-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          28m
openshift-kube-scheduler                                revision-pruner-4-ip-10-223-231-25.eu-central-1.compute.internal          0/1     Completed   0          27m
openshift-kube-scheduler                                revision-pruner-4-ip-10-223-231-52.eu-central-1.compute.internal          0/1     Completed   0          24m
openshift-kube-scheduler                                revision-pruner-4-ip-10-223-231-58.eu-central-1.compute.internal          0/1     Completed   0          26m
openshift-kube-storage-version-migrator-operator        kube-storage-version-migrator-operator-db8476558-98s2j                    1/1     Running     1          39m
openshift-kube-storage-version-migrator                 migrator-7fcc869c69-dqflk                                                 0/1     Pending     0          31m
openshift-machine-api                                   machine-api-controllers-67b7986dcb-22qs9                                  4/4     Running     0          30m
openshift-machine-api                                   machine-api-operator-558fff69-zwtrh                                       2/2     Running     0          39m
openshift-machine-config-operator                       machine-config-controller-65dcccb867-2htx9                                1/1     Running     0          31m
openshift-machine-config-operator                       machine-config-daemon-ntzld                                               2/2     Running     0          31m
openshift-machine-config-operator                       machine-config-daemon-srx7z                                               2/2     Running     0          29m
openshift-machine-config-operator                       machine-config-daemon-v4kc8                                               2/2     Running     0          29m
openshift-machine-config-operator                       machine-config-operator-db5985b4f-cf5lj                                   1/1     Running     0          39m
openshift-machine-config-operator                       machine-config-server-662xk                                               1/1     Running     0          30m
openshift-machine-config-operator                       machine-config-server-m4nz8                                               1/1     Running     0          29m
openshift-machine-config-operator                       machine-config-server-zlbf6                                               1/1     Running     0          29m
openshift-multus                                        multus-admission-controller-fxqbg                                         1/1     Running     0          31m
openshift-multus                                        multus-admission-controller-j48wg                                         1/1     Running     0          29m
openshift-multus                                        multus-admission-controller-wclx5                                         1/1     Running     0          29m
openshift-multus                                        multus-q674d                                                              1/1     Running     0          32m
openshift-multus                                        multus-qrqtc                                                              1/1     Running     0          32m
openshift-multus                                        multus-xd2jq                                                              1/1     Running     0          32m
openshift-network-operator                              network-operator-74c79867cb-hdttq                                         1/1     Running     0          39m
openshift-operator-lifecycle-manager                    catalog-operator-6677c7cbb9-w6t4j                                         1/1     Running     0          39m
openshift-operator-lifecycle-manager                    olm-operator-69cdc8848d-b47xf                                             1/1     Running     0          39m
openshift-operator-lifecycle-manager                    packageserver-6c4474d8d9-dzfg8                                            1/1     Running     0          30m
openshift-operator-lifecycle-manager                    packageserver-6c4474d8d9-qp464                                            1/1     Running     0          30m
openshift-sdn                                           ovs-9t8dm                                                                 1/1     Running     0          32m
openshift-sdn                                           ovs-jfszn                                                                 1/1     Running     0          32m
openshift-sdn                                           ovs-p666q                                                                 1/1     Running     0          32m
openshift-sdn                                           sdn-46j2l                                                                 1/1     Running     0          32m
openshift-sdn                                           sdn-9j9vl                                                                 1/1     Running     0          32m
openshift-sdn                                           sdn-controller-2mrsl                                                      1/1     Running     0          32m
openshift-sdn                                           sdn-controller-tczwd                                                      1/1     Running     0          32m
openshift-sdn                                           sdn-controller-wqhvh                                                      1/1     Running     0          32m
openshift-sdn                                           sdn-ptxzj                                                                 1/1     Running     0          32m
openshift-service-ca-operator                           service-ca-operator-5dd48ddc9f-qkj8t                                      1/1     Running     1          39m
openshift-service-ca                                    service-ca-d97dbbcf7-rvt8s                                                1/1     Running     0          31m
openshift-service-catalog-apiserver-operator            openshift-service-catalog-apiserver-operator-8cd5797d8-rm8nz              1/1     Running     1          39m
openshift-service-catalog-controller-manager-operator   openshift-service-catalog-controller-manager-operator-7ddf7q4dw           1/1     Running     1          39m

# What you expected to happen?

Installation of OKD 4.4. succeeded in a restricted AWS environment

# How to reproduce it (as minimally and precisely as possible)?

**Installation configuration**
export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=registry.svc.ci.openshift.org/origin/release@sha256:79f2415cc7b702866c0ccb974d5dabc7b85d0eacb5537680c846df7ad6e06352

adaption of install-config before creation of manifests
 _Set the compute replicas to "0" (see installation guide "Empty Computing pool")_ 
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
_Adapt Network type to (as written here:https://github.com/openshift/okd/issues/59):_
  networkType: OpenShiftSDN

**Cloudformation scripts customisations done:**
Cluster-Bootstrap + Cluter-Master_nodes cloudformation scripts from the docu was patched to use ignition version 3.0. ("version":"3.0.0"). 
Additionally Cluster-Master-Nodes cloud formation scripts where patched to use "merge" instead of "append" (https://github.com/coreos/ignition/blob/master/doc/configuration-v3_0.md):
 "config":{"merge"

After bootstrap node was started and all infrastructure containers were deployed, etcd pods keeps failing. (failures in bootkube.service + kubelet.service)
Solution was to restart crio service: 
`sudo systemctl restart crio`
Afterwards, the ports were opened and the master ignition file could be read from the master-nodes

Next, master-nodes cloud formation scripts were deployed.

Then waiting until installation finished:

# Anything else we need to know?

I tried to overwrite machineconfig_99-master-ssh.yaml before creating the ignition-configs (./openshift-install create ignition-configs --dir openshift-config)
_replace ignition->config->replace->source: null with “”
        replace:
          source: ""_
```
vi openshift-config/openshift/99_openshift-machineconfig_99-master-ssh.yaml
vi openshift-config/openshift/99_openshift-machineconfig_99-worker-ssh.yaml
```

But with that, the Master-Nodes were not able anymore to read ignition config during startup (empty config found).

**Comment by Capr1sna** [comment]
just saw, the machine-config-server containers gives a lot of handshake errors

`I0330 08:28:35.525003       1 bootstrap.go:37] Version: machine-config-daemon-4.3.0-201910280117-203-g7c976803-dirty (7c9768037fa9d47243ec81bad5b0d52d036cbe50)
I0330 08:28:35.527054       1 api.go:51] Launching server on :22623
I0330 08:28:35.531388       1 api.go:51] Launching server on :22624
2020/03/30 08:28:35 http: TLS handshake error from 10.223.231.21:57068: EOF
2020/03/30 08:28:35 http: TLS handshake error from 10.223.231.21:47249: EOF
2020/03/30 08:28:36 http: TLS handshake error from 10.223.231.21:27557: EOF
2020/03/30 08:28:36 http: TLS handshake error from 10.223.231.21:22458: EOF
2020/03/30 08:28:36 http: TLS handshake error from 10.223.231.21:51203: EOF
2020/03/30 08:28:37 http: TLS handshake error from 10.223.231.21:14437: EOF
2020/03/30 08:28:38 http: TLS handshake error from 10.223.231.21:6951: EOF
2020/03/30 08:28:38 http: TLS handshake error from 10.223.231.21:27236: EOF
2020/03/30 08:28:39 http: TLS handshake error from 10.223.231.21:56774: EOF
2020/03/30 08:28:39 http: TLS handshake error from 10.223.231.21:43310: EOF
2020/03/30 08:28:39 http: TLS handshake error from 10.223.231.21:50590: EOF
2020/03/30 08:28:39 http: TLS handshake error from 10.223.231.21:36008: EOF
2020/03/30 08:28:40 http: TLS handshake error from 10.223.231.21:24733: EOF
2020/03/30 08:28:40 http: TLS handshake error from 10.223.231.21:34026: EOF
2020/03/30 08:28:40 http: TLS handshake error from 10.223.231.21:37408: EOF
2020/03/30 08:28:42 http: TLS handshake error from 10.223.231.21:22612: EOF
2020/03/30 08:28:43 http: TLS handshake error from 10.223.231.21:59439: EOF
2020/03/30 08:28:43 http: TLS handshake error from 10.223.231.21:34424: EOF
2020/03/30 08:28:43 http: TLS handshake error from 10.223.231.21:25661: EOF
2020/03/30 08:28:46 http: TLS handshake error from 10.223.231.21:10684: EOF
2020/03/30 08:28:46 http: TLS handshake error from 10.223.231.21:6007: EOF
2020/03/30 08:28:46 http: TLS handshake error from 10.223.231.21:60396: EOF
2020/03/30 08:28:47 http: TLS handshake error from 10.223.231.21:57741: EOF
2020/03/30 08:28:47 http: TLS handshake error from 10.223.231.21:57281: EOF
2020/03/30 08:28:47 http: TLS handshake error from 10.223.231.21:31082: EOF
2020/03/30 08:28:48 http: TLS handshake error from 10.223.231.21:6767: EOF
2020/03/30 08:28:49 http: TLS handshake error from 10.223.231.21:23927: EOF
2020/03/30 08:28:50 http: TLS handshake error from 10.223.231.21:2279: EOF
2020/03/30 08:28:50 http: TLS handshake error from 10.223.231.21:27548: EOF
2020/03/30 08:28:50 http: TLS handshake error from 10.223.231.21:52873: EOF
2020/03/30 08:28:50 http: TLS handshake error from 10.223.231.21:59918: EOF
2020/03/30 08:28:52 http: TLS handshake error from 10.223.231.21:42275: EOF
2020/03/30 08:28:53 http: TLS handshake error from 10.223.231.21:28101: EOF
2020/03/30 08:28:53 http: TLS handshake error from 10.223.231.21:24351: EOF
2020/03/30 08:28:54 http: TLS handshake error from 10.223.231.21:30838: EOF
2020/03/30 08:28:56 http: TLS handshake error from 10.223.231.21:50678: EOF
2020/03/30 08:28:56 http: TLS handshake error from 10.223.231.21:55675: EOF
2020/03/30 08:28:57 http: TLS handshake error from 10.223.231.21:48359: EOF
2020/03/30 08:28:57 http: TLS handshake error from 10.223.231.21:56862: EOF
2020/03/30 08:28:57 http: TLS handshake error from 10.223.231.21:38218: EOF
2020/03/30 08:28:57 http: TLS handshake error from 10.223.231.21:51720: EOF
2020/03/30 08:28:58 http: TLS handshake error from 10.223.231.21:59778: EOF
2020/03/30 08:28:59 http: TLS handshake error from 10.223.231.21:20288: EOF`

**Comment by vrutkovs** [comment]
Please file a ticket in https://github.com/openshift/okd instead and attach the archive produced by `oc adm must-gather` there

/close
