### ISSUE TITLE
DEBUG Still waiting for the Kubernetes API: Get https://api.cluster1.yh.lab:6443/version?timeout=32s: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by yunghanlu** [openshift/installer#3383]
# Version
$ openshift-install version
./openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d

# Platform:
Bare metal

I'm trying to create a OpenShift cluster, I created the following nodes with rhcos-4.3.0-x86_64-installer.iso:
1 bootstrap
3 master
2 worker
When I run the command below, I stuck on still waiting for the Kubernetes API
[root@utility openshift-install]# /openshift-install/openshift-source/openshift-install --dir=/openshift-install wait-for bootstrap-complete --log-level=debug

Otherwise, I checked the bootstrap node using podman and found that only Etcd-signer is running. The etcdctl sometimes running and sometimes gone. I checked the bootstrap node using "journalctl -b -f -u bootkube.service" the following log showed repeatedly.
Mar 31 06:08:17 bootstrap.cluster1.yh.lab podman[19296]: 2020-03-31 06:08:17.870947587 +0000 UTC m=+5.376243813 container died 21f61313ee1c20a5aaab2a881716cfd609e4f9e6c3d5e2f694e49ee926b8d987 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:18 bootstrap.cluster1.yh.lab podman[19296]: 2020-03-31 06:08:18.330711799 +0000 UTC m=+5.836008045 container remove 21f61313ee1c20a5aaab2a881716cfd609e4f9e6c3d5e2f694e49ee926b8d987 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:18 bootstrap.cluster1.yh.lab bootkube.sh[2802]: etcdctl failed. Retrying in 5 seconds...
Mar 31 06:08:23 bootstrap.cluster1.yh.lab podman[19400]: 2020-03-31 06:08:23.410010192 +0000 UTC m=+0.062195758 container create 1047ddb7bc343e9f77f87e69bbb6f6537a11f7eb6ca5a0d9ae717ced7868b3d2 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:23 bootstrap.cluster1.yh.lab podman[19400]: 2020-03-31 06:08:23.643013895 +0000 UTC m=+0.295199444 container init 1047ddb7bc343e9f77f87e69bbb6f6537a11f7eb6ca5a0d9ae717ced7868b3d2 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:23 bootstrap.cluster1.yh.lab podman[19400]: 2020-03-31 06:08:23.652192789 +0000 UTC m=+0.304378345 container start 1047ddb7bc343e9f77f87e69bbb6f6537a11f7eb6ca5a0d9ae717ced7868b3d2 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:23 bootstrap.cluster1.yh.lab podman[19400]: 2020-03-31 06:08:23.652248305 +0000 UTC m=+0.304433907 container attach 1047ddb7bc343e9f77f87e69bbb6f6537a11f7eb6ca5a0d9ae717ced7868b3d2 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: {"level":"warn","ts":"2020-03-31T06:08:28.656Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-ce10db29-d4cb-4d37-b51f-5b3779932cae/etcd-0.cluster1.yh.lab:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.40.5.118:2379: connect: connection refused\""}
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: {"level":"warn","ts":"2020-03-31T06:08:28.656Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-94b67f98-284c-4c92-8e83-1ce03c392c1b/etcd-2.cluster1.yh.lab:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.40.5.122:2379: connect: connection refused\""}
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: {"level":"warn","ts":"2020-03-31T06:08:28.656Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-be9a4660-c4a6-41e3-9748-4c7aff50435e/etcd-1.cluster1.yh.lab:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.40.5.121:2379: connect: connection refused\""}
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: https://etcd-0.cluster1.yh.lab:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: https://etcd-2.cluster1.yh.lab:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: https://etcd-1.cluster1.yh.lab:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: Error: unhealthy cluster
Mar 31 06:08:28 bootstrap.cluster1.yh.lab podman[19400]: 2020-03-31 06:08:28.678989823 +0000 UTC m=+5.331175409 container died 1047ddb7bc343e9f77f87e69bbb6f6537a11f7eb6ca5a0d9ae717ced7868b3d2 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:28 bootstrap.cluster1.yh.lab podman[19400]: 2020-03-31 06:08:28.726504292 +0000 UTC m=+5.378689856 container remove 1047ddb7bc343e9f77f87e69bbb6f6537a11f7eb6ca5a0d9ae717ced7868b3d2 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c6de86b5f3140fa33a69477c286afc901b4ecd6e73e82d0ccfc8a0e0fe5e648, name=etcdctl)
Mar 31 06:08:28 bootstrap.cluster1.yh.lab bootkube.sh[2802]: etcdctl failed. Retrying in 5 seconds...

My DNS Config as below:
@   IN  SOA     utility.cluster1.yh.lab. root.cluster1.yh.lab. (
                                                2020032501    ;Serial
                                                3H      ;Refresh
                                                15M     ;Retry
                                                1W      ;Expire
                                                1D      ;Minimum TTL
                                                )

;Name Server Information
@      IN  NS      utility.cluster1.yh.lab.

;IP address of Name Server
utility                         IN  A           10.40.5.116

;A - Record HostName To IP Address
api                             IN  A           10.40.5.116
api-int                         IN  A           10.40.5.116
master-0                        IN  A           10.40.5.118
master-1                        IN  A           10.40.5.121
master-2                        IN  A           10.40.5.122
etcd-0                          IN  A           10.40.5.118
etcd-1                          IN  A           10.40.5.121
etcd-2                          IN  A           10.40.5.122
worker-1                        IN  A           10.40.5.123
worker-2                        IN  A           10.40.5.124
bootstrap                       IN  A           10.40.5.117
vcenter                         IN  A           10.40.5.201

*.apps                          IN  A           10.40.5.116

;SRV - etcd SRV Record
_etcd-server-ssl._tcp.cluster1.yh.lab   86400   IN  SRV 0 10 2380 etcd-0.cluster1.yh.lab.
_etcd-server-ssl._tcp.cluster1.yh.lab   86400   IN  SRV 0 10 2380 etcd-1.cluster1.yh.lab.
_etcd-server-ssl._tcp.cluster1.yh.lab   86400   IN  SRV 0 10 2380 etcd-2.cluster1.yh.lab.

My HAProxy config as below:
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

frontend kubernetes_api
    mode tcp 
    option tcplog
    bind *:6443
    default_backend kubernetes_api

backend kubernetes_api
    mode tcp
    balance source
    server bootstrap bootstrap.cluster1.yh.lab:6443 check
    server master-0 master-0.cluster1.yh.lab:6443 check
    server master-1 master-1.cluster1.yh.lab:6443 check
    server master-2 master-2.cluster1.yh.lab:6443 check

frontend machine_config
    mode tcp
    option tcplog
    bind *:22623
    default_backend machine_config

backend machine_config
    mode tcp
    balance source
    server bootstrap bootstrap.cluster1.yh.lab:22623 check
    server master-0 master-0.cluster1.yh.lab:22623 check
    server master-1 master-1.cluster1.yh.lab:22623 check
    server master-2 master-2.cluster1.yh.lab:22623 check

frontend router_https
    mode tcp
    option tcplog
    bind *:443
    default_backend router_https

backend router_https
    mode tcp
    option ssl-hello-chk
    server worker-1 worker-1.cluster1.yh.lab:443 check
    server worker-2 worker-2.cluster1.yh.lab:443 check

frontend router_http
    mode tcp
    option tcplog
    bind *:80
    default_backend router_http

backend router_http
    mode tcp
    server worker-1 worker-1.cluster1.yh.lab:80 check
    server worker-2 worker-2.cluster1.yh.lab:80 check

Does anyone knows what happen with my environment? Please help me!!!
The log bundle is also attached.
[log-bundle-20200331114718.tar.gz](https://github.com/openshift/installer/files/4407080/log-bundle-20200331114718.tar.gz)

**Comment by Vidita2506** [comment]
Do you have a fix for this ? I am facing the same issue

**Comment by yunghanlu** [comment]
> Do you have a fix for this ? I am facing the same issue

You must install OpenShift within 24 hours. Because certificate create in ign files will expire in 24 hours.

**Comment by Vidita2506** [comment]
I did install it in 2 hours. Still facing the same issue. 
Also, the haproxy stats for openshift-api-server and machine-config-server doesn't show master nodes up.
But the services are listening on ports 22623 and 6443.
