### ISSUE TITLE
Openstack: Significance of VIP and request for an alternative approach

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [openshift/installer#3409]
# Version
4.4.0.rc4

# Platform:
Openstack (IPI)

# What happened?

We are trying to deploy an installer provisioned openshift cluster on Openstack. Going through the infrastructure that installer builds for openstack, I can see that installer relies heavily on VIP and keepalived to setup the platform. Is there any special use case for using VIPs ? I would like to know, in depth if possible, about the significance of using VIPs.
From my findings, `VIP` is an outdated network model and is known be be not the best in performance. Shouldn't an alternate approach like the calico network model or a bare metal network model be used instead, if the performance part is true.
Right now, `VIPs` and `VRRP` that `keepalived` uses are acting as a blocker and we can't use IPI because of that. Our infrastructure provider doesn't support them.

# What you expected to happen?

It's more of a request to get to know more about the significance of VIPs. And maybe a feature request to move away from VIPs if possible.

**Comment by mandre** [comment]
Hi @ahmedwaleedmalik, I had trouble understanding what you meant by "the infrastructure doesn't support VRRP". Does it mean that you're using a neutron driver that doesn't know about vrrp and it's preventing you from installing OCP on this platform?

If I'm not mistaken, changing from "protocol=vrrp" to "protocol=112" while creating the security groups [1][2] should do the trick. That's the only place to my knowledge where we're making assumption about vrrp protocol.

[1] https://github.com/openshift/installer/blob/290df6a/data/data/openstack/topology/sg-master.tf#L358
[2] https://github.com/openshift/installer/blob/290df6a46c6414fcd4583e03a866e5d7f79741b7/data/data/openstack/topology/sg-worker.tf#L263

**Comment by mandre** [comment]
This was fixed in master already and should be fixed in 4.4 with https://github.com/openshift/installer/pull/3528
