### ISSUE TITLE
OCP UPI Installation fails on AWS, with error while downloading images from quay.io

### ISSUE THREAD

**Issue by PushpamSaxena** [openshift/installer#3414]
# Version 

```console
$ openshift-install version
./openshift-install v4.3.5
built from commit 82f9a63c06956b3700a69475fbd14521e139aa1e
release image quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a
```

# Platform:
aws (UPI)

# What happened?

Followed the guidelines as mentioned in the documentation at https://github.com/openshift/installer/blob/master/docs/user/aws/install_upi.md and https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-user-infra.html.

At the step - Monitor for bootstrap-complete and Initialization
The installer fails while getting stuck at - "Waiting up to 30m0s for the Kubernetes API"

In logs bootstrap/journals/release-image.log, I can see lots of error messages as - 
Apr 05 11:30:24 ip-10-0-9-4 release-image-download.sh[2377]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error getting username and password: illegal base64 data at input byte 48

# What you expected to happen?
The installer should make the Kubernetes API server up and running.

# How to reproduce it (as minimally and precisely as possible)?
Follow the steps mentioned in https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-user-infra.html

# Anything else we need to know?

I used the secret from https://cloud.redhat.com/openshift/install/aws/user-provisioned

**Comment by abhinavdahiya** [comment]
> In logs bootstrap/journals/release-image.log, I can see lots of error messages as -
Apr 05 11:30:24 ip-10-0-9-4 release-image-download.sh[2377]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error getting username and password: illegal base64 data at input byte 48

I think the error is pretty self explanatory.. `error getting username and password: illegal base64 data at input byte 48` , The pull secret you have provided is invalid... Fixing the pull-secret should fix your problem.

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/issues/3414#issuecomment-609999903
ping @PushpamSaxena

**Comment by PushpamSaxena** [comment]
Hi @abhinavdahiya 
I tried again from scratch and it worked this time.
Thanks for your inputs. Hence closing.
