### ISSUE TITLE
[ Feature Request ] Store TF State Files in Bucket

### ISSUE THREAD

**Issue by ldelossa** [openshift/installer#3417]
Hello there,

I am utilizing openshift-installer to host instances of Clair for demos and other purposes.  I am curious if the thought of having this tool store it's TF state files in a bucket created by TF itself was an approach worth exploring. If so, I will gladly start a branch for this work, wanted to open it up for discussion first.

**Comment by abhinavdahiya** [comment]
The installer uses terraform as an internal implemtations to _easily create infrastructure resource_ and that's about it. We don't use it for anything other than that. 

the tfstate file is therefore of no use after installation, an example of this is that openshift-install destroy cluster doesn't even use the tfstate.

So storing the tfstate to any persistent place is not useful at all for a users imo.

**Comment by ldelossa** [comment]
Makes sense to me. Was under the impression destruction required the TF state files to be around.
