### ISSUE TITLE
[Documentation] Build steps in README reflect unnecessary steps

### ISSUE THREAD

**Issue by angelofdeauth** [openshift/installer#3422]
# Version

```console
$ openshift-install version
```
refs/heads/master @ b5bbde619a07c05a4582015a8ea4940f828e2467
Tue Apr  7 14:39:58 UTC 2020

# Platform:

UPI

# What happened?

Build steps in README suggest cloning the repository to `$GOPATH/src/github.com/openshift/installer`. 
This is unnecessary as of `Go 1.13` due to go modules.

# What you expected to happen?

Builld steps in README suggest cloning the repository to an arbitrary path of the user's choice.

**Comment by abhinavdahiya** [comment]
fixed by https://github.com/openshift/installer/pull/3423
/close
