### ISSUE TITLE
Volumes attached to worker nodes are not getting encrypted even after mentioning the kms key arn for the kms field in install-config.yaml  file

### ISSUE THREAD

**Issue by tejasrao97** [openshift/installer#3456]
# Version

```console
$ openshift-install version
 openshift-install 4.3.9
built from commit 64fccd954517812eab166d38c7fc5bf71b219b7e
release image quay.io/openshift-release-dev/ocp-release@sha256:f0fada3c8216dc17affdd3375ff845b838ef9f3d67787d3d42a88dcd0f328eea

```

# Platform:

# What happened?

Volumes attached to worker nodes are not getting encrypted even after mentioning the kms key arn for the kms field in install-config.yaml  file

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Volumes attached to nodes had to be encrypted

# How to reproduce it (as minimally and precisely as possible)?

 openshift-install create install-config --dir=<path to create install-config.yaml> --log-level=info

apiVersion: v1
baseDomain: ##########
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - ap-south-1a
      - ap-south-1b
      type: m5.xlarge
      rootVolume:
        iops: 4000
        size: 100
        type: io1
        kmsKeyARN: arn:aws:kms:ap-south-1:****************************
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - ap-south-1a
      - ap-south-1b
      type: m5.xlarge
      rootVolume:
        iops: 4000
        size: 100
        type: io1
        kmsKeyARN: arn:aws:kms:ap-south-1:************************
  replicas: 3
metadata:
  creationTimestamp: null
  name: voymir
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ap-south-1

![image](https://user-images.githubusercontent.com/55922259/79343955-c22a1000-7f4c-11ea-8d4a-06e6ee80542f.png)

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Only supported started 4.4.0

**Comment by abhinavdahiya** [comment]
> Only supported started 4.4.0

/close

**Comment by tejasrao97** [comment]
> > Only supported started 4.4.0
> 
> /close

oh okay thanks for the info abhinav
