### ISSUE TITLE
Openstack: Alternate for setting registry to an empty directory (pre-install)

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [openshift/installer#3486]
# Version

```console
$ openshift-install version
openshift-install v4.3.5
built from commit 82f9a63c06956b3700a69475fbd14521e139aa1e
release image quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a
```

# Platform:

Openstack IPI, but platform doesn't matter

# What happened?

We are trying to provision an openshift cluster via hive on openstack using IPI. For registry storage backend, we don't want to use swift(the default) and instead would like to initialize it with empty directory. It's more of a feature request or request for an alternative for setting registry storage backend to empty directory. We don't want to manually patch the registry instead i think this could be a part of the `install-config.yaml`. Because if we try to provision via hive we can't really run scripts because that would hinder the end to end automation.
Other option would be store a default `manifest` and apply it manually but that would omit the `httpSecret` part because that's generated at run time.

# What you expected to happen?

An option to set image registry storage option in `install-config.yaml` instead of manually patching it.

**Comment by abhinavdahiya** [comment]
I'm sorry, I think with OpenShift4. you will have to interact with the registry operator to configure the operation as day-2.

As long as any configuration isn't required to successfully install a cluster, it wouldn't be immediately added to the isntall-config.yaml. We want to make sure users are conformable changing their clusters to desire after the _default_ cluster is up.

**Comment by ahmedwaleedmalik** [comment]
As far as my understanding goes, openshift installer will wait for all the `cluster operators` to be available. In this case, since there is not support for `swift` the registry operator will never work and hence the installation will not `succeed` even if everything else is up and running. Swift-less alternative for registry is pretty much needed in this case. And patching still doesn't help with the automation.

**Comment by mandre** [comment]
If you don't have swift available (if the service is not enabled, or if the user doesn't have the permission to use it) then the image-registry will fallback to cinder backend, allowing you to finish the installation and later move the image-registry to another backend of your choice as day-2 operation.

**Comment by mandre** [comment]
I'm closing this issue as it is possible to deploy without swift in the upcoming 4.4 release. There is currently no plans to backport this feature to 4.3.

/close
