### ISSUE TITLE
OpenShift 4 Installer AWS Platform Permissions Check not correct

### ISSUE THREAD

**Issue by srnal** [openshift/installer#3493]
# Version

```console
$ openshift-install version
latest stable openshift-installer
```

# Platform:

# What happened?

The installer does not check AWS-IAM-permissions correctly:
The permissions that are mentioned in the error output are all listed in the permissions policy but not the permissions that are really missed.

This permissions are needed and in the policy:
                "ec2:CreateTags",
                "ec2:DeleteTags",
                "tag:UntagResources",
                "tag:TagResources",
                "iam:CreateUser",
                "iam:DeleteAccessKey",
                "iam:DeleteUser",
                "iam:DeleteUserPolicy",
                "iam:GetUserPolicy",
                "iam:ListAccessKeys",
                "iam:PutUserPolicy",
                "iam:TagUser",
                "s3:PutLifecycleConfiguration",
                "s3:HeadBucket",
                "s3:ListBucketMultipartUploads",
                "s3:AbortMultipartUpload",
                "iam:GetUserPolicy",
                "iam:ListAccessKeys",
                "ec2:AllocateAddress",
                "ec2:AssociateAddress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CopyImage",
                "ec2:CreateNetworkInterface",
                "ec2:CreateSecurityGroup",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteSecurityGroup",
                "ec2:DeleteSnapshot",
                "ec2:DeregisterImage",
                "ec2:DescribeAccountAttributes",
                "ec2:DescribeAddresses",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeImages",
                "ec2:DescribeInstanceAttribute",
                "ec2:DescribeInstanceCreditSpecifications",
                "ec2:DescribeInstances",
                "ec2:DescribeInternetGateways",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeNatGateways",
                "ec2:DescribeNetworkAcls",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribePrefixLists",
                "ec2:DescribeRegions",
                "ec2:DescribeRouteTables",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DescribeVpcAttribute",
                "ec2:DescribeVpcClassicLink",
                "ec2:DescribeVpcClassicLinkDnsSupport",
                "ec2:DescribeVpcEndpoints",
                "ec2:DescribeVpcs",
                "ec2:ModifyInstanceAttribute",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:ReleaseAddress",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:RunInstances",
                "ec2:TerminateInstances",
                "ec2:AssociateDhcpOptions",
                "ec2:AssociateRouteTable",
                "ec2:AttachInternetGateway",
                "ec2:CreateDhcpOptions",
                "ec2:CreateInternetGateway",
                "ec2:CreateNatGateway",
                "ec2:CreateRoute",
                "ec2:CreateRouteTable",
                "ec2:CreateSubnet",
                "ec2:CreateVpc",
                "ec2:CreateVpcEndpoint",
                "ec2:ModifySubnetAttribute",
                "ec2:ModifyVpcAttribute",
                "elasticloadbalancing:AddTags",
                "elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
                "elasticloadbalancing:AttachLoadBalancerToSubnets",
                "elasticloadbalancing:ConfigureHealthCheck",
                "elasticloadbalancing:CreateListener",
                "elasticloadbalancing:CreateLoadBalancer",
                "elasticloadbalancing:CreateLoadBalancerListeners",
                "elasticloadbalancing:CreateTargetGroup",
                "elasticloadbalancing:DeleteLoadBalancer",
                "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                "elasticloadbalancing:DeregisterTargets",
                "elasticloadbalancing:DescribeInstanceHealth",
                "elasticloadbalancing:DescribeListeners",
                "elasticloadbalancing:DescribeLoadBalancerAttributes",
                "elasticloadbalancing:DescribeLoadBalancers",
                "elasticloadbalancing:DescribeTags",
                "elasticloadbalancing:DescribeTargetGroupAttributes",
                "elasticloadbalancing:DescribeTargetHealth",
                "elasticloadbalancing:ModifyLoadBalancerAttributes",
                "elasticloadbalancing:ModifyTargetGroup",
                "elasticloadbalancing:ModifyTargetGroupAttributes",
                "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                "elasticloadbalancing:RegisterTargets",
                "elasticloadbalancing:SetLoadBalancerPoliciesOfListener",
                "iam:AddRoleToInstanceProfile",
                "iam:CreateInstanceProfile",
                "iam:CreateRole",
                "iam:DeleteInstanceProfile",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:GetInstanceProfile",
                "iam:GetRole",
                "iam:GetRolePolicy",
                "iam:GetUser",
                "iam:ListInstanceProfilesForRole",
                "iam:ListRoles",
                "iam:ListUsers",
                "iam:PassRole",
                "iam:CreateAccessKey",
                "iam:PutRolePolicy",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:SimulatePrincipalPolicy",
                "iam:TagRole",
                "route53:ChangeResourceRecordSets",
                "route53:ChangeTagsForResource",
                "route53:CreateHostedZone",
                "route53:DeleteHostedZone",
                "route53:GetChange",
                "route53:GetHostedZone",
                "route53:ListHostedZones",
                "route53:ListHostedZonesByName",
                "route53:ListResourceRecordSets",
                "route53:ListTagsForResource",
                "route53:UpdateHostedZoneComment",
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketCors",
                "s3:GetBucketLocation",
                "s3:GetBucketLogging",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetBucketReplication",
                "s3:GetBucketRequestPayment",
                "s3:GetBucketTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketWebsite",
                "s3:GetEncryptionConfiguration",
                "s3:GetLifecycleConfiguration",
                "s3:GetReplicationConfiguration",
                "s3:ListBucket",
                "s3:PutBucketAcl",
                "s3:PutBucketTagging",
                "s3:PutEncryptionConfiguration",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:GetObjectVersion",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:PutObjectTagging",
                "autoscaling:DescribeAutoScalingGroups",
                "ec2:DeleteNetworkInterface",
                "ec2:DeleteVolume",
                "elasticloadbalancing:DeleteTargetGroup",
                "elasticloadbalancing:DescribeTargetGroups",
                "iam:ListInstanceProfiles",
                "iam:ListRolePolicies",
                "iam:ListUserPolicies",
                "s3:DeleteObject",
                "tag:GetResources",
                "ec2:DeleteDhcpOptions",
                "ec2:DeleteInternetGateway",
                "ec2:DeleteNatGateway",
                "ec2:DeleteRoute",
                "ec2:DeleteRouteTable",
                "ec2:DeleteSubnet",
                "ec2:DeleteVpc",
                "ec2:DeleteVpcEndpoints",
                "ec2:DetachInternetGateway",
                "ec2:DisassociateRouteTable",
                "ec2:ReplaceRouteTableAssociation"

# What you expected to happen?

The correct check of the policy and just the output of the missed permissions in the policy to create a correct policy for the installer.

# References

- #3490

**Comment by abhinavdahiya** [comment]
I don't think i understand what you are trying to say. Can you be a little more descriptive! Thanks!

**Comment by srnal** [comment]
The openshift-installer don't proceed because of this error:
"**FATAL** failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Permissions Check": validate AWS credentials: current credentials insufficient for performing cluster installation".

But the credentials are correct and the needed permissions as listed above are in the policy of the iam-user in aws.
That means the installer don't check the permissions correctly.

**Comment by tshiamo-motsoane** [comment]
Has anyone managed to figure this out. I can install v4.3 perfectly but for some reason I get the same error about permissions for versions above that

**Comment by Razique** [comment]
Do you have an active SCP at the org. level?

**Comment by defanator** [comment]
I'm seeing the same picture with org-level SCP preventing to use any region except eu-central-1.

I'm also seeing a weird issues while deploying a cluster (4.7) under these perms with `credentialsMode: Mint` (ingress operator failing, no wildcard route53 record is being created).

Finally, when I'm trying to destroy a cluster, it ends up with endless loop trying to perform `resourcegroupstaggingapi get-resources` call using us-east-1 endpoint, despite that I had strictly set eu-central-1 in install-config.yaml.

Would appreciate any insights on how this could be mitigated. I suspect that having us-east-1 access for at least `resourcegroupstaggingapi get-resources` API is mandatory, but can't find any proofs (yet).

**Comment by staebler** [comment]
The route53 and iam requests are made to the us-east-1 region. The ingress operator will not be able to create DNS records if access to us-east-1 is blocked. Destroying a cluster requires searching for resources in us-east-1 so that route53 and iam resources can be deleted.

**Comment by defanator** [comment]
@staebler thanks for clarifying this. The interesting fact is that I was able to actually create a cluster in eu-central-1 with completely disabled us-east-1 - except the "*.apps" DNS record - but as you pointed out, this cluster can't be destroyed entirely despite of the fact that eu-central-1 API endpoint was used to create both IAM and **part of** Route53 resources.

Perhaps it would be a good thing to emit a warning / note at the permissions check stage in the installer (e.g. by doing two sets of checks if custom region is specified, and comparing the results).

**Comment by staebler** [comment]
I'm not sure how much we could do here. The permissions checking is best effort and not guaranteed to catch all problems. It relies on simulation provided by the AWS API.

**Comment by defanator** [comment]
@staebler totally understood. Maybe another option would be to add a note about possible Service Control Policy effect somewhere in https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-account.html documentation.

Again, thanks for your attention!
