### ISSUE TITLE
Error refreshing state: state snapshot was created by Terraform v0.12.23, which is newer than current v0.12.0; upgrade to Terraform v0.12.23 or greater to work with this state

### ISSUE THREAD

**Issue by vasukulkarni** [openshift/installer#3525]
# Version: 

```console
$ openshift-install version
built from commit db4411451af55e0bab7258d25bdabd91ea48382f
release image registry.svc.ci.openshift.org/ocp/release@sha256:8e6afc44e94a013dce7a714968c033d2bd7d876edb3c954e52c3936e6574d46b
```

# Platform:

# What happened?
```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: /Users/vasukulkarni/ocs-ci/bin/openshift-install create cluster --dir /Users/vasukulkarni/cluster-path4 --log-level INFO.
E           Error is level=info msg="Consuming Install Config from target directory"
E           level=info msg="Creating infrastructure resources..."
E           level=error msg="Error refreshing state: state snapshot was created by Terraform v0.12.23, which is newer than current v0.12.0; upgrade to Terraform v0.12.23 or greater to work with this state"
E           level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to initialize Terraform"
```

# What you expected to happen?

I already have latest terraform, so not sure why its complaining
$ brew info terraform
terraform: stable 0.12.24 (bottled), HEAD

I have tried 0.12.13 and other versions and hit same issue.

**Comment by abhinavdahiya** [comment]
The installer doesn't use the host terraform, we have our own version embedded into our binary.

Can you provide more details on the how to reproduce this error...

**Comment by abhinavdahiya** [comment]
Also maybe can you attach the .openshift_install.log

**Comment by vasukulkarni** [comment]
@abhinavdahiya here are the openshift logs: https://paste.centos.org/view/raw/d8bc13ab

**Comment by vasukulkarni** [comment]
Additional info:

Mac: 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

I also removed terraform(which was previously installed via brew) and I see the same issue.

**Comment by abhinavdahiya** [comment]
looking at the logs it looks like you are reusing the same directory that was previously used to create a clusters..

can you make sure you are using a separate target directory.. ` --dir <>`
