### ISSUE TITLE
OperatorSources certificate issue, x509: certificate is valid for *, not quay.io

### ISSUE THREAD

**Issue by davis-jacob** [openshift/installer#3536]
# Version
Freshly installed
Client Version: 4.3.13
Server Version: 4.3.13
Kubernetes Version: v1.16.2

# Platform:
vSphere

# What happened?
Freshly installed OCP 4.3
Operator hub shows no items in the UI
Operator source shows below status

NAME                  TYPE          ENDPOINT              REGISTRY              DISPLAYNAME           PUBLISHER   STATUS        MESSAGE                                                                                                                                          AGE
certified-operators   appregistry   https://quay.io/cnr   certified-operators   Certified Operators   Red Hat     Configuring   Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: x509: certificate is valid for *.apps.djqa.twentynet.local, not quay.io   90m
community-operators   appregistry   https://quay.io/cnr   community-operators   Community Operators   Red Hat     Configuring   Get https://quay.io/cnr/api/v1/packages?namespace=community-operators: x509: certificate is valid for *.apps.djqa.twentynet.local, not quay.io   90m
redhat-operators      appregistry   https://quay.io/cnr   redhat-operators      Red Hat Operators     Red Hat     Configuring   Get https://quay.io/cnr/api/v1/packages?namespace=redhat-operators: x509: certificate is valid for *.apps.djqa.twentynet.local, not quay.io      90m

# What you expected to happen?

 Operators listed under Operator hub

Name:         certified-operators
Namespace:    openshift-marketplace
Labels:       opsrc-provider=certified
Annotations:  <none>
API Version:  operators.coreos.com/v1
Kind:         OperatorSource
Metadata:
  Creation Timestamp:  2020-05-03T19:25:25Z
  Finalizers:
    finalizer.operatorsources.operators.coreos.com
  Generation:        7
  Resource Version:  51366
  Self Link:         /apis/operators.coreos.com/v1/namespaces/openshift-marketplace/operatorsources/certified-operators
  UID:               7b9ece47-a3d8-425d-bc60-e7d82822163b
Spec:
  Authorization Token:
  Display Name:        Certified Operators
  Endpoint:            https://quay.io/cnr
  Publisher:           Red Hat
  Registry Namespace:  certified-operators
  Type:                appregistry
Status:
  Current Phase:
    Last Transition Time:  2020-05-03T19:25:24Z
    Last Update Time:      2020-05-03T19:26:09Z
    Phase:
      Message:  Get https://quay.io/cnr/api/v1/packages?namespace=certified-operators: x509: certificate is valid for *.apps.djqa.twentynet.local, not quay.io
      Name:     Configuring
Events:         <none>

Only one operator source pod running.
root@installer ocp-installer]# oc get pods -n openshift-marketplace
NAME                                    READY   STATUS    RESTARTS   AGE
marketplace-operator-6f7cb8fd4d-bcngl   1/1     Running   0          2m52s

**Comment by abhinavdahiya** [comment]
I think you should open bug on OLM, https://github.com/operator-framework/operator-lifecycle-manager

the installer cannot help fix errors with operators.
/close
