### ISSUE TITLE
Release 4.4 branch has 4.3 version

### ISSUE THREAD

**Issue by BenHall** [openshift/installer#3547]
https://github.com/openshift/installer/blob/78b817ceb7657f81176bbe182cc6efc73004c841/pkg/asset/releaseimage/default.go#L23

This indicates that it is using 4.3, but the branch name indicates it should be 4.4

**Comment by abhinavdahiya** [comment]
OCP releases installer binaries to https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
and these binaries have the correct installer, release image tuples.
the source default is only a placeholder so that the release process can override it.

/close
