### ISSUE TITLE
openshift 4.3.13  install failed

### ISSUE THREAD

**Issue by MuraliSrinivasP** [openshift/installer#3564]
# Version

```console
$ openshift-install version

<openshift-install 4.3.13
built from commit db4411451af55e0bab7258d25bdabd91ea48382f
release image quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61>
```

# Platform:

# What happened?
Following is the command 
----->>>>>>     openshift-install --dir=first_install create cluster
------------>>>>>>>>>>>>     Installation failed

Following is the error
INFO Consuming Install Config from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 30m0s for the Kubernetes API at https://api.shift.7hillsinnovations.org:6443... 
INFO API v1.16.2 up                               
INFO Waiting up to 30m0s for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 30m0s for the cluster at https://api.shift.7hillsinnovations.org:6443 to initialize... 
ERROR Cluster operator authentication Degraded is True with RouteStatusDegradedFailedHost: RouteStatusDegraded: route is not available at canonical host oauth-openshift.apps.shift.7hillsinnovations.org: [] 
INFO Cluster operator authentication Progressing is Unknown with NoData:  
INFO Cluster operator authentication Available is Unknown with NoData:  
INFO Cluster operator console Progressing is True with RouteSyncProgressingFailedHost: RouteSyncProgressing: route is not available at canonical host [] 
INFO Cluster operator console Available is Unknown with NoData:  
INFO Cluster operator image-registry Available is False with NoReplicasAvailable: The deployment does not have available replicas 
INFO Cluster operator image-registry Progressing is True with DeploymentNotCompleted: The deployment has not completed 
ERROR Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: default 
INFO Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available.
Moving to release version "4.3.13".
Moving to ingress-controller image version "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9ea98af9b00609e17666738516a0eb750c31318a5b08c78cc0547b63b00e00b6". 
INFO Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available. 
INFO Cluster operator insights Disabled is False with :  
ERROR Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager Route to become ready failed: waiting for RouteReady of alertmanager-main: no status available for alertmanager-main 
INFO Cluster operator monitoring Available is False with :  
INFO Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack. 
FATAL failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, monitoring 

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

To make installation to complete on GCP
[.openshift_install.log](https://github.com/openshift/installer/files/4592593/default.openshift_install.log)

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
`
openshift-install create install-config --dir=first_install

openshift-install --dir=first_install create cluster`

# Anything else we need to know?

Enter text here.

# References

<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #6017
-->

- enter text here.

**Comment by MuraliSrinivasP** [comment]
Platform is GCP

**Comment by abhinavdahiya** [comment]
> INFO Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available.

it looks like the compute machines didn't join the cluster... can you make sure the compute machines were created.

you can collect debugging info using https://docs.openshift.com/container-platform/4.4/support/gathering-cluster-data.html

or here specifically look at the
```
oc get machines -A
```

**Comment by MuraliSrinivasP** [comment]
During installation,I got the following 
Still waiting for the Kubernetes API: the server could not find the requested resource 

![possible_errors](https://user-images.githubusercontent.com/46015257/81396914-ed66e000-9143-11ea-92db-e5eeb6ac36d9.png)

I

**Comment by MuraliSrinivasP** [comment]
I cannot able to access the oc commands
Here is the output

![oc_commnads_not_working](https://user-images.githubusercontent.com/46015257/81397715-7b8f9600-9145-11ea-92f4-3dafe6a91271.png)

**Comment by abhinavdahiya** [comment]
you can use the kubeconfig from the `<INSTALL_DIR>/auth/kubeconfig` to run the `oc` commands

**Comment by MuraliSrinivasP** [comment]
Yes.
Not all machines are in running phase
![machinesrunning](https://user-images.githubusercontent.com/46015257/81472503-13f54b80-9216-11ea-8738-240526d52b61.png)

**Comment by MuraliSrinivasP** [comment]
I created install-config file on GCP I executed the installer with default configuration to create a cluster(3 Masters and 3 worker nodes).
This installation with default configuration on AWS is successful with out giving any error. On AWS
even the cluster with 3 Masters and 2 workers is properly created.
Why installation on GCP is giving error? Any problem with the internal installer code??? or GCP???

**Comment by MuraliSrinivasP** [comment]
Ok Then what is the solution to this problem???.How can i make all the computing machines join the cluster and make installation successful???.

**Comment by abhinavdahiya** [comment]
as you have been successful in talking to the API, now you can run `oc adm must-gather` and attach the log bundle it generates here for debugging?

**Comment by MuraliSrinivasP** [comment]
Here is the must-gather data.
[must-gather.tar.gz](https://github.com/openshift/installer/files/4622462/must-gather.tar.gz)

**Comment by MuraliSrinivasP** [comment]
while gathering the data, the following error is identified
![mustgather_error](https://user-images.githubusercontent.com/46015257/81828327-4d4ff300-9557-11ea-897f-9fb8502e0efb.png)

**Comment by MuraliSrinivasP** [comment]
Installer version is openshift 4.4.3.
