### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS environment var is disregarded

### ISSUE THREAD

**Issue by angelofdeauth** [openshift/installer#3568]
# Version
Compiled from current master branch
```console
$ openshift-install version
<your output here>
```

# Platform:

GCP

# What happened?
Several environment variables for GCP credentials are supported from documentation, but the `GOOGLE_APPLICATION_CREDENTIALS` variable is not. I propose supporting this variable in the same format many other GCP tools do, which is as the name or path to the file.

Currently supported environment variables require the variable to be set to the contents of the file, not the name or path.
Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Can you include the steps to reproduce?
also maybe include the .openshift_install.log from that run. so we can debug.

**Comment by abhinavdahiya** [comment]
> Can you include the steps to reproduce?
> also maybe include the .openshift_install.log from that run. so we can debug.

ping @angelofdeauth

**Comment by angelofdeauth** [comment]
@abhinavdahiya 

This is documented in OpenShift here: https://docs.openshift.com/container-platform/4.3/installing/installing_gcp/installing-gcp-default.html#installation-launching-installer_installing-gcp-default

The OpenShift documentation mentions `GOOGLE_CREDENTIALS`, `GOOGLE_CLOUD_KEYFILE_JSON`, 
and `GCLOUD_KEYFILE_JSON`, all of which (as of my testing on 5/6/2020) must be set to the value of the text representation of the key in order to have effect -- though during my testing I noticed that the installer would still prompt for the keyfile contents and dump it to the `~/.gcp/osServiceAccount.json` file.

Google documents their usage of the `GOOGLE_APPLICATION_CREDENTIALS` for gcloud authentication here: https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable

Several other tools follow this paradigm.
 The installer should too.
