### ISSUE TITLE
Openshift 4.4 installer Openstack failed fetch from glance

### ISSUE THREAD

**Issue by jasonhjia** [openshift/installer#3577]
# Version

```console
$ openshift-install version
built from commit 4cb9ca89c59cbc7e5b4caf3863e098057b496a15
release image registry.svc.ci.openshift.org/origin/release@sha256:354e6e7b150738cafe52e64d5064db65d9a5809415196b121be9f9f682be4b51

```

# Platform:

openstack

# What happened?
Installer wait for Kubernetes API be ready until exhaust all retries, and then failed with following message:
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.<cluster>.<base_domain>:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 192.168.2.230:6443: connect: no route to host 

Also noticed in bootstrap node log, the following error show up:
Starting [0;1;39mIgnition (fetch)[0m...
[   10.120067] ignition[511]: Ignition 2.2.1
[   10.133843] ignition[511]: Stage: fetch
[   10.142188] ignition[511]: reading system config file "/usr/lib/ignition/base.ign"
[   10.157852] ignition[511]: no config URL provided
[   10.169044] ignition[511]: reading system config file "/usr/lib/ignition/user.ign"
[   10.188196] ignition[511]: no config at "/usr/lib/ignition/user.ign"
[   10.201129] ignition[511]: GET http://169.254.169.254/openstack/latest/user_data: attempt #1
[   11.133441] ignition[511]: GET result: OK
[   11.142600] ignition[511]: warning at $.ignition.config.merge.0.httpHeaders, line 1 col 34: Unused key httpHeaders
[   11.160597] ignition[511]: GET http://192.168.2.136:9292//v2/images/a16c1759-8022-4fc4-85e1-55fc4070aaaf/file: attempt #1
[   11.183521] ignition[511]: GET result: Unauthorized
[   11.193844] ignition[511]: failed to fetch config: failed to fetch resource
[   11.207949] ignition[511]: failed to acquire config: failed to fetch resource
[[   11.223997] systemd[1]: ignition-fetch.service: Main process exited, code=exited, status=1/FAILURE
[   11.238955] ignition[511]: Ignition failed: failed to fetch resource
[0;1;31mFAILED[   11.250157] systemd[1]: ignition-fetch.service: Failed with result 'exit-code'.
[0m[   11.263931] systemd[1]: Failed to start Ignition (fetch).
] Failed to start [0;1;39mIgnition (fetch)[0m.

# What you expected to happen?

Install should be completed without error.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create install-config
$ openshift-install create cluster
```

# Anything else we need to know?

In openstack console, 3 master nodes up and running, 1 bootstrap node is running but not functional due to this error. No other nodes are created.

# References

- enter text here.

**Comment by jasonhjia** [comment]
[ 11.142600] ignition[511]: warning at $.ignition.config.merge.0.httpHeaders, line 1 col 34: Unused key httpHeaders

this could be the root cause, which probably cause the http request send to glance missing x-auth-token header, thus cause the unauthorized error

**Comment by jasonhjia** [comment]
According to:
https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md#bootstrap-ignition

By default Glance service doesn't allow anonymous access to the data. So, if you use Glance to store the ignition config, then you also need to provide a valid auth token in the ignition.config.append.httpHeaders field.

However, noticed that during cluster creation, it creates a file "terraform.openstack.auto.tfvars.json" with following content:

"openstack_bootstrap_shim_ignition": "{\"ignition\":{\"config\":{\"merge\":[{\"httpHeaders\":[{\"name\":\"X-Auth-Token\",\"value\":\"gAAAAABet24wW6t6zGlSkVYtRSVQod5AM1mUgtbvZEKYwpXsNOUdipiK28EJR3I8VeenVkC7DHa0I-Jh8yChTduI0pKQmsuwItQaHFneaYTckRjz9woEamcJl1CaBtB8IaXgTn5eMpF-1MMZqwISa4VCQzV2CYMRwKogIY6BKbTW0O7TP6HiKEo\"}],\"source\":\"http://192.168.2.136:9292//v2/images/bbb1c51a-5844-4458-8a9e-3676ad77a20c/file\"}]},\"version\":\"3.1.0-experimental\"},\"storage\":{\"files\":[{\"overwrite\":true,\"path\":\"/etc/hostname\",\"contents\":{\"source\":\"data:text/plain;base64,b2tkLXA1ajZtLWJvb3RzdHJhcA==\"},\"mode\":420},{\"overwrite\":true,\"path\":\"/opt/openshift/tls/cloud-ca-cert.pem\",\"contents\":{\"source\":\"data:text/plain;charset=utf-8;base64,\"},\"mode\":420}]}}"

So think here "merge" need be changed to "append"

**Comment by abhinavdahiya** [comment]
Can you include the reproduction steps please.
Your previous comment links to UPI docs, but then you link terraform json file that is created for ipi workflow.

Clarifying the steps you took or the document you followed will help triage this better.

**Comment by Fedosin** [comment]
To start with, this is not OpenShift 4.4, this is OKD master (based on 4.5 at this moment) -> the issue description may lead to confusion.

In the latest FCOS version they started using new Ignition spec 3.1, that supports `httpHeaders` and therefore storing ignitions in Glance.
When @vrutkovs updated the image (https://github.com/openshift/installer/pull/3572), you began to see the error.
This happens because  the installer still uses the outdated 3.1-experimental spec, despite the fact the FCOS image was updated : https://github.com/openshift/installer/blob/fcos/pkg/tfvars/openstack/bootstrap_ignition.go#L14

We need to start using 3.1 asap to fix it.

**Comment by vrutkovs** [comment]
Dupe of https://github.com/openshift/okd/issues/122
/close

**Comment by LorbusChris** [comment]
Ignition v2.3.0 with stable spec 3.1 was released last Thursday and will likely make its way into the next Fedora CoreOS release images.

We'll also need to update the import at: https://github.com/openshift/installer/blob/fcos/pkg/tfvars/openstack/bootstrap_ignition.go#L14
