### ISSUE TITLE
Bare Metal Platform Customization document mentions wrong field

### ISSUE THREAD

**Issue by mzamot** [openshift/installer#3582]
# Version

```console
$ openshift-install version
```
N/A
# Platform:
Baremetal

# What happened?
In the [Bare Metal Platform Customization document](https://github.com/openshift/installer/blob/master/docs/user/metal/customization_ipi.md) the value `clusterProvisioningIP` is mentioned to modify the IP within the cluster where the provisioning services run. However, this field is not the correct one, instead `provisioningHostIP` should be used.
By using `clusterProvisioningIP` in the install-config.yaml file, no IP is changed, but by using `provisioningHostIP` the right behavior is achieved.

# What you expected to happen?
The right field should be mentioned in the table.

# How to reproduce it (as minimally and precisely as possible)?
N/A

**Comment by hardys** [comment]
This should be fixed when we land https://github.com/openshift/installer/pull/4053 but I guess the docs should be modified to reflect the correct name on older release branches

**Comment by stbenjam** [comment]
This was fixed in https://github.com/openshift/installer/pull/4053

/close
