### ISSUE TITLE
Documentation and ouput are not consistent in Openstack IPI

### ISSUE THREAD

**Issue by gyohuangxin** [openshift/installer#3585]
# Version

```console
$ openshift-install version
./openshift-install 4.4.3
built from commit 78b817ceb7657f81176bbe182cc6efc73004c841
release image quay.io/openshift-release-dev/ocp-release@sha256:039a4ef7c128a049ccf916a1d68ce93e8f5494b44d5a75df60c85e9e7191dacc
```

# Platform:

Openstack IPI

# What happened?
In installer output message, it shows "waiting up to 20m0s". But in [openstack ipi doc](https://github.com/openshift/installer/blob/master/docs/user/openstack/README.md#without-floating-ips), it shows 30 minutes
```
time="2020-05-11T05:19:07-04:00" level=info msg="Waiting up to 20m0s for the Kubernetes API at https://api.openstack.huangxin:6443..."
```

# What you expected to happen?

I think they should be changed to the same

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by pierreprinetti** [comment]
Thank you @gyohuangxin!
