### ISSUE TITLE
IAM roles attached to master nodes have IAM full access permissions in the policy 

### ISSUE THREAD

**Issue by tejasrao97** [openshift/installer#3593]
# Version

```console
$ openshift-install version
openshift-install 4.4.3
built from commit 78b817ceb7657f81176bbe182cc6efc73004c841
release image quay.io/openshift-release-dev/ocp-release@sha256:039a4ef7c128a049ccf916a1d68ce93e8f5494b44d5a75df60c85e9e7191dacc

```

# Platform:

# What happened?
IAM roles attached to master have IAM full access permissions defined in the policy, is there any way that we can add only the required permissions before bootstrapping the cluster, as this leads to policy violations

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Only required permissions must be added to the policy 

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/pull/3451 should fix your issues. Try using nightly 4.5

/close
