### ISSUE TITLE
Error refreshing state: state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.0; upgrade to Terraform v0.12.24 or greater to work with this state

### ISSUE THREAD

**Issue by amoonakal** [openshift/installer#3596]
# Version

```console
$ openshift-install version
4.4.3
built from commit 78b817ceb7657f81176bbe182cc6efc73004c841
release image quay.io/openshift-release-dev/ocp-release@sha256:039a4ef7c128a049ccf916a1d68ce93e8f5494b44d5a75df60c85e9e7191dacc

```

# Platform: aws UPI

# What happened?

Used terraform to generate the aws infrastructure based on the code present in https://github.com/ibm-cloud-architecture/terraform-openshift4-aws . 
1) Terraform apply creates the required manifest and ignition files within a temp directory.
2) Terraform apply creates an openshit-installer, kubectl and oc files as well 

Below is how the folder structure looks like

-rw-rw-r--. 1 ec2-user ec2-user     14869 May 12 12:24 installer.tf
-rwxr-xr-x. 2 ec2-user ec2-user  75916904 Apr 26 19:59 kubectl
-rwxr-xr-x. 2 ec2-user ec2-user  75916904 Apr 26 19:59 oc
-rwxr-xr-x. 1 ec2-user ec2-user 354664448 Apr 26 20:07 openshift-install
-rw-rw-r--. 1 ec2-user ec2-user       500 May 12 12:24 output.tf
-rw-rw-r--. 1 ec2-user ec2-user        84 May 12 12:24 ssh_key.tf
drwxrwxr-x. 6 ec2-user ec2-user       182 May 13 15:16 temp
-rw-rw-r--. 1 ec2-user ec2-user      2594 May 12 12:24 variables.tf

3) /temp is where the ignition and manifest get generated as seen below:

drwxr-x---. 2 ec2-user ec2-user     50 May 13 12:17 auth
drwxr-x---. 2 ec2-user ec2-user   4096 May 13 12:17 _manifests
-rw-r-----. 1 ec2-user ec2-user    247 May 13 14:37 metadata.json
drwxr-x---. 2 ec2-user ec2-user   4096 May 13 12:28 _openshift
-rw-r-----. 1 ec2-user ec2-user 309673 May 13 14:37 terraform.tfvars.json
drwxr-x---. 2 ec2-user ec2-user     62 May 13 13:57 tls

4) Apply creates the bootsrap instance and master instance

5) Running below command from the root of my folder which contains the tfstate file using command
/home/ec2-user/terraform-openshift4-aws/install/openshift-install create cluster --dir=/home/ec2-user/terraform-openshift4-aws/install/temp/ --log-level info

results is below error
"Error refreshing state: state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.0; upgrade to Terraform v0.12.24 or greater to work with this state"

$ terraform version
Terraform v0.12.24
+ provider.aws v2.61.0
+ provider.ignition v1.2.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.1.1

$ terraform state pull | grep terraform_version
  "terraform_version": "0.12.24"

Had done a destroy once or twice to recreate the infra, did observe that the temp folder was wiped out. 

Root terraform main file and modules looks like this after running the apply.

[ec2-user@ip-172-31-94-83 terraform-openshift4-aws]$ ll
total 1284
drwxrwxr-x. 2 ec2-user ec2-user      58 May 13 10:57 bootstrap
-rw-rw-r--. 1 ec2-user ec2-user    2100 May 12 12:24 config.tf
drwxrwxr-x. 2 ec2-user ec2-user      41 May 12 12:24 iam
drwxrwxr-x. 2 ec2-user ec2-user     278 May 12 12:24 img
drwxrwxr-x. 3 ec2-user ec2-user     173 May 13 12:17 install
-rw-r-----. 1 ec2-user ec2-user      23 May 13 12:17 kubeadmin-password
-rw-r-----. 1 ec2-user ec2-user    8939 May 13 12:17 kubeconfig
-rw-rw-r--. 1 ec2-user ec2-user   11357 May 12 12:24 LICENSE
-rw-rw-r--. 1 ec2-user ec2-user    4380 May 12 12:24 main.tf
drwxrwxr-x. 2 ec2-user ec2-user      59 May 13 10:54 master
-rw-rw-r--. 1 ec2-user ec2-user    2824 May 12 12:31 openshift_pull_secret.json
-rw-rw-r--. 1 ec2-user ec2-user     197 May 12 12:24 OWNERS
-rw-rw-r--. 1 ec2-user ec2-user   12444 May 12 12:24 README.md
-rw-rw-r--. 1 ec2-user ec2-user   10585 May 12 12:24 README.orig.md
drwxrwxr-x. 2 ec2-user ec2-user      58 May 12 12:24 route53
-rw-rw-r--. 1 ec2-user ec2-user 1228303 May 13 12:24 terraform.tfstate
-rw-rw-r--. 1 ec2-user ec2-user     544 May 12 12:34 terraform.tfvars
-rw-rw-r--. 1 ec2-user ec2-user    3395 May 12 12:29 variables-aws.tf
drwxrwxr-x. 2 ec2-user ec2-user     223 May 12 12:24 vpc

# What you expected to happen?

Cluster should get created and worker nodes should get provisioned.

**Comment by abhinavdahiya** [comment]
> Used terraform to generate the aws infrastructure based on the code present in https://github.com/ibm-cloud-architecture/terraform-openshift4-aws .

shouldn't this bug to that repo then??

also in the similar boat: https://github.com/openshift/installer/issues/3525

**Comment by amoonakal** [comment]
Thanks Abhinav, have raised the issue on a different repo.
