### ISSUE TITLE
Hard Coded Configuration Caused UPI Failed on Azure China

### ISSUE THREAD

**Issue by nichochen** [openshift/installer#3598]
# Version
4.4

# Platform:
Azure UPI on Azure China

# What happened?
Installation failed on Azure China. A key cloud provider configuration is hard codded in following file as 'AzurePublicCloud'.
https://github.com/openshift/installer/blob/d3332b3b54dfcdebb674a7c5cdc36c9646da663c/pkg/asset/manifests/azure/cloudproviderconfig.go

# What you expected to happen?
Installation finish successfully on Azure China.

# How to reproduce it (as minimally and precisely as possible)?
Install OpenShift 4.4 with UPI on Azure China.

# Anything else we need to know?
Following code should be configurable during installation.
`Cloud:                       "AzurePublicCloud",`

# References
Cloud provider docs for Azure.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/dfa2ab5068ab3c319dff342343d4cea0a0ce874d/docs/cloud-provider-config.md

**Comment by abhinavdahiya** [comment]
we don't support any other cloud yet. only AzurePublicCloud. Feel free to comment on https://github.com/openshift/enhancements/pull/321

So personally we should close this issue in favor of getting the enhancement that is in progress.

**Comment by abhinavdahiya** [comment]
and as for UPI manual workaround, you can easily modify the manifests.
```
$ openshift-install create manifests
## edit the cloud provider configmap in manifests
$ openshift-install create ignition-configs
```

**Comment by pichuang** [comment]
@adambkaplan does it mean it is possible to use bare metal UPI to install OCP on Azure China?

**Comment by adambkaplan** [comment]
@pichuang think you meant to mention @abhinavdahiya

**Comment by abhinavdahiya** [comment]
> we don't support any other cloud yet. only AzurePublicCloud. Feel free to comment on [openshift/enhancements#321](https://github.com/openshift/enhancements/pull/321)
> 
> So personally we should close this issue in favor of getting the enhancement that is in progress.

closing in favor of the enhancement [openshift/enhancements#321](https://github.com/openshift/enhancements/pull/321)

/close
