### ISSUE TITLE
No mention of create load balancer in openstack document

### ISSUE THREAD

**Issue by jasonhjia** [openshift/installer#3623]
# Version
4.4 release
```console
$ openshift-install version
<your output here>
```

# Platform:

openstack

# What happened?
In the installation document (UPI) , there's no mention of create load balancer, and the ansible playbook script also doesn't create it.

In the document of AWS and vsphere, both specifically mentioned that the load balancer must be created manually. 

Therefore, when install openstack UPI, it ends up with waiting for load balancer be ready forever.

# What you expected to happen?
openstack UPI document should include steps to create load balancer.

**Comment by iamemilio** [comment]
Could you please provide more info. The log from your run, and your install-config.yaml with redacted keys would be fantastic!
