### ISSUE TITLE
Error running terraform init

### ISSUE THREAD

**Issue by smohandass** [openshift/installer#3629]
# Version

```console
$ openshift-install version
./openshift-install 4.3.21
built from commit 7bc8168fbba1c831ac1b25c858f4f56cd7468801
release image openshift-43-mirror.automation.cloud:5000/ocp4/openshift4@sha256:79a48030fc5e04fad0fd52f0cdd838ce94c7c1dfa7e7918fd7614d7bcab316f0
```

# Platform:

# What happened?

When running terraform init , i see following error 

terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /root/openshift-43/ocpinstall/installer/upi/vsphere/main.tf: At 4:25: Unknown token: 4:25 IDENT formatlist

terraform version
Terraform v0.11.14

**Comment by abhinavdahiya** [comment]
I think you need to use terraform 0.12.z I think

**Comment by abhinavdahiya** [comment]
> I think you need to use terraform 0.12.z I think

/close
