### ISSUE TITLE
Compiling/Downloading specific Openshift-installer version

### ISSUE THREAD

**Issue by akinfemi** [openshift/installer#3631]
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-3068-g64529d5dcd02bfc2cb279397850dd32c89799883
built from commit 64529d5dcd02bfc2cb279397850dd32c89799883
release image registry.svc.ci.openshift.org/origin/release:4.5
```

# Platform:

MacOS
# What happened?

I'm trying to obtain the latest 4.3.x version. I checked out the `release-4.3` branch and ran the hack/build.sh but still ended up with an unreleased version 4.5 from the master branch. Of course if there's a release page for the 4.3.x binaries somewhere, please share.

# What you expected to happen?

Get a Openshift-install 4.3.x binary
# How to reproduce it (as minimally and precisely as possible)?

```console
$ git clone https://github.com/openshift/installer.git -b release-4.3
$ cd installer
$ hack/build.sh
```

**Comment by abhinavdahiya** [comment]
you should be able to download the installer from try.openshift.com

**Comment by akinfemi** [comment]
Except I'm missing something, the link https://cloud.redhat.com/openshift/install/azure/installer-provisioned points to the latest released (4.4) and pre-released versions

**Comment by akinfemi** [comment]
@abhinavdahiya ^^

**Comment by akinfemi** [comment]
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
