### ISSUE TITLE
is it possible to install Openshift 4.x on RHEL7/8 instead of CoreOS?

### ISSUE THREAD

**Issue by dada216** [openshift/installer#3642]
is it possible to use RHEL7/8 as the OS for the master,infra and node machines?
install would be made in UPI mode and obviously it's expected to not be supported, the question is if it is even possible.

**Comment by abhinavdahiya** [comment]
No, we only support RHEL CoreOS for the control-plane, bootstrap, infra nodes. Although RHEL7 nodes are allowed for compute.

see https://docs.openshift.com/container-platform/4.4/machine_management/more-rhel-compute.html

/close

**Comment by dada216** [comment]
I've installed a 4.4 on RHEV with static ips in UPI mode, I've used this method:
https://www.openshift.com/blog/openshift-upi-using-static-ips
with this ansible playbook:
https://github.com/noseka1/openshift-auto-upi

it should now be possible to add a compute node (worker node) running a rhel 7.6, while the infra and workers are using CoreOS, correct?
