### ISSUE TITLE
libvirt install:  Network created with static dhcp assignments, why?

### ISSUE THREAD

**Issue by michaelgugino** [openshift/installer#367]
There's no good reason to do this, doesn't comport with actual cloud providers or how most people consume libvirt.

**Comment by wking** [comment]
Can you provide more detail, I'm having trouble parsing "static dhcp" ;).  Maybe you mean our [static IPs][1]?  We don't really care what the IPs are, but it seems like users won't care either.  Is your issue just "we should drop those at some point" and not a "this is breaking `$WORKFLOW`"?

Also, for our cloud systems we push up masters and workers in separate subnets, which we don't bother with for libvirt.  I don't see that changing, but we could obviously revisit that if someone raises a use-case where it would matter.

[1]: https://github.com/openshift/installer/blob/06a4afb0a325db1b674ee69dc44321f5d03efd41/data/data/libvirt/variables-libvirt.tf#L26-L39

**Comment by michaelgugino** [comment]
> I'm having trouble parsing "static dhcp" 

I mean exactly that.  DHCP on libvirt is configured to provide static-only IP assignments, not from a pool.

Relevant config:
```sh
[root@mguginop50 ~]# cat /var/lib/libvirt/dnsmasq/tectonic.conf 
##WARNING:  THIS IS AN AUTO-GENERATED FILE. CHANGES TO IT ARE LIKELY TO BE
##OVERWRITTEN AND LOST.  Changes to this configuration should be made using:
##    virsh net-edit tectonic
## or other application using the libvirt API.
##
## dnsmasq conf file created by libvirt
strict-order
local=/tt.testing/
domain=tt.testing
expand-hosts
pid-file=/var/run/libvirt/network/tectonic.pid
except-interface=lo
bind-dynamic
interface=tt0
dhcp-range=192.168.122.1,static
dhcp-no-override
dhcp-authoritative
dhcp-hostsfile=/var/lib/libvirt/dnsmasq/tectonic.hostsfile
addn-hosts=/var/lib/libvirt/dnsmasq/tectonic.addnhosts
```

```sh
[root@mguginop50 ~]# virsh net-dumpxml tectonic
<network connections='4'>
  <name>tectonic</name>
  <uuid>34300328-11b3-4dbb-ab76-dcd1e52886d4</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='tt0' stp='on' delay='0'/>
  <mac address='52:54:00:bb:79:58'/>
  <domain name='tt.testing' localOnly='yes'/>
  <dns>
    <host ip='192.168.122.10'>
      <hostname>mgugino-test-api</hostname>
    </host>
    <host ip='192.168.122.11'>
      <hostname>mgugino-test-api</hostname>
      <hostname>mgugino-test-etcd-0</hostname>
    </host>
    <host ip='192.168.122.50'>
      <hostname>mgugino-test</hostname>
    </host>
  </dns>
  <ip family='ipv4' address='192.168.122.1' prefix='24'>
    <dhcp>
      <host mac='5e:f3:a7:15:ce:5d' name='mgugino-test-master-0' ip='192.168.122.11'/>
      <host mac='5a:c0:c4:e9:62:ba' name='mgugino-test-bootstrap' ip='192.168.122.10'/>
      <host mac='da:68:1d:0d:86:d1' name='worker-sdb9x' ip='192.168.122.51'/>
    </dhcp>
  </ip>
</network>
```

Compare those to libvirt's default network configuration, you'll see what I mean.  There's no need to statically code dhcp entries, just use an IP range.

My use case is getting old installer to work with new via scaleup (part of my 4.0 deliverable).  While I can work around this issue, it does add extra steps and it's just weird that it would be this way by default.

**Comment by dustymabe** [comment]
maybe related: https://github.com/openshift/installer/issues/708

**Comment by crawford** [comment]
I believe this is an artifact of the way the old (Tectonic) installer worked. Now that we use DNS to resolve the hosts, there shouldn't be any need for static assignments. We could try removing these, but it doesn't feel like a high priority at the moment.

**Comment by abhinavdahiya** [comment]
@zeenix is this still something you are looking at?
