### ISSUE TITLE
vSphere UPI: outdated README.md and terraform.tfvars.example

### ISSUE THREAD

**Issue by salv-orlando** [openshift/installer#3674]
# Version
4.4.3

# Platform:
None (UPI)

# What happened?

Commit 27c03c8ead0ebd13efdde0d0c2498194be651b8e overhauled the vSphere API by also changing the way in which ignition data are handled. However this is not reflect in terraforms.tfvars.example and in the README file.

For instance the README file still has not reference to route53 and PHP IPAM, and terraform.tfvars.example still references variables that do not exist anymore in the terraform configuration such as control_plane_ignition and compute_ignition.

# What you expected to happen?

1) README to contain updated instructions
2) terraform.tfvars.example to contain the new required variables (e.g.: region) and omit the ones that do not exist anymore.

# How to reproduce it (as minimally and precisely as possible)?

Not a functional issue, so no reproduction instructions.

# Anything else we need to know?

Nope, It'll be awesome to have updated docs!

# References

**Comment by abhinavdahiya** [comment]
Please feel free to send in an update! Will try to update the docs soon.

**Comment by dbarreda** [comment]
Any idea on what to put on the tfvars to skip the requirement for region? Right now it fails on terraform plan.

**Comment by DizzyThermal** [comment]
Running into the same issue with **region** being required for vSphere UPI cluster install.

This happens when running:
```
terraform apply -auto-approve
```

Output:

```
Error: Missing required argument

The argument "region" is required, but was not set.
```

**Comment by DizzyThermal** [comment]
For completeness:

Before hitting the required **region** argument (above comment), I also had to modify the names of the following values in **terraform.tfvars**:

```
bootstrap_ip -> bootstrap_ip_addresses
control_plane_ips -> control_plane_ip_addresses
compute_ip -> compute_ip_addresses
```

**Comment by tthebst** [comment]
@DizzyThermal For me it worked when I defined following environment variables.

```
$ export AWS_ACCESS_KEY_ID=acceseky
$ export AWS_SECRET_ACCESS_KEY=asecretkey
$ export AWS_DEFAULT_REGION=us-west-2
```

**Comment by staebler** [comment]
> Any workaround on how to turn off the "region" requirement ?

There is no workaround. You **must** specify the AWS region. See step 5 in the [README](https://github.com/openshift/installer/tree/master/upi/vsphere).
