### ISSUE TITLE
vsphere UPI without Route53 and PHPIpam

### ISSUE THREAD

**Issue by salv-orlando** [openshift/installer#3675]
# Version
4.4.3

# Platform:
none (UPI)

# What happened?
The vSphere UPI since commit 27c03c8ead0ebd13efdde0d0c2498194be651b8e assumes route53 as a DNS server and PHP Ipam for assigning nodes to addresses.

While installing the IPAM server is doable, AWS route53 might not be available for users wishing to leverage UPI for vSphere. I am aware vSphere will move to IPI (4.5?), but I wonder if it could be worth to provide an alternate terraform configuration which does not make the assumptions above.

# What you expected to happen?

I was honestly expecting to be able to leverage UPI for 4.4 in the same was as I did for 4.3, with a list of static IPs for bootstrap, control-plane, and compute VMs.

The purpose for opening this issue is to find out whether it could be acceptable to have an alternate terraform configuration. For instance the DNS provider (https://www.terraform.io/docs/providers/dns/index.html) could be used to provide updates to a local bind instance (I know it's not as cool as route53). As for IPAM, I reckon it might be worth thinking about an alternative for bypassing the IPAM server, but that's probably not very important as long as there's a documented process to configure it (see https://github.com/openshift/installer/issues/3674) 

If it's not possible to consider this kind of changes to vSphere UPI, the issue can be closed.

# How to reproduce it (as minimally and precisely as possible)?

Try to perform ```terraform apply``` with a terraform.tfvars prepared for the release-4.3 branch, and see the failure.
Related issue: https://github.com/openshift/installer/issues/3674

# Anything else we need to know?

Nope.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
NACKed

The terraform templates are one example of doing the vsphere upi, and not a reference. So we are not looking to making it any more configurable than it is today. you should try to use vpshere IPI that is already availble for testing here https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.5/

/close
