### ISSUE TITLE
Openshift 4.2 static IPs vsphere, error: unable to recognize "./99_cloud-creds-secret.yam

### ISSUE THREAD

**Issue by cunnadkat** [openshift/installer#3676]
# Version

```console
$ openshift-install version
openshift-install v4.2.13
built from commit 46f909e4ccb4f7a4f82bf1ee28b32fa011a6bd1f
release image quay.io/openshift-release-dev/ocp-release@sha256:782b41750f3284f3c8ee2c1f8cb896896da074e362cf8a472846356d1617752d
```

# Platform:

# What happened?

When i wait for the bootstrap to install the master/workers, the api is timing out after 30 minutes and the master/workers are not showing available on the proxy.

Logging into the bootstrap and tailing the journalctl i can see a cloud-creds error looping every 5 seconds. I can see this file is existing in folder /opt/openshift/openshift but this may be unrelated

openshift.sh[1704]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
openshift.sh[1704]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"

```console
openshift-install wait-for bootstrap-complete --log-level debug
```

# What you expected to happen?

I expect the the bootstrap to install the cluster onto the master/worker notes

# How to reproduce it (as minimally and precisely as possible)?

using the approach in this blog https://shanna-chan.blog/2019/07/26/openshift4-vsphere-static-ip/

Setup load balancer, dns, create install-config.yaml
Generate manifests, change scheduling to false, create ignition files
Use filetranspiler to add static network configuration, creating bootstrap-static.ign, master(1-3)-static.ign worker(1-2)-static.ign
Create 3 master 2 worker custom iso using the rhcos.iso
Create bootstrap form the OVA, start master/computes with their custom iso, pulling correct ignition files

Add the networks LAN certificate onto the bootstrap to allow to access the internet, and run below command to check progress

```console
openshift-install wait-for bootstrap-complete --log-level debug
```

# Anything else we need to know?

I have also tried the method in this blog post which is pretty much the same minus the custom iso. I found that by entering the options on the console before the installation, the VM still used dhcp and not the static ip i had assigned, so this counted as another failed method
 https://www.openshift.com/blog/openshift-4-2-vsphere-install-with-static-ips 

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
> openshift-install v4.2.13

4.2 is a very old version, maybe retry with 4.4 atleast.

Also if possible can you attach the log-bundle for aid in debugging?

**Comment by cunnadkat** [comment]
I have tried with 4.4 and due to the more advanced logging in the journalctl, i could see my vsphere credits+url was not accepted by the installer, e.g the special characters in the password, and the construct of the host was "https://xxx.com/".

Thank you for the response!

**Comment by cunnadkat** [comment]
here is the output of the oc get nodes, i am expecting "oscompute1" and "oscompute2" to appear as workers/compute (they are built with the worker.ign)
osmaster1.chirag.com   Ready    master   46m   v1.17.1
osmaster2.chirag.com   Ready    master   53m   v1.17.1
osmaster3.chirag.com   Ready    master   53m   v1.17.1

Journal logging on the compute1 node shows that the compute node is not found, and thats is because it cant connect to the api server using "system:anonymous"

I can login with oc login -u system:admin, but not with 
oc login -u system:anonymous

May 29 14:22:40 oscompute1.chirag.com hyperkube[1480]: E0529 14:22:40.441759    1480 kubelet.go:2274] node "oscompute1chirag.com" not found
May 29 14:22:40 oscompute1.chirag.com hyperkube[1480]: I0529 14:22:40.537838    1480 csi_plugin.go:947] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "oscompute1.chirag.com" is forbidden: User "system:anonymous" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope
