### ISSUE TITLE
openshift-install 4.4.x , prompt to platform when using "wait-for install-complete"

### ISSUE THREAD

**Issue by msoranno** [openshift/installer#3678]
# Version

```console
$ openshift-install version
[core@tst01-stn-001-bastion bastionboot]$ ./openshift-install version
./openshift-install 4.4.3
built from commit 78b817ceb7657f81176bbe182cc6efc73004c841
release image quay.io/openshift-release-dev/ocp-release@sha256:039a4ef7c128a049ccf916a1d68ce93e8f5494b44d5a75df60c85e9e7191dacc
```

# Platform:

UPI (vsphere)

# What happened?
Using **wait-for install-complete** , prompt to platforms

But, when using **wait-for bootstrap-complete**, works just fine, no prompts.

# What you expected to happen?

I was expecting no prompt at all when using **wait-for install-complete** ..

# How to reproduce it (as minimally and precisely as possible)?
```console

1. Create a cluster
2. try to monitor status by using
./openshift-install --dir=<your install dir> wait-for install-complete

[core@tst01-stn-001-bastion bastionboot]$ ./openshift-install --dir=install-config-coreos-files wait-for install-complete
? Platform  [Use arrows to move, enter to select, type to filter, ? for more help]
> aws
  azure
  gcp
  openstack
  ovirt
```

# Anything else we need to know?

 It working good unitl 4.3.x

**Comment by stbenjam** [comment]
It looks like this was fixed by https://github.com/openshift/installer/pull/3681

/close
