### ISSUE TITLE
[RFE] Updating docs/user/metal

### ISSUE THREAD

**Issue by rlopez133** [openshift/installer#3705]
Our team has created documentation within the [baremetal-deploy repository](https://github.com/openshift-kni/baremetal-deploy ) on showing how to deploy IPI on Baremetal. We currently have a [homepage](https://openshift-kni.github.io/baremetal-deploy/ ) for all the docs with it capturing how to deploy IPI on BM [4.3](https://openshift-kni.github.io/baremetal-deploy/4.3/Deployment.html), [4.4](https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html) and soon [4.5](https://openshift-kni.github.io/baremetal-deploy/4.5/Deployment) We've included [troubleshooting](https://openshift-kni.github.io/baremetal-deploy/4.5/Troubleshooting) documentation as well. All of our documentation  is rendered in both HTML and PDF, is modularized, and we've worked with the docs team to ensure we have a standard for both upstream and downstream. What would be the process to get our docs to reside here or maybe even point to our existing https://openshift-kni.github.io/baremetal-deploy/ as we are actively maintaining it?

Thanks,
Roger

**Comment by stbenjam** [comment]
The documentation there is very high quality, it needs to go somewhere and be discoverable. Do other platforms have analogous documentation upstream? Could it be relocated to https://github.com/openshift/openshift-docs and then we could easily link to to docs.openshift.com from the installer repo?

I'm hesitant to say it should be linked directly to the baremetal-deploy GitHub page or to be all incorporated here.

Ultimately it's up to the installer team I think.

@abhinavdahiya PTAL

**Comment by rlopez133** [comment]
> The documentation there is very high quality, it needs to go somewhere and be discoverable. Do other platforms have analogous documentation upstream? Could it be relocated to https://github.com/openshift/openshift-docs and then we could easily link to to docs.openshift.com from the installer repo?
> 
> I'm hesitant to say it should be linked directly to the baremetal-deploy GitHub page or to be all incorporated here.
> 
> Ultimately it's up to the installer team.
> 
> @abhinavdahiya PTAL

@stbenjam - The modules live here as well: https://github.com/openshift/openshift-docs/tree/master/installing/installing_bare_metal_ipi . Essentially the docs team works with us and they build the downstream from this. Regarding upstream, the modules are all there, but since we are always updating constantly within our repo, things don't necessarily land immediately in the openshift-docs repo as the process right now is update baremetal-deploy repo, then things get picked up in openshift-docs repo when we sync. Also this documentation right now in openshift-docs is requires credentials to access.
