### ISSUE TITLE
Install using AWS private DNS

### ISSUE THREAD

**Issue by anairatgithub** [openshift/installer#3719]
# Version

```console
$ openshift-install version
./openshift-install 4.4.6
built from commit 99e1dc030910ccd241e5d2563f27725c0d3117b0
release image quay.io/openshift-release-dev/ocp-release@sha256:7613d8f7db639147b91b16b54b24cfa351c3cbde6aa7b7bf1b9c80c260efad06

```

# Platform:

# What happened?
 ./openshift-install create install-config --log-level debug --dir=ocp44-install-config 
fails with
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": no public Route 53 hosted zones found
# What you expected to happen?
No failures when using private DNS hosted zones in AWS
# How to reproduce it (as minimally and precisely as possible)?

```console
./openshift-install create install-config --log-level debug --dir=ocp44-install-config 
```

# Anything else we need to know?
I am not a go programmer by any measure, but looking at the code base
https://github.com/openshift/installer/blob/64f1a13dbe64c4148c4098707649ba70bcb20aec/pkg/asset/installconfig/aws/basedomain.go#L40
you explicitly exclude any private zones - is that right?

# References

- enter text here.
#3136

**Comment by anairatgithub** [comment]
If this is not a supported configuration, can you please let me know how to interpret this documentation:
Installing a private cluster on AWS
https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-private.html

Thanks.

**Comment by abhinavdahiya** [comment]
we do not support creating a internal only cluster install-config.yaml using the prompts.. the user needs to create their own and provide it to the installer. That is not to say you can't create a internal only cluster on AWS.

look at the sample provided https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-private.html#installation-aws-config-yaml_installing-aws-private

```
$ mkdir install_dir
$ cp aws-internal-install-config.yaml install_dir/install-config.yaml
$ openshift-install --dir install_dir create cluster
```

```
$ openshift-install explain installconfig
```
Can also be used to see all the supported configuration if you are using a 4.5 nightly.

/close
