### ISSUE TITLE
Bootstrap node not starting up due to wrong ignition version

### ISSUE THREAD

**Issue by gerr1t** [openshift/installer#3745]
# Version

```console
$ openshift-install version
openshift-install 4.4.0-0.okd-2020-05-23-055148-beta5
built from commit 0f0142e7261349b93c3dd3dd02a9ce164dfd2d4f
release image quay.io/openshift/okd@sha256:057e2eead0443a60877fc9b579770e6464eb7fa8d92855f5c2f09ef7340d60db
```

# Platform:
openstack

# What happened?
The openshift-install application is creating ignition files for version 3.0.0, but the FCOS image (when deploying OKD) that is used only support 2.2.1, which means the bootstrap node fails to launch with the following error:

```
[    6.722739] ignition[551]: warning at $.ignition.config.merge.0.httpHeaders, line 1 col 34: Unused key httpHeaders
```

The fact that these headers are not used means it cannot authenticate against the Glance API of Openstack, which causes the images download to fail and the bootstrap node to be stuck in a reboot loop.

The image used for this deployment: 
```
https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200420.3.0/x86_64/fedora-coreos-31.20200420.3.0-openstack.x86_64.qcow2.xz?sha256=2bfa0e9773df90f37b3e8d8292a09b59f2159457a427858a566b73ad7b89e88b
```

A snippet from the generated ignition file:
```
{
  "ignition": {
    "version": "3.0.0"
  },
...
```

The problem seems to be related to the fact that this FCOS image has Ignite 2.2.1 installed, but the ignition files that are generated and pushed to glance, are written in version 3.0.0

**Comment by vrutkovs** [comment]
Lets use openshift/okd repo to track that

/close
