### ISSUE TITLE
RHCOS OCP4.3 master0 boot is failing : User provisioned baremetal

### ISSUE THREAD

**Issue by rahulsingh45-tech** [openshift/installer#3746]
Hi Team,

In bootstrap node , boot is successfully completed. 
In master0 node, boot is failing with below errors: 
It seems like master0 node is not getting the ignition config from bootstrap node. I have checked the DNS configuration and verified all the parameters but not getting what is causing the issue.

![master0_error](https://user-images.githubusercontent.com/64540939/84426552-0da52580-ac41-11ea-9489-f15f18886cd2.jpg)

**Comment by abhinavdahiya** [comment]
Try calling the log bundle for debugging https://github.com/openshift/installer/blob/master/docs/user/troubleshootingbootstrap.md

**Comment by abhinavdahiya** [comment]
> Try calling the log bundle for debugging https://github.com/openshift/installer/blob/master/docs/user/troubleshootingbootstrap.md

/close
