### ISSUE TITLE
libvirt install does not create etcd-0 dns records

### ISSUE THREAD

**Issue by RobMokkink** [openshift/installer#3748]
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-2696-g1541bf917973186bbab6a5f895f08db4334a5d9a
built from commit 1541bf917973186bbab6a5f895f08db4334a5d9a
release image registry.svc.ci.openshift.org/origin/release:4.3
```

# Platform:

libvirt

ipi
# What happened?

I installed the environment as describe in https://github.com/openshift/installer/blob/release-4.4/docs/dev/libvirt/README.md.
The installation starts, but the etcd-0 records are not created

# What you expected to happen?

The etcd-0 records to be created

# How to reproduce it (as minimally and precisely as possible)?
https://github.com/openshift/installer/blob/release-4.4/docs/dev/libvirt/README.md

# Anything else we need to know?
Cannot patch the libvirt installation

# References

- enter text here.

**Comment by RobMokkink** [comment]
Here is some output from `boot-kube.service`

`
Jun 13 13:29:25 lab-k2sqj-bootstrap bootkube.sh[2072]: {"level":"warn","ts":"2020-06-13T13:29:25.673Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-22d4878e-53fb-4447-a893-d540503bb3b9/etcd-0.lab.ocp.local:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup etcd-0.lab.ocp.local on 192.168.126.1:53: no such host\""}
Jun 13 13:29:25 lab-k2sqj-bootstrap bootkube.sh[2072]: https://etcd-0.lab.ocp.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded
`


This is the dump from the libvirtd network:
`
<network connections='2'>
  <name>lab-k2sqj</name>
  <uuid>e82c8bbc-54e6-49ca-b82c-9614cef5d30d</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='tt0' stp='on' delay='0'/>
  <mac address='52:54:00:df:3d:7c'/>
  <domain name='lab.ocp.local' localOnly='yes'/>
  <dns enable='yes'>
    <host ip='192.168.126.10'>
      <hostname>api.lab.ocp.local</hostname>
      <hostname>api-int.lab.ocp.local</hostname>
    </host>
    <host ip='192.168.126.11'>
      <hostname>api.lab.ocp.local</hostname>
      <hostname>api-int.lab.ocp.local</hostname>
    </host>
  </dns>
  <ip family='ipv4' address='192.168.126.1' prefix='24'>
    <dhcp>
      <range start='192.168.126.2' end='192.168.126.254'/>
      <host mac='52:54:00:f6:96:76' name='lab-k2sqj-master-0.lab.ocp.local' ip='192.168.126.11'/>
      <host mac='52:54:00:3a:a3:bc' name='lab-k2sqj-bootstrap.lab.ocp.local' ip='192.168.126.10'/>
    </dhcp>
  </ip>
</network>
`

**Comment by RobMokkink** [comment]
I switched to branch `origin/release-4.3` and created and started the build.
Then i created the cluster, see the output from the libvirt network:
`
<network connections='2'>
  <name>lab-qfqvw</name>
  <uuid>4ac0cd75-e9a0-451a-8f4a-f5678486359e</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='tt0' stp='on' delay='0'/>
  <mac address='52:54:00:f4:74:ca'/>
  <domain name='lab.ocp.local' localOnly='yes'/>
  <dns enable='yes'>
    <srv service='etcd-server-ssl' protocol='tcp' domain='lab.ocp.local' target='etcd-0.lab.ocp.local' port='2380' weight='10'/>
    <host ip='192.168.126.10'>
      <hostname>api.lab.ocp.local</hostname>
      <hostname>api-int.lab.ocp.local</hostname>
    </host>
    <host ip='192.168.126.11'>
      <hostname>api.lab.ocp.local</hostname>
      <hostname>api-int.lab.ocp.local</hostname>
      <hostname>etcd-0.lab.ocp.local</hostname>
    </host>
  </dns>
  <ip family='ipv4' address='192.168.126.1' prefix='24'>
    <dhcp>
      <range start='192.168.126.2' end='192.168.126.254'/>
      <host mac='52:54:00:4a:50:fc' name='lab-qfqvw-bootstrap.lab.ocp.local' ip='192.168.126.10'/>
      <host mac='52:54:00:12:86:6d' name='lab-qfqvw-master-0.lab.ocp.local' ip='192.168.126.11'/>
    </dhcp>
  </ip>
</network>
`
The service record is created now.

**Comment by cfergeau** [comment]
This was an intentional 4.4/etcd change, see https://github.com/openshift/installer/commit/b0ed309b90a82239c6d74c934147c1b3bb9df89b

**Comment by cfergeau** [comment]
No longer needed in recent openshift releases
/close
