### ISSUE TITLE
check early if nodes have a hostname of `localhost` and error 

### ISSUE THREAD

**Issue by dustymabe** [openshift/installer#3751]
# Version

```console
openshift-install unreleased-master-2503-g0f0142e7261349b93c3dd3dd02a9ce164dfd2d4f-dirty
built from commit 0f0142e7261349b93c3dd3dd02a9ce164dfd2d4f
release image quay.io/openshift/okd@sha256:057e2eead0443a60877fc9b579770e6464eb7fa8d92855f5c2f09ef7340d60db
```

# Platform:
baremetal

* UPI (semi-manual installation on customised infrastructure)

# What happened?

Basically a lot of chasing random error messages on the internet to find out later my nodes didn't have hostnames set. They were all set to `localhost` because of [this bug](https://github.com/coreos/fedora-coreos-tracker/issues/538).

I'd like to know if we can somehow add a rudimentary error check somewhere early on in the bootstrap/install process and bubble up a nice error message to the user that says "your hostnames are set to localhost, which is probably the root of your issues". It's been a while since I installed openshift and it took me a while to dig in and find the root of my problems. This could definitely bite a new user hard. Can we improve?

**Comment by wking** [comment]
I don't see this as install-specific, and would rather address it with [rhbz#1817774](https://bugzilla.redhat.com/show_bug.cgi?id=1817774) or similar.  We'd still want to follow that up with installer-side code to gather alerts and log them from the log bundle (#2569).

**Comment by darkmuggle** [comment]
This might be addressed with https://github.com/openshift/machine-config-operator/pull/1813

**Comment by dustymabe** [comment]
I guess what I'm looking for is somehow getting a message back up the user that says: "hey, this system isn't going to work, or probably isn't going to work because your hostnames are set to `localhost`".

Anything that makes that happen would be a win!
