### ISSUE TITLE
baremetal: relax network interface and BMH validations when generating ignition-configs

### ISSUE THREAD

**Issue by yevgeny-shnaidman** [openshift/installer#3788]
# Version

```console
$ openshift-install version
4.6
```

# Platform:

baremetal

Assisted-installer
# What happened?

When running in assisted installer mode, we need to disable the following validation:
1) validating network interfaces. Currently these validations are performed using livbirt, which is
    not available in the assisted-installer environment
2) bare metal host validation - currently assited-installer does not support or use baremetal host, so we would like to not fill this irrelevent info in the install_config.yaml
3) currently compiling baremetal openshift-installer requires TAG="baremetal+libvirt", which is kind of confusing. This can easily be changed to TAG="baremetal"

# What you expected to happen?

# How to reproduce it (as minimally and precisely as possible)?

```console

```

# Anything else we need to know?

# References

**Comment by hardys** [comment]
/retitle Disabling network interface and BMH validations for assisted-installer

**Comment by hardys** [comment]
I think the underlying requirement here is to not enforce validation of the nics and libvirt endpoint, when running `create ignition-configs` for the `baremetal` platform.

The assisted installer flow creates the ignition configs only, and doesn't do the full `create cluster` automated workflow (the bootstrap node and masters are manually booted), so we either need a way to disable those validations, or ensure they are only triggered when `create cluster` is invoked.

**Comment by hardys** [comment]
/retitle baremetal: relax network interface and BMH validations when generating ignition-configs

**Comment by dhellmann** [comment]
This issue was resolved with https://github.com/openshift/enhancements/pull/388 and #3851

/close
