### ISSUE TITLE
kubedmin password exposed by intaller in stdout

### ISSUE THREAD

**Issue by andrejs-sisojevs-accenture** [openshift/installer#3805]
# Version: 4.4.6
# Platform: any, IPI
# What happened?
openshift-installer outputs sensitive data (kudeadmin password) to stdout. We would like to have openshift-installer output in our logs, but we have to silence it because of this exposure. E.g.,
```
...
level=info msg="Install complete!"
level=info msg="To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/tmp/install/20200618_acn-platforms_7oeUhIREW/depl
oy/auth/kubeconfig'"
level=info msg="Access the OpenShift web-console here: https://console-openshift-console.apps.example.domainname.com"
level=info msg="Login to the console with user: kubeadmin, password: ABCD-EFGH-123456-789"
```

# What you expected to happen?

Login credentials are already output by installer to "auth" directory - just refernce that file, instead of writing credetials to stdout.

**Comment by abhinavdahiya** [comment]
Is is required for installer to print this password so the users can copy and use it directly.
A lot of cli's print passwords to the stdout and I don't think why the installer wouldn't

In-any case we can not stop printing it due to established requirements.

**Comment by andrejs-sisojevs-accenture** [comment]
It's a pity you won't follow common and basic security practices.

For those, who suffer similar problem, here is a workaround:
```
./openshift-install <arguments> | grep -v "Login to the console with user"
```
