### ISSUE TITLE
adding a rhel compute node to a 4.4 cluster installed in UPI

### ISSUE THREAD

**Issue by dada216** [openshift/installer#3813]
following this closed issue:
https://github.com/openshift/installer/issues/3642

I've installed a 4.4 on RHEV with static ips in UPI mode, I've used this method:
https://www.openshift.com/blog/openshift-upi-using-static-ips
with this ansible playbook:
https://github.com/noseka1/openshift-auto-upi

it should now be possible to add a compute node (worker node) running a rhel 7.6, while the infra and workers are using CoreOS, correct?

**Comment by abhinavdahiya** [comment]
Here's how you can add RHEL compute https://docs.openshift.com/container-platform/4.4/machine_management/more-rhel-compute.html
