### ISSUE TITLE
failed install ocp-master in baremental

### ISSUE THREAD

**Issue by majorinche** [openshift/installer#3825]
# Version

```console
$ openshift-install version
openshift-install 4.4.3
built from commit 78b817ceb7657f81176bbe182cc6efc73004c841
release image quay.io/openshift-release-dev/ocp-release@sha256:039a4ef7c128a049ccf916a1d68ce93e8f5494b44d5a75df60c85e9e7191dacc

```

# Platform:
baremetal
UPI

# What happened?

try install OCP 4.4.3 into baremental, but failed to install master node
there are 3 nodes, all of them are failed, i can list some failure, but not sure which one would be helpful
multipathd: -----start up----
multipathd: read /etc/multipath.conf
multipathd: /etc/multipath.conf does not exist
iscsid: iscsid: can't open InitiatorName configuration file /etc/iscsi/initialtorname.iscsi does not exist

# What you expected to happen?

master node install successfully

# How to reproduce it (as minimally and precisely as possible)?
1, with pxe environment ok, and support required files and configuration
rhcos-4.4.3-x86_64-metal.x86_64.raw.gz

DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL rhcos-4.4.3-x86_64-installer-kernel-x86_64
    APPEND ip=10.30.0.59::10.30.0.223:255.255.255.0:master3.bm1.ocp443.sonic.com:ens192:none nameserver=10.20.0.224 rd.neednet=1 initrd=rhcos-4.4.3-x86_64-installer-initramfs.x86_64.img coreos.inst=yes coreos.inst.ignition_url=http://10.30.0.154/master.ign coreos.inst.image_url=http://10.30.0.154/rhcos-4.4.3-x86_64-metal.x86_64.raw.gz coreos.inst.install_dev=sda coreos.inst.insecure=yes console=tty0

2, reboot the baremental and boot from PXE

btw, this environent can install ok in vmware virtual matchine

**Comment by abhinavdahiya** [comment]
Can you attach bit logs for failed machines

**Comment by majorinche** [comment]
it just get into dracut like: dracut:/#

and how can i get the boot logs (journal -xb) out, i already try to configure ip address successfully, but scp command seems not work

**Comment by cgwalters** [comment]
Try using e.g. `systemctl --failed`.  As for getting the logs out, one approach is to use `curl -X POST` to send to a pastebin type service.

**Comment by miabbott** [comment]
For debugging Ignition failures (this looks like one given the information) - https://github.com/openshift/os/blob/master/FAQ.md#q-how-do-i-debug-ignition-failures

**Comment by majorinche** [comment]
systemctl –failed
find coreos-installer service error 

journalctl -b –u coreos-installer
find: 
![ignition failed](https://user-images.githubusercontent.com/19666925/86306154-138d9580-bc46-11ea-9bca-c66547d570a0.png)

**Comment by bigg01** [comment]
On a HPE DL 380 Gen 9 and 10 you have to disable internal sd card if you want to use sda and not switch to sdb.
