### ISSUE TITLE
bootstrapping is getting timedout and master is not coming up - Openshift 4.4 Install

### ISSUE THREAD

**Issue by naga49-source** [openshift/installer#3857]
Hi All

I have the following queries, 
1.I am trying to setup openshift cluster using one master and 2 worker nodes.. is it a supported configuration?
2. I am following the baremetal method of installation and trying to setup the openshift cluster the bootstrap is getting timedout with the following error.

[root@node1-kube openshift-install-files]# ./openshift-install wait-for bootstrap-complete --dir=/root/install
INFO Waiting up to 20m0s for the Kubernetes API at https://api.ocp.lab.lan:6443...
INFO API v1.17.1+912792b up
INFO Waiting up to 40m0s for bootstrapping to complete...

ERROR Cluster operator network Degraded is True with RolloutHung: DaemonSet "openshift-sdn/sdn" rollout is not making progress - last change 2020-07-07T11:46:03Z
INFO Cluster operator network Progressing is True with Deploying: DaemonSet "openshift-multus/multus-admission-controller" is waiting for other operators to become ready
DaemonSet "openshift-sdn/sdn" is not available (awaiting 1 nodes)
INFO Cluster operator network Available is False with Startup: The network is starting up
INFO Use the following commands to gather logs from the cluster
INFO openshift-install gather bootstrap --help
FATAL failed to wait for bootstrapping to complete: timed out waiting for the condition

3. when I run "oc get co" I am getting the following error..
[root@node1-kube install]# oc get co
NAME               VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
cloud-credential             True        False         False      17h
network                      False       True          True       17h

I am uploading the logs I have pulled from the system. Please help me to come out from this issue..
[log-bundle-20200707175642.tar.gz](https://github.com/openshift/installer/files/4888625/log-bundle-20200707175642.tar.gz)

[root@node1-kube install]# oc get nodes
NAME                  STATUS     ROLES    AGE   VERSION
master0.ocp.lab.lan   NotReady   master   17h   v1.17.1+912792b

# Version

```console
$ openshift-install version
[root@node1-kube openshift-install-files]# ./openshift-install version
./openshift-install 4.4.9
built from commit 1541bf917973186bbab6a5f895f08db4334a5d9a
release image quay.io/openshift-release-dev/ocp-release@sha256:15280aba8f1c82fe39180a617e3b4886401f6c2aef63c7962203aa10530d1db8

```

# Platform:

**Comment by abhinavdahiya** [comment]
> 1.I am trying to setup openshift cluster using one master and 2 worker nodes.. is it a supported configuration?

No, we need 3 control-plane and 2 compute minimum, https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#machine-requirements_installing-bare-metal

I think we support 3 control-plane no workers, but that makes the 3 control-plane act both as compute and control plane roles.

**Comment by naga49-source** [comment]
What is the reason behind asking for 3 control planes.. Why it won't work with one Control plane..
