### ISSUE TITLE
bond support on bare metal IPI

### ISSUE THREAD

**Issue by chz8494** [openshift/installer#3876]
# Version

```console
$ openshift-install version
4.4
```

# Platform:
baremetal

Please specify:
* IPI 

# What happened?

Actually need few answers for following questions:
1. I only see guide about enabling bond through kernel options on [RHCOS UPI](https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-iso_installing-bare-metal), is there a way to enable bond/port-channel on IPI? seems IPI yaml has option to define which interface to be used as for data, I'd expect that interface can be bond too, but the bond interface has to be pre-created by something, would it be included in bootstrap? I know Openstack ironic can do that, just don't see this part in Openshif IPI script. 
2. There are other use cases too for customized network setup on bare metal, such as isolating mgmt/data/storage/sriov, I don't want to put them all in same interfaces, so far I can't find such example anywhere in your documents, bond support is only one of this use cases. Anyhow, I feel IPI is not officially fully supported, are you encouraging users to create their own automation process to install openshift in a UPI kind of way?
3. Is there a way to manage/PXE boot RHCOS hosts in a way like ubuntu MaaS for Redhat? That would make things much easier.

**Comment by hardys** [comment]
This is a known issue for IPI baremetal deployments, currently the only solution is to use either MachineConfig customization or ignition customizations ref https://github.com/openshift/installer/blob/master/docs/user/customization.md

That may be sufficient to configure the primary controlplane network on a bond, but it is not sufficient e.g if you also require a non-default VLAN.

Further discussion in:

https://github.com/coreos/ignition/issues/979

https://github.com/openshift/machine-config-operator/issues/1690

https://github.com/openshift/enhancements/pull/394

/label platform/baremetal

https://github.com/openshift/enhancements/pull/399

**Comment by chz8494** [comment]
@hardys I don't see how machineconfig works with bond on that page.
For ignition config, is there a full example? I see the simple example at the end of that document talking about increasing http timeout. I would assume to put any extra config in `worker.ign` or `master.ign`? where are these files in installer? are they auto generated? so to enable bond it'd be like putting this but in a json format in `worker.ign`?
```
networkd:
  units:
   - name: 10-int.network
     contents: |
       [Match]
       Name=eno*
       [Network]
       Bond=bond0
       LinkLocalAddressing=no
       IPv6AcceptRA=no
   - name: 20-bond0.netdev
     contents: |
       [NetDev]
       Name=bond0
       Kind=bond
       [Bond]
       Mode=balance-rr
       MIIMonitorSec=1
   - name: 30-bond0.network
     contents: |
       [Match]
       Name=bond0
       [Network]
       DHCP=true
```

**Comment by chz8494** [comment]
plus I don't see bare metal option in create-config command. Anyhow, I feel this version of Openshift is not well organized and documented, and not user friendly to bare metal users at all. :(
