### ISSUE TITLE
OCP 4.5 on OSP13 - api server cannot be reached

### ISSUE THREAD

**Issue by 2-face** [openshift/installer#3913]
# Version

```console
./openshift-install 4.5.1
built from commit b714ff8ee8845b86da2dafce8fa5630ef1806f3b
release image quay.io/openshift-release-dev/ocp-release@sha256:a656048696e79a30f0536f5acd5a1e8ec5ae331d4c7d21ca62bc8de412c79dc4
```

# Platform:
OSP13 (Queens)

IPI

No Octavia. Tried with trunk and without trunk Neutron extension.

# What happened?

Installation of OCP times out at reaching k8s API server via api_fip (floating-ip, preconfigured, that is assigned to api_port).
Installer should either:
* assign floating_ip to bootstrap machine
* access API server via bootstrap_fip and then when it completes on bootstrap switch to api_fip

Workers are never created and bootstrap node is not destroyed

On bootstrap node:
```console
[core@ocp-uc-7m8x4-bootstrap ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Fri 2020-07-17 10:37:20 UTC. --
Jul 17 12:44:04 ocp-uc-7m8x4-bootstrap bootkube.sh[28966]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
```

Error while installing
```console
 to host
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.ocp.uc.nelab:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 10.134.255.2:6443: connect: no route to host
DEBUG Fetching Bootstrap SSH Key Pair...
DEBUG Loading Bootstrap SSH Key Pair...
DEBUG Using Bootstrap SSH Key Pair loaded from state file
DEBUG Reusing previously-fetched Bootstrap SSH Key Pair
DEBUG Fetching Install Config...
DEBUG Loading Install Config...
DEBUG   Loading SSH Key...
DEBUG   Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Loading Cluster Name...
DEBUG     Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Loading Pull Secret...
DEBUG   Loading Platform...
DEBUG Using Install Config loaded from state file
DEBUG Reusing previously-fetched Install Config
INFO Pulling debug logs from the bootstrap machine
DEBUG Added /tmp/bootstrap-ssh115195768 to installer's internal agent
DEBUG Added /home/mimazure/.ssh/id_rsa to installer's internal agent
DEBUG Gathering bootstrap systemd summary ...
DEBUG Gathering bootstrap failed systemd unit status ...
DEBUG Gathering bootstrap journals ...
DEBUG Gathering bootstrap containers ...
DEBUG Gathering rendered assets...
DEBUG Gathering cluster resources ...
DEBUG Waiting for logs ...
DEBUG Gather remote logs
DEBUG Collecting info from 10.0.0.11
 EBUG Warning: Permanently added '10.0.0.11' (ECDSA) to the list of known hosts.
DEBUG Gathering master systemd summary ...
DEBUG Gathering master failed systemd unit status ...
DEBUG Gathering master journals ...
DEBUG Gathering master containers ...
DEBUG time="2020-07-17T08:16:34Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
DEBUG Waiting for logs ...
DEBUG Collecting info from 10.0.0.29
 EBUG Warning: Permanently added '10.0.0.29' (ECDSA) to the list of known hosts.
DEBUG Gathering master systemd summary ...
DEBUG Gathering master failed systemd unit status ...
DEBUG Gathering master journals ...
DEBUG Gathering master containers ...
DEBUG time="2020-07-17T08:16:36Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
DEBUG Waiting for logs ...
DEBUG Collecting info from 10.0.0.21
DEBUG lost connection
 EBUG ssh: connect to host 10.0.0.21 port 22: No route to host
DEBUG Log bundle written to /var/home/core/log-bundle-20200717081627.tar.gz
INFO Bootstrap gather logs captured here "/home/mimazure/ocp/install/log-bundle-20200717081627.tar.gz"
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get https://api.ocp.uc.nelab:6443/version?timeout=32s: dial tcp 10.134.255.2:6443: connect: no route to host
```

Assumption is that api_fip is reachable even though it is assigned to port which is down (as per openstack README it should work). 
/etc/hosts point to api_fip properly.

# What you expected to happen?

Installation should proceed.

# How to reproduce it (as minimally and precisely as possible)?

```console
./openshift-install create cluster --dir=. --log-level=debug
```

# Anything else we need to know?

As a matter of fact I've tried to assign api_fip to bootstrap VM and then it started responding. In such case maybe there is some OSP setting which should allow for api_fip to respond?
Also as far as I could see - 10.0.0.5 is assigned on bootstrap VM.
Tried the same with OCP4.4.11 for RHEL7 too - same errors.

**Comment by r3d3mpt10n** [comment]
Hey so just to clarify. When the bootstrap machine is started, the FIP (Which is attached to the fixed IP of 10.0.0.5) is hosted on the Bootstrap node. Then, once Bootstrap is completed, that 10.0.0.5 moves over to one of the Controllers and stays there with Keepalived.

If the master nodes don't come up for what ever reason, then it will show that same error after the timeout. For example here:
`INFO Bootstrap gather logs captured here "/home/stack/ocp4.5/ocp/log-bundle-20200720120234.tar.gz"                                                                                                                                            
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get https://api.stack-ocp.lab.net:6443/version?timeout=32s: dial tcp 172.20.0.130:6443: i/o timeout  `

Then if I check the console of my master nodes:
`openstack console log show stack-ocp-brvjm-master-1`

I can see that it spent the whole time being unable to reach the machine-config endpoint:

`[K[  [0;31m*[0;1;31m*[0m[0;31m* [0m] A start job is running for Ignition (fetch) (31min 52s / no limit)[K[ [0;31m*[0;1;31m*[0m[0;31m*  [0m] A start job is running for Ignition (fetch) (31min 52s / no limit)[K[[0;31m*[0;1;31m*[0m[0;31m*   [0m] A start job is running for Ignition (fetch) (31min 53s / no limit)[K[[0;1;31m*[0m[0;31m*    [0m] A start job is running for Ignition (fetch) (31min 53s / no limit)[K[[0m[0;31m*     [0m] A start job is running for Ignition (fetch) (31min 54s / no limit)[K[[0;1;31m*[0m[0;31m*    [0m] A start job is running for Ignition (fetch) (31min 54s / no limit)[K[[0;31m*[0;1;31m*[0m[0;31m*   [0m] A start job is running for Ignition (fetch) (31min 55s / no limit)[K[ [0;31m*[0;1;31m*[0m[0;31m*  [0m] A start job is running for Ignition (fetch) (31min 55s / no limit)[K[  [0;31m*[0;1;31m*[0m[0;31m* [0m] A start job is running for Ignition (fetch) (31min 56s / no limit)[K[   [0;31m*[0;1;31m*[0m[0;31m*[0m] A start job is running for Ignition (fetch) (31min 56s / no limit)[ 1925.864696] ignition[865]: GET https://10.0.0.5:22623/config/master: attempt #240
`
 
Are you able to see if this is the same error for you? openstack console log show NAME_OF_MASTER_VM

**Comment by r3d3mpt10n** [comment]
My issue was a combination of DVR and DNS. I disabled DVR and the masters all started up and could reach the machine-config endpoint on the Bootstrap node. So a console log show now shows that the VM has been configured:

```
Red Hat Enterprise Linux CoreOS 45.82.202007141718-0 (Ootpa) 4.5
SSH host key: SHA256:RLI3eHtJbCN5ecv1XYQ/BypDJiisOOSi8Vqe3ff+bFk (ED25519)
SSH host key: SHA256:Ey9xmzuu8iy7tAf9fld7wBng0CjrSHFPcbF/J53SyBM (ECDSA)
SSH host key: SHA256:Ft8b8gd4K4ytvIybL7ikrlSUmJyNVG1waPWXHqBCn7M (RSA)
ens3: 10.0.1.221 fe80::1570:907b:a89f:75d4
stack-ocp-brvjm-master-1 login: [  401.189958] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
```

Is there any other errors on that Bootstrap node that you can see? You shared this one:
```
[core@ocp-uc-7m8x4-bootstrap ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Fri 2020-07-17 10:37:20 UTC. --
Jul 17 12:44:04 ocp-uc-7m8x4-bootstrap bootkube.sh[28966]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
```

But that will just keep looping until it eventually creates it, eg:
```
Jul 20 02:57:27 stack-ocp-brvjm-bootstrap bootkube.sh[290226]: [#313] failed to create some manifests:
Jul 20 02:57:27 stack-ocp-brvjm-bootstrap bootkube.sh[290226]: "99_openshift-cluster-api_worker-machineset-0.yaml": unable to get REST mapping for "99_openshift-cluster-api_worker-machineset-0.yaml": no matches for kind "MachineSet" in version "machine.openshift.io/v1beta1"
Jul 20 02:57:28 stack-ocp-brvjm-bootstrap bootkube.sh[290226]: Created "99_openshift-cluster-api_worker-machineset-0.yaml" machinesets.v1beta1.machine.openshift.io/stack-ocp-brvjm-worker -n openshift-machine-api
Jul 20 02:57:28 stack-ocp-brvjm-bootstrap bootkube.sh[290226]: Updated status for "99_openshift-cluster-api_worker-machineset-0.yaml" machinesets.v1beta1.machine.openshift.io/stack-ocp-brvjm-worker -n openshift-machine-api
```

Once I fixed the DVR and DNS issues I was having, I can see the bootstrap process has completed without issues. So I'm using:

```
$ ./openshift-install version
./openshift-install 4.5.2
built from commit 6336a4b3d696dd898eed192e4188edbac99e8c27
release image quay.io/openshift-release-dev/ocp-release@sha256:8f923b7b8efdeac619eb0e7697106c1d17dd3d262c49d8742b38600417cf7d1d
```

And I'm not seeing any issues with the way the FIPs are assigned and moved between Bootstrap and Masters. Maybe if you can share the journalctl -u bootkube.service --no-pager  output and we can help find any other errors that might exist there?

**Comment by 2-face** [comment]
Hi, thank you for your comment (I've seen of similar errors too). What I did (as all computes in Openstack cluster are network nodes too) I had to modify Neutron config on each compute from DVR to **DVR_SNAT** in l3_agent.conf:

```
ovs_integration_bridge = br-int
interface_driver=neutron.agent.linux.interface.OVSInterfaceDriver
agent_mode=dvr_snat
```

After that api_fip starts to be reachable (initially pointing to bootstrap node, then to selected master node).

Issue with initial settings (dvr only) - was that a created router (although it had IP address assigned on external network, and interface attached to tenant network) - wasn't really forwarding packets. Honestly - in all my setups I've always been setting up compute/network node, not separately, so possibly there is a caveat to make it work as separate entities (for which I assume original settings for l3_agent were).

I have another problem now - which possibly is related to Neutron settings too, however I need to open another issue and attach new log bundle. Etcd is not coming up on master nodes.

**Comment by adduarte** [comment]
@2-face and @r3d3mpt10n , could you take a look at this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1818695
It seems that you might be running into another permutation of that issue. 
OpenShift uses address_pairs assigned to the FIP ports. DVR seems to have some problems handling that. (proably because the port shows as down).

**Comment by r3d3mpt10n** [comment]
Yeah, the issue with DVR is that it tries to populate the ARP entries on the DVR routers based on data in the Neutron DB. The problem with this is that it doesn't allow for the floating nature of the IP address. Since it could be on any one of the 3 masters, and Neutron can't possibly know which one. So the local DVR router on the compute node hosting the master with the FIP will work fine, since it's ARP entries will be populated by ARP who-has responses.

The port will always appear to be down, since Neutron can never really know where it is. ... Well, it could if we used actual ARP responses rather than relying on the DB, but I digress.

That's actually my bugzilla you linked there. We implemented a temporary solution for that particular BZ, but it wont be relevant here unfortunately. It was specifically for Octavia and Kuryr in that case. There was also another issue with DVR here: https://bugzilla.redhat.com/show_bug.cgi?id=1819055

I think the best bet is to just centralize the OpenShift router at this stage until the issues with DVR are resolved upstream in Neutron. You can easily do that:
```
openstack router set --disable OCP_ROUTER_NAME
openstack router set --centralized OCP_ROUTER_NAME
openstack router set --enable OCP_ROUTER_NAME
```

That should avoid any of the above mentioned issues.
