### ISSUE TITLE
IPI for vSphere: Support deployment to vSphere Resource Pool

### ISSUE THREAD

**Issue by lamw** [openshift/installer#3921]
# Version

```console
$ openshift-install version

4.5.2
built from commit 6336a4b3d696dd898eed192e4188edbac99e8c27
release image quay.io/openshift-release-dev/ocp-release@sha256:8f923b7b8efdeac619eb0e7697106c1d17dd3d262c49d8742b38600417cf7d1d
```

# Platform:
```
vSphere
```

# Method:
```
IPI
```

# What happened?

During the `create` install-config operation, it looks like the only option for where the OpenShift VMs are deployed to is at the root of the vSphere Cluster. For environments that leverage vSphere Resource Pools, it would be nice to be able to specify that, rather than having to move that after the fact. See screenshot below

![openshift-on-vmware-cloud-on-aws-4new](https://user-images.githubusercontent.com/602199/87853734-84c57d80-c8c1-11ea-8f56-fadbb51e5524.png)

# What you expected to happen?

List both top level vSphere Cluster but also any Resource Pools that maybe available for selection.

# Additional Details

I see that vSphere Terraform provider is being leveraged for the automation and Resource Pools is a supported option

**Comment by giannisalinetti** [comment]
This would be a great feature for IPI installations and I wonder why it is going stale. Please consider working on it, many customers that are adopting IPI on vsphere would love it!

**Comment by claudiotassini** [comment]
Confirmed same behaviour with openshift-install 4.6.4,

**Comment by styblope** [comment]
same problem here. See my [quick 4.7 patch](https://github.com/styblope/installer/wiki/Support-for-Resource-Pools-in-vSphere-IPI-OpenShift-installation) to get things done.

**Comment by jcpowermac** [comment]
@styblope please submit a PR, cc me and I will review.

**Comment by willhaines** [comment]
/remove-lifecycle stale

Still trying to work through issues with e2e-vsphere test.
