### ISSUE TITLE
gather: baremetal fails to collect logs when terraform fails

### ISSUE THREAD

**Issue by stbenjam** [openshift/installer#3927]
# What happened?

On baremetal, Ironic failed to come up which means terraform created the bootstrap but failed to create the masters.

# What you expected to happen?

Logs should've been collected

# How to reproduce it (as minimally and precisely as possible)?

While terraform is creating the masters, tear down the `ironic` service to simulate a failure.

I would've expected a log bundle to be created, we'd have to examine the code paths to see what happens when terraform itself fails, and whether we had enough information to collect IP's for install gather (we should be able to use the provisioning IP, since in this case it was far enough along to have it.)

**Comment by wking** [comment]
There's an Azure RFE ticket in Jira for this too
