### ISSUE TITLE
Openshift-install 4.5.2 - vSphere - destroy cluster fails

### ISSUE THREAD

**Issue by saintdle** [openshift/installer#3951]
# Version

Openshift-install 4.5.2

# Platform:
vSphere

IPI
# What happened?

running the following

dean@dean:~/ocp45$ openshift-install destroy cluster

FATAL Failed while preparing to destroy cluster: no platform configured in metadata

# What you expected to happen?

OCP cluster to be destroyed and vSphere virtual machines deleted

# How to reproduce it (as minimally and precisely as possible)?

As above, install to vSphere cluster was fine and cluster works, just removing fails

![image](https://user-images.githubusercontent.com/22192242/88323932-e00ccb00-cd1a-11ea-8544-a9d24d5f8f8b.png)
![image](https://user-images.githubusercontent.com/22192242/88323988-f155d780-cd1a-11ea-9a0d-2c10a52d7122.png)

**Comment by yigitpolat** [comment]
Same issue for Bare Metal installation as well.

During installation, 'openshift-install create ignition-configs' command creates metadata.json file without any platform keyword defined. However 'openshift-install destroy cluster' command requires platform to be defined.

Below screenshot shows both metadata.json file used during the Bare Metal installation and error received during the destruction process.

<img width="1034" alt="Screen Shot 2020-08-10 at 13 40 02" src="https://user-images.githubusercontent.com/15480459/89780473-2edba280-db1a-11ea-9733-c5d3044b954d.png">

**Comment by saintdle** [comment]
Running the Openshift-installer 4.5.3, the destroy cluster arguments work successfully.
