### ISSUE TITLE
primaryAvailabilitySetName usage on Openshift 4.3 manifests on IPI Installer for Azure

### ISSUE THREAD

**Issue by abudavis** [openshift/installer#3954]
Background: Since the Azure Norway East region does not yet support deployment into Azure availability zones and since RedHat doesn't yet support deployments into Azure availability sets for achieving high availability for the deployed nodes/VMs, I am wondering if there is a way to do this on Openshift 4.3 by editing the "manifests" generated by the terraform installer - https://github.com/openshift/installer/blob/5b318d79b79d41d0f78d948d98e50d60c5bad43b/pkg/asset/manifests/azure/types.go#L45-L50

Question: 1. What is the expected output of setting a "primaryAvailabilitySetName" in the manifest  file "cloud-provider-config.yaml" ? 
2. Is there an Azure API that the IPI installer would call which will create the azure availability set or tag the master and worker VMs during install into an existing azure availability set (defined externally by an Azure MVP)?
```
apiVersion: v1
data:
  config: "{\n\t\"cloud\": \"AzurePublicCloud\",\n\t\"tenantId\": \"redacted\",\n\t\"aadClientId\":
    \"\",\n\t\"aadClientSecret\": \"\",\n\t\"aadClientCertPath\": \"\",\n\t\"aadClientCertPassword\":
    \"\",\n\t\"useManagedIdentityExtension\": true,\n\t\"userAssignedIdentityID\":
    \"\",\n\t\"subscriptionId\": \"redacted\",\n\t\"resourceGroup\":
    \"dummycluster-hqpqp-rg\",\n\t\"location\": \"norwayeast\",\n\t\"vnetName\": \"dummycluster-hqpqp-vnet\",\n\t\"vnetResourceGroup\":
    \"dummycluster-hqpqp-rg\",\n\t\"subnetName\": \"dummycluster-hqpqp-worker-subnet\",\n\t\"securityGroupName\":
    \"dummycluster-hqpqp-node-nsg\",\n\t\"routeTableName\": \"dummycluster-hqpqp-node-routetable\",\n\t\"primaryAvailabilitySetName\":
    \"\",\n\t\"vmType\": \"\",\n\t\"primaryScaleSetName\": \"\",\n\t\"cloudProviderBackoff\":
    true,\n\t\"cloudProviderBackoffRetries\": 0,\n\t\"cloudProviderBackoffExponent\":
    0,\n\t\"cloudProviderBackoffDuration\": 6,\n\t\"cloudProviderBackoffJitter\":
    0,\n\t\"cloudProviderRateLimit\": false,\n\t\"cloudProviderRateLimitQPS\": 0,\n\t\"cloudProviderRateLimitBucket\":
    0,\n\t\"cloudProviderRateLimitQPSWrite\": 0,\n\t\"cloudProviderRateLimitBucketWrite\":
    0,\n\t\"useInstanceMetadata\": true,\n\t\"loadBalancerSku\": \"standard\",\n\t\"excludeMasterFromStandardLB\":
    null,\n\t\"disableOutboundSNAT\": null,\n\t\"maximumLoadBalancerRuleCount\": 0\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cloud-provider-config
  namespace: openshift-config
```

# Version
Openshift 4.3.28 on Azure (IPI)

# References
https://bugzilla.redhat.com/show_bug.cgi?id=1856551
Support for availability sets RFE: https://issues.redhat.com/browse/RFE-793.

**Comment by abhinavdahiya** [comment]
The file mentioned only modifies the configuration for k8s azure cloud provider . It does not affect the installer to create availability sets. For all information regarding this file options you are better suited to look into upstream documentation. Based on my initial search this field is useless for ipi based clusters as we do not use the available sets for our setup.

We do not intent to support availability sets for our ipi setup. So we do not provide options to interact with those. Your best path forward is to track the RFE you linked.

/close
