### ISSUE TITLE
openshift-install create cluster not working with the default options

### ISSUE THREAD

**Issue by jllado** [openshift/installer#3991]
# Version

```console
$ openshift-install version
./openshift-install 4.5.3
built from commit 01f5643a02f154246fab0923f8828aa9ae3b76fb
release image quay.io/openshift-release-dev/ocp-release@sha256:eab93b4591699a5a4ff50ad3517892653f04fb840127895bb3609b3cc68f98f3
```

# Platform:
openstack

# Please specify:
IPI

# What happened?
I tried to follow the steps from installation get started. And when I execute:
`./openshift-install create cluster` 

I always get the following error:
```
jllado@jllado-laptop:~/pruebas/openshift$ ./openshift-install create cluster
? SSH Public Key <none>
? Platform openstack
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Cluster ID": failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": no clouds.yaml file found
```
I've also tried with the clouds.yaml example from the docs. But then it fails with aut_url timeout. I don't know where to get that url.

# What you expected to happen?
Quickly create a cluster with the default options

**Comment by iganinja** [comment]
Same problem here

**Comment by iamemilio** [comment]
Hi, please make sure that your clouds.yaml file is valid, and in one of the expected locations. You can refer to [this section of the documentation](https://github.com/openshift/installer/tree/master/docs/user/openstack#openstack-credentials) for more information about it. If this doesn't resolve your problem, then please let us know.

**Comment by mrostamii** [comment]
Mine has occurred the error when I used filename `.config/openstack/clouds.yml` instead of the correct one which is `.config/openstack/clouds.yaml`.
In addition, I have had that problem with OKD(OpenShift Origin) [v4.7.0](https://github.com/openshift/okd/releases/tag/4.7.0-0.okd-2021-06-04-191031). It was ok with OpenShift Enterprise.
