### ISSUE TITLE
Bootstrap failed to complete on ovirt

### ISSUE THREAD

**Issue by godpusa** [openshift/installer#3993]
# Version

```console
$ openshift-install version
./openshift-install 4.5.0-0.okd-2020-07-29-070316
built from commit 699277bb61706731d687b9e40700ebf4630b0851
release image quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3
```

# Platform:
ovirt

# What happened?

./openshift-install create cluster --dir=/opt/okd --log-level=debug
always failed on ovirt.  ovirt storage domain type is FCP
error log :
INFO Waiting up to 20m0s for the Kubernetes API at https://api.adg-cluster.<base_domain>:6443... 
DEBUG Still waiting for the Kubernetes API: Get https://api.adg-cluster.<base_domain>:6443/version?timeout=32s: dial tcp 192.168.49.225:6443: connect: no route to host 
....
a log of "no route to host" here 
....
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.adg-cluster.<base_domain>:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 192.168.49.225:6443: connect: no route to host 
DEBUG Fetching Bootstrap SSH Key Pair...           
DEBUG Loading Bootstrap SSH Key Pair...            
DEBUG Using Bootstrap SSH Key Pair loaded from state file 
DEBUG Reusing previously-fetched Bootstrap SSH Key Pair 
DEBUG Fetching Install Config...                   
DEBUG Loading Install Config...                    
DEBUG   Loading SSH Key...                         
DEBUG   Using SSH Key loaded from state file       
DEBUG   Loading Base Domain...                     
DEBUG     Loading Platform...                      
DEBUG     Using Platform loaded from state file    
DEBUG   Using Base Domain loaded from state file   
DEBUG   Loading Cluster Name...                    
DEBUG     Loading Base Domain...                   
DEBUG     Loading Platform...                      
DEBUG   Using Cluster Name loaded from state file  
DEBUG   Loading Pull Secret...                     
DEBUG   Using Pull Secret loaded from state file   
DEBUG   Loading Platform...                        
DEBUG Using Install Config loaded from state file  
DEBUG Reusing previously-fetched Install Config    
INFO Pulling debug logs from the bootstrap machine 
DEBUG Added /tmp/bootstrap-ssh279212836 to installer's internal agent 
DEBUG Added /root/.ssh/id_rsa to installer's internal agent 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the private key is added to your authentication agent (ssh-agent) or specified with the --key parameter: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain 
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get https://api.adg-cluster.<base_domain>:6443/version?timeout=32s: dial tcp 192.168.49.225:6443: connect: no route to host

during the installation process, tmpvm , bootstrap vm and 3 master vm has been added. but there was no response when I  ping the bootstrap vm.

# What you expected to happen?

I can quickly install a default, non-customized, OKD cluster.

# How to reproduce it (as minimally and precisely as possible)?

```console
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
./openshift-install create cluster --dir=/opt/okd --log-level=debug
```

# Anything else we need to know?

ovirt version is 4.3.10. and ovrit's api works ok.

# References

- enter text here.

**Comment by bshephar** [comment]
Hi,

Do you have any other VM's on that same subnet? Are you able to ping those other VMs from the system you're running the installer on?

The error you're getting:
```
dial tcp 192.168.49.225:6443: connect: no route to host
```

It seems like there is no route between the system you're running the installer on, and the 192.168.49.225 network.

**Comment by godpusa** [comment]
Actually , there is a lot of vms in the 192.168.49.0/24 network,  and I can ping them successfully. I don't think the installer can attach the corresponding IP to the corresponding VM.

**Comment by bshephar** [comment]
Do you see any errors on the console of the VM at all?

So that address is the VIP. Assuming there are no errors on the console and you can see that it has booted into CoreOS. Can you SSH to the bootstrap node on the other IP address that it has? (I know you said that you can't ping it. But do you mean that you can't ping the VIP? In this case 192.168.49.225. It should have another IP as well.)

The other, non-VIP address will come from DHCP. So if you can't log in at all, maybe tcpdump from one of the other VM's on the same subnet to see if you're able to see the DHCP requests going out?

```
tcpdump -i any port 68 or port 69 -nevv
```

Do you have control of the DHCP server as well? tcpdump from the DHCP server would give you the best results there to see if the REQUEST and OFFER is coming through. 

You can also identify the interface attached to the VM and tcpdump that from the ovirt host the VM is running on. For example:

```
# virsh --readonly list --all
 Id   Name                        State
-------------------------------------------
 2    HostedEngine                running
 6    idm-server.lab.net     running
 64   ocp4-59xll-worker-0-mjq25   running
 85   ocp4-59xll-master-0         running
 92   osp16-Director              running
 93   ocp4-59xll-master-1         running
 94   ocp4-59xll-master-2         running
 95   ocp4-59xll-worker-0-vh47h   running
```

```
# virsh --readonly dumpxml 93
```

Look for:
```
    <interface type='bridge'>
      <mac address='56:6f:14:f3:00:03'/>
      <source bridge='Infra'/>
      <target dev='vnet9'/>
      <model type='virtio'/>
      <driver name='vhost' queues='4'/>
      <link state='up'/>
      <mtu size='9000'/>
      <alias name='ua-24182f86-5332-45b0-9f31-6069aa566345'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </interface>
```

Then we can tcpdump that interface. So in my case, vnet9:
```
# ip link show vnet9
366: vnet9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq master Infra state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:6f:14:f3:00:03 brd ff:ff:ff:ff:ff:ff
```

**Comment by godpusa** [comment]
I found out what the problem was.
My 192.168.49.0/24 network had DHCP enabled and the virtual machine automatically acquired an IP address before the installer assigned it, making it impossible to connect. I can ssh to the bootstrap's IP address assigned by DHCP.
Our DHCP is enabled by a layer 3 switch, is there any way for ovirt to disable DHCP?

**Comment by bshephar** [comment]
Nice!  You might be able to try vNIC filters: https://www.ovirt.org/develop/release-management/features/network/networkfilterparameters.html
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/virtualization_deployment_and_administration_guide/index#sect-Virtual_Networking-Applying_network_filtering

I know they can block DHCP requests coming INTO the VM network. I'm not too sure about egress DHCP though sorry.

**Comment by godpusa** [comment]
Hi, I have disabled all the dhcp servers in the lan.  this time , no ip address was assigned to the vms.  still the same error: "no route to host".

**Comment by EagleIJoe** [comment]
@godpusa, how long did you wait for the API? I have the no route to host until the API is completely up on the bootstrap machine. Then I get one "connection refused" and then I get API up.

**Comment by godpusa** [comment]
@EagleIJoe I waited 20 minutes and finally the installer made an error and quit.
