### ISSUE TITLE
Azure UPI 4.3 Fails- Timeout when deploying VMs

### ISSUE THREAD

**Issue by JonWoodlief** [openshift/installer#4001]
# Version

```console
$ openshift-install version
./openshift-install 4.3.31
built from commit 96253d3f2ed8da6f70ff6ad9f69d67b65c688889
release image quay.io/openshift-release-dev/ocp-release@sha256:6395ddd44276c4a1d760c77f9f5d8dabf302df7b84afd7b3147c97bdf268ab0f
```

# Platform:
Azure

UPI
using existing public DNS zone
No additional network restrictions or DNS zones

# What happened?
Following the documentation at-
https://github.com/openshift/installer/blob/master/docs/user/azure/install_upi.md

When we deploy the bootstrap using-
az group deployment create -g $RESOURCE_GROUP   --template-file "04_bootstrap.json"   --parameters bootstrapIgnition="$BOOTSTRAP_IGNITION"   --parameters sshKeyData="$SSH_KEY"   --parameters baseName="$INFRA_ID"

the machine fails to boot and throws the following error-
Deployment failed. Correlation ID: 74defff3-b547-4ca9-8e27-f91e2cd591c4. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OSProvisioningTimedOut",
        "message": "OS Provisioning for VM 'walmartcpat3-nh4q5-bootstrap' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. Also, make sure the image has been properly prepared (generalized).\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ \r\n * If you are deploying more than 20 Virtual Machines concurrently, consider moving your custom image to shared image gallery. Please refer to https://aka.ms/movetosig for the same."
      }
    ]
  }
}

# What you expected to happen?

The bootstrap to boot successfully and enter 'running' state without error

# How to reproduce it (as minimally and precisely as possible)?

Follow the documentation here exactly-
https://github.com/openshift/installer/blob/master/docs/user/azure/install_upi.md

We perform no network customizations. We follow the option to re-use an existing public DNS zone where applicable.

# Anything else we need to know?

This is happening in a very vanilla Azure test environment where we have full access. We are testing UPI installs for a production scenario. We've been able to re-use the service principal and public DNS zone from a failed UPI install to do a successful IPI install- so we know those two components should work.

We've tried this with both the latest 4.3 images of RHCOS, and also the latest dev releases of RHCOS. We have also tried this by re-using the images uploaded by a successful 4.3 IPI installation on this same Azure account.

this means we think we can rule out permissions, the image, and the DNS zone as a potential issue.

this is a test environment for us- so we're willing to give anything a try in the name of troubleshooting.

# References

None that I'm aware of

**Comment by ArunaLakmal** [comment]
Any Idea on this, I'm seeing the same issue with ARM templates as well as terraform.

**Comment by tsze-redhat** [comment]
The error msg above is kind of generic from Azure.
Please check all the environmental variables are set correctly (e.g. AZURE_REGION) and compare to the values set in install-config.yaml.

**Comment by ArunaLakmal** [comment]
You were correct, this was a generic error and not helpful for identifying the correct root cause of the issue. I was able to fix  it enabling the  serial console of the  vm  and it gave me the reason to the error. It was due to a failure of DNS record. I updated it and was able to provision the cluster. Thanks for the reply.

**Comment by tsze-redhat** [comment]
Glad your problem is resolved.
Good luck with your deployments.
