### ISSUE TITLE
Installer unable to build because https://gitlab.howett.net/go/plist.git seems down at the moment.

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/installer#4013]
Hi,
I was trying to rebuild the 4.5.4 installer (because I'm using libvirt) and go seems to hang trying to download this module:

```
      `-git,278462 ls-remote -q origin
          `-git-remote-http,278464 origin https://gitlab.howett.net/go/plist.git
```
Perhaps go.sum should point to the github mirror instead?
It was working two hours ago and I hadn't noticed but now the 4.5.x rebuild doesn't finish and hangs there..

**Comment by cfergeau** [comment]
This does not seem to be a direct dependency of the installer, is this still happening? could you share the full build error?
