### ISSUE TITLE
[RFE] installer should manage node network interface MTU for UPI baremetal installations

### ISSUE THREAD

**Issue by aneagoe** [openshift/installer#4019]
# Version
```console
$ openshift-install version
openshift-install 4.5.0-0.okd-2020-07-29-070316
```

# Platform:
baremetal
* UPI

# What happened?

The installer does not seem to provide a way for configuring network interface MTU of the hosts that are to be provisioned (for either controlPlane or worker types). https://github.com/openshift/installer/pull/3896 seems to try and address this point, but only for OpenStack. Also, https://access.redhat.com/solutions/5092381 references a solution for addressing this in machine config; presumably one can manually add the suggested fix in the install folder before generating the ignition files (ie `99_openshift-machineconfig_99-[master|worker]-mtu.yaml`).
Since SDN MTU cannot be changed after installation, this has to be correctly configured at install time.

# What you expected to happen?

Since installer is in charge of generating the machine configs for master/worker nodes, it should also be in charge of managing the network interface MTU of the nodes.

# References

- https://github.com/openshift/installer/pull/3896
- https://access.redhat.com/solutions/5092381

**Comment by vap0rtranz** [comment]
Doesn't the network manifest already honor MTU settings at install time?

```
 openshiftSDNConfig:
      mtu: 1450
```

Looks to be an option since 4.3 according to Alex's blog:
[https://www.openshift.com/blog/advanced-network-customizations-for-openshift-install](https://www.openshift.com/blog/advanced-network-customizations-for-openshift-install)

**Comment by aneagoe** [comment]
@vap0rtranz that's the SDN MTU which *can* indeed be set. However, the node's MTU (which is a pre-requisite for the SDN MTU) is not handled anywhere. Please check the hint in the reference (RH solution to this).

**Comment by vap0rtranz** [comment]
@aneagoe ah, understood.

Checking around, it looks like folks are:

1) ssh'ing into CoreOS during install and setting Node MTU via NetworkManager
2) creating network-scripts to set the Node MTU (can be pushed via MachineConfig or ssh)

Neither are pre-install nor ideal ... so looking around.
