### ISSUE TITLE
AWS ap-east-1 Hong Kong region is missing in the installation step

### ISSUE THREAD

**Issue by nebula0248** [openshift/installer#4061]
**# Version**
./openshift-install 4.5.6
built from commit baccbcfbbeed464b45a33f00ced17dfe8134fd7b
release image quay.io/openshift-release-dev/ocp-release@sha256:0147ab7622969c1cde71e8e5eb8796e8245137fdbf3a5cae63017189a9060f86

**# Platform:**
aws, IPI

**# What happened?**
AWS has a region in Hong Kong (ap-east-1), and the OpenShift installer does not provide support and any option for us to select ap-east-1. Please add it back as we have customers who want to deploy OpenShift 4 at AWS Hong Kong region.

**# What you expected to happen?**
The installer allow us to select ap-east-1 as the deployment region.

**# How to reproduce it (as minimally and precisely as possible)?**
Run ./openshift-installer create install-config, then select AWS as the platform, and see there is no ap-east-1 in the region list.

**# References**
https://github.com/openshift/installer/search?q=ap-southeast-1&unscoped_q=ap-southeast-1
(This is the search page that shows all currently supported region, but without ap-east-1)

**Comment by abhinavdahiya** [comment]
The terminal prompts do not show all the regions, mostly because those regions do not have AMI published by OS team. But the installer itself supports those regions if you use a use-provided install config. see https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations

```
$ mkdir test-cluster
$ cat ap-east-1-install-config.yaml
apiVersion: v1
baseDomain: '<base domain>'
controlPlane:
  name: master
  replicas: 3
compute:
- name: worker
  replicas: 3
metadata:
  name: test-cluster-1
platform:
  aws:
    region: ap-east-1
pullSecret: '<pull secret>'
sshKey: 'ssh key'

$ cp ap-east-1-install-config.yaml test-cluster/install-config.yaml
$ openshift-install --dir test-cluster create cluster
```

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/issues/4061#issuecomment-675592566
@nebula0248 that should work, if it doesn't feel free to re-open


/close
