### ISSUE TITLE
Diagram Improvements

### ISSUE THREAD

**Issue by GZasman** [openshift/installer#4065]
# Version 4

```console
$ openshift-install version
4.3
```

# Platform:

# What happened?

Enter text here. Thanks for doing this awesome work. The three ELB's on the diagram are they all ALB's? Maybe you can make that clearer and use the ALB icons. Could you also please annotate the OpenShift components e.g. master nodes, worker node, etcd etc?

Thanks In Advance

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
@GZasman did you mean https://raw.githubusercontent.com/openshift/installer/28f344b512699588f3d64ba79abb4b6d606f0769/docs/user/aws/images/install_upi.svg ??

- all our LBs are layer-4 NLB or classic ELB, none of them are ALBs
- the diagram is already very busy and putting OpenShift roles in infra diagram seemed like too much.

But we are open to any improvements you have and I can try to review those changes too.

**Comment by GZasman** [comment]
Awesome that was quick and thanks Abhinav. Looks like we both work for IBM.


  *   All our LBs are layer-4 NLB or classic ELB, none of them are ALBs.
If you want you could use the NLB AWS ICON for clarity instead of the generic ELB icon.
[cid:image001.png@01D67626.D2262B80]

  *   The diagram is already very busy and putting OpenShift roles in infra diagram seemed like too much.
Makes sense. Maybe you could possibly just show which are the master, etcd and worker nodes.

Thanks
Gary
