### ISSUE TITLE
OpenStack IPI install fails during bootstrap due to availability zone name

### ISSUE THREAD

**Issue by yussufsh** [openshift/installer#4069]
# Version

```
# ./openshift-install version
./openshift-install 4.6.0-0.nightly-ppc64le-2020-08-18-034628
built from commit c5495ccf4b1b784f10d073f1e7aaa12189be051d
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:2b016d9d663693551c4958d27e3613dcfb7f8691e58acab3c474538340be8134
```

# Platform:
openstack IPI

# What happened?

Bootkube process loops endlessly to create the worker machineset due to the availability zone name having uppercase letters.

```
Aug 19 09:57:13 yus-pt67t-bootstrap bootkube.sh[2565]: [#12247] failed to create some manifests:
Aug 19 09:57:13 yus-pt67t-bootstrap bootkube.sh[2565]: "99_openshift-cluster-api_worker-machineset-0.yaml": failed to create machinesets.v1beta1.machine.openshift.io/yus-pt67t-worker-PowerKVM -n openshift-machine-api: MachineSet.machine.openshift.io "yus-pt67t-worker-PowerKVM" is invalid: metadata.name: Invalid value: "yus-pt67t-worker-PowerKVM": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

# What you expected to happen?

Worker machines should get created without any error related to the metadata name.

# How to reproduce it (as minimally and precisely as possible)?

1. Use availability zone name in install-config having at least one capital letter.
2. Run the create cluster command.

# Anything else we need to know?

This is on top of https://github.com/openshift/installer/pull/4000

# References

https://github.com/openshift/installer/pull/4000

Need to use lowercase name in machineset.

**Comment by pierreprinetti** [comment]
Tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1870082
