### ISSUE TITLE
Complete the Availability Zones support for OpenStack

### ISSUE THREAD

**Issue by ITD27M01** [openshift/installer#4084]
# Version

```console
$ openshift-install version
4.6
```

# Platform:
OpenStack
IPI

# What happened?
Current support [1] is partially implemented because Neutron objects are provisioned elsewhere. I'm talking about openshift-install and IPI where we need to specify the availability zone. As you know, the openshift-install uses Terraform and its manifests to deploy bootstrap and master nodes: https://github.com/openshift/installer/tree/master/data/data/openstack.

The Neutron objects are router: https://github.com/openshift/installer/blob/master/data/data/openstack/topology/private-network.tf#L142 and network: https://github.com/openshift/installer/blob/master/data/data/openstack/topology/private-network.tf#L15

The sync can be done by availability_zone_hint (https://github.com/ITD27M01/openshift-installer-patchset/blob/master/4.5-okd-fcos/0002-AZ-support-for-network-release-4.5.patch) parameter which does not force the scheduling but only suggests the location - if there is no availability zone with such a name, the scheduler will provision router or network elsewhere. The current "zones" list can be copied to availability_zone_hint list to complete the OpenStack Availability Zone support.

# What you expected to happen?
OpenStack Availability zone support for openshift-install installer.

# References
[1] https://github.com/openshift/installer/pull/3918
[2] https://github.com/openshift/installer/issues/2391

**Comment by klaphi** [comment]
We have the same requirements.

**Comment by pierreprinetti** [comment]
Thank you for this issue.

This is now internally tracked in https://issues.redhat.com/browse/OSASINFRA-2160. Since our board is not public (yet), I am keeping this issue open for visibility.

**Comment by usamaahmadkhan** [comment]
Any news on this guys? We are unable to deploy a multi AZ cluster because of this :/

**Comment by pierreprinetti** [comment]
We introduced support for Nova zones in 4.6. With 4.8 we introduce support for Cinder zones. Neutron AZs are unfortunately not supported in IPI yet. You might consider installing on top of pre-created infrastructure with UPI --> https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md

**Comment by EmilienM** [comment]
@usamaahmadkhan I think you could deploy a multi AZ cluster if you deploy on top of a Provider network. See doc:
https://github.com/openshift/installer/blob/master/docs/user/openstack/provider_networks.md
