### ISSUE TITLE
From where we can get the "create-templates-and-vms.yml" playbook required for the UPI based installation of RHV.

### ISSUE THREAD

**Issue by vpagar1** [openshift/installer#4165]
I am following the steps given in "https://github.com/openshift/installer/blob/master/docs/user/ovirt/install_upi.md=" and trying to deploy the UPI cluster but I am not able to find any playbook which used in the above document. From where we can get the playbooks? 

I checked the RHV manager as well, but the playbook is not present there, so do we need to create it manually? or we can get it from somewhere?

**Comment by stobias123** [comment]
https://github.com/openshift/installer/blob/master/docs/user/ovirt/install_upi.md#getting-ansible-playbooks
