### ISSUE TITLE
Is it possible to use the installer to associate the private hosted zone created by the installer with multiple VPCs?

### ISSUE THREAD

**Issue by HenriAW** [openshift/installer#4225]
In our installation of OpenShift we require the private hosted zone created by OpenShift to be associated with multiple VPCs. Without manually adding an association the installer cannot install and gets stuck in trying to talk to the kubernetes API before deprovisioning itself.
Is this extra association something that's possible with the installer, or is this something that needs to be done manually? 
If this is not possible, is it possible for OpenShift to use an existing private hosted zone?
Thanks!

**Comment by abhinavdahiya** [comment]
afaik currently the installer only accepts subnets from a single VPC, therefore any private dns zone created by the installer should allow for resolution from all the machines created in those subnets.

So can you explain your setup in a little more detail and how you think it causes the installer to fail.
