### ISSUE TITLE
unable to use GCP without using a service account key

### ISSUE THREAD

**Issue by errordeveloper** [openshift/installer#4232]
# Version

```console
$ openshift-install version
built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
release image quay.io/openshift/okd@sha256:5fd1fe9707a9a4f53c8ccafad0cf44824a3a0b51e197f3fbc98d0884a9ddcf4f
```

# Platform: GCP IPI

# What happened?

Unreadable error when GCP is selected.

```
$ openshift-install create install-config --dir cluster-8 --log-level debug
DEBUG OpenShift Installer 4.5.0-0.okd-2020-09-18-202631 
DEBUG Built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8 
DEBUG Fetching Install Config...                   
DEBUG Loading Install Config...                    
DEBUG   Loading SSH Key...                         
DEBUG   Loading Base Domain...                     
DEBUG     Loading Platform...                      
DEBUG   Loading Cluster Name...                    
DEBUG     Loading Base Domain...                   
DEBUG     Loading Platform...                      
DEBUG   Loading Pull Secret...                     
DEBUG   Loading Platform...                        
DEBUG   Fetching SSH Key...                        
DEBUG   Generating SSH Key...                      
? SSH Public Key /Users/ilya/.ssh/id_rsa.pub
DEBUG   Fetching Base Domain...                    
DEBUG     Fetching Platform...                     
DEBUG     Generating Platform...                   
? Platform gcp
INFO Credentials loaded from gcloud CLI defaults  
? Project ID cilium-dev (cilium-dev)
? Region europe-west1
DEBUG   Generating Base Domain...                  
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": could not retrieve base domains: Get https://dns.googleapis.com/dns/v1/projects/cilium-dev/managedZones?alt=json&prettyPrint=false: context canceled 
$
```

Having found https://github.com/openshift/installer/issues/3044, I figured I should try using a service account key.

With the service account key, I got a very different error:
```
$ GOOGLE_CLOUD_KEYFILE_JSON=~/Downloads/cilium-dev-ff448990c25d.json ../openshift-install create install-config --dir "${CLUSTER_NAME}"
? SSH Public Key /Users/ilya/.ssh/id_rsa.pub
? Platform gcp
INFO Credentials loaded from environment variable "GOOGLE_CLOUD_KEYFILE_JSON", file "/Users/ilya/Downloads/cilium-dev-ff448990c25d.json" 
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": failed to get projects: googleapi: Error 403: Cloud Resource Manager API has not been used in project 171187002445 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=171187002445 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
$
```

I was able to proceed once I enabled Resource Manager API, but not without `GOOGLE_CLOUD_KEYFILE_JSON`.

I suspect `gcloud` credentials no longer work properly.

# What you expected to happen?

Clearer error messages.

**Comment by tsze-redhat** [comment]
Did you set the variable export GOOGLE_CREDENTIALS=<your-service-account-json> before your run the installer?
This needs to be set every time you start a terminal or set in bash_profile.

**Comment by errordeveloper** [comment]
@tsze-redhat I didn't set `GOOGLE_CREDENTIALS`, what is it supposed to be set to exactly?

**Comment by tsze-redhat** [comment]
Set it to your service account json like
GOOGLE_CREDENTIALS=service_account.json

**Comment by errordeveloper** [comment]
@tsze-redhat as you see above, I did used `GOOGLE_CLOUD_KEYFILE_JSON` (which is equivalent to `GOOGLE_CREDENTIALS` in my understanding). However, in my understanding, one should also be able to use `openshift-install` without setting either of these environment variables, and in that case it is meant to use same credentials `gcloud` uses.

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/tree/master/docs/user/gcp#gcp-project-setup

We clearly document that we require service account key . We do not support using gcloud for crendential backend. We can use the credentials used by gcloud only after you run https://cloud.google.com/sdk/gcloud/reference/auth/application-default to allow local applications to use your gcloud credentials.

**Comment by errordeveloper** [comment]
Ok, so why isn't the error message clearer?
The output clearly states:
```
INFO Credentials loaded from gcloud CLI defaults  
```
And after that it lists my projects etc, so I didn't think anything is wrong with the auth.
I have to use a service account key, or run `gcloud auth application-default login`, I'm happy to do either, I just wish it was clearer from the start. Surely a few checks can be easily implemented to improve the user experience.

**Comment by errordeveloper** [comment]
@abhinavdahiya I also understand that you have documented this clearly in https://github.com/openshift/installer/blob/master/docs/user/gcp/iam.md, but I don't see the same when you look at 
 https://docs.openshift.com/container-platform/4.2/installing/installing_gcp/installing-gcp-account.html. And these docs are very long anyway, you cannot expect people to find such info unless it's highlighted somehow.

**Comment by errordeveloper** [comment]
OK, so I just tested `gcloud auth application-default login`, and it doesn't actually work either. Service account key appears to be the only auth method that actually works.

**Comment by tsze-redhat** [comment]
I have created this bugzilla to improve our user facing documentation:
https://bugzilla.redhat.com/show_bug.cgi?id=1912452

If there is other problem installing a cluster, please open a new thread. Thanks.

**Comment by matihost** [comment]
For historical reference:

As of OKD 4.12
it is still unclear that GSA key file path provided via GOOGLE_CREDENTIALS env variable is the only option to move forward with installer.
Aka
```
export GOOGLE_CREDENTIALS=/path/to/gsa/key/file.json
openshift-installer .....
```

Two improvements are nice to be there:

* Getting `INFO Credentials loaded from gcloud CLI defaults` is missleading as it works for some steps for openshift-installer but later getting `context canceled`.
It would be nice if debug logs could show what actually is called (like terraform TF_LOG debug shows beautifully) are made to GCP API (with hidden token ofc)



* `INFO Credentials loaded from gcloud CLI defaults` does not work.
as for example: 
```
curl -H "Authorization: Bearer `gcloud auth print-access-token`" https://dns.googleapis.com/dns/v1/projects/PROJECT/managedZones?alt=json&prettyPrint=false
```   does work.
