### ISSUE TITLE
RHCOS Vmware image not meeting security compliance rules

### ISSUE THREAD

**Issue by noushi** [openshift/installer#4233]
Hello,

# Version

```
4.5
```

# Platform:

* vsphere

* IPI

# What happened?

One of our customers is failing the security compliance check due to the RHCOS image lacking VM hardening options.

The security report mentions the following VM options that should be set:
- isolation.device.connectable.disable
- isolation.device.edit.disable
- isolation.tools.copy.disable
- isolation.tools.diskShrink.disable
- isolation.tools.diskWiper.disable
- isolation.tools.getCreds.disable
- isolation.tools.guestDnDVersionSet.disable
- isolation.tools.hgfsServerSet.disable
- isolation.tools.memSchedFakeSampleStats.disable
- isolation.tools.paste.disable
- isolation.tools.vmxDnDVersionGet.disable
- tools.guestlib.enableHostInfo

# What you expected to happen?

These options should be set in order to meet corporate security compliance.

# How to reproduce it (as minimally and precisely as possible)?

The RHCOS image that is used during IPI lacks these.

**Comment by abhinavdahiya** [comment]
I think you should open this with [openshift/os](https://github.com/openshift/os/issues/new/choose) repo. The installer does not create or publish these images.

/close

**Comment by noushi** [comment]
> I think you should open this with [openshift/os](https://github.com/openshift/os/issues/new/choose) repo. The installer does not create or publish these images.
> 
> /close

Thank you. 
That's the repo I've been looking for.
