### ISSUE TITLE
Bootstrap and Master Nodes on continuous loop with multiple attemps

### ISSUE THREAD

**Issue by AvRajath** [openshift/installer#4263]
# Version

```console
$ openshift-install version
./openshift-install 4.5.9
built from commit 0d5c871ce7d03f3d03ab4371dc39916a5415cf5c
release image quay.io/openshift-release-dev/ocp-release@sha256:7ad540594e2a667300dd2584fe2ede2c1a0b814ee6a62f60809d87ab564f4425
```

# Platform:
baremetal
* UPI (semi-manual installation on customised infrastructure)

# What happened?
Cluster details:
Control planes on the baremetal and worker on baremetal. But the bootstrap is running on the ESXi server which is on the same network. 

After i launch my boot strap and control nodes i can see this message for boot strap:

# ~/openshift-install --dir ~/ocp-install wait-for bootstrap-complete --log-level=debug
DEBUG OpenShift Installer 4.5.9
DEBUG Built from commit 0d5c871ce7d03f3d03ab4371dc39916a5415cf5c
INFO Waiting up to 20m0s for the Kubernetes API at https://api.lab.ocp.lan:6443...
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.ocp.lan:6443/version?timeout=32s: EOF

And on the Control plane nodes i can see the error as seen below image:
![image](https://user-images.githubusercontent.com/54664782/95780011-c3b07700-0ce8-11eb-9e2f-fe8907b840e8.png)

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Expected it to boot up succesfully.

# How to reproduce it (as minimally and precisely as possible)?

* Generated ignition files and uploaded it to my http server
* Entered the kernel commands in the kernel command line during boot.
* The image is pulled and the system restarts and starts showing these errors.

```console
$ your-commands-here
```

# Anything else we need to know?

# References

- enter text here.

**Comment by AvRajath** [comment]
Any update?

**Comment by AvRajath** [comment]
my HAProxy status:

![image](https://user-images.githubusercontent.com/54664782/95850433-75de5200-0d6e-11eb-9234-7d1510279df3.png)

**Comment by RobyYasirAmri** [comment]
i also experienced the same thing, is there any solution regarding this problem?

**Comment by AvRajath** [comment]
IDK how but i just redid the whole thing and left the cluster for 12 hours straight and suddenly everything was up. Dont know what was the issue. I really think the response on the Git should improve from redhat
