### ISSUE TITLE
bootstrap ignition file its running in loop and starting with emergency mode  on bootstrap server

### ISSUE THREAD

**Issue by darpan91** [openshift/installer#4310]
We have started with OKD 4.5.0 Openshift version on RHCOS 4.5.2 & RHEL 7.8 (service server) Operating system . we are planning to create 3 master and 2 worker node.

We have created Service server (Helper node) with RHEL OS.
Ignition files(bootstrap ,master and worker)  has been created on  Same server.

While running kernel command with bootstrap ignition file its running in loop and starting with emergency mode  on bootstrap server .
![bootstrap node error](https://user-images.githubusercontent.com/65757312/97271492-a1753800-1856-11eb-9ad6-f51d4a880970.JPG)
 We are unable to boot the bootstrap node .

Attached error screenshot . Please help us to resolve the issue

**Comment by abhinavdahiya** [comment]
Please reach out to [openshift/os](https://github.com/openshift/os/issues/new) regarding booting RHCOS instance with ignition.
