### ISSUE TITLE
Expose InstallConfig type and validations as a module

### ISSUE THREAD

**Issue by carbonin** [openshift/installer#4330]
In [OpenShift's Assisted Installer](https://github.com/openshift/assisted-service) and, if I understand correctly, to some degree [HyperShift](https://github.com/openshift-hive/hypershift-installer) we have use-cases which rely on generating or composing an install config at runtime.

I understand that the installer is primarily a command line tool, but could the structure of the module change (possibly by adding a sub-module) such that other projects could get access to the canonical `InstallConfig` type and it's associated validations?

In particular, the use case I'm trying to solve is one where the assisted installer builds an install config from (in part) user-provided data in our cloud.redhat.com service. We would like to be able to validate that config before shipping it off to a node where it could fail the installation process.

cc @romfreiman @ironcladlou @csrwng

**Comment by staebler** [comment]
Are there blockers that are keeping you from vendoring the installer package as is and importing the types and validation packages? Or is this an ask to make vendoring easier by separating out only the packages for which you have a use?

**Comment by carbonin** [comment]
The issue is with how complicated the dependencies of the installer are. The effort involved in maintaining the module overrides that my project wouldn't otherwise need outweighs just copying in the types (or some compatible struct I can deserialize into).

Generally I think the types and validations could be a useful API outside of all of the other functionality of the installer.

**Comment by staebler** [comment]
I generally agree that it would be useful to have the API as a separate module. However, I do not expect that it would be a super simple undertaking to do. That is why I was asking about the impact to your team. I doubt that it is something that would make it onto the installer team's workload in the short term. I know that the Hive team has some desire to separate out parts of the installer module into smaller modules that would be easier for Hive to consume as well. Perhaps if you combine forces, you could demonstrate enough need for this work to compel it.

**Comment by ironcladlou** [comment]
>Are there blockers that are keeping you from vendoring the installer package as is and importing the types and validation packages? Or is this an ask to make vendoring easier by separating out only the packages for which you have a use?

Just to clarify, and I hope someone will correct me if I'm confused about how they work in this case, but the problem is that with Go modules we can't depend on a subpackage (e.g. the api package) unless that package is a nested module. This means that to get the api package (which itself has almost no dependencies, which you'd expect for an api), one must declare a dependency on the base installer module itself, thus bringing in _all of the installer's dependencies_ transitively.

**Comment by staebler** [comment]
> > Are there blockers that are keeping you from vendoring the installer package as is and importing the types and validation packages? Or is this an ask to make vendoring easier by separating out only the packages for which you have a use?
> 
> Just to clarify, and I hope someone will correct me if I'm confused about how they work in this case, but the problem is that with Go modules we can't depend on a subpackage (e.g. the api package) unless that package is a nested module. This means that to get the api package (which itself has almost no dependencies, which you'd expect for an api), one must declare a dependency on the base installer module itself, thus bringing in _all of the installer's dependencies_ transitively.

@ironcladlou You are not confused. That is what will happen. And, yes, that is a large burden on a codebase that just wants the API.
