### ISSUE TITLE
How to identify which commit matches the exact revision of the installer (4.y.z) in a specific branch (release-4.y)

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/installer#4351]
This is related to :+1: 
https://github.com/openshift/installer/issues/4332

because openshift on libvirt requires a rebuild of the installer, the introduction of non-backward compatible changes broke installs of OCP 4.5 on Libvirt for almost a week (Oct 28th to Nov 5th 2020).

This happens because a 4.y.z version of the binary installer gets pulled down but the -rebuild- happens using master from release-4.5 since there are no tags that say 'this commit is for 4.5.17'.

It would be convenient to have a table that matches versions to branch commits, e.g:
commit <bblablabla> is the release of 4.5.17

perhaps tags would be sufficient but right now there aren't any that are useful:
```
$ git branch
  master
  release-4.4
* release-4.5
$ git tag
unreleased-master
v0.1.0
v0.10.0
v0.10.1
v0.11.0
v0.12.0
v0.13.0
v0.13.1
v0.14.0
v0.15.0
v0.16.0
v0.16.1
v0.2.0
v0.3.0
v0.4.0
v0.5.0
v0.5.0-master
v0.6.0
v0.7.0
v0.7.0-master
v0.8.0
v0.8.0-master
v0.9.0
v0.9.0-master
v0.9.1
```

**Comment by ElCoyote27** [comment]
@luisarizmendi FYI

**Comment by staebler** [comment]
This is not something that we are going to do. You can get the commit used for a release from the release images.

For example, you can use the following command to get the appropriate commit to use for 4.5.17.
```
$ oc adm release info 4.5.17 --commit-urls | grep -E "\sinstaller\s"
  installer                                      https://github.com/openshift/installer/commit/c01623963a11f3c58cdb740c0a05a828dab2db50
```

**Comment by ElCoyote27** [comment]
@staebler Thanks. I didn't know about the oc adm command.. but how do you get that without having a working OCP cluster as a pre-requisite? I'd need this commit ahead of time in order to be able to rebuild the installer to deploy OCP.. Sounds like a little like a chicken and egg problem, don't you think?

**Comment by staebler** [comment]
> @staebler Thanks. I didn't know about the oc adm command.. but how do you get that without having a working OCP cluster as a pre-requisite? I'd need this commit ahead of time in order to be able to rebuild the installer to deploy OCP.. Sounds like a little like a chicken and egg problem, don't you think?

You do not need an OCP cluster in order to run that command.
