### ISSUE TITLE
[Openstack UPI] Openstack server group error occurs due to os-api-version

### ISSUE THREAD

**Issue by gyohuangxin** [openshift/installer#4374]
# Version

```console
$ openshift-install version
./openshift-install 4.6.1
built from commit ebdbda57fc18d3b73e69f0f2cc499ddfca7e6593
release image quay.io/openshift-release-dev/ocp-release@sha256:d14e2a166a2889633850f4bb472e6803c6408622316ffe63d21a68f068eb4bc9
```

# Platform:

Openstack (os api version: 2.72)

UPI

# What happened?

Refer to: https://github.com/openshift/installer/blob/9be316bc89f560653e3ad07cde7a716bf938cf6d/upi/openstack/control-plane.yaml#L45

If it's the second time to do Openstack UPI on an Openstack which OS_COMPUTE_API_VERSION=2.72, server group error will occur as below.
`The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-ecc9a588-fe38-4ac2-89da-88ccd48bb045)`

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
/label platform/openstack

Hi @gyohuangxin, thanks for the report. Just to make sure I understand, with OpenStack Stein (micro-version 2.72), you get the above error when re-running the `control-plane.yaml` playbook?

**Comment by gyohuangxin** [comment]
> /label platform/openstack
> 
> Hi @gyohuangxin, thanks for the report. Just to make sure I understand, with OpenStack Stein (micro-version 2.72), you get the above error when re-running the `control-plane.yaml` playbook?

Yes, failed to re-run `openstack server group list -f json -c ID -c Name` , because the previous record has the key `policies`. Hence, we used `openstack --os-compute-api-version=2.15 server group list -f json -c ID -c Name`.
