### ISSUE TITLE
dns names for etcd urls cannot be resolved

### ISSUE THREAD

**Issue by deads2k** [openshift/installer#440]
The hostname plus dns suffix in endpoints is insufficient to get a working etcd connection.

After merging the etcd endpoints and wiring the operators to consume the information (plus https://github.com/openshift/cluster-openshift-apiserver-operator/pull/33), we still fail to access etcd.  Debugging the daemonset, `oc -n openshift-apiserver debug daemonset.apps/apiserver`, will show 
```
sh-4.2# nslookup test1-etcd-0.tt.testing
;; reply from unexpected source: 10.2.0.6#53, expected 10.3.0.10#53
```

It looks like we'll either be blocked until DNS/SDN functions properly or until the endpoint can provide a working IP address.

@abhinavdahiya @aaronlevy @mfojtik @smarterclayton @sttts @ironcladlou

**Comment by deads2k** [comment]
There's a known workaround that I ran on my master0 as root

```
The DNS issue is fixed. The cause is flannel using the bridge to route pod traffic and the bridge does not participate in iptables if routed locally.
The fix is to force the cni0 bridge to use iptables:
`sysctl -w net.bridge.bridge-nf-call-iptables=1`
And if the above command fails, then ensure the kernel module is loaded:
`modprobe br_netfilter`
```

**Comment by deads2k** [comment]
@mfojtik now I appear to have a bad ca cert

**Comment by abhinavdahiya** [comment]
@deads2k can you provide details around how you are running this, so that we can try to reproduce this.

**Comment by crawford** [comment]
@deads2k why did we merge that change into the installer if it wasn't sufficient?

**Comment by deads2k** [comment]
> @deads2k why did we merge that change into the installer if it wasn't sufficient?

It was necessary (we do need an endpoints object).  Lack of sufficiency wasn't obvious until we tried to hang the entire (net new) functionality together.  I don't see anything wrong with step-wise refinement in a direction we know we need to go.

**Comment by crawford** [comment]
>  Lack of sufficiency wasn't obvious until we tried to hang the entire (net new) functionality together. I don't see anything wrong with step-wise refinement in a direction we know we need to go.

We would much rather see all of this working together in a development setup before beginning to merge the necessary components. That will require you to build development images and wire everything together yourself rather than iterating in the installer repo and waiting for CI/CD to make available the pieces needed for testing. The team has enough work to tackle on their own and having to stop and review all of these iterations is very time consuming.

**Comment by crawford** [comment]
I believe this has been fully addressed at this point.

/close
