### ISSUE TITLE
openshift-install failed to install OCP 4.6 using libvirt IPI and Kubernetes API is not up

### ISSUE THREAD

**Issue by pratham-m** [openshift/installer#4418]
# Version
```console
$ openshift-install version
openshift-install unreleased-master-3761-gdb0f93089a64c5fd459d226fc224a2584e8cfb7e-dirty
built from commit db0f93089a64c5fd459d226fc224a2584e8cfb7e
release image registry.svc.ci.openshift.org/origin/release:4.5
```
Note: openshift-install binary is built using **release-4.6** branch, but still shows **release:4.5** in output

# Platform: libvirt IPI

# What happened?

Bootstrap failed to complete while "waiting for Kubernetes API" to come up.
[openshift_install.log](https://github.com/openshift/installer/files/5597010/openshift_install.log)

# What you expected to happen?

Kubernetes API should come up before timeout and installation should proceed, to successfully create the cluster.

# How to reproduce it (as minimally and precisely as possible)?

Clone the repository with release-4.6 branch and then,
```console
$ TAGS=libvirt hack/build.sh 
$ cp ./bin/openshift-install /usr/local/bin/
$ openshift-install --dir=/root/ipi/c3 create install-config
$ openshift-install --dir=/root/ipi/c3 create manifests
$ export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/openshift-release-dev/ocp-release:4.6.1-ppc64le
$ export OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE=https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.6/latest/rhcos-4.6.1-ppc64le-qemu.ppc64le.qcow2.gz
$ openshift-install create cluster --dir=/root/ipi/c3 --log-level=debug
```

# Anything else we need to know?
Bootstrap journals logs attached.
[approve-csr.log](https://github.com/openshift/installer/files/5597751/approve-csr.log)
[bootkube.log](https://github.com/openshift/installer/files/5597752/bootkube.log)
[crio.log](https://github.com/openshift/installer/files/5597753/crio.log)
[crio-configure.log](https://github.com/openshift/installer/files/5597754/crio-configure.log)
[ironic.log](https://github.com/openshift/installer/files/5597755/ironic.log)
[kubelet.log](https://github.com/openshift/installer/files/5597756/kubelet.log)
[master-update-bmh.log](https://github.com/openshift/installer/files/5597757/master-update-bmh.log)
[release-image.log](https://github.com/openshift/installer/files/5597759/release-image.log)

```console
$ virsh version
Compiled against library: libvirt 6.0.0
Using library: libvirt 6.0.0
Using API: QEMU 6.0.0
Running hypervisor: QEMU 2.12.0
```

# References

Tried troubleshooting using https://github.com/openshift/installer/blob/release-4.6/docs/user/troubleshooting.md#kubernetes-api-is-unavailable but no success.
[etcd-master-0.txt](https://github.com/openshift/installer/files/5597042/etcd-master-0.txt)

**Comment by staebler** [comment]
As you have seen, if you build from the release-4.6 branch, the binary will use an OpenShift 4.5 release image. You can explicitly use an OpenShift 4.6 release image by setting the OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE environment variable when running the binary.

https://github.com/openshift/installer/blob/master/docs/dev/alternative_release_image_sources.md#controlling-the-content

**Comment by pratham-m** [comment]
@staebler thanks for the reply.
Understood about the OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE environment variable.

Regarding below error  
> waiting for the Kubernetes API: Get \"https://api.ocp3.redhat.com:6443/version?timeout=32s\": EOF"
 
I am using haproxy loadbalancer, so had to configure the haproxy.cfg file to fix the issue.
