### ISSUE TITLE
Installer cleans up everything and does not fail if no correct cloud credentials are provided

### ISSUE THREAD

**Issue by Fodoj** [openshift/installer#4428]
# Version

```console
$ openshift-install version
openshift-install 4.6.0-0.okd-2020-11-27-200126
built from commit 7b5bd8be9e5f18cc9b8af5f95d629ddd64c015cc
release image quay.io/openshift/okd@sha256:a5392db432c990ee012ab189e9fa0d7b6a168f6e9b9e9da7fb10768b48752ca0
```

# Platform:

AWS, IPI

# What happened?

I've run "openshift-install destroy cluster" without setting correct AWS_PROFILE before. Installer deleted all the relevant files from my local directory, but did not delete any of AWS resources. Now I have to manually clean up everything.

# What you expected to happen?

I would expect installer to fail to destroy if it can not find resources.

# How to reproduce it (as minimally and precisely as possible)?

1. Install the cluster with one set of AWS credentials (could be profile, could be access keys in ENV)
2. Try to delete the cluster with another set of AWS credentials.

**Comment by Fodoj** [comment]
Any update on it?

**Comment by staebler** [comment]
> Any update on it?

We do not have any plans to change this behavior in the short term. It is not an error for the destroyer to not find any resources to delete. This may occur if there were an error running `create cluster` where no resources were actually created. We may consider a change in the future where the metadata.json file is preserved so that `destroy cluster` may be run again.

**Comment by Fodoj** [comment]
May be I didn't describe it correctly. Problem is not that destroyer can't find files - problem is that it removes files even if there is a failure during cluster deletion. Imagine I am trying to delete the cluster and the machine where I do it has a network hiccup, or some credentials are missing. It would be quite unpleasant to lose all the files in that case and not being able to delete the cluster afterwards.

**Comment by staebler** [comment]
If there are errors during destroy, the files should not be deleted. In the scenario presented originally, there was not error. You asked the destroyer to clean up the resources in the account that you had configured, and the destroyer succeeded in doing that.

**Comment by Fodoj** [comment]
In the scenario presented, this is exactly what I wrote - "Installer deleted all the relevant files from my local directory, but did not delete any of AWS resources. Now I have to manually clean up everything." I asked the destroyer to clean up - clean up failed, but it removed all files. As you are saying that it should not delete the files, then I would keep this issue and add a "bug" label. :-)

**Comment by staebler** [comment]
You installed the cluster in account A. You asked the destroyer to clean up the resources in account B. The destroyer cannot tell that you are using the wrong account. The destroyer successfully did what you asked it to do, namely to clean up all of the cluster resources in account B. The destroyer encountered no error: All cluster resources in account B were successfully deleted.

**Comment by Fodoj** [comment]
If cluster was created in Account A, then installer should not even try to do anything in Account B - assuming that installer is state-aware. I did assume that's the case, because the installer is using Terraform under the hood, and even stores the state in a Terraform state file. 

Normally Terraform would be able to figure out that it runs in a wrong account - because it will try to fetch the current state of AWS resources that it manages and will get a permissions error if AWS credentials are wrong. 

Of course, using Terraform directly and using it as a package inside another tool are two different things, but seeing state-aware utility behave like it's not state aware is at least surprising.
