### ISSUE TITLE
Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded

### ISSUE THREAD

**Issue by bassnsmq** [openshift/installer#4436]
# Version

```console
$ openshift-install version
openshift-install v4.2.15
built from commit 90f3dffe9089583c714ef6833fd86fa8d7523a13
release image quay.io/openshift-release-dev/ocp-release@sha256:e5a6e348721c38a78d9299284fbb5c60fb340135a86b674b038500bf190ad514

```

# Platform:
AWS - region ap-southeast-1

# What happened?
DEBUG Apply complete! Resources: 123 added, 0 changed, 0 destroyed.
DEBUG OpenShift Installer v4.2.15
DEBUG Still waiting for the Kubernetes API: Get https://api.openshift.hkeas.com:6443/version?timeout=32s: dial tcp: lookup api.openshift.hkeas.com on 172.31.0.2:53: server misbehaving
INFO Bootstrap gather logs captured here "/root/install-dir/log-bundle-20201201072424.tar.gz"
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded

The install log is here:
[openshift_install (2).log](https://github.com/openshift/installer/files/5621177/openshift_install.2.log)

# What you expected to happen?

OCP cluster can be provisioned correctly on aws platform.

# How to reproduce it (as minimally and precisely as possible)?
launch the destroy of the cluster and launch again the create

`./openshift-install create cluster --dir=/root/install-dir/ --log-level=debug`

# References

- enter text here.

**Comment by staebler** [comment]
> DEBUG Still waiting for the Kubernetes API: Get https://api.openshift.hkeas.com:6443/version?timeout=32s: dial tcp: lookup api.openshift.hkeas.com on 172.31.0.2:53: server misbehaving

Your DNS server at 172.31.0.2 is misbehaving. That is a problem with your configuration and not with the OpenShift installer.

/close
