### ISSUE TITLE
 defaultNodeSelector does not work as design

### ISSUE THREAD

**Issue by clyang82** [openshift/installer#4446]
# Version
`4.5.16`

# Platform:

# What happened?

According to the document - https://docs.openshift.com/container-platform/4.5/rest_api/config_apis/scheduler-config-openshift-io-v1.html
```
defaultNodeSelector helps set the cluster-wide default node selector to restrict pod placement to specific nodes. This is applied to the pods created in all namespaces without a specified nodeSelector value. For example, defaultNodeSelector: "type=user-node,region=east" would set nodeSelector field in pod spec to "type=user-node,region=east" to all pods created in all namespaces. Namespaces having project-wide node selectors won’t be impacted even if this field is set. This adds an annotation section to the namespace. For example, if a new namespace is created with node-selector='type=user-node,region=east', the annotation openshift.io/node-selector: type=user-node,region=east gets added to the project. When the openshift.io/node-selector annotation is set on the project the value is used in preference to the value we are setting for defaultNodeSelector field. For instance, openshift.io/node-selector: "type=user-node,region=west" means that the default of "type=user-node,region=east" set in defaultNodeSelector would not be applied.
```
`This is applied to the pods created in all namespaces without a specified nodeSelector value. ` Actually, the `defaultNodeSelector` is added whenever you have defined `nodeSelector` or not in your pod.
# What you expected to happen?

If there is no `nodeSelector` defined in the pod, the `defaultNodeSelector` should be added. while, if there is `nodeSelector` defined in the pod, the `defaultNodeSelector` should not be added.

**Comment by staebler** [comment]
The installer does not have anything to do with default node selectors.

With that being said, I think that you are misinterpreting the following part of the documentation (emphasis mine).
```
This is applied to the pods created in all namespaces without a **specified nodeSelector value**.
```
You can **supplement** the node selector labels for a specific pod, but you cannot choose to **not** apply the default node selector labels (whether they be the cluster-wide or the project-specific default).

See https://docs.openshift.com/container-platform/4.5/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-cluster_nodes-scheduler-node-selectors for more detail.

/close
