### ISSUE TITLE
Need Azure openshift-install to allow custom tags

### ISSUE THREAD

**Issue by brianotte** [openshift/installer#4449]
Openshift 4.6+

# Platform: Azure IPI

# What happened?

It is desired to assign custom tags to created objects in Azure when installing IPI
```
You cannot customize Azure Availability Zones or Use tags to organize your Azure resources with an Azure cluster.
SOURCE:  https://docs.okd.io/latest/installing/installing_azure/installing-azure-network-customizations.html
```

# What you expected to happen?

Azure IPI allows adding user defined tags.

# How to reproduce it (as minimally and precisely as possible)?

User tagging does not exist with Azure IPI (it does exist in AWS IPI).

**Comment by staebler** [comment]
Could you provide some more details around what your use case is for custom tags? The cluster installs to a dedicated resource group. Everything for the cluster (outside of some public DNS records and application registrations) are contained within that resource group. And everything in that resource group belongs to the cluster.

**Comment by brianotte** [comment]
Our enterprise uses tags to manage billing, reporting, and ownership of objects down to the resource level – we’d be looking for functionality similar to what is already available for AWS tagging, so that, at the very least, we can specify a set of tags at the RG, but preferably they would be added to any object created for the specific cluster

**Comment by staebler** [comment]
I have created a card on the OpenShift installer team's Jira board to track this feature request.

https://issues.redhat.com/browse/CORS-1604

**Comment by brianotte** [comment]
Hello David,

Is there any mechanisms you have to escalate this to the next level.  With so many days of inactivity it seems like a solution is not progressing.

Is there any additional information needed?

Please let us know.


Thank you.

Brian

From: OpenShift Bot ***@***.***>
Reply-To: openshift/installer ***@***.***>
Date: Wednesday, March 10, 2021 at 8:08 AM
To: openshift/installer ***@***.***>
Cc: "brian.otte" ***@***.***>, Author ***@***.***>
Subject: EXTERNAL: Re: [openshift/installer] Need Azure openshift-install to allow custom tags (#4449)


CAUTION: This email originated from outside of the company. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Issues go stale after 90d of inactivity.

Mark the issue as fresh by commenting /remove-lifecycle stale.
Stale issues rot after an additional 30d of inactivity and eventually close.
Exclude this issue from closing by commenting /lifecycle frozen.

If this issue is safe to close now please do so with /close.

/lifecycle stale

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopenshift%2Finstaller%2Fissues%2F4449%23issuecomment-795460722&data=04%7C01%7Cbrian.otte%40fisglobal.com%7Cd481184899544dd5401a08d8e3cdf377%7Ce3ff91d834c84b15a0b418910a6ac575%7C0%7C0%7C637509821017595518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7Rpih4N3csFbZU27wvkx4Tzr%2BkkhhvwMM6swX4B%2FZjs%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKJVPNKH2UOENIHVZM7FKTTTC5VLVANCNFSM4UMKR2GQ&data=04%7C01%7Cbrian.otte%40fisglobal.com%7Cd481184899544dd5401a08d8e3cdf377%7Ce3ff91d834c84b15a0b418910a6ac575%7C0%7C0%7C637509821017605511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9B%2B%2BesOYcNwAG6wP5oTKdBsqX2QPWtJ78FCxVhxKaFc%3D&reserved=0>.

The information contained in this message is proprietary and/or confidential. If you are not the intended recipient, please: (i) delete the message and all copies; (ii) do not disclose, distribute or use the message in any manner; and (iii) notify the sender immediately. In addition, please be aware that any message addressed to our domain is subject to archiving and review by persons other than the intended recipient. Thank you.
