### ISSUE TITLE
IPI vSphere: Vcenter tags are not deleted during cluster destroy

### ISSUE THREAD

**Issue by damhau** [openshift/installer#4478]
# Version

```console
./bin/openshift-install 4.6.0-0.okd-2020-12-08-152921
built from commit d0853e763a3aa3878e15f931bb06455247ee4261
release image registry.svc.ci.openshift.org/origin/release@sha256:2d8f9c334d8388dc75c6140f460430e309e532d88c094bbc2163ac85cd793da8
```

# Platform:
IPI
vSPhere

# What happened?

After running openshift-install destroy cluster the vCenter tag are not deleted.

# What you expected to happen?

The vCenter tag to be deleted

**Comment by staebler** [comment]
This was fixed by https://github.com/openshift/installer/pull/3941.

/close
