### ISSUE TITLE
someone is stomping etcd service

### ISSUE THREAD

**Issue by deads2k** [openshift/installer#448]
The etcd service as created by the installer has no selector and manual endpoints.  At some point during the installation, it is getting overwritten by one that has a selector and that destroys the endpoints.  I need help learning how to chase down who is modifying a particular resource.

```
[deads@deads-02 installer]$ oc get svc -n kube-system etcd -oyaml -w
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-10T12:07:21Z
  labels:
    k8s-app: etcd
  name: etcd
  namespace: kube-system
  resourceVersion: "43605"
  selfLink: /api/v1/namespaces/kube-system/services/etcd
  uid: 0a8d1afa-cc85-11e8-a193-fadc1ad39248
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    openshift.io/component: etcd
    openshift.io/control-plane: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

/assign  @steveeJ

**Comment by deads2k** [comment]
Found it in the cluster-monitoring-operator.  That was a lot harder than I'd like.  Opened https://github.com/openshift/cluster-monitoring-operator/pull/122

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/prometheus-k8s/service-etcd.yaml

**Comment by deads2k** [comment]
> https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/prometheus-k8s/service-etcd.yaml
> 
> EDIT: @deads2k you beat me to it. :)

Only after spending over an hour searching.  We need to find a better way.

**Comment by abhinavdahiya** [comment]
@deads2k https://github.com/openshift/cluster-monitoring-operator/pull/122 merged; does that fix the issue?

**Comment by brancz** [comment]
Sorry for having caused this in the first place.

Probably the best thing for discovering this type of stuff would be the audit log, no? I'd be nice if had that nicely indexed and searchable in the OpenShift UI. As the monitoring team we should probably take this to our PM as it seems like it would be a valuable addition for troubleshooting this type of problem :slightly_smiling_face: .

**Comment by crawford** [comment]
This seems to have been addressed at this point.

/close
