### ISSUE TITLE
EC2 aws_bootstrap_instance_type should be modified when platform.aws.defaultMachinePlatform.type is set to prevent install failures where m5 instance types are explicitly denied 

### ISSUE THREAD

**Issue by davdunc** [openshift/installer#4489]
# Version: 
OKD 4.6 
 msg="OpenShift Installer 4.6.0-0.okd-2020-12-12-135354"

# Platform:
* AWS
* IPI (automated install with `openshift-install`) 

# What happened?
time="2020-12-15T00:xx:xxZ" level=error msg="Error: Error launching source instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: . . . 

where the erro message shows: 

> msg="Error: Error launching source instance: UnauthorizedOperation: You are not authorized to perform this operation.

# What you expected to happen?
I expected that setting the default instance type in install-config.yaml would modify the bootstrap instance
`platform:
   aws:
     defaultMachinePlatform:
       type: t3.2xlarge`

would modify the bootstrap instance. 

# How to reproduce it (as minimally and precisely as possible)?

- Set a IAM or SCP policy in IAM or AWS organizations preventing the launch of C5 or M5 instance types. Something that satisfies the requirements to create something similar to this: 
`{
  "allowed": false,
  "explicitDeny": true,
  "matchedStatements": {
    "items": [
      {
        "statementId": "ToPreventCreationOfC5AndM5Instances",
        "effect": "DENY",
        "principals": {
          "items": [
            {
              "value": "ALDRE4443539938346436"
            }
          ]
        },
        "principalGroups": {
          "items": []
        },
        "actions": {
          "items": [
            {
              "value": "ec2:RunInstances"
            }
          ]
        },
        "resources": {
          "items": [
            {
              "value": "arn:aws:ec2:us-east-1:*:instance/*"
            }
          ]
        },
        "conditions": {
          "items": [
            {
              "key": "ec2:InstanceType",
              "values": {
                "items": [
                  {
                    "value": "c5*"
                  },
                  {
                    "value": "m5*"
                  }
                ]
              }
            }
          ]
        }
     }  
   ]
},
`
- Start an installation with an install-config where the platform instance types are anything other than M5 or C5 family instances

The install will fail with an encoded failure message that looks something like this one in the log: 

`level=error msg="Error: Error launching source instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: Qn14TV6qrHfOF6YctTgdp1e1nAWNdG_wNSrn_QEh3aajStovLXQRbTRh_9kpfckCwhC3TEBRtglWd0Mtsbhn2yXYEHLCHcTw58ZeMu4PS1dR7Rktn2p5L1lsZYlOwdgBzuHWFoECaeGFduDZXP0LJ2k3aFMJ0ADkKV8xLw4lQ81Abu5Sp6GnYu7SDDBCMNYc7_VGgfTvu5y_3IW8CF0nvZpb[...truncated...]"
time="2020-12-15T03:55:08Z" level=error msg="\tstatus code: 403, request id: removed-8888-424f-aaa9-f217d7f9a315"`

# References
None that I am aware of at the time I filed it.

**Comment by staebler** [comment]
The defaults specified in `defaultMachinePlatform` only apply to the control plane and compute machines. The installer does not support configuration of the bootstrap machine.

/close

**Comment by davdunc** [comment]
I didn't says that the install supports configuration of the bootstrap machine only that I need a way to configure the bootstrap machine. Thanks for pointing out the obvious and closing the issue.
