### ISSUE TITLE
[AWS][RFE] Create a way to modify the aws_bootstrap_instance_type

### ISSUE THREAD

**Issue by davdunc** [openshift/installer#4495]
# Version

OKD 4.6
msg="OpenShift Installer 4.6.0-0.okd-2020-12-12-135354"

# Platform:
AWS

* IPI (automated install with `openshift-install`\)

# What happened?
Unable to create a cluster because the typical bootstrap instance type (m5) is blocked by policy. 

# What you expected to happen?
I expected to locate a way to modify the bootstrap instance the terraform uses, in fact, I expected that the default machine type would modify that instance as well. 

# How to reproduce it (as minimally and precisely as possible)?

See https://github.com/openshift/installer/issues/4489 for details on the process and reproduction. 

# Anything else we need to know?

This is a major blocker for any user with a service control policy that blocks the m5 as an instance type. 

# References
https://github.com/openshift/installer/issues/4489

**Comment by staebler** [comment]
I have added this feature request as a card on the installer's Jira board.

https://issues.redhat.com/browse/CORS-1608
