### ISSUE TITLE
bootstrap node image pull failed

### ISSUE THREAD

**Issue by wychl** [openshift/installer#4504]
# Version

```console
$ openshift-install version
openshift-install 4.6.8
built from commit f5ba6239853f0904704c04d8b1c04c78172f1141
release image registry.ocp.ibm.com:5000/ocp4/openshift4@sha256:6ddbf56b7f9776c0498f23a54b65a06b3b846c1012200c5609c4bb716b6bdcdf
```

# Platform: baremetal

# What happened?

Enter text here.
Dec 22 07:03:03 localhost release-image-download.sh[2406]: Error: error pulling image "registry.ocp.ibm.com:5000/ocp4/openshift4@sha256:6ddbf56b7f9776c0498f23a54b65a06b3b846c1012200c5609c4bb716b6bdcdf": unable to pull registry.ocp.ibm.com:5000/ocp4/openshift4@sha256:6ddbf56b7f9776c0498f23a54b65a06b3b846c1012200c5609c4bb716b6bdcdf: unable to pull image: Error initializing source docker://registry.ocp.ibm.com:5000/ocp4/openshift4@sha256:6ddbf56b7f9776c0498f23a54b65a06b3b846c1012200c5609c4bb716b6bdcdf: error pinging docker registry registry.ocp.ibm.com:5000: Get "https://registry.ocp.ibm.com:5000/v2/": x509: certificate signed by unknown authority

# What you expected to happen?

# How to reproduce it (as minimally and precisely as possible)?

```console
$ journalctl -b -f -u release-image.service -u bootkube.service
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by staebler** [comment]
This is not a problem with the installer. This is a problem that needs to be brought up with whomever is building that openshift-installer with that release image. You can add the CA bundle to trust the image registry by adding it to the `additionalTrustBundle` field in the install-config.yaml.

```
$ ./bin/openshift-install explain installconfig.additionalTrustBundle
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <string>
  AdditionalTrustBundle is a PEM-encoded X.509 certificate bundle that will be added to the nodes' trusted certificate store.
```

**Comment by tsze-redhat** [comment]
Specifically, the section in install-config will look like
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGDzCCA......
  722Hg==
  -----END CERTIFICATE-----
  
  Note the 2 spaces in the content area.

**Comment by Sarah-Kriesch** [comment]
Use the openshift-installer version 4.6.9. This version works. Anyway, 4.6.8 is damaged for s390x. In my case, the binary of openshift-installer was not able to be executed with 4.6.8. A change to 4.6.9 was successful.

**Comment by wychl** [comment]
thanks solved

**Comment by tsze-redhat** [comment]
wychi, Glad to hear your problem is resolved. How did you resolve the problem? Just curiouis.
