### ISSUE TITLE
openshift 4.6 installation on aws failed with the following error 

### ISSUE THREAD

**Issue by kiransharma2016** [openshift/installer#4512]
DEBUG Log bundle written to /var/home/core/log-bundle-20201227013420.tar.gz
INFO Bootstrap gather logs captured here "/opt/openshift4/ospdir/log-bundle-20201227013420.tar.gz"
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://api.cluster2.bipratech.com:6443/version?timeout=32s": dial tcp 3.223.115.185:6443: i/o timeout

I repeated this process many times afer cleaning the system hoping it could work but it did  not. As there is very less to do before install,  is this only for me or any other people are also encountiering this issue? It is self installation  process so I am not sure what should i check?

I tried to be sure, ssh keys are creaed, ssh agent is running and key  are added  to it.  I have Iam user creared  with admin access, nothing else is running in my account so no problem of resources. 

I would appreciate any help

**Comment by staebler** [comment]
Look through the logs captured at `/var/home/core/log-bundle-20201227013420.tar.gz` for errors. Most likely you will see errors in one of the journals logs under `bootstrap/journals`.
