### ISSUE TITLE
Baremetal IPI install: cannot specify inspect_interface

### ISSUE THREAD

**Issue by zhouhao3** [openshift/installer#4541]
# Version

```console
$ openshift-baremetal-install version
openshift-baremetal-install 4.7.0-0.nightly-2021-01-12-203716
built from commit b3dae7f4736bcd1dbf5a1e0ddafa826ee1738d81
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:c97466158d19a6e6b5563da4365d42ebe5579421b1163f3a2d6778ceb5388aed 
```

# Platform:

baremetal

IPI

# What happened?

When the boosstrap VM is running, the `inspect_interfaces` available for the ironic running in the ironic-conductor container are as follows:

```
2021-01-13 03:14:09.481 1 DEBUG oslo_service.service [-] enabled_inspect_interfaces     = ['inspector', 'idrac', 'irmc', 'fake', 'redfish'] log_opt_values /usr/lib/python3.6/site-packages/oslo_config/cfg.py:2585^[[00m
```
The default value of `inspect_interface` is inspector:
```
'inspect_interface': 'inspector', 'management_interface': 'irmc', 'network_interface': 'noop', 'power_interface': 'irmc', 'raid_interface': 'irmc', 'rescue_interface': 'no-rescue',
```
Because our baremetal is connected by `irmc`, so we hope that the value of `inspect_interface` is also set to `irmc`. But we found no place to specify this value.

In this case, the inspector cannot successfully inspect the irmc machine, which will cause the installation to exit due to timeout.

# What you expected to happen?

There can be a field in the `install-config.yaml` file to specify the value of `inspect_interface`.

**Comment by stbenjam** [comment]
/remove-lifecycle stale

We use the inspector for everything, if you had a timeout there was likely another cause. Sorry for delay in getting to this, can you maybe share some more information?

@dtantsur Could you have a look at this, and confirm what I said about inspector is right?

**Comment by zhouhao3** [comment]
We have solved this problem by changing the configuration of the machine, sorry for not shutting down in time.
BTW, although we won't have this problem again, I think OCP still lacks the ability to let users specify some interfaces (power_interface, inspect_interface).
