### ISSUE TITLE
Build fails if cloud-credential-operator pin is updated

### ISSUE THREAD

**Issue by hawkowl** [openshift/installer#4545]
# Version

release-4.6, at least

# What happened?

build fails because change in https://github.com/openshift/cloud-credential-operator/pull/167 was overwritten by https://github.com/openshift/cloud-credential-operator/commit/b44655bddf36161038483788388ef79fc01158c7#diff-39260fbf46ea076702be0085fc20b3897395b779af4dbaee85902ce0b95d725d

**Comment by staebler** [comment]
@hawkowl Can you provide the output for your failed build?
