### ISSUE TITLE
qemu-kvm: -fw_cfg: invalid option

### ISSUE THREAD

**Issue by debianmaster** [openshift/installer#455]
# Version

```console
$ openshift-install version
0.1.0
```

# Platform (aws|libvirt|openshift):

libvirt/kvm

# What happened?

when i tried installing against libvirt

```
Error: Error applying plan:

2 error(s) occurred:

* module.bootstrap.libvirt_domain.bootstrap: 1 error(s) occurred:

* libvirt_domain.bootstrap: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option')
* libvirt_domain.master: 1 error(s) occurred:

* libvirt_domain.master: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option')
```

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by rphillips** [comment]
A newer version of qemu will be needed likely. Centos for the host OS? This might help: https://lists.centos.org/pipermail/centos/2017-July/165577.html.

**Comment by debianmaster** [comment]
thanks!  checking.

**Comment by wking** [comment]
It would be easier to debug this sort of thing if we could extract relevant version information from the libvirt Terraform provider like we currently do for Terraform itself.

**Comment by wking** [comment]
> It would be easier to debug this sort of thing if we could extract relevant version information from the libvirt Terraform provider...

dmacvicar/terraform-provider-libvirt#444

**Comment by wking** [comment]
Cross-linking #477, which also has some QEMU version discussion.

**Comment by wking** [comment]
Grepping through the QEMU history, `-fw_cfg` is from qemu/qemu@81b2b81062612e (v2.4.0-rc0~87^2~1), so that sets a floor version for Ignition injection.

**Comment by wking** [comment]
Cross-linking #675.

**Comment by crawford** [comment]
I think this has been adequately answered.

/close
