### ISSUE TITLE
make openstack security rules optional

### ISSUE THREAD

**Issue by clnperez** [openshift/installer#4555]
IBM's PowerVC (more info: https://www.ibm.com/products/powervc) is built on top of Openstack, and exposes Openstack APIs. We're hoping to make some tweaks to the installer for openstack that would allow us to use this against PowerVC. In experimenting with this, there are a few PowerVC limitations we've come across. I've been asked to open this issue for the security rules.

I would like to make them optional, as the only way to use them with PowerVC is to set up Novalink (more info: https://www.ibm.com/support/knowledgecenter/en/SSXK2N_1.4.0/com.ibm.powervc.standard.help.doc/powervc_sdn.html), which not all customers will have configured. 

I've done some initial hacking (mostly gutting), and can run the installer without creating any security rules. One concern was with DHCP server conflicts, but since network isolation (I believe), seems to be accomplished using tagged VLANs on the SEA, we may not need to worry about that.

Any other thoughts or concerns are welcome.

/cc @EricArrakis @iamemilio

**Comment by mandre** [comment]
It sounds like you want to deploy using UPI. That gives you the freedom to update the playbooks to match the environment, removing the security groups creation in your case.

**Comment by clnperez** [comment]
Actually this was for the PowerVC IPI work we talked about in Slack, @mandre .

**Comment by iamemilio** [comment]
Would you be able to use the additional security groups property in the install config to attach a security group that allows the connections you need to have @clnperez ?

**Comment by pierreprinetti** [comment]
@clnperez 
cf. https://docs.openshift.com/container-platform/4.8/installing/installing_openstack/installing-openstack-installer-custom.html#installation-configuration-parameters-optional-osp_installing-openstack-installer-custom

**Comment by pierreprinetti** [comment]
Closing; please reopen if the problem still exists and is not covered by @iamemilio 's suggestion.

/close

**Comment by pierreprinetti** [comment]
Re-reading the description, I understand that the problem is not blocked connections; but rather, that the platform does not support creating security groups and therefore errors when the Installer tries to create them. Is that the problem?

If this is the case, and the problem is still valid, and building on OpenStack's UPI is not possible, please reopen.

**Comment by clnperez** [comment]
Yes, this is correct @pierreprinetti. I've moved on to something else for a while (see https://github.com/openshift/enhancements/pull/736) -- so if we do come back to needing this support, I'll reopen and pick this up. No point in having it open and go stale and take up people's time all over again. :D Thanks very much for the read-through, though!
