### ISSUE TITLE
Pull Secret flag for create cluster

### ISSUE THREAD

**Issue by pcarney8** [openshift/installer#4558]
# Version

```console
$ openshift-install version
built from commit a48ad4a15b42102d1747d2f5f3b635deffb950b5
release image quay.io/openshift-release-dev/ocp-release@sha256:43d5c84169a4b3ff307c29d7374f6d69a707de15e9fa90ad352b432f77c0cead

```

# Platform:
all

* IPI (automated install with `openshift-install`. If you don't know, then it's IPI)

# What happened?

can't pass in pull secret via flag

# What you expected to happen?

`openshift-install create cluster --dir=directory-0 --log-level=info -p pullsecret.txt`

`openshift-install create cluster --dir=directory-0 --log-level=info --pull-secret pullsecret.txt`

# How to reproduce it (as minimally and precisely as possible)?

nothing to reproduce

# Anything else we need to know?

# References

**Comment by staebler** [comment]
The installer deliberately does not provide flags for customizing the installation. Customization is done via the install-config.yaml file. See https://github.com/openshift/installer/blob/master/docs/user/customization.md#platform-customization.

/close
