### ISSUE TITLE
OKD Install fails with "33.20210104.3.0" due to DNS resolution issues (vSphere IPI)

### ISSUE THREAD

**Issue by fortinj66** [openshift/installer#4573]
# Version

```console
33.20210104.3.0
```

# Platform:
vSphere IPI

# What happened?

DNS setup is incorrect after firstboot.  

```
[root@localhost ~]# cat /etc/resolv.conf
# Generated by KNI resolv prepender NM dispatcher script
search qa-c1v4.os.maeagle.corp
nameserver 10.102.5.77      (This is the node IP)
nameserver 127.0.0.53
```

Since there are not any other nameservers available and these do not represent working DNS servers, DNS resolution fails and ignition fails.

# What you expected to happen?

OKD successfully installed

# How to reproduce it (as minimally and precisely as possible)?

install latest OK stable release on vSphere IPI.  Fails 100%

# Anything else we need to know?

If we use an older version of FCOS: 33.20201214.3.1 and overide the payload to the latest OKD the install works fine so it doesn't seem to be an OKD issue...

# References
Slack conversation regarding this issue: https://kubernetes.slack.com/archives/C6BRQSH2S/p1611079697086200

https://github.com/openshift/installer/pull/4572

**Comment by vrutkovs** [comment]
It seems when DNS settings are passed via kargs, it gets preserved on the host by systemd-resolved. But later on this is not being used.

Not sure if its OKD specific behaviour, but previous stable FCOS seems to work great

**Comment by fortinj66** [comment]
may be same issue as https://github.com/openshift/installer/issues/4568

**Comment by fortinj66** [comment]
a workaround was to add good DNS server entries to the /etc/resolv.conf.  Once added, installation proceeded successfully...

**Comment by nerdalertdk** [comment]
Looks a lot like my problem

**Comment by fortinj66** [comment]
This has been resolved for quite a while now.
