### ISSUE TITLE
FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to unmarshal install-config.yaml: error converting YAML to JSON: yaml: line 31: could not find expected ':'

### ISSUE THREAD

**Issue by jayapalreddy18** [openshift/installer#4593]
# Version 4.6

```console
$ openshift-install version
4.6
```

# Platform:

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?
unable to create manifesto
Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by tsze-redhat** [comment]
Please paste your install-config.yaml here please.
You can remove the content of the lines for ssh key and pull-secret.

**Comment by jayapalreddy18** [comment]
apiVersion: v1
baseDomain: nonprod.hclpnp.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: DSOCP
networking:
  clusterNetworks:
  - cidr: 10.0.128.0/16
    hostSubnetLength: 9
  machineCIDR: 10.0.0.0/16
  serviceCIDR: 172.30.0.0/16
platform:
  vsphere:
    vcenter: xxxxxxx
    folder: "/NJDC/vm/Openshift"
    username: xxxxx
    password: xxxxxxxx
    datacenter: NJDC
    defaultDatastore: NETAPP_CIT_NONPROD_DS01
  fips: false
pullSecret: 
sshKey:

**Comment by jayapalreddy18** [comment]
this is the latest error.

[root@haproxy-ocp ~]# /openshift-install create manifests --dir=vsphere-install
FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field InstallConfig.pullSecret of type string

**Comment by staebler** [comment]
You may be missing quotes around your pull secret value. If you entered the pull secret JSON as is, then the yaml unmarshaling will consider the fields of the pull secrets as fields under `.pullSecret`.

For example, notice the single quotes around the test.
```
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"somekey"}}}'
```

Or, notice the pipe to indicate a multiline string.
```
pullSecret: |
  {
    "auths":{
      "cloud.openshift.com":{
        "auth":"somekey"
      }
    }
  }
```

**Comment by jayapalreddy18** [comment]
issue has been fixed thanks for suggestion
