### ISSUE TITLE
openshift / installer using UPI in VMWARE 6.7

### ISSUE THREAD

**Issue by jayapalreddy18** [openshift/installer#4607]
# Version
4,6

```console
$ openshift-install version
<your output here>
4.6.1
```

# Platform:
vmware

# What happened?

Enter text here.

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.
how to assign static IP 

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by staebler** [comment]
See Step 5(g) of https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-machines_installing-vsphere.
