### ISSUE TITLE
When OCP 4.n ships, unable to rebuild a -working- installer for 4.n-1, 4.n-2

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/installer#4615]
Hi,
I'm doing OCP on libvirt thanks to the ocp_libvirt_ipi ansible role.

I've run into a strange issue/story:

When OCP 4.5.z was the current version, I was able to deploy OCP 4.5.z successfully.
When OCP 4.6.z shipped, OCP 4.5.z still worked for a while and now it no longer works, even if the installer rebuilds properly.

Here is what the role is doing:
1) the role will find the proper commit id for the installer (e.g: the commit ID for 4.5.25)
2) the role will checkout the proper commit id.
3) the role will rebuild the installer, produce ignition configs and launch the install.

Those steps are here:
https://github.com/luisarizmendi/ocp-libvirt-ipi-role/blob/master/tasks/ocp_deploy.yml#L50-L64
https://github.com/luisarizmendi/ocp-libvirt-ipi-role/blob/master/tasks/ocp_deploy.yml#L77-L80

When OCP fails to deploy (think OCP 4.5 several weeks after OCP 4.6 has shipped), here is what happens:
The bootstrap IPI VM will boot fine and the temporary API endpoint on 6443 will come up.

The 'masters' will however fail to get a working ignition config (the VMs are IP, their IPs are pinging) because of an MCO error which says there is an unsupported version (I'll get the exact logs later as I'm re-deploying'

Is it no longer possible to rebuild, say, the 4.5.12 installer once 4.6.z has shipped?

Is there anything I could check to further investigate?

**Comment by ElCoyote27** [comment]
Here's the error I see on the bootstrap node:

```
Feb 03 16:59:44 ocp4d-vz8kk-bootstrap hyperkube[2325]: F0203 16:59:37.041575       1 bootstrap.go:47] error running MCC[BOOTSTRAP]: parsing Ignition config failed with error: config is not valid
```

**Comment by staebler** [comment]
There should not be any problem with installing a previous version.
Can you provide the result of `git show --oneline` for the branch that you are building?
Can you provide the .openshift_install.log from your install attempt?

**Comment by staebler** [comment]
> Here's the error I see on the bootstrap node:
> 
> ```
> Feb 03 16:59:44 ocp4d-vz8kk-bootstrap hyperkube[2325]: F0203 16:59:37.041575       1 bootstrap.go:47] error running MCC[BOOTSTRAP]: parsing Ignition config failed with error: config is not valid
> ```

Are you making any manual changes to the manifests or ignition configs?

**Comment by ElCoyote27** [comment]
I was in fact injecting an extra ignition config that carried this:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-ssd-override-udev
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
```
3.1.0 was the problem and since that extra manifest had stayed in my install dire, it was killing the deploy.
I'm now able to deploy 4.5.z (any version) by getting rid of the extra manifest:
```
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.31    True        False         11m     Cluster version is 4.5.31
 
```
