### ISSUE TITLE
Option to disable Manila CSI driver during openstack installation

### ISSUE THREAD

**Issue by tfrisk** [openshift/installer#4645]
# Version

```console
$ openshift-install version
4.6.12
```

# Platform:
openstack

# What happened?

I have tested installer on openstack to create a cluster. Now I have this persistent issue of failing Manila driver as our openstack (queens) does not have it enabled. How can I disable Manila driver? Our storage works with `cinder.csi.openstack.org` driver.

I have tested with both IPI and UPI methods and could not get rid of Manila. IPI installer fails to bring cluster up as Manila errors prevent it. UPI installer gets up eventually but cluster still fails to initialize 100% as Manila fails. With UPI installer, I can bring cluster up, add other CSI driver and get image registry working etc., but Manila errors still clutter event logs.

# What you expected to happen?

I want to have working cluster running on openstack without Manila CSI driver. There could be a config parameter for this in `install-config.yaml`.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by mandre** [comment]
I believe your issue was fixed with https://github.com/openshift/csi-driver-manila-operator/pull/88 that should be available with the upcoming release 4.6.18.

**Comment by tfrisk** [comment]
Awesome. I will test with 4.6.18+ when it's released.

**Comment by tfrisk** [comment]
Tested IPI install with versions 4.6.18 and 4.6.19 today. Storage clusteroperator still ends up in degraded state, which prevents installer to complete.

Last few lines of 4.6.19 installer logs:
```
INFO Cluster operator console Progressing is True with SyncLoopRefresh_InProgress: SyncLoopRefreshProgressing: Working toward version 4.6.19 
INFO Cluster operator console Available is False with Deployment_FailedUpdate: DeploymentAvailable: 1 replicas ready at version 4.6.19 
INFO Cluster operator image-registry Available is False with NoReplicasAvailable: Available: The deployment does not have available replicas
ImagePrunerAvailable: Pruner CronJob has been created 
INFO Cluster operator image-registry Progressing is True with DeploymentNotCompleted: Progressing: The deployment has not completed 
INFO Cluster operator insights Disabled is False with AsExpected:  
INFO Cluster operator kube-apiserver Progressing is True with NodeInstaller: NodeInstallerProgressing: 1 nodes are at revision 2; 2 nodes are at revision 6 
ERROR Cluster operator storage Degraded is True with ManilaCSIDriverOperatorCR_ManilaController_SyncError: ManilaCSIDriverOperatorCRDegraded: ManilaControllerDegraded: cannot authenticate with given credentials: Authentication failed 
INFO Cluster operator storage Progressing is True with ManilaCSIDriverOperatorCR_WaitForOperator: ManilaCSIDriverOperatorCRProgressing: Waiting for Manila operator to report status 
INFO Cluster operator storage Available is False with ManilaCSIDriverOperatorCR_WaitForOperator: ManilaCSIDriverOperatorCRAvailable: Waiting for Manila operator to report status 
FATAL failed to initialize the cluster: Multiple errors are preventing progress:
* Cluster operator console is reporting a failure: RouteHealthDegraded: failed to GET route (https://console-openshift-console.apps.clustername/health): Get "https://console-openshift-console.apps.clustername/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
* Cluster operator storage is reporting a failure: ManilaCSIDriverOperatorCRDegraded: ManilaControllerDegraded: cannot authenticate with given credentials: Authentication failed 
```

I also tried with 4.7.0 but it failed to load my configs (which loaded fine with 4.6).

**Comment by mandre** [comment]
Your error is different than in [the issue](https://bugzilla.redhat.com/show_bug.cgi?id=1918367) fixed by openshift/csi-driver-manila-operator#88 though:

```
ERROR Cluster operator storage Degraded is True with ManilaCSIDriverOperatorCR_ManilaController_SyncError: ManilaCSIDriverOperatorCRDegraded: ManilaControllerDegraded: cannot authenticate with given credentials: Authentication failed 
 ```

Can you run manila commands with the credentials from your `clouds.yaml`?

**Comment by tfrisk** [comment]
Hi. Our openstack (Queens) does not have manila available at all. That is why I want to disable manila for installer.

I added python client to my dev container and ran some test commands with it, they return the same error:
```
 > manila api-version
ERROR: Could not find Manila endpoint in catalog
 > manila type-list
ERROR: Could not find Manila endpoint in catalog
 >
```

I have a feeling 4.7 installer fails on something like this when it tries to verify openstack access. It's very difficult to debug it as it's not giving out the actual errors (even with debug log level, which is not verbose enough for debugging).

**Comment by tfrisk** [comment]
Update: weird behavior of my test cluster seems to be local configuration issue. I had passed wrong `project_name` value to my `clouds.yaml` file template. Installer versions 4.6 and 4.7 handled this in very different ways. These different failure models made debugging harder than it should have been.

- 4.6 used project_name at the end of the install when it tried to bring up storage operators (all other resources were provisioned properly, only storage operator failed. That's why I presumed my clouds.yaml was fine).
- 4.7 has added validations at the beginning and it failed during the first second.

Hope this will help someone else who may struggle with similar issue.

I still think you could make cluster-included storage csi driver list (https://github.com/openshift/installer/blob/master/vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go#L42-L48) configurable, so users could select which ones they want.

**Comment by mandre** [comment]
It was probably reading the OS_PROJECT_NAME variable from your environment.

In openshift 4.7 we've introduced a default client that ignores environment variables for all of the openstack calls to make sure that the provided `clouds.yaml` entry is really used. See:

https://github.com/openshift/installer/blob/05453ef/pkg/types/openstack/defaults/clientopts.go#L11-L14

**Comment by iamemilio** [comment]
This seems resolved. Please re-open if that is not correct.
/close
