### ISSUE TITLE
Passing parameters to openshift-install create install-config in order to bypass interactive prompt. 

### ISSUE THREAD

**Issue by isaacnboyd** [openshift/installer#4671]
# Version

```console
openshift-install 4.6.0
```

# Platform:

Disclaimer, I don't have much experience with open source contributing/question asking. I am trying to automate the generation of install-config and the ignition-files so that I can create OSEv4 clusters from a Jenkins Pipeline. I would love to use `openshift-install create install-config ` but it is an interactive tool. The help docs don't provide any means of passing parameters via command line. Can someone tell me where in the code this interactive tool is? I would like to see if I can pass the necessary parameters via command line. 

# How to reproduce it (as minimally and precisely as possible)?

```console
openshift-install create install-config
openshift-install create ignition-configs
```

# References

```
$ openshift-install create install-config -h
$ openshift-install create ignition-configs -h
```

**Comment by staebler** [comment]
What you are going to want to do is to create an `install-config.yaml` file and place it in your asset directory. The installer does not accept command-line arguments to customize the installation.

See https://github.com/openshift/installer/blob/master/docs/user/customization.md

**Comment by isaacnboyd** [comment]
That's exactly what I needed to know!! Thank you so much.

**Comment by isaacnboyd** [comment]
Openshift-install create ignition-configs will read from an install-config within the asset directory and automatically populate the Ignition Configs.
