### ISSUE TITLE
Any option to use bonded interfaces (with static IPs) in baremetal IPI install

### ISSUE THREAD

**Issue by rm75** [openshift/installer#4690]
# Version

```console
$ openshift-install version
4.6
```

# Platform:

Any option to use bonded interfaces (with static IPs) in baremetal IPI install?
I was planning to customize node file system as mentioned in https://openshift-kni.github.io/baremetal-deploy/latest/Ansible%20Playbook%20Install.html#ansible-playbook-customizing-the-node-filesystems, but seems like is applied to all the master or worker nodes. 

Appreciate any helps.

**Comment by staebler** [comment]
You can do this with a NodeNetworkConfigurationPolicy? See https://docs.openshift.com/container-platform/4.6/virt/node_network/virt-updating-node-network-config.html#virt-example-bond-nncp_virt-updating-node-network-config.
