### ISSUE TITLE
Docker fails to start on all master nodes

### ISSUE THREAD

**Issue by DanPhonovation** [openshift/installer#4711]
```console
$ openshift-install version
./openshift-install 4.7.0-0.okd-2021-02-25-144700
built from commit a005bb9eddcbc97e4cac2cdf4436fe2d524cc75e
release image quay.io/openshift/okd@sha256:d0141818eca0f2d49fdea7f3ae5789f3bc747a669f2459f8ef189d1702405b08
```

Platform:vsphere 7/esx6.7U3 with LOTS and LOTS of resources.

Hi all, Sorry I'm a K8 noob. I've gotten pretty far w/ the docs but I am stumped. Please help.

bootstrapping seems to go fine. Im currently looking at 3 master's, 1 bootstrap.

From the bootstrap, I can ssh to any of the masters.

My provision machine has been hung on Waiting for logs for ages. Scared to back out of it for the time being to collect logs. Logging onto the masters and running  

```console
sudo kubectl get nodes --kubeconfig /etc/kubernetes/kubeconfig 
```

gives me:

```console
The connection to the server localhost:6443 was refused - did you specify the right host or port?
```

I then went to go check on the docker service and the kubelet service and docker won't even start.

Launcing dockerd manually launches the api but complains about docker-exec not being in $PATH.

I was getting the same in provisioner, verified my DNS entries as per: https://github.com/openshift/okd/issues/171

I'm thoroughly confused.

# What you expected to happen?

A success on the bootstrap

**Comment by DanPhonovation** [comment]
Ok so I got frustrated and took someone's comments and restarted the bootstrapper and workers.

Docker as a service is now missing and kubelet is started, but clearly the install process timed out and exited during the reboot.

**Comment by staebler** [comment]
OpenShift does not use docker to run containers. It uses the CRI-O container runtime. So you should not expect to see the docker service running on the cluster machines.

**Comment by staebler** [comment]
I recommend that you check the logs of the kubelet.service and the crio.service to start.

**Comment by DanPhonovation** [comment]
THat's odd. I certainly saw it listed in systemctl and had binaries.

`ERROR Cluster operator etcd Degraded is True with BootstrapTeardown_Error::ClusterMemberController_Error::EtcdEndpoints_ErrorUpdatingEtcdEndpoints::EtcdMe                                                                                   mbersController_ErrorUpdatingReportEtcdMembers::NodeController_MasterNodesReady::StaticPods_Error: StaticPodsDegraded: pods "etcd-okdcluster-6wwm2-master-                                                                                   0" not found
ERROR StaticPodsDegraded: pods "etcd-okdcluster-6wwm2-master-1" not found
ERROR StaticPodsDegraded: pods "etcd-okdcluster-6wwm2-master-2" not found
ERROR EtcdMembersControllerDegraded: failed to get etcd client: failed to make etcd client for endpoints [https://10.1.8.11:2379 https://10.1.8.12:2379 ht                                                                                   tps://10.1.8.13:2379 https://10.1.8.3:2379]: context deadline exceeded
ERROR NodeControllerDegraded: The master nodes not ready: node "okdcluster-6wwm2-master-0" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatu                                                                                   sUnknown (Kubelet stopped posting node status.), node "okdcluster-6wwm2-master-1" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown                                                                                    (Kubelet stopped posting node status.), node "okdcluster-6wwm2-master-2" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet                                                                                    stopped posting node status.)
ERROR EtcdEndpointsDegraded: could not create etcd client: failed to get etcd client: failed to make etcd client for endpoints [https://10.1.8.11:2379 htt                                                                                   ps://10.1.8.12:2379 https://10.1.8.13:2379 https://10.1.8.3:2379]: context deadline exceeded
ERROR ClusterMemberControllerDegraded: failed to get etcd client: failed to make etcd client for endpoints [https://10.1.8.11:2379 https://10.1.8.12:2379                                                                                    https://10.1.8.13:2379 https://10.1.8.3:2379]: context deadline exceeded
ERROR BootstrapTeardownDegraded: failed to get etcd client: failed to make etcd client for endpoints [https://10.1.8.12:2379 https://10.1.8.13:2379 https:                                                                                   //10.1.8.11:2379 https://10.1.8.3:2379]: context deadline exceeded
INFO Cluster operator etcd Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have achieved new revision                                                                                    2
INFO Cluster operator etcd Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at revision 0; 0 nodes                                                                                    have achieved new revision 2
INFO Cluster operator insights Progressing is True with Initializing: Initializing the operator
ERROR Cluster operator kube-apiserver Degraded is True with ConfigObservation_Error::NodeController_MasterNodesReady::StaticPods_Error: NodeControllerDegr                                                                                   aded: The master nodes not ready: node "okdcluster-6wwm2-master-0" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet stoppe                                                                                   d posting node status.), node "okdcluster-6wwm2-master-1" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting                                                                                    node status.), node "okdcluster-6wwm2-master-2" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node sta                                                                                   tus.)
ERROR ConfigObservationDegraded: configmaps openshift-etcd/etcd-endpoints: no etcd endpoint addresses found
ERROR StaticPodsDegraded: pods "kube-apiserver-okdcluster-6wwm2-master-0" not found
ERROR StaticPodsDegraded: pods "kube-apiserver-okdcluster-6wwm2-master-1" not found
ERROR StaticPodsDegraded: pods "kube-apiserver-okdcluster-6wwm2-master-2" not found
INFO Cluster operator kube-apiserver Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have achieved ne                                                                                   w revision 2
INFO Cluster operator kube-apiserver Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at revision                                                                                    0; 0 nodes have achieved new revision 2
ERROR Cluster operator kube-controller-manager Degraded is True with NodeController_MasterNodesReady::StaticPods_Error: NodeControllerDegraded: The master                                                                                    nodes not ready: node "okdcluster-6wwm2-master-1" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node s                                                                                   tatus.), node "okdcluster-6wwm2-master-2" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.),                                                                                    node "okdcluster-6wwm2-master-0" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
ERROR StaticPodsDegraded: pods "kube-controller-manager-okdcluster-6wwm2-master-0" not found
ERROR StaticPodsDegraded: pods "kube-controller-manager-okdcluster-6wwm2-master-1" not found
ERROR StaticPodsDegraded: pods "kube-controller-manager-okdcluster-6wwm2-master-2" not found
INFO Cluster operator kube-controller-manager Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have ac                                                                                   hieved new revision 2
INFO Cluster operator kube-controller-manager Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at                                                                                    revision 0; 0 nodes have achieved new revision 2
ERROR Cluster operator kube-scheduler Degraded is True with NodeController_MasterNodesReady::StaticPods_Error: StaticPodsDegraded: pods "openshift-kube-sc                                                                                   heduler-okdcluster-6wwm2-master-0" not found
ERROR StaticPodsDegraded: pods "openshift-kube-scheduler-okdcluster-6wwm2-master-1" not found
ERROR StaticPodsDegraded: pods "openshift-kube-scheduler-okdcluster-6wwm2-master-2" not found
ERROR NodeControllerDegraded: The master nodes not ready: node "okdcluster-6wwm2-master-0" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatu                                                                                   sUnknown (Kubelet stopped posting node status.), node "okdcluster-6wwm2-master-1" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown                                                                                    (Kubelet stopped posting node status.), node "okdcluster-6wwm2-master-2" not ready since 2021-03-04 01:16:28 +0000 UTC because NodeStatusUnknown (Kubelet                                                                                    stopped posting node status.)
`


Lots of debug logging and I didn't scroll up. I believe this means I missed having etcd SRV TXT records?

**Comment by DanPhonovation** [comment]
Certaintly looks like a etcd messup on my part. Seems it keeps respinning?

```
I0304 04:06:04.939477       1 scheduler.go:592] "Successfully bound pod to node" pod="openshift-etcd-operator/etcd-operator-65d79cb548-kb86r" node="master1" evaluatedNodes=3 feasibleNodes=2
W0304 04:09:58.451763       1 authentication.go:332] Error looking up in-cluster authentication configuration: etcdserver: request timed out
I0304 04:13:06.120568       1 scheduler.go:592] "Successfully bound pod to node" pod="openshift-etcd/etcd-quorum-guard-bcb75dd9b-vcrrx" node="master1" evaluatedNodes=3 feasibleNodes=2
I0304 04:13:06.122455       1 factory.go:321] "Unable to schedule pod; no fit; waiting" pod="openshift-etcd/etcd-quorum-guard-bcb75dd9b-jrcxl" err="0/3 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't match pod anti-affinity rules."
I0304 04:13:06.123469       1 scheduler.go:592] "Successfully bound pod to node" pod="openshift-etcd/etcd-quorum-guard-bcb75dd9b-v7hx9" node="master0" evaluatedNodes=3 feasibleNodes=1
I0304 04:13:06.168564       1 factory.go:321] "Unable to schedule pod; no fit; waiting" pod="openshift-etcd/etcd-quorum-guard-bcb75dd9b-jrcxl" err="0/3 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't match pod anti-affinity rules."
I0304 04:14:10.042061       1 factory.go:321] "Unable to schedule pod; no fit; waiting" pod="openshift-etcd/etcd-quorum-guard-bcb75dd9b-jrcxl" err="0/3 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't match pod anti-affinity rules."
```

My dig for _etcd-server-ssl points to the 3 different masters; the only ones I currently have as I guess I'm not at the worker stage yet.

**Comment by DanPhonovation** [comment]
Ok so... I think this is whats happening but why or how to fix:
```

2021-03-04T05:25:31.738774379+00:00 stderr F WARNING: 2021/03/04 05:25:31 grpc: addrConn.createTransport failed to connect to {https://10.1.8.11:2379  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.1.8.11:2379: connect: connection refused". Reconnecting...
2021-03-04T05:25:31.738816152+00:00 stderr F WARNING: 2021/03/04 05:25:31 grpc: addrConn.createTransport failed to connect to {https://10.1.8.12:2379  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.1.8.12:2379: connect: connection refused". Reconnecting...
2021-03-04T05:25:32.739143625+00:00 stderr F WARNING: 2021/03/04 05:25:32 grpc: addrConn.createTransport failed to connect to {https://10.1.8.11:2379  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.1.8.11:2379: connect: connection refused". Reconnecting...
2021-03-04T05:25:32.739168104+00:00 stderr F WARNING: 2021/03/04 05:25:32 grpc: addrConn.createTransport failed to connect to {https://10.1.8.12:2379  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.1.8.12:2379: connect: connection refused". Reconnecting...
2021-03-04T05:25:32.739212949+00:00 stderr F WARNING: 2021/03/04 05:25:32 grpc: addrConn.createTransport failed to connect to {https://10.1.8.13:2379  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.1.8.13:2379: connect: connection refused". Reconnecting...
2021-03-04T05:25:34.212792181+00:00 stderr F WARNING: 2021/03/04 05:25:34 grpc: addrConn.createTransport failed to connect to {https://10.1.8.13:2379  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.1.8.13:2379: connect: connection refused". Reconnecting...
```
These are logs from master0. The other masters had a /var/log/containers folder for etcd but no log files within.

Those 3 IPs are my masters. Note, the bootstrap IP isn't listed here. This is what my 3 service records point to.

However, manually going to check listening ports - the only box listening on that port is the bootstrap box.

I'm going to try adding it in there to see if behavior changes.

**Comment by DanPhonovation** [comment]
With 4.6 I'm getting the following logs:

```NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version             False       True          88m     Unable to apply 4.6.0-0.okd-2021-02-14-205305: some cluster operators have not yet rolled out
[root@provisioner okd-installing]# oc get clusteroperators
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                                                             False       False         True       72m
cloud-credential                           4.6.0-0.okd-2021-02-14-205305   True        False         False      86m
cluster-autoscaler                         4.6.0-0.okd-2021-02-14-205305   True        False         False      71m
config-operator                            4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
console                                    4.6.0-0.okd-2021-02-14-205305   Unknown     True          False      67m
csi-snapshot-controller                    4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
dns                                        4.6.0-0.okd-2021-02-14-205305   True        False         False      70m
etcd                                       4.6.0-0.okd-2021-02-14-205305   True        False         False      71m
image-registry                             4.6.0-0.okd-2021-02-14-205305   True        False         False      67m
ingress                                                                    False       True          True       71m
insights                                   4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
kube-apiserver                             4.6.0-0.okd-2021-02-14-205305   True        False         False      70m
kube-controller-manager                    4.6.0-0.okd-2021-02-14-205305   True        False         False      69m
kube-scheduler                             4.6.0-0.okd-2021-02-14-205305   True        False         False      68m
kube-storage-version-migrator              4.6.0-0.okd-2021-02-14-205305   False       False         False      72m
machine-api                                4.6.0-0.okd-2021-02-14-205305   True        False         False      66m
machine-approver                           4.6.0-0.okd-2021-02-14-205305   True        False         False      71m
machine-config                             4.6.0-0.okd-2021-02-14-205305   True        False         False      71m
marketplace                                4.6.0-0.okd-2021-02-14-205305   True        False         False      70m
monitoring                                                                 False       True          True       67m
network                                    4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
node-tuning                                4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
openshift-apiserver                        4.6.0-0.okd-2021-02-14-205305   True        False         False      67m
openshift-controller-manager               4.6.0-0.okd-2021-02-14-205305   True        False         False      69m
openshift-samples                          4.6.0-0.okd-2021-02-14-205305   True        False         False      67m
operator-lifecycle-manager                 4.6.0-0.okd-2021-02-14-205305   True        False         False      71m
operator-lifecycle-manager-catalog         4.6.0-0.okd-2021-02-14-205305   True        False         False      71m
operator-lifecycle-manager-packageserver   4.6.0-0.okd-2021-02-14-205305   True        False         False      67m
service-ca                                 4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
storage                                    4.6.0-0.okd-2021-02-14-205305   True        False         False      72m
```


No worker VMs are ever spun up. I see similar issues on libvirt.

**Comment by DanPhonovation** [comment]
Figured it out. At least for all these issues. Going back to try 4.7.

I also own the ent network. The nazi sysadmin made the assumption that only the provisioning machine (bootstrap) would need access to vsphere/esx servers to create the VMs. Nope. The control plane machines need access as well. Hidden amongst all the messages in one of the container logs it was :)

THanks for reading!

TL:DR; If you're running against VSphere, be sure your provisioner and control plane have access to vsphere/esx infrastructure.
