### ISSUE TITLE
OpenStack: option to disable network tags

### ISSUE THREAD

**Issue by krauthosting** [openshift/installer#4721]
# Version

```console
level=debug msg=OpenShift Installer 4.7.0
level=debug msg=Built from commit 98e11541c24e95c864328b9b35c64b77836212ed
```

# Platform: openstack

* IPI
* UPI

# What happened?

Customer cloud setup with OpenStack doesn't allow network tags in security groups / subnets.
Within IPI the Terraform part fails as it can't tag network things in OpenStack during bootstrap:

```
ERROR
ERROR Error: Error setting tags on openstack_networking_secgroup_v2 99849af5-74ed-4198-ae74-b09fa40c1108: Resource not found
ERROR
ERROR on ../../../../tmp/openshift-install-081101502/topology/sg-master.tf line 1, in resource "openstack_networking_secgroup_v2" "master":
ERROR 1: resource "openstack_networking_secgroup_v2" "master" {
ERROR
ERROR
ERROR
ERROR Error: Error setting tags on openstack_networking_secgroup_v2 57ce7fcd-5927-4fed-906b-1c86136f88ac: Resource not found
ERROR
ERROR on ../../../../tmp/openshift-install-081101502/topology/sg-worker.tf line 1, in resource "openstack_networking_secgroup_v2" "worker":
ERROR 1: resource "openstack_networking_secgroup_v2" "worker" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```

Looking it up in UPI we assume that Terraform like Ansible it's just want to set the cluster id:

```console
us@pc:~/Downloads/OpenShift/UPI$ grep -rnie "\-\-tag" .
./control-plane.yaml:28: cmd: "openstack port set --tag {{ cluster_id_tag }} {{ item.1 }}-{{ item.0 }}"
./compute-nodes.yaml:27: cmd: "openstack port set --tag {{ cluster_id_tag }} {{ item.1 }}-{{ item.0 }}"
./down-network.yaml:15: cmd: "openstack port list --device-owner=network:router_interface --tags {{ cluster_id_tag }} -f value -c id"
./down-network.yaml:25: cmd: "openstack port list --device-owner=network:ha_router_replicated_interface --tags {{ cluster_id_tag }} -f value -c id"
./down-network.yaml:35: cmd: "openstack port list --tags {{ cluster_id_tag }} -f value -c id"
./down-network.yaml:50: cmd: "openstack network list --tags {{ cluster_id_tag }} -f value -c ID"
./network.yaml:20: cmd: "openstack network set --tag {{ primary_cluster_network_tag }} --tag {{ cluster_id_tag }} {{ os_network }}"
./network.yaml:32: cmd: "openstack subnet set --tag {{ cluster_id_tag }} {{ os_subnet }}"
./network.yaml:41: cmd: "openstack network set --tag {{ cluster_id_tag }} {{ os_svc_network }}"
./network.yaml:79: cmd: "openstack subnet list --name {{ os_svc_subnet }} --tag {{ cluster_id_tag }}"
./network.yaml:85: cmd: "openstack subnet create --ip-version 4 --gateway {{ gateway_ip }} --subnet-range {{ os_svc_network_range }} {{ allocation_pool }} --no-dhcp --network {{ os_svc_network }} --tag {{ cluster_id_tag }} {{ os_svc_subnet }}"
./network.yaml:92: cmd: "openstack subnet pool list --name {{ subnet_pool }} --tags {{ cluster_id_tag }}"
./network.yaml:98: cmd: "openstack subnet pool create --default-prefix-length {{ host_prefix }} --pool-prefix {{ cluster_network_cidrs }} --tag {{ cluster_id_tag }} {{ subnet_pool }}"
./network.yaml:113: cmd: "openstack router set --tag {{ cluster_id_tag }} {{ os_router }}"
./network.yaml:130: cmd: "openstack port set --tag {{ cluster_id_tag }} {{ os_port_api }}"
./network.yaml:144: cmd: "openstack port set --tag {{ cluster_id_tag }} {{ os_port_ingress }}"
./down-security-groups.yaml:15: cmd: "openstack security group list --tags {{ cluster_id_tag }} -f value -c ID"
./bootstrap.yaml:25: cmd: "openstack port set --tag {{ cluster_id_tag }} {{ os_port_bootstrap }}"
./security-groups.yaml:19: cmd: "openstack security group set --tag {{ cluster_id_tag }} {{ os_sg_master }} "
./security-groups.yaml:27: cmd: "openstack security group set --tag {{ cluster_id_tag }} {{ os_sg_worker }} "
us@pc:~/Downloads/OpenShift/UPI$ grep -rnie "\-\-tag" . | wc -l
20
```

# What you expected to happen?

Maybe we're unaware what those tagging might be else used for especially in day 2 operations.
But from UPI we're assuming it's for having multiple OpenShift clusters in one OpenStack project.
For scenarios with one OpenShift per OpenStack project a workaround or toggl would be sweet.

Like we can't demand changes to public clouds same is true for onpremise setups with OpenStack.
In that regard would be an option to disable those breaking tagging be possible for the IPI installer?
If for timing reasons that can be only hacked in UPI are there day 2 problems to expect without tags?

**Comment by mandre** [comment]
To give a bit of context, these tags are not only useful in the case where multiple clusters are deployed in the same tenant, but in all cases where there is no dedicated tenant for the openshift cluster.

We're using tags to identify resources created by the installer, which must later be removed when destroying the cluster, and is currently [a requirement](https://github.com/openshift/installer/tree/master/docs/user/openstack#openstack-requirements) for deploying openshift on openstack platforms.

If you're absolutely sure you have a dedicated openstack tenant for your openshift deployment you may want to modify the UPI playbooks to remove tag creation, it should allow to deploy. It's unlikely we'll provide a switch to turn this off though.

**Comment by krauthosting** [comment]
@mandre Late but big thanks for detailed explanation :+1:  For the customer project it was the last hurdle on OpenStack.
We faced a bunch of problems using their older RHOSP10 which is not supported by any supported OpenShift anyway.
Their install also didn't meet the requirement of network tagging and we're continuing with them on their vSphere clusters.
Therefore i close this issue but hope it serves as reference for other folks running into such more restricted OpenStack :)
