### ISSUE TITLE
Not able to create the cluster 

### ISSUE THREAD

**Issue by ShadySQL** [openshift/installer#4730]
I just got started with this and ran the installer but get the error:

FATAL failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Permissions Check": validate AWS credentials: current credentials insufficient for performing cluster installation

I did put this in my file: credentialsMode: Mint 

as in:

apiVersion: v1
baseDomain: test.test.com
credentialsMode: Mint 

additionally is there a way to tell the installer to use that file? All the information for the prompts the installer ask for are in that file. 

I can vouch that I just have developer (super user access) to our AWS account and I'm not sure I can get an account with admin rights on the account. Is there a way to bypass this check all together?

**Comment by staebler** [comment]
Any changes you make to the install-config.yaml file will be picked up by the installer. That file is the authoritative source for configuration for the installer. You can start with that file if you do not want to go through the user prompts.

Put the install-config.yaml in a directory, say $INST_DIR. Then run,
```
openshift-install create cluster --dir=$INST_DIR
```

As to the question of bypassing the credentials, if you set the `credentialsMode` field in the install-config.yaml file, then the installer will skip doing any permissions check. However, that is usually used when you have specific permissions configurations that the AWS permissions simulator does not support. If you want to manually see if you have all of the permissions that OpenShift needs, you can refer to https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account.

**Comment by ShadySQL** [comment]
I ran these commands:

openshift-install create install-config --dir=install

openshift-install create cluster --dir=instsall --log-level=info

I got my file here: https://pastebin.pl/view/3deada66

I still get that error however. I think I might be missing a step or?

**Comment by staebler** [comment]
Can you provide the .openshift_install.log file from your install directory?

**Comment by ShadySQL** [comment]
Here you go: https://paste.ubuntu.com/p/qZznX4BwGS/

It's the same error. I'm not sure if the installer is able to consume my install-config.yaml in my install directory as it still checks for the AWS permissions even though I pass the flag: 

credentialsMode: Mint

for it to bypass that check.

**Comment by staebler** [comment]
From the logs, the installer never loaded your install-config.yaml file from disk, in any of the three runs. Are you putting the install-config.yaml in the install directory?

**Comment by ShadySQL** [comment]
I did place that file in the install directory

**Comment by staebler** [comment]
Would you mind taking your install-config.yaml file, placing it in a new directory, and running the following?
```
openshift-install create cluster --dir=NEW_DIR
```
where `NEW_DIR` is the new directory with the file.

**Comment by ShadySQL** [comment]
This seems to have at least kicked off the deployment into AWS after I was able to get admin access to the account. Here is the log:

`install % openshift-install create cluster --dir=installer
INFO Credentials loaded from the "default" profile in file "/Users/homedirectory/.aws/credentials"
INFO Consuming Install Config from target directory
INFO Creating infrastructure resources...
INFO Waiting up to 20m0s for the Kubernetes API at https://api.test-cluster.xxxxx.com:6443...
INFO API v1.20.0+bd9e442 up
INFO Waiting up to 30m0s for bootstrapping to complete...
INFO Destroying the bootstrap resources...
INFO Waiting up to 40m0s for the cluster at https://api.test-cluster.xxxxx.com:6443 to initialize...



ERROR Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthRouteCheckEndpointAccessibleController_SyncError::OAuthServerDeployment_DeploymentAvailableReplicasCheckFailed::OAuthServerRoute_InvalidCanonicalHost::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError::OAuthVersionDeployment_GetFailed::Route_InvalidCanonicalHost::WellKnownReadyController_SyncError: OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded: oauth service endpoints are not ready
ERROR IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server
ERROR OAuthServiceCheckEndpointAccessibleControllerDegraded: Get "https://172.30.70.208:443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
ERROR OAuthRouteCheckEndpointAccessibleControllerDegraded: route status does not have host address
ERROR WellKnownReadyControllerDegraded: failed to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap: configmap "oauth-openshift" not found (check authentication operator, it is supposed to create this)
ERROR OAuthVersionDeploymentDegraded: Unable to get OAuth server deployment: deployment.apps "oauth-openshift" not found
ERROR RouteDegraded: no ingress for host oauth-openshift.apps.test-cluster.xxxxx.com in route oauth-openshift in namespace openshift-authentication
ERROR OAuthServerDeploymentDegraded: deployments.apps "oauth-openshift" not found
ERROR OAuthServerRouteDegraded: no ingress for host oauth-openshift.apps.test-cluster.xxxxx.com in route oauth-openshift in namespace openshift-authentication
INFO Cluster operator authentication Available is False with OAuthServiceCheckEndpointAccessibleController_EndpointUnavailable::OAuthServiceEndpointsCheckEndpointAccessibleController_EndpointUnavailable::OAuthVersionDeployment_MissingDeployment::ReadyIngressNodes_NoReadyIngressNodes::WellKnown_NotReady: OAuthServiceEndpointsCheckEndpointAccessibleControllerAvailable: Failed to get oauth-openshift enpoints
INFO ReadyIngressNodesAvailable: Authentication requires functional ingress which requires at least one schedulable and ready node. Got 0 worker nodes, 3 master nodes, 0 custom target nodes (none are schedulable or ready for ingress pods).
INFO OAuthServiceCheckEndpointAccessibleControllerAvailable: Get "https://172.30.70.208:443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
INFO WellKnownAvailable: The well-known endpoint is not yet available: failed to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap: configmap "oauth-openshift" not found (check authentication operator, it is supposed to create this)
INFO Cluster operator baremetal Disabled is True with UnsupportedPlatform: Nothing to do on this Platform
ERROR Cluster operator cloud-credential Degraded is True with CredentialsFailing: 5 of 5 credentials requests are failing to sync.
INFO Cluster operator cloud-credential Progressing is True with Reconciling: 0 of 5 credentials requests provisioned, 5 reporting errors.
INFO Cluster operator console Progressing is True with DefaultRouteSync_FailedAdmitDefaultRoute::OAuthClientSync_FailedHost: DefaultRouteSyncProgressing: route "console" is not available at canonical host []
INFO OAuthClientSyncProgressing: route "console" is not available at canonical host []
INFO Cluster operator console Available is Unknown with NoData:
INFO Cluster operator image-registry Available is False with DeploymentNotFound: Available: The deployment does not exist
INFO ImagePrunerAvailable: Pruner CronJob has been created
INFO Cluster operator image-registry Progressing is True with Error: Progressing: Unable to apply resources: unable to sync storage configuration: unable to get cluster minted credentials "openshift-image-registry/installer-cloud-credentials": secret "installer-cloud-credentials" not found
ERROR Cluster operator image-registry Degraded is True with Unavailable: Degraded: The deployment does not exist
INFO Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available.
INFO Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available.
ERROR Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: ingresscontroller "default" is degraded: DegradedConditions: One or more other status conditions indicate a degraded state: PodsScheduled=False (PodsNotScheduled: Some pods are not scheduled: Pod "router-default-6d756547b5-745qp" cannot be scheduled: 0/3 nodes are available: 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate. Pod "router-default-6d756547b5-j9948" cannot be scheduled: 0/3 nodes are available: 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate. Make sure you have sufficient worker nodes.), DeploymentAvailable=False (DeploymentUnavailable: The deployment has Available status condition set to False (reason: MinimumReplicasUnavailable) with message: Deployment does not have minimum availability.), DeploymentReplicasMinAvailable=False (DeploymentMinimumReplicasNotMet: 0/2 of replicas are available, max unavailable is 1), DNSReady=False (NoZones: The record isn't present in any zones.)
INFO Cluster operator insights Disabled is False with AsExpected:
INFO Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available
INFO Cluster operator monitoring Available is False with :
INFO Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack.
ERROR Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager Route to become ready failed: waiting for route openshift-monitoring/alertmanager-main: no status available
INFO Cluster operator network ManagementStateDegraded is False with :
INFO Cluster operator network Progressing is True with Deploying: Deployment "openshift-network-diagnostics/network-check-source" is not available (awaiting 1 nodes)
INFO Cluster operator storage Progressing is True with AWSEBSCSIDriverOperatorCR_AWSEBSDriverControllerServiceController_Deploying: AWSEBSCSIDriverOperatorCRProgressing: AWSEBSDriverControllerServiceControllerProgressing: Waiting for Deployment to deploy pods
INFO Cluster operator storage Available is False with AWSEBSCSIDriverOperatorCR_AWSEBSDriverControllerServiceController_Deploying: AWSEBSCSIDriverOperatorCRAvailable: AWSEBSDriverControllerServiceControllerAvailable: Waiting for Deployment to deploy the CSI Controller Service
ERROR Cluster initialization failed because one or more operators are not functioning properly.
ERROR The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
ERROR https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
ERROR The 'wait-for install-complete' subcommand can then be used to continue the installation
FATAL failed to initialize the cluster: Some cluster operators are still updating: authentication, console, image-registry, ingress, kube-storage-version-migrator, monitoring, storage`

**Comment by staebler** [comment]
```
ERROR Cluster operator cloud-credential Degraded is True with CredentialsFailing: 5 of 5 credentials requests are failing to sync.
INFO Cluster operator cloud-credential Progressing is True with Reconciling: 0 of 5 credentials requests provisioned, 5 reporting errors.
```
The cloud-credential-operator is not able to mint new IAM roles. This is blocking other operators from being able to access the AWS API. Does your IAM user have permissions to mint IAM roles? If not, you can try using `Passthrough` credentials mode instead. In that mode, the operators in the cluster will all use your IAM user when accessing the AWS API.

**Comment by ShadySQL** [comment]
Is that a CLI option or some new field I need to add to the install-config.yml?

**Comment by ShadySQL** [comment]
Made the change and now it works! Thanks a ton for your help and support!
