### ISSUE TITLE
Ansible File - Password Stored None Encrypted

### ISSUE THREAD

**Issue by penguinpages** [openshift/installer#4768]
# Version
4.7.0
```console
$ openshift-install version
openshift-install 4.5.4
built from commit 01f5643a02f154246fab0923f8828aa9ae3b76fb
release image quay.io/openshift-release-dev/ocp-release@sha256:02dfcae8f6a67e715380542654c952c981c59604b1ba7f569b13b9e5d0fbbed3
```

# Platform:
vSphere

<!--
Please specify:
* IPI

# What happened?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?
# Build cluster configuration with wizard.  Note to use cluster instance.  Ex: os03
./openshift-install create install-config --dir=/home/core/$cluster  --log-level=debug
vi install-config.yaml 

<<<snip>>>
  vsphere:
    apiVIP: 172.20.12.23
    cluster: Production
    datacenter: SolutionCenter
    defaultDatastore: v90001_dr_vmfs00
    ingressVIP: 172.20.12.33
    network: 012server
    password: Pa55w0rd!
    username: openshift@acme.com
<<<snip>>>

Most people save off this Ansible playbook for use later, as a means to re-deploy, or to share with support etc..

Passwords saved in clear text is bad form.

Suggestion:  Your keying IPI deployment to use SSH key of installation user on bastion node.  So this "key selection" is being used in cluster ignition.  So use that key to do an encryption of the password within the playbook.

**Comment by staebler** [comment]
@penguinpages Please provide more details.

**Comment by staebler** [comment]
The installer does not use any ansible. The install-config.yaml file does not have anything to do with ansible. The install-config.yaml is just input into the installer. The wizard is one means of creating that input file, but you do not have to go through the wizard.

If you are backing you install-config.yaml, you are welcome to omit the password in your backward and then insert the password into the file that you supply to the installer.

**Comment by penguinpages** [comment]
well.   Then change feature request to "don't store passwords in plain text files"  ... how you change your methods for save and then later recompile into the Terraform manifests etc....   Its just bad form.
