### ISSUE TITLE
AWS install fails if controlPlane.Platform.AWS.IAMRole is missing from install-config

### ISSUE THREAD

**Issue by sallyom** [openshift/installer#4816]
# Version

```console
$ openshift-install version
openshift-install 4.8.0-0.ci-2021-04-03-201542
built from commit af24457b32af35787a0ec84c3b2037877ef27a33
release image registry.ci.openshift.org/ocp/release@sha256:2bc95d8ed5de089aa88175132e641c894e00824ea30f47138f7bfdec490416b3
```

# Platform:
aws

# What happened?

The install-config created from `openshift-install create install-config` does not include or ask for a controlPlane.Platform.AWS.IAMRole.
When launching with the install-config, I'm getting a nil pointer dereference panic at this line:
https://github.com/openshift/installer/blob/master/pkg/asset/cluster/aws/aws.go#L93

# How to reproduce it (as minimally and precisely as possible)?
download latest CI-release and:

```console
$ openshift-install create install-config --dir testdir
$ openshift-install create cluster --dir testdir
```

**Comment by staebler** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1946119

**Comment by patrickdillon** [comment]
/close
Fix has merged
