### ISSUE TITLE
Buggy role_assignment in terraform-provider-azurerm

### ISSUE THREAD

**Issue by YoavCohen** [openshift/installer#4829]
# Version

```console
$ openshift-install version
built from commit e15f17c958b4a04e770c0cfe758ca69452874508
release image quay.io/openshift-release-dev/ocp-release@sha256:0a4c44daf1666f069258aa983a66afa2f3998b78ced79faa6174e0a0f438f0a5
```

# Platform:

# What happened?

Enter text here.
When trying to build a cluster on Azure using installer getting the follwing error:
ERROR Error: authorization.RoleAssignmentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="RoleAssignmentNotFound" Message="The role assignment '9f6023cc-81c9-7914-5c89-03cc7ea74ea1' is not found."
ERROR
ERROR   on ../../tmp/openshift-install-935734395/main.tf line 161, in resource "azurerm_role_assignment" "main":
ERROR  161: resource "azurerm_role_assignment" "main" …
# What you expected to happen?

Works fine

# How to reproduce it (as minimally and precisely as possible)?

Just try to install openshift on Azure

```console
./openshift-install create cluster --dir=./ --log-level=debug
```

# Anything else we need to know?

Looks like You are using old TF provider, a fix for this bug was already merged here:
https://github.com/terraform-providers/terraform-provider-azurerm/pull/9698

Can you please specify how to use the newer version or fix it?

Thanks

# References

- enter text here.

**Comment by staebler** [comment]
Thanks for the report. This will be fixed by https://github.com/openshift/installer/pull/4729.
