### ISSUE TITLE
kubelet uses self-signed serving certs

### ISSUE THREAD

**Issue by mfojtik** [openshift/installer#486]
After #420 merged, we are not setting the `ca` field for `kubeletClientInfo` which will cause the kube-apiserver->kubelet communication is insecure because the kubelet identity is not checked.

/assign @sjenning

**Comment by ashcrow** [comment]
Is this still an issue? We seem to be seeing the following now:

```
Nov 30 20:19:34 test1-master-0 hyperkube[2875]: I1130 20:19:34.843859    2875 logs.go:49] http: TLS handshake error from 192.168.126.51:49656: remote error: tls: bad certificate
Nov 30 20:19:45 test1-master-0 hyperkube[2875]: I1130 20:19:45.660350    2875 logs.go:49] http: TLS handshake error from 192.168.126.51:49698: remote error: tls: bad certificate
```

**Comment by sjenning** [comment]
this is the last bit https://github.com/openshift/machine-config-operator/pull/187
