### ISSUE TITLE
Configure Availability Set for workers on Azure?

### ISSUE THREAD

**Issue by YoavCohen** [openshift/installer#4863]
# Version

```console
$ openshift-install version
built from commit e15f17c958b4a04e770c0cfe758ca69452874508
release image quay.io/openshift-release-dev/ocp-release@sha256:0a4c44daf1666f069258aa983a66afa2f3998b78ced79faa6174e0a0f438f0a5
```

# Platform:

# What happened?
How can I configure Availability Set for workers on Azure?
# What you expected to happen?

Able to configure the Availability Set for the Azure vms.
# How to reproduce it (as minimally and precisely as possible)?

..

```console
./openshift-install create cluster --dir=./ --log-level=debug
```

# Anything else we need to know?

We need to set the Availability SEt of the VMs on Azure, this can't be changed later and blocking us as we need all workers to be in the same Availability Set.

Thanks

Thanks

# References

- enter text here.

**Comment by staebler** [comment]
OpenShift does not use availability sets when the installer creates the infrastructure. You may provision the infrastructure yourself and use availability sets.
See https://docs.openshift.com/container-platform/4.7/installing/installing_azure/installing-azure-user-infra.html for an example of how to provision the infrastructure yourself.
