### ISSUE TITLE
remove temporary bootkube kube-proxy and kube-dns manifests

### ISSUE THREAD

**Issue by mfojtik** [openshift/installer#487]
#420 introduced https://github.com/openshift/installer/blob/master/pkg/asset/ignition/bootstrap/content/bootkube_temporary.go to workaround the fact that kube-core operator is no longer rendering these bootstrap manifests. They seems to be needed for the `bootkube start` in order to bring the tectonic-network operator to life (it needs kube-proxy to talk to API server).

Should be resolved by @ironcladlou and @squeed

**Comment by ironcladlou** [comment]
https://github.com/openshift/installer/pull/548
