### ISSUE TITLE
NTP and Timezone setting

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/installer#4885]
# Version
openshift-install 4.7.0-0.okd-2021-04-24-103438
```console
$ openshift-install version
openshift-install 4.7.0-0.okd-2021-04-24-103438
```

# Platform:

Barametal 

# What happened?

After cluster install time is set to UTC and need to manualy change it to correct time zone. 
Can't find any config to make it correct

# What you expected to happen?

Install cluster with specific timezone

**Comment by staebler** [comment]
OpenShift does not support configuring the timezone for the nodes.

**Comment by ZrytyADHD** [comment]
Ok but there is a possible to set it during install somehow ? Installer always set time to UTC but differens is 2h betwen my local time and time in OKD cluster.

**Comment by staebler** [comment]
No, there is no option to configure it during install either. What problem are you having with the nodes using UTC as the timezone?

**Comment by ZrytyADHD** [comment]
The problem is very simple my timezone is Europe/Warsaw Time. When we investigate logs from apps the time in it should be the same as we use. It's help to investigate when something go wrong.
Maybe in future release will be a option to set correct time zone during install.
