### ISSUE TITLE
Openshift 4.7.4 IPI failed to upload the OVA to ESXi host 

### ISSUE THREAD

**Issue by vishnoisuresh** [openshift/installer#4951]
# Version

```console
$ openshift-install version
openshift-install 4.7.9
built from commit fae650e24e7036b333b2b2d9dfb5a08a29cd07b1
release image quay.io/openshift-release-dev/ocp-release@sha256:dd75546170e65d7d17130de10a6ffeb425f960399640632cbc8426b9da338458

```

# Platform:
```
on VMWARE  using IPI
```

# What happened?

Excuse my ignorance with vmware best pracitces, why would installer need to upload the OVA directly to ESXI host rather than giving OVA to vCenter. Besides authentication credential of vCenter are provided to installer.   In my environment, The jumpbox is not allowed to directly connect with esxi hosts due to firewall. 

```
INFO Consuming Install Config from target directory
INFO Obtaining RHCOS image file from 'https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7/47.83.202103251640-0/x86_64/rhcos-47.83.202103251640-0-vmware.x86_64.ova?sha256=6ac67b43ed6fe25cbe4b01b8f8900a9a5bc0bb6a9894d40be46b994cda906efd'
INFO The file was found in cache: /home/suresh.vishnoi/.cache/openshift-installer/image_cache/d49901108cb7e7981a91c8cdcfb0cf2c. Reusing...
INFO Creating infrastructure resources...
ERROR
ERROR Error: failed to upload: Post "https://ESXI_HOST.example/nfc/524ac856-a366-7216-2a4a-7525775598b9/disk-0.vmdk": dial tcp 10.58.24.23:443: connect: connection timed out
ERROR
ERROR   on ../../tmp/openshift-install-431769835/main.tf line 43, in resource "vsphereprivate_import_ova" "import":
ERROR   43: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```

# What you expected to happen?

Upload the  OVA using vCenter rather than by passing it.    I would like to understand, what are the reasons to upload ova directly to host 
as its commmented here https://github.com/openshift/installer/pull/3299/commits/ff35ac03721331c65c27b1c17eee3a8a2b8b6fca#diff-f90cf5cba5c9f06892b8eae9a722872a76fc4bd1fe7e4c758a795febd60aca18R176-R178

**Comment by jcpowermac** [comment]
@vishnoisuresh there is no public method of using vCenter as a proxy to the ESXi for uploading the vmdk. I know this is confusing because when you import via vCenter UI you won't have this problem.

Using `govc import.ova` as an example, I added `spew.Dump()` to the Upload

```
 func (cmd *ovfx) Upload(ctx context.Context, lease *nfc.Lease, item nfc.FileItem) error {
+
+       spew.Dump(lease)
+       spew.Dump(item)
+
```

You will see the `URL` for ESXi, this is the location where the VMDK upload happens.

```
➜  Development ~/go/bin/govc import.ova -options=rhcos.json rhcos-4.7.7-x86_64-vmware.x86_64.ova
(*nfc.Lease)(0xc00040cc60)(HttpNfcLease:session[5299280d-31dd-044c-ca43-f5198e7a41ff]529fd4da-3ac6-2201-c3e2-10d57a556b5c)
(nfc.FileItem) {
 OvfFileItem: (types.OvfFileItem) {
  DynamicData: (types.DynamicData) {
  },
  DeviceId: (string) (len=55) "/jcallen-rhcos-import-test/ParaVirtualSCSIController0:0",
  Path: (string) (len=9) "disk.vmdk",
  CompressionMethod: (string) "",
  ChunkSize: (int64) 0,
  Size: (int64) 974496768,
  CimType: (int32) 17,
  Create: (bool) false
 },
 URL: (*url.URL)(0xc00009cab0)(https://10.3.32.8/nfc/52255075-4350-1df5-7615-21f371beaf29/disk-0.vmdk),
 ch: (chan progress.Report) 0xc000103080
}
[21-05-21 11:56:24] Uploading disk.vmdk... OK
➜  Development
```

**Comment by jcpowermac** [comment]
> I'm currently dealing with exactly the same problem. Is it possible to upload the OVA file manually to vSphere, either via govc or web interface, and then tell the openshift-install tool to skip the upload and use the existing OVA on vSphere? I know this is nearly going the UPI approach.

@Aldjinn unfortunately no.

**Comment by Aldjinn** [comment]
Presenting this topic and a little bit whining got me the connection the to vSphere hosts and I was able to perform an IPI installation and it worked like a charm. 

No comparison to manual UPI installation I've done before.  😉

**Comment by jcpowermac** [comment]
I think this is ok to close. If not please reopen
/close
