### ISSUE TITLE
Specify which minor version of OCP 4.x to install

### ISSUE THREAD

**Issue by anraghun** [openshift/installer#4954]
# Version

```console
$ openshift-install version
./openshift-install 4.7.11
built from commit 47dadceff29de54c5d6c2315c7f109ea86cdf8e6
release image quay.io/openshift-release-dev/ocp-release@sha256:8c3f5392ac933cd520b4dce560e007f2472d2d943de14c29cbbb40c72ae44e4c
```

# Platform: azure

IPI Installer

# What happened?

While running `openshift-installer create cluster`, I'm not given the option to specify the minor version of OCP I wish to install. I also checked the [installer-config docs](https://github.com/openshift/installer/blob/master/docs/user/customization.md#platform-customization) but couldn't find a parameter to specify which minor version I want to install.

# What you expected to happen?

While running `openshift-installer create cluster`, there should be an optional parameter to install a specific minor version.

**Comment by staebler** [comment]
The installer is built to install a specific version. If you want to install a different version, then you need to use a different installer.

If you look at the output of `openshift-install version` above, you can see that it is built to install OpenShift 4.7.11.

**Comment by anraghun** [comment]
@staebler Thanks for your response. Is there a mapping that indicates which version of the installer provisions which version of ocp? For instance, which versions of the installer should I use to install 4.6.x and 4.5.x versions of OCP?

**Comment by staebler** [comment]
https://versions.openshift.tips/

**Comment by staebler** [comment]
> Will I have to clone a specific release/branch/commit of the repo and build it, or are the binaries for each version available to download?

The binaries for each version are available to download.

**Comment by anraghun** [comment]
@staebler Thanks for sharing this. This helps. Just a tiny feedback, the `openshift-installer` links for linux (at least) are broken in the page you shared above. 

This is the link I got from the openshift cluster manager:
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-install-linux.tar.gz

And this is the link from the page you shared:
https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.6.29/openshift-install-linux.tar.gz

Removing the "x86_64" from the URL path did the trick.
