### ISSUE TITLE
openshift 4.8.0-0.nightly-2021-04-15-152737 IPI failed due to the continuous restart of the Master

### ISSUE THREAD

**Issue by zhouhao3** [openshift/installer#4963]
# Version

```console
$ openshift-baremetal-install  version
openshift-baremetal-install 4.8.0-0.nightly-2021-04-15-152737
built from commit d0462d8b5074448e1917da7f0a5d7a904bd60359
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:70fe4f1a828dcbe493dce6d199eb5d9e76300d053c477f0f4b4577ef7b7d2934

```

# Platform:

Baremetal

* IPI 

# What happened?

When the Master is successfully deployed, the VM is deleted and related services are migrated to the Master. During the worker deployment phase, the Master restarts in stages (restarts every few minutes). This will result in the inability to access the ironic service and the deployment will fail.

```
E0526 14:41:26.719722 1584040 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: failed to list *v1.ClusterVersion: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&resourceVersion=39250": dial tcp 192.168.30.201:6443: connect: no route to host
E0526 14:42:21.183589 1584040 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: failed to list *v1.ClusterVersion: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&resourceVersion=39250": dial tcp 192.168.30.201:6443: connect: no route to host
E0526 14:43:15.455763 1584040 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: failed to list *v1.ClusterVersion: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&resourceVersion=39250": dial tcp 192.168.30.201:6443: connect: no route to host
E0526 14:44:08.447631 1584040 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: failed to list *v1.ClusterVersion: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&resourceVersion=39250": dial tcp 192.168.30.201:6443: connect: no route to host
E0526 14:44:49.983687 1584040 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: failed to list *v1.ClusterVersion: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&resourceVersion=39250": dial tcp 192.168.30.201:6443: connect: no route to host
E0526 14:45:32.095693 1584040 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: failed to list *v1.ClusterVersion: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusterversions?fieldSelector=metadata.name%3Dversion&resourceVersion=39250": dial tcp 192.168.30.201:6443: connect: no route to host
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.openshift.zz.local:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 192.168.30.201:6443: connect: no route to host 
ERROR Cluster initialization failed because one or more operators are not functioning properly. 
ERROR The cluster should be accessible for troubleshooting as detailed in the documentation linked below, 
ERROR https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html 
ERROR The 'wait-for install-complete' subcommand can then be used to continue the installation 
FATAL failed to initialize the cluster: Working towards 4.8.0-0.nightly-2021-04-15-152737: 655 of 677 done (96% complete) 
```

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

1. We manually merged related PRs during testing, circumventing known [issue](https://github.com/openshift/installer/issues/4857).
2. Because of [IPMI credentials,](https://github.com/metal3-io/baremetal-operator/issues/879) we cannot use the latest night version for testing. We hope that [PR880](https://github.com/metal3-io/baremetal-operator/pull/880) can be merged into openshift as soon as possible so that the latest version can be used for testing.
3. We are currently locating in which night version this issue was introduced. If there is new progress, we will update this issue.

# References

- enter text here.

**Comment by zhouhao3** [comment]
I tried to use the latest night version( 4.8.0-0.nightly-2021-05-27-195432 ) to test and found that this issue will still appear.

**Comment by zhouhao3** [comment]
At present, I locate the version where this error occurs for the first time is `4.8.0-0.nightly-2021-02-23-122306`, which uses the same `openshift/install` commit as the previous version（`4.8.0-0.nightly-2021-02-23-092027`）. Comparing the mirror images used by the two versions, I found that only `console` and `ironic` are different. Based on the error phenomenon, I think this should be caused by `ironic`.
I tried to replace the ironic image of `4.8.0-0.nightly-2021-02-23-122306`, but the changed image did not take effect when the worker was deployed. I am currently comparing the two ironic images try to find out the cause of the error.

**Comment by rhjanders** [comment]
@zhouhao3 https://github.com/openshift/installer/pull/4900 has merged, are you able to retest and let us know if this PR is still needed?

**Comment by zhouhao3** [comment]
https://github.com/openshift/installer/pull/4900 and  [135](https://github.com/openshift/baremetal-runtimecfg/pull/135)  have resolved this issue, and I will close this issue.

**Comment by zhouhao3** [comment]
Sorry for the operation error.
4900 did not solve this issue. At present, we have investigated the cause of this issue to be unique to iRMC devices. Because ironic will obtain the [Bios settings](https://opendev.org/openstack/ironic/src/branch/master/ironic/drivers/modules/irmc/bios.py#L115) when managing the node, this will restart the iRMC machine, which includes the Master deployed with ironic. After the restart, the node will be managed again, and then restart, which will lead to an infinite loop.
We are currently solving this problem.
