### ISSUE TITLE
AWS env loading fails with awsume

### ISSUE THREAD

**Issue by alecholmez** [openshift/installer#5012]
# Version

```console
$ openshift-install version

openshift-install unreleased-master-4666-g4190cad024d0e3d23a7121b48666554776dfc2f6
built from commit 4190cad024d0e3d23a7121b48666554776dfc2f6
release image registry.ci.openshift.org/origin/release:4.8
```

# Platform:
aws

UPI

# What happened?

When trying to generate manifests with a role assumed by awsume, we receive this error:
```
alecholmes:openshift alecholmes$ openshift-install create manifests
INFO Credentials loaded from default AWS environment variables
FATAL failed to fetch Openshift Manifests: failed to generate asset "Openshift Manifests": AWS credentials provided by EnvConfigCredentials are not valid for default credentials mode
```

# What you expected to happen?

We expected the manifests to generate properly.

# How to reproduce it (as minimally and precisely as possible)?

1. Assume a role from `awsume`
2. Run `openshift-install create manifests`

**Comment by staebler** [comment]
You cannot use temporary credentials with the default mint credentials mode. If you are using temporary credentials, then you must run in manual mode by setting `credentialsMode: Manual` in the install-config.yaml. Note that you would then be responsible for supplying credentials secrets for the `CredentialsRequest` resources in the cluster.

**Comment by dontlaugh** [comment]
@staebler is `CredentialsRequest` a CRD?

**Comment by staebler** [comment]
Yes, `credentialsrequest.cloudcredentialoperator.openshift.io`. The CRs are in the openshift-cloud-credential-operator namespace.
