### ISSUE TITLE
bootkube mcd binds to ipv6 on RHEL

### ISSUE THREAD

**Issue by michaelgugino** [openshift/installer#502]
openshift/installer @ d50325798d92047b9ae96f16ae2f69e6893d71f5

[root@tx-bootstrap ~]# ss -ln | grep 49500
tcp    LISTEN     0      128      :::49500                :::*

This results in failure of other hosts to properly retrieve configs.

**Comment by wking** [comment]
Is this an installer issue?  It feels more of a [bootkube][1] or [machine-config operator][2] issue.  Also, can you provide steps to reproduce?  You haven't even said if this is on AWS, libvirt, or both ;).  See [the issue template][3] for the sort of things that help.

[1]: https://github.com/kubernetes-incubator/bootkube/
[2]: https://github.com/openshift/machine-config-operator/
[3]: https://github.com/openshift/installer/blob/master/.github/ISSUE_TEMPLATE.md
