### ISSUE TITLE
libvirt based installation failing on ARM 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [openshift/installer#5035]
libvirt based installation failing on ARM.

libvirt mentioned in install-config.yaml is not recognized. 

I could see that the PR #4870  is merged and the commit is added in openshift-install. 

# Version

```console
$ openshift-install version
openshift-install 4.9.0-0.nightly-arm64-2021-06-26-045833
built from commit 8e3a3203a6e06536a50da877a87944edfc2fb92e
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:68381f9b05b9fcce3c7c3a7437375fa9f044230fc0ed7a0b5157212f9e87ff86

```

# Platform:
libvirt

* IPI (automated install with `openshift-install`. If you don't know, then it's IPI)

# What happened?

FATAL failed to fetch Metadata: failed to load asset "Install Config": invalid "install-config.yaml" file: platform: Invalid value: "libvirt": must specify one of the platforms (aws, azure, baremetal, gcp, ibmcloud, kubevirt, none, openstack, ovirt, vsphere) 

# What you expected to happen?

libvirt based installation should go through 

# How to reproduce it (as minimally and precisely as possible)?

```
$ openshift-install create cluster 
```

# References

**Comment by SaravanaStorageNetwork** [comment]
@yselkowitz  @Prashanth684  PTAL

**Comment by Prashanth684** [comment]
Did you build the installer yourself ? Did you build with 'TAGS=libvirt' env ? Libvirt is not an officially supported platform so you have to provide this env variable.

**Comment by Prashanth684** [comment]
Ah.. ok I see the installer version mentioned above . So the openshift-installer extracted from the payload does not support libvirt . But the baremetal installer in the payload supports libvirt. That must be used.
