### ISSUE TITLE
Ability to change cluster resources with OpenShift IPI Deployment on VMware 7.02

### ISSUE THREAD

**Issue by linebackj** [openshift/installer#5077]
# 4.7 and later

```console
$ openshift-install version
4.7 and later
```

# Platform:

# What happened?

When deploying on a DL380 GEN8 Server with 96GB memory and dual 8 core socket machine the install fails because not enough resources on the ESXi host.  The failure code below is because not enough memory and CPU resources to deploy the cluster.  This is not a Storage or Username/Password issue so not enough hardware resources.
ERROR                                              
ERROR Error: rpc error: code = Unavailable desc = transport is closing 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change

# What you expected to happen?

I am using an install-config.yaml file and it would be good to have a parameter to reduce the vCPU's and Memory for the control or worker nodes.  

# How to reproduce it (as minimally and precisely as possible)?
Using another hardware platform a Dell server with 32 cores and 256GB of memory works fine.

```console
$ ./openshift-install create cluster --log-level=debug
```

# Anything else we need to know?

It would be good to have the ability to control the sizing of the worker and control nodes from a storage sizing, vCPU and Memory point of view since installing on top of a single non HA piece of hardware for test and dev.

# References

**Comment by patrickdillon** [comment]
You should be able to modify all of these attributes in the machine pool. Please check https://github.com/openshift/installer/blob/master/docs/user/vsphere/customization.md#machine-pools and either close this issue or let us know how this does not satisfy your needs.

**Comment by linebackj** [comment]
found workaround.
