### ISSUE TITLE
cluster-kube-apiserver-operator unknown flag --infra-config-file

### ISSUE THREAD

**Issue by ehsjoar** [openshift/installer#5081]
# Version: built from commit cd9b77b47192554473b015657a117ce663920a1e

```console
$ openshift-install version
<your output here>
```

# Platform: libvirt

IPI

# What happened?

Bootstrap node fails with:
Jul 14 12:24:01 ocp-whrb7-bootstrap bootkube.sh[2271]: Rendering Kubernetes API server core manifests...
Jul 14 12:24:08 ocp-whrb7-bootstrap bootkube.sh[2271]: Error: unknown flag: --infra-config-file
Jul 14 12:24:08 ocp-whrb7-bootstrap bootkube.sh[2271]: Usage:
Jul 14 12:24:08 ocp-whrb7-bootstrap bootkube.sh[2271]:   cluster-kube-apiserver-operator render [flags]

Seems like commit a5c73e97a3fcaa12bfda4db972bb54854853a3da added that flag and it is not supported

# What you expected to happen?

Well, I expected it to go further in the process

# How to reproduce it (as minimally and precisely as possible)?
Follow https://github.com/openshift/installer/tree/master/docs/dev/libvirt

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by patrickdillon** [comment]
You did not include the version in your issue report but in general this error occurs when you use an outdated release image.

The bootkube script has been updated to use a flag not present in the release image you are using. 

So you need to use a more recent image or use an installer version that is pinned to a release.

**Comment by nelsonspbr** [comment]
I just had the same problem using `openshift/installer` `master` branch.

```
[nelson@nelson-206-ctr master]$ ./bin/openshift-install --dir=cluster-0/ create cluster
INFO Consuming Install Config from target directory
INFO Obtaining RHCOS image file from 'https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.8/48.84.202105190318-0/x86_64/rhcos-48.84.202105190318-0-qemu.x86_64.qcow2.gz?sha256=84683a75c0e3d164c1d4a95448e142490a0bf91ff07076bff2b3bbc209c6c368'
INFO Creating infrastructure resources...
INFO Waiting up to 20m0s for the Kubernetes API at https://api.test1.tt.testing:6443...
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.test1.tt.testing:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 192.168.126.10:6443: connect: connection refused
INFO Pulling debug logs from the bootstrap machine
INFO Bootstrap gather logs captured here "/home/nelson/github.com/openshift/installer/master/cluster-0/log-bundle-20210715134654.tar.gz"
ERROR Bootstrap failed to complete: Get "https://api.test1.tt.testing:6443/version?timeout=32s": dial tcp 192.168.126.11:6443: connect: connection refused
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
FATAL Bootstrap failed to complete
```

Looking at `bootstrap/pods/kube-apiserver-render-4a491cee789a.log`:

```
Error: unknown flag: --infra-config-file
Usage:
  cluster-kube-apiserver-operator render [flags]
...
```

I am trying one more thing before switching to a release version.

**Comment by patrickdillon** [comment]
Master branch is aligned with OKD by default. When using master, you need to use a recent image such as a nightly from here https://amd64.ocp.releases.ci.openshift.org/ for which you will need a pull secret https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/#how-do-i-log-in-to-pull-images-that-require-authentication

**Comment by nelsonspbr** [comment]
I was actually about to test `release-4.10` but I noticed it is the same commit (?) from master. Trying `release-4.8` right now, which matches what I see from the installer output (from any version I have built):

```
[nelson@nelson-206-ctr release-4.8]$ ./bin/openshift-install version
./bin/openshift-install unreleased-master-4657-ga5ddd2dd6c72d8a5ea0a5f17acd8b964b6a3d1be
built from commit a5ddd2dd6c72d8a5ea0a5f17acd8b964b6a3d1be
release image registry.ci.openshift.org/origin/release:4.8
```

Compare this to what I get from `master`:

```
[nelson@nelson-206-ctr master]$ ./bin/openshift-install version
./bin/openshift-install unreleased-master-4808-g252facf5e6e1238ee60b5f78607214e8691a3eab
built from commit 252facf5e6e1238ee60b5f78607214e8691a3eab
release image registry.ci.openshift.org/origin/release:4.8
```

Or ` release-4.10`:

```
[nelson@nelson-206-ctr release-4.10]$ ./bin/openshift-install version
./bin/openshift-install unreleased-master-4808-g252facf5e6e1238ee60b5f78607214e8691a3eab
built from commit 252facf5e6e1238ee60b5f78607214e8691a3eab
release image registry.ci.openshift.org/origin/release:4.8
```

**Comment by nelsonspbr** [comment]
@patrickdillon Thanks for the pointer Patrick, I will try that if what I am trying now does not work. I do not **really** need the latest version, I think, so if 4.8 works it is ok.

**Comment by patrickdillon** [comment]
> @patrickdillon Thanks for the pointer Patrick, I will try that if what I am trying now does not work. I do not **really** need the latest version, I think, so if 4.8 works it is ok.

If you do not need the latest, it is recommended to use a stable release, then you don't have to deal

**Comment by patrickdillon** [comment]
You should only work off master if you need to, otherwise it is a simpler workflow to use the most recent stable release.

Please let us know how it goes and close this issue if your problem has been resolved.

**Comment by ehsjoar** [comment]
Hi Patrick,

Sorry for the late reply. I didn't have time to look at this till today.

When I used 4.8 it worked (well I have other problems now, but it didn't
choke on the --infra-config-file) so feel free to close it. Perhaps we
should update
https://github.com/openshift/installer/tree/master/docs/dev/libvirt ?

Cheers,

// Jonas
