### ISSUE TITLE
Password authentication on Azure IPI VMs

### ISSUE THREAD

**Issue by kitforbes** [openshift/installer#5085]
# Version

```console
$ openshift-install version
4.8.0
```

# Platform:
Azure IPI

# What happened?
Not an error, more of a question around implementation choice. My client's security team have a test which looks to see if a VM in Azure was created with this setting enabled or not:

https://github.com/openshift/installer/blob/252facf5e6e1238ee60b5f78607214e8691a3eab/data/data/azure/master/master.tf#L98

Their test looks to see if `disablePasswordAuthentication` is `false`. As this is static and never changes, the test is fairly meaningless

```console
$ az vm show -g some-rg -n some-vm --query osProfile.linuxConfiguration.disablePasswordAuthentication
false
```

Is password authentication needed as part of the Ignition process? I have confirmed that the nodes are disabling password authentication in the `/etc/ssh/sshd_config` file, so I know that there is not a real issue here.

# What you expected to happen?

n/a

# Anything else we need to know?

n/a

# References

n/a

**Comment by patrickdillon** [comment]
This is an interesting issue, and I believe it might be possible to switch `disable_password_authentication` to `true`. I know of no compelling reason to keep it false, and we should experiment with changing that value.

**Comment by staebler** [comment]
Azure requires that you either provide an admin password or an admin ssh key for the VM. We could disable the password and provide an ssh key instead. However, the OS would ultimately not use either. Since we are using RHCOS, the Azure agent is not being installed on the VM, so Azure is not able to set admin password or ssh key anyway.

**Comment by kitforbes** [comment]
If the admin password is unused as well, then perhaps a junk value could be provided for the key? It would satisfy the Azure Security Centre check. Happy for this yo be closed though.
