### ISSUE TITLE
Master Node different rendered machine-config first deploy

### ISSUE THREAD

**Issue by Ralph3223** [openshift/installer#5086]
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-4787-g13fcd1b99e0b54baf33fa89f26de376028b1a739-dirty
built from commit 13fcd1b99e0b54baf33fa89f26de376028b1a739
release image registry.ci.openshift.org/origin/release:4.8
```

# Platform:
Libvirt

# What happened?

I followed the instruction at https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md to create a OpenShift cluster lab. The command 'openshift-install create cluster --log-level=debug' marks machine-config for master node as degraded and cluster creation fails.

Output: oc get mcp
```
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master                                                      False     True       True       1              0                   0                     1                      13m
```
Output: oc get mc
```
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
00-worker                                          2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
01-master-container-runtime                        2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
01-master-kubelet                                  2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
01-worker-container-runtime                        2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
01-worker-kubelet                                  2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
99-master-generated-registries                     2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
99-master-okd-extensions                                                                      3.1.0             18m
99-master-ssh                                                                                 3.2.0             18m
99-okd-master-disable-mitigations                                                             3.1.0             18m
99-okd-worker-disable-mitigations                                                             3.1.0             18m
99-worker-generated-registries                     2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
99-worker-okd-extensions                                                                      3.1.0             18m
99-worker-ssh                                                                                 3.2.0             18m
rendered-master-832121d4539a8dd046e4fbc8edf537c2   2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
rendered-worker-31012e5de51880a98cdf04ca95e40412   2bf53cf742d10eefcda1f83fc1da158f9f5f18e1   3.2.0             14m
```
Snippet output: oc describe mcp -n master
```
Status:
  Conditions:
    Last Transition Time:  2021-07-15T13:57:25Z
    Message:               Node cluster1-cntvv-master-0 is reporting: "machineconfig.machineconfiguration.openshift.io \"rendered-master-7c6a35359d8f223e19afa4d643363fa5\" not found"
    Reason:                1 nodes are reporting degraded status on sync
```
Snipper output: oc logs -n openshift-machine-config-operator machine-config-daemon-v4qkc -c machine-config-daemon
```
I0715 13:56:30.536816   10557 node.go:24] No machineconfiguration.openshift.io/currentConfig annotation on node cluster1-cntvv-master-0: map[volumes.kubernetes.io/controller-managed-attach-detach:true], in cluster bootstrap, loading initial node annotation from /etc/machine-config-daemon/node-annotations.json
I0715 13:56:30.537310   10557 node.go:45] Setting initial node config: rendered-master-7c6a35359d8f223e19afa4d643363fa5
I0715 13:56:30.565372   10557 daemon.go:767] In bootstrap mode
E0715 13:56:30.565420   10557 writer.go:135] Marking Degraded due to: machineconfig.machineconfiguration.openshift.io "rendered-master-7c6a35359d8f223e19afa4d643363fa5" not found
```

It is not clear to me why there are two rendered machine-configs for the master:
- rendered-master-7c6a35359d8f223e19afa4d643363fa5
- rendered-master-832121d4539a8dd046e4fbc8edf537c2

# What you expected to happen?

Running OpenShift Cluster

# How to reproduce it (as minimally and precisely as possible)?

1. Create installation directory cluster_install
2. Create install-config with openshift-install create install-config
3. Create ignition-configs with openshift-install create ignition-configs
4. Create manifests with openshift-install create manifests
5. Edit openshift/99_openshift-cluster-api_master-machines-0.yaml update DomainMemory to 16384
6. Run create cluster with openshift-install create cluster --log-level=debug

# Anything else we need to know?

I updated the file data/data/libvirt/main.tf, disabled 'local_only' and added dns fowarders.

# References

**Comment by apoorvajagtap** [comment]
Hi, if you have the same cluster, can you share the following?

$ oc get mc -o json | jq -r '.items[].metadata | "\(.creationTimestamp) - \(.name)"' | grep rendered-master | sort -n
$ oc get node <affected-master> -ojson | jq .metadata.annotations

**Comment by staebler** [comment]
Could you try to match up the installer commit that you are using with the installer commit used in the OpenShift release image that you are using? I notice that you are using a 4.8 release image but building from a 4.9 commit.

**Comment by jonkstevenson** [comment]
Only applies if this happens right at install time and the master nodes are in a degraded state because they cannot find the appropriate rendered master config. Missing at install?  Huh .. who figures. Still wondering why, but didn't want to fuss with a whole tear down and rebuild. Hopefully helps someone else.

On one of the master nodes:
> cat /etc/machine-config-daemon/currentconfig | jq > /tmp/mc.yaml

If you review the file, this is the json definition of the missing rendered config. The rendered-master-xxxx name should match up to the missing rendered config shown with oc describe node master0 | grep -i machine

Now review the output of oc get mc and run the following command against a current rendered-master-xxx that exists.
> oc get mc rendered-master-xxxx -o jsonpath='{.metadata.ownerReferences[0].uid}'

This will return the uid of the rendered set, now using vi edit the file.

vi /tmp/mc.yaml ...

You will notice in the file that ownerReferences > uid  is set to ""  
Edit the file and change the following line:

   "uid":  ""   --->  "uid": "your-uid-returned-in-the-previous-command"

Now recreate the mc 
oc create -f /tmp/mc.yaml

Be patient, in a few moments the error will clear and  oc get mcp will be clean, The masters will then progress in apply the additional rendered-master-xxx configs that you currently have defined.
