### ISSUE TITLE
[4.8][regression] openshift-install vCenter value must be the domain name or IP address

### ISSUE THREAD

**Issue by piyushkv1** [openshift/installer#5126]
# Version

```console
$ openshift-install version
openshift-install 4.8.2
built from commit a5ddd2dd6c72d8a5ea0a5f17acd8b964b6a3d1be
release image quay.io/openshift-release-dev/ocp-release@sha256:0e82d17ababc79b10c10c5186920232810aeccbccf2a74c691487090a2c98ebc
```

# Platform:

vSphere

IPI
# What happened?

openshift-install with version 4.8 failed with error invalid domain of vCenter. Same is working till 4.7 version.

cat .openshift_install.log
time="2021-08-03T12:34:10Z" level=debug msg="OpenShift Installer 4.8.2"
time="2021-08-03T12:34:10Z" level=debug msg="Built from commit a5ddd2dd6c72d8a5ea0a5f17acd8b964b6a3d1be"
time="2021-08-03T12:34:10Z" level=debug msg="Fetching Master Machines..."
time="2021-08-03T12:34:10Z" level=debug msg="Loading Master Machines..."
time="2021-08-03T12:34:10Z" level=debug msg="  Loading Cluster ID..."
time="2021-08-03T12:34:10Z" level=debug msg="    Loading Install Config..."
time="2021-08-03T12:34:10Z" level=debug msg="      Loading SSH Key..."
time="2021-08-03T12:34:10Z" level=debug msg="      Loading Base Domain..."
time="2021-08-03T12:34:10Z" level=debug msg="        Loading Platform..."
time="2021-08-03T12:34:10Z" level=debug msg="      Loading Cluster Name..."
time="2021-08-03T12:34:10Z" level=debug msg="        Loading Base Domain..."
time="2021-08-03T12:34:10Z" level=debug msg="        Loading Platform..."
time="2021-08-03T12:34:10Z" level=debug msg="      Loading Networking..."
time="2021-08-03T12:34:10Z" level=debug msg="        Loading Platform..."
time="2021-08-03T12:34:10Z" level=debug msg="      Loading Pull Secret..."
time="2021-08-03T12:34:10Z" level=debug msg="      Loading Platform..."
time="2021-08-03T12:34:10Z" level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: platform.vsphere.vCenter: Invalid value: \"192-162-213-81.private.vmware.com.\": must be the domain name or IP address of the vCenter"

**Comment by salv-orlando** [comment]
Hi there, it appears that host name used for vCenter are not allowing dots (.) as the following commit made the value compliant with RFC1123 as it adds a function that ends up calling validateSubdomain (https://github.com/openshift/installer/blob/master/pkg/validate/validate.go#L49)

commit 7c98e02d52cdd8da0a9892429ae6b1e8edef9ebd
Date:   Wed Mar 3 11:32:34 2021 -0500
 
    vsphere: Validate vcenter user input to match RFC standards
    
    Vcenter input must always only be the hostname yet it is possible
    for the user to provide other types of input like URLs. URLs would
    cause an error to occur only during the time of cluster creation
    as connection to the vcenter would succeed.
    
    Adding a validation check for the user input for the vcenter value
    so that it conforms to the RFC-1035 standard and forces the user
    to re-enter the value rather than throw an error during cluster
    creation.

Was that intentional considering that instead the commit message mentions compliance with RFC1035?

**Comment by salv-orlando** [comment]
Please note that the hostname in the PR report is probably not a valid example  as it has a trailing dot.
The only open question about this issue is whether compliance should be with RFC1123 or RFC1035.

**Comment by rna-afk** [comment]
I was under the impression that the only difference between the two was that RFC-1035 started with a lowercase character and all the others were the same. The code follows RFC-1035 if I am not wrong.

**Comment by gonoph** [comment]
RFC1123 Section 2.1

```The syntax of a legal Internet host name was specified in RFC-952 [DNS:4]. One aspect of host name syntax is hereby changed: the restriction on the first character is relaxed to allow either a letter or a digit. Host software MUST support this more liberal syntax.```

**Host software MUST support this more liberal syntax.**

If the Openshift installer is enforcing RFC for host name validation, then it should be enforcing up to date RFC's.

**Comment by rna-afk** [comment]
Which would be true for RFC-1123 and not RFC-1035 that we use?

**Comment by gonoph** [comment]
Just my opinion, but if you're going to commit *new* code to enforce RFCs, then it would make sense to enforce the full set of RFCs that describe the scope "aka hostnames" of what you're trying to do, rather than a subset of RFCs that in essence manifest outdated behaviors.
