### ISSUE TITLE
Failed at "Waiting up to 30m0s for bootstrapping to complete..."

### ISSUE THREAD

**Issue by darksyud** [openshift/installer#5128]
# Version 

```console
$ openshift-install version
<./openshift-install 4.7.22
built from commit 23a2fe80a021a19ab4364904f6928a1f8c715dc0
release image quay.io/openshift-release-dev/ocp-release@sha256:a2b650fae8387c7d900438606e4c77bb936497b005f792a45ad0649da5b07219
>
```

# Platform:

# What happened?

time="2021-08-03T14:33:32+07:00" level=info msg="API v1.20.0+558d959 up"
time="2021-08-03T14:33:32+07:00" level=info msg="Waiting up to 30m0s for bootstrapping to complete..."
time="2021-08-03T15:03:42+07:00" level=error msg="Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: an error on the server (\"\") has prevented the request from succeeding (get clusteroperators.config.openshift.io)"

Something more showup like 
E0609 12:09:57.685885      67 reflector.go:138] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: an error on the server ("") has prevented the request from succeeding (get configmaps) 

# What you expected to happen?

INFO It is now safe to remove the bootstrap resources

# How to reproduce it (as minimally and precisely as possible)?

 import vcenter certficate
 
./openshift-install create install-config --dir

edit install-config.yaml 

./openshift-install create manifests --dir=

 rm -f openshift/99_openshift-cluster-api_master-machines-*.yaml openshift/99_openshift-cluster-api_worker-machineset-*.yaml

 confirm manifests/cluster-scheduler-02-config.yml masterSchedulable is false

 ./openshift-install create ignition-configs --dir

 base64 -w0 install_dir/master.ign > install_dir/master.64

 base64 -w0 install_dir/worker.ign > install_dir/worker.64 

base64 -w0 install_dir/bootstrap.ign > install_dir/bootstrap.64 

Create Master Node in Vsphere Clone VM template, set custom parameter for VM 

./openshift-install --dir=<installation_directory> wait-for bootstrap-complete
 

# Anything else we need to know?

No SSH in configuration, worker replicas =0, static IP. Checking listening in load balancer include port 6443,5000,80,443,22623,36459

# References

**Comment by darksyud** [comment]
[https://ufile.io/tehv0qxb](url)

sorry i dont know the other host for file. I attach the log bundle from gather bootstrap.

Please help !

**Comment by darksyud** [comment]
For DNS testing I have succeed in:
dig +noall +answer @192.168.21.180 api.osc-lab.localdomain 
>> 192.168.21.182 
dig +noall +answer @192.168.21.180 api-int.osc-lab.localdomain 
>> 192.168.21.182 
dig +noall +answer @192.168.21.180 randomtest.apps.osc-lab.localdomain 
>> 192.168.21.183
dig +noall +answer @192.168.21.180 bootstrap.osc-lab.localdomain 
>> 192.168.21.184
dig +noall +answer @192.168.21.180 master0.osc-lab.localdomain
>> 192.168.21.185 
dig +noall +answer @192.168.21.180 master1.osc-lab.localdomain 
>> 192.168.21.186
dig +noall +answer @192.168.21.180 master2.osc-lab.localdomain 
>> 192.168.21.187
dig +noall +answer @192.168.21.180 -x 192.168.21.182
>> 182.21.168.192.in-addr.arpa. 0	IN	PTR	api-osc-lab.localdomain. 
182.21.168.192.in-addr.arpa. 0	IN	PTR	api.osc-lab.localdomain.


For HAPROXY i can queyr netsat only and find the port required listening.

**Comment by darksyud** [comment]
[https://ufile.io/b1r2d128](https://ufile.io/b1r2d128)

I upload new re-try with ssh configuration

**Comment by staebler** [comment]
@darksyud The log bundle is no longer available. Can you re-upload it? Or could you at least provide the logs from the bootkube.service on the boostrap machine?
