### ISSUE TITLE
reflector.go:127] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused

### ISSUE THREAD

**Issue by gowriprasadk** [openshift/installer#5131]
# Version

```console
$ openshift-install version
 openshift-install version
openshift-install 4.7.19
built from commit 3948d1fe9f04057823b871133085d602e6575067
release image quay.io/openshift-release-dev/ocp-release@sha256:eafdac268e1f65053de423ba4a028e8de5133ab78e7954d76ed838bcf5f4f666
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="47.83.202102090044-0"
VERSION_ID="4.7"
OPENSHIFT_VERSION="4.7"
RHEL_VERSION="8.3"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 47.83.202102090044-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.7"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.7"
OSTREE_VERSION='47.83.202102090044-0'
```

# Platform:

# What happened?

bootstrap installation fails at below stage 

Jul 30 18:37:19 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: Starting temporary bootstrap control plane...
Jul 30 18:37:19 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: E0730 18:37:19.819524       1 reflector.go:127] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:19 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#1] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#2] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#3] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused

Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#4] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#5] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#6] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#7] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: E0730 18:37:21.104737       1 reflector.go:127] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#8] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#9] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused

# What you expected to happen?
bootstrap install to compelete 

# How to reproduce it (as minimally and precisely as possible)?

baremetal UPI setup 4.7 using coreinstaller command to install rhcos and rebooting server for bootstrap to start 
sudo coreos-installer install /dev/sda --insecure-ignition --ignition-url=http://10.30.236.121:8080/ocpcluster/bootstrap.ign 

```console
$ your-commands-here

all dns resolution checked with dig command for wildcard and all nodes and ha proxy server 

sudo coreos-installer install /dev/sda --insecure-ignition --ignition-url=http://10.30.236.121:8080/ocpcluster/bootstrap.ign
dig +noall +answer 10.30.236.120 api.ocpcluster.example.com
api.ocpcluster.example.com. 86400 IN A 10.30.236.121 <<--- ha proxy ip as well
dig +noall +answer 10.30.236.120 api-int.ocpcluster.example.com
api-int.ocpcluster.example.com. 86400 IN A 10.30.236.121
dig +noall +answer 10.30.236.120 -x 10.30.236.121
121.236.30.10.in-addr.arpa. 86400 IN PTR api.ocpcluster.example.com.
121.236.30.10.in-addr.arpa. 86400 IN PTR haproxy.example.com.
121.236.30.10.in-addr.arpa. 86400 IN PTR api-int.ocpcluster.example.com.

dig +noall +answer 10.30.236.120 -x 10.30.236.141
141.236.30.10.in-addr.arpa. 86400 IN PTR masternode1.ocpcluster.example.com.

[root@ocinstaller ~]# dig +noall +answer 10.30.236.120 -x 10.30.236.140
140.236.30.10.in-addr.arpa. 86400 IN PTR bootstrapnode.ocpcluster.example.com.

[root@ocinstaller ~]# dig +noall +answer 10.30.236.120 -x 10.30.236.142
142.236.30.10.in-addr.arpa. 86400 IN PTR masternode2.ocpcluster.example.com.

[root@ocinstaller ~]# dig +noall +answer 10.30.236.120 -x 10.30.236.143
143.236.30.10.in-addr.arpa. 86400 IN PTR masternode3.ocpcluster.example.com.
journalctl -b -f -u release-image.service -u bootkube.service
```Jul 30 18:37:19 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: Starting temporary bootstrap control plane...
Jul 30 18:37:19 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: E0730 18:37:19.819524       1 reflector.go:127] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:19 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#1] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#2] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#3] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused

Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#4] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#5] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:20 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#6] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#7] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: E0730 18:37:21.104737       1 reflector.go:127] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#8] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused
Jul 30 18:37:21 bootstrapnode.ocpcluster.example.com bootkube.sh[158089]: [#9] failed to fetch discovery: Get "https://localhost:6443/api?timeout=32s": dial tcp [::1]:6443: connect: connection refused

# Anything else we need to know?

i can provide more info as needed or requested 

# References

<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #6017
-->

- enter text here.

**Comment by gowriprasadk** [comment]
@staebler
please help

**Comment by gowriprasadk** [comment]
any clue please ?

**Comment by gowriprasadk** [comment]
now it the instal moved on little ahead and fails with this error 

[core@bootstrapnode ~]$ journalctl -b -f -u release-image.service  -u bootkube.service
-- Logs begin at Thu 2021-08-05 15:28:49 UTC. --
Aug 06 04:14:27 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: Skipped "secret-csr-signer-signer.yaml" secrets.v1./csr-signer-signer -n openshift-kube-controller-manager-operator as it already exists
Aug 06 04:14:28 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: Skipped "secret-initial-kube-controller-manager-service-account-private-key.yaml" secrets.v1./initial-service-account-private-key -n openshift-config as it already exists
Aug 06 04:14:28 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: Skipped "secret-kube-apiserver-to-kubelet-signer.yaml" secrets.v1./kube-apiserver-to-kubelet-signer -n openshift-kube-apiserver-operator as it already exists
Aug 06 04:14:28 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: Skipped "secret-loadbalancer-serving-signer.yaml" secrets.v1./loadbalancer-serving-signer -n openshift-kube-apiserver-operator as it already exists
Aug 06 04:14:29 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: Skipped "secret-localhost-serving-signer.yaml" secrets.v1./localhost-serving-signer -n openshift-kube-apiserver-operator as it already exists
Aug 06 04:14:29 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: Skipped "secret-service-network-serving-signer.yaml" secrets.v1./service-network-serving-signer -n openshift-kube-apiserver-operator as it already exists

****Aug 06 04:15:49 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: E0806 04:15:49.829216       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
Aug 06 04:15:49 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: E0806 04:15:49.831941       1 reflector.go:251] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: Get "https://localhost:6443/api/v1/pods?watch=true": dial tcp [::1]:6443: connect: connection refused
Aug 06 04:15:50 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: E0806 04:15:50.832856       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused
Aug 06 04:15:51 bootstrapnode.ocpcluster.example.com bootkube.sh[316338]: E0806 04:15:51.833775       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused****


current created pods are 

[core@bootstrapnode ~]$ sudo crictl ps -a
CONTAINER           IMAGE                                                                                                                    CREATED             STATE               NAME                             ATTEMPT             POD ID
425149643c074       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         9 minutes ago       Running             kube-controller-manager          16                  81765db2b0c48
c95616021295b       f4a9e2b4d37edfb0526fc5d8fd3337ee613f88b269de635faad36ec689e6b367                                                         10 minutes ago      Running             kube-apiserver-insecure-readyz   3                   3405a8baa133e
6ca0f639f012e       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         10 minutes ago      Running             kube-apiserver                   35                  3405a8baa133e
da47abf3be0df       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         10 minutes ago      Exited              setup                            3                   3405a8baa133e
774544b7b0342       0da33150a6cbe246a42814522b3b583d5543dc80920507a687ea787087ce9a9e                                                         10 minutes ago      Running             cluster-policy-controller        7                   81765db2b0c48
88884a16726b1       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         10 minutes ago      Exited              kube-controller-manager          15                  81765db2b0c48
9ddd3e9013820       quay.io/openshift-release-dev/ocp-release@sha256:a8bc2a472611d499d99f347b3e2a7c385107e9c4e44b45d765a99338b566dd12        10 minutes ago      Running             cluster-version-operator         7                   bbd79d3f9e13f
fbe4af2926cc8       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         10 minutes ago      Running             kube-scheduler                   7                   67e96c6c9bbd2
a8c473d990a1b       quay.io/openshift-release-dev/ocp-release@sha256:a8bc2a472611d499d99f347b3e2a7c385107e9c4e44b45d765a99338b566dd12        12 minutes ago      Exited              cluster-version-operator         6                   bbd79d3f9e13f
1a8f856aab76a       0da33150a6cbe246a42814522b3b583d5543dc80920507a687ea787087ce9a9e                                                         12 minutes ago      Exited              cluster-policy-controller        6                   81765db2b0c48
0a1bebeea14e8       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         12 minutes ago      Exited              kube-scheduler                   6                   67e96c6c9bbd2
61a084ba6162b       1efd19186ae8d1d0d39b56bce36df79becd0e7cbe5a9571c96cb78b3a25f1ee9                                                         12 minutes ago      Running             cloud-credential-operator        3                   ca92f26aaeb62
2c512231cb0eb       f4a9e2b4d37edfb0526fc5d8fd3337ee613f88b269de635faad36ec689e6b367                                                         30 minutes ago      Exited              kube-apiserver-insecure-readyz   2                   429f8a04c18b3
ac68d7ffcc1d9       414ee43c38075a16e90bf6c5737dc6a85787a5e6fdc137269d6060e9f7a9336a                                                         30 minutes ago      Exited              kube-apiserver                   34                  429f8a04c18b3
99c81091db42e       1efd19186ae8d1d0d39b56bce36df79becd0e7cbe5a9571c96cb78b3a25f1ee9                                                         32 minutes ago      Exited              cloud-credential-operator        2                   be09ef10cc578
642abb9459e55       8cfd29fcb8ce4dce54bade51b3d7fc2eb52fa1aecb6cd69e8a5890035bd6a746                                                         12 hours ago        Running             machine-config-server            0                   9305d2fadc185
e945e18263b7f       8cfd29fcb8ce4dce54bade51b3d7fc2eb52fa1aecb6cd69e8a5890035bd6a746                                                         12 hours ago        Exited              machine-config-controller        0                   9305d2fadc185
d407270017f9f       quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:57f1d4094c93eca3b5b34d0e757431594aaff3683510b7fbdc092f7c74c3936f   12 hours ago        Running             etcd-member                      0                   459a4e8a5bbe9



[core@bootstrapnode ~]$ sudo crictl ps -a | wc -l
19

**Comment by gowriprasadk** [comment]
any help please ?

**Comment by gowriprasadk** [comment]
seems to be goin in loop and failing at same place 



Aug 06 05:55:47 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "kube-cloud-config.yaml" secrets.v1./kube-cloud-cfg -n kube-system as it already exists
Aug 06 05:55:47 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "kube-system-configmap-root-ca.yaml" configmaps.v1./root-ca -n kube-system as it already exists
Aug 06 05:55:48 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "machine-config-server-tls-secret.yaml" secrets.v1./machine-config-server-tls -n openshift-machine-cdy exists
Aug 06 05:55:48 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "openshift-config-secret-pull-secret.yaml" secrets.v1./pull-secret -n openshift-config as it already
Aug 06 05:55:48 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "openshift-install-manifests.yaml" configmaps.v1./openshift-install-manifests -n openshift-config as
Aug 06 05:55:49 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-aggregator-client-signer.yaml" secrets.v1./aggregator-client-signer -n openshift-kube-apiser exists
Aug 06 05:55:49 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-control-plane-client-signer.yaml" secrets.v1./kube-control-plane-signer -n openshift-kube-apeady exists
Aug 06 05:55:50 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-csr-signer-signer.yaml" secrets.v1./csr-signer-signer -n openshift-kube-controller-manager-ots
Aug 06 05:55:50 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-initial-kube-controller-manager-service-account-private-key.yaml" secrets.v1./initial-servicpenshift-config as it already exists
Aug 06 05:55:50 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-kube-apiserver-to-kubelet-signer.yaml" secrets.v1./kube-apiserver-to-kubelet-signer -n opensor as it already exists
Aug 06 05:55:51 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-loadbalancer-serving-signer.yaml" secrets.v1./loadbalancer-serving-signer -n openshift-kube-lready exists
Aug 06 05:55:51 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-localhost-serving-signer.yaml" secrets.v1./localhost-serving-signer -n openshift-kube-apiser exists
Aug 06 05:55:52 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: Skipped "secret-service-network-serving-signer.yaml" secrets.v1./service-network-serving-signer -n openshifts it already exists
Aug 06 05:57:11 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: E0806 05:57:11.946163       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: sed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
Aug 06 05:57:11 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: E0806 05:57:11.949010       1 reflector.go:251] github.com/openshift/cluster-bootstrap/pkg/start/status.go:6: Get "https://localhost:6443/api/v1/pods?watch=true": dial tcp [::1]:6443: connect: connection refused
Aug 06 05:57:12 bootstrapnode.ocpcluster.example.com bootkube.sh[360113]: E0806 05:57:12.949978       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:6 Get "https://localhost:6443/api/v1/pods": dial tcp [::1]:6443: connect: connection refused

**Comment by staebler** [comment]
@gowriprasadk 
1) Is this an IPI or a UPI installation?
2) What is the platform (eg., aws, gcp, baremetal)?
3) Can you provide the complete log from the bootkube service on the bootstrap machine?
4) Can you provide the log from the kube-apiserver container on the bootstrap mcahine?
4) Are the control plane machines completing their boot? If so, can you provide the log from the kubelet service on one of the control plane machines?
