### ISSUE TITLE
FATAL Bootstrap failed to complete   with timeout

### ISSUE THREAD

**Issue by bkunal** [openshift/installer#5185]
# Version
OCP-4.9.0

```console
$ openshift-install version
$ ./openshift-install version
./openshift-install 4.9.0-0.nightly-2021-08-31-123131
built from commit 1d21be17667df4266c3def1de353488009881905
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:2cba6a2024037034a65f9bf3764a45a12c9e935b04385d409d437121508aa87b
release architecture amd64
```

# Platform:

AWS

IPI

# What happened?

I have been trying to install OCP for a couple of days and have tried multiple versions like OCP-4.8, 4.7, 4.9, and all of them fails with the same error.  Certainly, it seems some issue on my end but I am not able to figure out what could be the issue. Things were working fine previously, suddenly it has stopped working for me. 

```
DEBUG Log bundle written to /var/home/core/log-bundle-20210901144755.tar.gz 
INFO Bootstrap gather logs captured here "/home/bkunal/OCS-4/OCP-4.9/cluster-1/log-bundle-20210901144755.tar.gz" 
ERROR Bootstrap failed to complete: Get "https://api.bkunal-cluster-1.product-exp.indianshift.support:6443/version?timeout=32s": dial tcp: lookup api.bkunal-cluster-1.product-exp.indianshift.support on 127.0.0.53:53: no such host 
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane. 
FATAL Bootstrap failed to complete   
```

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Installation to complete
# How to reproduce it (as minimally and precisely as possible)?

not much with the steps. 
1. Create Install config
2. Create cluster

It is always reproducible on my end.

```console
$ ./openshift-install create install-config  --dir=cluster-1
$ ./openshift-install create cluster   --dir=cluster-1  --log-level=debug
```

# Anything else we need to know?

I will attach log-bundle
[log-bundle-20210901144755.tar.gz](https://github.com/openshift/installer/files/7096249/log-bundle-20210901144755.tar.gz)

# References

- Not aware.

**Comment by staebler** [comment]
The cluster completes its bootstrapping successfully. Your issue is with your DNS configuration. When I try to resolve product-exp.indianshift.support, it does not resolve to a route53 name server.

**Comment by bkunal** [comment]
the issue is resolved now. Closing the issue.
