### ISSUE TITLE
Unpacking tectonic-dev.tar.gz generates "implausibly old time stamp" warnings

### ISSUE THREAD

**Issue by wking** [openshift/installer#52]
```console
$ git describe --always
ae41b0a
$ bazel build tarball
INFO: Analysed target //:tarball (0 packages loaded).
INFO: Found 1 target...
Target //:tectonic-dev up-to-date:
  bazel-bin/tectonic-dev.tar.gz
INFO: Elapsed time: 0.163s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
$ tar -xzf bazel-bin/tectonic-dev.tar.gz 2>&1 | head -n3
tar: ./tectonic-dev/config.tf: implausibly old time stamp 1969-12-31 16:00:00
tar: ./tectonic-dev/modules/aws/etcd/ignition.tf: implausibly old time stamp 1969-12-31 16:00:00
tar: ./tectonic-dev/modules/aws/etcd/nodes.tf: implausibly old time stamp 1969-12-31 16:00:00
$ tar --version | head -n1
tar (GNU tar) 1.26
```

Those "implausibly old time stamp" warnings are probably so we get reproducible tarballs (without drifting timestamps) when we don't actually care about the timestamps on these files.  In order to avoid distracting people running `tar`, do we want to change [our suggestion][1] to:

    tar -xz --warning=no-timestamp -f bazel-bin/tectonic-dev.tar.gz

That would make life less noisy for folks running the command, but a bit more noisy for folks reading the README.  Thoughts?

[1]: https://github.com/openshift/installer/blame/ae41b0a3fa6f3c074bb1e0fd726a9aec406c4301/README.md#L25

**Comment by crawford** [comment]
Which version of tar are you using? I don't see those warnings on my system.

**Comment by wking** [comment]
> Which version of tar are you using?

GNU tar 1.26 (see the final two lines of [my console session][1]).

[1]: https://github.com/openshift/installer/issues/52#issue-340835339

**Comment by cgwalters** [comment]
General best practice is to use the timestamp of the git commit, or better that and [support SOURCE_DATE_EPOCH](https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal).

**Comment by wking** [comment]
> General best practice is to use the timestamp of the git commit, or better that and support `SOURCE_DATE_EPOCH`.

It looks like [Bazel clobbers some metadata][1] when [shelling out to tar][2] (and also maybe [over here][3]), but [gives no way to clobber ctimes][4].  There's some discussion of this limitation in bazelbuild/bazel#1299.

[1]: https://github.com/bazelbuild/bazel/blob/0.16.0/tools/build_defs/pkg/pkg.bzl#L29
[2]: https://github.com/bazelbuild/bazel/blob/0.16.0/tools/build_defs/pkg/pkg.bzl#L82
[3]: https://github.com/bazelbuild/bazel/blob/0.16.0/tools/build_defs/pkg/build_tar.py#L274-L276
[4]: https://github.com/bazelbuild/bazel/blob/0.16.0/tools/build_defs/pkg/README.md#pkg_tar

**Comment by cgwalters** [comment]
Kind of related: https://pagure.io/teamsilverblue/issue/21  (ostree also uses a timestamp of 0)

**Comment by crawford** [comment]
We no longer package everything into a tarball.
