### ISSUE TITLE
"openshift-install destroy cluster" leaves auth dir, breaking next install 

### ISSUE THREAD

**Issue by sttts** [openshift/installer#522]
After installing, there is the `auth/kubeconfig` file in the current checkout. When destroying the cluster, this file is not deleted. A following cluster install load this files, but it does not match the new certificates. Hence, the cluster does not work as expected for the user.

**Comment by sttts** [comment]
Couldn't double check this due to the current AWS quota issues. Please confirm if this is an issue.

**Comment by wking** [comment]
> A following cluster install load this files...

More on this over [here][1] and later.  For now, the easiest approach is probably to use `--dir=whatever` and then after you destroy the cluster `rm -rf whatever` to give you a clean slate for the next run.

[1]: https://github.com/openshift/installer/pull/388#issuecomment-430106965

**Comment by crawford** [comment]
I don't follow how the presence of `auth/kubeconfig` caused the certificate mismatch. If the installer's state file was still present, it would have reused all of the previously generated TLS assets, resulting in valid certificates. Did you remove the installer's state file but leave the kubeconfig?

**Comment by stlaz** [comment]
Encountered the very same problem - several times. Removing the `auth/` directory always fixes the cert mismatch.

**Comment by crawford** [comment]
Yes, that makes sense. You are effectively telling the installer to ignore whatever kubeconfig it has generated and to instead use the one you have provided (which will almost always be incorrect).

We should revisit this UX issue soon.

**Comment by mazzystr** [comment]
I have been doing the following...
* ```bin/openshift-install destroy-cluster```
* ```rm -rf terraform.state terraform.tfvars terraform.tfstate .openshift_install_state.json metadata.json```
* ```bin/openshift-install cluster```
* ```mv auth/kubeconfig ~/.kube/ccallegar```
* ```export KUBECONFIG=$HOME/.kube/ccallegar```

The result is a failed cluster.  All instances behind the int and ext aws elb are OutOfService.  Kublet services are failed on instances.  There is not OpenShift cluster.

You will the following output (and systemd journal logs) when starting kublet ....
> [root@ip-10-0-7-17 ~]#  /usr/bin/hyperkube     kubelet       --config=/etc/kubernetes/kubelet.conf       --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig       --rotate-certificates       --kubeconfig=/var/lib/kubelet/kubeconfig       --container-runtime=remote       --container-runtime-endpoint=/var/run/crio/crio.sock       --allow-privileged       --node-labels=node-role.kubernetes.io/master       --minimum-container-ttl-duration=6m0s       --client-ca-file=/etc/kubernetes/ca.crt       --cloud-provider=aws             --anonymous-auth=false       --register-with-taints=node-role.kubernetes.io/master=:NoSchedule
> Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Flag --allow-privileged has been deprecated, will be removed in a future version
> Flag --minimum-container-ttl-duration has been deprecated, Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.
> Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Flag --allow-privileged has been deprecated, will be removed in a future version
> Flag --minimum-container-ttl-duration has been deprecated, Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.
> Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> I1030 18:27:51.651642    4254 server.go:418] Version: v1.11.0+d4cacc0
> I1030 18:27:51.652086    4254 aws.go:1032] Building AWS cloudprovider
> I1030 18:27:51.652953    4254 aws.go:994] Zone not specified in configuration file; querying AWS metadata service
> I1030 18:27:51.836182    4254 tags.go:76] AWS cloud filtering on ClusterID: ccallegar
> F1030 18:27:51.842709    4254 server.go:262] failed to run Kubelet: cannot create certificate signing request: Post https://ccallegar-api.ccallegar.sysdeseng.com:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: EOF
> 


Executing the following fixes everything!
* rm -rf terraform.state terraform.tfvars terraform.tfstate .openshift_install_state.json metadata.json **auth**

**Comment by wking** [comment]
>     rm -rf terraform.state terraform.tfvars terraform.tfstate .openshift_install_state.json metadata.json auth

Docs for the easier `--dir` approach are in flight with #532.

**Comment by sttts** [comment]
I still think the UX is broken. There should be a default for `--dir` and a warning or even error if that dir already exists, with an override if it is really intended to re-use a dir.

**Comment by jeremyeder** [comment]
I wanted to post an error message from a state my system is in now which I think is related to this issue.  ```openshift-install cluster delete``` fails with the following message:

```
DependencyViolation: resource sg-0d577e26d576aabc9 has a dependent object
```

**Comment by jeremyeder** [comment]
Ack - https://github.com/openshift/installer/issues/836

**Comment by wgordon17** [comment]
@wking 

> But I think it would make life slightly more complicated for external users, who are more likely to successfully launch a single cluster and then walk away from the installer for weeks+.

Why would having a default `--dir` value be slightly more complicated for external users? Having a default `--dir` automatically be set to the cluster name would make it nice and obvious I would think.

What are the potential issues here? I anticipate that once this GA's, it would be writing to the system default `kubeconfig` (~/.kube/config), right? So I guess I'm curious what the complications would be?

**Comment by rajatchopra** [comment]
Fixed with this commit: https://github.com/openshift/installer/commit/b6865885001580c7e8bcc983cff46146c715540a

Closing the issue. Please re-open if it still exists. I have tested it against a libvirt cluster and auth gets removed upon a destroy.

**Comment by rajatchopra** [comment]
> Why would having a default --dir value be slightly more complicated for external users? Having a default --dir automatically be set to the cluster name would make it nice and obvious I would think.

Setting to the cluster name may be okay, but only when we are generating it all from scratch. We have to support the case where install-config is imported in.

> What are the potential issues here? I anticipate that once this GA's, it would be writing to the system default kubeconfig (~/.kube/config), right? So I guess I'm curious what the complications would be?

~/.kube/config may not be ideal (though useful in many cases) because multiple clusters may (and likely) need to be launched from a single local machine. So isolating a cluster to its target 'dir' is strongly desirable.

**Comment by tzvatot** [comment]
This issue still happens with
```
./openshift-install v4.1.0-201904211700-dirty
built from commit f3b726cc151f5a3d66bc7e23e81b3013f1347a7e
release image quay.io/openshift-release-dev/ocp-release@sha256:345ec9351ecc1d78c16cf0853fe0ef2d9f48dd493da5fdffc18fa18f45707867
```
Not sure why this version is marked "dirty" - I downloaded it from the official link.
