### ISSUE TITLE
bootstrap node not getting small ignition file with certificateAuthorities definition

### ISSUE THREAD

**Issue by homer314** [openshift/installer#5283]
# Version

```console
$ openshift-install version
./openshift-install-stable 4.8.13
built from commit 450e95767d89f809cb1afe5a142e9c824a269de8
```

# Platform:

openstack (installer provided infrastructure)

# What happened?

I need to use my custom CA, so i added:
- "cacert"  in clouds.yaml
and
- "additionalTrustBundle"  in install-config.yaml

I'm pretty sure that bootrap node is not getting my ca by ignition process.
In temporary terraform's path, i can find
cat terraform.tfvars.json | jq .'ignition_master'
"{\"ignition\":{\"config\":{\"merge\":[{\"source\":\"https://10.0.0.5:22623/config/master\"}]},\"security\":{\"tls\":{\"certificateAuthorities\":[{\"source\":\"data:text/plain;charset=utf-8;base64,[..]}]}},\"version\":\"3.2.0\"}}"
as expected, but for boostrap node

cat terraform.tfvars.json | jq .'ignition_bootstrap' i get the same 300kb output as for glance's uploaded image content.

master's boot logs: (expected)
[    8.601399] ignition[723]: GET http://169.254.169.254/openstack/latest/user_data: attempt #3
[    9.603668] ignition[723]: GET result: OK
[    9.647240] ignition[723]: Adding "root-ca" to list of CAs

for bootstrap node, intstead: (no ca-releated action event)
[    8.601399] ignition[723]: GET http://169.254.169.254/openstack/latest/user_data: attempt #3
[    9.603668] ignition[723]: GET result: OK
] ignition[723] GET error: Get "https://mysq//v2/images/uuid/file": x509: certificate signed by unknown authority

# What you expected to happen?
i'm expecting that installer will create:
- a glance image with the main ignition file
- a small ignition file containing just custom big ignition file (283k) reference (glance url) for bootstrap node, as for master and others

# How to reproduce it (as minimally and precisely as possible)?

```console
created clouds.yaml (with cacert filed)
$ ./openshift-install create install-config --dir=openshift-installer-files

added "additionalTrustBundle"  in install-config.yaml
$ ./openshift-install create cluster --dir=openshift-installer-files
```

**Comment by staebler** [comment]
> sorry, my mistake. 'cacert:' should be in the same level of auth.

I am assuming that this means that the issue was in your clouds.yaml file. As such, I am closing this issue. Feel free to re-open it if I am mistaken.

/close
