### ISSUE TITLE
openshift-install fails with "Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding"

### ISSUE THREAD

**Issue by dalier-ramirez** [openshift/installer#5341]
# Version

```console
$ openshift-install version
openshift-install 4.8.15
built from commit 0c5cd91b7f5b9c4497ce294e6af74afe30bd3fb1
release image quay.io/openshift-release-dev/ocp-release@sha256:92b684258b9f80dadce5b2f4efce0e110fb92b9f08f8837bdcbe7393c57d388f
```

# Platform:

# What happened?

DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding
...

# What you expected to happen?

Bootstrapping to complete.

# How to reproduce it (as minimally and precisely as possible)?

```console
# openshift-install --dir=/root/ocp67 wait-for bootstrap-complete --log-level debug
DEBUG OpenShift Installer 4.8.13                   
DEBUG Built from commit 450e95767d89f809cb1afe5a142e9c824a269de8 
INFO Waiting up to 20m0s for the Kubernetes API at https://api.openshift.interop.com:6443... 
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding ...
```

# Anything else we need to know?

Log File
--------
```console
$ grep -i Fail .openshift_install.log
time="2021-10-28T11:22:00-04:00" level=debug msg="Failed to marshal PKIX public key: %!s(<nil>)"
time="2021-10-28T11:22:03-04:00" level=debug msg="Failed to marshal PKIX public key: %!s(<nil>)"
```
```console
$ grep -i error .openshift_install.log
time="2021-10-28T11:22:31-04:00" level=debug msg="Still waiting for the Kubernetes API: an error on the server (\"\") has prevented the request from succeeding"
```

Debug
-----
```console
$ wget --verbose --debug https://api.openshift.interop.com:6443
DEBUG output created by Wget 1.19.5 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'index.html' (UTF-8) -> 'index.html' (UTF-8)
--2021-10-20 09:34:10--  https://api.openshift.interop.com:6443/
Certificates loaded: 143
Resolving api.openshift.interop.com (api.openshift.interop.com)... 192.168.67.1
Caching api.openshift.interop.com => 192.168.67.1
Connecting to api.openshift.interop.com (api.openshift.interop.com)|192.168.67.1|:6443... connected.
Created socket 3.
Releasing 0x000055818e4e3590 (new refcount 1).
GnuTLS: The TLS connection was non-properly terminated.
Closed fd 3
Unable to establish SSL connection.
```
```console
$ wget --verbose --debug --no-check-certificate https://api.openshift.interop.com:6443
Setting --check-certificate (checkcertificate) to 0
Setting --check-certificate (checkcertificate) to 0
DEBUG output created by Wget 1.19.5 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'index.html' (UTF-8) -> 'index.html' (UTF-8)
--2021-10-28 11:25:41--  https://api.openshift.interop.com:6443/
Certificates loaded: 147
Resolving api.openshift.interop.com (api.openshift.interop.com)... 192.168.67.1
Caching api.openshift.interop.com => 192.168.67.1
Connecting to api.openshift.interop.com (api.openshift.interop.com)|192.168.67.1|:6443... connected.
Created socket 3.
Releasing 0x0000562dcb21c430 (new refcount 1).
GnuTLS: The TLS connection was non-properly terminated.
Closed fd 3
Unable to establish SSL connection.
```
```console
$ curl -v https://api.openshift.interop.com:6443
* Rebuilt URL to: https://api.openshift.interop.com:6443/
*   Trying 192.168.67.1...
* TCP_NODELAY set
* Connected to api.openshift.interop.com (192.168.67.1) port 6443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.openshift.interop.com:6443
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.openshift.interop.com:6443
```
```console
$ openshift-install gather bootstrap --bootstrap bootstrap.openshift.interop.com --master master-0.openshift.interop.com
INFO Pulling debug logs from the bootstrap machine
FATAL failed to create SSH client: dial tcp 192.168.67.253:22: connect: no route to host
```

# References

- enter text here.

**Comment by staebler** [comment]
There is a lot to unpack here, and I have no familiarity with https://github.com/I8C/installing-openshift-on-single-vmware-esxi-host. But at first glance it appears that there may be a problem with the load balancing on your bastion host.

Can you ssh into your bastion host to see if there is connectivity to https://192.168.67.253:6443 from there?

Are you able to ssh into the bootstrap VM from the bastion host? If so, you could run the `openshift-install gather bootstrap` command from the bastion host to get the bootstrap gather.

**Comment by dalier-ramirez** [comment]
Matthew,

I think the failure occurs before the boostrap VM gets to boot.

# openshift-install gather bootstrap --bootstrap bootstrap.openshift.interop.com --master master-0.openshift.interop.com
INFO Pulling debug logs from the bootstrap machine
FATAL failed to create SSH client: dial tcp 192.168.67.253:22: connect: no route to host

Attached are the wget, curl, and openssl outputs at the bastion VM, comparing http versus https.

[wget-http.txt](https://github.com/openshift/installer/files/7513688/wget-http.txt)
[wget-https.txt](https://github.com/openshift/installer/files/7513689/wget-https.txt)
[curl-http.txt](https://github.com/openshift/installer/files/7513691/curl-http.txt)
[curl-https.txt](https://github.com/openshift/installer/files/7513693/curl-https.txt)
[openssl.txt](https://github.com/openshift/installer/files/7513695/openssl.txt)

.

**Comment by dalier-ramirez** [comment]
Sorry for the font.  Still not used to markup.

**Comment by staebler** [comment]
OK. What is the serial console output on the bootstrap VM?

**Comment by dalier-ramirez** [comment]
Bootstrap VM console attached

<img width="952" alt="serial-console-bootstrap-vm" src="https://user-images.githubusercontent.com/93206849/141176506-5e13f5da-5493-4b2f-bfe6-3571688738fb.png">
.

**Comment by staebler** [comment]
OK. So the bootstrap VM failed to ignite. That is not an issue with the OpenShift installer. That is an issue with how you have your VM configured. [Here](https://github.com/coreos/fedora-coreos-tracker/issues/698) is another issue with some pointers on how to figure out what the issue may be.

**Comment by dalier-ramirez** [comment]
Removed blank lines and extra characters from the /var/lib/matchbox/profiles/bootstrap.json pulled from the git.
The bootstrap VM is now trying to boot.
But still not completing.

<img width="887" alt="boostrap-vm" src="https://user-images.githubusercontent.com/93206849/141222202-873b5293-295e-4b23-aeae-39f591b75d1f.png">

**Comment by dalier-ramirez** [comment]
time="2021-11-10T20:26:14-05:00" level=error msg="Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: an error on the server (\"\") has prevented the request from succeeding (get clusteroperators.config.openshift.io)"
time="2021-11-10T20:26:14-05:00" level=info msg="Use the following commands to gather logs from the cluster"
time="2021-11-10T20:26:14-05:00" level=info msg="openshift-install gather bootstrap --help"
time="2021-11-10T20:26:14-05:00" level=error msg="Bootstrap failed to complete: an error on the server (\"\") has prevented the request from succeeding"
time="2021-11-10T20:26:14-05:00" level=error msg="Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane."
time="2021-11-10T20:26:14-05:00" level=fatal msg="Bootstrap failed to complete"

**Comment by staebler** [comment]
The bootstrap VM cannot fetch its OS from the bastion. It looks like the script that you are following is well out of date.
https://github.com/I8C/installing-openshift-on-single-vmware-esxi-host/blob/b88de8b5b646648c9b5623042abd89df6de0fd3a/installBastion.sh#L45-L48
The preceding RHCOS files no longer exist at the URL used.

**Comment by dalier-ramirez** [comment]
Actually, I have been using the attached installation script.  It is updated.

[installBastion.sh.txt](https://github.com/openshift/installer/files/7521695/installBastion.sh.txt)

**Comment by staebler** [comment]
In an event, I cannot provide support for why your bootstrap VM cannot find the file that it is looking for from your TFTP server.

**Comment by Praveenmail2him** [comment]
where is the fix?

**Comment by Tej81222** [comment]
does this issue is fixed?
