### ISSUE TITLE
[okd4.7] operators authentication &  console degraded will not allow oc login throwing unable to connect to the server: EOF

### ISSUE THREAD

**Issue by vglaiju** [openshift/installer#5359]
Both authentication & console operators are now in False state
![image](https://user-images.githubusercontent.com/30792061/140903361-e57f51f2-434e-4501-8de1-6f8f198dfbfc.png)

# Version
enivronment :vmware upi
binary:           openshift-install-linux-4.7.0-0.okd-2021-05-22-050008.tar.gz

```console
$ openshift-install version
[kubenode@api okd4_files]$ openshift-install version
openshift-install 4.7.0-0.okd-2021-05-22-050008
built from commit ba1a5fc61dd3be134a24fa6d89ae24012a93385a
release image quay.io/openshift/okd@sha256:301cd36b2ab370027ddb0ec43e540a03a24748a25b69578dec504d130475304b
```

# Platform: vmware upi

# What happened?

Cluster installation successful , was able to use the cluster for 3 months.
After that frequent oc login issues in services-vm. 
[kubenode@api ~]$ oc login --certificate-authority=/etc/ssl/certs/ca-bundle.trust.crt  https://api.lab.okd.local:6443 -u kubeadmin -p $(cat install_dir/auth/kubeadmin-password) --loglevel=8
I1109 02:29:23.107775 1017556 loader.go:379] Config loaded from file:  /home/kubenode/.kube/config
I1109 02:29:23.109677 1017556 round_trippers.go:422] HEAD https://api.lab.okd.local:6443/
I1109 02:29:23.109702 1017556 round_trippers.go:429] Request Headers:
I1109 02:29:23.119318 1017556 round_trippers.go:448] Response Status:  in 9 milliseconds
I1109 02:29:23.119367 1017556 round_trippers.go:451] Response Headers:
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

I1109 02:29:26.233288 1017556 round_trippers.go:422] HEAD https://api.lab.okd.local:6443/
I1109 02:29:26.233312 1017556 round_trippers.go:429] Request Headers:
I1109 02:29:26.244217 1017556 round_trippers.go:448] Response Status: 403 Forbidden in 10 milliseconds
I1109 02:29:26.244249 1017556 round_trippers.go:451] Response Headers:
I1109 02:29:26.244256 1017556 round_trippers.go:454]     Date: Tue, 09 Nov 2021 07:29:31 GMT
I1109 02:29:26.244261 1017556 round_trippers.go:454]     Audit-Id: d5add6ed-27a3-40d8-9d0e-035b7845e027
I1109 02:29:26.244265 1017556 round_trippers.go:454]     Cache-Control: no-cache, private
I1109 02:29:26.244273 1017556 round_trippers.go:454]     Content-Type: application/json
I1109 02:29:26.244279 1017556 round_trippers.go:454]     X-Content-Type-Options: nosniff
I1109 02:29:26.244283 1017556 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: e12c82f9-d758-4755-bb29-9d996d84eb7b
I1109 02:29:26.244288 1017556 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: b9069ea6-ccbc-4ca5-9a12-f2bc4ac22774
I1109 02:29:26.244293 1017556 round_trippers.go:454]     Content-Length: 186
I1109 02:29:26.244303 1017556 request_token.go:89] GSSAPI Enabled
I1109 02:29:26.244331 1017556 round_trippers.go:422] GET https://api.lab.okd.local:6443/.well-known/oauth-authorization-server
I1109 02:29:26.244340 1017556 round_trippers.go:429] Request Headers:
I1109 02:29:26.244348 1017556 round_trippers.go:433]     X-Csrf-Token: 1
I1109 02:29:26.245339 1017556 round_trippers.go:448] Response Status: 200 OK in 0 milliseconds
I1109 02:29:26.245363 1017556 round_trippers.go:451] Response Headers:
I1109 02:29:26.245375 1017556 round_trippers.go:454]     Date: Tue, 09 Nov 2021 07:29:31 GMT
I1109 02:29:26.245383 1017556 round_trippers.go:454]     Audit-Id: 4633ad3a-d463-476d-8da4-4b16ab5af5a4
I1109 02:29:26.245390 1017556 round_trippers.go:454]     Cache-Control: no-cache, private
I1109 02:29:26.245401 1017556 round_trippers.go:454]     Content-Type: application/json
I1109 02:29:26.245411 1017556 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: e12c82f9-d758-4755-bb29-9d996d84eb7b
I1109 02:29:26.245421 1017556 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: b9069ea6-ccbc-4ca5-9a12-f2bc4ac22774
I1109 02:29:26.245431 1017556 round_trippers.go:454]     Content-Length: 579
I1109 02:29:26.247150 1017556 round_trippers.go:422] GET https://api.lab.okd.local:6443/api/v1/namespaces/openshift/configmaps/motd
I1109 02:29:26.247174 1017556 round_trippers.go:429] Request Headers:
I1109 02:29:26.247189 1017556 round_trippers.go:433]     Accept: application/json, */*
I1109 02:29:26.247200 1017556 round_trippers.go:433]     User-Agent: oc/v4.2.0 (linux/amd64) kubernetes/95881af
I1109 02:29:26.248186 1017556 round_trippers.go:448] Response Status: 403 Forbidden in 0 milliseconds
I1109 02:29:26.248208 1017556 round_trippers.go:451] Response Headers:
I1109 02:29:26.248221 1017556 round_trippers.go:454]     Date: Tue, 09 Nov 2021 07:29:31 GMT
I1109 02:29:26.248230 1017556 round_trippers.go:454]     Audit-Id: 267ff582-e9b1-4dcd-90ed-5ec2a74e1168
I1109 02:29:26.248240 1017556 round_trippers.go:454]     Cache-Control: no-cache, private
I1109 02:29:26.248248 1017556 round_trippers.go:454]     Content-Type: application/json
I1109 02:29:26.248255 1017556 round_trippers.go:454]     X-Content-Type-Options: nosniff
I1109 02:29:26.248263 1017556 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: e12c82f9-d758-4755-bb29-9d996d84eb7b
I1109 02:29:26.248271 1017556 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: b9069ea6-ccbc-4ca5-9a12-f2bc4ac22774
I1109 02:29:26.248283 1017556 round_trippers.go:454]     Content-Length: 303
I1109 02:29:26.248310 1017556 request.go:1107] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"motd\" is forbidden: User \"system:anonymous\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"openshift\"","reason":"Forbidden","details":{"name":"motd","kind":"configmaps"},"code":403}
I1109 02:29:26.248909 1017556 helpers.go:234] Connection error: Head https://oauth-openshift.apps.lab.okd.local: EOF
F1109 02:29:26.248949 1017556 helpers.go:115] Unable to connect to the server: EOF
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc001818000, 0x53, 0xc6)
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x4b74a00, 0xc000000003, 0x0, 0x0, 0xc00177f3b0, 0x46f3ba4, 0xa, 0x73, 0x420300)
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x4b74a00, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc001778620, 0x1, 0x1)
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/klog/v2.FatalDepth(...)
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1488
k8s.io/kubectl/pkg/cmd/util.fatal(0xc00093b800, 0x24, 0x1)
        /go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x26e
k8s.io/kubectl/pkg/cmd/util.checkErr(0x33c7480, 0xc00074e510, 0x3109da8)
        /go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
github.com/openshift/oc/pkg/cli/login.NewCmdLogin.func1(0xc001515600, 0xc00094a3f0, 0x1, 0x7)
        /go/src/github.com/openshift/oc/pkg/cli/login/login.go:77 +0x679
github.com/spf13/cobra.(*Command).execute(0xc001515600, 0xc00094a380, 0x7, 0x7, 0xc001515600, 0xc00094a380)
        /go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc001515340, 0x2, 0xc001515340, 0x2)
        /go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /go/src/github.com/openshift/oc/cmd/oc/oc.go:93 +0x5e5

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x4b74a00)
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 22 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x4b74920)
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /go/src/github.com/openshift/oc/vendor/k8s.io/klog/klog.go:411 +0xd8

goroutine 44 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3109cb8, 0x33c5ba0, 0xc00144d860, 0x1, 0xc000178120)
        /go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x3109cb8, 0x12a05f200, 0x0, 0xc001508001, 0xc000178120)
        /go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/apimachinery/pkg/util/wait.Forever(0x3109cb8, 0x12a05f200)
        /go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/component-base/logs.InitLogs
        /go/src/github.com/openshift/oc/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

goroutine 45 [select]:
io.(*pipe).Read(0xc0016afb00, 0xc001470000, 0x1000, 0x1000, 0x29f5400, 0x1, 0xc001470000)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc0001158c8, 0xc001470000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc00175f900, 0x0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/bufio/scan.go:214 +0xa9
github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter.func1(0xc00175f900, 0x33c7500, 0xc000010018, 0x2f16926, 0x17)
        /go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:496 +0x13e
created by github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter
        /go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:495 +0x1d0

goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x7fad1c6026b0, 0x72, 0x33ca7c0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc001234998, 0x72, 0x33ca700, 0x496a5c8, 0x0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001234980, 0xc001260000, 0x14ad, 0x14ad, 0x0, 0x0, 0x0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc001234980, 0xc001260000, 0x14ad, 0x14ad, 0x203000, 0x7825fb, 0xc001938be0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000426008, 0xc001260000, 0x14ad, 0x14ad, 0x0, 0x0, 0x0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00032f6a0, 0xc001260000, 0x14ad, 0x14ad, 0x149, 0x1460, 0xc0005e3710)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc001938d00, 0x33c1b20, 0xc00032f6a0, 0x41d7a5, 0x2b27d80, 0x2e11ea0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc001938a80, 0x33c7020, 0xc000426008, 0x5, 0xc000426008, 0x138)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc001938a80, 0x0, 0x0, 0xc0005e3d18)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc001938a80, 0xc00126a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0003401e0, 0xc0002d6ff8, 0x9, 0x9, 0xc0005e3d18, 0x310ab00, 0x9b762b)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x33c18c0, 0xc0003401e0, 0xc0002d6ff8, 0x9, 0x9, 0x9, 0xc0000a2060, 0x0, 0x33c1de0)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/io/io.go:314 +0x87
io.ReadFull(...)
        /opt/rh/go-toolset-1.15/root/usr/lib/go-toolset-1.15-golang/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc0002d6ff8, 0x9, 0x9, 0x33c18c0, 0xc0003401e0, 0x0, 0x0, 0xc0005e3dd0, 0x47fba5)
        /go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002d6fc0, 0xc00150ed20, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0005e3fa8, 0x0, 0x0)
        /go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0017dc480)
        /go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

# What you expected to happen?
 oc login continues to work

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by vglaiju** [comment]
the console pods throw the same error as they are unable to get token from authentication operator
![image](https://user-images.githubusercontent.com/30792061/140904982-9b53d62c-394e-4189-bc4f-8b9f4206eb70.png)

**Comment by staebler** [comment]
You have a lot of degraded operators. Can you provide the status of the degraded operators?
