### ISSUE TITLE
Azure IPI - SSH Inbound rule removal

### ISSUE THREAD

**Issue by grtn316** [openshift/installer#5369]
# Installer Version
4.6

# Platform:
Azure - IPI

# What happened?

When the bootstrap VM is created, it also creates an NSG rule that opens port 22 for SSH into the bootstrap VM. I believe this was probably left for testing and should be removed as custom azure policies could block this rule resulting in a failed deployment.

# What you expected to happen?

Rule to not exist since its unattended.

# How to reproduce it (as minimally and precisely as possible)?

Standard deploying with the installer. Noticed the SSH rule while the install was in progress.

**Comment by ranieuwe** [comment]
Offending SSH rule for NSG is here: https://github.com/openshift/installer/blob/6d778f911e79afad8ba2ff4301eda5b5cf4d8e9e/upi/azure/04_bootstrap.json#L224

**Comment by staebler** [comment]
The SSH rule is there for diagnostics in the case of an installation that fails during bootstrapping. It is included intentionally and was not left from testing.

**Comment by grtn316** [comment]
@staebler customers that user Azure Policy to prevent exposing ports on the public internet are unable to use the IPI installer due to this rule. I believe it would be better to add this manually as needed for diagnostics and/or add a flag turning deployment to prevent this firewall rule from being created. This rule current results in a failed deployment for customers that block the creation of rules to allow ssh/rdp from the public internet.

**Comment by staebler** [comment]
Customers that block the creation of the rule are required to use a UPI install. Those customer will have no information about why an installation failed if it failed while bootstrapping.
