### ISSUE TITLE
Azure IPI - Bring your own Storage Accounts

### ISSUE THREAD

**Issue by grtn316** [openshift/installer#5370]
# Version

4.6+

# Platform:
Azure - IPI

# What happened?

When deploying OCP into a private network, there are storage accounts that lack private endpoints. Options to enable private endpoints for these storage accounts AND allow customers to bring their own storage accounts that are already configured to an existing VNET.

# What you expected to happen?

Prevent creation of storage accounts that have not been secured by private endpoints.

# How to reproduce it (as minimally and precisely as possible)?

Standard IPI deployment

**Comment by ranieuwe** [comment]
Related in ARO: https://github.com/Azure/OpenShift/issues/230

**Comment by staebler** [comment]
The first part of this, using private endpoints, is on the roadmap for inclusion in OpenShift 4.10, with the possibility of being backported to OpenShift 4.8.
