### ISSUE TITLE
Requesting Removal of InstallConfig ClusterID

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#538]
Right now you must pre-generate your own UUID and set it as the ClusterID if you are using your own install-config.yml, otherwise the install fails. UUID is set when generating an install config and the rest of the code assumes it's set, but this is not the case if you're using a config file generated by other means. (i.e. Hive)

In past discussions the plan was to remove this from install-config as it was not meant to be something users could set. 

Alternatively, we could keep it as an override and update the code to realize no UUID is set, and generate one. (we've requested being able to generate our own UUIDs as this would give us all info needed to cleanup a cluster in the event of install failure, without having to wrap install and upload metadata files, however this did not appear popular with install team in past discussions.)

**Comment by wking** [comment]
> Alternatively,  we could keep it as an override and update the code to realize no UUID  is set, and generate one.

This sounds straightforward.

> ... we've requested being able to generate our  own UUIDs as this would give us all info needed to cleanup a cluster in  the event of install failure, without having to wrap install and upload  metadata files, however this did not appear popular with install team in  past discussions.

If you are referring to [this][1], I had been arguing that you didn't need to be able to set the UUID in order to cleanup in the event of an install failure.  I don't remember arguing that a configurable UUID was a bad idea (I'd be a bit concerned about foot-gunning, but folks who set it themselves would be explicitly deciding to do so).  Was there other discussion that was more strongly against user-provided UUIDs?

[1]: https://github.com/openshift/installer/issues/458#issuecomment-430767063

**Comment by dgoodwin** [comment]
No that was it, it seemed the proposal to generate was not something desired given the alternatives mentioned, but I guess we did not settle why. If we are all ok with keeping Cluster ID, and allowing override if someone wants to do so, and a small update to the code to generate if it's empty string, this would be awesome from my POV.

**Comment by wking** [comment]
Is this problem more general than `ClusterID`?  I'd expect many fields in the loaded install-config could be optional (e.g. we could inject networking if you left it out).

**Comment by dgoodwin** [comment]
Good question, we haven't really defined what is optional on our side yet so we tend to specify most things so far. Does the installer clearly define what is optional in InstallConfig right now? I know the generated ones are somewhat thin so it must be doing ok, but might be some more problems there if networking for example wasn't setup.

**Comment by wking** [comment]
There are some brief notes in this direction in #263.  No clear docs, as far as I know.

**Comment by wking** [comment]
Fixed by #1057.

/close
