### ISSUE TITLE
OCP4.10.0-0.nightly-2021-10-30-074439 and later versions cannot download RHCOS images

### ISSUE THREAD

**Issue by fenggw-fnst** [openshift/installer#5389]
# Version

```console
$ openshift-baremetal-install version
openshift-baremetal-install 4.10.0-0.nightly-2021-10-30-074439
built from commit 7f607034ae20f7fe1ca30a26e0595418d0772e84
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:63df01bb226ef7e9e9ebb8aa3723266eab9e0bab6d45af01f77282a1d759781e
release architecture amd64
```
as well as the later versions of OCP4.10 nightly.

# Platform:

IPI

# What happened?

We have been using a [RHCOS image cache](https://docs.openshift.com/container-platform/4.9/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-install-creating-an-rhcos-images-cache_ipi-install-installation-workflow) for IPI, but since above version, we cannot get rhcos.json, it returns 404. E.g.:
```console
$ curl -s -S https://raw.githubusercontent.com/openshift/installer/7f607034ae20f7fe1ca30a26e0595418d0772e84/data/data/rhcos.json
404: Not Found%
```

# What you expected to happen?

Get rhcos.json correctly. E.g.:
```console
$ curl -s -S https://raw.githubusercontent.com/openshift/installer/e01a3268a67efc953a197512c2368809482dbaee/data/data/rhcos.json | jq .images.openstack.path | sed 's/"//g'
rhcos-410.84.202110140201-0-openstack.x86_64.qcow2.gz
```

**Comment by staebler** [comment]
`openshift-baremetal-installer coreos print-json-stream`

**Comment by fenggw-fnst** [comment]
Thanks!
