### ISSUE TITLE
Openshift on GCP - IPI - Customize (unmanaged) Instance Group Name

### ISSUE THREAD

**Issue by alekonko** [openshift/installer#5399]
# Version

```console
$ openshift-install version
4.8
```
# Platform:
gcp - ipi

# What happened?

Creation of Instance group with well know name

# What you expected to happen?

By creating clusters on GCP (ipi or ipi + shared-vpc) instance Groups are created with a slightly too random name (k8s-xxxxxxxxxxxxxxxxxxxxxxxxx).

it would be more appropriate, for a more efficient management of resources and side objects, a greater categorization, at least adding the cluster-name in the name of the instance group.

Is there a way to do this today?

![instance groups](https://user-images.githubusercontent.com/22982001/142458928-902acea2-2f04-4d6c-9744-12158ac18a01.png)

**Comment by staebler** [comment]
The instance groups starting with "k8s-ig-" are not created by the installer.
