### ISSUE TITLE
two pods in openshift-marketplact are failed to pull image after UPI installation

### ISSUE THREAD

**Issue by SunnyGu74** [openshift/installer#5419]
# Version
4.7.32

# Platform:
baremetal

Please specify:
UPI

# What happened?
After completing installation, I notice one community-operators pods in openshift-marketplact are failed to pull image
# oc get pod -o wide
NAME                                   READY   STATUS             RESTARTS   AGE   IP            NODE                      NOMINATED NODE   READINESS GATES
certified-operators-6r5sl              1/1     Running            0          18h   172.15.5.15   w01.ocp47u.sunnylab.com   <none>           <none>
community-operators-vn5rr              1/1     Running            0          18h   172.15.5.19   w01.ocp47u.sunnylab.com   <none>           <none>
community-operators-wn5kz              0/1     ImagePullBackOff   0          8h    172.15.4.6    w03.ocp47u.sunnylab.com   <none>           <none>
marketplace-operator-f5847c78c-kt5j8   1/1     Running            0          18h   172.15.2.24   m02.ocp47u.sunnylab.com   <none>           <none>
redhat-marketplace-nvlfk               1/1     Running            0          18h   172.15.5.4    w01.ocp47u.sunnylab.com   <none>           <none>
redhat-operators-chr9l                 1/1     Running            0          18h   172.15.5.21   w01.ocp47u.sunnylab.com   <none>           <none>

# oc describe pod community-operators-wn5kz
......
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  Failed   173m (x65 over 8h)     kubelet  Error: ErrImagePull
  Normal   Pulling  33m (x92 over 8h)      kubelet  Pulling image "registry.redhat.io/redhat/community-operator-index:v4.7"
  Normal   BackOff  13m (x2034 over 8h)    kubelet  Back-off pulling image "registry.redhat.io/redhat/community-operator-index:v4.7"
  Warning  Failed   3m19s (x2068 over 8h)  kubelet  Error: ImagePullBackOff

# What you expected to happen?
I think the pod should be in running

# How to reproduce it (as minimally and precisely as possible)?
I just follow official document to install it, all other pods are optimal, just pod in openshift-marketplace project has issue.

# Anything else we need to know?

# References

**Comment by staebler** [comment]
This does not seem like an installer issue.
My best guess is one of the following.
1. A problem with the specific community-operator-index image. I assume that community-operators pod running on w01 pulled the same image. But that pull looks to have been 10 hours earlier.
2. A problem with the configuration of w03.
Can you try to do the image pull from a `oc debug node/w03`? Or look at the status of the pod to see if there is more information about why the image pull failed.
