### ISSUE TITLE
How can I specify the cluster to be not OKD?

### ISSUE THREAD

**Issue by OlegSternbergIBM** [openshift/installer#5440]
# Version
Latest master branch

```console
$ openshift-install version
Olegs-MacBook-Pro:installer olegsternberg$ ./bin/openshift-install create cluster --dir=/Users/<my username>/openshift-install-assets/osternbe-hoh1
INFO Credentials loaded from the "default" profile in file "/Users/<my username>/.aws/credentials" 
INFO Consuming Install Config from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s (until 4:01PM) for the Kubernetes API at https://api.osternbe-hoh1.dev10.red-chesterfield.com:6443... 
INFO API v1.22.1-1747+bac83a5ac2d725-dirty up     
INFO Waiting up to 30m0s (until 4:14PM) for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 40m0s (until 4:36PM) for the cluster at https://api.osternbe-hoh1.dev10.red-chesterfield.com:6443 to initialize... 
W1202 16:07:00.930974   46204 reflector.go:441] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ClusterVersion ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
INFO Waiting up to 10m0s (until 4:17PM) for the openshift-console route to be created... 
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/Users/<my username>/openshift-install-assets/osternbe-hoh1/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://<my url> 
INFO Login to the console with user: "kubeadmin", and password: "XXXX" 
INFO Time elapsed: 35m44s     
```

# Platform:

# What happened?

Enter text here.
OKD cluster has been installed

# What you expected to happen?

Regular OpenShift cluster should be installed

# How to reproduce it (as minimally and precisely as possible)?
Create 'install-config.yaml' with 'm5.4xlarge' type

```console
$ ./bin/openshift-install create cluster --dir=/Users/olegsternberg/openshift-install-assets/osternbe-hoh1
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by staebler** [comment]
When you build the installer yourself, the release image used by that installer is an OKD release image. To use an OCP release image, you must specify the OpenShift release image to use via the `OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE` environment variable.

For example, to install the latest OpenShift release, which is 4.9.10 at the time of this writing, get the release image from https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.9.10/release.txt.
```
OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/openshift-release-dev/ocp-release@sha256:e1853d68d8ff093ec353ca7078b6b6df1533729688bb016b8208263ee7423f66
 ./bin/openshift-install create cluster --dir=/Users/olegsternberg/openshift-install-assets/osternbe-hoh1`
```

**Comment by OlegSternbergIBM** [comment]
When I defined:
OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/openshift-release-dev/ocp-release@sha256:e1853d68d8ff093ec353ca7078b6b6df1533729688bb016b8208263ee7423f66

and run:
 ./bin/openshift-install create cluster --dir=/Users/olegsternberg/openshift-install-assets/osternbe-hoh1`
 
 it still creates OKD cluster.
 
 When I defined:
 OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/openshift-release-dev/ocp-release@sha256:e1853d68d8ff093ec353ca7078b6b6df1533729688bb016b8208263ee7423f66
 
 Made build:
 .hack/build.sh
 
 And run the installer:
  ./bin/openshift-install create cluster --dir=/Users/olegsternberg/openshift-install-assets/osternbe-hoh1`
  
  the installation finished with error:
  INFO Credentials loaded from the "default" profile in file "/Users/olegsternberg/.aws/credentials" 
WARNING Found override for release image. Please be warned, this is not advised 
INFO Consuming Install Config from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s (until 2:52PM) for the Kubernetes API at https://api.osternbe-hoh2.dev10.red-chesterfield.com:6443... 
INFO API v1.22.3+ffbb954 up                       
INFO Waiting up to 30m0s (until 3:04PM) for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 40m0s (until 3:21PM) for the cluster at https://api.osternbe-hoh2.dev10.red-chesterfield.com:6443 to initialize... 
INFO Waiting up to 10m0s (until 2:59PM) for the openshift-console route to be created... 
INFO Cluster operator baremetal Disabled is True with UnsupportedPlatform: Nothing to do on this Platform 
INFO Cluster operator etcd RecentBackup is Unknown with ControllerStarted:  
INFO Cluster operator insights Disabled is False with AsExpected:  
INFO Cluster operator kube-apiserver Progressing is True with NodeInstaller: NodeInstallerProgressing: 1 nodes are at revision 5; 2 nodes are at revision 6 
INFO Cluster operator network ManagementStateDegraded is False with :  
ERROR Cluster initialization failed because one or more operators are not functioning properly. 
ERROR The cluster should be accessible for troubleshooting as detailed in the documentation linked below, 
ERROR https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html 
ERROR The 'wait-for install-complete' subcommand can then be used to continue the installation 
FATAL fetching default-ingress-cert configmap from openshift-config-managed namespace: Get "https://api.osternbe-hoh2.dev10.red-chesterfield.com:6443/api/v1/namespaces/openshift-config-managed/configmaps/default-ingress-cert": http2: client connection lost

Please assist

**Comment by OlegSternbergIBM** [comment]
Rerun and it works.
Thanks.
