### ISSUE TITLE
Install fails if bootstrap IAM roles cannot be deleted

### ISSUE THREAD

**Issue by mattpielm** [openshift/installer#5487]
# Version
At least 4.7 - 4.9 that I've seen

# Platform:

Observed in aws

IPI

# What happened?

Our Enterprise Cloud team has policy enforcement rules in place that automatically adds a policy to any IAM role that gets created. These aren't causing issues with the install, but Terraform by default will not delete the IAM role because it has been modified.

This also occurs with the machine-api roles while destroying a cluster, but as far as I can tell that's not part of the installer code.

# What you expected to happen?

Install completes without failing.

# How to reproduce it (as minimally and precisely as possible)?

To reproduce, start a cluster install, and while the bootstrap/masters are waiting for Kuberenets API, add a policy to the created IAM role (such as fail-95dcc-bootstrap-role)  before the bootstrap is destroyed.

# Anything else we need to know?

I solved the issue by modifying the installer Terraform to force deletion of the role. Note the path is from the 4.8 and 4.7 release, 4.9 that file is data/data/aws/bootstrap/cluster/main.tf.
```
index 89dacb91a..8ccf77ebd 100644
--- a/data/data/aws/bootstrap/main.tf
+++ b/data/data/aws/bootstrap/main.tf
@@ -54,7 +54,8 @@ resource "aws_iam_role" "bootstrap" {

   name = "${var.cluster_id}-bootstrap-role"
   path = "/"
-
+  force_detach_policies = true
+
   assume_role_policy = <<EOF
 {
     "Version": "2012-10-17",
```

# Reference
I have this in a fork that I'm also using to disable Route53:
https://github.com/mattpielm/installer/tree/release-4.9-noroute53

**Comment by staebler** [comment]
This seems like a reasonable change. Thanks for the issue. I need to dig deeper into the consequences of using `force_detach_policies` as I have no experience with it.

> This also occurs with the machine-api roles while destroying a cluster, but as far as I can tell that's not part of the installer code.

Can you provide a bit more information about this? Are you getting errors when trying to destroy the cluster? Or do you just mean that the machine-api roles are also getting additional policies attached to them?

**Comment by mattpielm** [comment]
I was thinking about this more, I think the other way around this would be for the install process (via install-config.yaml or modifying the manifests after `create manifests` to be able to add custom roles to these items. When I tested with Terraform itself, if you add our custom role (CommonDeny) to the Terraform definition, the items delete fine since Terraform expects CommonDeny to be there and deletes it. It's only when there are items that aren't expected that Terraform gets lost.

**Comment by mattpielm** [comment]
Not sure if anyone is following up on this; I haven't installed a cluster with 4.10 yet, so I'll test that soon to see if this got fixed along the line.
