### ISSUE TITLE
Verify openstackCredsFile

### ISSUE THREAD

**Issue by sallyom** [openshift/installer#550]
# Platform openstack:

With this PR, https://github.com/openshift/installer/pull/427 need to verify that the correct file to get OpenStack creds is this: `/etc/openstack/clouds.yaml`.  Another option would be `openStackCredsFile = os.Getenv("HOME") + "/.config/openstack"`

Once the OpenStack folks verify, this issue can be closed.    

With an OpenStack launch of installer, you will see a secret `openstack-creds` in `-n kube-system`  with encoded `clouds.yaml` in the data of the secret.  Might want to add multiple files/conditional to what creds file is found on the host system during launch in that secret.

**Comment by wking** [comment]
The existing pattern (e.g. for pull secrets and SSH pubkeys) is to try and pick a sane default, but to have a wizard prompt when we aren't sure and an environment variable to override.  That seems sane to me, if we have doubts about our automatic-detection logic.  And even if we do get that wrong, folks can now do a multi-step install to slot in the creds they wish we'd found :).
