### ISSUE TITLE
Is having a master-count of 1 still valid? 

### ISSUE THREAD

**Issue by jtaleric** [openshift/installer#5508]
Trying some libvirt deployments with replica:1 for masters (the default)[1], I keep having deployment issues. However digging around in the issues, it seems we now must have a minimum master count of 3?[2]

[1] https://github.com/openshift/installer/blob/release-4.9/data/data/config.tf#L23-L33
[2] https://github.com/openshift/installer/issues/3579

**Comment by staebler** [comment]
The default master count for a libvirt install is 1, and that is the expected, typical replica count.
