### ISSUE TITLE
Openshift 4.8.9 worker installation fails when proxy services are configured on BIGIP

### ISSUE THREAD

**Issue by yogeesh-venkanna** [openshift/installer#5617]
# Version

```console
$ openshift-install version
openshift-install 4.8.9
built from commit 24fcf7a2e962eb7d3fcca851c6c08750b3e22547
release image quay.io/openshift-release-dev/ocp-release@sha256:5fb4b4225498912357294785b96cde6b185eaed20bbf7a4d008c462134a4edfd

```

# Platform:

# What happened?

Enter text here.
I am trying to install openshift cluster (Version 4.8.9) by configuring proxy services on bigip LB.  Installation works just fine when I use haproxy LB.
Deployment of master nodes was fine, but deployment of workers fails with the below error:
![image](https://user-images.githubusercontent.com/79639485/152753517-2cb578f2-d69f-4a34-95d5-07d5fded0c92.png)

BigIP LB is configured manually based on the template: https://github.com/chen23/openshift-4-3/blob/master/fast/openshift/2_infrastructure.yaml

Need help to rectify this.

I am able to successfully curl both master & worker configs using master's IP address, but the same fails when I use the bigIP LB's IP address:
[yv@pve-haproxy01-ocp-is01 etc]$ curl -vk https://api-int.yv.okd:22623/config/master
*   Trying api-int.yv.okd...
* TCP_NODELAY set
* Connected to api-int.yv.okd port 22623 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api-int.yv.okd
*  start date: Feb  7 07:24:16 2022 GMT
*  expire date: Mar  9 07:24:17 2022 GMT
*  issuer: OU=openshift; CN=kube-apiserver-lb-signer
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* Using Stream ID: 1 (easy handle 0x55ffae4e93d0)
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET /config/master HTTP/2
> Host: api-int.yv.okd:22623
> User-Agent: curl/7.61.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* Connection state changed (MAX_CONCURRENT_STREAMS == 2000)!
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/2 403
< audit-id: f4ffe169-86e3-4688-9271-ad6b33775917
< cache-control: no-cache, private
< content-type: application/json
< x-content-type-options: nosniff
< x-kubernetes-pf-flowschema-uid: bad9ebd3-3aed-48fd-be47-1eb23ac1f6f7
< x-kubernetes-pf-prioritylevel-uid: 12216b21-a171-4645-b5ae-3de14f93bf11
< content-length: 246
< date: Mon, 07 Feb 2022 08:45:06 GMT
<
* TLSv1.3 (IN), TLS app data, [no content] (0):
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/config/master\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
* Connection #0 to host api-int.yv.okd left intact

Can anyone help me to identify the issue?

# What you expected to happen?

Workers should be able to successfully fetch the ignition configuration and join the cluster.

# How to reproduce it (as minimally and precisely as possible)?

# References

Regards,
Y V

**Comment by staebler** [comment]
Your load balancer is incorrectly routing incoming port 22623. It should be routed to port 22623 on the masters. Instead, it appears to be routing to the API server at port 6443.

**Comment by yogeesh-venkanna** [comment]
Hi @staebler ,

Thanks for response.  I have tried with that configuration as well.  But the result is same.  Can you please help me further to verify my configuration?  If you have any working configuration which can be used as reference, it will be of great help.

**Comment by staebler** [comment]
I am not sure how your results could be the same if your load balancer was set up to correctly forward traffic sent to the 22623 port. The cert used by the machine-config-server running at the 22623 port uses the common name "system:machine-config-server" rather than "kube-apiserver-lb-signer".

**Comment by yogeesh-venkanna** [comment]
Hi @staebler ,
I am getting many certificates which I am approving, but no luck.  Bootstrap server entries were removed from the pools as soon as master nodes were up & running.

csr-zztcf                                  38h     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper         Approved
csr-zzxcg                                  3d4h    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper         Approved
system:openshift:openshift-authenticator   4d7h    kubernetes.io/kube-apiserver-client           system:serviceaccount:openshift-authentication-operator:authentication-operator   Approved,Issued
[root@pve-haproxy01-ocp-is01 ~]# oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs --no-run-if-empty oc adm certificate approve
certificatesigningrequest.certificates.k8s.io/csr-5gbxr approved
certificatesigningrequest.certificates.k8s.io/csr-88grc approved
certificatesigningrequest.certificates.k8s.io/csr-hgs9q approved
certificatesigningrequest.certificates.k8s.io/csr-j7sg4 approved
certificatesigningrequest.certificates.k8s.io/csr-jfcr6 approved
certificatesigningrequest.certificates.k8s.io/csr-l6fvm approved
certificatesigningrequest.certificates.k8s.io/csr-sdbkx approved
certificatesigningrequest.certificates.k8s.io/csr-sxcmm approved
certificatesigningrequest.certificates.k8s.io/csr-wqg2v approved


[root@pve-haproxy01-ocp-is01 ~]# oc get csr | wc -l
2004

**Comment by staebler** [comment]
The cert that I was referring to was the TLS cert used by the server to which you are connecting when you curl https://api-int.yv.okd:22623/config/master. In your output from the curl, the CN of the cert was "kube-apiserver-lb-signer". If you had the load balancer configured correctly, the CN of the cert would have been "system:machine-config-server".

**Comment by yogeesh-venkanna** [comment]
Ok, noted.  
Do you think if my LB is configured as following, it should work?
1. Self IP configured

2. 4 VS created using the same selfIP:
frontend-machine-config-server (22623) >> member of backend-machine-config-server pool
frontend-openshift-api-server (6443) >> member of backend-openshift-api-server pool
frontend-ingress-http (80) >> member of backend-ingress-http pool
frontend-ingress-https (443) >> member of backend-ingress-https pool

3. 4 pools created:
backend-machine-config-server >> all masters & bootstrap severs are members of this pool (port 22623)
backend-openshift-api-serve >> all masters & bootstrap servers are members of this pool (port 6443)
backend-ingress-http >> all workers are members of this pool (port 80)
backend-ingress-https >> all workers are members of this pool (port 443)

**Comment by staebler** [comment]
I don't have any experience with using the bigip LB. With that said, at a high level, the configuration that you described looks correct.

**Comment by yogeesh-venkanna** [comment]
Ok, I will reattempt an installation with the abovesaid configuration, and update here the results.
Thanks for swift response.

**Comment by yogeesh-venkanna** [comment]
Hi @staebler ,

I configured the LB as mentioned here: https://github.com/openshift/installer/issues/5617#issuecomment-1046966603.

Workers are unable to join the cluster, see the below errors on workers:
![image](https://user-images.githubusercontent.com/79639485/155445091-399202e2-61ac-471c-ab0a-6079c8edc23d.png)

But getting lot of CSRs, even upon approval, there is no change in the status of worker nodes:
![image](https://user-images.githubusercontent.com/79639485/155445176-9f38d2b9-3b76-41b3-8548-d117ca86edf1.png)

Bootstrap server was removed from the pools after the masters had come up.

Any hint please?

**Comment by SHAKY404** [comment]
> Rotten issues close after 30d of inactivity.
> 
> Reopen the issue by commenting `/reopen`. Mark the issue as fresh by commenting `/remove-lifecycle rotten`. Exclude this issue from closing again by commenting `/lifecycle frozen`.
> 
> /close
