### ISSUE TITLE
Azure - UPI - Bootstrap failed to complete - ocp 4.8.28

### ISSUE THREAD

**Issue by mahima-ipath** [openshift/installer#5630]
# Version

```console
$ openshift-install version
openshift-install 4.8.28
built from commit aaa978bb5d76472df23f6e90293e68aaa43a8457
release image quay.io/openshift-release-dev/ocp-release@sha256:ba1299680b542e46744307afc7effc15957a20592d88de4651610b52ed8be9a8

# Platform:
<!--
Please specify the platform type: aws, libvirt, openstack or baremetal
-->
Azure
<!--
Please specify:
* IPI (automated install with `openshift-install`. If you don't know, then it's IPI)
* UPI (semi-manual installation on customised infrastructure)
-->
UPI
# What happened?

Bootstrap failed to complete

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

<!--
Please list the full steps required to reproduce the issue.
-->

```console
$ openshift-install wait-for bootstrap-complete --log-level debug
```

Wait for the bootstrap complete
DEBUG OpenShift Installer 4.8.28                   
DEBUG Built from commit aaa978bb5d76472df23f6e90293e68aaa43a8457 
INFO Waiting up to 20m0s for the Kubernetes API at https://api.myupicluster.ipath-demos.com:6443... 
DEBUG Still waiting for the Kubernetes API: Get "https://api.myupicluster.ipath-demos.com:6443/version?timeout=32s": dial tcp 20.119.105.215:6443: i/o timeout 
DEBUG Still waiting for the Kubernetes API: Get "https://api.myupicluster.ipath-demos.com:6443/version?timeout=32s": dial tcp 20.119.105.215:6443: i/o timeout 
DEBUG Still waiting for the Kubernetes API: Get "https://api.myupicluster.ipath-demos.com:6443/version?timeout=32s": dial tcp 20.119.105.215:6443: i/o timeout 
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get "https://api.myupicluster.ipath-demos.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 20.119.105.215:6443: i/o timeout 
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
ERROR Bootstrap failed to complete: Get "https://api.myupicluster.ipath-demos.com:6443/version?timeout=32s": dial tcp 20.119.105.215:6443: i/o timeout 
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane. 
FATAL Bootstrap failed to complete 

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by staebler** [comment]
A common cause of this is if your load balancer or DNS is not configured properly.

If you run the `openshift-install gather bootstrap` command, you can look at the bootkube.service log to see if bootstrapping completed. If it did, then the issue is with external communication to your cluster, as is likely the issue above.

**Comment by pdas-cp4i** [comment]
You are correct. Issue was with my custom domain.
It's working now.

Thanks

**Comment by bipluv89** [comment]
We are having similar problem. When you say there issue was with my customer domain - can you please share the issue with custom domain?
