### ISSUE TITLE
[etcdctl] Error: context deadline exceeded 

### ISSUE THREAD

**Issue by tsannier** [openshift/installer#5646]
# Version

```console
./openshift-install 4.9.0-0.okd-2021-11-28-035710
built from commit 1c538b8949f3a0e5b993e1ae33b9cd799806fa93
release image quay.io/openshift/okd@sha256:7d8356245fc3a75fe11d1832ce9fef17f3dd0f2ea6f38271319c95918416b9d9
release architecture amd64
```

# Platform:

We try to deploy an OKD cluster with Baremetal documentation

# What happened?

During the Bootstrap installation the etcdctl container crash indefinitly. 

```console 
Feb 12 22:00:51 localhost bootkube.sh[501188]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Feb 12 22:00:51 localhost bootkube.sh[501188]: Error: unhealthy cluster
```

# How to reproduce it (as minimally and precisely as possible)?

We disable DHCP and configure network manually with nmcli command and add --copy-network to the coreos-installer command

```console
sudo nmcli con mod "Wired connection 1" ipv4.dns "10.7.168.146"
sudo nmcli con mod "Wired connection 1" IPv4.address 10.7.167.90/24
sudo nmcli con mod "Wired connection 1" IPv4.method manual
sudo nmcli device modify "ens33" ipv4.ignore-auto-dns yes
sudo nmcli con mod "Wired connection 1" IPv4.gateway 10.7.160.1
```

DNS configuration seems to be correctly configure. 

Ignitiation config files were created less than 12 hours before the begining of bootstraping. 

# Log 

[log-bundle-20220212230056.tar.gz](https://github.com/openshift/installer/files/8056456/log-bundle-20220212230056.tar.gz)

**Comment by TrevorBenson** [comment]
I see the same error in my `bootkube.service` logs on OKD 4.10.

I'm attempting to build a single node cluster following the [okd4-single-node-cluster](https://cgruver.github.io/okd4-single-node-cluster/) guide with OKD 4.10 and Fedora CoreOS 35.

**Comment by yujungcheng** [comment]
Hi, I have same issue on OKD 4.10 with Fedora CoreOS 36.

openshift-install version
`
./openshift-install 4.10.0-0.okd-2022-07-09-073606
built from commit d63a12ba0ec33d492093a8fc0e268a01a075f5da
release image quay.io/openshift/okd@sha256:5a748561c829c23c7413b0fe0ec8f97b4eabf5cfd1934b9e93a8a5df3f59738d
release architecture amd64
`
The bootstrap node juournal logs
$ journalctl -b -f -u release-image.service -u bootkube.service
`Jul 24 14:52:09 ssd-okd4-bootstrap etcdctl[10283]: {"level":"warn","ts":"2022-07-24T14:52:09.440Z","logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000c4380/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:2379: connect: connection refused\""}
Jul 24 14:52:09 ssd-okd4-bootstrap etcdctl[10283]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Jul 24 14:52:09 ssd-okd4-bootstrap etcdctl[10283]: Error: unhealthy cluster
Jul 24 14:52:09 ssd-okd4-bootstrap bootkube.sh[10273]: {"level":"warn","ts":"2022-07-24T14:52:09.440Z","logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000c4380/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:2379: connect: connection refused\""}
Jul 24 14:52:09 ssd-okd4-bootstrap bootkube.sh[10273]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Jul 24 14:52:09 ssd-okd4-bootstrap bootkube.sh[10273]: Error: unhealthy cluster
`

Reference: https://medium.com/swlh/guide-okd-4-5-single-node-cluster-832693cb752b

**Comment by marcin-zajac** [comment]
I have the sam issue now:

```
Nov 18 22:23:27 okd4-bootstrap etcdctl[17924]: {"level":"warn","ts":"2022-11-18T22:23:27.984Z","logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00014c000/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:2379: connect: connection refused\""}
Nov 18 22:23:27 okd4-bootstrap etcdctl[17924]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 18 22:23:27 okd4-bootstrap bootkube.sh[17913]: {"level":"warn","ts":"2022-11-18T22:23:27.984Z","logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00014c000/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:2379: connect: connection refused\""}
Nov 18 22:23:27 okd4-bootstrap bootkube.sh[17913]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 18 22:23:27 okd4-bootstrap bootkube.sh[17913]: Error: unhealthy cluster
Nov 18 22:23:27 okd4-bootstrap etcdctl[17924]: Error: unhealthy cluster
```

/reopen

**Comment by marcin-zajac** [comment]
@tsannier 
can you reopen please?

**Comment by CpuID** [comment]
This should be reopened, experiencing this on OKD `4.13.0-0.okd-2023-09-03-082426` currently.

**Comment by CpuID** [comment]
Curious to hear if anyone here has come up with a workaround so far...?

**Comment by drevofil** [comment]
same on `4.13.0-0.okd-2023-09-30-084937`
