### ISSUE TITLE
AWS UPI - Bootstrap failed to complete 

### ISSUE THREAD

**Issue by pdas-cp4i** [openshift/installer#5663]
# Version

```console
$ openshift-install version
openshift-install 4.8.28
built from commit aaa978bb5d76472df23f6e90293e68aaa43a8457
release image quay.io/openshift-release-dev/ocp-release@sha256:ba1299680b542e46744307afc7effc15957a20592d88de4651610b52ed8be9a8

# Platform:
<!--
Please specify the platform type: aws, libvirt, openstack or baremetal
-->
aws
<!--
Please specify:
* IPI (automated install with `openshift-install`. If you don't know, then it's IPI)
* UPI (semi-manual installation on customised infrastructure)
-->
UPI
# What happened?


ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get "https://api.myupicluster.demos-ipath.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 3.134.72.220:6443: connect: connection refused 
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
ERROR Bootstrap failed to complete: Get "https://api.myupicluster.demos-ipath.com:6443/version?timeout=32s": dial tcp 18.216.75.111:6443: connect: connection refused 
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane. 
FATAL Bootstrap failed to complete     

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

<!--
Please list the full steps required to reproduce the issue.
-->

```console
$ your-commands-here
```

# Anything else we need to know?

Bootstrap nodes and 3 Master nodes are up and running. But all 3 LB health check is failing for all the 5 nodes.

# References

- enter text here.

**Comment by staebler** [comment]
Did you run `openshift-install gather bootstrap`? If so, what is shown in the logs for the bootkube service on the bootstrap machine? If you did not run the command, you can ssh into the bootstrap to gather the same information about the bootkube service via `journalctl`.

**Comment by pdas-cp4i** [comment]
openshift-install gather bootstrap commands throws connection refused on port 22. I checked inbound security rule. The ssh port 22 is allowed from source anywhere.
i tried ssh into the bootstrap.. Getting connection refused.

Thanks

**Comment by staebler** [comment]
Check the console output for your bootstrap VM. Most likely your VM is having problems igniting because it cannot pull its ignition config.

**Comment by pdas-cp4i** [comment]
I see some ignition issues.  bootstrap.ign is in s3 bucket with public access.  

[    7.637528] ignition[667]: failed to acquire config: unsupported config version


    7.610477] ignition[667]: GET http://169.254.169.254/2009-04-04/user-data: attempt #5
[    7.618298] ignition[667]: GET result: OK
[    7.622995] ignition[667]: failed to fetch config: unsupported config version
[[0;1;31mFAILED[0m] Failed to start Ignition (disks).
See 'systemctl status ignition-disks.service' for details.
[[0;1;33mDEPEND[0m] Dependency failed for Initrd Default Target.
[    7.637528] ignition[667]: failed to acquire config: unsupported config version
[[0;32m  OK  [0m] Stopped target Timers.
[[0;32m  OK  [0m] Stopped target Remote File Systems.
[    7.650288] systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE
[[0;32m  OK  [0m] Stopped target Remote File Systems (Pre).
[[0;32m  OK  [0m] Stopped Ask OSTree to mount /var in initramfs.
[    7.664006] ignition[667]: Ignition failed: unsupported config version
[[0;32m  OK  [0m] Stopped File System Check on /dev/dâ¦6c49a-0403-474d-b727-80e256f7c564.
[    7.673950] systemd[1]: ignition-disks.service: Failed with result 'exit-code'.
[[0;32m  OK  [0m] Stopped target Initrd Root Device.
[    7.683145] systemd[1]: Failed to start Ignition (disks).
         Starting Setup Virtual Console...
[    7.691088] systemd[1]: Dependency failed for Initrd Default Target.
[    7.691248] systemd[1]: initrd.target: Job initrd.target/start failed with result 'dependency'.

**Comment by pdas-cp4i** [comment]
@staebler 
Never mind. I got wrong ami id.

Thanks for all your help
