### ISSUE TITLE
libvirt ipi fails to start master ovsdb-server.service

### ISSUE THREAD

**Issue by eformat** [openshift/installer#5685]
# Version
rhcos-4.10/410.84.202201251210-0/x86_64/rhcos-410.84.202201251210-0-qemu.x86_64.qcow2.gz

# Platform:
libvirt / ipi

single node using:

```
cat << EOF > cluster/install-config.yaml
apiVersion: v1
baseDomain: tt.testing
metadata:
  name: sno
networking:
  networkType: OpenShiftSDN
  machineNetwork:
  - cidr: 10.1.1.0/24
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
platform:
  libvirt:
    URI: qemu+tcp://192.168.86.24/system
pullSecret:
sshKey:
EOF
```

# What happened?

master fails to provision sdn

```bash
[root@sno-wh9l2-master-0 ~]# crictl ps -a
CONTAINER           IMAGE                                                              CREATED             STATE               NAME                                 ATTEMPT             POD ID
b76a6f1df0887       c96c12fc2cdb6e981406b972c048ddcaa54af264edfa249a4cd7563ea75297ce   52 seconds ago      Exited              sdn                                  18                  68a02b4655152
b3b1d6eda6003       c24961b12f33f0797115aad16309e00af96e8bb19f5fd96e057e7a9cf4c313f1   3 minutes ago       Running             kube-multus-additional-cni-plugins   1                   db9a70d1e40e0
a21936d77b554       0e5f1ba035a0b55c1ff2f90b3a88414ba518b94fe99e691db9c05e629536ee11   3 minutes ago       Exited              whereabouts-cni                      1                   db9a70d1e40e0
2be8a9d6115a4       0e5f1ba035a0b55c1ff2f90b3a88414ba518b94fe99e691db9c05e629536ee11   3 minutes ago       Exited              whereabouts-cni-bincopy              1                   db9a70d1e40e0
d80418fbd6da3       eee4f46662a4d9ab790e0db08d1f002e1520bd7d6360f7e968dac400e24b2621   3 minutes ago       Exited              routeoverride-cni                    1                   db9a70d1e40e0
47324e784a3e6       7c9607ef231c0ffbdd6348e70835f785801249ac67abafdc5629085203ffa23c   3 minutes ago       Exited              bond-cni-plugin                      1                   db9a70d1e40e0
44babec651a1b       588c6d45b6819c84b7a95cde43c73bb50d63e3a7acc9ca6b320f879fc39e1e2f   3 minutes ago       Exited              cni-plugins                          1                   db9a70d1e40e0
e661d4415032a       19fe8540f8737eec13b6ef65a0acfe4135415299551fed824afaefcb3067f7ad   3 minutes ago       Running             kube-rbac-proxy                      1                   68a02b4655152
9736a394253ec       19fe8540f8737eec13b6ef65a0acfe4135415299551fed824afaefcb3067f7ad   3 minutes ago       Running             kube-rbac-proxy                      1                   b7b1bfa2d1039
b57283844d87a       a9d91e3ff8947c1e83bd56039877c2fa34ce9e10b469fcc0861f6dcb12dbc4d2   3 minutes ago       Running             config-sync-controllers              1                   acc9d56ab856d
f3ba11c7d04d7       c96c12fc2cdb6e981406b972c048ddcaa54af264edfa249a4cd7563ea75297ce   3 minutes ago       Running             sdn-controller                       1                   b7b1bfa2d1039
530a61b9d26e2       e416979342818a7856d52cf43e12b788ad303d93b3b938c0d94b09045144a57a   3 minutes ago       Running             network-operator                     1                   f211b3d5513f3
0ce7c2c749123       fefdbd55e1cb334ef6e37f19aaa40259c85b3f16e01f3d9139d8e8dd56c80f5c   3 minutes ago       Exited              egress-router-binary-copy            1                   db9a70d1e40e0
9adc063463693       a9d91e3ff8947c1e83bd56039877c2fa34ce9e10b469fcc0861f6dcb12dbc4d2   3 minutes ago       Running             cluster-cloud-controller-manager     1                   acc9d56ab856d
5c5e6b9fea09d       c24961b12f33f0797115aad16309e00af96e8bb19f5fd96e057e7a9cf4c313f1   3 minutes ago       Running             kube-multus                          5                   5978d066d6130

```

```bash
$ ssh core@10.1.1.11
Fedora CoreOS 35
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

Last login: Mon Mar  7 01:19:37 2022 from 10.1.1.1
[systemd]
Failed Units: 1
  ovsdb-server.service
[core@sno-wh9l2-master-0 ~]$ sudo su -
Last login: Mon Mar  7 01:20:04 UTC 2022 on pts/0
[systemd]
Failed Units: 1
  ovsdb-server.service
[root@sno-wh9l2-master-0 ~]# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
core:x:1000:1000:CoreOS Admin:/var/home/core:/bin/bash
[root@sno-wh9l2-master-0 ~]# systemctl status ovsdb-server.service
× ovsdb-server.service - Open vSwitch Database Unit
     Loaded: loaded (/usr/lib/systemd/system/ovsdb-server.service; static)
    Drop-In: /etc/systemd/system/ovsdb-server.service.d
             └─10-ovsdb-restart.conf
     Active: failed (Result: exit-code) since Mon 2022-03-07 01:32:17 UTC; 41s ago
    Process: 1203 ExecStartPre=/usr/bin/rm -f /run/openvswitch.useropts (code=exited, status=0/SUCCESS)
    Process: 1204 ExecStartPre=/usr/bin/chown ${OVS_USER_ID} /var/run/openvswitch /var/log/openvswitch (code=exited, status=1/FAILURE)
    Process: 1206 ExecStartPre=/bin/sh -c /usr/bin/echo "OVS_USER_ID=${OVS_USER_ID}" > /run/openvswitch.useropts (code=exited, status=0/SUCCESS)
    Process: 1208 ExecStartPre=/bin/sh -c if [ "$${OVS_USER_ID/:*/}" != "root" ]; then /usr/bin/echo "OVS_USER_OPT=--ovs-user=${OVS_USER_ID}" >> /run/openvswitch.useropts; fi (code=exited, status=0/SUC>
    Process: 1210 ExecStart=/usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor --system-id=random ${OVS_USER_OPT} start $OPTIONS (code=exited, status=1/FAILURE)
        CPU: 40ms

Mar 07 01:32:17 sno-wh9l2-master-0 systemd[1]: ovsdb-server.service: Scheduled restart job, restart counter is at 5.
Mar 07 01:32:17 sno-wh9l2-master-0 systemd[1]: Stopped Open vSwitch Database Unit.
Mar 07 01:32:17 sno-wh9l2-master-0 systemd[1]: ovsdb-server.service: Start request repeated too quickly.
Mar 07 01:32:17 sno-wh9l2-master-0 systemd[1]: ovsdb-server.service: Failed with result 'exit-code'.
Mar 07 01:32:17 sno-wh9l2-master-0 systemd[1]: Failed to start Open vSwitch Database Unit.

[root@sno-wh9l2-master-0 ~]# cat /run/openvswitch.useropts
OVS_USER_ID=openvswitch:hugetlbfs
OVS_USER_OPT=--ovs-user=openvswitch:hugetlbfs

[root@sno-wh9l2-master-0 ~]# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
core:x:1000:1000:CoreOS Admin:/var/home/core:/bin/bash

[root@sno-wh9l2-master-0 ~]# ls -lartZ /etc/openvswitch 
total 20
-rw-r--r--.  1  800  801 system_u:object_r:openvswitch_rw_t:s0  163 Jan 25 12:16 default.conf
-rw-r--r--.  1  800  801 system_u:object_r:openvswitch_rw_t:s0   37 Mar  7 00:34 system-id.conf
drwxr-xr-x.  2  800  801 system_u:object_r:openvswitch_rw_t:s0   48 Mar  7 01:20 .
drwxr-xr-x. 89 root root system_u:object_r:etc_t:s0            8192 Mar  7 01:32 ..

```

# What you expected to happen?

ovsdb-server.service should start, sdn pod should run OK

# How to reproduce it (as minimally and precisely as possible)?

happens every time
```bash
openshift-install create cluster --dir=cluster
```

**Comment by srinivasabb** [comment]
What di you do to fix this ? I am facing the similar issue in Azure VM

[root@okdsrini2july-vlk26-master-0 openvswitch]# /usr/share/openvswitch/scripts/ovs-ctl version
ovsdb-server (Open vSwitch) 3.1.1
ovs-vswitchd (Open vSwitch) 3.1.1
DPDK 22.11.1

Log
× ovsdb-server.service - Open vSwitch Database Unit
     Loaded: loaded (/usr/lib/systemd/system/ovsdb-server.service; static)
    Drop-In: /etc/systemd/system/ovsdb-server.service.d
             └─10-ovsdb-restart.conf
             /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
             /usr/lib/systemd/system/ovsdb-server.service.d
             └─99-okd-permission-fix.conf
     Active: failed (Result: exit-code) since Sun 2023-07-02 15:58:34 UTC; 2s ago
    Process: 39086 ExecStartPre=/usr/bin/rm -f /run/openvswitch.useropts (code=exited, status=0/SUCCESS)
    Process: 39088 ExecStartPre=/usr/bin/chown ${OVS_USER_ID} /run/openvswitch /var/log/openvswitch (code=exited, status=1/FAILURE)
    Process: 39090 ExecStartPre=/bin/sh -c /usr/bin/echo "OVS_USER_ID=${OVS_USER_ID}" > /run/openvswitch.useropts (code=exited, status=0/SUCCESS)
    Process: 39093 ExecStartPre=/bin/sh -c if [ "$${OVS_USER_ID/:*/}" != "root" ]; then /usr/bin/echo "OVS_USER_OPT=--ovs-user=${OVS_USER_ID}" >> /run/openvswitch.useropts; fi (code=exited, status=0/SUCCESS)
    Process: 39096 ExecStartPre=/bin/sh -c /usr/bin/chown -R ${OVS_USER_ID} /var/lib/openvswitch (code=exited, status=1/FAILURE)
    Process: 39098 ExecStartPre=/bin/sh -c /usr/bin/chown -R ${OVS_USER_ID} /etc/openvswitch (code=exited, status=1/FAILURE)
    Process: 39100 ExecStartPre=/bin/sh -c /usr/bin/chown -R ${OVS_USER_ID} /run/openvswitch (code=exited, status=1/FAILURE)
    Process: 39102 ExecStart=/usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor --system-id=random ${OVS_USER_OPT} start $OPTIONS (code=exited, status=1/FAILURE)
        CPU: 89ms

Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Scheduled restart job, restart counter is at 5.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: Stopped ovsdb-server.service - Open vSwitch Database Unit.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Start request repeated too quickly.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Failed with result 'exit-code'.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: Failed to start ovsdb-server.service - Open vSwitch Database Unit.
[root@okdsrini2july-vlk26-master-0 openvswitch]# journalctl -u ovsdb-server.service -f
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 ovs-ctl[39143]: setpriv: failed to parse reuid: ''
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 ovs-ctl[39102]: Starting ovsdb-server ... failed!
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Control process exited, code=exited, status=1/FAILURE
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Failed with result 'exit-code'.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: Failed to start ovsdb-server.service - Open vSwitch Database Unit.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Scheduled restart job, restart counter is at 5.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: Stopped ovsdb-server.service - Open vSwitch Database Unit.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Start request repeated too quickly.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: ovsdb-server.service: Failed with result 'exit-code'.
Jul 02 15:58:34 okdsrini2july-vlk26-master-0 systemd[1]: Failed to start ovsdb-server.service - Open vSwitch Database Unit.
^C

**Comment by mohammadfalahat** [comment]
it's because ovsdb-server looking for /usr/local instead of /run directly, create these symlinks to solve that problem:

```
mkdir -p /usr/local/var/run/openvswitch
ln -s /run/openvswitch/ovsdb-server.pid /usr/local/var/run/openvswitch/ovsdb-server.pid
ln -s /run/openvswitch/db.sock /usr/local/var/run/openvswitch/db.sock
```
