### ISSUE TITLE
Vsphere IPI installation how can I create apiVIP

### ISSUE THREAD

**Issue by teomanS** [openshift/installer#5728]
# Version

```console
$ openshift-install version
./openshift-install 4.8.14
built from commit 0c5cd91b7f5b9c4497ce294e6af74afe30bd3fb1
release image quay.io/openshift-release-dev/ocp-release@sha256:bf48faa639523b73131ec7c91637d5c94d33a4afe09ac8bdad672862f5e86ccb
```

# Platform:
Vsphere

IPI 

# What happened?

openshift master get error when they try to get master configuration from "https://apiVIP:22623/config/master " although bootstrap VM is up and running.

# What you expected to happen?

For example api DNS is = api.myocp.mydomain.com and It's apiVIP address is 10.1.0.161.
I think this DNS should be the address of the load balancer in front of the bootstrap and master nodes.
On the other hand bootstrap and master nodes should get their IP address dynamically from dhcp server.
How can I define this Loadbalancer when I do not know the IPs of bootstrap and master nodes?

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create cluster
```

# References

https://docs.openshift.com/container-platform/4.8/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html

**Comment by saintdle** [comment]
MAC address reservations on DHCP for your VMs before you boot them. 

If you are using IPI installation, which is what you are specifying in the docs link. Then the LB is done within the OpenShift cluster anyway, not externally. So they boot off DHCP and the VIP address floats.
