### ISSUE TITLE
add support for graviton 3 systems

### ISSUE THREAD

**Issue by ausil** [openshift/installer#5740]
Amazon has Graviton 3 based instances in their cloud. https://aws.amazon.com/ec2/graviton/  the instance type is c7g when trying to install to it the install fails to get started 

# Version

```console
$ openshift-install version
openshift-install 4.10.4
built from commit 3b701903d96b6375f6c3852a02b4b70fea01d694
release image quay.io/openshift-release-dev/ocp-release@sha256:94b6b1daf167810d2da0fac35b5628458a9b2327443e2da6be454c3d01ac1538
release architecture arm64

```

# Platform:

aws

IPI
# What happened?

FATAL failed to fetch Metadata: failed to load asset "Install Config": [controlPlane.platform.aws.type: Invalid value: "c7g.xlarge": instance type c7g.xlarge not found, compute[0].platform.aws.type: Invalid value: "c7g.xlarge": instance type c7g.xlarge not found] 

# What you expected to happen?
Install to start and c7g instances to be used

# How to reproduce it (as minimally and precisely as possible)?

do an AWS install  and change the instance type to c7g, this does require an account authorised for use with graviton 3 instances until Amazon opens up access to everyone

**Comment by yselkowitz** [comment]
[aws-sdk-go](https://github.com/aws/aws-sdk-go) has yet to be updated for c7g instance types, possibly because it is not GA.  Once that is available upstream, then it needs to be updated in all the places it is vendored (installer, terraform-providers-aws, autoscaler, cluster-api-provider-aws, etc.).

**Comment by yselkowitz** [comment]
Deployments on c7g have been successfully tested
/close
