### ISSUE TITLE
LoadBalancer Services are not provisioned on cloud platforms

### ISSUE THREAD

**Issue by ironcladlou** [openshift/installer#576]
# Version

```console
$ openshift-install version
<your output here>
```

# Platform (aws|libvirt|openshift):

Enter text here.

# What happened?

Enter text here.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by sjenning** [comment]
I think this was opened in error.  https://github.com/openshift/installer/issues/577 has same subject with actual information.

**Comment by ironcladlou** [comment]
No idea what happened there... thanks
