### ISSUE TITLE
Zero worker nodes and only master nodes is showing.

### ISSUE THREAD

**Issue by Kabsuri31** [openshift/installer#5768]
# Version

```console
$ openshift-install version
4.7
```

# Platform:
AWS

# What happened?

No worker nodes are showing when doing **oc get nodes**, it only shows master nodes in ready state. Install logs saying some cluster operators are still updating and failing after time out.
Please note this set up is hybrid set up . It means VM is in Google cloud and openshift cluster is going to be created in AWS.
Let me know if you need any other information.

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

Worker nodes should come up, so that required cluster operators(like console, authentication, monitoring etc) can be installed and cluster gets created.

# How to reproduce it (as minimally and precisely as possible)?
Init VM(Google cloud) in different cloud and openshift creation in AWS.

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by fortinj66** [comment]
any pending CSRs?  `oc get csr`
