### ISSUE TITLE
LoadBalancer Services are not provisioned on cloud platforms

### ISSUE THREAD

**Issue by ironcladlou** [openshift/installer#577]
# Version

```console
$ bin/openshift-install version
bin/openshift-install v0.3.0-66-gfd240e9beccd6ac3dfa7a219400b961a05652520
Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html
```

# Platform (aws|libvirt|openshift):

aws

# What happened?

```
$ oc get -n openshift-ingress services/router-default -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-30T17:21:27Z
  labels:
    app: router
    router: router-default
  name: router-default
  namespace: openshift-ingress
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: DaemonSet
    name: router-default
    uid: 3bcc5370-dc68-11e8-8eea-06e196c833cc
  resourceVersion: "7897"
  selfLink: /api/v1/namespaces/openshift-ingress/services/router-default
  uid: 3bdcfed9-dc68-11e8-8eea-06e196c833cc
spec:
  clusterIP: 10.3.154.62
  externalTrafficPolicy: Local
  healthCheckNodePort: 30652
  ports:
  - name: http
    nodePort: 31523
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: router
    router: router-default
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

# What you expected to happen?

Load balancer should be provisioned and an external IP/hostname assigned to the service.

# How to reproduce it (as minimally and precisely as possible)?

Start a new cluster and run:

```
$ oc get -n openshift-ingress services/router-default -o yaml
```
# Anything else we need to know?

Root cause is lack of `cloud-provide` configuration for kube-controller-manager. See the `kube-system daemonsets/kube-controller-manager` logs:

```
E1026 00:07:32.866829       1 core.go:72] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
```

# References

Related to https://github.com/openshift/installer/issues/530.

**Comment by mazzystr** [comment]
I dunno.  "No cloud provider" doesn't feel right.  My cluster has int, ext, con elb instances and worker ec2 instances.

For me the master instances were registered to the con elb.  That's not right since the openshift-ingress/daemonset.apps/router-default uses nodeSelector: node-role.kubernetes.io/worker: "".  I manually removed the master instances and registered the worker instances.  http://blah.ccallegar.ccallegar.sysdeseng.com immediately became browseable an expected with a router error of "Application is not available"

**Comment by ironcladlou** [comment]
We already know `--cloud-provider` and `--cloud-provider-config` are no longer being passed to kube-controller-manager (a regression with the removal of kube-core-operator). We know the Kube service controller fails to start because of the missing arguments. The service controller is responsible for provisioning LBs related to LoadBalancer type Services. https://github.com/openshift/cluster-kube-controller-manager-operator/pull/65 is the fix.

>The ELB listener, forwarder, and worker SG ports don't match up.

The current bug is about ELBs managed by the Kube service controller. The ELB and other resources you are referencing are part of cluster provisioning and are unrelated.

>the master instances were registered to the con elb. That's not right since the openshift-ingress/daemonset.apps/router-default uses nodeSelector: node-role.kubernetes.io/worker: "". I manually removed the master instances and registered the worker instances. http://blah.ccallegar.ccallegar.sysdeseng.com immediately became browseable an expected with a router error of "Application is not available"

External DNS for the routers isn't yet implemented. The master ELBs aren't the way routers are publicly exposed. Further, even with the router LB regression fix, external DNS for app routing isn't yet implemented, so app routes are only available by going through the LB directly and setting `Host` headers.
