### ISSUE TITLE
Cannot install OCP4.8.21 on VMs by vmware workstation

### ISSUE THREAD

**Issue by vincent-pli** [openshift/installer#5837]
# Version

```console
$ openshift-install version
./openshift-install 4.8.21
built from commit 1c11fbcac64b85985ed1c30852317164cab06f10
release image registry.ocp48.cluster.local.com:5000/ocp4/openshift4@sha256:f7e664bf56c882f934ed02eb05018e2683ddf42135e33eae1e4192948372d5ae
```

# Platform:
The environments is UPI, with vmware workstation on a windows server.

# What happened?
Basically, the OCP was not installed success.
Since I try to install a single master envrionment. and the `bootstrap` seems works fine but the `master` cannot be bootstrap succeed.
- With different option when I create VM with vmware workstation about `hardware compatibility` (in my scenario, I adopt `workstation 1x.x`  )
<img width="491" alt="图片" src="https://user-images.githubusercontent.com/8669744/165040664-5c97144b-36ef-441e-919a-d3eec5de7a9e.png">

With different option(workstation 1x.x), I got two different exception:
- `Master` cannot be bootstrap, no container was created(with `crictl ps`)
- Bootstrapped but get `go routine` error in both `etcd operator` and `api-server operator`

# What you expected to happen?
OCP installed

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?
I wonder to know if the virtualization will effect the installation of OCP.
In vsphere env, the option is `ESXi` by default, and everything works fine

# References

- enter text here.

**Comment by jcpowermac** [comment]
VMware Workstation isn't supported with OCP.
