### ISSUE TITLE
bootkube is looping on "unable to determine api-server readiness: API Server http status: 0"

### ISSUE THREAD

**Issue by wjiangjay** [openshift/installer#586]
Hi:

I am trying to install a cluster with libvirt, and nearly done.
But I often met the following issues:

```
> on bootstrap node:
bootkube service is looping on "unable to determine api-server readiness: API Server http status: 0" 
and run out the timeout.
> on master0 node:
the latest log of kubelet service is `csr for this node is still valid`
```

So I have to destroy cluster and create a new one, sometime I will setup successfully.

So my question is, what should I do for this? just wait? 

And a csr for master is in pending status actually

**Comment by wjiangjay** [comment]
I got the answer now, the `auth` directory of previous `create cluster` must be deleted for next try.

**Comment by wking** [comment]
> I got the answer now, the auth directory of previous create cluster must be deleted for next try.

#532 should help with this

**Comment by abhinavdahiya** [comment]
> I got the answer now, the `auth` directory of previous `create cluster` must be deleted for next try.

/close
