### ISSUE TITLE
Ctrl-c not handled well

### ISSUE THREAD

**Issue by sttts** [openshift/installer#590]
When stopping the installer with ctrl-c in the terminal, terraform keeps running and prints log output. Looks like a sighub signal handler is missing and not shutting down subprocesses.

When killing terraform, a following `openshift-install destroy cluster` does not work (doesn't find necessary files like metadata.json). This leads to a lot of resource leaking.

**Comment by kikisdeliveryservice** [comment]
After I do a `openshift-install destroy cluster`, I always also do `rm -rf .openshift_install_state.json auth/ metadata.json terraform.tfstate terraform.tfvars` to clean up those files. Probably not ideal but it's been what works for me.

**Comment by wking** [comment]
> My point is more that I cannot destroy the cluster if some files are missing.

I'm planning on updating our Terraform invocation once I get back to #556 to:

* Separate the `metadata.json` information we have before our `terraform` invocation (which is what you'd need to clean up) from the metadata produced by the `terraform` invocation.
* Use contexts, e.g. [`CommandContext`][1], which would allow us to cancel running commands gently from signal handlers.

[1]: https://golang.org/pkg/os/exec/#CommandContext

**Comment by eparis** [comment]
we write out metadata.json much earlier now with sufficient information to clean up an AWS cluster. We also do a better job not continuing to run terraform in the background. So I'm going to close this issue.
