### ISSUE TITLE
waiting for the kubernetes API: Get "https://api.<cluster name>.<domain name>:6443/version": dial tcp 10.1.xxx.xxx:6443: connect: connection refused

### ISSUE THREAD

**Issue by moalghwell** [openshift/installer#5948]
# Version

```console
$ openshift-install version
./openshift-install 4.10.14
built from commit Oadfce2albfede7d74ac8930a5d56df1a406a533
release image quay.io/openshift-release-dev/ocp-release@sha256: e6aa643f494f64eefc8a6ad92b64156290bccd7e5cda56b8809f3a67ee2a53bb
release architecture amd64
```

# Platform:
vSphere

* IPI

# What happened?

The installation goes and the bootstrap created with the IP for "api.<cluster name>.<domain name>. The 3 masters created with no IP, and kept looping trying to dial the bootstrap with an answer of "connection refused".
The other error appears related to SSH. The message was "failed to create ssh client ..."
Also, there is a message stating "bootstrap failed to complete ... connection refused"

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
# ./openshift-install create cluster --log-level debug
```
# Anything else we need to know?

Enter text here.

# References

**Comment by Mohamed-Zakaria333** [comment]
i face the same issue also

**Comment by Praveenmail2him** [comment]
I face the same issue also, this has to be prioritized.

**Comment by Praveenmail2him** [comment]
I face the same issue also, this has to be prioritized. My platform is AWS.

**Comment by 0x4d6165** [comment]
stalebots are the death of this project
