### ISSUE TITLE
OCP V4.10 create-templates-and-vms.yml Ansible playbook for oVirt on UPI fails

### ISSUE THREAD

**Issue by pdfruth** [openshift/installer#5978]
# Version
4.10
```console
$ openshift-install version
./openshift-install 4.10.15
built from commit 629c3e0aadf8825dd8a3bc4c8a75d41f625140ba
release image quay.io/openshift-release-dev/ocp-release@sha256:ddcb70ce04a01ce487c0f4ad769e9e36a10c8c832a34307c1b1eb8e03a5b7ddb
release architecture amd64
```

# Platform:
oVirt 4.15
UPI on x86_64

# What happened?
As per the documentation [here](https://docs.openshift.com/container-platform/4.10/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-creating-templates-virtual-machines_installing-rhv-user-infra);
https://docs.openshift.com/container-platform/4.10/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-creating-templates-virtual-machines_installing-rhv-user-infra

Running the create-templates-and-vms.yml Ansible playbook on the oVirt engine server with this command;
```
ansible-playbook -i inventory.yml create-templates-and-vms.yml
```

Results in an error message, and the playbook fails;
```
.
.
Template with name 'worker_rhcos_tpl' and version 'None' in data center 'Default' was not found
.
.
PLAY RECAP *********************************************************************
localhost                  : ok=54   changed=5    unreachable=0    failed=1    skipped=44   rescued=0    ignored=0 
```

# What you expected to happen?

Ansible playbook should complete with no failures

# Anything else we need to know?

The create-templates-and-vms.yml  Ansible playbook has a small bug, which is easily fixed by changing one line of code.

In the [create-templates-and-vms.yml file](https://github.com/openshift/installer/blob/release-4.10/upi/ovirt/create-templates-and-vms.yml) here;
https://github.com/openshift/installer/blob/release-4.10/upi/ovirt/create-templates-and-vms.yml

change line 59
from;
`        template_name: "{{ item.disks.0.name }}"`
to;
`        template_name: "{{ item.template }}"`

**Comment by barbacbd** [comment]
@pdfruth I believe that this issue should be migrated over to openshift ansible. 

Can you provide the version of ansible that you were using when you encountered this error?
