### ISSUE TITLE
OCP bootstrap failed to complete on Openstack (ppc64le)

### ISSUE THREAD

**Issue by aditijadhav38** [openshift/installer#6024]
# Version OpenShift Installer 4.11.0-0.nightly-ppc64le-2022-06-14-051507

```console
$ openshift-install version
openshift-install 4.11.0-0.nightly-ppc64le-2022-06-14-051507
built from commit 190547fa8cb065dddb88ec17b9994c5c81b42004
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:630b3891c90fce91898abe441128e2b8600ee75d4b0631d98f539f6d1c55e554
release architecture ppc64le
```

# Platform:
openstack 

# Architecture:
ppc64le

Installing with IPI:
* IPI (automated install with `openshift-install`.)

# What happened?
We are trying to deploy ocp on openstack with IPI. We have set DNS to localhost. 
We can see bootstrap, masters and workers machine got created on openstack env. However facing below issue 
```
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://****:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp *.*.*.*:6443: i/o timeout
ERROR Bootstrap failed to complete: Get "https://****:6443/version": dial tcp *.*.*.*:6443: i/o timeout
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
```

# What you expected to happen?

OCP cluster should deploy successfully and we can access master and worker machines.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create cluster --dir=**** --log-level=debug
```

**Comment by kulkarma** [comment]
Were you able to solve this issue. I am observing this on OCP 4.10.37.
