### ISSUE TITLE
Some cluster operators are still updating: authentication, console

### ISSUE THREAD

**Issue by fenggolang** [openshift/installer#6079]
![image](https://user-images.githubusercontent.com/16982786/177292993-18c99ea3-05f0-49d4-8dde-b407213d77f9.png)

![image](https://user-images.githubusercontent.com/16982786/177293273-637d4139-5f00-4253-b6cb-2ab128a126e5.png)

**Comment by r4f4** [comment]
https://docs.openshift.com/container-platform/4.10/installing/installing-troubleshooting.html
