### ISSUE TITLE
[oVirt IPI] Bootstrap never completes due to api-int.<domain> not resolving (similar to https://github.com/openshift/installer/pull/5788)

### ISSUE THREAD

**Issue by fortinj66** [openshift/installer#6104]
# Version

```console
[root@dev okd]# ./openshift-install version
./openshift-install 4.10.0-0.okd-2022-05-07-021833
built from commit 0adfce2a1bfede7d74ac8930a5d56df1a406a533
release image quay.io/openshift/okd@sha256:249685016c13b5a6890a6999a6b1f0b7e7d5fded1be345b4b9e85764e4eac0e4
release architecture amd64

```

# Platform:
oVirt IPI

# What happened?

Similar to https://github.com/openshift/installer/pull/5788 for vSphere, Bootstrap node is unable to resolve `api-int.<domain>` and cannot finish the bootstrap process 

```
Jul 07 20:27:42 2603-6080-c340-0400-b061-2355-9743-0394.res6.spectrum.com bootkube.sh[1751]: Trying again to restore CVO overrides
Jul 07 20:27:43 2603-6080-c340-0400-b061-2355-9743-0394.res6.spectrum.com bootkube.sh[17197]: Unable to connect to the server: dial tcp: lookup api-int.okd4.fortin.pvt: no such host
```

# What you expected to happen?

Bootstrap to finish successfully

# How to reproduce it (as minimally and precisely as possible)?

oVirt IPI install  (and not having api-int.<domain> in DNS)

Unlike vSphere, I have not been able to come up with a way to pass the Domain to the oVirt bootstrap node.  My initial thought was to add an ovirt_vm_tag with the domain, but I cannot figure out how to read that tag from within the bootstrap VM at build time.  There does not seem to be an equivalent tool to `vmtoolsd`

**Comment by Murf** [comment]
create a DNS A recoird for api-int that resolves to the same IP adders you have for api
