### ISSUE TITLE
openshift-image-registry: CrashLoopBackOff

### ISSUE THREAD

**Issue by kikisdeliveryservice** [openshift/installer#616]
# Version

```console
$ openshift-install version
openshift-install v0.3.0-141-g503d150d04bd32d502fadb80108f867d0fb5cc5c
```
# Platform (aws|libvirt|openshift):
libvirt

# What happened?
After pulling the recent master today
`oc get pods --all-namespaces`
shows that:
`openshift-image-registry  cluster-image-registry-operator-77ddd8b4fb-dcgwc   0/1    CrashLoopBackOff   6          10m
`
# What you expected to happen?

I expected this to run sucessfully.

# How to reproduce it (as minimally and precisely as possible)?

```console
$openshift-install --log-level=debug create cluster
$oc get pods --all-namespaces|grep CrashLoop

```

cc: @cgwalters

**Comment by wking** [comment]
If you see this again, can you get logs from the crashing pod?  Using the above output, it would be something like:

```console
$ oc logs -n openshift-image-registry --all-containers cluster-image-registry-operator-77ddd8b4fb-dcgwc
```

you might need `-p` as well to get the previous run.  That may produce too much output to paste here, but hopefully the error sticks out at you ;).

**Comment by kikisdeliveryservice** [comment]
Will do @wking ! Currently not seeing this on  `v0.3.0-151-g8ef57585ccc79b3ac54da7f0757593d4c6a54e70` which makes me hopeful.

**Comment by wking** [comment]
Maybe this is openshift/cluster-image-registry-operator/issues/58?

Also useful for cases like this is the release version and/or operator version of the crashing pod.  For example (different pod):

```console
$ KUBECONFIG=wking/auth/kubeconfig oc get pod -o json -n openshift-cluster-network-operator cluster-network-operator-84ccl | jq '.status.containerStatuses[] | {name, state, image}'
{
  "name": "cluster-network-operator",
  "state": {
    "waiting": {
      "message": "configmaps \"cluster-config\" not found",
      "reason": "CreateContainerConfigError"
    }
  },
  "image": "registry.svc.ci.openshift.org/openshift/origin-v4.0-20181106232208@sha256:af8333760046cefb84d5f222a96e28c8af06823de8e2fed44647d614cedc925a"
}
```

**Comment by bparees** [comment]
this was fixed by https://github.com/openshift/cluster-image-registry-operator/pull/54
