### ISSUE TITLE
openshift-install executable not working on Apple Silicon

### ISSUE THREAD

**Issue by tkelkermans** [openshift/installer#6224]
Hello,

I tried to install openshift-install 4.11 command-line on my Apple Macbook Pro M1 (Apple Silicon).

Downloading it from https://console.redhat.com/openshift/install/ (macOS aarch64), that points to : https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/pre-release/openshift-install-mac-arm64.tar.gz

When I try to use the openshift-install command line I get the following error on Mac : "“openshift-install” is damaged and can’t be opened. You should move it to the Bin."

It works using x86_64 and Rosetta2.
I'm using a MacBook Pro 14" M1 Pro, running Monterey 12.5

**Comment by r4f4** [comment]
That's because the binary is unsigned. It should work fine if you sign it yourself:
```
//some machines need to run with sudo
codesign --force --deep -s - openshift-install
```
