### ISSUE TITLE
Pull secret prompt is ambiguous

### ISSUE THREAD

**Issue by brianredbeard** [openshift/installer#627]
# Version

```console
$ openshift-install version
./openshift-install v0.3.0-151-g8ef57585ccc79b3ac54da7f0757593d4c6a54e70
Terraform v0.11.10
```

# Platform ibvirt:

N/A

# What happened?

While attempting to run the installer it prompts for the following:

```
? Pull Secret [? for help] 
```

I attempted first to copy-paste the pull secret, which was validated with `jq` and received the following error:

`X Sorry, your reply was invalid: unexpected end of JSON input`

I then attempted to put it into a file named `ocp-secret.json` (in case it was ambiguously prompting me for a file instead of copying/pasting the secret) and received the following error:

`X Sorry, your reply was invalid: invalid character 'o' looking for beginning of value`

# What you expected to happen?

Who knows?  The first time I errored out was when prompted for the SSH key (I didn't have colors enabled in my terminal and I didn't expect arrow key navigation despite the prompting on the screen).

The next time I errored out was when I realized that despite fancy readline handling with the errors, it wasn't handling common key-binding scenarios and `ctrl+w` didn't work.

The third time I had to abort was when prompted for base domain followed by cluster name (I included my cluster name _in_ my base domain because I'm using a well structure name server delegation structure).

So this is my fourth attempt at just walking through the _*prompts*_ on the installer.  Who knows what could happen next. 

# How to reproduce it (as minimally and precisely as possible)?

See above.

**Comment by brianredbeard** [comment]
It appears that the pull-secret prompt expects the input to be compacted.  This should be more clearly specified.

**Comment by abhinavdahiya** [comment]
> The third time I had to abort was when prompted for base domain followed by cluster name (I included my cluster name in my base domain because I'm using a well structure name server delegation structure).

@brianredbeard just to more info around the UX

why did you include `clustername` in the dns domain when prompted for `basedomain`.

So if you had continued with 
```
basedomain = `clustername.<somthing>` 
clustername = `clustername`
```
the installer would have created dns entries like, the k8s api would be `clustername-api.clustername.<something>`. Do you think that would be acceptable? If not what would you have expected?
