### ISSUE TITLE
Wrong certs generated?

### ISSUE THREAD

**Issue by droslean** [openshift/installer#646]
# Version
```console
$ openshift-install version
./openshift-install v0.3.0-161-ge64a43d293f594c1d51a317822aa6b4783295ecb
Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html

```

# Platform:

libvirt

# What happened?
Kubelet in master node can't start
```
 failed to run Kubelet: cannot create certificate signing request: the server rejected our request for an unknown reason (post certificatesigningrequests.certificates.k8s.io)
```

# Debug Logs
http://pastebin.test.redhat.com/667783

**Comment by wking** [comment]
>     failed to run Kubelet: cannot create certificate signing request: the server rejected our request for an unknown reason (post certificatesigningrequests.certificates.k8s.io)

Was the before tge etcd-cert-signer exited?  We expect the kubelet to have cert issues until at least the bootkube API comes up.  Can you work through [this][1] and the rest of the troubleshooting doc to narrow this down?

[1]: https://github.com/openshift/installer/blob/a5557750a0ae99cd164031485ca4edb5262d70e6/docs/user/troubleshooting.md#etcd-is-not-running
