### ISSUE TITLE
Error: unknown flag: --image-references for Machine Config Operator image while bringing up bootstrap for s390x arch

### ISSUE THREAD

**Issue by Phaneendra-Ravuri** [openshift/installer#6477]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-7091-g4609fe4eb24e84029e22f78be2de9527e1ad27e7
built from commit 4609fe4eb24e84029e22f78be2de9527e1ad27e7
release image quay.io/openshift-release-dev/ocp-release:4.12.0-ec.0-s390x
release architecture s390x
```

# Platform: ibmcloud

* IPI (automated install with `openshift-install`.)

# What happened?

Triggered IPI installation for ibmcloud with s390x arch rhcos custom images and ocp-release image with 4.12-ec-0.
While creating the cluster, IPI is failing at bootstrap boot up with an error mentioned below related to machine config operator.

Oct 11 15:17:44 phani-s390x-oct11-xp2kn-bootstrap bootkube.sh[134354]: Rendering MCO manifests...
Oct 11 15:17:45 phani-s390x-oct11-xp2kn-bootstrap bootkube.sh[135750]: Error: unknown flag: --image-references
Oct 11 15:17:45 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 15:17:45 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: bootkube.service: Failed with result 'exit-code'.
Oct 11 15:17:51 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: bootkube.service: Service RestartSec=5s expired, scheduling restart.
Oct 11 15:17:51 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 89.
Oct 11 15:17:51 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: Stopped Bootstrap a Kubernetes cluster.
Oct 11 15:17:51 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: Started Bootstrap a Kubernetes cluster

# What you expected to happen?

IPI trigger should start bootstrap node seamlessly without this flag issue as tha images we used are totally s390x compatible

# How to reproduce it (as minimally and precisely as possible)?

trigger the create cluster command using the openshift-install binary of s390x arch and you should see the debug logs showing unable to contact the cluster on it's API, then login bootstrap node and check for the journalctl logs of bootkube.service as by that time bootstrap and master nodes should be created

```console
$ journalctl -b -f -u release-image.service -u bootkube.service
# This will provide the logs of bootkube.service after logging into bootstrap node
```

# Anything else we need to know?

We triggered this IPI installation for s390x arch base VSI cloud machines on IBM cloud

# References

Nil

**Comment by r4f4** [comment]
This error
```
Oct 11 15:17:44 phani-s390x-oct11-xp2kn-bootstrap bootkube.sh[134354]: Rendering MCO manifests...
Oct 11 15:17:45 phani-s390x-oct11-xp2kn-bootstrap bootkube.sh[135750]: Error: unknown flag: --image-references
Oct 11 15:17:45 phani-s390x-oct11-xp2kn-bootstrap systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
```
is happening because you're using a release image that's too old for the installer version. The `--image-references` was introduced in `4.12.0-ec.2`.

**Comment by Phaneendra-Ravuri** [comment]
okay thanks @r4f4 for your input. I will pick the ec.2 patch version and will trigger the install.

**Comment by Phaneendra-Ravuri** [comment]
I am closing this issue as the image I took was incorrect for the flag , Thanks @r4f4
