### ISSUE TITLE
Increase certificate validity

### ISSUE THREAD

**Issue by vrutkovs** [openshift/installer#650]
https://github.com/openshift/installer/blob/44b2220414ddf357256fe17e469c44603d7852c4/pkg/asset/tls/tls.go#L29

Cert validity is hardcoded to 30 mins. In most BYOR cases this is insufficient, as bootstrap and masters need to be prepared first (setup CRIO, pull images etc.) and by the time kubelets issue CSR the cert might expire.

As a temporary measure it would be nice to have this period extended to an hour, but ideally this should be configurable

**Comment by wking** [comment]
> As a temporary measure it would be nice to have this period extended to an hour, but ideally this should be configurable

I'm fine bumping this to an hour, but I'd rather not make it configurable.  Folks who need to override the default should be able to adjust by clobbering the cert (or any TLS assets they like) in the asset directory during a [multi-step install][1].  I dunno if that works at the moment, but it will with #556 or similar.

[1]: https://github.com/openshift/installer/blob/fc8e1ec41927fdfe0a1878aa3bb41e916ceda0b1/docs/user/overview.md#multiple-invocations

**Comment by wking** [comment]
Cross linking #167.  This issue is about making expiration less likely.  #167 issue is about handling expiration when it happens.

**Comment by vrutkovs** [comment]
>adjust by clobbering the cert (or any TLS assets they like) in the asset directory

So that'd require some sort of 'regen certs' util?

**Comment by vrutkovs** [comment]
It seems a proper rotation (if #167 is about that) would fix that, without adjustments to the validity time. Feel free to close this issue if that's the case
