### ISSUE TITLE
panic pkg/asset/machines/master.go:53 on master

### ISSUE THREAD

**Issue by wongma7** [openshift/installer#672]
# Version

```console
$ openshift-install version
bin/openshift-install v0.3.0-210-gf3c63c4a242ff1513a6e11f6c5e5fe4c304162a3
Terraform v0.11.10
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

panic

$ bin/openshift-install create cluster --log-level=debug
DEBUG Fetching "Terraform Variables"...            
DEBUG Fetching dependencies of "Terraform Variables"... 
DEBUG   Fetching "Install Config"...               
DEBUG   Fetching dependencies of "Install Config"... 
DEBUG     Fetching "Cluster ID"...                 
DEBUG     Found "Cluster ID" in state file         
DEBUG     Loading "Cluster ID" from state file     
DEBUG     Fetching "Email Address"...              
DEBUG     Found "Email Address" in state file      
DEBUG     Loading "Email Address" from state file  
DEBUG     Fetching "Password"...                   
DEBUG     Found "Password" in state file           
DEBUG     Loading "Password" from state file       
DEBUG     Fetching "SSH Key"...                    
DEBUG     Found "SSH Key" in state file            
DEBUG     Loading "SSH Key" from state file        
DEBUG     Fetching "Base Domain"...                
DEBUG     Found "Base Domain" in state file        
DEBUG     Loading "Base Domain" from state file    
DEBUG     Fetching "Cluster Name"...               
DEBUG     Found "Cluster Name" in state file       
DEBUG     Loading "Cluster Name" from state file   
DEBUG     Fetching "Pull Secret"...                
DEBUG     Found "Pull Secret" in state file        
DEBUG     Loading "Pull Secret" from state file    
DEBUG     Fetching "Platform"...                   
DEBUG     Found "Platform" in state file           
DEBUG     Loading "Platform" from state file       
DEBUG   Found "Install Config" in state file       
DEBUG   Loading "Install Config" from state file   
DEBUG   Fetching "Bootstrap Ignition Config"...    
DEBUG   Fetching dependencies of "Bootstrap Ignition Config"... 
DEBUG     Fetching "Install Config"...             
DEBUG     Reusing previously-fetched "Install Config" 
DEBUG     Fetching "Root CA"...                    
DEBUG     Found "Root CA" in state file            
DEBUG     Loading "Root CA" from state file        
DEBUG     Fetching "Certificate (etcd)"...         
DEBUG     Fetching dependencies of "Certificate (etcd)"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG     Found "Certificate (etcd)" in state file 
DEBUG     Loading "Certificate (etcd)" from state file 
DEBUG     Fetching "Certificate (kube-ca)"...      
DEBUG     Fetching dependencies of "Certificate (kube-ca)"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG     Found "Certificate (kube-ca)" in state file 
DEBUG     Loading "Certificate (kube-ca)" from state file 
DEBUG     Fetching "Certificate (aggregator)"...   
DEBUG     Fetching dependencies of "Certificate (aggregator)"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG     Found "Certificate (aggregator)" in state file 
DEBUG     Loading "Certificate (aggregator)" from state file 
DEBUG     Fetching "Certificate (service-serving)"... 
DEBUG     Fetching dependencies of "Certificate (service-serving)"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG     Found "Certificate (service-serving)" in state file 
DEBUG     Loading "Certificate (service-serving)" from state file 
DEBUG     Fetching "Certificate (etcd)"...         
DEBUG     Fetching dependencies of "Certificate (etcd)"... 
DEBUG       Fetching "Certificate (etcd)"...       
DEBUG       Reusing previously-fetched "Certificate (etcd)" 
DEBUG     Found "Certificate (etcd)" in state file 
DEBUG     Loading "Certificate (etcd)" from state file 
DEBUG     Fetching "Certificate (kube-apiaserver)"... 
DEBUG     Fetching dependencies of "Certificate (kube-apiaserver)"... 
DEBUG       Fetching "Certificate (kube-ca)"...    
DEBUG       Reusing previously-fetched "Certificate (kube-ca)" 
DEBUG       Fetching "Install Config"...           
DEBUG       Reusing previously-fetched "Install Config" 
DEBUG     Found "Certificate (kube-apiaserver)" in state file 
DEBUG     Loading "Certificate (kube-apiaserver)" from state file 
DEBUG     Fetching "Certificate (kube-apiserver-proxy)"... 
DEBUG     Fetching dependencies of "Certificate (kube-apiserver-proxy)"... 
DEBUG       Fetching "Certificate (aggregator)"... 
DEBUG       Reusing previously-fetched "Certificate (aggregator)" 
DEBUG     Found "Certificate (kube-apiserver-proxy)" in state file 
DEBUG     Loading "Certificate (kube-apiserver-proxy)" from state file 
DEBUG     Fetching "Certificate (system:admin)"... 
DEBUG     Fetching dependencies of "Certificate (system:admin)"... 
DEBUG       Fetching "Certificate (kube-ca)"...    
DEBUG       Reusing previously-fetched "Certificate (kube-ca)" 
DEBUG     Found "Certificate (system:admin)" in state file 
DEBUG     Loading "Certificate (system:admin)" from state file 
DEBUG     Fetching "Certificate (system:serviceaccount:kube-system:default)"... 
DEBUG     Fetching dependencies of "Certificate (system:serviceaccount:kube-system:default)"... 
DEBUG       Fetching "Certificate (kube-ca)"...    
DEBUG       Reusing previously-fetched "Certificate (kube-ca)" 
DEBUG     Found "Certificate (system:serviceaccount:kube-system:default)" in state file 
DEBUG     Loading "Certificate (system:serviceaccount:kube-system:default)" from state file 
DEBUG     Fetching "Certificate (mcs)"...          
DEBUG     Fetching dependencies of "Certificate (mcs)"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG       Fetching "Install Config"...           
DEBUG       Reusing previously-fetched "Install Config" 
DEBUG     Found "Certificate (mcs)" in state file  
DEBUG     Loading "Certificate (mcs)" from state file 
DEBUG     Fetching "Key Pair (service-account.pub)"... 
DEBUG     Found "Key Pair (service-account.pub)" in state file 
DEBUG     Loading "Key Pair (service-account.pub)" from state file 
DEBUG     Fetching "Kubeconfig Admin"...           
DEBUG     Fetching dependencies of "Kubeconfig Admin"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG       Fetching "Certificate (system:admin)"... 
DEBUG       Reusing previously-fetched "Certificate (system:admin)" 
DEBUG       Fetching "Install Config"...           
DEBUG       Reusing previously-fetched "Install Config" 
DEBUG     Found "Kubeconfig Admin" in state file   
INFO Consuming "Kubeconfig Admin" from target directory 
DEBUG     Loading "Kubeconfig Admin" from both state file and target directory 
DEBUG     Fetching "Kubeconfig Kubelet"...         
DEBUG     Fetching dependencies of "Kubeconfig Kubelet"... 
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG       Fetching "Certificate (system:serviceaccount:kube-system:default)"... 
DEBUG       Reusing previously-fetched "Certificate (system:serviceaccount:kube-system:default)" 
DEBUG       Fetching "Install Config"...           
DEBUG       Reusing previously-fetched "Install Config" 
DEBUG     Found "Kubeconfig Kubelet" in state file 
DEBUG     Loading "Kubeconfig Kubelet" from state file 
DEBUG     Fetching "Common Manifests"...           
DEBUG     Fetching dependencies of "Common Manifests"... 
DEBUG       Fetching "Install Config"...           
DEBUG       Reusing previously-fetched "Install Config" 
DEBUG       Fetching "Network Config"...           
DEBUG       Fetching dependencies of "Network Config"... 
DEBUG         Fetching "Install Config"...         
DEBUG         Reusing previously-fetched "Install Config" 
DEBUG       Generating "Network Config"...         
DEBUG       Fetching "Root CA"...                  
DEBUG       Reusing previously-fetched "Root CA"   
DEBUG       Fetching "Certificate (etcd)"...       
DEBUG       Reusing previously-fetched "Certificate (etcd)" 
DEBUG       Fetching "Certificate (ingress)"...    
DEBUG       Fetching dependencies of "Certificate (ingress)"... 
DEBUG         Fetching "Certificate (kube-ca)"...  
DEBUG         Reusing previously-fetched "Certificate (kube-ca)" 
DEBUG         Fetching "Install Config"...         
DEBUG         Reusing previously-fetched "Install Config" 
DEBUG       Found "Certificate (ingress)" in state file 
DEBUG       Loading "Certificate (ingress)" from state file 
DEBUG       Fetching "Certificate (kube-ca)"...    
DEBUG       Reusing previously-fetched "Certificate (kube-ca)" 
DEBUG       Fetching "Certificate (service-serving)"... 
DEBUG       Reusing previously-fetched "Certificate (service-serving)" 
DEBUG       Fetching "Certificate (etcd)"...       
DEBUG       Reusing previously-fetched "Certificate (etcd)" 
DEBUG       Fetching "Certificate (mcs)"...        
DEBUG       Reusing previously-fetched "Certificate (mcs)" 
DEBUG       Fetching "Certificate (system:serviceaccount:kube-system:default)"... 
DEBUG       Reusing previously-fetched "Certificate (system:serviceaccount:kube-system:default)" 
DEBUG       Fetching "KubeCloudConfig"...          
DEBUG       Generating "KubeCloudConfig"...        
DEBUG       Fetching "MachineConfigServerTLSSecret"... 
DEBUG       Generating "MachineConfigServerTLSSecret"... 
DEBUG       Fetching "OpenshiftServiceCertSignerSecret"... 
DEBUG       Generating "OpenshiftServiceCertSignerSecret"... 
DEBUG       Fetching "Pull"...                     
DEBUG       Generating "Pull"...                   
DEBUG       Fetching "CVOOverrides"...             
DEBUG       Generating "CVOOverrides"...           
DEBUG       Fetching "LegacyCVOOverrides"...       
DEBUG       Generating "LegacyCVOOverrides"...     
DEBUG       Fetching "EtcdServiceEndpointsKubeSystem"... 
DEBUG       Generating "EtcdServiceEndpointsKubeSystem"... 
DEBUG       Fetching "KubeSystemConfigmapEtcdServingCA"... 
DEBUG       Generating "KubeSystemConfigmapEtcdServingCA"... 
DEBUG       Fetching "KubeSystemConfigmapRootCA"... 
DEBUG       Generating "KubeSystemConfigmapRootCA"... 
DEBUG       Fetching "KubeSystemSecretEtcdClient"... 
DEBUG       Generating "KubeSystemSecretEtcdClient"... 
DEBUG       Fetching "TectonicNamespace"...        
DEBUG       Generating "TectonicNamespace"...      
DEBUG       Fetching "OpenshiftWebConsoleNamespace"... 
DEBUG       Generating "OpenshiftWebConsoleNamespace"... 
DEBUG       Fetching "OpenshiftMachineConfigOperator"... 
DEBUG       Generating "OpenshiftMachineConfigOperator"... 
DEBUG       Fetching "OpenshiftClusterAPINamespace"... 
DEBUG       Generating "OpenshiftClusterAPINamespace"... 
DEBUG       Fetching "OpenshiftServiceCertSignerNamespace"... 
DEBUG       Generating "OpenshiftServiceCertSignerNamespace"... 
DEBUG       Fetching "AppVersionKind"...           
DEBUG       Generating "AppVersionKind"...         
DEBUG       Fetching "EtcdServiceKubeSystem"...    
DEBUG       Generating "EtcdServiceKubeSystem"...  
DEBUG     Found "Common Manifests" in state file   
DEBUG     Loading "Common Manifests" from state file 
DEBUG     Fetching "Tectonic Manifests"...         
DEBUG     Fetching dependencies of "Tectonic Manifests"... 
DEBUG       Fetching "Install Config"...           
DEBUG       Reusing previously-fetched "Install Config" 
DEBUG       Fetching "Certificate (ingress)"...    
DEBUG       Reusing previously-fetched "Certificate (ingress)" 
DEBUG       Fetching "Certificate (kube-ca)"...    
DEBUG       Reusing previously-fetched "Certificate (kube-ca)" 
DEBUG       Fetching "Cluster.cluster.k8s.io/v1alpha1"... 
DEBUG       Fetching dependencies of "Cluster.cluster.k8s.io/v1alpha1"... 
DEBUG         Fetching "Install Config"...         
DEBUG         Reusing previously-fetched "Install Config" 
DEBUG         Fetching "Network Config"...         
DEBUG         Reusing previously-fetched "Network Config" 
DEBUG       Generating "Cluster.cluster.k8s.io/v1alpha1"... 
DEBUG       Fetching "Worker Machines"...          
DEBUG       Fetching dependencies of "Worker Machines"... 
DEBUG         Fetching "Install Config"...         
DEBUG         Reusing previously-fetched "Install Config" 
DEBUG         Fetching "Worker Ignition Config"... 
DEBUG         Fetching dependencies of "Worker Ignition Config"... 
DEBUG           Fetching "Install Config"...       
DEBUG           Reusing previously-fetched "Install Config" 
DEBUG           Fetching "Root CA"...              
DEBUG           Reusing previously-fetched "Root CA" 
DEBUG         Found "Worker Ignition Config" in state file 
DEBUG         Loading "Worker Ignition Config" from state file 
DEBUG       Generating "Worker Machines"...        
DEBUG       Fetching "Master Machines"...          
DEBUG       Fetching dependencies of "Master Machines"... 
DEBUG         Fetching "Install Config"...         
DEBUG         Reusing previously-fetched "Install Config" 
DEBUG         Fetching "Master Ignition Config"... 
DEBUG         Fetching dependencies of "Master Ignition Config"... 
DEBUG           Fetching "Install Config"...       
DEBUG           Reusing previously-fetched "Install Config" 
DEBUG           Fetching "Root CA"...              
DEBUG           Reusing previously-fetched "Root CA" 
DEBUG         Found "Master Ignition Config" in state file 
DEBUG         Loading "Master Ignition Config" from state file 
DEBUG       Generating "Master Machines"...        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11fdfd3]

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/machines.(*Master).Generate(0xc0000af020, 0xc000454c60, 0x0, 0x0)
	/home/mawong/go/src/github.com/openshift/installer/pkg/asset/machines/master.go:53 +0x173
github.com/openshift/installer/pkg/asset.(*StoreImpl).fetch(0xc0003528c0, 0x1a66620, 0xc0000af020, 0xc0000b7f20, 0x6, 0xc0000b7f20, 0x6, 0x0)
	/home/mawong/go/src/github.com/openshift/installer/pkg/asset/store.go:223 +0x909
github.com/openshift/installer/pkg/asset.(*StoreImpl).fetch(0xc0003528c0, 0x1a66760, 0xc000459ac0, 0xc000462348, 0x4, 0xc000462348, 0x4, 0x0)
	/home/mawong/go/src/github.com/openshift/installer/pkg/asset/store.go:187 +0x695
github.com/openshift/installer/pkg/asset.(*StoreImpl).fetch(0xc0003528c0, 0x1a662a0, 0xc000450340, 0x187e524, 0x2, 0x187e524, 0x2, 0x0)
	/home/mawong/go/src/github.com/openshift/installer/pkg/asset/store.go:187 +0x695
github.com/openshift/installer/pkg/asset.(*StoreImpl).fetch(0xc0003528c0, 0x1a66260, 0x2a7f480, 0x0, 0x0, 0xc00002db28, 0x409a38, 0x1696680)
	/home/mawong/go/src/github.com/openshift/installer/pkg/asset/store.go:187 +0x695
github.com/openshift/installer/pkg/asset.(*StoreImpl).Fetch(0xc0003528c0, 0x1a66260, 0x2a7f480, 0x1a66260, 0x2a7f480)
	/home/mawong/go/src/github.com/openshift/installer/pkg/asset/store.go:63 +0x4b
main.runTargetCmd.func1(0x2a78160, 0xc0000a8860, 0x0, 0x1, 0x0, 0x0)
	/home/mawong/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:142 +0x127
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0x2a78160, 0xc0000a8590, 0x1, 0x1, 0x2a78160, 0xc0000a8590)
	/home/mawong/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00011c780, 0x10, 0x0, 0xc000139680)
	/home/mawong/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00011c780, 0xc00002df48, 0x1)
	/home/mawong/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/mawong/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:33 +0x285

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by wongma7** [comment]
I had a bunch of files left over from a previous install.

deleted them all, not sure which one caused the panic, anyway now I'm getting a different error.

**Comment by staebler** [comment]
Looking...

**Comment by staebler** [comment]
My educated guess is that @wongma7 had a state file that was created prior to the change in https://github.com/openshift/installer/commit/4fbf790d858a03d25c909e3b68aef3b848b6f4e8#diff-fe47c17da610d46d9bf4d6a1cfba8bcc. That commit changed the fields of the master ignition config asset from `Configs` and `FileList` to `Config` and `File`. Unmarshaling the state file didn't fill in any of the fields of the master ignition config asset.

We should add some verification to each asset that the data from the state file makes the asset viable. Or add some versioning on the state file.

**Comment by wking** [comment]
+1 to versioning the state file.

**Comment by crawford** [comment]
@staebler has this been addressed with your validation changes?
