### ISSUE TITLE
The name "count" is reserved for use in a future version of Terraform in vSphere UPI terraform scripts

### ISSUE THREAD

**Issue by petr-balogh** [openshift/installer#6762]
# Version

```console
$ openshift-install version
4.13

Terraform version: 0.12.26
```

# Platform:
vSphere

UPI using terraform scripts from this repo

# What happened?
When running terraform UPI vSphere scritps

It started failing with:
```
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: /home/jenkins/bin/terraform apply   '-var-file=/home/jenkins/current-cluster-dir/openshift-cluster-dir/terraform_data/terraform.tfvars' -auto-approve  '/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/external/installer/upi/vsphere/'.
2023-01-11 13:41:05  E               Error is 
2023-01-11 13:41:05  E               Error: Reserved argument name in module block
2023-01-11 13:41:05  E               
2023-01-11 13:41:05  E                 on ../../../workspace/qe-deploy-ocs-cluster-prod/ocs-ci/external/installer/upi/vsphere/[main.tf](http://main.tf/) line 211, in module "control_plane_vm":
2023-01-11 13:41:05  E                211:   count = length(module.control_plane_a_records.fqdns)
2023-01-11 13:41:05  E               
2023-01-11 13:41:05  E               The name "count" is reserved for use in a future version of Terraform.
```

# What you expected to happen?

Do not fail with this error.

I noticed that those change with defining `count` vars is new in 4.13 release branch:
https://github.com/openshift/installer/blob/release-4.13/upi/vsphere/main.tf#L33

And is not in 4.12 release branch.

As it complains about `The name "count" is reserved for use in a future version of Terraform.` we should follow this terraform convention here and do not name variable with reserved name I think.

# How to reproduce it (as minimally and precisely as possible)?

Run the terraform script with 0.12.26 terraform version.

```console
terraform apply   '-var-file=/home/jenkins/current-cluster-dir/openshift-cluster-dir/terraform_data/terraform.tfvars' -auto-approve  /installer/upi/vsphere
```

**Comment by petr-balogh** [comment]
I looked that someone had similar issue in different project and they fixed with renaming variables here:
https://github.com/hobby-kube/provisioning/pull/48

I actually like how they are defining required version of terraform here:
https://github.com/hobby-kube/provisioning/pull/48/files#diff-dfd5848fa77a04d0343891fe859286cc210473d10f0e62c7f99f0d5ecf1a9927R2-R4

Maybe if some minimum version of terraform is required, will be good if we will add this to this repo as well. WDYT?

**Comment by rvanderp3** [comment]
@petr-balogh thanks for raising this issue.  This update was made to facilitate multi-zone UPI installations in CI.   The use of the variable name `count` is intentional as an array is being built containing the those resources and `count` is used to iterate over the resources.  Efforts were made to ensure the UPI terraform would support traditional single zone and multi-zone installations.  In CI, [terraform version 1.0.11](https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L65) is used.  I'm in agreement that we should update the UPI README with additional details regarding the minimum terraform version.
