### ISSUE TITLE
ROADMAP / future features / comparison to kubeadm / bare metal

### ISSUE THREAD

**Issue by cdrage** [openshift/installer#679]
So I came across this project because of my difficulty of using the Ansible playbooks with OpenShift.

First off, this is *amazing*.

Few questions:

- Is there a ROADMAP / public doc on goals / future features
- I see that there are implementations for Libvirt / AWS / OpenStack, however, are there any plans for bare-metal support (on generally most OS') similar to how `kubeadm` has `init` and `join` that works on CentOS, Ubuntu, Debian, etc?
- Is there planned support for Fedora CoreOS (when it's out)

**Comment by crawford** [comment]
We don't have a public roadmap, no. Once the initial version is released, we may revisit that stance. For now, we are focused on getting this working well with AWS.

**Comment by wking** [comment]
> ... are there any plans for bare-metal support (on generally most OS')...

The folks working on [OpenShift Hive][1] and [OpenShift Ansible][2] are working on launching clusters on bare-metal (among other things).  I'm not sure where they are on the doc front, but you may be able to ask over there for some pointers.

[1]: https://github.com/openshift/hive
[2]: https://github.com/openshift/openshift-ansible

**Comment by uocxp** [comment]
i am also interested since we are using now okd 3.9 on bare-metal servers on centos and we are willing to upgrade to 4.0 as soon as possible

**Comment by DanyC97** [comment]
@uocxp in various public presentations/ talks was mentioned that soon after 4.1 (which will be out close after 4.0) there will be more info shared around the BM/ migration story.

So my suggestion would be to hold it for a bit (if you can), at least that is what i'm doing anyway ;) and in meantime stressing 4.0 in AWS ;)

**Comment by uocxp** [comment]
when will be OKD 4.0  actually released ? In the past days (3.x) there was a release every 3 months but since 3.11 release on Oct there has been no new releases. I didn't find any roadmap for releasing 4.0

**Comment by DanyC97** [comment]
@uocxp i guess is fair to say that getting 4.x out is a total different game (so many changes at all levels) vs releasing a new 3.x

only judging by the commits and the changes i'd take a wild guess that things are getting closer, just keep your eyes open is all i can say ;) ( i guess everyone is eager to see 4.0 taking off).

> there was a release every 3 months but since 3.11 release on Oct there has been no new releases

i think is fair to compare the release cycle time once 4.0 is out with next 4.x release rather than v3.11 vs v4.0

**Comment by sdodson** [comment]
OKD working group is driven through https://github.com/openshift/community
/close
