### ISSUE TITLE
Bootstrap nodes should not be deleted after successful installation rather it can act as a management node.

### ISSUE THREAD

**Issue by mansura-habiba** [openshift/installer#6877]
# Version

Any version

# Platform:
AWS custom instalaltion

# What happened?

After a successful installation the bootstrap node get deleted. However, it remain available it become easier to manage the OCP cluster in future

# What you expected to happen?

After a successful installation the bootstrap node remain un-deleted and connected to other master node and worker node. So we can use bootstrap node to access other ec2 instance for management purpose. 

# How to reproduce it (as minimally and precisely as possible)?

Once a successful installation is finished

**Comment by rahulbansod519** [comment]
Yes, you are correct. Bootstrap nodes should not be deleted after successful installation. They can act as a management node and provide centralized management and control for the entire cluster.
