### ISSUE TITLE
Not permitted to install on AWS

### ISSUE THREAD

**Issue by jcantrill** [openshift/installer#696]
Following the prompts but dont see any specific documentation to advise what I need in order to have the right permissions.
# Version

```$ ./bin/openshift-install version
./bin/openshift-install v0.3.0-228-g31567af33f8e8500f54dc4f5867598b9f1da68dd
Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html
```

# Platform (aws|libvirt|openstack):
aws

```
INFO Using Terraform to create cluster...         
ERROR Error: Error applying plan:

15 error(s) occurred:

* module.vpc.aws_lb.api_external: 1 error(s) occurred:

* aws_lb.api_external: Error creating Application Load Balancer: DuplicateLoadBalancerName: A load balancer with the same name 'jcantril-ext' exists, but with different settings
	status code: 400, request id: d08a39bd-e9d7-11e8-8d85-5f706ad9220e
* module.iam.aws_iam_role.worker_role: 1 error(s) occurred:

* aws_iam_role.worker_role: Error creating IAM Role jcantril-worker-role: AccessDenied: User: arn:aws:iam::531415883065:user/jcantril is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::531415883065:role/jcantril-worker-role
	status code: 403, request id: bafea11b-e9d7-11e8-840d-3599d79a57bd
* module.vpc.aws_lb.api_internal: 1 error(s) occurred:

* aws_lb.api_internal: Error creating Application Load Balancer: DuplicateLoadBalancerName: A load balancer with the same name 'jcantril-int' exists, but with different settings
	status code: 400, request id: d0ba4970-e9d7-11e8-941b-1310329ac071
* module.vpc.aws_eip.nat_eip[2]: 1 error(s) occurred:

* aws_eip.nat_eip.2: Error creating EIP: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 69b1998c-f390-49f2-8ca1-d913e891cac6
* module.vpc.aws_lb_target_group.services: 1 error(s) occurred:

* aws_lb_target_group.services: Error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'jcantril-services' exists, but with different settings
	status code: 400, request id: bd7c7270-e9d7-11e8-beea-a1040e8be696
* module.vpc.aws_lb_target_group.api_external: 1 error(s) occurred:

* aws_lb_target_group.api_external: Error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'jcantril-api-ext' exists, but with different settings
	status code: 400, request id: bd7b8836-e9d7-11e8-b77f-a5ae92ee3915
* module.vpc.aws_eip.nat_eip[5]: 1 error(s) occurred:

* aws_eip.nat_eip.5: Error creating EIP: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: a27f80b2-a4e0-47ff-b2d5-13f5ce9a9de2
* module.vpc.aws_lb_target_group.api_internal: 1 error(s) occurred:

* aws_lb_target_group.api_internal: Error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'jcantril-api-int' exists, but with different settings
	status code: 400, request id: bd7c729d-e9d7-11e8-9c04-9f331b3b2a3b
* module.vpc.aws_eip.nat_eip[3]: 1 error(s) occurred:

* aws_eip.nat_eip.3: Error creating EIP: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: fbea0c98-20d0-4e75-a8fd-a08baa314e32
* module.vpc.aws_eip.nat_eip[0]: 1 error(s) occurred:

* aws_eip.nat_eip.0: Error creating EIP: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 599ce5b7-86d6-4868-8f30-05086eb9ba08
* module.vpc.aws_eip.nat_eip[4]: 1 error(s) occurred:

* aws_eip.nat_eip.4: Error creating EIP: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 7d88879c-0f95-4a29-8251-fddf0d492b76
* module.bootstrap.aws_s3_bucket.ignition: 1 error(s) occurred:

* aws_s3_bucket.ignition: Error creating S3 bucket: AccessDenied: Access Denied
	status code: 403, request id: 58E522CBFF923890, host id: ysEIuGS338j+QnQP5g3LyFDsmAKgAo57o/MTbLFG6Lt6Gl3I4BwJOUEXVDhzDeZUe7VomOArYe0=
* module.bootstrap.aws_iam_role.bootstrap: 1 error(s) occurred:

* aws_iam_role.bootstrap: Error creating IAM Role jcantril-bootstrap-role: AccessDenied: User: arn:aws:iam::531415883065:user/jcantril is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::531415883065:role/jcantril-bootstrap-role
	status code: 403, request id: bafea149-e9d7-11e8-98d4-474864fbea3d
* module.masters.aws_iam_role.master_role: 1 error(s) occurred:

* aws_iam_role.master_role: Error creating IAM Role jcantril-master-role: AccessDenied: User: arn:aws:iam::531415883065:user/jcantril is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::531415883065:role/jcantril-master-role
	status code: 403, request id: bafea156-e9d7-11e8-8700-7f377c0f7a24
* module.vpc.aws_eip.nat_eip[1]: 1 error(s) occurred:

* aws_eip.nat_eip.1: Error creating EIP: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: c7ce0762-2c70-4ead-be20-0ded090753db
```
# What happened?
 Permissions error trying to deploy to aws

# What you expected to happen?
running cluster on aws

# How to reproduce it (as minimally and precisely as possible)?

```
$ ./bin/openshift-install create cluster --dir ~/tmp/cluster
```

**Comment by abhinavdahiya** [comment]
> Following the prompts but dont see any specific documentation to advise what I need in order to have the right permissions.

What kind of documentation are you expecting. Every org/team does the permission handling differently.

/cc @wking @crawford

**Comment by jcantrill** [comment]
> > Following the prompts but dont see any specific documentation to advise what I need in order to have the right permissions.
> 
> What kind of documentation are you expecting. Every org/team does the permission handling differently.
> 
> /cc @wking @crawford

Ref: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md

**Comment by abhinavdahiya** [comment]
> > > Following the prompts but dont see any specific documentation to advise what I need in order to have the right permissions.
> > 
> > 
> > What kind of documentation are you expecting. Every org/team does the permission handling differently.
> > /cc @wking @crawford
> 
> Ref: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md

A little more detail would be appreciated. I am not sure how that doc ties into this conversation.

**Comment by jcantrill** [comment]
> > Ref: https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md
> 
> A little more detail would be appreciated. I am not sure how that doc ties into this conversation.

There is an explicit document that defines the prereqs for libvirt but nothing with regards to the other providers.  I find the prompts lacking and a document expanding on some of the nuances of installing to AWS would be useful

**Comment by wking** [comment]
> I find the prompts lacking...

Did you `?` to get more info on the prompts?  Which were lacking?  What would you like to see in addition to what we already show?

**Comment by wking** [comment]
Also, #444 is in flight to pre-check your user's permissions so we can fail earlier with a more concise error.

**Comment by wking** [comment]
> There is an explicit document that defines the prereqs for libvirt but nothing with regards to the other providers.

The doc for other providers is [here][1].  If we need additional information for something else, I'd rather put it in the prompt system (where all users will have it available) instead of separate docs (which may or may not get read).  It would be good to have separate docs for admins setting up accounts and such, who are focused on enabling others to launch clusters, but for folks launching clusters, it would be nice if the installer binary was all you needed.

[1]: https://github.com/openshift/installer/#quick-start

**Comment by jcantrill** [comment]
I did use the prompts but I think back to previous releases, for development clusters in particular, where we had a document that advised all the prereqs in order to even to begin to get an AWS cluster.  Maybe #444 resolves the issue.

**Comment by dak1n1** [comment]
Yeah, #444 will give you exactly the IAM policy names that need to be applied to your user in order to run the installer. It looks at what you currently have and helps you fill in the gaps.
