### ISSUE TITLE
error while deploying openshift on azure

### ISSUE THREAD

**Issue by Mahdiidriss** [openshift/installer#6964]
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.ocp-me-cluster.mednszone.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp: lookup api.ocp-me-cluster.dnszone.com on 192.168.......:53: no such host

ERROR Bootstrap failed to complete: Get "https://api.ocp-me-cluster.mednszone.com:6443/version": dial tcp: lookup api.ocp-mahdi-cluster.mednszone.com on 192.168.......:53: no such host

ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.

**knowing that all al master and worker nodes were provisioned on azure portal.**

**Comment by tanaybaswa** [comment]
Have the same issue.
