### ISSUE TITLE
Error running an IBM Cloud IPI installation - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cambelem** [openshift/installer#7224]
# Version

```console
$ openshift-install version
./openshift-install 4.12.14
built from commit 4e5513ad5a5887a8036ba74ca48b1fa4eafe76cc
release image quay.io/openshift-release-dev/ocp-release@sha256:157cc02d63bfe67988429fd803da632e495e230d811759b1aed1e6ffa7a3f31a
release architecture amd64
```

# Platform: ibmcloud
* IPI with openshift-install

# What happened?

Running `openshift-install create cluster --dir install_dir --log-level=DEBUG` leads to the following error:
```
DEBUG   Fetching Common Manifests...               
DEBUG   Reusing previously-fetched Common Manifests 
DEBUG Generating Terraform Variables...            
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2bdb706]

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/installconfig/ibmcloud.(*Metadata).IsVPCPermittedNetwork(0xc000e89b80, {0x1a8b9918, 0xc00007c088}, {0xc0009d8678, 0x8})
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/ibmcloud/metadata.go:175 +0x186
github.com/openshift/installer/pkg/asset/cluster.(*TerraformVariables).Generate(0x1dc55040, 0x5?)
	/go/src/github.com/openshift/installer/pkg/asset/cluster/tfvars.go:606 +0x3a5a
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc000ca0d80, {0x1a8ab280, 0x1dc55040}, {0x0, 0x0})
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:227 +0x5fa
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0x7ffd948754cc?, {0x1a8ab280, 0x1dc55040}, {0x1dc32840, 0x8, 0x8})
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:77 +0x48
main.runTargetCmd.func1({0x7ffd948754cc, 0xb})
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:261 +0x125
main.runTargetCmd.func2(0x1dc38800?, {0xc000ca0a80?, 0x3?, 0x3?})
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:291 +0xe7
github.com/spf13/cobra.(*Command).execute(0x1dc38800, {0xc000ca0a20, 0x3, 0x3})
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bc8000)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:918
main.installerMain()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:61 +0x2b0
main.main()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:38 +0xff
```

# What you expected to happen?

The installation should continue through to create the underlying resources. 

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create cluster --dir install_dir --log-level=DEBUG
```

# Anything else we need to know?
This was working on May 14, 2023. The cluster was destroyed a week later using `openshift-install destroy cluster --dir install_dir` however the underlying VPC infrastructure did not change. The install-config.yaml did not change either.

I have tried the 4.13 openshift-install and added the field: `networkResourceGroupName` to the install-config.yaml but this leads to the exact same segmentation fault. This also has been tested on another VPC as well.

**Comment by cambelem** [comment]
@cjschaef, thanks for the reply.

I am using 4.12.14 and 4.12.19 with both running into the same errors. I'm fairly sure it's a problem with the API calls as the Dallas and Washington region (`us-east`, `us-south`) are causing the error mentioned above while Toronto (`ca-tor`) and Frankfort (`eu-de`) works without an issue. 

The automation I've created sets up a VPC, DNS service (global), and a bastion VSI in its respective region/zone which is later linked to the install-config.yaml's configuration as seen below. 
```
...
platform:
  ibmcloud:
    region: eu-de
    resourceGroupName: ibm-rg
    networkResourceGroupName: ibm-rg
    vpcName: ibm-vpc
    controlPlaneSubnets:
      - ibm-subnet-0
      - ibm-subnet-1
      - ibm-subnet-2
    computeSubnets:
      - ibm-subnet-0
      - ibm-subnet-1
      - ibm-subnet-2
...
```

Each run whether successful or unsuccessful has its resources removed and reran in a new region. Every other variables staying the same between each run. As mentioned above, there are no problems running in `ca-tor` and `eu-de`.

**Comment by cjschaef** [comment]
@cambelem Thanks for the additional details. I'll take a look to see what I can find out.

**Comment by cjschaef** [comment]
I duplicated the issue in `us-east` using OCP 4.12.19.
Now I will try to see what the underlying issue is.

**Comment by cjschaef** [comment]
I have opened a Jira for this issue to be worked and eventually backported to 4.13 and 4.12
https://issues.redhat.com/browse/OCPBUGS-14963

**Comment by cambelem** [comment]
Awesome, thanks for looking into this and finding the problem!

**Comment by sean-freeman** [comment]
Error exists in installer versions `4.12.6`, `4.12.12`, `4.12.22`, `4.13.0` and `4.13.3` for the `us-south` Region
