### ISSUE TITLE
AWS: override AMI

### ISSUE THREAD

**Issue by vrutkovs** [openshift/installer#728]
# Platform aws

Add an option to override AMI. This would be extremely helpful for BYOR:

* infra could be provisioned by openshift-installer
* openshift-ansible would use dynamic inventory to find created instances
* openshift-ansible would apply Ignition/MCD configs and complete the install

This way openshift-ansible repo won't have to replicate installer changes using Ansible tasks

**Comment by wking** [comment]
> Add an option to override AMI.

You can do this by setting [`amiID`][1] in your install-config during [a multi-step install][2].

[1]: https://github.com/openshift/installer/blob/v0.4.0/pkg/types/aws/machinepool.go#L9-L10
[2]: https://github.com/openshift/installer/blob/v0.4.0/docs/user/overview.md#multiple-invocations

**Comment by vrutkovs** [comment]
Ah, I see, so setting:
```
- name: master
  platform: {}
  replicas: 3
  amiID: ami-deadbeef
```
would fix that.

I ran `install cluster-config`, updated both `install-config.yml` and `.openshift_install_state.json` then `install ignition-configs` and then `create cluster`, but it seem to have applied to workers only:

I see `KubeSysConfig` got updated in `.openshift_install_state.json`:
```
....
    "*manifests.Manifests": {
        "KubeSysConfig": {
            "kind": "ConfigMap",
            "apiVersion": "v1",
            "metadata": {
                "name": "cluster-config-v1",
                "namespace": "kube-system"
            },
            "data": {
                "install-config": "....machines:\n- name: master\n  platform: {}\n  replicas: 3\n  amiID: \"ami-9887c6e7\"\n- name: worker\n  platform: {}\n  replicas: 3\n  amiID: \"ami-9887c6e7\"\n..."
```
but the started instances are RHCOS and `.openshift_install_state.json` has:
```
            "machines": [
                {
                    "name": "master",
                    "replicas": 3,
                    "platform": {}
                },
                {
                    "name": "worker",
                    "replicas": 3,
                    "platform": {}
                }
            ],
```

**Comment by staebler** [comment]
```
- name: master
  platform:
    aws:
      amiID: ami-deadbeef
  replicas: 3
```

**Comment by vrutkovs** [comment]
Closing in favor of #991 - this one has more info
