### ISSUE TITLE
 failed to get vsphere Terraform variables: failed to use cached vsphere image

### ISSUE THREAD

**Issue by mostafasookar** [openshift/installer#7295]
INFO Consuming Install Config from target directory
INFO Obtaining RHCOS image file from 'https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.13-9.2/builds/413.92.202305021736-0/x86_64/rhcos-413.92.202305021736-0-vmware.x86_64.ova?sha256='
FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get vsphere Terraform variables: failed to use cached vsphere image: Get "https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.13-9.2/builds/413.92.202305021736-0/x86_64/rhcos-413.92.202305021736-0-vmware.x86_64.ova": x509: certificate signed by unknown authority

**Comment by jcpowermac** [comment]
@mostafasookar 
https://docs.openshift.com/container-platform/4.13/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-adding-vcenter-root-certificates_installing-vsphere-installer-provisioned

**Comment by r4f4** [comment]
/close
Reopen in case the problem persists.
