### ISSUE TITLE
Error: Invalid provider configuration:Uses AWS Provider instead of vSpere Provider when Deploying UPI

### ISSUE THREAD

**Issue by kulkarma** [openshift/installer#7324]
# Version

```console
$ openshift-install version
4.10.37
```

# Platform:

# What happened?

 I am not allowed to comment AWS provider in the lock file and also no means advised. My Question is when I declare vsphere provider why should it look for AWS provider credentials. Cannot alter the terraform Lock file.

│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded

# What you expected to happen?

When the root file has the vsphere provider it should not look for other providers OR should allow commenting the lock file so the existing provider in the main.tf can be used.

# How to reproduce it (as minimally and precisely as possible)?

Download the installer from git
configure the main.tf, terraform.tf and variables.tf with vsphere parmeter 
Run the ignition file to create openshift ignition files.
run terraform init ---> Observe aws provider config being downloaded
run terraform plan --> observe the error as above.

main.tf
========================================
locals {
  failure_domains     = length(var.failure_domains) == 0 ? [{
        datacenter = var.vsphere_datacenter
        cluster = var.vsphere_cluster
        datastore = var.vsphere_datastore
        network = var.vm_network
        distributed_virtual_switch_uuid = ""
  }] : var.failure_domains

  failure_domain_count = length(local.failure_domains)
  bootstrap_fqdns     = ["bootstrap-0.${var.cluster_domain}"]
  lb_fqdns            = ["lb-0.${var.cluster_domain}"]
  api_lb_fqdns        = formatlist("%s.%s", ["api", "api-int", "*.apps"], var.cluster_domain)
  control_plane_fqdns = [for idx in range(var.control_plane_count) : "control-plane-${idx}.${var.cluster_domain}"]
  compute_fqdns       = [for idx in range(var.compute_count) : "compute-${idx}.${var.cluster_domain}"]
  datastores          = [for idx in range(length(local.failure_domains)) : local.failure_domains[idx]["datastore"]]
  datacenters         = [for idx in range(length(local.failure_domains)) : local.failure_domains[idx]["datacenter"]]
  datacenters_distinct = distinct([for idx in range(length(local.failure_domains)) : local.failure_domains[idx]["datacenter"]])
  clusters            = [for idx in range(length(local.failure_domains)) : local.failure_domains[idx]["cluster"]]
  networks            = [for idx in range(length(local.failure_domains)) : local.failure_domains[idx]["cluster"]]
  folders             = [for idx in range(length(local.datacenters)) : "/${local.datacenters[idx]}/vm/${var.cluster_id}"]
}

provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
   count = length(local.datacenters_distinct)
   name = local.datacenters_distinct[count.index]
}
========================================

I ran this same installer in 2021 with terraform version Terraform v0.11.14 and with installer then. It ran smooth. This time with many functions are there but no easy documentation to disable certain unwanted providers. Please advise.
-->

```console
terraform init -get=false
terraform plan
```

# Anything else we need to know?

I want the procedure to silence other providers and use only vsphere please let me know the steps OR if any documentation exists please point me.

I also deleted all the provider folders leaving back only vcenter.

[root@scllab-5gsdm-bastion01 providers]# pwd;ls -latr
/root/ocp410/installer/terraform/providers
total 0
drwxr-xr-x 3 root root  64 Jul 12 16:07 ignition
drwxr-xr-x 3 root root  78 Jul 12 16:07 vsphere
drwxr-xr-x 3 root root 203 Jul 12 16:07 vsphereprivate
drwxr-xr-x 4 root root  74 Jul 13 00:46 ..
drwxr-xr-x 7 root root  84 Jul 13 00:47 .
drwxr-xr-x 3 root root  64 Jul 13 00:49 local
drwxr-xr-x 3 root root  64 Jul 13 00:50 time

# References

- enter text here.

**Comment by kulkarma** [comment]
Tested with the following Branches:
4.4 to 4.15 still continue to show the same error.

**Comment by r4f4** [comment]
See https://docs.openshift.com/container-platform/4.13/installing/installing_vsphere/installing-vsphere.html for the vsphere UPI docs.
