### ISSUE TITLE
Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady

### ISSUE THREAD

**Issue by adirilx** [openshift/installer#7459]
Hi All, I would apperciate some help with an issue I'm stuck with. I'm trying to install UPI Bare metal on ESXI Host 7.0.2 using OVN Kubernetes as CNI.  

Whenever I start the master nodes - I see those error "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started" repeatedly . I looked everywhere for a proper solutionbut didn't find any. I followed this document to the letter https://docs.openshift.com/container-platform/4.12/installing/installing_bare_metal/installing-bare-metal.html using the same configuration files.
Best Regards,
Adir

**Comment by kaplan-michael** [comment]
Hey @adirilx , 
I have ran into the same issue. I have dug out this from the logs `Fatal glibc error: CPU does not support x86-64-v2`

 It seems your CPU needs to support `x86-64-v2` instructions. The CPU types in qemu are pretty well explained in  [Proxmox qemu docs](https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines) Section  CPU Type. and in [RedHat docs on the microarchitecture specifics](https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#background_of_the_x86_64_microarchitecture_levels)
 
 
therefore, I assume, you'd have to configure the emulated/virtual CPU in ESXI to support that.
I'm not sure how esxi handles this, but setting the CPU type to something that supports it, or setting it to emulate the host CPU should fix it. atleast, it did for me. 

[kubevirt issue, with similar problem for reference](https://github.com/kubevirt/containerized-data-importer/issues/2652)
