### ISSUE TITLE
Provide a target which creates tfvars only

### ISSUE THREAD

**Issue by vrutkovs** [openshift/installer#753]
This would apply to all providers, but the primary target is AWS.

BYOR team has to come up with our own playbooks to provision infra on GCP to test libvirts case. In other provider's cases we'd like to avoid duplicating terraform and use it instead.

Here's what we'd like to do (marked parts we already have implemented):
* [x] Create install configs and modify settings - change AMI to point to CentOS/RHEL instead of RHCOS. See 
* [x] Generate bootstrap ignition files
* [ ] Run `create cluster --no-wait`. This command would finish once necessary infra is provisioned, no need to wait for "bootstrap completed" event
* [ ] Openshift-ansible playbook would fetch created instances and put them in according groups.
      Currently all instances are identical, it would be nice to have them tagged with a group
* [x] openshift-ansible would run the playbook to apply bootstrap Ignition file and complete the install
* [x] Cluster would be deprovisioned via `destroy cluster` command

Does that seem feasible? cc @sdodson @michaelgugino @wking

**Comment by wking** [comment]
> Run `create cluster --no-wait`. This command would finish once necessary infra is provisioned, no need to wait for "bootstrap completed" event

If you want us to use Terraform to create resources, why wouldn't you want to leave bootstrap-cleanup to us as well?  If want more fine-grained control of Terraform, I'd rather spit out `terraform.tfvars` so you can invoke Terraform directly (currently it's tightly-coupled to the launch in the installer code, but we could separate if if there was a use-case).

**Comment by vrutkovs** [comment]
> If you want us to use Terraform to create resources, why wouldn't you want to leave bootstrap-cleanup to us as well?

The plan is to use that for CI on BYOR. I'd rather have all infra provisioned in once place so that it would be easier to make changes.

Later on I suppose we'll come up with our own playbooks.

>If want more fine-grained control of Terraform, I'd rather spit out terraform.tfvars so you can invoke Terraform directly (currently it's tightly-coupled to the launch in the installer code, but we could separate if if there was a use-case).

That might work, seems to be the easiest solution so far

**Comment by vrutkovs** [comment]
>CI and prod should use the same method for provisioning infrastructure (otherwise, CI isn't giving us much).

Agree, that's what we'd like to achieve - unless 'RHEL instances on AWS' case is not planned

**Comment by vrutkovs** [comment]
Lets go with another target which produces tfvars

**Comment by wking** [comment]
> Lets go with another target which produces tfvars

We can split this out in the current asset framework if you need something in the short term.  But if you can wait a bit longer, #556 is overhauling the asset framework to generate all the assets in one pass (vs. having multiple asset-generating steps).  So you can:

```console
$ openshift-install --dir=whatever create assets
$ ls whatever/terraform/
libvirt-terraform.auto.tfvars  terraform.tfvars
$ cat whatever/metadata.json
{"clusterName":"wking","libvirt":{"uri":"qemu+tcp://192.168.122.1/system"}}
```

and so on, to get all the assets that we generate in Go.  Running `create cluster` instead just has [these additional steps][1], where we copy the already-generated assets into a scratch directory, invoke Terraform in that directory to launch the cluster, wait for the `bootstrap-complete` event, hit Terraform again to clean up the bootstrap resources, and print a nice message for users.  So folks who want to call Terraform on their own or who want to get `metadata.json` before invoking Terraform through the installer can use `create assets` to get everything they need.

[1]: https://github.com/openshift/installer/blob/f1db73b71fd9a15fd89373d2a0a0cf7331eb54dc/cmd/openshift-install/create.go#L86-L96

**Comment by eparis** [comment]
I'm going to close this issue. If we need to re-use any terraform assets in our CI system to add RHEL nodes to an existing OpenShift cluster we can look at how to write a (hidden) command to output those, but at this point I don't think we are going to address this issue.

Any new issue should be in Jira, not here.
