### ISSUE TITLE
openshift-apiserver is down

### ISSUE THREAD

**Issue by yrobla** [openshift/installer#755]
Since latest commits, the openshift-apiserver seems to be down. The origin of the problem seems to be on https://github.com/openshift/installer/commit/c6c9d832e94d0c677f3d8e6170e4306dd00df23a, where the ranges changed.
But this seems to don't be changed in all places, because openshit-apiserver is unable to start . I see that the service is up:

kubectl get service -n openshift-apiserver
NAME   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
api    ClusterIP   172.30.124.110   <none>        443/TCP   2h

But then the pods are being destroyed/recreated all the time. When i look at the events i can see:

1m          2h           59      kubernetes.156b58f4b18c6e06   Service               Warning   ClusterIPOutOfRange   ipallocator-repair-controller   Cluster IP 172.30.0.1 is not within the service CIDR 10.3.0.0/16; please recreate service

And in the events for the openshift-apiserver namespace, i just see the pod being recreated and killed all the time:

1m          1m           1       apiserver-zfxsk.156b623a9f2179f6   Pod         spec.containers{openshift-apiserver}   Normal    Created               kubelet, testcluster-master-0   Created container
1m          1m           1       apiserver-zfxsk.156b623aab6a49df   Pod         spec.containers{openshift-apiserver}   Normal    Started               kubelet, testcluster-master-0   Started container
1m          1m           1       apiserver-zfxsk.156b623c0c868d2d   Pod         spec.containers{openshift-apiserver}   Warning   Unhealthy             kubelet, testcluster-master-0   Readiness probe failed: Get https://10.128.0.91:8443/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
1m          1m           1       apiserver-zfxsk.156b623c61d1f53a   Pod         spec.containers{openshift-apiserver}   Normal    Killing               kubelet, testcluster-master-0   Killing container with id cri-o://openshift-apiserver:Need to kill Pod

**Comment by yrobla** [comment]
It was already reported

**Comment by wking** [comment]
See openshift/cluster-kube-apiserver-operator#143 and #751.
