### ISSUE TITLE
NTP configuration for Bare Metal IPI/UPI in Disconnected Network 

### ISSUE THREAD

**Issue by BadgerOps** [openshift/installer#7571]
# Version

```console
$ openshift-install version
4.12.33
```

# Platform:
baremetal

* IPI

# What happened?

We are installing using the [openshift-install agent IPI method](https://docs.openshift.com/container-platform/4.12/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.html) 

We are using static IP's that are defined in the `agent-config.yaml` and do not have DHCP available in our environment.

We observe a failure to deploy the cluster due to clock drift. Manually logging into the nodes while they're in the initialization stage and hand-editing `/etc/chronyd.conf` with our internal NTP servers & restarting the `chronyd` service allows the install to continue. 

We're aware of the [post-install machine configuration](https://docs.openshift.com/container-platform/4.12/post_installation_configuration/machine-configuration-tasks.html#installation-special-config-chrony_post-install-machine-configuration-tasks) options, but obviously this isn't useful for us at this point.

I did some digging in this repo, and noticed the question has been asked before, so apologies for bringing it up again - I do think the concept holds merit, especially given the rise in disconnected installs.

# What you expected to happen?

The ability to configure NTP Server(s) or Pools for openshift-installer agent based IPI installs on baremetal

# How to reproduce it (as minimally and precisely as possible)?

I unfortunately cannot provide the logs here, but:

1. Attempt an installation on several non-DHCP & non-internet connected systems
2. Observe clock skew preventing the installer from continuing
3. Experience despair
4. Manually set the clock or manually update `/etc/chronyd.conf`
5. Observe installation continue

# Anything else we need to know?

Y'all are fine peeps doing good work

# References

* https://github.com/openshift/installer/issues/3258
* https://github.com/openshift/enhancements/blob/master/enhancements/installer/agent-based-installation-in-hive.md (good notes on why NTP in pre-install env is helpful in the PR for this enhancement)

# NOTE:

I recognize this is likely a hurdle due to how the RHCOS filesystem is deployed & would be happy to help find a path forward!

**Comment by BadgerOps** [comment]
Any thoughts / direction on this? Don't mean to bug y'all, just don't want this to atrophy.

**Comment by snecklifter** [comment]
Hey @BadgerOps - just stumbled across this whilst trying to do the same thing - any reason https://docs.openshift.com/container-platform/4.12/installing/install_config/installing-customizing.html wont work for you?

**Comment by BadgerOps** [comment]
Hi @snecklifter yes, I did see that, I _could be wrong_ but as far as I can tell, these configs don't apply during _initialization_ but are applied to the installed hosts as part of the ignition process.

**Comment by snecklifter** [comment]
@BadgerOps modifying node ignition might get you what you want - https://access.redhat.com/solutions/4909411 - although that kb is quite old now. Hmm, I am doing the same deployment so I wonder why clock drift is an issue for you. It might be worth checking bmc/hwclock has a reliable source?

**Comment by Skalador** [comment]
Hello,
we are currently preparing for an agent-based installation and will most likely run into the same issue. Therefore we are planning to use something similar to this:
```shell
openshift-install --dir installation/ agent create image && coreos-installer iso ignition show installation/agent.x86_64.iso > installation/tmp.ign
cd installation/
export CHRONY_CONF_BASE64=$(cat << EOF | base64 -w 0
server <NTP_SERVER> iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
logdir /var/log/chrony
EOF          
)


jq '.storage.files += [{
  "filesystem": "root",
  "path": "/etc/chrony.conf",
  "contents": {
    "source": "data:text/plain;charset=utf-8;base64,$CHRONY_CONF_BASE64"
  },
  "mode": 420
}]' tmp.ign > custom_ign.ign
coreos-installer iso ignition embed -fi custom_ign.ign agent.iso
```
Note: `<NTP_SERVER>` has to be replaced with your actual server.
Unfortunately, I cannot test this right now. Please let me know, if this has worked out for you.

**Comment by Skalador** [comment]
Hi @BadgerOps thanks for trying. I will be happy to know, if this works. 
Just some side note, I have also injected kernel parameters into `/etc/sysctl.d/99-custom.conf` which were "ignored" according to the iLO console screen of our BareMetal servers. Nevertheless, they were used. Not sure yet, if my configuration was not fully correct, thus it was "ignored" or if there is some sort of bug.

**Comment by sjbylo** [comment]
Hi @Skalador, 

your above script did not work for me, but i think i got it working. 

Even though I added extra '' to make your script work and the resulting ign looked ok, the SNO failed at boot.  I then changed the ignition config to look *more like the existing entries* and it seems to work for me, thanks:

I got it to work with this script:

```
dir=iso-agent-based
ntp_ip=10.0.1.8

openshift-install --dir $dir/ agent create image

coreos-installer iso ignition show $dir/agent.x86_64.iso > $dir/tmp.ign

export CHRONY_CONF_BASE64=$(cat << EOF | base64 -w 0
server $ntp_ip iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
logdir /var/log/chrony
EOF
)


jq '.storage.files += [{
  "group": {},
  "overwrite": true,
  "path": "/etc/chrony.conf",
  "user": {
    "name": "root"
  },
  "contents": {
    "source": "data:text/plain;charset=utf-8;base64,'$CHRONY_CONF_BASE64'"
  },
  "mode": 420
}]' $dir/tmp.ign > $dir/custom_ign.ign

coreos-installer iso ignition embed -fi $dir/custom_ign.ign $dir/agent.x86_64.iso
```


Seems to be working in node0:

```
[core@sno ~]$ sudo chronyc sources -v 

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current best, '+' = combined, '-' = not combined,
| /             'x' = may be in error, '~' = too variable, '?' = unusable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
^* 10.0.1.8                      2   6    37    23   -213ns[  +15us] +/-   11ms
```

**Comment by Skalador** [comment]
> Hi @Skalador, 
> 
> your above script did not work for me, but i think i got it working. 
> 
> Even though I added extra '' to make your script work and the resulting ign looked ok, the SNO failed at boot.  I then changed the ignition config to look *more like the existing entries* and it seems to work for me, thanks:
> 
> I got it to work with this script:
> 
> ```
> dir=iso-agent-based
> ntp_ip=10.0.1.8
> 
> openshift-install --dir $dir/ agent create image
> 
> coreos-installer iso ignition show $dir/agent.x86_64.iso > $dir/tmp.ign
> 
> export CHRONY_CONF_BASE64=$(cat << EOF | base64 -w 0
> server $ntp_ip iburst
> driftfile /var/lib/chrony/drift
> makestep 1.0 3
> rtcsync
> logdir /var/log/chrony
> EOF
> )
> 
> 
> jq '.storage.files += [{
>   "group": {},
>   "overwrite": true,
>   "path": "/etc/chrony.conf",
>   "user": {
>     "name": "root"
>   },
>   "contents": {
>     "source": "data:text/plain;charset=utf-8;base64,'$CHRONY_CONF_BASE64'"
>   },
>   "mode": 420
> }]' $dir/tmp.ign > $dir/custom_ign.ign
> 
> coreos-installer iso ignition embed -fi $dir/custom_ign.ign $dir/agent.x86_64.iso
> ```
> 
> 
> Seems to be working in node0:
> 
> ```
> [core@sno ~]$ sudo chronyc sources -v 
> 
>   .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
>  / .- Source state '*' = current best, '+' = combined, '-' = not combined,
> | /             'x' = may be in error, '~' = too variable, '?' = unusable.
> ||                                                 .- xxxx [ yyyy ] +/- zzzz
> ||      Reachability register (octal) -.           |  xxxx = adjusted offset,
> ||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
> ||                                \     |          |  zzzz = estimated error.
> ||                                 |    |           \
> MS Name/IP address         Stratum Poll Reach LastRx Last sample               
> ===============================================================================
> ^* 10.0.1.8                      2   6    37    23   -213ns[  +15us] +/-   11ms
> ```
> 

@sjbylo Great, now we have a working solution. Thanks for sharing!

**Comment by BadgerOps** [comment]
This is fantastic to see, thanks for sharing back to this thread. I didn't think of adding the ignition after the iso was generated, nice work.

**Comment by sjbylo** [comment]
Hi, hope you find it useful,   

I am working on some automation around the agent based installer.  I have added this NTP workaround to it also.  

You just need to clone the repo on a connected Linux box (Fedora or RHEL) and install then run make and it will guide you through the whole process. 

https://github.com/sjbylo/aba.git  

You are welcome to try it and make it better :) 

Cheers,

**Comment by BadgerOps** [comment]
Closing this - I think we've got sufficient data in this issue for posterity - thanks, all!
