### ISSUE TITLE
Support Multiple Clusters With Same Name

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#762]
Service Delivery raised a use case where a customer may want multiple clusters, in one AWS account, with the same subdomain name, but different base domains. 

As discussed in arch call this issue is to track any cloud infra we create by cluster name that would collide if this use case in play.

CC @jhernand

**Comment by DanyC97** [comment]
just jumping in with a quick q:

does installer support the use case of multiple clusters in same VPC ?

**Comment by crawford** [comment]
@DanyC97 no, it does not.

**Comment by DanyC97** [comment]
is something you would consider or goes against your deployment vision ?

**Comment by crawford** [comment]
Yes, multiple clusters in a single VPC is not something we want to support. We think VPC peering is an acceptable alternative.

**Comment by DanyC97** [comment]
thanks for the feedback @crawford

**Comment by wking** [comment]
> does installer support the use case of multiple clusters in same VPC?

Just to keep focus on this issue in case someone comes along and sees the shared-VPC sub-thread, shared-VPC discussion belongs in #1083.

**Comment by wking** [comment]
@dgoodwin, in relation to #1169, we'd briefly discussed using the full domain name (vs. just the tip subdomain) in resource names to address this problem.  And while I still think that would narrowly address this issue, it would not address the slightly larger issue from #1174, where orphaned resources from broken previous cleanups collided with new resource requests for subsequent clusters.  So my preference is still for names based on the cluster ID, with the full cluster domain in tags.  Not quite as user friendly to casual AWS-web-console browsers, but you can generally configure the web-console to add a column for a given tag to list views.  You could obviously also use the full domain plus some random, uniquifying subset of the cluster ID, but I start worrying about length constraints with that approach (or even with the full-domain approach alone).

**Comment by dgoodwin** [comment]
We can make that work on our side but can we pursue a change like this at this point? I know we have some dependencies on names of objects in AWS, I think we're talking about a large multi-team coordinated change here.

**Comment by akostadinov** [comment]
I would say that cluster name and ID are somehow a duplication. Why do we need both name and UUID to identify a cluster? Much simpler to identify by name and much simpler to recover in case of leftover resources.

**Comment by abhinavdahiya** [comment]
This is now supported.

/close
