### ISSUE TITLE
Unable to log in to OCP console due to expired certificate

### ISSUE THREAD

**Issue by cndingwei** [openshift/installer#7623]
OCP version 4.8.57
Because the certificate has expired, I cannot log in to the OCP web console, including oc login.
The prompts for logging in via oc login are as follows:
error: x509: certificate has expired or is not yet valid: current time 2023-10-23T12:54:27+08:00 is after 2023-09-18T00:59:27Z

How to solve it?

**Comment by nakulbhati** [comment]
Check redhat solution number : 6632521 (recovering from exp ocp cert)

**Comment by cndingwei** [comment]
> Check redhat solution number : 6632521 (recovering from exp ocp cert)

Can you give me a link?
If it is the link below, it prompts me that I do not have permission.
https://access.redhat.com/mt/zh-hans/solutions/6632521

Access denied

You do not have permission to access the page you requested. If this is knowledge content, it may be unpublished or retired. Documents may be retired when they are outdated, duplicated, or no longer necessary. Please try [searching](https://access.redhat.com/search/browse/search) the Customer Portal for the most current, published information.

**Comment by cndingwei** [comment]
> Check redhat solution number : 6632521 (recovering from exp ocp cert)

The result of my execution according to the document is as follows:
====================
[root@bostion auth]# pwd
/root/ocp47/auth
[root@bostion auth]# scp -r /root/ocp47/auth/kubeconfig core@master01.wyocp.wanyanggroup.cn:/tmp
kubeconfig                                                                                             100%   21KB  18.3MB/s   00:00
[root@bostion auth]# ssh core@master01.wyocp.wanyanggroup.cn
Red Hat Enterprise Linux CoreOS 48.84.202301181057-0
  Part of OpenShift 4.8, RHCOS is a Kubernetes native operating system
  managed by the Machine Config Operator (`clusteroperator/machine-config`).

WARNING: Direct SSH access to machines is not recommended; instead,
make configuration changes via `machineconfig` objects:
  https://docs.openshift.com/container-platform/4.8/architecture/architecture-rhcos.html

---
Last login: Thu Oct 26 06:30:43 2023 from 182.18.18.65
[core@master01 ~]$ cd /tmp
[core@master01 tmp]$ ls
kubeconfig  systemd-private-f1205e9cfddc405685ec5189afa7e94f-chronyd.service-0tWvUh  vmware-root_1228-2990547542
[core@master01 tmp]$ sudo -i
[root@master01 ~]# export KUBECONFIG=/tmp/kubeconfig
[root@master01 ~]# oc whoami
error: You must be logged in to the server (Unauthorized)

**Comment by cndingwei** [comment]
The environment has been upgraded from OCP4.7 to 4.8

**Comment by cndingwei** [comment]
The problem is solved.
Obtain login information through https://oauth-openshift.apps.wyocp.wanyanggroup.cn/oauth/token/display
Then execute the following command:
oc delete secret -n openshift-ingress ingress-cert --ignore-not-found=true
oc create secret tls ingress-cert \
  --cert=certs/apps.full.pem \
  --key=certs/apps.key \
  -n openshift-ingress
oc patch ingresscontroller.operator default \
  --type=merge -p \
  '{"spec":{"defaultCertificate": {"name": "ingress-cert"}}}' \
  -n openshift-ingress-operator

**Comment by SankaraNarayananK-sudo** [comment]
@cndingwei May I know how the apps.full.pem and apps.key generated to fix this issue?
