### ISSUE TITLE
Q: value of libvirt URI for external and internal communication?

### ISSUE THREAD

**Issue by gbraad** [openshift/installer#774]
In the libvirt howto, the following is written

```bash
export OPENSHIFT_INSTALL_LIBVIRT_URI=qemu+tcp://192.168.122.1/system
```

I understand that `122.1` is used, as this is the default network that exists for libvirt, but this means that the cluster will also communicate on this same address, while they have their own cluster network as `126.1`. I also know that it can not be changed, as this same variable is used by Terraform to setup the communication to create the infra and nodes BEFORE the cluster network exists (it needs to communicate with the daemon).

So, somehow this feels like a variable that has been given a double meaning, as the cluster communication does not have to be the same as the host communication for setup. right? is there a way around it?

E.g. what if I want to target a remote host with the installer, and use the remote IP address for this... I would like the cluster to use the internal network instead.

**Comment by wking** [comment]
> I understand that `122.1` is used, as this is the default network that exists for libvirt, but this means that the cluster will also communicate on this same address, while they have their own cluster network as `126.1`.

The IP used in `OPENSHIFT_INSTALL_LIBVIRT_URI` is completely orthogonal to the IP used for your new cluster.  The libvirt connection URI lives [here][1] in your install-config, while the node CIDR lives [here][2].  We expect that [the default libvirt node CIDR][3] will work for enough users that there's no need for a wizard prompt for that setting, but you can override it by supplying your own install-config during a [multi-stage install][4].

> So, somehow this feels like a variable that has been given a double meaning, as the cluster communication does not have to be the same as the host communication for setup. right?

Right, you could theoretically have a cluster on 192.168.126.0/24, the installer libvirt connection as qemu+tcp://1.2.3.4/system, and the cluster libvirt connection as qemu+tcp://192.168.122.1/system.  We don't have separate knobs for that now, because we expect there to usually be one IP for the libvirt connection that works from both the install host and the cluster nodes.  If you don't have that, perhaps you can use a domain name (qemu+tcp://libvirt.example.com/system) and set up your host and cluster DNS to resolve it appropriately for each context?

[1]: https://github.com/openshift/installer/blob/v0.4.0/pkg/types/libvirt/platform.go#L10-L13
[2]: https://github.com/openshift/installer/blob/v0.4.0/pkg/types/libvirt/network.go#L7-L8
[3]: https://github.com/openshift/installer/blob/v0.4.0/pkg/asset/installconfig/libvirt/libvirt.go#L20
[4]: https://github.com/openshift/installer/blob/v0.4.0/docs/user/overview.md#multiple-invocations

**Comment by gbraad** [comment]
the issue exists mostly due to terraform, as it introduced a chicken-egg problem here. I'll look into the DNS solution, as this is anyway a requirement for the setup.

I'll see if we can work around it this way.

**Comment by praveenkumar** [comment]
@wking About mutli-stage install, I want to understand some of following context.

1. when we run `install-config` and the artifact which it generates is again used by terraform, since all configs are coming from env variable.

```console
$ bin/openshift-install --dir test --log-level debug create install-config
DEBUG Fetching "Install Config"...                 
DEBUG Loading "Install Config"...                  
DEBUG   Loading "Cluster ID"...                    
DEBUG   Loading "Email Address"...                 
DEBUG   Loading "Password"...                      
[...]

$ cat test/install-config.yml 
admin:
  email: prkumar@foo.com
  password: mytopsecret
  sshKey: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/jLwQntqEW8oym5eSXMzJJZfD+xP1ilsNDsqRWDFWUzjLtvhfY80RCz1OVgmTXa6loXB/iH5v8CyiiDA5gsZvmVtVEnuPbYXRtbZa5h/dMbW/sFPUZ311TZxbvDpNJFyVoSbbkXjkX5XeSAYq5jsRa9iOZIz3Ql9HFn3+OOF5OTcRWczBf+4A31BcIgSjo4K3H5G37WVAuwsiHYm0UHdlbrjj8w80qLQw2I/PunKqtmEWL/APf3OKRm5WLHFXI8a1i58Mj78Bqs0oECH/RYFRlfmugvkddflE477u55eeuF0erWnzrCtjU56crLvSsGh8uz/CkRvj95O7yLsxhP6x prkumar@local
baseDomain: tt.testing
clusterID: 3baee746-d2f5-4ed8-9b19-e900e6876e3f
machines:
- name: master
  platform: {}
  replicas: 1
- name: worker
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: test1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  serviceCIDR: 172.30.0.0/16
  type: OpenshiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.100.1/system
    defaultMachinePlatform:
      image: https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/47.172/redhat-coreos-maipo-47.172-qemu.qcow2
    masterIPs: null
    network:
      if: tt0
      ipRange: 192.168.126.0/24
pullSecret:X
```

2. But if I generate the manifest and grep the libvirt URI and change those that wouldn't be issue right? 

```console
14:36 $ bin/openshift-install --dir test --log-level debug create manifests
DEBUG Fetching "Common Manifests"...               
DEBUG Loading "Common Manifests"..
[...]

14:41 $ grep -nR 100 .
./tectonic/99_openshift-cluster-api_worker-machineset.yaml:45:            uri: qemu+tcp://192.168.100.1/system
./tectonic/99_openshift-cluster-api_master-machines.yaml:31:        uri: qemu+tcp://192.168.100.1/system
./manifests/cluster-config.yaml:29:        URI: qemu+tcp://192.168.100.1/system
./.openshift_install_state.json:167:                    "URI": "qemu+tcp://192.168.100.1/system",
./.openshift_install_state.json:202:            "URI": "qemu+tcp://192.168.100.1/system",
./.openshift_install_state.json:337:                "install-config": "admin:\n  email: prkumar@foo.com\n  password: mytopsecret\n  sshKey: |\n    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/jLwQntqEW8oym5eSXMzJJZfD+xP1ilsNDsqRWDFWUzjLtvhfY80RCz1OVgmTXa6loXB/iH5v8CyiiDA5gsZvmVtVEnuPbYXRtbZa5h/dMbW/sFPUZ311TZxbvDpNJFyVoSbbkXjkX5XeSAYq5jsRa9iOZIz3Ql9HFn3+OOF5OTcRWczBf+4A31BcIgSjo4K3H5G37WVAuwsiHYm0UHdlbrjj8w80qLQw2I/PunKqtmEWL/APf3OKRm5WLHFXI8a1i58Mj78Bqs0oECH/RYFRlfmugvkddflE477u55eeuF0erWnzrCtjU56crLvSsGh8uz/CkRvj95O7yLsxhP6x prkumar@local\nbaseDomain: tt.testing\nclusterID: 3baee746-d2f5-4ed8-9b19-e900e6876e3f\nmachines:\n- name: master\n  platform: {}\n  replicas: 1\n- name: worker\n  platform: {}\n  replicas: 1\nmetadata:\n  creationTimestamp: null\n  name: test1\nnetworking:\n  clusterNetworks:\n  - cidr: 10.128.0.0/14\n    hostSubnetLength: 9\n  serviceCIDR: 172.30.0.0/16\n  type: OpenshiftSDN\nplatform:\n  libvirt:\n    URI: qemu+tcp://192.168.100.1/system\n    defaultMachinePlatform:\n      image: https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/47.172/redhat-coreos-maipo-47.172-qemu.qcow2\n    masterIPs: null\n    network:\n      if: tt0\n      ipRange: 192.168.126.0/24\npullSecret: '{\"auths\": {\"quay.io\": {\"auth\": \"Y29yZW9zK3RlYzJfaWZidWdsandoYTNkaW4yYmlqY2MybjJlaTpLMVNEQjNVWTlHMUZQUFpKTFg5VTFOWlJIQjRURjA1WllEOTZBMjdSWTRYRVcwSVVKVkxWRFZFSDFDSlZNQlNS\",\"email\":\n  \"\"}}}'\n"
```

3. What is the use of `openshift_install_state.json` file, since this only created during the manifest command?

**Comment by gbraad** [comment]
DNS is a better way forward, as it makes the environment not rely on
internal/configed IP addresses, but can all be co trolled by static
hostnames and address values by a DNS server or host file

**Comment by praveenkumar** [comment]
@gbraad one of the network (test1) anyway we need to configure `192.168.126.x` we can just use DNS to resolve the IP from this network though.

**Comment by crawford** [comment]
> We don't have separate knobs for that now, because we expect there to usually be one IP for the libvirt connection that works from both the install host and the cluster nodes.

@wking there isn't any technical reason for this limitation, right?

**Comment by wking** [comment]
> > We don't have separate knobs for that now, because we expect there to usually be one IP for the libvirt connection that works from both the install host and the cluster nodes.
>
> @wking there isn't any technical reason for this limitation, right?

Just "more knobs makes this more confusing for maintainers and users, and gives one more way for folks to break things".  What's the use-case here?  Do we expect cases that can't be addressed via DNS management?

**Comment by gbraad** [comment]
At the moment using:

```
  <dns>
   ... 
   <host ip='192.168.126.1'>
      <hostname>libvirt</hostname>
    </host>
  </dns>
```
in the network defintion of libvirt. this works as expected.

I am wondering if more knobs are needed. This works for our usecase and hides the IP address from the cluster.

**Comment by gbraad** [comment]
Works for me (you may close if no further comments)

**Comment by wking** [comment]
> ```xml
> <host ip='192.168.126.1'>
>   <hostname>libvirt</hostname>
> </host>
> ```

It's still strange to me that you have a `libvirtd` that is reachable from both the install host and the cluster but which does not have a single IP that can be used from both sides.  On my system, `192.168.126.1` is `tt0`, the bridge setup by libvirt for the cluster network.  Are you not forwarding connections from the cluster to that bridge on to the wider internet (including the `libvirtd` running on your host)?  What interfaces is your `libvirtd` listening to?

```console
$ ps -A -o pid,args | grep libvirtd | grep -v grep
 2171 /usr/sbin/libvirtd --listen
$ sudo ss -lp | grep '^tcp.*pid=2171,'
tcp    LISTEN     0      128     *:16509                 *:*                     users:(("libvirtd",pid=2171,fd=13))
tcp    LISTEN     0      128    :::16509                :::*                     users:(("libvirtd",pid=2171,fd=14))
```

And I can successfully connect to that `libvirtd` using any IPv4 address associated with my system:

```console
$ for IP in $(ip -4 addr | sed -n 's|.* inet \([0-9.]*\)/.*|\1|p'); do virsh -c "qemu+tcp://${IP}/system" version | grep Running; done
Running hypervisor: QEMU 2.9.0
Running hypervisor: QEMU 2.9.0
Running hypervisor: QEMU 2.9.0
Running hypervisor: QEMU 2.9.0
Running hypervisor: QEMU 2.9.0
Running hypervisor: QEMU 2.9.0
```

(and presumably IPv6 too, although I haven't checked).  Those IP addresses include several different interface types:

```console
$ ip -4 addr | grep '^[0-9]'
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
3: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
6: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
21: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
541: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1360 qdisc pfifo_fast state UNKNOWN group default qlen 100
710: tt0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
```

So I'm happy to revisit this if you can provide more details about why neither 192.168.122.1 nor 192.168.126.1 work for both your install-host and cluster nodes, but until then I'll close the issue.

/close

**Comment by gbraad** [comment]
we do not want to use `.122.1`, as the cluster itself is defining it's own network as `126.1`. We do not see a need to have another network (although default) to exist to make the environment spinup new instances; as in the currently described setup you are relying on the existence of the default network also (this is not always defined on certain distros other than Fedora/CentOS). In our case, we want to rely on as little dependencies to have the environment working (self contained with a single network definition).
