### ISSUE TITLE
Installer does not recognize Azure platform cloud name USSec for Azure secret cloud (IL6)

### ISSUE THREAD

**Issue by mradecker** [openshift/installer#7787]
Customer tried installing OpenShift in Azure secred cloud and cannot even create an install-config.yaml because the cloudName: USSec is not recognized by the installer.  Below are the current valid values for cloudName.  

Valid Values: "","AzurePublicCloud","AzureUSGovernmentCloud","AzureChinaCloud","AzureGermanCloud","AzureStackCloud"

Adding "USSec" would allow customers to integrate with the Azure secret cloud.

**Comment by mbach04** [comment]
Ref PR: [PR 7788](https://github.com/openshift/installer/pull/7788/files)

**Comment by adimusset** [comment]
Can we re-open this issue, this Cloud still needs to be added to the installer
