### ISSUE TITLE
bootstrap node do not boot

### ISSUE THREAD

**Issue by serjtk** [openshift/installer#7855]
# Version

```console
$ openshift-install version
openshift-install unreleased-master-9212-g611e16ac251e6057eb170f733b9530260b8dcf4a
built from commit 611e16ac251e6057eb170f733b9530260b8dcf4a
release image registry.ci.openshift.org/origin/release:4.14
release architecture amd64
```

# Platform:
libvirt

Please specify:
IPI

# What happened?

Bootstrap node do not complete boot

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

#platform libvirt
$ openshift-install create cluster

```console
$ journalctl -b -f -u release-image.service -u bootkube.service
Dec 20 14:07:37 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Failed with result 'exit-code'.
Dec 20 14:07:37 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Consumed 1.268s CPU time.
Dec 20 14:07:42 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 942.
Dec 20 14:07:42 serjtk-cluster-9mr5t-bootstrap systemd[1]: Stopped Bootstrap a Kubernetes cluster.
Dec 20 14:07:42 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Consumed 1.268s CPU time.
Dec 20 14:07:42 serjtk-cluster-9mr5t-bootstrap systemd[1]: Started Bootstrap a Kubernetes cluster.
Dec 20 14:07:44 serjtk-cluster-9mr5t-bootstrap bootkube.sh[318202]: F1220 14:07:44.318642       1 image.go:32] error: error: Unknown name requested, could not find cluster-config-api in UpdatePayload
Dec 20 14:07:44 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 20 14:07:44 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Failed with result 'exit-code'.
Dec 20 14:07:44 serjtk-cluster-9mr5t-bootstrap systemd[1]: bootkube.service: Consumed 1.228s CPU time.
```

# Anything else we need to know?

do not find cluster-config-api image
$ podman run --quiet --rm --net=none registry.ci.openshift.org/origin/release@sha256:3cdbe4a34d3f32881c7183b4446951d5fd98fb290631cbacb01eaa1e3aecb4b5 image cluster-config-api
F1220 12:37:57.774137       1 image.go:32] error: error: Unknown name requested, could not find cluster-config-api in UpdatePayload

**Comment by arunmk** [comment]
I also encountered the same issue in the `master` branch for the vSphere infra. However, when I moved to the `release-4.14` branch, the issue disappeared.

I suspect that there is a regression in the `master` branch. I have not investigated it further.
