### ISSUE TITLE
containerd dependency has known vulnerability 

### ISSUE THREAD

**Issue by rolandmkunkel** [openshift/installer#7930]
The installer uses a replace directive to replace containerd with version v1.5.18 in dependencies [1].

This version is known to have a vulnerability [2]. 

Is it possible to upgrade to at least 1.6.26?

[1] https://github.com/openshift/installer/blob/7be2cf71cdef9f5fe0d2d9687615c2bb2741ffcd/go.mod#L315
[2] https://github.com/advisories/GHSA-7ww5-4wqc-m92c

**Comment by rolandmkunkel** [comment]
% go mod why github.com/containerd/containerd   
# github.com/containerd/containerd
(main module does not need package github.com/containerd/containerd)

It looks like this dependency is not used at all

**Comment by barbacbd** [comment]
https://github.com/openshift/installer/pull/7942
