### ISSUE TITLE
IPI fails on IBM Cloud due to pre_provisioning DNS Services

### ISSUE THREAD

**Issue by lionelvillard** [openshift/installer#8040]
# Version

```console
$ openshift-install version
./openshift-install 4.14.11
built from commit b4bcb87d2a677f75561749939216451e45c430ce
release image quay.io/openshift-release-dev/ocp-release@sha256:36783a8b066c96dd6258e818ce51b5a763438adbf56221ea5c4b62ae4f345886
release architecture amd64
```

# Platform: IBM Cloud

* IPI (automated install with `openshift-install`. If you don't know, then it's IPI)

# What happened?

I'm getting this error:

```
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "CVO Ignore": failed to fetch dependency of "Common Manifests": failed to generate asset "DNS Config": failed to get DNS zone ID: Access to the api resource is not authorized.
```

After further investigation, I determined the root cause is a DNS service instance in pre_provisioning state. When listing zones in this instance I get a not authorized error.

# What you expected to happen?

IPI should only consider active DNS Services

# How to reproduce it (as minimally and precisely as possible)?

Create a DNS service in pre_provisioning state and install Openshift in the same account. 

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by cjschaef** [comment]
I've opened a Jira bug for this issue
https://issues.redhat.com/browse/OCPBUGS-29673

I expect this GH issue can be closed in place of that (although I cannot do that).

**Comment by r4f4** [comment]
/close
Discussion moved to Jira.
