### ISSUE TITLE
A suggestion on the name of binaries on the release page

### ISSUE THREAD

**Issue by hongkailiu** [openshift/installer#807]
It is about the binaries on [the release page](https://github.com/openshift/installer/releases).

I would suggest to compress bin file, eg, `openshift-install-darwin-amd64`, into a zip/tar.gz file even though it contains only 1 file for the moment. OS and Arch info (maybe also add the version and commit-hash in) appears only on the wrapper file, instead of the binary file.

Take the sample for terraform release (also 1 file inside).
https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip

```sh
$ unzip -l terraform_0.11.10_linux_amd64.zip 
Archive:  terraform_0.11.10_linux_amd64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 89397536  10-23-2018 15:00   terraform
---------                     -------
 89397536                     1 file

```

**Comment by wking** [comment]
That would also allow folks to unpack without explicitly setting the executable bit on the new file.  But `funzip` vs. rename and post `chmod` is a wash for me, I don't feel strongly either way.  Anyone else want to weigh in?

**Comment by hongkailiu** [comment]
@wking Yes. That is exactly what I did after curl. ^_^

```
$ curl -LO https://github.com/openshift/installer/releases/download/v0.5.0/openshift-install-linux-amd64
$ mv openshift-install-linux-amd64 openshift-install
$ chmod +x ./openshift-install
```

Probably it is just me. Seeing a file without extension after `curl`, I just lost the idea of what to do next.

**Comment by eparis** [comment]
I do not think we are going to change this at this time. I apologize for any inconvenience.
