### ISSUE TITLE
cloud.openshift.com is rendered completely inoperable by Privacy Badger

### ISSUE THREAD

**Issue by danwinship** [openshift/installer#809]
(I'm filing this against the installer because I'm not sure where else to file it; the only help/documentation links from try.openshift.com point to the installer docs.)

If you visit try.openshift.com under Firefox with the Privacy Badger extension installed and running, you get a completely blank page. Like, 100% completely blank.

(Privacy Badger is a fairly popular/encouraged plugin. At the moment, if you go to https://addons.mozilla.org/en-US/firefox/, it is the first plugin listed.)

**Comment by danwinship** [comment]
So apparently there is a known problem with Privacy Badger where it tends to think that SAML auth is an attempt to do evil cross-website tracking (https://github.com/EFForg/privacybadger/issues/137). The bug won't happen for all users because Privacy Badger learns over time, so for some users it may not have decided that `developers.redhat.com` is a tracker.

I'm not sure whether this problem is likely to be common or rare. (The workaround is to click on the Privacy Badger icon and click "Disable Privacy Badger For This Site".)

**Comment by wgordon17** [comment]
@danwinship try.openshift.com *was* just a redirect to cloud.openshift.com. It's now a landing page. Can you confirm if you're still having this issue with

- try.openshift.com
-cloud.openshift.com

**Comment by wking** [comment]
Presumably it's still an issue with cloud.openshift.com, since users would (hopefully ;) have to authenticate in order to get their pull secrets.  And we bypass try.openshift.com in our links since #886.  So I'm just going to update the title now, but please let me know if my guess is incorrect ;).

**Comment by danwinship** [comment]
yes, the problem was with cloud.openshift.com, not try.openshift.com

**Comment by vbatts** [comment]
ha yea, same issue. Disabling badger for this site allowed it to work correctly.

**Comment by eparis** [comment]
Moved to: https://jira.coreos.com/browse/SDA-649
