### ISSUE TITLE
Images from installer seem to be unavailable at later times

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/installer#815]
# Version

```console
$ openshift-install version
openshift-install v0.4.0-60-g12ef0cba3e6d86dca78c6879cfef2981d96fa441
Terraform v0.11.8
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

I was working on a local change to the `console-operator` binary and wanted to disable the `console-operator` deployed by the installer.  I noticed that if you `oc delete deployment console-operator -n openshift-console` the deployment is recreated within a minute or so.  This is expected.  However, if you `oc get pods`, the pod for the operator is in `ImagePullBackoff`.  

# What you expected to happen?

It appears that images used during install are no longer available later.  I was expecting that the recreated deployment would be able to continue to run pods. This seems problematic.  I assume it is not just the `console-operator` image, but other images could be affected as well.

# How to reproduce it (as minimally and precisely as possible)?

```bash 
oc delete deployment console-operator
oc get pods
# check the pod over time & see if it remains in ImagePullBackoff
```

# Anything else we need to know?

This may or may not be a bug, it depends on how resilient we expect things to be at this point.  I would assume a customer who accidentally deleted the operator pod would be concerned that it was not actually able to fix its own state.

This may or may not be related to the `installer`.  I am happy to move the issue elsewhere if there is a better component fit.

Thanks!

**Comment by wking** [comment]
If you build from master (like you did), the installer floats with the most-recent update payload in the CI repository.  But we garbage collect those fairly aggressively (today we *increased* retention to 72 hours).  If you want something that is going to last more than a few days, you should use [a released installer][1], which pin to a particular quay.io/openshift-release-dev/ocp-release tag.  You can still build from source if you want, but build from one of our release tags tags to get the update-payload pinning.

I'm going to assume that's what happened to you and close this issue.  But if it doesn't sound right, let us know and we'll re-open.

/close

[1]: https://github.com/openshift/installer/releases

**Comment by benjaminapetersen** [comment]
Great, that's very helpful, thanks!
