### ISSUE TITLE
Asset naming is confusing

### ISSUE THREAD

**Issue by wgordon17** [openshift/installer#820]
The MacOS assets compiled in the releases should be named as such, not `darwin`. `darwin` is not widely known outside of the overly tech savy. Even the `oc` client tools refer to `macos`

**Comment by wking** [comment]
`darwin` come [from Go][1].  If folks want to put a prettier name on it, I'm fine with a frontend web page like [Terraform's][2] with the logo and `macOS` which links to `terraform_0.11.10_darwin_amd64`.  But I'd rather not maintain our own synonyms for Go's OS labels in the code here.

Also somewhat related to release-executable filenames is #807.

[1]: https://golang.org/doc/install/source#environment
[2]: https://www.terraform.io/downloads.html

**Comment by wgordon17** [comment]
Huh...I didn't even notice that Terraform still used `darwin` in the name of their download. I think there should be a frontend available...but probably not important this early in the game
