### ISSUE TITLE
Add supported versions for Go, OpenShift in build dependencies page

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/installer#824]
# Version

```console
$ openshift-install version
<your output here>
$ ~/.terraform.d/plugins/terraform-provider-libvirt -version  # only needed if you're using libvirt
<your output here>
```

# Platform (aws|libvirt|openstack):

Anyplatform

# What happened?

As of now, we don't have versions of golang and OpenShift in build dependencies page. Depending on version of OpenShift(kube), the golang version changes, it'd be better to have those dependencies captured.

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by crawford** [comment]
This should be covered by https://github.com/openshift/installer/blob/master/docs/dev/dependencies.md.
/close
