### ISSUE TITLE
WARNING Unrecognized AWS region "", defaulting to us-east-1

### ISSUE THREAD

**Issue by wgordon17** [openshift/installer#828]
When installing, without providing a default region in the `.aws/credentials` file, the $SUBJECT is displayed. This can be concerning for users, and may make them think they've done something wrong. Especially on an easily recognizable string like `""`, you should just suppress the warning

**Comment by wking** [comment]
> Especially on an easily recognizable string like `""`, you should just suppress the warning

In flight with #864.
