### ISSUE TITLE
Terraform: AWS account Pending Verification

### ISSUE THREAD

**Issue by wgordon17** [openshift/installer#829]
# Version

```console
$ openshift-install version
bin/openshift-install v0.5.0-master-36-gb4f5ceb6bfde8d3dc0e29f708e0494488ea37ee0
Terraform v0.11.10
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

Terraform eventually failed with an error regarding my AWS account Pending Verification. It appears that Terraform already initiated the necessary steps to verify my account, and after waiting, the install completed successfully. **But**, this left the install in a weird state where I had to destroy my non-existent cluster, and caused all sorts of oddities

# What you expected to happen?

The installer should check if the aws account is verified at the beginning of the process to prevent being in a weird state in the middle of an install

# How to reproduce it (as minimally and precisely as possible)?

I'm pretty sure just create a brand new aws account, and then try the installer

**Comment by wgordon17** [comment]
Sorry, I don't have the logs...but I can try creating another AWS account to test with.

Sorry for the confusion. After getting the "AWS account Pending Verification" errors, terraform was in a weird state that prevented the usage of `openshift-install destroy cluster`. But after cleaning it up manually...I waited about an hour then tried `openshift-install create cluster` again, and the install worked...meaning that Terraform did the right thing with verifying my account, but it would be nice if `openshift-install` caught and warned about this issue before Terraform took off trying to create all the resources

I'm gonna test again and will try to provide as many logs as I can!

**Comment by wgordon17** [comment]
Full `.openshift_install.log` including `create cluster` and `destroy cluster` logs. Turns out `destroy cluster` worked without issue this time, so that's good 👍 

The provisioning errors start at https://gist.github.com/wgordon17/7e02bdd96d6845ef557f6f66a1a12040#file-openshift_install-log-L1998

**Comment by wking** [comment]
So the error was:

```
 * module.masters.aws_instance.master[2]: 1 error occurred:
 * aws_instance.master.2: Error launching source instance: PendingVerification: Your account is currently being verified. Verification normally takes less than 2 hours. Until your account is verified, you may not be able to launch additional instances or create additional volumes. If you are still receiving this message after more than 2 hours, please let us know by writing to aws-verification@amazon.com. We appreciate your patience.
 status code: 400, request id: 9cb4b9ad-343c-4834-af2a-58099bfd1c48
```

I've looked around briefly, but haven't found an API to pre-check that yet.

**Comment by wgordon17** [comment]
I'm wondering if getting the account `max-instances` might be valuable? https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAccountAttributes.html

I'm also attempting to post an AWS forum question (apparently have to wait for my Forum account to also activate because it's too new 😆)

**Comment by wking** [comment]
To investigate the `max-instances` idea, can you run:

```console
$ aws ec2 describe-account-attributes --query "AccountAttributes[?AttributeName == 'max-instances'].AttributeValues" --output text
```

the next time you create an account?  I don't have access to any account where it's less than 200 (although the example in the docs you link has it at 20).  Based on your `master[2]` failure, the limit for you at that time was two or three (depending on whether the bootstrap instance had already been created or not).

**Comment by wgordon17** [comment]
So, on a brand new account, running that gives me:

    An error occurred (OptInRequired) when calling the DescribeAccountAttributes operation: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.

It's not a great error message, but visiting https://us-east-2.console.aws.amazon.com/ec2 in the browser was enough to make the command complete successfully with a value of `20`.

[AWS](https://aws.amazon.com/premiumsupport/knowledge-center/error-access-service/) also recommends going to https://aws-portal.amazon.com/gp/aws/developer/registration/index.html to finish the sign up process, but in my case, it didn't do anything. Not like going to https://us-east-2.console.aws.amazon.com/ec2 did. (Obviously the AWS link can just be any region link, but since the installer know the region ahead of time, it should be easy to provide the correct link).

Damn....so even with getting a value of `20` from the API, I'm still getting the `PendingVerification` error message.

**Comment by eparis** [comment]
I'm sorry to say that I don't think the installer is going to do much to make sure that the AWS account has completed registration. Thankfully the inability to destroy/recreate has been largely resolved. So I am going to close this issue and do apologize for the inconvenience.
