### ISSUE TITLE
openshift-install cluster delete fails DependencyViolation: resource sg-0d577e26d576aaXXX has a dependent object

### ISSUE THREAD

**Issue by jeremyeder** [openshift/installer#836]
# Version

```
$ openshift-install version
# ./openshift-install-linux-amd64 version
./openshift-install-linux-amd64 v0.5.0
Terraform v0.11.10
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

Installs are failing.  Deletes are failing.  I think installs are failing because deletes are not totally cleaning things up.

# What you expected to happen?

Install to work.

# How to reproduce it (as minimally and precisely as possible)?

I believe it was caused by creating a cluster and then creating again before deleting?  Don't have a clear reproducer at the moment.

**Comment by jeremyeder** [comment]
Full cluster delete logs:
https://gist.github.com/jeremyeder/783af93542440d5f2cc3a6ddde8ce912

**Comment by jeremyeder** [comment]
![image](https://user-images.githubusercontent.com/1919640/49672003-b9abf600-fa37-11e8-9eae-213448cd6b18.png)

**Comment by jeremyeder** [comment]
Using a different OPENSHIFT_INSTALL_CLUSTER_NAME and --dir let me at least unblock.

**Comment by crawford** [comment]
Is this still an issue with the latest installer?

**Comment by jeremyeder** [comment]
At least I haven't seen this in a few weeks.

**Comment by cuppett** [comment]
I've been able to create/delete the same cluster (name, account, region) multiple times since the break. The simple case is okay. I didn't deploy any apps though, so I don't know about user-provided LoadBalancer services and how well those are lifecycled.

**Comment by eparis** [comment]
ELBs create by service type loadbalancer are no tagged appropriately and will be cleaned up by destroy.
