### ISSUE TITLE
How to customize openshift-install and remove tags for security groups

### ISSUE THREAD

**Issue by bd-bord1** [openshift/installer#8426]
openshift-install version 4.13.11

Hi, 
I have been trying to deploy an openshift cluster on Open Telekom Cloud(Openstack). The networking infrastructure included subnets has been already provisioned on Open Telekom Cloud. 

Our error is failed to add tags to security groups for master and worker nodes as Open Telekom Cloud doesn't have this API and they don't plan to implement it in the future.

This problem doesn't allow us to install OCP on this cloud and am wondering if there is any workaround to skip adding tags to security groups or customize the terraform files in openshift-installer.

I would be grateful for any advice or insight. 
Thank you and best regards,
Doinita 

```
Error: Error setting tags on openstack_networking_secgroup_v2 285be096-c8ac-4b2f-9ae3-22052e95adb6: Resource not found: [PUT https://vpc.eu-de.otc.t-systems.com/v2.0/security-groups/285be096-c8ac-4b2f-9ae3-22052e95adb6/tags], error message: {"error_msg":"The API does not exist: method PUT not found","error_code":"APIGW.0101","request_id":"93674cfb39b0f5b086dd6eb6b14fcb1f"} 
ERROR                                              
ERROR                                              
ERROR   with openstack_networking_secgroup_v2.master, 
ERROR   on sg-master.tf line 1, in resource "openstack_networking_secgroup_v2" "master": 
ERROR    1: resource "openstack_networking_secgroup_v2" "master" { 
```

**Comment by pierreprinetti** [comment]
@bd-bord1 If your OpenStack cloud doesn't meet certain requirements, like tagging for example, you can choose to install OpenShift by creating the required OpenStack resources yourself, and then running the Installer to complete the installation. This is what we call "User Provider Infrastructure" (UPI) and it is documented here: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/installing/installing-on-openstack#choosing-an-method-to-install-ocp-on-openstack-user-provisioned

Note that a cluster installed that way has limited support for OpenStack features, and for example won't manage existing or additional machines by default.
