### ISSUE TITLE
Unclear how to restart a fresh "bin/openshift-install install cluster"

### ISSUE THREAD

**Issue by rwsu** [openshift/installer#845]
# Version

```console
$ openshift-install version
bin/openshift-install v0.5.0-master-47-gf7d6d2923a7979344fcac33293084051cecc8aab-dirty
Terraform v0.11.10
$ ~/.terraform.d/plugins/terraform-provider-libvirt -version  # only needed if you're using libvirt
Compiled against library: libvirt 4.1.0
Using library: libvirt 4.1.0
Running hypervisor: QEMU 2.11.2
Running against daemon: 4.1.0
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

My first install failed with:
````
WARNING Failed to connect events watcher: Get https://demo-api.localdomain:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp: lookup demo-api.localdomain on 127.0.0.1:53: no such host 
WARNING Failed to connect events watcher: Get https://demo-api.localdomain:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp: lookup demo-api.localdomain on 127.0.0.1:53: no such host 
WARNING Failed to connect events watcher: Get https://demo-api.localdomain:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp: lookup demo-api.localdomain on 127.0.0.1:53: no such host 
WARNING Failed to connect events watcher: Get https://demo-api.localdomain:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp: lookup demo-api.localdomain on 127.0.0.1:53: no such host 
FATAL Error executing openshift-install: waiting for bootstrap-complete: timed out waiting for the condition 
````
Then I destroyed the cluster:
````
[root@puppy installer]# bin/openshift-install destroy cluster
INFO Deleted domain                                domain=demo-master-0
INFO Deleted domain                                domain=demo-bootstrap
INFO Deleted network                               network=demo
INFO Deleted volume                                volume=demo-bootstrap
INFO Deleted volume                                volume=demo-master.ign
INFO Deleted volume                                volume=demo-bootstrap.ign
INFO Deleted volume                                volume=demo-base
INFO Deleted volume                                volume=demo-master-0
````
When try to rerun the installer to create the cluster, it doesn't prompt me and reuses what I had entered before. It is not clear how to reset the installer so that it prompts me for domain, install type, etc..

# What you expected to happen?

There should be an option or instructions on how to reset the installer or its state so it starts fresh.

# How to reproduce it (as minimally and precisely as possible)?

 bin/openshift-install create cluster
 bin/openshift-install destroy cluster
 bin/openshift-install create cluster

**Comment by ravisantoshgudimetla** [comment]
I am noticing this too on AWS. FWIW, I have created cluster with other another name and that failed too. I am trying other combinations, like removing .openshift_install_state.json. Will post the status here if anything works fine.

**Comment by akrzos** [comment]
I also had to remove `.openshift_install_state.json` in order to get subsequent installs on AWS to occur.

**Comment by wking** [comment]
There are some cleanup suggestions [here][1].  Sometimes recycling state from a previous cluster is [a good thing][2], and sometimes it is confusing.  Some more on this [here][3], in #635, etc., so obviously there's still room for improving the UX here.

[1]: https://github.com/openshift/installer/blame/v0.6.0/README.md#L52-L54
[2]: https://github.com/openshift/installer/blob/v0.6.0/docs/user/overview.md#multiple-invocations
[3]: https://github.com/openshift/installer/pull/547#issuecomment-435565108

**Comment by wgordon17** [comment]
I know there's a `--dir` option which installs everything into a self-contained directory. What if the "default" is to use a directory named after the cluster? You can still override with `--dir`, but I think this would at least make it easier to separate installs. And then commands like `openshift-install destroy cluster` could look in the current directory, or fail with an error message, something like `cluster not found in current directory, use --dir to specify the cluster directory`

**Comment by wking** [comment]
> What if the "default" is to use a directory named after the cluster? You can still override with `--dir`, but I think this would at least make it easier to separate installs.

This has been [suggested before][1], and I still feel like [this][2].  In fact, lets close this issue as a dup of #522.  Please post a comment here if you feel like there's enough space between to two to be worth separate issues.

/close

[1]: https://github.com/openshift/installer/issues/522#issuecomment-434976379
[2]: https://github.com/openshift/installer/issues/522#issuecomment-435011379
