### ISSUE TITLE
Drop changes.md and start a new change log after our next release?

### ISSUE THREAD

**Issue by wking** [openshift/installer#86]
A lot of changes have been made since the last time `changes.md` was touched:

```console
$ git log -1 changes.md | cat
commit 8f1a763ee32512980bd0613b2c0d54f7a227daed
Author: sudhaponnaganti <sudha.ponnaganti@coreos.com>
Date:   Tue Sep 12 12:29:05 2017 -0700

    Update changes.md
$ git log --oneline --no-merges 8f1a763e..HEAD | wc -l
1251
```

Given the Tectonic -> OpenShift rebranding and significant overhauling, can we scrap `changes.md` and start a fresh change log when we cut our first OpenShift-branded release?  I'm certainly not excited about reviewing that many commits to work up detailed change notes ;).

On the other hand, it may be useful to have someone with a good understanding of both the Tectonic 1.7.3 installer and the new OpenShift installer who can write migration notes to help previous Tectonic-installer users across the transition.  In that case, maybe we'd keep the existing `changes.md`.

**Comment by crawford** [comment]
I'm in favor of removing the changes.md and starting anew.
