### ISSUE TITLE
OpenStack: clouds.yaml in current directory does not work

### ISSUE THREAD

**Issue by akostadinov** [openshift/installer#860]
# Version

```console
$ openshift-install version
openshift-install 485b1bec14c39e954c70b1a83cee706ef3d5edde-dirty
Terraform v0.11.8
```

# Platform (openstack):

`clouds.yaml` is searched in different places. According to `pkg/asset/installconfig/openstack/openstack.go`:

1. OS_CLIENT_CONFIG_FILE
1. Current directory.
1. unix-specific user_config_dir (~/.config/openstack/clouds.yaml)
1. unix-specific site_config_dir (/etc/openstack/clouds.yaml)

# What happened?

When `clouds.yaml` is in current directory, installer accepts it and goes ahead. But then Terraform fails with

```console
DEBUG * provider.ignition: version = "~> 1.0"      
DEBUG                                              
DEBUG Terraform has been successfully initialized! 
DEBUG                                              
DEBUG You may now begin working with Terraform. Try running "terraform plan" to see 
DEBUG any changes that are required for your infrastructure. All Terraform commands 
DEBUG should now work.                             
DEBUG                                              
DEBUG If you ever set or change modules or backend configuration for Terraform, 
DEBUG rerun this command to reinitialize your working directory. If you forget, other 
DEBUG commands will detect it and remind you to do so if necessary. 
DEBUG Running &exec.Cmd{Path:"/usr/local/bin/terraform", Args:[]string{"/usr/local/bin/terraform", "apply", "-auto-approve", "-input=false", "-no-color", "-state=terraform.tfstate"}, Env:[]string(nil), Dir:"/tmp/openshift-install-115028963", Stdin:io.Reader(nil), Stdout:(*lineprinter.LinePrinter)(0xc420384280), Stderr:(*bytes.Buffer)(0xc420038fc0), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)}... 
ERROR Failed to read tfstate: open /tmp/openshift-install-115028963/terraform.tfstate: no such file or directory 
ERROR Error: Error refreshing state: 1 error(s) occurred:

* provider.openstack: unable to load clouds.yaml: no clouds.yaml file found 
FATAL Error executing openshift-install: failed to fetch Cluster: failed to generate asset "Cluster": failed to run terraform: failed to execute Terraform: exit status 1 
```

# What you expected to happen?

Installation should work.

# How to reproduce it (as minimally and precisely as possible)?

1. download `clouds.yaml` to current directory
1. edit `clouds.yaml` and enter password into it (by default it is iwthout password)
1. openshift-installer create cluster --dir install/

**Comment by wking** [comment]
CC @flaper87, @russellb

**Comment by russellb** [comment]
Thanks for the report!  will look into this.

**Comment by akostadinov** [comment]
I think issue is obvious - `terraform` is run in `Dir:"/tmp/openshift-install-115028963"`. So clouds.yaml is no longer in current dir (where installer is run from).

I think it makes sense for installer to set env variable `OS_CLIENT_CONFIG_FILE` when executing `terraform` to the detected location of `clouds.yaml`. This will also allow installer to **ask** user for `clouds.yaml` location instead of failing when it is not found among the expected locations.

**Comment by pierreprinetti** [comment]
Hi @akostadinov,
The issue looks fixed in the current `master`: I could install a cluster after moving the `clouds.yaml` to the working directory.

Are you still experiencing this problem?

**Comment by akostadinov** [comment]
I don't but since OpenStack not yet supported, I didn't try since the time of reporting. If you don't see this problem anymore, then I guess it is fixed.
