### ISSUE TITLE
Install should meet all prerequites or dependencies for the user. 

### ISSUE THREAD

**Issue by sferich888** [openshift/installer#874]
# Version

```console
$ openshift-install version
0.6.0
```

# Platform (aws|libvirt|openstack): 

All - but in this case OpenStack (as an example). 

# What happened?

```
ERROR Error: Error refreshing state: 2 errors occurred: 
ERROR   * module.bootstrap.data.openstack_compute_flavor_v2.bootstrap_flavor: 1 error occurred: 
ERROR   * module.bootstrap.data.openstack_compute_flavor_v2.bootstrap_flavor: data.openstack_compute_flavor_v2.bootstrap_flavor: Your query returned no results. Please change your search criteria and try again. 
ERROR                                              
ERROR                                              
ERROR 	* module.masters.data.openstack_compute_flavor_v2.masters_flavor: 1 error occurred: 
ERROR 	* module.masters.data.openstack_compute_flavor_v2.masters_flavor: data.openstack_compute_flavor_v2.masters_flavor: Your query returned no results. Please change your search criteria and try again. 
```

# What you expected to happen?

The install should meet all of the pre-requisites it needs and not error with issues like this. 
Deploying or Creating flavors in an OpenStack environment is something terraform can do: https://www.terraform.io/docs/providers/openstack/r/compute_flavor_v2.html 

# How to reproduce it (as minimally and precisely as possible)?

Try to deploy to OpenStack that does not have the flavors *bootstrap_flavor* or *masters_flavor* defined. 

# Anything else we need to know?

With a great lack of [documentation](https://github.com/openshift/installer/issues/855) in this space, users will likely never complete an install without significant heartache an pain, in trying to deploy something over an over again and again (reminds me of the openshift-ansible installer). 

# References

https://github.com/openshift/installer/issues/867 should also be connected to this; as any issues that the installer can't create or resolve for a user need to be called out by this pre-requisite check.

**Comment by abhinavdahiya** [comment]
Closing duplicate of https://github.com/openshift/installer/issues/867
