### ISSUE TITLE
“openshift-install” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by c3d** [openshift/installer#8785]
It looks like #2722 is back, but this time for a binary downloaded from console.redhat.com

# Workaround

1. Right-click on binary file in Finder
2. Select "Open"
3. Finder complains that this is an unsafe file, agree to proceed
4. Terminal launches, but fails (presumably because wrong command-line options)
5. After that, launching from original terminal works.

# Version

```console
$ openshift-install version
Not available: program does not run
MD5 (openshift-install) = c5459d1d9ac58613152b8fddcb450f36
```

After applying workaround:

```console
$ openshift-install version
./openshift-install 4.16.3
built from commit e1f9f057ce87c1a4a5f3c268812fa4c9dc003cb7
release image quay.io/openshift-release-dev/ocp-release@sha256:0ddd267a78d7a03d033a92218129a01a5471f5b3372db7312e2c39e7ba85611a
release architecture arm64
```

Also seen with pre-release:

```
./openshift-install 4.17.0-ec.2
built from commit 54e81ef067d432cc41a3333765b2f28ad34bbbea
release image quay.io/openshift-release-dev/ocp-release@sha256:32bde146b5875c70ebd72a2e4f7c319a6a8fb3c93acd3e817d152f26371e7198
WARNING Release Image Architecture not detected. Release Image Architecture is unknown 
release architecture unknown
default architecture arm64
```

# Platform:

macOS ARM (M1), Sonoma 14.5

# What happened?

Dowloaded macOS installer from https://console.redhat.com/openshift/install/azure/multi/installer-provisioned, selected macOS aarch64, untarred the file.

Ran `./openshift-install create cluster`

The binary fails to run (incorrectly signed?), instead I get the message:
 **“openshift-install” can’t be opened because Apple cannot check it for malicious software.**

<img width="251" alt="image" src="https://github.com/user-attachments/assets/978f0d5b-81ec-4dd0-b9e1-54f9da74a3f7">

# What you expected to happen?

The installer should run without having to go through hoops 

# How to reproduce it (as minimally and precisely as possible)?

1. Connect to https://console.redhat.com/openshift/install/azure/multi/installer-provisioned and login
6. Download the macOS / ARM version
7. Expand the content of the tar file
8. From terminal, run `./openshift-install`

# Anything else we need to know?

As a Red Hatter, it's possible that I'm not downloading the public version?

# References

This looks like a return of #2722. I did not see another open issue that matches (sorry if I missed it).

**Comment by c3d** [comment]
Same problem with pre-release version downloaded from https://console.redhat.com/openshift/install/multi/pre-release

```
MD5 (openshift-install) = 5a3161dc2e6ebcaabc3593eb9c884081
```

**Comment by c3d** [comment]
Workaround to make it work:
- Right click on the binary in the Finder, select `Open`
- There is a warning asking if you want to proceed. Agree.
- A terminal window opens, and closes quickly because the correct command-line options are not given
- Running from the command-line after that works.

**Comment by r4f4** [comment]
@c3d does that also happen if you use the single-arch payload instead of multi? So the binary from https://console.redhat.com/openshift/install/azure/arm/installer-provisioned

**Comment by c3d** [comment]
> @c3d does that also happen if you use the single-arch payload instead of multi? So the binary from https://console.redhat.com/openshift/install/azure/arm/installer-provisioned

Yes. I tried both the aarch64 and the x86-64 versions (under Rosetta). The x86 version gives me a slightly different message, but same kind of problem.

“openshift-install” cannot be opened because the developer cannot be verified.

<img width="256" alt="image" src="https://github.com/user-attachments/assets/e7266f2f-f193-42d0-8c54-8481a8a9f56e">

aarch64 I tested: MD5 (./openshift-install) = 67cfd992c0cfb47415c5d819df75cd0e
x86 I tested: MD5 (./openshift-install) = 4ad13b686b8aaf68d4222c1fe8b91d10

**Comment by r4f4** [comment]
Using the Mac binary obtained from the [Customer Portal](https://access.redhat.com) should solve the problem. We have opened a task to investigate improvements to the binary in the developer portal, but since that's out of the scope from the Installer team, I'm going to close this issue.

/close

**Comment by McMac** [comment]
> Using the Mac binary obtained from the [Customer Portal](https://access.redhat.com) should solve the problem. We have opened a task to investigate improvements to the binary in the developer portal, but since that's out of the scope from the Installer team, I'm going to close this issue.
> 
> /close

Could you be any more generic? Have you looked at the customer portal? Where would I find "the Mac binary"?!?

**Comment by r4f4** [comment]
@McMac "Downloads -> Cloud Computing / Red Hat Openshift Container Platform -> OpenShift v4.17.1 macOS Installer". If you are having trouble, please contact support.

**Comment by c3d** [comment]
Please note that macOS Sequoia 15.1 has disabled the execution of unsigned binaries altogether, so the workaround I gave above using the Finder no longer works. I will update the description.
