### ISSUE TITLE
S3 buckets may be created in other regions

### ISSUE THREAD

**Issue by vrutkovs** [openshift/installer#881]
See teardown logs for some installer PRs, e.g. https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_installer/861/pull-ci-openshift-installer-master-e2e-aws/2219/artifacts/e2e-aws/container-logs/
```
time="2018-12-12T11:48:04Z" level=debug msg="error getting tags for bucket terraform-20181206052653207700000001: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'\n\tstatus code: 400, request id: C19FE5751CD377FE, host id: TQVaCRQWJLM2n6aUebh1WnRXJEswR/frJdhlZb3eb6olxiiUqEyTJdHzucFmKLD02zDe1NeZ+DI=, skipping..."
```

Seems `cluster destroy` expects the bucket to be in `us-east-1`, but it was created in `us-west-2` for some reason

**Comment by dgoodwin** [comment]
CC @joelddiaz

**Comment by joelddiaz** [comment]
I replied in slack, but here was the response for posterity

@dgoodwin @vrutkovs @crawford so IIRC you can see S3 buckets in different regions than what your aws session is configured for, and trying to perform operations on them (when your aws config says us-east-1 and the bucket is in not-us-east-1) you get these messages
so we just ignore these errors in the uninstaller as of this PR . so we just ignore those s3 buckets as of this PR https://github.com/openshift/hive/pull/14

**Comment by abhinavdahiya** [comment]
> I replied in slack, but here was the response for posterity
> 
> @dgoodwin @vrutkovs @crawford so IIRC you can see S3 buckets in different regions than what your aws session is configured for, and trying to perform operations on them (when your aws config says us-east-1 and the bucket is in not-us-east-1) you get these messages
> so we just ignore these errors in the uninstaller as of this PR . so we just ignore those s3 buckets as of this PR [openshift/hive#14](https://github.com/openshift/hive/pull/14)

thanks @joelddiaz 

/close
