### ISSUE TITLE
Failed to create cluster: failed to apply using terraform

### ISSUE THREAD

**Issue by jatanmalde** [openshift/installer#883]
# Version

```console
$ openshift-install version
[jmalde@myplace ~]$ ./openshift-install version
./openshift-install v0.6.0
Terraform v0.11.10
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

After adding the aws configuration, openshift-install create cluster command fails at tfstate file.
```console
[jmalde@myplace ~]$ ./openshift-install create cluster
INFO Consuming "Kubeconfig Admin" from target directory 
INFO Creating cluster...                          
ERROR                                              
ERROR Error: Error refreshing state: 1 error occurred: 
ERROR 	* module.dns.data.aws_route53_zone.base: 1 error occurred: 
ERROR 	* module.dns.data.aws_route53_zone.base: data.aws_route53_zone.base: no matching Route53Zone found 
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR                                              
ERROR Failed to read tfstate: open /tmp/openshift-install-058568585/terraform.tfstate: no such file or directory 
FATAL Error executing openshift-install: failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using terraform 
```

# What you expected to happen?

Expected to get the openshift cluster created

# How to reproduce it (as minimally and precisely as possible)?

```console
1. Configure awscli initially and then add the credentials 
2. Download the openshift-install binary and run the command 
$ ./openshift-install create cluster
```

# Anything else we need to know?

I followed all the steps listed in  try.openshift.com except for the domain and hence the first error seems to be expected but the second error is difficult to understand. These are fresh aws credentials.

# References

- enter text here.

**Comment by crawford** [comment]
> module.dns.data.aws_route53_zone.base: data.aws_route53_zone.base: no matching Route53Zone found 

This is the real error. This indicates that you have tried to use a base domain for which there exists no existing zone.

**Comment by jatanmalde** [comment]
> > module.dns.data.aws_route53_zone.base: data.aws_route53_zone.base: no matching Route53Zone found
> 
> This is the real error. This indicates that you have tried to use a base domain for which there exists no existing zone.

Yes @crawford , I am working to get that fixed by having a domain registered and soon should be able get rid of that error.

I probably do not think it would be related to the issue I filed, but I am happy to be corrected. 

Thanks again.

**Comment by eparis** [comment]
The error is that you set BaseDomain to a domain that you have not delegated to route53. This is user error, not a bug. Once you have a DNS domain in route53 and use that as the BaseDomain you will not get this error.

**Comment by jhadvig** [comment]
> Once you have a DNS domain in route53 and use that as the BaseDomain you will not get this error.

@eparis can you please provide some instruction on how to do that ?
