### ISSUE TITLE
Permission errors deleting S3 buckets

### ISSUE THREAD

**Issue by coverprice** [openshift/installer#887]
# Version

```console
bin/openshift-install v0.5.0-master-81-g717e2a035665e4c272c34d5bebfb6400bd7dc29c
Terraform v0.11.10
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?
During teardown, I saw hundreds of S3 errors similar to this:
```
DEBUG error getting tags for bucket terraform-20181212191843343200000001: BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
        status code: 301, request id: , host id: , skipping...
```

# What you expected to happen?

To see no permission errors for getting tags.

# How to reproduce it (as minimally and precisely as possible)?

I just stood up a vanilla cluster and after it came up I immediately destroyed it.

```console
source openshift_env.sh
bin/openshift-install create cluster --dir ./my_cluster --log-level=debug
bin/openshift-install destroy cluster --dir ./my_cluster --log-level=debug
```

# Anything else we need to know?

May be related to #881 but I'm not sure.

**Comment by wking** [comment]
Yeah, I think this is the same thing [described here][1], and that while these may be interesting debug-level logs, it's not something that you should have to worry about.  Feel free to re-open if that's not convincing ;).

/close

[1]: https://github.com/openshift/installer/issues/881#issuecomment-446631789
