### ISSUE TITLE
Issues setting OPENSHIFT_INSTALL_PULL_SECRET variable

### ISSUE THREAD

**Issue by jobbler** [openshift/installer#888]
# Version

```console
$ openshift-install version
bin/openshift-install v0.5.0-master-89-g814fbf7c1433aaf4c304c17a6f57a9bed1b08444
Terraform v0.11.10
```

# Platform (aws|libvirt|openstack):

aws
# What happened?

install fails when setting the OPENSHIFT_INSTALL_PULL_SECRET environment variable for install. Works fine when using OPENSHIFT_INSTALL_PULL_SECRET_PATH.

# How to reproduce it (as minimally and precisely as possible)?

Set the variable and execute a create. The installation fails.
export OPENSHIFT_INSTALL_PULL_SECRET='{ "auths": { "quay.io": { "auth": "fdfgggsfgfgfgsfgggsggfggsgdfgg", "email": "" } } }'

# Anything else we need to know?

If you set the variable as a here-doc, installation works.

export OPENSHIFT_INSTALL_PULL_SECRET=$( cat <<EOF
{ "auths": { "quay.io": { "auth": "fdfgggsfgfgfgsfgggsggfggsgdfgg", "email": "" } } }'
EOF
)

This should be included in the documentation to prevent others from having the same issue.

**Comment by crawford** [comment]
We are removing environment variables altogether (https://github.com/openshift/installer/pull/861). Once that merges, I'm going to close this out since it will no longer be applicable.

**Comment by wking** [comment]
You should transition to supplying an install-config instead (as documented in #861).

**Comment by crawford** [comment]
https://github.com/openshift/installer/pull/861 has merged.

/close
