### ISSUE TITLE
No validation of config in `create ignition-configs`

### ISSUE THREAD

**Issue by vrutkovs** [openshift/installer#910]
If the user brings in an incorrect install-config (e.g. `metadata.name` is empty or `baseDomain` is empty) and runs `create ignition-configs` the config is not validated. This would make bootstrap node breaks at some point, but this could be easily prevented by validating the configs first

**Comment by eparis** [comment]
@staebler

**Comment by staebler** [comment]
This validation is included in https://github.com/openshift/installer/pull/711.
