### ISSUE TITLE
RFE: preconfigure masters with KUBECONFIG

### ISSUE THREAD

**Issue by mfojtik** [openshift/installer#929]
It would be nice if all masters automatically set the `KUBECONFIG` env var pointing to the admin kubeconfig, so when an admin ssh into master node (for debugging/etc.) he don't need to search for admin.kubeconfig file, but `kubectl`/`oc` works automatically for him.

**Comment by abhinavdahiya** [comment]
The installer give the cluster-admin `admin` kubeconfig on installation and IMO I don't think it is too much to ask the admn to scp that kubeconfig on the master machine to keep access.

**Comment by abhinavdahiya** [comment]
The installer give the cluster-admin `admin` kubeconfig on installation and IMO I don't think it is too much to ask the admn to scp that kubeconfig on the master machine to keep access.

**Comment by wking** [comment]
I agree with @abhinavdahiya.  I'd rather not be leaving high-power kubeconfigs around (although on the masters you probably have the power to look into etcd anyway), where they're one more thing to keep track of.  And I'd rather not spend a lot of effort on the "`ssh` into machines and do things" use case.  Is there a reason you can't just run your `kubectl` and `oc` from your install host?

**Comment by akostadinov** [comment]
If you have an automated (non-local) system it is actually rather hard to do thing properly if admin kubeconfig is not retrievable from master. In an automated system you'd have to archive that kubeconfig somehow, then know relationship between cluster and automated build, then also make sure unauthorized people cannot download it (e.g. people with only read access to builds).

It is much preferable if all cluster information can be discovered from master also for purposes of removing old clusters without searching for artifacts related to that particular cluster.

**Comment by wking** [comment]
> If you have an automated (non-local) system it is actually rather hard to do thing properly if admin kubeconfig is not retrievable from master.

So have your automated, non-local system `scp` whatever assets you need up to the cluster?

> It is much preferable if all cluster information can be discovered from master also for purposes of removing old clusters without searching for artifacts related to that particular cluster.

We don't load-balance port 22.  So this is "I'll be able to look up a master IP for this cluster to SSH in, but will not be able to look up anything else about the cluster"?  Why are IPs especially available?

Also  teardown using resources stored the cluster will usually be fine, but doesn't cover cases where the cluster died before the place you where hoping to store those resources got created.  But we should probably continue *this* part of the discussion in #746.

**Comment by akostadinov** [comment]
You can discover IPs in test run logs, chats, looking at your cloud account, etc. Then everything is in one place.

SCP is surely possible if we know where to SCP. Is there information about all VMs created stored in install-dir after install? This can greatly help if we can have external/internal IPs of provisioned machines somewhere in install-dir as I don't know how we discover these without looking at cloud account.

**Comment by mfojtik** [comment]
I don't think that leaving cluster admin kubeconfig file on master nodes poses any security risk. In fact we already leaving it there in static pod manifests for kube apiserver and controller manager. However that path is pretty hard to discover and it changes with revision (and the path will be also subject of pruning old revisions...).

I thought that will be mostly UIX/convenience thing for debugging problems on masters. In case I need to SSH to investigate problems on master nodes, first thing I do is exporting `KUBECONFIG` so `oc` will work with the current cluster. Automating this for 'advanced' users will make the experience better I think. Although I dunno how complicated it will be to modify host environment (/etc/profile/...) so if this will be significant effort, I can live without it (as there are more important issues right now to solve).

**Comment by xingxingxia** [comment]
Thanks for your discussion. As the [issue raiser](https://bugzilla.redhat.com/show_bug.cgi?id=1660273), I agree `automating this for 'advanced' users will make the experience much better`. And also agree `if this will be significant effort, I can live without it` either

**Comment by cgwalters** [comment]
One thing I'd say is we could at least link to some sort of docs in the `/etc/motd` or something when ssh-ing into the node.  Honestly I actually didn't even think about `scp`'ing the `kubeconfig` over; it's obvious when one thinks about it, but not everyone will.

**Comment by crawford** [comment]
I agree with @abhinavdahiya and @wking above. While it may not be a security concern to leave root credentials laying around on the master, rotating those credentials _is_ a problem. We (as an organization) have no mechanism for managing those files, nor do we have a plan to do so. Additionally, I don't buy the argument that archiving this information is too much of a hurdle for customers. At the end of the day, they will always need to archive _something_. Even if the kubeconfigs are on the masters, customers still need to archive their credentials to that cluster. If they can keep track of those credentials, I believe they can also keep track of this.

I agree that it would be a nice debugging UX, but given my concern around the unmanaged nature of these credentials, I'm going to close this out. We can revisit this if there is a good solution for management. Thanks for the request.

/close

**Comment by akostadinov** [comment]
can we have a simple command that one can execute on master to have kubeconfig regenerated to `/root/.kube/config` on demand? Thus automatic rotation would not be needed and still make things easy for adiministrators and QE.

**Comment by wking** [comment]
> can we have a simple command that one can execute on master...

This sounds reasonable to me, although I don't know how you'd implement it (hitting etcd directly?).  Patches welcome :)
