### ISSUE TITLE
is v0.7 installer pinned to specific openshift release ?

### ISSUE THREAD

**Issue by DanyC97** [openshift/installer#930]
# Version

```console
 # ./openshift-install-linux-amd64 version
./openshift-install-linux-amd64 v0.7.0
# sha256sum openshift-install-linux-amd64 
879d1966b229a4723520b0522e9bd79308071c8cfae2b13e14800948c45ea73f  openshift-install-linux-amd64
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

Trying to deploy a cluster and while scanning the logs i've noticed the below in the boostrap's journalctl output

```
1-129 bootkube.sh[4434]: Trying to pull quay.io/openshift-release-dev/ocp-release:4.0.0-6...Getting image source signatures
Dec 17 18:15:58 ip-10-0-1-129 bootkube.sh[4434]: Copying blob sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17
Dec 17 18:16:03 ip-10-0-1-129 bootkube.sh[4434]: [503B blob data]
Dec 17 18:16:03 ip-10-0-1-129 bootkube.sh[4434]: Copying blob sha256:9afeca73426ec14b331e7968e69e8514225c232ecf782a31c08935c6eebd063c
Dec 17 18:16:05 ip-10-0-1-129 bootkube.sh[4434]: [119B blob data]
Dec 17 18:16:05 ip-10-0-1-129 bootkube.sh[4434]: Copying blob sha256:8c631e03cd56d716a5966b766ff589b7702b7b643cc41a841f4c84f58fa0c4f6
Dec 17 18:16:08 ip-10-0-1-129 bootkube.sh[4434]: [301B blob data]
Dec 17 18:16:08 ip-10-0-1-129 bootkube.sh[4434]: Copying blob sha256:21dcbb91f69fca7abce98841c6e654cf9c74ce12b17f8f8441d1b1b97ed4a2c3
Dec 17 18:16:09 ip-10-0-1-129 bootkube.sh[4434]: [67B blob data]
Dec 17 18:16:09 ip-10-0-1-129 bootkube.sh[4434]: Writing manifest to image destination
Dec 17 18:16:09 ip-10-0-1-129 bootkube.sh[4434]: Storing signatures
Dec 17 18:16:16 ip-10-0-1-129 bootkube.sh[4434]: 5d537bf661a70aba1fb621e759c56eecca06b26de32698f9ef5fa09c2ba8b274
Dec 17 18:16:27 ip-10-0-1-129 bootkube.sh[4434]: Rendering Cluster Version Operator Manifests...
Dec 17 18:16:28 ip-10-0-1-129 bootkube.sh[4434]: Rendering Kubernetes API server core manifests...
Dec 17 18:16:29 ip-10-0-1-129 bootkube.sh[4434]: Trying to pull quay.io/openshift-release-dev/ocp-v4.0@sha256:5e1f172040c411d4768bf419372c847fd10a2456ce612957cb2acac18c425e28...Getting image source signatures


```

# What you expected to happen?

Expecting to see `4.0.0-7` and the layers below

```
skopeo inspect docker://quay.io/openshift-release-dev/ocp-release:4.0.0-7
{
    "Name": "quay.io/openshift-release-dev/ocp-release",
    "Tag": "4.0.0-7",
    "Digest": "sha256:3e70b2d2004c9335dabc24d6259c5b03739fd86eae435c191ee2b8592e86efec",
    "RepoTags": [
        "4.0.0-0",
        "4.0.0-1",
        "4.0.0-2",
        "4.0.0-3",
        "4.0.0-5",
        "4.0.0-4",
        "4.0.0-6",
        "4.0.0-7"
    ],
    "Created": "2018-12-15T06:41:33.392131088Z",
    "DockerVersion": "1.13.1",
    "Labels": {
        "io.openshift.release": "4.0.0-7",
        "io.openshift.release.base-image-digest": "sha256:f9585cce1889d934b6f9c8361bb1fcc532235ddc4b88ab8614be40545e6bf5d8"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17",
        "sha256:9afeca73426ec14b331e7968e69e8514225c232ecf782a31c08935c6eebd063c",
        "sha256:8c631e03cd56d716a5966b766ff589b7702b7b643cc41a841f4c84f58fa0c4f6",
        "sha256:0960e51c3ab7e61ef6b9632eeb4e9a01038709c8dc23034b0a015b1e3bc55fe4"
    ]
}

```

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

I've also tried to override the image but that didn't make any difference, am i doing something wrong with this variable ?

`export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="registry.svc.ci.openshift.org/openshift/origin-release:4.0.0-7"`

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Yes, installer releases pin the RHCOS version and release image version.

**Comment by abhinavdahiya** [comment]
> export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="registry.svc.ci.openshift.org/openshift/origin-release:4.0.0-7"

the released installer currently does not support override the release image with `OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE`.

**Comment by DanyC97** [comment]
> Yes, installer releases pin the RHCOS version and release image version.

you mind showing/ pointing me at the code where it does that ? 

> he released installer currently does not support override the release image with OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE

is any other release which does ? cause if not then i'm surprised to hear since your [CI does use](https://github.com/openshift/release/blob/782f40b35d5421c7476e7f910f1f78c9148d80cf/ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml#L240) it or one of your [operator](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/1f215f909f257da585e6d9131410afe52212f56d/README.md#L18)

**Comment by abhinavdahiya** [comment]
here's an example https://github.com/openshift/installer/pull/918

**Comment by DanyC97** [comment]
right and i've seen that before but is [not in master](https://github.com/openshift/installer/blob/master/pkg/asset/ignition/bootstrap/bootstrap.go#L147), the PR was closed w/o getting merged and so i expect to have no pin release image

**Comment by DanyC97** [comment]
oh, very interesting ... thank you for letting me know about this process @abhinavdahiya
