### ISSUE TITLE
Cannot create cluster even after correcting IAM role permissions

### ISSUE THREAD

**Issue by philipho11** [openshift/installer#937]
# Version

```console
$ openshift-install version
./openshift-install v0.7.0

$ ~/.terraform.d/plugins/terraform-provider-libvirt -version  # only needed if you're using libvirt
<your output here>
```

# Platform (aws|libvirt|openstack):

aws

# What happened?
.openshift_install.log partially attached below:

`time="2018-12-18T08:48:38Z" level=error msg="Error: Error applying plan:"
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error msg="4 errors occurred:"
time="2018-12-18T08:48:38Z" level=error msg="\t* module.bootstrap.aws_s3_bucket.ignition: 1 error occurred:"
time="2018-12-18T08:48:38Z" level=error msg="\t* aws_s3_bucket.ignition: Error creating S3 bucket: AccessDenied: Access Denied"
time="2018-12-18T08:48:38Z" level=error msg="\tstatus code: 403, request id: 81372D2B3B26991C, host id: +9FolLA0UZkoO6+Od6rn6AXSXNIGsL24+NLhxuLC8uGtqWOlKna4Sqi+S/vY8JRhS13LXfRktno="
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error msg="\t* module.bootstrap.aws_iam_role.bootstrap: 1 error occurred:"
time="2018-12-18T08:48:38Z" level=error msg="\t* aws_iam_role.bootstrap: Error creating IAM Role osc-bootstrap-role: AccessDenied: User: arn:aws:iam::152735899475:user/ec2-only is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::152735899475:role/osc-bootstrap-role"
time="2018-12-18T08:48:38Z" level=error msg="\tstatus code: 403, request id: d2312634-02a0-11e9-bcf4-756b179e64b7"
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error msg="\t* module.iam.aws_iam_role.worker_role: 1 error occurred:"
time="2018-12-18T08:48:38Z" level=error msg="\t* aws_iam_role.worker_role: Error creating IAM Role osc-worker-role: AccessDenied: User: arn:aws:iam::152735899475:user/ec2-only is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::152735899475:role/osc-worker-role"
time="2018-12-18T08:48:38Z" level=error msg="\tstatus code: 403, request id: d230155f-02a0-11e9-a8a8-13ae4bdd7d87"
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error msg="\t* module.masters.aws_iam_role.master_role: 1 error occurred:"
time="2018-12-18T08:48:38Z" level=error msg="\t* aws_iam_role.master_role: Error creating IAM Role osc-master-role: AccessDenied: User: arn:aws:iam::152735899475:user/ec2-only is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::152735899475:role/osc-master-role"
time="2018-12-18T08:48:38Z" level=error msg="\tstatus code: 403, request id: d232fb04-02a0-11e9-921c-bded53ebb833"
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error msg="Terraform does not automatically rollback in the face of errors."
time="2018-12-18T08:48:38Z" level=error msg="Instead, your Terraform state file has been partially updated with"
time="2018-12-18T08:48:38Z" level=error msg="any resources that successfully completed. Please address the error"
time="2018-12-18T08:48:38Z" level=error msg="above and apply again to incrementally change your infrastructure."
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=error
time="2018-12-18T08:48:38Z" level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using terraform"
`

# What you expected to happen?
After adding back the IAM permissions, issue the same command. It still returns error immediately:

./openshift-install create cluster
INFO Consuming "Kubeconfig Admin" from target directory 
FATAL failed to fetch Cluster: failed to load asset "Cluster": "terraform.tfstate" already exists.  There may already be a running cluster 

From AWS console, only security group has been created, no volume, no instance yet.

# How to reproduce it (as minimally and precisely as possible)?
./openshift-install create cluster

# Anything else we need to know?

Enter text here.

# References
#444 

- enter text here.

**Comment by abhinavdahiya** [comment]
> After adding back the IAM permissions, issue the same command. It still returns error immediately:

The errors from you two invocations are different.
first create `time="2018-12-18T08:48:38Z" level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using terraform"` **failed to apply using terraform**
second create after fixing iam `FATAL failed to fetch Cluster: failed to load asset "Cluster": "terraform.tfstate" already exists. There may already be a running cluster` **"terraform.tfstate" already exists. There may already be a running cluster**

> ./openshift-install create cluster
INFO Consuming "Kubeconfig Admin" from target directory
FATAL failed to fetch Cluster: failed to load asset "Cluster": "terraform.tfstate" already exists. There may already be a running cluster

The installer failed because you did not destroy. Please follow https://github.com/openshift/installer#cleanup and retry create

**Comment by philipho11** [comment]
Thanks @abhinavdahiya , now I got to connect tcp 6443 failure. My installer and openshift clusters to be deployed are in two different regions, is it the reason?

INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
INFO API v1.11.0+793dcb0 up                       
INFO Waiting up to 30m0s for the bootstrap-complete event... 
ERROR: logging before flag.Parse: E1219 03:40:35.896913   30383 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARNING RetryWatcher - getting event failed! Re-creating the watcher. Last RV:  
WARNING Failed to connect events watcher: Get https://osc-api.pcbho.net:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp 54.66.136.96:6443: connect: connection refused 
WARNING Failed to connect events watcher: Get https://osc-api.pcbho.net:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp 52.63.59.28:6443: connect: connection refused 
WARNING Failed to connect events watcher: Get https://osc-api.pcbho.net:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp 3.104.32.38:6443: connect: connection refused 
WARNING Failed to connect events watcher: Get https://osc-api.pcbho.net:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp 54.66.136.96:6443: connect: connection refused 
WARNING Failed to connect events watcher: Get https://osc-api.pcbho.net:6443/api/v1/namespaces/kube-system/events?watch=true: dial tcp 52.63.59.28:6443: connect: connection refused

**Comment by DanyC97** [comment]
@philipho11 i suspect the issue you are facing is related to your public domain `pcbho.net`. Can you please confirm that a) is a registered domain and b) provide dig output from the location where you running the installer ?

If your domain is not registered but is only a public R53 zone then that won't work and you will end up in all sorts of issues like described [here](https://groups.google.com/forum/#!topic/openshift-4-dev-preview/Jmt6AK0EJR4)

**Comment by philipho11** [comment]
From installer, I can dig. The domain is registered in R53.

[root@ip-172-31-6-214 ~]# dig osc-api.pcbho.net

; <<>> DiG 9.9.4-RedHat-9.9.4-61.amzn2.1.1 <<>> osc-api.pcbho.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41543
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;osc-api.pcbho.net.		IN	A

;; ANSWER SECTION:
osc-api.pcbho.net.	48	IN	A	3.104.41.241
osc-api.pcbho.net.	48	IN	A	52.65.106.186
osc-api.pcbho.net.	48	IN	A	54.66.186.35

;; Query time: 0 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Wed Dec 19 08:09:17 UTC 2018
;; MSG SIZE  rcvd: 94

Philip

**Comment by DanyC97** [comment]
@philipho11 i've asked about `is a registered domain` ?

If i do 

```
dig osc-api.pcbho.net

; <<>> DiG 9.10.6 <<>> osc-api.pcbho.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3924
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;osc-api.pcbho.net.		IN	A

;; AUTHORITY SECTION:
pcbho.net.		900	IN	SOA	ns-98.awsdns-12.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 45 msec
;; SERVER: 2001:420:464d:2000::a#53(2001:420:464d:2000::a)
;; WHEN: Wed Dec 19 09:32:36 GMT 2018
;; MSG SIZE  rcvd: 126

```

If i go and check the domain is not available 

<img width="1023" alt="domain" src="https://user-images.githubusercontent.com/7383422/50212249-796f4080-0372-11e9-8c5a-1e1c20f726d2.png">

**Comment by eparis** [comment]
It appears there were numerous issues but nothing further actionable for the installer. So I am closing this issue.
