### ISSUE TITLE
4kB ignition data limit for {master,worker}.ign in .openshift_install_state.json 

### ISSUE THREAD

**Issue by jmencak** [openshift/installer#938]
# Version

```console
$ git describe
v0.7.0-master-6-g8f02020b
$ ~/.terraform.d/plugins/terraform-provider-libvirt -version  # only needed if you're using libvirt
Compiled against library: libvirt 4.7.0
Using library: libvirt 4.7.0
Running hypervisor: QEMU 3.0.0
Running against daemon: 4.7.0
```

# Platform libvirt

# What happened?
I tried to customize master/worker ignition files to add a CA file to `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` and the base64 data for `{master/worker}.ign` was cut to 4096B in  `$cluster/.openshift_install_state.json` 

# What you expected to happen?
The `{master,worker}.ign` data not to be cut to 4kB.

# How to reproduce it?

```
$ cluster=cluster-0
$ bin/openshift-install create ignition-configs --dir=$cluster --log-level=debug 2>&1 | tee install.log
$ # edit the generated $cluster/*.ign file to make them larger by adding your own CA file for example to /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
$ bin/openshift-install create ignition-configs --dir=$cluster --log-level=debug 2>&1 | tee install.log
$ # the base64 data for {master/worker}.ign will be cut to 4096B in  $cluster/.openshift_install_state.json 
```

**Comment by crawford** [comment]
@jmencak why do you need to add this CA? Is it necessary for bootstrapping (i.e. you are going through a proxy) or is it needed for your workload?

@staebler can you take a look at this truncation?

**Comment by jmencak** [comment]
@crawford I needed to add this CA for my workload.

@staebler , cannot reproduce it either now.  Thanks for looking into this, closing the issue.

**Comment by crawford** [comment]
@jmencak you'll want to use the in-cluster facilities to add additional folks to your hosts. That will allow you to rotate that CA over time. Modifying the Ignition Configs in the manner presented here won't let you do that. I don't think we have docs on this topic yet, but you'll eventually want to use the Machine Config Operator to do this.
