### ISSUE TITLE
libvirt install fails booting bootstrap & master-0 

### ISSUE THREAD

**Issue by dcbw** [openshift/installer#953]
v0.7.0-master-52-ga2e193ab5b9501f7ed2758856bc3ae2f24c21a82

The disk images that ignition creates (eg /var/lib/libvirt/images/test-master-0) apparently aren't bootable. The VMs show this on their console:

```
Booting from hard disk...
Boot failed: could not read the boot disk

No bootable device.
```

Full log is http://people.redhat.com/dcbw/openshift-installer-libvirt.txt

**Comment by sjenning** [comment]
@RobertKrawitz and @sallyom where hitting this.  Something related to the terraform plugin I think.

**Comment by dcbw** [comment]
Yeah, that got me further.  Anyone know the VM login offhand? The Kube API is not up and I'd like to poke around and debug it inside the VM.

**Comment by dcbw** [comment]
Also I could swear some documentation told me to "GOBIN=~/.terraform.d go get XXXX" for terraform but I can't find that anymore. Maybe that documentation should be changed?

**Comment by RobertKrawitz** [comment]
login: kubeadmin
password: $(cat auth/kubeadmin-password)

**Comment by RobertKrawitz** [comment]
There was documentation to GOBIN=...  That's the step that you need to *not* take now.

**Comment by wking** [comment]
Sounds like this is fixed.  Please re-open or comment if you still have issues.

**Comment by patilsuraj767** [comment]
Hello,
I am facing the same issue. openshift-installer is able to create the bootstrap and master VM, but when I open the console of VM I see the same message. 

openshift_install.log  => https://pastebin.com/XcfpH87V

```
[root@dell-r430-18 openshift]# ./installer/bin/openshift-install version
./installer/bin/openshift-install unreleased-master-2131-g0ee8c541dadabaf29cf287cc0d4a4b4544e16970
built from commit 0ee8c541dadabaf29cf287cc0d4a4b4544e16970
release image registry.svc.ci.openshift.org/origin/release:4.3

[root@dell-r430-18 openshift]# du -sh /root/.cache/openshift-install/libvirt/image/4363e29a3b233b2f3addf8bef1514fcc 
735M	/root/.cache/openshift-install/libvirt/image/4363e29a3b233b2f3addf8bef1514fcc

[root@dell-r430-18 openshift]# file /root/.cache/openshift-install/libvirt/image/4363e29a3b233b2f3addf8bef1514fcc 
/root/.cache/openshift-install/libvirt/image/4363e29a3b233b2f3addf8bef1514fcc: gzip compressed data, was "rhcos-43.81.201911081536.0-qemu.x86_64.qcow2", last modified: Fri Nov  8 15:43:04 2019, from Unix, original size 2105212928
```

I tried this - `rm -rf ~/.terraform.d` but honestly in my case this `~/.terraform.d` directory never gets created.
