### ISSUE TITLE
Include version number in release filename

### ISSUE THREAD

**Issue by brianredbeard** [openshift/installer#965]
# Version

```$ ./openshift-install-linux-amd64\ \(1\) version
./openshift-install-linux-amd64 (1) v0.7.0
```

To minimize confusion with work over time, please include the version number within the release filename.

**Comment by wking** [comment]
Won't having multiple installer versions installed in parallel be a rare corner case?  I'd expect most users to only have a single `openshift-install`.

Also in the "how to publish the release binary?" space: #807.

**Comment by wking** [comment]
Can you provide more details on your use-case and why the lack of version numbers is causing a problem?

**Comment by jeremyeder** [comment]
I'm not super religious about this, but had I seen that, I probably would have retweeted :-)

My reasoning as I wrote on slack: I keep them around for convenience, in case i need to go back - you know the newest one isnt always working/best/introduces something im not ready for

**Comment by brianredbeard** [comment]
To answer the lack of version numbers causing a problem,I just downloaded [`v.0.16.0`](https://github.com/openshift/installer/releases/tag/v0.16.0).  This is now what I'm looking at:

```
$ ls -1tr ~/Downloads/openshift-install-linux-amd64*
'/home/bharrington/Downloads/openshift-install-linux-amd64 (1)'
'/home/bharrington/Downloads/openshift-install-linux-amd64 (2)'
/home/bharrington/Downloads/openshift-install-linux-amd64
'/home/bharrington/Downloads/openshift-install-linux-amd64 (3)'
'/home/bharrington/Downloads/openshift-install-linux-amd64 (4)'
'/home/bharrington/Downloads/openshift-install-linux-amd64 (5)'
```

At the same time, I had Terraform issues when destroying clusters (back in January) when I did not have the _same_ version of the installer available, thus the software has lead me to a place where I don't trust that it's safe to remove the old versions as I'll likely need them.

**Comment by DanyC97** [comment]
@wking my 0.002$ - even in openshift-ansible/ origin rpms we published onto CentOS repos we had  version in it - see [example](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/)

**Comment by smarterclayton** [comment]
This is covered under the new release tooling that will create version numbers.

**Comment by DanyC97** [comment]
> This is covered under the new release tooling that will create version numbers.

excellent news @smarterclayton , any pointer where the code might be (if exist today)? thanks !

**Comment by abhinavdahiya** [comment]
> This is covered under the new release tooling that will create version numbers.

/close
