### ISSUE TITLE
Include newline / carriage return at the end of the pull secret

### ISSUE THREAD

**Issue by brianredbeard** [openshift/installer#966]
Version 0.7

When following the directions at (https://cloud.openshift.com/clusters/install) there is an option to download the pull secret.  The pull secret does not include a newline and thus increases the complexity of retrieving the pull secret to supply to the installer.

**Comment by crawford** [comment]
I don't follow. Can you show me your invocation?

**Comment by brianredbeard** [comment]
This is unrelated to the invocation of the installer and is a related UX issue to the pull secret generated for use by the installer.

**Comment by brianredbeard** [comment]
Sure. Just tell me what repo is appropriate for the server side of the
installer consumables.

**Comment by wking** [comment]
After fixing some bugs in my upstream PR (I'm not very good at JSX ;), it has landed, and is now live in production.

/close

**Comment by wking** [comment]
Prow seems to be sleeping and missed my `/close`.
