### ISSUE TITLE
failed installation when trying to delete bootstrap

### ISSUE THREAD

**Issue by brianredbeard** [openshift/installer#968]
# Version

```console
$ openshift-install version
0.7
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

The cluster didn't install correctly then failed with an obtuse error which provides no usable data for the user to proceed to next steps.

# What you expected to happen?

I expected to have a working cluster.

# How to reproduce it (as minimally and precisely as possible)?

1. Run installer
2. ...
3. Profit

```console
$ ./openshift-installer create cluster
...

INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
INFO API v1.11.0+793dcb0 up                       
INFO Waiting up to 30m0s for the bootstrap-complete event... 
ERROR: logging before flag.Parse: E1220 15:27:27.661712   13335 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARNING RetryWatcher - getting event failed! Re-creating the watcher. Last RV: 2636 
INFO Destroying the bootstrap resources...        
FATAL failed to copy terraform.tfvars to the temporary directory: open terraform.tfvars: no such file or directory 
```
[.openshift_install.log](https://github.com/openshift/installer/files/2700998/default.openshift_install.log)

**Comment by staebler** [comment]
@brianredbeard Did you run `openshift-install` twice? If so, was it sequentially, or were both executions running concurrently?

**Comment by staebler** [comment]
From my reading of the log file, one run of `openshift-install` started at 2018-12-20T15:09:09-08:00 and failed at 2018-12-20T15:15:36-08:00, and a second run of `openshift-install` started at 2018-12-20T15:15:14-08:00 and failed at 2018-12-20T15:27:34-08:00. So, the second run started 5 seconds after the first one started and 22 before the first one finished.

**Comment by brianredbeard** [comment]
@staebler The installations were executed sequentially.

In the case of https://github.com/openshift/installer/issues/968#issuecomment-449462613 this occurred because the installation was run without the correct environment variables set.  It would make sense that, the second attempt at the install would have been kicked off about 5 seconds later (roughly the time needed to request an STS token, set the environment variables and re-run the installer).

Hailing @abhinavdahiya as he watched me run through this.

**Comment by eparis** [comment]
The logs don't seem to show much to go on, other than the runs seem parralellized, which we know would be problematic. If you can still reproduce please open a bugzilla under the installer component with the updated version and full logs.
