### ISSUE TITLE
libvirt: coreos image is saved to memory(?) causing huge memory usage (until failure)

### ISSUE THREAD

**Issue by mykaul** [openshift/installer#975]
# Version
commit hash 5e7b36d6351c9cc773f1dadc64abf9d7041151b1

```console
$ openshift-install version
<your output here>
```
bin/openshift-install v0.8.0-master-2-g5e7b36d6351c9cc773f1dadc64abf9d7041151b1
# Platform (aws|libvirt|openstack):
libvirt
# What happened?

When downloading the coreos image, it apparently writes it into memory(?), so the installer is using gigs and gigs of resident RAM until it blows up.

See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?
Download in chunks and save to disk?

# How to reproduce it (as minimally and precisely as possible)?
Always - to me.

```console
$ your-commands-here
```
[ykaul@ykaul installer]$ bin/openshift-install create cluster
? SSH Public Key /home/ykaul/.ssh/id_rsa.pub
? Platform libvirt
? Libvirt Connection URI qemu+tcp://192.168.122.1/system
? Base Domain ykauldom
? Cluster Name ykaulcls
? Pull Secret [? for help] ****************************************************************************************************************************************************************************************INFO Fetching OS image: redhat-coreos-maipo-47.239-qemu.qcow2.gz 
FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get Tfvars: failed to use cached libvirt image: open /home/ykaul/.cache/openshift-install/libvirt/image/a143c801ad1d611be3efaaafcd4ddc3e.tmp: file exists 
[ykaul@ykaul installer]$ rm /home/ykaul/.cache/openshift-install/libvirt/image/a143c801ad1d611be3efaaafcd4ddc3e.tmp
rm: remove write-protected regular file '/home/ykaul/.cache/openshift-install/libvirt/image/a143c801ad1d611be3efaaafcd4ddc3e.tmp'? y
[ykaul@ykaul installer]$ bin/openshift-install create cluster
? SSH Public Key /home/ykaul/.ssh/id_rsa.pub
? Platform libvirt
? Libvirt Connection URI qemu+tcp://192.168.122.1/system
? Base Domain ykauldom
? Cluster Name ykaulcls
? Pull Secret [? for help] ***************************************************************************************
X Sorry, your reply was invalid: invalid character '/' looking for beginning of value
? Pull Secret [? for help] ****************************************************************************************************************************************************************************************INFO Fetching OS image: redhat-coreos-maipo-47.239-qemu.qcow2.gz 
^C
[ykaul@ykaul installer]$ ^C
```
# Anything else we need to know?

Enter text here.

# References

<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #6017
-->

- enter text here.

**Comment by mykaul** [comment]
I can only assume it's something with the http client ?
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body

**Comment by mykaul** [comment]
At least a consistent leak is happening (with debug enabled) @ 
```
INFO Fetching OS image: redhat-coreos-maipo-47.239-qemu.qcow2.gz 
DEBUG Unpacking OS image into "/home/ykaul/.cache/openshift-install/libvirt/image/a143c801ad1d611be3efaaafcd4ddc3e"... 

```

**Comment by wking** [comment]
Dup of #610.

/close
