### ISSUE TITLE
Enhancement request: compress rhcos qemu images with xz, instead of gz

### ISSUE THREAD

**Issue by mykaul** [openshift/installer#976]
You can save ~25% of the file download time (and size).
Example:
```
[ykaul@ykaul image]$ du -ch *
657M	a143c801ad1d611be3efaaafcd4ddc3e.gz
493M	a143c801ad1d611be3efaaafcd4ddc3e-xz.xz
1.2G	total
```

The download experience will be better. I assume decompression will take slightly longer.

**Comment by wking** [comment]
The installer just consumes these images, we don't generate them.  If you want to get alternative (or additional) compression schemes, file [an openshift/os issue][1].

/close

[1]: https://github.com/openshift/os/issues

**Comment by gbraad** [comment]
Are you sure? If in future XZ would be chosen, targeting a local hypervisor like Hyper-V this would have to be decompressed by the installer (just like for the libvirt provider, right?)

**Comment by mykaul** [comment]
I think we need to be friendly to the provider. Libvirt runs under Linux and qcow2 could be easily decompressed using xz under Linux. We don't need to compress via XZ different images (for hyper-V for example), just qcow2.
