### ISSUE TITLE
v0.8 release does not show libvirt in platforms

### ISSUE THREAD

**Issue by Jooho** [openshift/installer#979]
# Version

```console
$ ./openshift-installer version
./openshift-installer v0.8.0

```

# Platform (aws|libvirt|openstack):
libvirt

# What happened?

When I try to execute 
```
./openshift-installer create cluster --dir ./initial --log-level=debug
```
SSH Public key is ok but platform does not show `libvirt`. There are only aws/openstack

![image](https://user-images.githubusercontent.com/2375181/50607875-c6860300-0e98-11e9-8bb0-bfc81799838f.png)

# What you expected to happen?

It should show `libvirt`

# How to reproduce it (as minimally and precisely as possible)?

```console
./openshift-installer create cluster --dir ./initial --log-level=debug

```

# Anything else we need to know?

I am sure v0.7 work fine. Even though I build it myself, the result is the same.

# References

- enter text here.

**Comment by abhinavdahiya** [comment]
Can you make sure you are building `v0.8.0` using the correct tags. https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#build-and-run-the-installer

more info: https://github.com/openshift/installer/pull/955

**Comment by wking** [comment]
The tag change was also [mentioned in the release notes][1], which are (hopefully :p) useful reading for folks changing installer versions.

[1]: https://github.com/openshift/installer/blame/v0.8.0/CHANGELOG.md#L41-L46

**Comment by Jooho** [comment]
@abhinavdahiya 

Oh... the TAG is changed... When I build it by myself, now I can see `libvirt` but I assume the release version should have `libvirt`. is it intended not to include libvirt from release binary?

**Comment by Jooho** [comment]
@wking 
Thanks for the explanation.  

I am trying to write a blog to help people who want to try openshift 4 on libvirt with released openshift-installer. But sound like,  who want to install OCP4 on KVM, they must build an installer with the TAG first, right? um... I am not sure this is good or not but one thing that I feel is ... it is a little bit difficult to try OCP 4 for who don't know how to build golang. Even though people who are familiar with golang, it is hassle steps.  

I think I need to create ansible playbook for build `openshift-installer` for them on top of Eric's one.

**Comment by crawford** [comment]
As @wking mentioned, libvirt is for OpenShift developers only. Users of OpenShift can test out 4.0 by using AWS.

**Comment by Jooho** [comment]
@crawford  @wking 

Thanks! I am closing this ticket.
