### ISSUE TITLE
v0.8 installs on AWS always get a throttling error

### ISSUE THREAD

**Issue by mffiedler** [openshift/installer#981]
# Version
v0.8 (downloaded binary from try.openshift.com)

```console
$ openshift-install version
./openshift-install-linux-amd64 version
./openshift-install-linux-amd64 v0.8.0
```

# Platform (aws|libvirt|openstack):

aws

# What happened?
./openshift-install-linux-amd64  create cluster
? SSH Public Key /home/fedora/.ssh/libra.pub
? Platform aws
? Region us-west-2
ERROR list hosted zones: Throttling: Rate exceeded
        status code: 400, request id: 942ed9e4-0ed2-11e9-b8e1-6927c728939c
? Base Domain devcluster.openshift.com
? Cluster Name mffiedler
? Pull Secret [? for help] ******************************************************************************************************************INFO 
Creating cluster...      

Ignoring the error seems to be OK - the install finished successfully.

**Comment by wking** [comment]
More on this in #957 and #960.  We still need [a more efficient teardown][1] to reduce Route 53 throttling in busy AWS accounts.

[1]: https://github.com/openshift/installer/issues/957#issuecomment-449049193

**Comment by wking** [comment]
I'm guessing this was actually #1014, so I'm going to close it.  Please comment if you can still reproduce with code that includes #1014.  More efficient teardown would still be nice, and I've just floated #1039 with a mostly-complete destroy reroll to move in that direction.

/close
