### ISSUE TITLE
Provide alternative to 'oc cluster up'

### ISSUE THREAD

**Issue by gustavonalle** [openshift/installer#994]
Since it was removed on 4.0.0.Alpha1, it'd be nice to have something that could start a cluster using only docker without the need for virtualization.

**Comment by crawford** [comment]
We aren't going to support this. There is just too much deviation between the docker-based cluster and a production one. Users will be able to make use of some ongoing development (I don't think anything has been announced yet) that uses hypervisors to create VMs to run the cluster. In the meantime, sufficiently motivated users can try building the installer with libvirt support and using that locally.

/close

**Comment by gustavonalle** [comment]
The idea of pure docker cluster is to get a quick running cluster for **development** and **test** purposes, so it is by definition not close to production: no need for real SSL certificates, multi-node clusters, DNS server, high availability and so on. 

It just needs to be easy to launch (one line, only requirement is Docker), so it can even be used in travis continuous integrations builds.

The current installer does not tackle the use cases above, and using virtualization is cumbersome and add extra overhead.
