### ISSUE TITLE
Allow for allocation of custom key/value pair for tagging

### ISSUE THREAD

**Issue by brianredbeard** [openshift/installer#999]
For a number of reasons (auditing, inventory, cost allocation, etc) organizations define key / value pairs to be assigned to resources.  At CoreOS we used these with https://github.com/coreos/grafiti as well as with https://github.com/cloud-custodian/cloud-custodian to aid in the cleanup of unused resources.

In one use case example:  Without the ability to define a custom set of tags, background utilities like cloud custodian will reap all the resources generated by the installer because they will be missing the tags defined by organization policy.

Related to #458

**Comment by crawford** [comment]
This is already supported - it's just not documented. You can see how we do this [today in CI](https://github.com/openshift/release/blob/734b6e9c999ff1f15a32969f92a6928d8a95135f/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L334).

**Comment by wking** [comment]
> This is already supported - it's just not documented
> This is already supported - it's just not documented.

It's [quasi-documented][1], since currently our install-config docs are basically "drill into [this][2]" :p.

[1]: https://godoc.org/github.com/openshift/installer/pkg/types/aws#Platform
[2]: https://godoc.org/github.com/openshift/installer/pkg/types#InstallConfig

**Comment by eparis** [comment]
closing this issue.
